dags/bqetl_fivetran_google_ads.py
sql/moz-fx-data-shared-prod/google_ads_derived/campaign_names_map_v1/metadata.yaml

This task was added and is not failing due to partitioning configuration.

bug: tweaked date_partition_parameter scheduling settings for campaign_names_map query

---

bigquery_etl/cli/query.py
bigquery_etl/cli/utils.py
bigquery_etl/cli/view.py

Adding `--skip-dryrun` options to some validation commands. This is for adding CI tests to private-bigquery-etl: https://github.com/mozilla/private-bigquery-etl/pull/179 Most of the views/queries in that repo are restricted, so dryruns will always fail. Running some checks is still useful however, e.g. to detect incorrect references in views (which has caused some issues in the past).

Add --skip-dryrun option for CLI validation commands

---

.circleci/config.yml
bigquery_etl/query_scheduling/task.py
dags/bqetl_mobile_activation.py
sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activation_v1/metadata.yaml
sql_generators/feature_usage/templates/metadata.yaml

We currently have a separate `verify-dags-up-to-date` task which runs separately from `generate-dags`. We can move the up-to-date check into the `generate-dags` (this way we'll only need to run the generation once) and with this DAGs can now also reference and schedule generated content (which wasn't available in `verify-dags-up-to-date`)

Move check for dags being up to date after DAGs have been generated

---

sql/moz-fx-data-shared-prod/telemetry_derived/public_data_report_user_activity_v1/query.sql

This goes together with https://github.com/mozilla/firefox-public-data-report-etl/pull/15

Bug 1779585 - fix version comparison in public data report query

---

docs/cookbooks/common_workflows.md
docs/cookbooks/testing.md
docs/mkdocs.yml
docs/reference/recommended_practices.md
requirements.in
requirements.txt

Most nested lists in the generated [BigQuery ETL docs](https://mozilla.github.io/bigquery-etl/) have ended up improperly formatted in HTML, because by default mkdocs requires nested lists to be indented by four spaces in Markdown ([ref](https://github.com/mkdocs/mkdocs/issues/545#issuecomment-316821418)), but most nested lists in our docs haven't been formatted that way (probably because many people are more used to [GitHub Flavored Markdown](https://github.github.com/gfm/), which is more lenient when it comes to list formatting).
To allow more lenient Markdown list formatting in our docs this adds and enables the [mdx_truly_sane_lists](https://github.com/radude/mdx_truly_sane_lists) extension with mkdocs.  Note that some existing nested lists which had been formatted to work with the …

Fix docs formatting

---

sql/moz-fx-data-shared-prod/telemetry/active_users_aggregates/view.sql
sql/moz-fx-data-shared-prod/telemetry/active_users_aggregates_device/view.sql

[DENG 515](https://mozilla-hub.atlassian.net/browse/DENG-515):
There is a need to clean up os grouping in the active_users_aggregates tables. The current logic exists in lookml and should be moved into big query views instead.
`Active_users_aggregates_attribution` view was not updated since `os` column does not exist in the table.

DENG-515 Added normalized os column to active_users_aggregates tables

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/guardian_apple_events_v1/query.sql
sql/moz-fx-data-shared-prod/subscription_platform/apple_subscriptions/view.sql
sql/moz-fx-data-shared-prod/subscription_platform/nonprod_apple_subscriptions/view.sql
sql/mozfun/iap/parse_apple_event/udf.sql

This requires updating historical subscription ids with the following DML:
<details>
<summary>migration.sql</summary>
```
UPDATE
`moz-fx-data-shared-prod`.mozilla_vpn_derived.active_subscription_ids_v1
SET
subscription_id = migration.original_transaction_id
FROM
(
SELECT DISTINCT
CAST(id AS STRING) AS legacy_subscription_id,
original_transaction_id,
FROM
(
SELECT
id,
mozfun.iap.parse_apple_receipt(provider_receipt_json) AS apple_receipt,
FROM
`moz-fx-data-shared-prod`.mozilla_vpn_external.subscriptions_v1 AS subscriptions
WHERE
-- Subscriptions migrated to fxa no longer have subscriptions.provider = "APPLE"
provider_receipt_json IS NOT NULL
AND JSON_VALUE(provider_receipt_json, "$.receipt.bundle_id") = "org.mozilla.ios.FirefoxVPN"
-- Exclude duplicate subscriptions rejected by FxA …
```

Don't use legacy subscription ids from guardian for apple subscriptions

---

sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/schema.yaml

Bug 1811572 add new column to schema_error_counts

---

sql/moz-fx-data-shared-prod/mozilla_vpn/deletion_request/view.sql
sql/moz-fx-data-shared-prod/mozilla_vpn/main/view.sql

This currently causes queries against this view to fail because of a field mismatch in the `client_info` subfields.
This field was recently added, but will only ever be available on Windows (for obvious reason).
Nonetheless the column exists everywhere.

Bug 1813015 - Account for new (optional) client_info field in VPN view

---

docs/cookbooks/testing.md

@lelilia following up on our discussion last week - narrowing down `testpaths` speeds up single test execution. On my machine it cuts ~1 min from the run time.

Add a documentation note on faster single test execution

---

dags.yaml
dags/bqetl_event_rollup.py
sql/moz-fx-data-shared-prod/telemetry_derived/event_types_history_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/event_types_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/events_daily_v1/metadata.yaml
sql_generators/events_daily/templates/event_types_history_v1/templating.yaml
sql_generators/events_daily/templates/event_types_v1/templating.yaml
sql_generators/events_daily/templates/events_daily_v1/templating.yaml

I've paused the DAG in Airflow per https://bugzilla.mozilla.org/show_bug.cgi?id=1805722#c10, this adds a documentation note. We'll revisit this soon when we'll have concrete plans for handling event analysis.

Bug 1805722 - Deprecate desktop event rollup

---

.github/workflows/push-to-upstream.yml

Since Jeff Klukas is no longer at Mozilla we should stop relying on his [git-push-fork-to-upstream-branch](https://github.com/jklukas/git-push-fork-to-upstream-branch) repo.  I've forked that repo into the `mozilla` GitHub org, and this updates the `push-to-upstream` workflow to use [our own fork of it](https://github.com/mozilla/git-push-fork-to-upstream-branch).
---

Use Mozilla-owned fork of `git-push-fork-to-upstream-branch` for `push-to-upstream` workflow

---

dags/bqetl_ctxsvc_derived.py
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_check_v1/metadata.yaml
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_check_v1/query.sql

This adds a check to make sure there are no empty partitions for `contextual_services_derived.event_aggregates_v1`. If empty partitions occur, for example after a backfill goes wrong then the Airflow task will fail and list affected partitions.
I can't test it on the actual dataset since I don't have permissions, so this might be a good time to hand this over to someone on the contextual services team who can test this.

Add check for contextual_services_derived.event_aggregates_v1

---

sql/moz-fx-data-shared-prod/fivetran_costs_derived/monthly_costs_v1/schema.yaml

The provided schema doesn't match with what is deployed

Fix data type for fivetran_costs_derived.montly_costs

---

dags/bqetl_analytics_aggregations.py
dags/bqetl_search_dashboard.py
sql_generators/glean_usage/templates/metrics_templating.yaml

This PR complements `org_mozilla_ios_klar.metrics` to align with the other browsers. It's adding `uri_count` & `is_default_browser`, which follows [same approach of Firefox iOS](https://github.com/mozilla/bigquery-etl/blob/8913f6543eced30d502f67c298a881d35d44b2d7/sql/moz-fx-data-shared-prod/firefox_ios_derived/metrics_clients_daily_v1/query.sql#L9).

DENG-601 Add is_default_browser and uri_count for Klar iOS

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v1/metadata.yaml

Bug(FXA-6695): ensuring fxa_users_last_seen is not run until fxa_users_daily task completes

---

sql_generators/glean_usage/common.py

I could reproduce the issue described in https://mozilla.slack.com/archives/C01E8GDG80N/p1675877827569069 and earlier with`treeherder`. The generation logic checks if referenced tables in generated queries exist and aborts if they don't. However, if a dataset that is referenced does not exist dryrun returns a different error code which was considered as "all references exist" (even though they didn't). This resulted in some tables and the `dataset_metadata.yaml` getting created, which resulted in the dataset actually being deployed. So in the next run the dryrun did get the correct error code for missing references and deleted the generated datasets again.
This should fix this issue.
cc @whd

Prevent glean_usage generation if referenced dataset doesn't exist

---

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_tables_inventory_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_tables_inventory_v1/query.py

[DENG-685](https://mozilla-hub.atlassian.net/browse/DENG-685):
* partition filter requirement was removed given small table size (~100MB)
* It was discovered that `submission_date` captured from airflow is always one day less than today’s date. Filters are added to remove creation dates greater than submission_date.
[DENG-685]: https://mozilla-hub.atlassian.net/browse/DENG-685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DENG-685 Fix tables inventory dates

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v2/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v2/schema.yaml

This is because previous partition field could contain records for two different days.

bug(1816398): fxa_users_services_first_seen_v2 partition_field changes to submission_date

---

sql/moz-fx-data-shared-prod/udf_js/bootstrap_percentile_ci/udf.sql

The publishing logic expects the format `library = "...."`

Fix UDF library reference format

---

.circleci/config.yml

I accidentally deleted the SSH key for deploying docs 🤦‍♀️. Adding it back

Update SSH doc deploy key

---

dags/bqetl_campaign_cost_breakdowns.py
sql/moz-fx-data-shared-prod/fenix_derived/google_ads_campaign_cost_breakdowns_v1/query.sql

We can't load into a partitioned table if the results are already sorted.

Remove order by clause

---

docs/reference/airflow_tags.md

As Sean pointed out, the tag provided in the docs was incorrect. This change fixes that.

Fixed typo in airflow_tags.md

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v2/query.sql

Two main changes
- logic: using correct field when filtering for existing records to avoid existing combinations (user/service) from making into the table twice. This is an important changes because the `first_service_flow_timestamp` can have a different date date value than submission_date which leads to the final table containing duplicate entries. 
- updated the alias for `new_entries` to make the query more consistent and easier to follow.

bug: fxa_users_services_first_seen_v2 not filtering previous records correctly

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/events_daily_v1/init.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/events_daily_v1/query.sql
sql_generators/events_daily/templates/events_daily_v1/query.sql
sql_generators/events_daily/templates/events_daily_v1/templating.yaml

For [VPN-3934](https://mozilla-hub.atlassian.net/browse/VPN-3934) "_Update our looker dashboards to filter by Glean SDK type_".
This will require rebuilding the `moz-fx-data-shared-prod.mozilla_vpn_derived.events_daily_v1` table.
CC @brizental 
---
[VPN-3934]: https://mozilla-hub.atlassian.net/browse/VPN-3934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `telemetry_agent` column to VPN `events_daily` table (VPN-3934)

---

.circleci/config.yml

Update CircleCI config to use unit tests from `telemetry-airflow` instead of running docker-compose. This significantly shortens CircleCI job `validate-dags` runtime from 5-6 minutes down to around 2 minutes.
Current implementation requires the job's executor to match `telemetry-airflow`'s python version. There's is a fairly low risk we encounter issues when updating `telemetry-airflow` to a new python version if we don't update the executor version in this CI config **_IF_** _there are breaking changes in key packages_. 
A possible alternative is to pull the latest `telemetry-airflow` image, mount the generated DAGs as a volume and run a pytest command. This will probably be the long-term solution as we would not need to pull a git repo and install python dependencies. I would probably …

chore(ci): use unit tests from telemetry-airflow

---

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/query.sql

This addresses two problems that led to over-counting visits in some cases:
1. Some valid interactions are not tagged with their newtab_open_source. This led to some visits having one interaction with a null `visit_id` and another with the actual `visit_id`
2. Some visits come from tab-preloading. We identify these by the fact that they do not have a `newtab.opened` event which has `newtab_open_source` and `newtab_visit_started_at` as extras OR any interactions. 
As a side note, we remove interactions without a `visit_id`, these won't be valid in any case.
See analysis of difference [here](https://sql.telemetry.mozilla.org/queries/90564/source) and broader context [here](https://docs.google.com/document/d/1chY8z6noN5CF3k8YX2TPThLRF3bTGuUR93zUZR8nX1Q/edit#) and …

Sidefill newtab.opened and filter invalid events in newtab_interactions

---

bigquery_etl/routine/publish_routines.py

Fixes https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/19235/workflows/e8f9dfd8-e019-4fe7-9e02-6c500596d8cd/jobs/184664
To deploy UDFs to stage for testing the names are fully qualified with "`" around the identifier. The UDF publishing logic currently doesn't handle this case. The PR should fix that

Fix publishing UDFs with fully qualified identifiers

---

bigquery_etl/routine/parse_routine.py

This fixes the UDF tests. The regex didn't correctly match fully qualified UDF names that include projects.

Fix UDF test regex matching

---

sql/moz-fx-data-shared-prod/subscription_platform/apple_subscriptions/view.sql

Somehow the [purchase date](https://developer.apple.com/documentation/appstoreservernotifications/purchasedate) can sometimes be a few seconds before the "[original purchase date](https://developer.apple.com/documentation/appstoreservernotifications/originalpurchasedate)".
---

For Apple subscriptions include the minimum purchase date as a subscription period start time

---

dags.yaml
dags/bqetl_pocket.py

Because the files from Pocket may not always be available on time (e.g. [bug 1818043](https://bugzilla.mozilla.org/show_bug.cgi?id=1818043)).
---

Retry `bqetl_pocket` DAG tasks for 10 hours rather than 1 hour (bug 1818043)

---

.circleci/config.yml

Probe-scraper takes at most 4 hours to run.
If those schemas get deployed, then this build will cache the latest stable schemas and make them available in the container.

Run a nighly CI workflow after probe-scraper

---

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_tables_inventory_v1/schema.yaml

This will fix the schema error introduced from #3638 causing an airflow DAG failure ([1821055](https://bugzilla.mozilla.org/show_bug.cgi?id=1821055)).

DENG-590: Fixed inventory schema

---

sql_generators/active_users/templates/desktop_query.sql

[DENG-514](https://mozilla-hub.atlassian.net/browse/DENG-514): Updated `os_version` column to use [windows_version_info udf](https://github.com/mozilla/bigquery-etl/blob/main/sql/mozfun/norm/windows_version_info/udf.sql) to capture the correct windows version.
The following table is created for validations:  `moz-fx-data-shared-prod.analysis.wchan-deng-514-windows`
[DENG-514]: https://mozilla-hub.atlassian.net/browse/DENG-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 DENG-514 capture windows version in active users aggregates

---

.circleci/config.yml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_oauth_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/incline_executive_v1/metadata.yaml
sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v2_external/metadata.yaml
sql/moz-fx-data-shared-prod/static/fxa_amplitude_export_users_daily/metadata.yaml
sql/moz-fx-data-shared-prod/static/fxa_amplitude_export_users_last_seen/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_content_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_gpu_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_parent_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_boolean_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_histogram_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_scalar_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_aggregates_new_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_bucket_counts_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_probe_counts_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_scalar_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_scalar_probe_counts_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/core_clients_first_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/event_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/experiments_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/glam_user_counts_extract_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/glam_user_counts_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/histogram_percentiles_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/main_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/public_data_report_user_activity_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/scalar_percentiles_v1/metadata.yaml

Adds metadata.yaml files for queries inside telemetry_derived that are missing one.
Metadata.yaml added include the following 3 keys with placeholder values:
- `friendly_name` - this is set to dataset name + table name
- `description` - set to `[DESCRIPTION_MISSING]`, this needs to be populated by the owner (as soon as one is determined)
- `owners` - set to `data-platform-infra-wg@mozilla.com` as we did not want to assign it to people without consulting with them first.
Those values for description and owners will enable us to easily search for metadata files without a description and owner assigned.
Next step is to add a CI check to ensure metadata.yaml file is added when a new query is created and contains those three keys.
related: https://github.com/mozilla/bigquery-etl/pull/3655 …

issues(3416): added missing metadata.yaml files inside moz-fx-data-shared-prod

---

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/schema.yaml

RE: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/761 adds missing schema entry

Bug 1822250 update schema to include enrollment_id

---

sql_generators/active_users/templates/desktop_query.sql

This is a fix for DENG-682 #3609 that set up a derived table and view for firefox desktop acitve users aggregates.  It was discovered that the counts were different between the existing aua table (`moz-fx-data-shared-prod.telemetry_derived.active_users_aggregates_v1`) and the new table (`moz-fx-data-shared-prod.firefox_desktop_derived.active_users_aggregates_v1`).  This PR fixes the `locale` field that attributed to the count differences.
Note there will still be a count difference between the two tables given the recent change in `os_version` field (#3646 )

Fix query for firefox desktop active_users_aggregates

---

sql/moz-fx-cjms-prod-f3c7/cjms_bigquery/flows_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_all_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_oauth_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/funnel_events_source_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/init.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_daily_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_daily_v2/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_daily_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v1/init.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_product_page_to_subscribed_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/fxa_attribution_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/login_flows_v1/query.sql

Whilst working with the FxA event data, it came to my attention that in the context of events and event analysis logic `event_category` is already used. This change aims to avoid those two fields getting confused.

feat(): renamed event_category to fxa_log to avoid confusion with event terminology

---

sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_other_events_overall_v1/view.sql

Used for the experiment enrollments dashboard: https://mozilla.cloud.looker.com/dashboards/216?Experiment=bug-1727596-pref-search-experiment-measuring-the-impacts-of-diffe-release-79-96&Time%20Range%20%5BUTC%5D=28%20day
cc @danielkberry

Expose disqualification and validation_failed counts in experiment_enrollment_other_events_overall_v1

---

dags/bqetl_org_mozilla_firefox_derived.py
sql/moz-fx-data-shared-prod/fenix/client_deduplication/view.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/client_deduplication_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/client_deduplication_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/client_deduplication_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/client_deduplication_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/client_deduplication_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/client_deduplication_v1/query.sql

Details in bug 1822283. The new field is mostly the same as the old one, but without the race condition.

Account for new Ad ID field in client_dedupe ping

---

sql/moz-fx-data-shared-prod/subscription_platform/nonprod_stripe_subscriptions_history/view.sql
sql/moz-fx-data-shared-prod/subscription_platform/stripe_subscriptions_history/view.sql

This is necessary because a Fivetran resync of the Stripe data on 2023-02-24 overwrote/deleted `subscription_history` records ([DENG-754](https://mozilla-hub.atlassian.net/browse/DENG-754)), so we now have 841 subscriptions where their first `subscription_history` record has a `previous_plan_id` (which shouldn't normally be possible).
Also, because we only have the most recent plan change in the Stripe subscription metadata, for any subscriptions that had more than one plan change prior to 2023-02-24 we can no longer tell what those additional previous plan changes were, so it will now appear that each subscription's most recent previous plan prior to 2023-02-24 was in effect from the beginning of the subscription (which may be before that plan was actually created/offered), and this will …

Synthesize `stripe_subcriptions_history` records for previous plan periods (DENG-754)

---

bigquery_etl/dryrun.py

Adds this query to the dry run skip list because it's timing out.

Add clients_first_seen_v1 to dry run skip list

---

.circleci/config.yml
bigquery_etl/cli/query.py
bigquery_etl/dependency.py
bigquery_etl/dryrun.py
bigquery_etl/format_sql/formatter.py
bigquery_etl/format_sql/tokenizer.py
bigquery_etl/pytest_plugin/sql.py
bigquery_etl/routine/parse_routine.py
bigquery_etl/util/common.py
bigquery_etl/view/__init__.py
sql/mozfun/hist/string_to_json/udf.sql
sql_generators/active_users/__init__.py
sql_generators/glean_usage/common.py
tests/cli/test_cli_dependency.py
tests/format_sql/jinja_example/expect.sql
tests/routine/test_parse_routine.py
tests/test_entrypoint.py
tests/test_run_query.py

With this change any `.sql` file will be treated as a Jinja template. Rendering of templates happens before queries are executed, UDFs and views are deployed as well as before a dryrun. The `generated-sql` branch will contain the rendered SQL files.
There is also a new CLI command `bqetl query render` which renders the SQL file templates
Next steps:
* metric-hub integration
* update docs

Support Jinja templating in query files

---

pom.xml

Reverts mozilla/bigquery-etl#3688

Revert "Bump zetasql.version from 2022.08.1 to 2023.03.2"

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v2/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v2/schema.yaml

The primary change introduced by the v2 compared to v1 is that it is now derived from a lower granularity table which contains users/service level granularity (`fxa_users_services_daily_v2`) instead of accessing the events table directly. This should reduce the amount of data we have to process as part of the FxA pipeline and reduced code duplication across different models (for example, only the initial users services table needs to filter for specific events).
- `app_version` - as pointed out by Arkadiusz, this field does not seem to make sense on the user level as it is related to the service used and as the result provides no useful meaning here. Also, it can be accessed via the upstream table `fxa_users_services_daily_v2`.
- `monitor_only` - based on the conversation under this PR it …

feat(DENG-610): added fxa_users_daily_v2 model

---

bigquery_etl/metrics.py
bigquery_etl/util/common.py
requirements.in
requirements.txt
tests/test_dryrun.py
tests/util/test_common.py

Depends on https://github.com/mozilla/metric-config-parser/pull/209
This adds a `metrics.calculate()` function to the Jinja context which allows to get the SQL for referenced metrics and use them in SQL queries.
`metrics.calculate()` is used here to rewrite the SSL ratios query to use available metrics: https://github.com/mozilla/bigquery-etl/pull/3698/files#r1156513857
Docs are under way here: https://github.com/mozilla/bigquery-etl/pull/3697 and will also be added to dtmo

Metric-hub integration

---

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/schema.yaml

Adds `organic_topsite_clicks`, `organic_topsite_impressions`, `topsites_rows` to `newtab_interactions_v1`.
Adding `topsite_position` adds a lot of cardinality to this table, particularly the impressions data. I'll do some tests to see whether this is a huge difference in terms of storage and/or data scanned. This might call for a v2 of this table with more nesting which will unfortunately require unnesting at query time.

DENG-784 - Add organic and rows topsite columns and to newtab_interactions

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v2/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v2/schema.yaml

depends: https://github.com/mozilla/bigquery-etl/pull/3607
---
The main difference between v2 and v1 of this table is that v2 is created using `fxa_users_daily_v2` instead of using the events table directly. This change aims to reduce code duplication and to have a cleaner and more linear flow of data which is a bit easier to reason about. Avoiding going directly to the events table also reduced the amount of data that we need to process for each run.
`Removed`:
- `services_used` - this was a field which was modified on each run and aggregates a list of all services the user has ever used. This feels like a wrong place for this information as it did not include only information related to the first instance of when a user was observed making the table more difficult to reason about. …

feat(DENG-704): added fxa_users_first_seen_v2

---

.circleci/config.yml
bigquery_etl/cli/query.py
bigquery_etl/cli/utils.py
sql/moz-fx-data-shared-prod/mozilla_vpn_external/devices_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_external/subscriptions_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/query.sql

--sql-dir is used in CircleCI for rendering templates but ignored

Add support for --sql-dir option

---

sql/moz-fx-data-shared-prod/monitoring_derived/stable_and_derived_table_sizes_v1/query.py

This job is failing because some table names have dashes `-` in them

Escape table names in stable_and_derived_table_sizes_v1

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_live/view.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_v1/schema.yaml

To match new subscriptions by channels in the dashboards with VPN growth model. 
Refer to  [this comment](https://mozilla-hub.atlassian.net/browse/DS-2814?focusedCommentId=668334) for details. 

[DS-2814]Adding granular event type in channel group proportions table

---

sql/moz-fx-data-shared-prod/telemetry/active_users_aggregates/view.sql

The dag bqetl_artifact_deployment has been failing at the `publish_views` task.
This is caused due to missing  project_id in the view name (not fully qualified)
https://workflow.telemetry.mozilla.org/log?dag_id=bqetl_artifact_deployment&task_id=publish_views&execution_date=2023-04-14T05%3A30%3A00%2B00%3A00

fix the publish_view issue introduced via DENG 710

---

bigquery_etl/cli/stage.py

https://github.com/mozilla/bigquery-etl/pull/3692 introduced a change that broke view deployment due to source table reference not being fully qualified. There was a [test failure](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/20171/workflows/43457535-6cb4-4519-b97d-167f3eb4b706/jobs/196148) that was missed, however the message wasn't obvious there: `ValueError: not enough values to unpack (expected 3, got 2)`.
This adds a check to validate table reference format to be fully qualified and throws an error with a clear message if it's not. …

Validate table references when deploying views

---

sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/additional_deletion_requests_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_focus_derived/additional_deletion_requests_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/additional_deletion_requests_v1/query.sql

to avoid conflict with next airflow run.
I backfilled this yesterday, and when i checked to make sure that new requests were showing up I found that the backfill had been overwritten due to the backfill partition lining up with the next partition to be written by airflow `>_<`

Backfill additional_deletion_requests to yesterday

---

sql/moz-fx-data-shared-prod/udf_js/extract_string_from_bytes/udf.sql
sql/moz-fx-data-shared-prod/udf_js/parse_sponsored_interaction/udf.sql

PR aiming to fix CI `test_sql` step. 
Fixes include the following two udf's:
- parse_sponsoder_interaction
- extract_string_from_bytes
----
Also, run bqetl formatting against the two definitions.

bug(): Fixing parse_sponsoder_interaction and extract_string_from_bytes udfs

---

sql/moz-fx-data-shared-prod/telemetry/releases/view.sql
sql/moz-fx-data-shared-prod/telemetry/releases_latest/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/releases_latest/view.sql
sql/mozfun/norm/extract_version/udf.sql

- Added `major`, `minor`, `patch` fields to the `telemetry.releases` view
- Added `telemetry.releases_latest` view to provide an entry for each day for release and beta channels and what app versions were available that day.

bug(1826384): add telemetry latest releases

---

sql/moz-fx-data-shared-prod/udf_js/parse_sponsored_interaction/udf.sql

bug(): fixing assert in parse_sponsored_interaction checking timestamp value parsed correctly

---

dags/bqetl_analytics_tables.py
dags/bqetl_mobile_activation.py
sql/moz-fx-data-shared-prod/firefox_ios/firefox_ios_clients/view.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/schema.yaml

Change to introduce attribution table for firefox_ios. This is to enable to to analyze effectiveness of our marketing campaigns on the ios platform.
`fenix_derived.firefox_android_clients_v1` was used as the basis and adjusted for firefox_ios.
A test table with the results (for submission_date `2023-04-05`) of this query was created: `tmp.kik_firefox_ios_clients_v1`
Follow-up PRs (introducing more changes to enable this form of analysis):
- https://github.com/mozilla/bigquery-etl/pull/3712
- https://github.com/mozilla/bigquery-etl/pull/3713

feat(DENG-790): Attribution table for firefox ios clients

---

sql/moz-fx-data-shared-prod/udf_js/parse_sponsored_interaction/udf.sql

💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩💩 :trollface: 
follow-up to: https://github.com/mozilla/bigquery-etl/pull/3741
follow-up to: https://github.com/mozilla/bigquery-etl/pull/3742
follow-up to: https://github.com/mozilla/bigquery-etl/pull/3743

bug(): fixing assert in parse_sponsored_interaction checking for null, null string is returned not null value

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/metadata.yaml

This is breaking artifact deploys
Based on the query it seems like the whole table should get overwritten, so we need to remove partitioning metadata

Remove partitioning metadata for firefox_ios_clients_v1

---

sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_suggest_v1/query.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_suggest_v1/schema.yaml
sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_tiles_v1/query.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_tiles_v1/schema.yaml
sql/moz-fx-data-shared-prod/udf_js/parse_sponsored_interaction/udf.sql

The following improvements have been made based on the feedback received ([RS682](https://mozilla-hub.atlassian.net/browse/RS-682?search_id=35def970-f5b5-4bb2-bf73-68e3a7dc431f)
- Remove `send_event` column
- Missing values coded as null (handled in the udf)
- product_version extracted from the string (as the number)

RS 682 - Improvements based on DS feedback

---

Dockerfile

Variable expansion in Docker command flags is [not yet supported](https://github.com/docker/cli/issues/3356#issuecomment-957892224), so since #3754 the `deploy-to-private-gcr` CI jobs have been failing with
```
Step 16/24 : COPY --from=google/cloud-sdk:${CLOUD_SDK_VERSION}-alpine /google-cloud-sdk /google-cloud-sdk
invalid from flag value google/cloud-sdk:${CLOUD_SDK_VERSION}-alpine: invalid reference format
```
---

Fix Google Cloud SDK pin in Dockerfile

---

dags/bqetl_mobile_activation.py
sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v2/query.sql

This is due to the investigation as part of `DENG-790`.

bug(): firefox_ios_derived.new_profile_activation_v2 exlude existing client_id entries

---

sql/mozfun/norm/firefox_android_package_name_to_channel/udf.sql
sql/mozfun/norm/get_windows_info/udf.sql

Fixes a [CI failure](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/20601/workflows/87d515b2-e489-403b-8086-03ba403e7f1b/jobs/201298?invite=true#step-106-94).

Update assert in udf norm.firefox_android_package_name_to_channel

---

bigquery_etl/metadata/parse_metadata.py
tests/data/metadata.yaml
tests/metadata/test_parse_metadata.py

In some cases we have owners that are GitHub identities, e.g.: https://github.com/mozilla/bigquery-etl/blob/5b178559b3f7b9de4ed5f12763b685c29d09d67d/sql_generators/active_users/templates/metadata.yaml#L17-L19 
These aren't always valid labels and currently show up as empty strings in BQ, so we should skip them entirely. ~Also we use emails verbatim as owners in dags so it makes sense here too I think.~

Filter non email owners from labels 

---

.circleci/config.yml

Skip the entire deploy job on non-main branches instead of just some steps. Also remove the tag condition since we're not doing that anymore

Skip deploy jobs on non-main branches

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_v1/schema.yaml

Table deploys are currently failing due to incompatible types.

Fix plan_interval_count schema type for channel_group_proportions_v1

---

dags/bqetl_analytics_tables.py
dags/bqetl_org_mozilla_firefox_derived.py
sql/moz-fx-data-shared-prod/firefox_ios/attributable_clients/view.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/init.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/schema.yaml

This change introduces a new table attributable_clients_v1 for firefox_ios. `fenix_derived.attributable_clients_v1` was used as the basis for this query.
This table will enable us to understand effectiveness of our marketing campaigns on ios.
depends on: https://github.com/mozilla/bigquery-etl/pull/3709

feat(DENG-788): adding firefox_ios.attributable_clients table

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/schema.yaml

This is a direct follow-up to #3712 where an incorrect `schema.yaml` was added. This PR is to fix that.
The table has already been deployed with the correct schema. This is just to make sure the file is correct in in the main branch.

bug(DENG-788): adding first_seen_date to schema.yaml to match with the query.sql file

---

bigquery_etl/dryrun.py

This is due to the views referencing tables located inside our Fivetran project.

feat(DENG-789): added apple_ads namespace views to dryrun skip 

---

sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_suggest_v2/query.sql

The airflow DAG is failing with `product_version has changed type from INTEGER to STRING`.
The PR should fix the issue.

Fix product version type

---

bigquery_etl/docs/mozfun/generate_mozfun_docs.py

This is a fix for #3778, which had a problem checking inputs/outputs before writing to docs file.

fix udf parsing for docs

---

bigquery_etl/query_scheduling/task.py
sql/moz-fx-data-bq-performance/release_criteria/rc_flattened_test_data_v1/query.sql
sql/moz-fx-data-marketing-prod/ga_derived/downloads_with_attribution_v2/query.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_suggest_v2/query.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/request_payload_tiles_v2/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v1/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/structured_detailed_error_counts_v1/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/structured_error_counts_v1/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/telemetry_missing_columns_v2/view.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/query.sql

Implements [RS-722](https://mozilla-hub.atlassian.net/browse/RS-722) to remove [CI error](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/21258/workflows/fde57dfe-620e-4418-aff7-6216ca291b22/jobs/209703) due to printed message.
[RS-722]: https://mozilla-hub.atlassian.net/browse/RS-722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RS-722 Remove task name from printed message in DAG generation

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_first_seen/view.sql

The v1 of this table has not been updated for more than a year now and it does not look like anything is using this view so there shouldn't be any impact.
Checked:
- bigquery-etl
- looker-spoke-default
- looker-hub (some minimal usage, but does not look like this should break anything)

feat(DENG-980): fxa_users_services_first_seen view updated to use v2

---

sql/moz-fx-data-shared-prod/subscription_platform/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/subscription_platform_derived/dataset_metadata.yaml

Plans have changed and they'll only contain data considered Mozilla-confidential.
---

Don't restrict access to the `subscription_platform` datasets

---

bigquery_etl/query_scheduling/task.py
dags/bqetl_fxa_events.py
dags/bqetl_org_mozilla_focus_derived.py
tests/query_scheduling/test_task.py

Airflow's limit for task names seems to be 250 characters ([ref](https://github.com/apache/airflow/blob/2.3.3/airflow/models/baseoperator.py#L754), [ref](https://github.com/apache/airflow/blob/2.3.3/airflow/utils/helpers.py#L56)).
As far as I can tell the 62 character limit was due to Airflow putting task names in Kubernetes pod labels and those label values being limited to 63 characters, which has been [worked around as of Airflow 2.0.1](https://github.com/apache/airflow/issues/13189#issuecomment-779419350) by using [`make_safe_label_value`](https://github.com/apache/airflow/blob/2.3.3/airflow/kubernetes/pod_generator.py#L45) to automatically truncate Kubernetes label values longer than the limit.
The only downside I see is the Kubernetes labels for long task names will be weird in a …

Increase task name limit from 62 characters to 250 characters

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_first_seen/view.sql

Reverts mozilla/bigquery-etl#3870 to unblock LookML generation. This was only merged yesterday so this should be safe to revert.

Bug 1836312 - Revert "feat(DENG-980): fxa_users_services_first_seen view updated to use v2"

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_first_seen/view.sql

rev2 of https://github.com/mozilla/bigquery-etl/pull/3870 due to lookml-generation failing. With this change, it should now work.

feat(DENG-980): fxa_users_services_first_seen view updated to use v2 - rev2

---

bigquery_etl/cli/stage.py

RE CI failures here: https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/21423/workflows/6d84560f-fee7-42ec-9ccb-5537dd22c03d/jobs/211743
There's a `FileNotFoundError` in the following block if `test_file_path` has already been renamed, for example if there's multiple `artifact_files` for the same `test_file_path` (`init.sql`, `query,sql`) in the case above:
```
for test_file_path in test_destination.glob("**/*"):
for test_dep_file in artifact_files:
...
test_file_path.rename(...)
```

During stage don't rename test dependencies that have already been renamed

---

.circleci/config.yml

Previously, we potentially copied the `sql` and `test` files directly into `staged-generated-sql` instead of into the corresponding subdirectories

Fix destination paths when copying stage files in CI

---

bigquery_etl/glam/generate.py
bigquery_etl/glam/templates/latest_versions_v1.sql

GLAM release currently has little data due to bad version number (999). This PR rewrites the `latest_version_v1` template to prevent this from happening again.

Simplify GLAM template for getting latest versions

---

bigquery_etl/cli/stage.py

#3791 changed `bqetl stage` so that replaced table IDs were entirely in quotes, but quoting the entire table ID breaks cases where an unaliased table name is used to qualify a column reference ([example](https://github.com/mozilla/bigquery-etl/blob/cfca76f9c498d6ae0eec4fe2dae08b642d7cd426/sql/moz-fx-data-shared-prod/mozilla_vpn/active_subscription_ids/view.sql#L10-L13)).
Quoting the individual table ID parts separately does not have the same problem.
---

Fix `bqetl stage` table ID quoting

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/init.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/schema.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/fenix.baseline_clients_first_seen.schema.json
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.schema.json
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/org_mozilla_firefox.baseline.schema.json
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_no_first_session/expect.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_no_first_session/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_no_first_session/org_mozilla_firefox.baseline.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_no_baseline/expect.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_no_baseline/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_no_baseline/org_mozilla_firefox.baseline.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_only_metrics_ping/expect.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_only_metrics_ping/org_mozilla_firefox.baseline.yaml

GROWTH-41
Gets latest attribution columns from metrics ping and latest client columns from baseline ping. 
(Most of the diff is adding the baseline schema)

GROWTH-41 Add last_seen columns to firefox_android_clients

---

bigquery_etl/cli/__init__.py
bigquery_etl/cli/query.py

The idea behind adding the `--log-level` flag is to over time tweak some of the logging statements to be debug statements to reduce the amount of noise produced by the query command unless the user explicitly wants to see all output.
Moving away from `print()` to `logging` makes the command output easier to work with and identify the source of the messages.
Example command:
`./bqetl --log-level=debug query my.query query`
The log level setting should now apply across runtime for all of the cli commands.
(part of the great bug throwdown pairing session, so kudos for @lelilia @lucia-vargas-a @akkomar @Iinh for participating and coming up with ideas to improve the command's output)
----
An alternative approach would be to have a `--verbose` flag to print all messages which could be excluded …

feat(): added support for `--log-level` to bqetl query command and using logging instead of print()

---

bigquery_etl/cli/query.py
bigquery_etl/metadata/parse_metadata.py
sql/moz-fx-data-shared-prod/static/data_incidents_v1/metadata.yaml
sql/moz-fx-data-shared-prod/static/monitoring_distinct_docids_notes_v1/metadata.yaml
sql/moz-fx-data-shared-prod/static/monitoring_missing_columns_notes_v1/metadata.yaml
sql/moz-fx-data-shared-prod/static/monitoring_missing_document_namespaces_notes_v1/metadata.yaml
sql/moz-fx-data-shared-prod/static/monitoring_schema_errors_notes_v1/metadata.yaml

The airflow table deployment has been failing for some tables with the following error
https://workflow.telemetry.mozilla.org/log?dag_id=bqetl_artifact_deployment&task_id=publish_new_tables&execution_date=2023-06-06T05%3A30%3A00%2B00%3A00
Upon investigating we found that a recent PR #3881 has change the way we parse the metadata for external config for google sheets. We have been using `"GOOGLE_SHEET"/"google_sheet"` in our config while google uses "GOOGLE_SHEETS." Previously we were doing the translation and #3881 changed to do it differently.
We could bring that translation back, but we thought it made more sense to bring our terminology in line with Google's.
We have a matching PR in `private-bigquery-etl` to accommodate this change …

Fix google sheets metadata and change from "google_sheet" to "google_sheets" for consistency with google

---

bigquery_etl/schema/__init__.py

When using `bqetl query schema update` to create a new `schema.yaml` file, BigQuery returns the column schema properties in a sensible order (`name`, `type`, `mode`, `fields`), but our `schema.yaml` output has been sorting those properties alphabetically which makes it much less readable.
Also, when using `bqetl query schema update` to update an existing `schema.yaml` file, this will now preserve whatever order the column schema properties were in.
---

Preserve the order of column schema properties in `schema.yaml` files

---

bigquery_etl/dependency.py

Otherwise the names of unaliased table references followed by a comment will incorrectly include the comment as part of the name ([example](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/21767/workflows/88be9f3b-7f81-4d4f-9649-f96f0e252e8a/jobs/216371)).
---

Ignore comments when detecting dependency table names

---

bigquery_etl/backfill/parse.py
bigquery_etl/cli/backfill.py
tests/cli/test_cli_backfill.py

[DENG-990](https://mozilla-hub.atlassian.net/browse/DENG-990):
* Refractored backfill `create` and `validate` cli commands
[DENG-999](https://mozilla-hub.atlassian.net/browse/DENG-999):
* Changed from `validating` to `validated` status
[DENG-990]: https://mozilla-hub.atlassian.net/browse/DENG-990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DENG-999]: https://mozilla-hub.atlassian.net/browse/DENG-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DENG-990 Refractor backfill cli commands

---

bigquery_etl/cli/query.py

partially reverts #3922
query arguments are ordered, and can override previous flags. this behavior is sometimes used to override flags set in one place with flags set in another. `list(set(query_arguments))` will not only deduplicate, it will non-deterministically order the flags, and neither of those are safe things.
for example `bq query --use_legacy_sql=False --use_legacy_sql=True --use_legacy_sql=False` should behave as `bq query --use_legacy_sql=False`, but with `list(set(query_arguments))` it could do either one depending on when and where it's run.

Don't deduplicate query arguments

---

bigquery_etl/glam/generate.py
bigquery_etl/glam/templates/latest_versions_v1.sql

Okay, second (and hopefully final) attempt at trying to simplify the latest_version template.
In this change we're using `buildhub2` data to make sure no bad version data gets in again. Also, `@submission_date` is added to template so the query is idempotent per @akkomar's suggestion.
Also, channel value is always `*` (channel values are switched to * in Glean pipeline because channels are processed in separate tables).
I have tested this query with some sample data and it's working as expected.

Simplify GLAM template for getting the latest version

---

bigquery_etl/dryrun.py
bigquery_etl/schema/__init__.py

* If SQL content is passed to dryrun we still need to rewrite date query parameters as `submission_date`, otherwise any such date parameters won't be found and the query will fail.
* The partition column name may be a reserved keyword, so it should be quoted.
---

Dryrun date param fixes

---

bigquery_etl/routine/parse_routine.py

This fixes the failing stage deploys. Stage changes UDF names to have escaped dataset and UDF names.

Regex for matching UDF names

---

bigquery_etl/format_sql/formatter.py
bigquery_etl/format_sql/tokenizer.py
tests/format_sql/jinja_example/expect.sql

Before:
```sql
WHERE
{% if is_init() %}
submission_date >= "2021-08-01" {% else %}
submission_date = @submission_date {% endif %}
```
After:
```sql
WHERE
{% if is_init() %}
submission_date >= "2021-08-01"
{% else %}
submission_date = @submission_date
{% endif %}
```
---

Format Jinja blocks like SQL blocks

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_aggregates_v2/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_probe_counts_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/schema.yaml

Bug 1838605 Fix schema for publishing new glam tables

---

sql/moz-fx-data-marketing-prod/ga_derived/downloads_with_attribution_v2/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/init.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_ios/ad_activation_performance/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_aggregates_v2/query.sql
sql/mozfun/norm/get_earliest_value/README.md
sql/mozfun/norm/get_earliest_value/metadata.yaml
sql/mozfun/norm/get_earliest_value/udf.sql

This PR updates the UDF `get_earliest_value()` to facilitate the implementation of the new profiles re-definition. 
Jira [DS-2965](https://mozilla-hub.atlassian.net/browse/DS-2965).
It also reduce the lines and complexity required to retrieve earliest ping.
> Note for the reviewer. Many files are reformatted to pass the CI. The files directly affected by the change are under fenix_derived/firefox_android_clients_v1 and mozfun/norm/get_earliest_value. 
[DS-2965]: https://mozilla-hub.atlassian.net/browse/DS-2965?atlOrigin=eyJpIjoi …

DS-2965 Update UDF get_earliest_value()

---

bigquery_etl/dryrun.py

The CI account doesn't have permission to access the tables in the `stripe_external` dataset.
---

Don't dryrun the `subscription_platform_derived.stripe_subscriptions_changelog_v1` ETL.

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_aggregates_v2/schema.yaml

Bug 1838605: fix histogram_aggregates field type

---

bigquery_etl/cli/query.py
bigquery_etl/util/parallel_topological_sorter.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1821767
Deploying tables takes around 45 minutes at the moment. Most time is spent updating table/query schemas, which is currently done sequentially. The order of how schemas are updated is important due to dependencies between queries. To get the right order, we have been using `TopologialSorter`. 
This PR, uses still keeps using `TopologialSorter` but processes queries as they get sorted in parallel. 
Updating schemas in `moz-fx-shared-prod` alone took around 30min. With this change it took around 8min running locally.
This PR will not only speed up the nightly table deploys, but also the stage deploy CI task in bigquery-etl.
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed …

[Bug 1821767] Speed up table deploys and schema updates

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/init.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/query.sql
sql/mozfun/norm/get_earliest_value/udf.sql

UDF norm.get_earliest_value requires a DATETIME for the third parameter.  This PR updates the usage of this UDF to retrieve a DATETIME, and adds a test case.

DS 2965 Follow up UDF get_earliest_value()

---

dags/bqetl_subplat.py
sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/init.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/schema.yaml

The FxA token columns aren't needed here, and contain sensitive authentication data.
Since the `mozilla_vpn_external.users_v1` ETL is self-referential, before merging this PR I will manually overwrite the table using the following query:
```sql
SELECT
* EXCEPT (
fxa_access_token,
fxa_refresh_token
)
FROM
`moz-fx-data-shared-prod.mozilla_vpn_external.users_v1`
```
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1044)

Exclude FxA token columns from `mozilla_vpn_external.users_v1`

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/event_types_v1/schema.yaml

follows-up: https://github.com/mozilla/bigquery-etl/pull/3968
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1047)

fix(DENG-353): removing submission_date from firefox_accounts_derived.event_types_v1 schema

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v2/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v2/schema.yaml

relates to: https://github.com/mozilla/bigquery-etl/pull/3607
---
This change is introducing `fxa_users_last_seen_v2` to build on top of the work done completed for `fxa_users_daily_v2`. The main reason for introducing v2 here is to enable both v1 and v2 to run in parallel until we validate that v2 is correctly generated at which point v1 if this table can be deprecated.
`Removed`:
- `days_seen_no_monitor_bits` - based of a monitor field in the daily table which appear to be no longer needed and is being removed in `fxa_users_daily_v2` and hence it is being removed here.
Below fields are being removed as they do not appear to fit in this table, primarily due to how we track the activity fields in this table (each activity field contains information for the last 28 days):
- `country`
- …

feat(DENG-711): Adding fxa_users_last_seen_v2

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_all_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/funnel_events_source_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_content_events_v1/schema.yaml

When reviewing #3407 I made an ill-advised code suggestion for the [`moz-fx-data-shared-prod.firefox_accounts_derived.funnel_events_source_v1` query](https://github.com/mozilla/bigquery-etl/pull/3407/files#diff-0664d1f3c1d2b6b20ccd19697c3d973c0ab1ee00af822b4b29f741d43cd18eec) which resulted in only a subset of columns being populated.  After that PR was merged, from 2022-12-15 onward the following 21 columns in `funnel_events_source_v1` have all ended up being null:
- `app_version`
- `country`
- `device_id`
- `email_provider`
- `entrypoint`
- `flow_id`
- `language`
- `logger`
- `os_name`
- `os_version`
- `receiveTimestamp`
- `sync_active_devices_day`
- `sync_active_devices_month`
- `sync_active_devices_week`
- `ua_browser`
- `ua_version`
- `utm_campaign`
- `utm_content`
- `utm_medium`
- …

Populate all columns in `firefox_accounts_derived.funnel_events_source_v1`

---

sql_generators/stable_views/__init__.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1839733
View deploys are currently failing due to the stable views for the new use counter tables:
```
Invalid function moz-fx-data-shared-prod.udf.normalize_main_payload Field name info does not exist in STRUCT<histograms STRUCT<use_counter2_appearance_nonwidget_button_document STRING, use_counter2_appearance_nonwidget_button_page STRING, use_counter2_appearance_nonwidget_checkbox_document STRING, ...>, processes STRUCT<content STRUCT<histograms STRUCT<use_counter2_appearance_nonwidget_button_document STRING, use_counter2_appearance_nonwidget_button_page STRING, use_counter2_appearance_nonwidget_checkbox_document STRING, ...>>>> Analysis of function Templated_SQL_Function:moz-fx-data-shared-prod.udf.normalize_main_payload failed at [8:5] …
```

[Bug 1839733] Fix stable view generation for use counter tables

---

bigquery_etl/shredder/config.py

#2512 added `firefox_accounts_derived.fxa_stdout_events_v1` in November 2021, but it wasn't added to the Shredder config at that time.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1060)

Shred `firefox_accounts_derived.fxa_stdout_events_v1`

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/exchange_rates_v1/query.py

The API has moved to a different URL and requests to the old URL are no longer working, which is currently breaking the `mozilla_vpn_derived.exchange_rates_v1` ETL ([bug 1840566](https://bugzilla.mozilla.org/show_bug.cgi?id=1840566)).
---

Update OANDA historical exchange rates API URL (bug 1840566)

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/exchange_rates_v1/query.py

OANDA's historical exchange rates API moved to a different URL, which was addressed in #3991.
However, that API now apparently has slightly different behavior where it may return exchange rates which have more than the 9 decimal places allowed by [BigQuery's decimal type](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types), in which case the `mozilla_vpn_derived.exchange_rates_v1` ETL will fail due to a behind-the-scenes "Invalid NUMERIC value" error ([bug 1840566](https://bugzilla.mozilla.org/show_bug.cgi?id=1840566)).
--- …

Round VPN exchange rates to fit in the BigQuery decimal type (bug 1840566)

---

bigquery_etl/dryrun.py

The CI has been failing with below errors -
https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/22374/workflows/a5160b11-a36e-40bf-a109-ad42a6fa61c4/jobs/224612?invite=true#step-106-707
https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/22374/workflows/a5160b11-a36e-40bf-a109-ad42a6fa61c4/jobs/224612?invite=true#step-106-685
as the tables have been classified as confidential.
This PR adds the tables to skiplist.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1087)

Add firefox_desktop and top_sites views to skiplist

---

bigquery_etl/view/__init__.py
tests/data/test_sql/moz-fx-data-test-project/test/view_with_metadata/metadata.yaml
tests/data/test_sql/moz-fx-data-test-project/test/view_with_metadata/view.sql
tests/view/test_view.py

Make sure that metadata `friendly_name` and `description` are published to views. Fixes #3850.

Publish view metadata

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
dags/bqetl_download_funnel_attribution.py

This should fix the failing check: https://workflow.telemetry.mozilla.org/dags/bqetl_download_funnel_attribution/grid?dag_run_id=scheduled__2023-06-27T23%3A00%3A00%2B00%3A00&task_id=checks__ga_derived__downloads_with_attribution__v2
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1088)

Ensure all necessary parameters are passed to DQ checks

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_server_events_v1/query.sql

This is to address Airflow failures.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1103)

fix(bug-1841622): updated nonprod_fxa_server_events_v1 schema

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_server_events_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_server_events_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1104)

fix(1841622): updated the nonprod_fxa_server_events_v1 schema to match the source table

---

bigquery_etl/view/__init__.py
tests/view/test_view.py

Related to https://github.com/mozilla/bigquery-etl/pull/3909
When calling `update_table()` multiple times it fails with
```
google.api_core.exceptions.PreconditionFailed: 412 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/moz-fx-data-shared-prod/datasets/firefox_ios/tables/metrics?prettyPrint=false: Precondition check failed.
```
Moving all metadata view updates into one call.
This should also fix current Airflow failures …

Update view metadata in a single update_table() operation

---

dags/bqetl_firefox_ios.py
sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/metadata.yaml

bug(1841621): updated execution_delta for some firefox_ios_derived scheduled queries
The `execution_delta` in the `depends` has been updated for the following two queries from `1h` to `3h`:
- `attributable_clients_v1`
- `firefox_ios_clients_v1`
This was causing the sensor to look for a task instance with a different execution_date than expected and being constantly rescheduled as the result of this.

bug(1841621): updated execution_delta for some firefox_ios_derived scheduled queries

---

dags/bqetl_feature_usage.py
dags/bqetl_main_summary.py
sql/moz-fx-data-shared-prod/telemetry/main_1pct/view.sql
sql/moz-fx-data-shared-prod/telemetry/main_remainder_1pct/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/main_remainder_1pct/view.sql
sql/moz-fx-data-shared-prod/telemetry/main_use_counter_1pct/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/main_use_counter_1pct/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/main_remainder_1pct_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/main_remainder_1pct_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/main_remainder_1pct_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/main_use_counter_1pct_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/main_use_counter_1pct_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/main_use_counter_1pct_v1/schema.yaml
sql_generators/feature_usage/templating.yaml

See discussion in https://mozilla.slack.com/archives/C01E8GDG80N/p1688570552377059
We've reached the point where `main_1pct` can no longer be populated by querying `telemetry_stable.main_v4`. The best way going forward is to split `main_1pct` much like we have split `main_v4` (into separate tables for use counters and the rest of the data).
The `telemetry.main_1pct` view will point to `telemetry.main_remainder_1pct` for now. I'll check if there are any dashboards that query use counter data from the old view version (no scheduled queries are affected by this).
For backfilling the `main_remainder_1pct_v1` and `main_use_counter_1pct_v1` we'll use the existing data in `main_1pct_v1` and generate a query that excludes the columns that are no longer part of the new tables. The underlying …

Split main_1pct

---

dags/bqetl_subplat.py
sql/moz-fx-data-shared-prod/stripe_external/customers_changelog_v1/metadata.yaml

Fixup for #4035.
The goal was to append to the `stripe_external.customers_changelog_v1` table, but since [`.bigqueryrc` specifies `--replace=true`](https://github.com/mozilla/bigquery-etl/blob/91882dd150169f045cceac48b87ad0267ce81026/.bigqueryrc#L6) the table is getting erased each time.  This should fix that.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1145)
[DENG-974]: https://mozilla-hub.atlassian.net/browse/DENG-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …

Override `--replace=true` from `.bigqueryrc` for `stripe_external.customers_changelog_v1` (DENG-974)

---

sql/moz-fx-data-shared-prod/stripe_external/subscriptions_changelog_v1/query.sql
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_revised_changelog_v1/query.sql

Going forward I want to use the new `is_init()` Jinja macro logic to make it easier to deploy all the new incremental SubPlat consolidated reporting ETLs, so for consistency, this PR adds such `is_init()` logic to the associated incremental Stripe ETLs that have already been deployed.
---
[DENG-974]: https://mozilla-hub.atlassian.net/browse/DENG-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …

Add init logic to new incremental Stripe ETLs (DENG-974)

---

bigquery_etl/docs/__init__.py
bqetl_project.yaml

Add missing "/" back to fix doc generation on `main` 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1163)

Add missing / for generating docs

---

bigquery_etl/__init__.py

This should fix the following error we hit in `copy_deduplicate.baseline_clients_first_seen`:
```
File "/usr/local/bin/bqetl", line 5, in <module>
from bigquery_etl.cli import cli
File "/usr/local/lib/python3.10/site-packages/bigquery_etl/cli/__init__.py", line 13, in <module>
from ..cli.backfill import backfill
File "/usr/local/lib/python3.10/site-packages/bigquery_etl/cli/backfill.py", line 31, in <module>
from ..cli.query import backfill as query_backfill
File "/usr/local/lib/python3.10/site-packages/bigquery_etl/cli/query.py", line 29, in <module>
from ..cli.utils import (
File "/usr/local/lib/python3.10/site-packages/bigquery_etl/cli/utils.py", line 147, in <module>
default=ConfigLoader.get("default", "sql_dir", fallback="sql"),
File …
```

Set ConfigLoader's project directory on module initialization

---

bqetl_project.yaml
sql_generators/glean_usage/common.py
sql_generators/glean_usage/glean_app_ping_views.py

This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1821784
Instead of skipping existing files during Glean generation processes, we should be explicit in what files should be skipped. This prevents us from breaking artifact deploys.
This is a less significant change than the alternative option of writing generated sql to a separate directory, which would also solve this issue: https://github.com/mozilla/bigquery-etl/issues/4068
This is something still worth considering, but this PR is a quicker fix for an issue that has been happening on a weekly basis now. …

[Bug 1821784] Be explicit about skipping generation for certain Glean artifacts

---

sql/moz-fx-data-shared-prod/adjust_derived/adjust_deliverables_v1/metadata.yaml
sql/moz-fx-data-shared-prod/adjust_derived/adjust_deliverables_v1/schema.yaml

The deployed table has a `date` field instead of `submission_date`. The schema needs to have the same
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1227)

Fix date field name for adjust_deliverables_v1

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql

`clients_histogram_bucket_counts` has a `client_id` threshold that takes into account total Weekly Active Users to determine whether or not a `build_id` should be processed. However this job is currently split in 10 sequential steps using `sample_id`, which reduces the `client_id` count to about a 1/10 of the original one for each step, making the aforementioned threshold about ten times higher than intended. This PR aims to fix that. …

Glam: consider sampling when applying % of WAU as threshold

---

bigquery_etl/cli/query.py
bigquery_etl/util/parallel_topological_sorter.py

Fixes https://mozilla.slack.com/archives/C4D5ZA91B/p1689588833802629
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1237)

Fix parallel schema updates

---

sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox/unified_metrics_v1/query.py

We're excluding fields from the generated view sql code:
- jwe
- text
- url
- labeled_rate
caused by: https://github.com/mozilla/bigquery-etl/pull/4029
More context can be found in bug 1840419.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1241)

bug(1840419): org_mozilla_ios_firefox.unified_metrics_v1 query fixing invalid query view generation

---

bigquery_etl/glam/clients_daily_histogram_aggregates.py
bigquery_etl/glam/clients_daily_scalar_aggregates.py
bigquery_etl/glam/templates/clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/clients_daily_scalar_aggregates_v1.sql

Due to historical incidents of bad version number getting in that broke the ETL, we added a filter that only accepts build IDs that match buildhub2 builds. However, [this query](https://sql.telemetry.mozilla.org/queries/93349/source) shows many FOG builds with substantial client count are being filtered out because they do not exist in buildhub2. This affects the client count we see in GLAM. 
Considering that we already have [a guardrail to ensure only valid version numbers get in](https://github.com/mozilla/bigquery-etl/pull/3933), we should remove the buildhub2 filter. Potentially will fix https://github.com/mozilla/glam/issues/2003.
For modifications to …

Remove buildhub2 filter in GLAM templates

---

sql_generators/glean_usage/common.py
sql_generators/glean_usage/glean_app_ping_views.py

This should fix errors related to fenix.client_deduplication. The issue was comparing Path objects to str (which for some reason works for me locally but not in CI)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1259)

Fix skipping client_dedup

---

bigquery_etl/glam/generate.py

We have a min client count filter for legacy probes, but not for FOG, which means builds with low client count can get it and pollute the dataset. This PR updates the min filter to avoid that.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1260)

Increase FOG client count minimum filter

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_scalar_probe_counts_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/scalar_percentiles_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/scalar_percentiles_v1/schema.yaml
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_scalar_probe_counts_v1/test_aggregation/expect.ndjson

Fixes 1844886
This brings `non_norm_aggregates` cols to scalar percentiles/aggregates tables so said tables match the schema of counterpart histogram tables, allowing downstream processes to `UNION` them.
Before those columns were being added to `telemetry_derived.client_probe_counts` view, prior to export.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1272)

Bug 1844886: Add non-norm cols to scalar tbls

---

sql/moz-fx-data-shared-prod/telemetry_derived/histogram_percentiles_v1/schema.yaml

Follow up to #3873 - looks like the checked-in schema doesn't match the deployed schema in some incompatible ways:
`[2023-07-25, 02:21:19 UTC] {pod_manager.py:235} INFO - google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/moz-fx-data-shared-prod/datasets/telemetry_derived/tables/histogram_percentiles_v1?prettyPrint=false: Field aggregates.KEY already exists in schema`

Update telemetry_derived.histogram_percentiles_v1 schema

---

dags.yaml
dags/bqetl_acoustic_contact_export.py
dags/bqetl_acoustic_raw_recipient_export.py
sql/moz-fx-data-marketing-prod/acoustic/contact_raw_v1/metadata.yaml
sql/moz-fx-data-marketing-prod/acoustic/contact_raw_v1/query.sql

As we started getting unexpected values (`yes` and `no` for some fields we previously assumed to be of numeric value only):
- ensuring the `double_opt_in` field is of type `INTEGER`, this includes conversion of `Yes` to `1` and `No` to `0`.
- ensuring the `fxa_account_deleted` field is of type `INTEGER`, this includes conversion of `Yes` to `1` and `No` to `0`.
- ensuring the `has_opted_out_of_email` field is of type `INTEGER`, this includes conversion of `Yes` to `1` and `No` to `0`.
Additionally, to avoid wasted cost by attempting to re-run the query (if the query is invalid, retrying is pointless)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1318)

bug(1844385): bqetl_acoustic_contact_export contacts_raw_v1 failing due to invalid schema update error.

---

sql/moz-fx-data-shared-prod/telemetry_derived/main_remainder_1pct_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/main_use_counter_1pct_v1/schema.yaml

fix(): udated schema.yaml files for main_remainder_1pct_v1 and main_use_counter_1pct_v1
Bigquery ETL main branch started failing on the `dry-run-sql` step with the following error:
```
Schema defined in sql/moz-fx-data-shared-prod/telemetry_derived/main_remainder_1pct_v1/schema.yaml incompatible with query sql/moz-fx-data-shared-prod/telemetry_derived/main_remainder_1pct_v1/query.sql
```
Both schema files have been updated by running:
```
./bqetl query schema update telemetry_derived.main_remainder_1pct_v1
./bqetl query schema update telemetry_derived.main_use_counter_1pct_v1
```
The reason both have been updated that locally when running:
```
./bqetl dryrun --validate-schemas sql/moz-fx-data-shared-prod/telemetry_derived
```
Both were reporting this error.
┆Issue is synchronized with …

fix(): udated schema.yaml files for main_remainder_1pct_v1 and main_use_counter_1pct_v1

---

docs/cookbooks/adding_data_checks.md
docs/reference/data_checks.md

This includes two docs:
- `cookbooks/adding_data_checks.md` - a guide to adding checks to a query.
- `reference/data_checks.md` - an overview of data checks and what checks are available.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1356)

docs(DENG-961): Added reference doc for data checks and a cookbook for adding new data checks

---

sql_generators/active_users/templates/focus_android_query.sql
sql_generators/active_users/templates/mobile_query.sql
sql_generators/active_users_deletion_requests/templates/mobile_deletion_request_query.sql

Fixes [DENG-1379](https://mozilla-hub.atlassian.net/browse/DENG-1379) and reported bug of null values in search counts for mobile.
[Validation query](https://sql.telemetry.mozilla.org/queries/93988/source).
[DENG-1379]: https://mozilla-hub.atlassian.net/browse/DENG-1379?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1380)

DENG-1379 Remove app_name from search filter and use join by client_id

---

bigquery_etl/cli/backfill.py
tests/cli/test_cli_backfill.py

In preparation for using this as an XCOM in Airflow. We'll read this JSON in downstream Airflow tasks to process backfills.
~- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.~
~- [ ] If adding a new field to a query, ensure that the schema and dependent downstream schemas have been updated.~
~- [ ] When adding a new derived dataset, ensure that data is not available already (fully or partially) and recommend extending an existing …

DENG-899 - Add json write functionality to bqetl schedule command

---

docs/mkdocs.yml

This is to ensure they are included in our docs page. This inclusion was missed in PR: #4162
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1403)

docs(DENG-961): added data checks docs to mkdocs.yml

---

bigquery_etl/cli/query.py

If the destination table is not set, data is ingested into a temporary table.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1407)

Add destination table when initializing query.

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/init.sql

A LEFT JOIN is required in the initialization script to avoid NULLS due to clients in the activations table that are not reported by any ping.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1417)

Left join with activations in init.sql

---

tests/checks/in_range.jinja
tests/checks/is_unique.jinja
tests/checks/not_null.jinja

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1425)

Allow bqetl checks that take a list of columns to also accept a single column string

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_all_events/view.sql

The `jsonPayload.fields.time` float values could be larger than the max BigQuery integer value allowed and/or larger than the max number of milliseconds that can be translated into a BigQuery timestamp value.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1426)

Update `fxa_all_events` to guard against bad event time values

---

bigquery_etl/backfill/utils.py

This sometimes maps a qualified table name to an empty list which causes an error downstream
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1444)

Skip tables with all filtered backfill entries

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql

Rewriting the `CROSS JOIN` in `telemetry_derived.clients_histogram_bucket_counts_v1` as `UNION ALL`. This reduced execution time by about 40% for some sampled data I tested it on.
The thing that is different with the `UNION`ed queries is that it can aggregate data for each of the `os` and `app_build_id` combinations in parallel on smaller datasets. Before, BigQuery ran the aggregations in a single step on a larger dataset which had all the combinations. 
One thing to note is that while the elapsed/felt time is 40% lower, this query is technically less efficient and consumes slightly more slot time and shuffles more bytes. I don't think that will be an issue, since it doesn't affect the cost and having these jobs finish quite a bit faster is desirable.
in the logs …

Speed up GLAM histogram bucket counts

---

bigquery_etl/cli/stage.py

#3791 changed `bqetl stage` so that replaced table IDs were always quoted, but there was still this logic to put extra quotes around wildcard table names, which results in invalid SQL.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1455)

Don't quote wildcard tables twice when updating stage references

---

bqetl_project.yaml
dags/bqetl_subplat.py
sql/moz-fx-data-shared-prod/subscription_platform/stripe_plans/view.sql
sql/moz-fx-data-shared-prod/subscription_platform/stripe_products/view.sql
sql/moz-fx-data-shared-prod/subscription_platform_derived/services_v1/query.sql
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_plans_v1/metadata.yaml
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_plans_v1/query.sql
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_plans_v1/schema.yaml
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_products_v1/metadata.yaml
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_products_v1/query.sql
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_products_v1/schema.yaml
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_revised_changelog_v1/query.sql

To add Stripe product and plan data in Looker the data needs to be in Mozilla-confidential-accessible tables, which is what these ETLs do.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1463)
[DENG-1448]: https://mozilla-hub.atlassian.net/browse/DENG-1448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add `stripe_products_v1` and `stripe_plans_v1` ETLs (DENG-1448)

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1470)

Bug 1836278 - Add dlsource to clients_daily

---

sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_instance_v1/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_instance_v1/schema.yaml

It appears due to an incorrect aliasing inside the `query.sql` we ended up with an incorrect field being used to populate the `job_id` field. This PR aims to fix this.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1475)

bug(): fixing airflow_task_instance query and correcting job_id type

---

tests/checks/min_rows.jinja

An example of a rendered check query before the change:
```sql
WITH min_rows AS (
SELECT
COUNT(*) AS total_rows
FROM
`moz-fx-data-shared-prod.firefox_ios_derived.app_store_funnel_v1`
WHERE
`date` = DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY)
)
SELECT
IF(
(SELECT total_rows FROM min_rows WHERE total_rows < 1) > 0,
ERROR(
CONCAT("Less than ", (SELECT total_rows FROM min_rows), " rows found (expected more than 1)")
),
NULL
);
```
Currently, the above results in `null` being returned even though we know there is missing data in the table.
Rendered query after the change:
```sql
WITH min_rows AS (
SELECT
COUNT(*) AS total_rows
FROM
`moz-fx-data-shared-prod.firefox_ios_derived.app_store_funnel_v1`
WHERE
`date` = DATE_SUB(CURRENT_DATE, INTERVAL 1 DAY)
)
SELECT
IF(
(SELECT COUNTIF(total_rows < 1) FROM …
```

bug(): tweaking the min_rows data check macro as currently it does not error when expected

---

dags.yaml
dags/bqetl_monitoring_airflow.py

changing the timing on the airflow monitoring DAG so that it runs after more of the other DAGs ran ... because at currently 2 am most haven't finished yet. Open for other suggestions on the timing
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1508)

DENG-797 change monitoring_airflow DAG schedule

---

docs/cookbooks/common_workflows.md

See https://mozilla-hub.atlassian.net/browse/DENG-1510 or https://bugzilla.mozilla.org/show_bug.cgi?id=1852117 for context.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1512)

fix DENG-1510: add dryrun flag to schema update command

---

.circleci/config.yml

The `bqetl query render` subcommand to support Jinja in SQL files was added in #3691, at which time the `generate-sql` CI job was updated to call `bqetl query render`.  However, the `private-generate-sql` and `generate-diff` CI jobs weren't updated to match.  One side effect of this is that SQL diffs on PRs currently erroneously show differences that are simply due to Jinja expressions getting rendered/replaced.
This updates the CI jobs that generate SQL to consistently call `bqetl query render`.
---
┆Issue is synchronized with …

Consistently call `bqetl query render` when generating SQL in CI

---

dags.yaml
dags/bqetl_kpis_shredder.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1542)

chore(): updated bqetl_kpis_shredder DAG description to indicate why it is paused

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_oauth_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/nonprod_fxa_all_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/nonprod_fxa_content_auth_stdout_events/view.sql

This change is required in order to make the data post migration available inside the existing Looker dashboards without requiring any effort on the Looker side.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1560)

feat(DENG-722): updated fxa views to point to fxa_all_events view

---

sql/moz-fx-data-shared-prod/app_store/firefox_app_store_territory_source_type_report/view.sql
sql/moz-fx-data-shared-prod/app_store/firefox_downloads_territory_source_type_report/view.sql
sql/moz-fx-data-shared-prod/app_store/firefox_usage_territory_source_type_report/view.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1563)

bug(): Apple timestamps appear to be using PST, converting to UTC

---

sql/moz-fx-data-shared-prod/app_store/firefox_app_store_territory_source_type_report/view.sql
sql/moz-fx-data-shared-prod/app_store/firefox_downloads_territory_source_type_report/view.sql
sql/moz-fx-data-shared-prod/app_store/firefox_usage_territory_source_type_report/view.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1565)

bug(): app store funnel v1 pst to utc date convertion incorrect function input

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1568)

bug(): correcting joins inside firefox_ios_derived/app_store_funnel_v1 causing undesired filtering

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_oauth_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1575)

bug(): readded fileds to the fxa_content_auth_stdout_events removed by an accident

---

sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/query.sql
sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/schema.yaml

Reverts mozilla/bigquery-etl#4283
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1580)

Revert "[RS-768] Add default engine & engagement info to revenue levers table"

---

docs/cookbooks/common_workflows.md

For https://bugzilla.mozilla.org/show_bug.cgi?id=1852336
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1591)

[Bug 1852336] Add more docs for updating clients_daily

---

.circleci/config.yml
bigquery_etl/cli/dag.py
bigquery_etl/cli/query.py
bigquery_etl/query_scheduling/generate_airflow_dags.py
bigquery_etl/util/common.py

This adds a step to CI to publish generated DAGs from `private-bigquery-etl` to the `private-generated-sql` branch in the same repository. We already generate and publish DAGs in bigquery-etl to the `generated-sql` branch and need to do the same in the private repo to support loading DAGs from these branches instead of `main`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1595)

Publish private-bigquery-etl DAGs to private-generated-sql

---

sql_generators/urlbar_events/templates/desktop_query.sql

Fixes a typo that caused the `num_open_tab_impressions` column to be all 0.
As discussed, this will need a backfill, but we can probably do this when we soon land new columns in the table.
@alekhyamoz Do I need to update `sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_v1/query.sql` as well, or will that happen automatically?
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1608)

Fix typo in open tab count

---

sql/moz-fx-data-shared-prod/firefox_desktop_derived/onboarding_v2/backfill.yaml

Validating backfill for `moz-fx-data-shared-prod.firefox_desktop_derived.onboarding_v2` - 2023-09-18
Please merge this pull request once the backfill data at location: `moz-fx-data-shared-prod.backfills_staging_derived.onboarding_v2_2023_09_18` has been validated.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1604)

Validating onboarding_v2 backfill 2023-09-18

---

sql/moz-fx-data-shared-prod/firefox_desktop_derived/onboarding_v2/backfill.yaml

Completing backfill for `moz-fx-data-shared-prod.firefox_desktop_derived.onboarding_v2` - 2023-09-18
Data from backfill location: `moz-fx-data-shared-prod.backfills_staging_derived.onboarding_v2_2023_09_18` has been copied to production location: `moz-fx-data-shared-prod.firefox_desktop_derived.onboarding_v2`.
A backup (clone) of the previous production data is located at `moz-fx-data-shared-prod.backfills_staging_derived.onboarding_v2_backup_2023_09_18` and will expire in 30 days.
Please merge this pull request once you confirm that your production data is as expected.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1610)

Completing onboarding_v2 backfill 2023-09-18

---

dags/bqetl_analytics_aggregations.py
dags/bqetl_firefox_ios.py
dags/bqetl_mobile_activation.py
sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/schema.yaml

Previously, the query has been using an incorrect source for getting new_profile numbers. This changes updated the query to use the new more recent table for getting this information.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1592)

bug(DENG-1558): firefox_ios_derived.app_store_funnel_v1 updated the source of new profiles

---

.circleci/config.yml

The `bqetl metadata update` subcommand was added in #4213, at which time the `generate-sql` and `private-generate-sql` CI jobs were updated to call `bqetl metadata update`. However, the `main-generate-sql-and-dags` CI job wasn't updated to match. One side effect of this is that SQL diffs on PRs currently erroneously show differences that are simply due to `schema.yaml` files getting updated by `bqetl metadata update`.
This updates the `main-generate-sql-and-dags` CI job to also call `bqetl metadata update`.
---
┆Issue is …

Consistently call `bqetl metadata update` when generating SQL in CI

---

.circleci/config.yml

With DAGs [soon to be completely auto-generated](https://mozilla.slack.com/archives/C01E8GDG80N/p1695225705737459?thread_ts=1695225273.715379&cid=C01E8GDG80N) and not checked in as part of PRs it'll be critical to understand how PRs are changing the DAGs.  We already have CI jobs that diff the generated code with what's in the `main` branch and attach the diff output to the PR as comments, but that currently diffs the SQL first and then the DAGs, and it only shows the first 65k characters of the diff, so the DAG diffs might not be shown.
This PR diffs the DAGs first so the DAG diffs should always be shown in the CI's generated diff PR comments.
---
For …

Diff DAGs first in `generate-diff` CI job

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/query.sql

Updated the country mapping table to use country_names table instead as the previous table was incorrectly used which resulted in a bunch of countries incorrectly being categorised as `null` and resulting in the granuality of the table (date, country) being violated. This change addresses this issue.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1623)

bug(DENG-1622): app_store_funnel_v1 country mapping table updated + check tweak

---

bigquery_etl/shredder/config.py

#4288 added `firefox_accounts_derived.fxa_gcp_stdout_events_v1` and `firefox_accounts_derived.fxa_gcp_stderr_events_v1`, but they weren't added to the Shredder config.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1635)

Shred `firefox_accounts_derived.fxa_gcp_*_events_v1`

---

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/query.py
sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/schema.yaml

Error in running previous version where data wasn't going into the right partition - Creation date was different from the date the job was run.
Added DATE when DAG was run as submission_date and made this the partition date. Kept the creation_date as this will be used later in the bigquery_tables_inventory_v1 query
Deleted the old table because a new column was added. Backfill to March 16, 2023 will need to happen after merging
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1641)

Update partitioning bigquery usage v2

---

bigquery_etl/query_scheduling/task.py
dags/bqetl_main_summary.py

This is required after these queries were moved out of copy_deduplicate_all in https://github.com/mozilla/telemetry-airflow/pull/1822
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1645)

Update split main ping queries parent task

---

dags/bqetl_firefox_ios.py

This is an operation missed in change: https://github.com/mozilla/bigquery-etl/pull/4343
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1652)

bug(): regenerated bqetl_firefox_ios DAG

---

bigquery_etl/query_scheduling/task.py
dags/bqetl_analytics_tables.py
sql/moz-fx-data-shared-prod/monitoring_derived/telemetry_missing_columns_v3/query.sql
sql/moz-fx-data-shared-prod/telemetry/main_1pct/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/main_remainder_1pct/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/main_remainder_1pct_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/main_remainder_1pct_v1/query.sql

and point at new copy_deduplicate tasks for similar pings
[Bug 1852630](https://bugzilla.mozilla.org/show_bug.cgi?id=1852630)
requires https://github.com/mozilla/telemetry-airflow/pull/1825

Bug 1852630 - Rename main_remainder_v4 to main_v5

---

sql/moz-fx-data-shared-prod/telemetry/first_shutdown/view.sql
sql/moz-fx-data-shared-prod/telemetry/main/view.sql
sql/moz-fx-data-shared-prod/telemetry/saved_session/view.sql

and rename main_remainder_v4 references to main_v5
[Bug 1852630](https://bugzilla.mozilla.org/show_bug.cgi?id=1852630)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1538)

Bug 1852630 - Override default main-like tables to pin v4

---

sql/moz-fx-data-shared-prod/firefox_ios/firefox_ios_clients/view.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/init.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/schema.yaml

filtering out "suspicious ios" users due to bug-1846554
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1674)

feat(): firefox_ios_clients_v1 table partitoning and clustering settings update + filtering out "suspicious ios" users

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1677)

fix(): updating clustering settings for firefox_ios_clients_v1 tale

---

bigquery_etl/query_scheduling/dag.py

For https://mozilla-hub.atlassian.net/browse/DENG-1091 (https://bugzilla.mozilla.org/show_bug.cgi?id=1841129)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1676)

fix DENG-1091: automatically add triage/confidential to private DAGs

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_2_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_2_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_2_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/schema.yaml

fix(): tweaks to partitioning settings for firefox_ios_derived.funnel_retention tables
This is to correctly work with the bqetl mechanism when inserting data into a specific data partition of a table:
https://github.com/mozilla/telemetry-airflow/blob/2048f039c6c68bf99254cb9721bc35923232cd82/dags/utils/gcp.py#L197
Otherwise, when running the query we get an error trying to insert the data into a "wrong partition"

fix(): tweaks to partitioning settings for firefox_ios_derived.funnel_retention tables

---

bigquery_etl/shredder/config.py

* `moz-fx-data-shared-prod.firefox_accounts_derived.events_daily_v1`
* Added in June 2021 by #2114.
* `moz-fx-data-shared-prod.firefox_accounts_derived.funnel_events_source_v1`
* Added in June 2021 by #2126.
* `moz-fx-data-shared-prod.firefox_accounts_derived.fxa_log_device_command_events_v1`
* Added in July 2020 by #1150.
* `moz-fx-data-shared-prod.firefox_accounts_derived.fxa_log_device_command_events_v2`
* Added in September 2023 by #4308.
---

Shred four more FxA tables

---

sql_generators/glean_usage/glean_app_ping_views.py

When the Glean app for the Mozilla VPN iOS network extension was added in mozilla/probe-scraper#628 this caused the `glean_usage` SQL generator to try to generate the `mozilla_vpn.main` view with some invalid SQL:
- A struct type definition contained an unqualified `range` field name, but `RANGE` is a [reserved keyword in BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#reserved_keywords).
- A struct type definition contained a `FLOAT` data type reference, but [BigQuery requires it to be `FLOAT64`](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#floating_point_types) (I've asked Google if they have any plans to support `FLOAT` without the `64` suffix).
This PR adds workarounds for both of those issues in the `glean_usage` SQL …

Fix `mozilla_vpn.main` view generated SQL

---

dags/bqetl_analytics_aggregations.py
dags/bqetl_firefox_ios.py
sql/moz-fx-data-shared-prod/firefox_ios/funnel_retention_week_4_aggregates/view.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_2_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_aggregates_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_aggregates_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/checks.sql

feat(): adding firefox ios retention week 4 aggregates query
This means that unless we decide to "backfill" this table the numbers reported by it should not be affected by Shredder.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1695)

feat(): adding firefox ios retention week 4 aggregates query

---

sql/moz-fx-data-shared-prod/firefox_ios/firefox_ios_clients/view.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_2_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/query.sql

feat(): moved out the is_suspicious_client_device filter from clients view to retention queries
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1709)

feat(): moved out the is_suspicious_client_device filter from clients view to retention queries

---

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Removes the `value` field from experiment branches because it has not been used by Experimenter in over a year and is causing an issue on a new experiment because it is missing.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1718)

remove unused deprecated field from branch

---

bqetl_project.yaml
dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts/docker_fxa_admin_server_sanitized/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v2/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v2/schema.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v1/metadata.yaml

feat(DENG-1696): docker fxa admin server sanitized updating after gcp migration
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1734)

feat(DENG-1696): docker fxa admin server sanitized updating after gcp migration

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_content_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_gpu_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_parent_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_v1.sql.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_boolean_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_histogram_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_scalar_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1.sql.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/query.sql

Switches glam_etl (legacy) to `main_v5` to benefit from the better performance that table offers.
The queries in this PR are irrelevant because they're auto-generated by the python script. They're only for humans to understand what's kinda getting generated.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1713)

glam etl uses main_v5

---

.circleci/config.yml

Add CI step to update the submodule reference for `private-bigquery-etl`'s `private-generated-sql` branch in [telemetry-airflow-dags](https://github.com/mozilla/telemetry-airflow-dags).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1755)

chore(ci): update private-bigquery-etl git submodule in telemetry-airflow-dags repo

---

.circleci/config.yml

Adds missing key to sync private-bigquery-etl repo in the sync-dags-repo step.
Also fix linting issue where fingerprints were defined as strings but should be arrays.

fix(ci): Add missing SSH key in sync-dags-repo step

---

.circleci/config.yml

private-bigquery-etl uses branch `private-generated-sql` instead of `generated-sql`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1757)

fix(ci): sync-dags-repo uses wrong branch for private-bigquery-etl

---

bigquery_etl/glam/templates/clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/clients_daily_scalar_aggregates_v1.sql
bigquery_etl/glam/templates/probe_counts_v1.sql

Samples (10%) `Windows` probes in `Release` for FOG, following what's done in Legacy Telemetry.
This is in response to a linear increase in BQ processing costs for the `glam_fog` dag since mid June 2023.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1747)

Add sampling to glam-fog

---

dags/bqetl_firefox_ios.py
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v2/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1749)

feat(DENG-1599): added ETL checks related to firefox_ios_derived.new_profile_activation_v2

---

.circleci/config.yml

Should fix CI failures on main. The issue is that we need two different SSH keys, for writer on telemetry-airflow-dags and for reader on private-bigquery-etl, and CircleCI does not support loading keys with different hosts for the same hostname.
By manually changing the SSH configuration, we can use those two keys without issues.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1760)

fix(ci): Manually set SSH configuration for multiple SSH keys.

---

sql/moz-fx-data-shared-prod/stripe/itemized_payout_reconciliation/view.sql

reverts all of the previous address changes (except renaming `state` and `postal_code` to `card_state` and `card_postal_code`) and instead pulls in tax address fields from the itemized tax report
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1770)

DS-2642 - Update tax address source in stripe payout report

---

dags/bqetl_serp.py
sql_generators/serp_events/templates/metadata.yaml

The bqetl_serp DAG is failing due to the below error 
Error in query string: Error processing job 'moz-fx-data-shared-
```Query parameter - 'submission_date' not found at [13:48]```
Error logs - https://workflow.telemetry.mozilla.org/dags/bqetl_serp/grid?dag_run_id=scheduled__2023-10-13T00%3A00%3A00%2B00%3A00&task_id=firefox_desktop_serp_events__v1&tab=logs
This should fix the issue

DENG1546 - Fix bqetl serp DAG failure due to missing parameter

---

sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1791)

DENG-476 - Remove unnecessary reference to main_v4 from ssl ratios

---

sql_generators/glean_usage/common.py

This should fix the artifact deploys.
`glean_usage` is generating various queries and corresponding views for each Glean application. The logic seems to skip the generation if a table that is referenced by a view does not exist. However, this is initially the case when a new app gets added. This PR fixes this behaviour.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1804)

Fix Glean usage generation; don't skip query generation when tables don't exist

---

dags/bqetl_serp.py
sql_generators/serp_events/templates/metadata.yaml

The dag bqetl_serp failed with error 
```Unparseable query parameter  `submission_date` in type `TYPE_DATE`, Invalid date: '20231015' value: - '20231015'```
Error logs - https://workflow.telemetry.mozilla.org/dags/bqetl_serp/grid?dag_run_id=scheduled__2023-10-15T00%3A00%3A00%2B00%3A00&task_id=firefox_desktop_serp_events__v1&tab=logs
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1783)

DENG1546 - Fix bqetl_serp DAG failure

---

bigquery_etl/cli/query.py

`copy_deduplicate.baseline_clients_first_seen` is failing today with:
```
[2023-10-18, 13:19:44 UTC] {pod_manager.py:235} INFO - google.api_core.exceptions.NotFound: 404 Not found: Dataset moz-fx-data-airflow-gke-prod:mozillavpn_derived was not found in location US
```
Setting project_id in the init job should fix this error.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1811)

Set project in init jobs

---

bigquery_etl/cli/query.py

Tested this locally. `bqetl backfill` now defaults to not running checks.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1814)

Add opt-in to running checks for backfill

---

dags/bqetl_analytics_tables.py
dags/bqetl_main_summary.py
sql/moz-fx-data-shared-prod/telemetry/clients_first_seen_28_days_later/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_28_days_later_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_28_days_later_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_28_days_later_v1/schema.yaml

Creates `clients_first_seen_28_days_later` query and view. 
More or less copy-paste from https://github.com/mozilla/bigquery-etl/pull/4358 and https://docs.google.com/document/d/1l-m7-WS51qo8V_29ArN4VYV-GX4U5YmV2UQtcDPL5LY/edit#heading=h.k926msualmu4. I'll highlight key differences in files changed.

DENG-1714 - Create clients_first_seen_28_days_later

---

dags/bqetl_analytics_tables.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_28_days_later_v1/metadata.yaml

This is currently trying to write to the current days partition, update to match the query's `DATE_SUB(27 DAY)`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1839)

Update clients_first_seen_28_days_later metadata to write to correct partition

---

bigquery_etl/cli/check.py
bigquery_etl/cli/utils.py

This has been very useful for checking e.g. all `baseline_clients_first_seen` tables for errors.
Another nice improvement would be parallelization, but that is not required.
Also added some typing.

Allow running multiple checks

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml

See https://github.com/mozilla/bigquery-etl/pull/3962#discussion_r1332186267 - get the first value for a client's `startup_profile_selection_reason`

DENG-1705 - Add startup_profile_selection_reason_first to clients_daily_v6

---

sql_generators/event_monitoring/templates/event_monitoring_live.init.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1866)

Add FxA custom events to view definition

---

dags/bqetl_internet_outages.py
dags/bqetl_main_summary.py
sql/moz-fx-data-shared-prod/internet_outages/global_outages_v1/metadata.yaml
sql/moz-fx-data-shared-prod/internet_outages/global_outages_v1/query.sql

also fixes dags waiting for the wrong upstream tables
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1786)

DENG-476 - Update internet outages to reference main_v5

---

sql/mozfun/norm/result_type_to_product_name/udf.sql

fixes bug introduced in https://github.com/mozilla/bigquery-etl/pull/4373
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1870)

Fix test for mozfun.norm.result_type_to_product_name

---

sql/moz-fx-data-shared-prod/amo_prod/desktop_addons_by_client_v1/query.sql

quick fix for #4481
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1872)

Bug-1860814-amo_prod__desktop_addons_by_client_fix 

---

dags/bqetl_monitoring.py
sql/moz-fx-data-shared-prod/monitoring_derived/glean_server_knob_experiments_v1/metadata.yaml

Fix for currently failing dag https://workflow.telemetry.mozilla.org/dags/bqetl_monitoring/grid?search=bqetl_monitoring&dag_run_id=scheduled__2023-10-30T02%3A00%3A00%2B00%3A00&task_id=glean_server_knob_experiments__v1&tab=logs
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1887)

Bug #1862203 Enforce no date partition parameter in DAG

---

sql/moz-fx-data-shared-prod/telemetry/fenix_events_v1/view.sql
sql/mozfun/norm/glean_ping_info/udf.sql
sql_generators/glean_usage/templates/baseline_clients_daily_v1.query.sql

In future versions of Glean that timestamp can be more precise, so we need to ensure we correctly parse it.
Re-push of #4459 directly to this repository
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1832)

Use mozfun.glean.parse_datetime to parse ping_info fields

---

.circleci/config.yml

[ci/circleci: main-generate-sql-and-dags is failing](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/26277/workflows/882f9402-d4d6-4c36-8eb7-0a99621b00dc/jobs/276045?invite=true#step-106-1696361_89) because the command `dag generate` is missing the output directory.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1906)

Add output_dir to command dag generate.

---

bigquery_etl/cli/query.py

Without this, the `bqetl query create` command fails with 
```
FileNotFoundError: [Errno 2] No such file or directory: 'dags/bqetl_default.py'
```
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1914)

Dont generate dags in bqetl query schedule command

---

bigquery_etl/dryrun.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1919)

chore(): prefixing schema error message inside dryrun to "ERROR" to make it easier to find the error in logs

---

bigquery_etl/cli/check.py
bigquery_etl/query_scheduling/task.py

This should fix issues we are seeing in https://workflow.telemetry.mozilla.org/dags/bqetl_firefox_ios/grid?dag_run_id=scheduled__2023-10-24T04%3A00%3A00%2B00%3A00&task_id=checks__warn_firefox_ios_derived__firefox_ios_clients__v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1925)

Set depend_on_past=False for warn checks

---

sql/mozfun/map/set_key/README.md
sql/mozfun/map/set_key/metadata.yaml
sql/mozfun/map/set_key/udf.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1926)

Add map.set_key to mozfun

---

sql/moz-fx-data-shared-prod/fenix/client_adclicks_history/metadata.yaml
sql/moz-fx-data-shared-prod/fenix/client_adclicks_history/view.sql
sql/moz-fx-data-shared-prod/fenix_derived/client_adclicks_history_v1/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/client_adclicks_history_v1/metadata.yaml
sql/moz-fx-data-shared-prod/fenix_derived/client_adclicks_history_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/client_adclicks_history_v1/schema.yaml

This creates a table with 1-row per-client, clustered on `sample_id`, with the full history of days and ad_clicks for that client.
This was the most efficient way to create this kind of table while still keeping the job idempotent.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1929)

DS-3281 - Add client adclicks history table

---

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql
sql_generators/glean_usage/templates/event_monitoring_live.view.sql
sql_generators/glean_usage/templates/event_monitoring_live_v1.init.sql

Experiment information that should show up on the event monitoring dashboard. 
We'll need to know the experiments, how many events are coming from clients enrolled in a specific experiment and will join it with enrollment information.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1916)

Add experiment information to event monitoring

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v2/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v2/moz-fx-data-shared-prod.telemetry_derived.clients_daily_v6.schema.json

Followup to https://github.com/mozilla/bigquery-etl/pull/4482#pullrequestreview-1707538782 
Adds missing columns to clients daily and first-seen. Sample data from beta here: `moz-fx-data-shared-prod.tmp.anich_clients_daily_1705_test`, `moz-fx-data-shared-prod.tmp.anich_clients_first_seen_v2_test_1705`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1897)

DENG-1705 - Add missing client attribution columns to clients daily/first-seen

---

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql

This will ensure that FxA tables are included in the aggregate.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1943)

Fix event_monitoring_aggregates_v1 template

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v2/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1945)

bug(): Fixing query error in fenix_derived/firefox_android_clients_v2/checks.sql

---

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql

Nulls need to be casted to string to make the union work.
This will fix https://workflow.telemetry.mozilla.org/log?execution_date=2023-11-09T02%3A00%3A00%2B00%3A00&task_id=monitoring_derived__event_monitoring_aggregates__v1&dag_id=bqetl_monitoring&map_index=-1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1954)

Fix event monitoring template

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1955)

# bug(1859232): removed check for firefox_ios_clients_v1 which used different filtering settings causing result mismatch

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/query.sql

I actually tried backfilling this one locally, and it runs.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1960)

Use correct app_version field

---

sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_instance_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_trigger_v1/schema.yaml

Will instead open a PR and wait until Fivetran makes the change prior to merging.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1961)

Revert "updated two affected fields across task_instance and trigger airflow metadata tables to type JSON (#4545)"

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_28_days_later_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_28_days_later_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v2/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v2/moz-fx-data-shared-prod.telemetry_derived.clients_daily_v6.schema.json

Follow up to https://github.com/mozilla/bigquery-etl/pull/4473. Small refactor to cfs_28_days_later
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1865)

DENG-1705 - Add startup_profile_selection_reason from first ping to clients_daily, clients_first_seen_v2 and downstream

---

sql/mozfun/norm/result_type_to_product_name/udf.sql

These result types are being added in relation to the new Rust backend for Suggest (https://docs.google.com/document/d/1JTSR4oVjSke0qKRe1s6nFvk3LHE01__dO2L8a20AhLg/edit#bookmark=id.b4zo4jx5g68i)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1952)

Add rust result types to product mapping

---

sql/moz-fx-data-shared-prod/firefox_desktop/serp_events/view.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/review_checker_clients_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/review_checker_clients_v1/schema.yaml
sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/review_checker_clients_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/review_checker_clients_v1/schema.yaml

android and (possibly) iOS review checker clients tables are missing metrics/dimensions for fx_dau, user_has_onboarded, and nimbus_disabled_shopping.  this is a PR to kick off making those changes
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1962)

missing-mobile-fields-review-checker

---

sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_2_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_4_v1/query.sql

This can be merged once PR: https://github.com/mozilla/bigquery-etl/pull/4562 has been merged.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1976)

feat(): updated fenix_derived.funnel_retention_clients_* to use clients view instead of table directly

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v2/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v2/moz-fx-data-shared-prod.telemetry_derived.clients_daily_v6.schema.json

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1980)

Bug 1864722 - Fix column name typo

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/metadata.yaml

For manual task dependencies specified in `metadata.yaml` files via `depends_on`, if the referenced task is in the same DAG with no execution delta then we should generate a normal intra-DAG task dependency, not an external task sensor.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1982)

Generate normal task dependencies from `depends_on` if the task is in the same DAG

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v2/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v2/schema.yaml

Looks like we forgot to include this field when originally creating the v2. It appears to be used downstream and hence why the query needs to be updated to include it.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1978)

feat(): updated fenix_derived.firefox_android_clients_v2 to include reported_baseline_ping field

---

dags.yaml
sql/moz-fx-data-shared-prod/mozilla_org/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_org/ga_sessions/view.sql
sql/moz-fx-data-shared-prod/mozilla_org_derived/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/checks.sql
sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/schema.yaml
tests/sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/moz-fx-data-marketing-prod.65789850.ga_sessions_20230331.schema.json
tests/sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/test_single_day/expect.yaml
tests/sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/test_single_day/moz-fx-data-marketing-prod.65789850.ga_sessions_20230331.yaml
tests/sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/test_single_day/query_params.yaml

This table aggregates session-level data from GA.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1963)

Add ga_sessions_v1 table & view

---

bigquery_etl/cli/utils.py
sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1993)

Add session date param; fix checks CLI bug

---

sql/moz-fx-data-shared-prod/firefox_accounts/docker_fxa_admin_server_sanitized/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v2/schema.yaml

`errorGroups` field was added in `docker_fxa_admin_server_sanitized_v2` and breaks the UNION.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2005)

Bug 1865716 - Include errorGroups in legacy docker_fxa_admin_server_sanitized query

---

bigquery_etl/cli/query.py

[DS-3361](https://mozilla-hub.atlassian.net/browse/DS-3361)
Documentation after changes to the `bqetl query initialize` command.
The [documentation for this command](https://mozilla.github.io/bigquery-etl/bqetl/#initialize) is updated with the docs generation.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2011)
[DS-3361]: https://mozilla-hub.atlassian.net/browse/DS-3361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DS-3361. Update documentation of initialize command.

---

.circleci/config.yml
.circleci/post-diff.js

This adds a link to PR diff comment to link to the full diff that is now stored as a CircleCI artifact
This also addresses https://github.com/mozilla/bigquery-etl/issues/4573 by adding the `--new-file` option
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2012)

Link to full diff in git comments

---

dags.yaml

This DAG is [active and running since Oct, 2023](https://workflow.telemetry.mozilla.org/dags/bqetl_kpis_shredder/grid?search=bqetl_kpis_shredder).

Correct DAG description as DAG is currently active.

---

.circleci/config.yml

This is a workaround for CI jobs timing out with `Too long with no output (exceeded 10m0s): context deadline exceeded` error.
Integration tests seem to especially prone to this failure because they are executed in parallel with pytest-xdist which captures test output during the run.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2023)

Increase no_output_timeout for long-running CI jobs

---

sql/moz-fx-data-shared-prod/fenix/funnel_retention_clients/view.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_2_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_2_v1/schema.yaml
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_4_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_4_v1/schema.yaml
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_week_4_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_week_4_v1/schema.yaml

The following tables will need to be redeployed and rebuild in order to update the schemas:
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1974)

feat(): updating fxa android funnel to support install_source filtering downstream

---

sql_generators/urlbar_events/templates/schema.yaml

This field was added to the schema twice
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2041)

Fix num_chars_typed in urlbar_events schema

---

sql/moz-fx-data-shared-prod/telemetry/desktop_acquisition_funnel/view.sql

Copy-paste from `mozdata.analysis.gkabbz_sample_desktop_funnel`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2080)

Add desktop_acquisition_funnel view

---

bigquery_etl/shredder/config.py

feat(): firefox_ios source added to shredder config
This is to enable us to add firefox_ios client level tables to the shredder configuration for "Shredding"
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2111)

feat(): firefox_ios source added to shredder config

---

dags.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/baseline_clients_yearly_v1/checks.sql

This is currently causing the `bqetl_firefox_ios` DAG to fail.
Now the render command appears to render a valid query that can be executed:
```
$ ./bqetl check render --sql_dir=sql --project_id=moz-fx-data-shared-prod firefox_ios_derived.baseline_clients_yearly_v1 --parameter=submission_date:DATE:2023-
11-30
#fail
WITH non_unique AS (
SELECT
COUNT(*) AS total_count
FROM
`moz-fx-data-shared-prod.firefox_ios_derived.baseline_clients_yearly_v1`
WHERE
submission_date = "2023-11-30"
GROUP BY
client_id
HAVING
total_count > 1
)
SELECT
IF(
(SELECT COUNT(*) FROM non_unique) > 0,
ERROR(
"Duplicates detected (Expected combined set of values for columns ['client_id'] to be unique.)"
),
NULL
);
#fail
-- Should have a partition with rows for each date
WITH min_row_count AS (
SELECT
COUNT(*) AS …
```

bug(1867537): fixing broken test for firefox_ios_derived.baseline_clients_yearly_v1

---

bigquery_etl/glam/templates/view_sample_counts_v1.sql
sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/query.sql

Fixes [GLAM Desktop imports](https://workflow.telemetry.mozilla.org/dags/glam_glean_imports/grid?tab=graph&dag_run_id=scheduled__2023-12-03T05%3A00%3A00%2B00%3A00&task_id=Prod_glam.glam_import_desktop_aggs_release) failure that happen today: 
```psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type bigint: "1.01033992827342e+15"```
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2124)

GLAM avoid scientific notation for big sample counts

---

bigquery_etl/shredder/config.py
sql/moz-fx-data-shared-prod/firefox_ios/clients_activation/view.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/clients_activation_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/clients_activation_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/clients_activation_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/clients_activation_v1/schema.yaml

The purpose of this change is to avoid the activations table diverging away from the clients table. This is currently possible, as both the clients and activations table are built independently using different sources. Naturally, this resulted us observing unexpected differences in the client counts between the two tables. This should not be the case and is something that is addressed by this change.
This change aims to improve the two following aspects of this data model:
1. Make the data lineage simpler and representative of the expected stage in the data lifecycle (there should be no activation for a client, unless they are recorded as a client in the clients table).
2. Remove the self (previous state) dependency from this model. This simplifies the logic and makes each partition …

feat(DENG-2083): added firefox_ios_derived.clients_activation_v1 and corresponding view

---

bigquery_etl/cli/query.py
tests/cli/test_cli_query.py

Add support for `dataset_partition_offset` for `bqetl query backfill`. Also require a `metadata.yaml` file for backfilling a table
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2098)

Support offset backfills, require metadata 

---

docs/reference/data_checks.md
sql/mozfun/hist/extract_histogram_sum/README.md
sql/mozfun/hist/extract_keyed_hist_sum/README.md
sql/mozfun/map/extract_keyed_scalar_sum/README.md
sql/mozfun/norm/fenix_app_info/metadata.yaml
sql/mozfun/norm/fenix_build_to_datetime/metadata.yaml
sql/mozfun/norm/get_windows_info/README.md
sql/mozfun/norm/os/metadata.yaml

Three fixes, all causing slight misrendering of the docs, all changes explained in their respective commit messages.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2118)

Doc fixes: less newlines, all UDFs get a ToC entry, fix broken link

---

sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql

DIM checks from here have been moved over to BQETL data checks:
- https://github.com/mozilla/dim/blob/main/dim_checks/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/dim_checks.yaml
- https://github.com/mozilla/dim/blob/main/dim_checks/moz-fx-data-shared-prod/telemetry/unified_metrics/dim_checks.yaml
---
*In the future*, we should turn some of these checks into macros:
- membership test (validate that a value in a column is expected)
- value length check
- value check to make sure it matches a regex expression.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2127)

feat(DENG-2049): Migrated DIM checks over to ETL checks for telemetry_derived.unified_metrics_v1

---

sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.checks.sql

All checks are turned into warning checks to avoid potentially breaking the pipeline tomorrow. Over time we can promote some of these to be fail checks.
---
This will also add the checks for all products using this specific sql generator template.
Example rendered output for org_mozilla_fenix_nightly_derived.baseline_clients_last_seen_v1 for submission_date `2023-12-03`:
```
#fail
WITH non_unique AS (
SELECT
COUNT(*) AS total_count
FROM
`moz-fx-data-shared-prod.org_mozilla_fenix_nightly_derived.baseline_clients_last_seen_v1`
WHERE
submission_date = "2023-12-03"
GROUP BY
client_id
HAVING
total_count > 1
)
SELECT
IF(
(SELECT COUNT(*) FROM non_unique) > 0,
ERROR(
"Duplicates detected (Expected combined set of values for columns ['client_id'] to be unique.)"
),
NULL
);
#fail
WITH …
```

feat(DENG-2120): migrated over checks defined in DIM for baseline_clients_last_seen fenix.

---

sql/moz-fx-data-shared-prod/monitoring_derived/structured_error_counts_v2/script.sql

Typo, `ping_count` appeared one too many times...
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2141)

Fix structured_error_counts query

---

sql/moz-fx-data-shared-prod/telemetry/clients_daily/view.sql
sql/moz-fx-data-shared-prod/telemetry/clients_daily_joined/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/clients_daily_joined/view.sql

The goal is to deprecate `telemetry.clients_daily_v6` in favour of `telemetry.clients_daily_joined`. Reduces the number of misdirections from 2 to 1. 
Before:
`telemetry_derived.clients_daily_v6` -> `telemetry_derived.clients_daily_joined_v1` -> `telemetry.clients_daily_v6` -> `telemetry.clients_daily`
After:
`telemetry_derived.clients_daily_v6` -> `telemetry_derived.clients_daily_joined_v1` -> `telemetry.clients_daily_joined` -> `telemetry.clients_daily`
This PR adds `telemetry.clients_daily_joined` I'll communicate via the usual deprecation process and create a follow-up PR to deprecate `telemetry.clients_daily_v6`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2142)

Create telemetry.clients_daily_joined 

---

bqetl_project.yaml

We skip `accounts_db_external.fxa_oauth_clients_v1` (`sql/moz-fx-data-shared-prod/accounts_db/**/*.sql`) in dry-run also for permissions reasons

Skip accounts_db.fxa_oauth_clients in view validation

---

docs/reference/airflow_tags.md

Adding `triage/confidential` to the Airflow Tags docs.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2164)

add triage/confidential tag to docs

---

docs/reference/data_checks.md
sql/moz-fx-data-shared-prod/internet_outages/global_outages_v1/checks.sql
sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql
sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.checks.sql
tests/checks/value_length.jinja

Example render command:
`$ ./bqetl check render --sql_dir=sql --project_id=moz-fx-data-shared-prod internet_outages.global_outages_v1 --parameter=submission_date:DATE:2023-12-03`
Output:
```
[...]
#warn
WITH value_length_checks AS (
SELECT
[IF(COUNTIF(LENGTH(country) <> 2) > 0, "country", NULL)] AS checks
FROM
`moz-fx-data-shared-prod.internet_outages.global_outages_v1`
WHERE
DATE(`datetime`) = "2023-12-03"
),
failed_columns AS (
SELECT
ARRAY_AGG(u IGNORE NULLS) AS checks
FROM
value_length_checks,
UNNEST(checks) AS u
)
SELECT
IF(
(SELECT ARRAY_LENGTH(checks) FROM failed_columns) > 0,
ERROR(
CONCAT(
"Columns with unexpected value length: ",
(SELECT ARRAY_TO_STRING(checks, ", ") FROM failed_columns)
)
),
NULL
);
``` …

feat(DENG-2156): added value_length check and updated some of the ETL checks to use the macro

---

bigquery_etl/dryrun.py

Running `CREATE OR REPLACE VIEW ...` on authorized views requires `datasets.update` permissions (which CI does not have). 
See current CI failure:
```
sql/moz-fx-data-shared-prod/telemetry/socorro_crash/view.sql ERROR
[{'code': 403, 'errors': [{'message': 'Access Denied: Dataset moz-fx-data-shared-prod:telemetry: Permission bigquery.datasets.update denied on dataset moz-fx-data-shared-prod:telemetry (or it may not exist).', 'domain': 'global', 'reason': 'accessDenied'}], 'response': {'headers': {'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'cache-control': 'private', 'content-encoding': 'gzip', 'content-type': 'application/json; charset=UTF-8', 'date': 'Mon, 11 Dec 2023 15:49:05 GMT', 'server': 'ESF', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, Referer', …
```

ci-fix Ignore dataset.update required permissions when dryrunning authorized views

---

sql/moz-fx-data-shared-prod/glam_derived/client_probe_counts_firefox_desktop_beta_v1/query.sql
sql/moz-fx-data-shared-prod/glam_derived/client_probe_counts_firefox_desktop_beta_v1/schema.yaml
sql/moz-fx-data-shared-prod/glam_derived/client_probe_counts_firefox_desktop_nightly_v1/query.sql
sql/moz-fx-data-shared-prod/glam_derived/client_probe_counts_firefox_desktop_nightly_v1/schema.yaml

I recently noticed that GLAM public dataset is outdated (latest version is 78) and this is due to the query reading from a deprecated table. I suggest that we use the following tables to fix it, because they're the last state of the data before importing data into into glam.

Glam public - update source tbl 

---

sql/mozfun/mobile_search/normalize_app_name/udf.sql

The test sql is failing due to no mention of namespace in the udf name.

Fix mobile_search udf

---

docs/reference/data_checks.md
sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql
sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.checks.sql
tests/checks/matches_pattern.jinja

This introduced `matches_pattern` etl check macro which allows us to specify a regex expression to test that values inside a column adhere to the regex defined pattern.
Checks already doing this via SQL have been updated to use the macro instead.
Example command:
`./bqetl check render --sql_dir=sql --project_id=moz-fx-data-shared-prod org_mozilla_fenix_derived.baseline_clients_last_seen_v1 --parameter=submission_date:DATE:2023-12-03`
Output:
```
[...]
#warn
SELECT
IF(
COUNTIF(normalized_channel NOT IN ("nightly", "aurora", "release", "Other", "beta", "esr")) > 0,
ERROR("Unexpected values for field normalized_channel detected."),
NULL
)
FROM
`moz-fx-data-shared-prod.org_mozilla_fenix_derived.baseline_clients_last_seen_v1`
WHERE
submission_date = "2023-12-03";
#warn
SELECT
IF(
COUNTIF(NOT …
```

feat(DENG-2175): added matches_pattern etl checks macro and updated tests to use it

---

sql/moz-fx-data-shared-prod/billing_syndicate/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/ctms/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/mdn_rumba/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/taskclusteretl/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/taskclusteretl_community/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/taskclusteretl_stage/dataset_metadata.yaml

Companion to https://github.com/mozilla-services/cloudops-infra/pull/5285
There's some documentation in https://mozilla-hub.atlassian.net/wiki/spaces/SRE/pages/27920974/BigQuery+shared-prod#BigQuery(shared-prod)-Addingsyndicatedatasets but I'm expecting real use cases in this repo to be sufficient as copypasta for most cases.
There's one more dataset I need to add either to this PR or private-bigquery-etl. I'll make that determination before merging this. …

Add dataset_metadata.yaml files for syndicates

---

sql/moz-fx-data-shared-prod/internet_outages/global_outages_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2200)

Bug 1868674 - Ignore certain fields in internet outage checks

---

bigquery_etl/docs/__init__.py
bigquery_etl/docs/mozfun/generate_mozfun_docs.py
docs/mkdocs.yml

I don't think we have live doc previews, so see screenshots in PR body. Also instructions to generate locally: 
`bqetl docs generate --output_dir=generated_docs` 
`cd generated_docs` 
`mkdocs serve`  
Refactor the generate udf docs script and add support rendering UDFs in shared-prod.udf and shared-prod.udf_js. Also supports rendering a few missing UDF datasets from the production docs `Assert.*` and `Ltv.*`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2202)

Support shared-prod UDFs in UDF docs

---

sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_logical_subscriptions_history_v1/query.sql
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_history_v2/metadata.yaml
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_history_v2/query.sql
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_history_v2/schema.yaml
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_v2/metadata.yaml
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_v2/query.sql
sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_v2/schema.yaml

This adds a `stripe_subscriptions_v2` table containing the current state of Stripe subscriptions in the Stripe API-like format.
---
[DENG-974]: https://mozilla-hub.atlassian.net/browse/DENG-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2206)

Add `stripe_subscriptions_v2` ETL (DENG-974)

---

bigquery_etl/metadata/parse_metadata.py

91acdfce70318b2f49e7a4ce22322dc9e820ce38 (in #4663) added this, which in turn broke (at least) doc generation.
See failure in https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/27883/workflows/c2e70f7c-268e-44d3-8763-4ffd8ea237ef/jobs/297400
This adds it as an optional field, which makes everything parse again.
Tested by running locally:
```
PATH="venv/bin:$PATH" script/bqetl docs generate --output_dir=generated_docs/
```
(with stuff from the `generated-sql` branch included in the `sql` dir for completeness)
┆Issue …

Add `syndication` as possible metadata field

---

docs/reference/data_checks.md
tests/checks/matches_pattern.jinja

Now we can specify how many percent of rows can fail the check before causing the check to fail.
Example rendered check with a default:
```
#warn
{{ matches_pattern(column="country", pattern="^[A-Z]{2}$", where="submission_date = @submission_date", message="Some values in this field do not adhere to the ISO 3166-1 specification (2 character country code, for example: DE).") }}
```
```
#warn
SELECT
IF(
ROUND((COUNTIF(NOT REGEXP_CONTAINS(country, r"^[A-Z]{2}$"))) / COUNT(*) * 100, 2) > 0,
ERROR(
"Some values in this field do not adhere to the ISO 3166-1 specification (2 character country code, for example: DE)."
),
NULL
)
FROM
`moz-fx-data-shared-prod.telemetry_derived.unified_metrics_v1`
WHERE
submission_date = "2023-12-13";
```
---
Example rendered check with a default overwrite:
``` …
```

feat(): added an option to matches_pattern to be able to specify percentage threshold / tolerance for failures for the check

---

sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1/metadata.yaml

Let the dependencies for the task resolve automatically by removing `referenced_tables`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2239)

[Bug 1869019] Fix task dependencies for fenix.clients_yearly

---

sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/query.sql

Bug 1865706 - Glam etl drops keys longer than 200 characters instead of truncating

---

dags.yaml

From bug, only most recent success matters

Bug 1815242 - Update bqetl_pocket triage notes

---

sql/moz-fx-data-shared-prod/accounts_db/fxa_accounts/metadata.yaml
sql/moz-fx-data-shared-prod/accounts_db/fxa_accounts/view.sql

Follow up to https://github.com/mozilla/bigquery-etl/pull/4578
This adds a new user-facing view to accounts table. After this lands we'll be able to remove `accounts_backend.accounts` and its underlying table. 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2251)

Add user-facing view to fxa_accounts

---

sql_generators/active_users/templates/desktop_checks.sql
sql_generators/active_users/templates/fenix_checks.sql
sql_generators/active_users/templates/mobile_checks.sql
tests/checks/matches_pattern.jinja

As per discussion with the owner of this dataset, the check needs filter out non-glean data in order to get the correct numbers. See the discussion inside the related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1870691
Also, fixed a typo.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2236)

bug(1870691): fixed spelling mistake and added missing filter for focus android check

---

sql/moz-fx-data-shared-prod/telemetry_dev_cycle_derived/firefox_major_release_dates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_dev_cycle_derived/glean_metrics_stats_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_dev_cycle_derived/telemetry_probes_stats_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_dev_cycle_external/experiments_stats_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_dev_cycle_external/glean_metrics_stats_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_dev_cycle_external/telemetry_probes_stats_v1/metadata.yaml

Airflow is complaining about missing partition .. so adding it to aaaall the metadata now 
```
Cannot read partition
[2023-12-22, 17:46:54 UTC] {pod_manager.py:437} INFO - [base] information from a table that is not partitioned: moz-fx-data-shared-
[2023-12-22, 17:46:54 UTC] {pod_manager.py:437} INFO - [base] prod:telemetry_dev_cycle_derived.firefox_major_release_dates_v1$20231222
```
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2260)

fixing DENG-2219 DENG-2220 DENG-2221

---

sql/moz-fx-data-shared-prod/udf_js/decode_uri_attribution/udf.sql

- https://mozilla-hub.atlassian.net/browse/DENG-2263
- There are occasionally rows where the URI decode function fails, and this makes the view unusable (throws an error if you try to query that row) - so we added a try / catch to return null if the decoding fails.
- Once this is in place, will be easier to look at examples of where the decoding is failing, so we can make any changes to that as needed in the future
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2265)

DENG-2263 - Adding try catch to udf_js.decodeURIComponent

---

sql/moz-fx-data-shared-prod/ads/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/ads_derived/dataset_metadata.yaml

Members of the `ads` workgroup should have view access to everything in the `ads` dataset. There are some tables in `ads_derived` that are further restricted, so I didn't add this access to that dataset as well. The ads team is working on some changes to their permissioning/workgroup structure so this is likely to change in the future, but this should provide the essential access for now.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2291)

Grant ads dataset to ads workgroup

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_content_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_content_events_v1/query.sql

Because the underlying FxA tables have been removed.
This shouldn't be an issue since the FxA content server events are now included in the `fxa_gcp_stdout_events_v1` ETL ([DENG-722](https://mozilla-hub.atlassian.net/browse/DENG-722)).
This should resolve [bug 1872186](https://bugzilla.mozilla.org/show_bug.cgi?id=1872186) "Airflow task bqetl_fxa_events.firefox_accounts_derived__fxa_content_events__v1 failing since exec_date 2023-12-25".
---
[DENG-722]: https://mozilla-hub.atlassian.net/browse/DENG-722?atlOrigin=eyJpIjoiNWRkNTljN …

Unschedule `fxa_content_events_v1` ETL (bug 1872186)

---

sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/flows_live/view.sql

The old FxA AWS log tables no longer exist.
This should resolve [bug 1872185](https://bugzilla.mozilla.org/show_bug.cgi?id=1872185) "Airflow task bqetl_cjms_nonprod.cjms_bigquery__flows__v1 failing since exec_date 2023-12-25 20:00:00".
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2299)

Update CJMS nonprod flows view to use FxA GCP log tables (bug 1872185)

---

bigquery_etl/cli/view.py
bigquery_etl/view/__init__.py
bqetl_project.yaml

There's no need to dryrun views during view validation. Views can be dryrun directly from the dryrun CLI, and are already in CI part of the `dry-run-sql` CI job.
The view validation skips under "access_denied" in `bqetl_project.yaml` are really dryrun skips.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2300)

Remove dryrun from view validation in CI

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2
tests/data/dags/python_script_test_dag
tests/data/dags/simple_test_dag
tests/data/dags/test_dag_duplicate_dependencies
tests/data/dags/test_dag_external_check_dependency
tests/data/dags/test_dag_external_dependency
tests/data/dags/test_dag_with_check_dependencies
tests/data/dags/test_dag_with_dependencies
tests/data/dags/test_public_data_json_dag

At the moment the link in the Airflow DAG docs leads to the dag-file in `main` that no longer exists.
So switching the link to point to the file in the `generated-sql` branch should fix this.
And while I was here I thought it might be nice to add the tags to the docs, because inside the DAG in airflow one can't see what the impact is, which is annoying during triage.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2303)

DAG docs - fix broken links and add tags to docs

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/schema.yaml

[DENG-2259]: https://mozilla-hub.atlassian.net/browse/DENG-2259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2310)

Change VPN subscriptions attribution from first touch to last touch (DENG-2259)

---

sql_generators/glean_usage/common.py

The app ID was changed in mozilla/probe-scraper#670.
This should remove the currently failing ETL checks ([bug 1873429](https://bugzilla.mozilla.org/show_bug.cgi?id=1873429#c1)).
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2334)

Update Glean app ID for Mozilla VPN Cirrus (bug 1873429)

---

sql/moz-fx-data-shared-prod/subscription_platform_derived/services_v1/query.sql

Monitor Plus is a new subscription product being released this month.
---
[DENG-972]: https://mozilla-hub.atlassian.net/browse/DENG-972?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2345)

Add Monitor Plus to SubPlat consolidated reporting config (DENG-972)

---

sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2201)

Bug 1868850 - Remove failing warn checks from UM

---

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/query.py

Needed for monitoring materialized views (https://bugzilla.mozilla.org/show_bug.cgi?id=1873276).
Materialized view references are in a separate field `materialized_view_statistics.materialized_view` in the `INFROMATION_SCHEMA.JOBS` views. This PR adds them to the `referenced_tables` field. I think it's fine to treat them as referenced tables for the purpose of monitoring
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2321)

[Bug 1873276] Add references materialized views to bigquery_usage tables

---

sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_beta_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_nightly_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_release_aggregates_v1/metadata.yaml

I spelled mozilla with one "L"
Soon enough I'll be writing GLLAM

Fix typo on dependency task name

---

sql_generators/use_counters/__init__.py

After making the BQ table public, I need to update the generated views to point to the new, updating public tables instead of the old ones, since the old ones will be deprecated.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2388)

1866834 - update use counters views

---

sql/mozfun/norm/fenix_app_info/udf.sql

This incorrect test just happened to work before because of unescaped underscores in the UDF's `LIKE` patterns, but the underscores were properly escaped in #4810.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2390)

Fix test for `norm.fenix_app_info` UDF

---

sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql

This is causing part of our ETL execution flow to be blocked unintentionally.
This is a follow up to this commit https://github.com/mozilla/bigquery-etl/commit/8fc3567ad48292efd6594fde990d9e7c0d8e56c8 which accidentally introduced this bug.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2377)

# bug(): wrapping commented out test in jinja comment to exclude it from the final output

---

sql_generators/glean_usage/templates/event_flow_monitoring_aggregates_v1.script.sql

Fix null casting error and use app datasets
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2396)

Fix null casting in script

---

sql/moz-fx-data-shared-prod/firefox_ios/firefox_ios_clients/view.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/schema.yaml

This is because is_activated is incorrectly generated inside the firefox_ios_clients table.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2397)

feat(DENG-2083): updated the source of is_activated inside the firefox_ios_clients view

---

bigquery_etl/shredder/config.py
bqetl_project.yaml
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_delete_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v2/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v2/schema.yaml

Along with a view to combine the `fxa_delete_events_v1` and `fxa_delete_events_v2` data, and use that view for Shredder.
This is being done in the context of [DENG-1590](https://mozilla-hub.atlassian.net/browse/DENG-1590) "_Add the new FxA tables to Shredder configuration (if currently not cofigured)_", but should have been done back in September as part of [DENG-1035](https://mozilla-hub.atlassian.net/browse/DENG-1035) "_Apply migration changes to prod datasets_".
---
[DENG-1590]: …

Add `fxa_delete_events_v2` ETL based on FxA logs from GCP

---

bigquery_etl/cli/query.py
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/metadata.yaml

After https://github.com/mozilla/bigquery-etl/pull/4769, `no_partition` is no longer needed to backfill unpartitioned tables. PR removes mentions
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2356)

Remove remaining mentions of no_partition

---

bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2427)

Fix duplicate wait_for tasks in public data JSON DAG

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/init.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/schema.yaml

We found that there were some inconsistencies with how we were previously generating the value for `is_activated` inside `firefox_ios_clients_v1` (see: DENG-2083). Instead of using `new_profile_activations_v2` we decided to make a new table to calculate activation information. This is for two main reasons: 
1) Cleaner data lineage
2) new_profile_activations has an awkward self dependency which makes the model more fragile and more difficult to recalculate if necessary.
This PR removes is_activated field related logic from the query file for firefox_ios_clients_v1
This information instead comes from `firefox_ios_derived.clients_activation_v1` and is also accessible via the `firefox_ios.firefox_ios_clients` view. …

feat(DENG-2432): removed activations field from firefox_ios_clients_v1

---

sql/moz-fx-data-shared-prod/firefox_ios/firefox_ios_clients/view.sql

Follow up to: https://github.com/mozilla/bigquery-etl/pull/4853
This also updates the view which was missed in the original PR.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2434)

feat(DENG-2432/): irefox ios clients v1 removing activation field view update

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_auth_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_content_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_device_command_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_stdout_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_auth_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_content_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_stdout_events_v1/metadata.yaml

This change removing scheduling configuration for FxA queries which use log tables coming from the AWS version of the service. This service is no longer active and has been fully migrated over to GCP.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2398)

feat(DENG-1697): Descheduled all FxA queries using the old AWS based tables

---

bigquery_etl/shredder/config.py

feat(DENG-1590): added existing fxa tables to shredder config

---

bigquery_etl/cli/stage.py
bigquery_etl/routine/parse_routine.py

The `deploy-changes-to-stage` CI for #4860 is currently failing because `bqetl stage` isn't first creating the dataset it's trying to deploy the new stored procedure into.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2453)

Fix `bqetl stage` to create parent dataset for stored procedures

---

bigquery_etl/view/__init__.py
sql_generators/derived_view_schemas/__init__.py
tests/data/test_sql/moz-fx-data-test-project/test/default/view.sql
tests/view/test_view.py

View schema files are only used for adding descriptions, this PR adds that assumption to the generator. 
Previously it was attempting to generate schema files for all views, including where they wouldn't/didn't have descriptions and so wouldn't be useful. This added a lot of extra dryruns to CI. 
Also copies the reference schema directly for "simple"/default views.  
A few schema files will be removed from this PR (see diff comment), but these aren't currently used for anything.

Restrict derived view schema generation to views with upstream schema files and directly copy reference schemas for simple views.

---

sql/moz-fx-data-shared-prod/fenix/client_ltv/view.sql
sql/moz-fx-data-shared-prod/fenix/ltv_state_values/view.sql
sql/moz-fx-data-shared-prod/fenix/ltv_states/view.sql
sql/moz-fx-data-shared-prod/fenix_derived/client_ltv_v1/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/client_ltv_v1/metadata.yaml
sql/moz-fx-data-shared-prod/fenix_derived/client_ltv_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/client_ltv_v1/schema.yaml
sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v1/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v1/metadata.yaml
sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v1/schema.yaml

The previous LTV table has a state value per-day. This table takes the most recent state value for each client, so the grain is simply `client_id`. The view joins with the state predictions, so we get the historic ad clicks and predicted future ad clicks for each client.

Add table for Android Client LTV

---

bigquery_etl/cli/query.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2480)

Make `bqetl query initialize` work for ETLs using `is_init()` in non-default projects

---

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_tables_inventory_v1/query.py
sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_tables_inventory_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/schema.yaml

The table field can't just be renamed since it's essentially deleting an existing row (and adding a new one).
I'd instead recommend renaming the fields in the public views (https://github.com/mozilla/bigquery-etl/blob/dd8d736c99bd9b4efd6b666e4fe424b86029bd20/sql/moz-fx-data-shared-prod/monitoring/bigquery_tables_inventory/view.sql). Although that would break all the dashboards that are currently using this table.
Or alternatively, we could add `table_creation_date` without removing `creation_date`, and optionally hide the `creation_date` field in the view.
Reverts mozilla/bigquery-etl#4797
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2493)

Revert "change 'creation_date' to 'table_creation_date' to be more clear"

---

bigquery_etl/cli/query.py

For new tables using `on_init()` the schemas need to be generated before deploying tables 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2495)

Run schema updates for new tables using is_init()

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
sql/moz-fx-data-shared-prod/static/country_codes_v1/description.txt
sql/moz-fx-data-shared-prod/static/country_codes_v1/schema.json

This is needed for `static.country_codes_v1` to be joinable to Google Search Console data, which uses ISO 3166 alpha-3 country codes ([DENG-1733](https://mozilla-hub.atlassian.net/browse/DENG-1733)).
---
[DENG-1733]: https://mozilla-hub.atlassian.net/browse/DENG-1733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2500)

Add ISO 3166 alpha-3 country codes to `static.country_codes_v1`

---

bigquery_etl/cli/query.py

Such ETLs don't write to a table when they run, so the table shouldn't be deployed at all.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2503)

Don't deploy ETLs with `destination_table: null` set in their scheduling metadata

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/events_live/metadata.yaml

I'll write a script to reconcile the remaining places where this is an issue later.
This isn't urgent to merge because I've manually applied these changes to production.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2521)

Fix table access where dataset ACLs have changed due to deprecation

---

sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2526)

bug(1876789): Delete active_users_aggregates_v1/checks.sql as no longer needed due to the dataset deprecation

---

sql/moz-fx-data-shared-prod/telemetry_derived/events_v1/metadata.yaml

See slack discussion. In use by https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/telemetry/events_v1/view.sql#L48C30-L48C58. I'm not sure how/if this is updated but we should probably add owner metadata too.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2523)

Remove deprecation metadata from telemmetry_derived.events_v1

---

sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v1/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v2/checks.sql
sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2524)

bug():  remove unwanted space in bqetl checks labels

---

sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/init.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/query.sql

Adds a `query_type` field ("branded" vs "non-branded") to suggest event aggregates, joining to the AMP suggestions data that we are now loading into BQ.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2507)

AD-178 quick_suggest query type field

---

script/entrypoint

pytest runs tests in parallel, some of which call the entrypoint script which is overwriting `/tmp/gcp.json`, and if one test's BigQuery client is trying to read `/tmp/gcp.json` while another invocation of the entrypoint script is in the middle of overwriting it, then the file could be read while it's in an empty or incomplete state.
This PR works around that by creating a unique `gcp.json` temp file for every invocation of the entrypoint script.
I'm hopeful this will eliminate the annoying "_File /tmp/gcp.json is not a valid json file_" error we keep getting sporadically in CI jobs. 🤞 
--- …

Create unique `gcp.json` temp files to avoid file contention from parallel tests

---

sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/init.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/query.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/init.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/query.sql
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_aggregation/expect.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_aggregation/firefox_desktop.quick_suggest.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_aggregation/moz-fx-data-bq-fivetran.admarketplace_suggest.blocks.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_overactive_filter/expect.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_overactive_filter/firefox_desktop.quick_suggest.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_overactive_filter/moz-fx-data-bq-fivetran.admarketplace_suggest.blocks.yaml

Fixed version of #4901 -- pulls `query_type` from AMP suggestions data and adds that to suggest event aggregates
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2557)

AD-178 Add query_type to event_aggregates_suggest and event_aggregates

---

.circleci/config.yml

We don't need to run `private-generate-sql` for each PR. This step is only relevant when creating the docker image on `main`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2596)

Don't run private-generate-sql for each PR

---

sql/moz-fx-data-shared-prod/glam_etl/glam_desktop_beta_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_desktop_nightly_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_desktop_release_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_beta_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_nightly_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_release_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_fog_beta_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_fog_nightly_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/glam_etl/glam_fog_release_aggregates_v1/metadata.yaml

As a preparation for GLAM serving data from BQ. Ensures proper access to production tables.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2594)

Add workgroup_access to GLAM prod tables

---

sql/moz-fx-data-shared-prod/apple_ads/ad_group_report/view.sql
sql/moz-fx-data-shared-prod/apple_ads/campaign_report/view.sql
sql/moz-fx-data-shared-prod/apple_ads/keyword_report/view.sql
sql/moz-fx-data-shared-prod/apple_ads/organization_report/view.sql
sql/moz-fx-data-shared-prod/apple_ads/search_term_report/view.sql

No changes to logic required as the timzone used corresponds to your Apple Ads accounts default timezone settings. Added a note to avoid confusion in the future.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2601)

bug(DENG-2598): No logic changes required, added a note to the views to for clarification

---

sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v2/schema.yaml

Updating the "bounces" column description to accurately match the column logic; the old logic in GA3 was the number of single page sessions, but now in GA4, it is the number of sessions without an engaged session event
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2605)

DENG-2492 - update column desc to accurately reflect new column logic

---

sql/moz-fx-data-shared-prod/udf_js/main_summary_active_addons/udf.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2617)

Fix main_summary_active_addons to handle additional addon fields

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v1/schema.yaml

follows-up: https://github.com/mozilla/bigquery-etl/pull/4950
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2618)

bug(): added submission_date and made it the partition key to address rows belonging to different partitions error

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v2/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v2/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v2/schema.yaml

Create query for version 2 of table clients_last_seen. This PR queries clients_first_seen_v2 directly, therefore **it should only be merged AFTER** its [backfill DS-3101](https://mozilla-hub.atlassian.net/browse/DS-3101) and [validation DS-3102](https://mozilla-hub.atlassian.net/browse/DS-3102).
The schema needs to be deployed.
This PR doesn't impact any other tables. --The view and DAG changes are moved to a separate PR to enable running the backfill and validations of this new version first.

DS-3104 Create version 2 of Clients Last Seen

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2622)

bug(): fix fenix_derived feature_usage_metrics_v1 SQL missing submission_date in group by

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2
tests/data/dags/python_script_test_dag
tests/data/dags/simple_test_dag
tests/data/dags/test_dag_duplicate_dependencies
tests/data/dags/test_dag_external_check_dependency
tests/data/dags/test_dag_external_dependency
tests/data/dags/test_dag_with_check_dependencies
tests/data/dags/test_dag_with_check_table_dependencies
tests/data/dags/test_dag_with_dependencies
tests/data/dags/test_public_data_json_dag

Fixes https://github.com/mozilla/bigquery-etl/issues/4895
We should wait with merging until next week and make those on Airflow Triage aware of these changes
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2506)

Remove gke_command usages

---

sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/query.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/query.sql
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_aggregation/moz-fx-ads-prod.adm.blocks.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_overactive_filter/moz-fx-ads-prod.adm.blocks.yaml

We previously set up a workaround via Box + Fivetran to pull this data into BQ; this switches over to pulling from a table the Ads team maintains and updates automatically each time we get a new file from AMP and load it into Remote Settings
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2641)

AD-178 Update event_aggregates tables to pull query_type from the Ads team's table

---

sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/query.sql
sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/schema.yaml

This change does 2 things: 
- Adds comments to code to explain some of the logic
- Fixes "time on site" calculation to convert to seconds

DENG-2492 - update time on site to convert to seconds, add comments

---

.circleci/config.yml

This change is to speed up the CI for PRs. One of the longer running tasks is `generate-sql` (and `main-generate-sql-and-dags`). In many cases re-running SQL generators is not necessary, instead we can pull in the `generated-sql` branch and merge it with changes made in the PR. This can save 10-15 minutes of CI run time.
There are still some cases when the SQL generation needs to run though:
- when the PR changes or adds a SQL generator
- when a SQL file gets deleted. Since merging `generated-sql` with the changes made in the PR is additive, files that got deleted in a PR will still show up (because they weren't yet deleted on `generated-sql`) and would change generated DAGs. https://github.com/mozilla/bigquery-etl/issues/4068 could solve this issue
- we always want to run SQL generation …

Use caching in generate-sql

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv

I noticed `country_codes_v1` incorrectly lists Singapore as being in Africa.
This updates `country_codes_v1` using the latest region data from the same [UN Statistics Division source](https://unstats.un.org/unsd/methodology/m49/overview) that was used when the region data was added in #2839, which fixes the Singapore record, as well as updating a few other records.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2656)

Update `country_codes_v1` regions from latest UN Statistics Division data

---

sql/moz-fx-data-shared-prod/mozilla_vpn/vat_rates/view.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/vat_rates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/vat_rates_v2/data.csv
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/vat_rates_v2/description.txt
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/vat_rates_v2/schema.json

Because the source Google Sheet for the `mozilla_vpn_derived.vat_rates_v1` ETL has apparently been deleted ([bug 1878898](https://bugzilla.mozilla.org/show_bug.cgi?id=1878898)).
This also adds some VAT rates that were missing from the source Google Sheet.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2654)

Replace the `mozilla_vpn_derived.vat_rates_v1` ETL with a CSV file (bug 1878898)

---

sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/query.sql

This logic change helps make sure that if a session does not have a session start event, that it still shows up in the table
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2670)

DENG-2492 - update logic of new ga_sessions_v2 table

---

.circleci/config.yml

https://mozilla-hub.atlassian.net/browse/DSRE-65?focusedCommentId=820935
This is part of the prep for using OIDC auth. We're expecting to use the SA whose key is currently in the `data-eng-circleci-tests` context for tests eventually but without needing the hard-coded credentials. For now, this switches CI to use the creds for the SA in the CircleCI environment variables of this repo (used when context is left unspecified e.g. `deploy-changes-to-stage`). https://github.com/mozilla-services/cloudops-infra/pull/5371 appears to have been the only change needed to get tests working, but I expect more significant code changes to be required to wire this back up into the SRE-managed tests project.
in the logs of the `manual-trigger-required-for-fork` CI task together …

Stop using data-eng-circleci-tests context in CI

---

script/entrypoint

#4924 didn't eliminate the "_File /tmp/gcp.json is not a valid json file_" errors we keep getting sporadically in CI jobs, and I think the reason is that the individual parallelized tests that call the entrypoint script weren't getting their own unique `gcp.json` files and instead were using (and overwriting) the same "unique" `gcp.json` file created by the initial entrypoint script run that kicked off the overall test run, since the `GOOGLE_APPLICATION_CREDENTIALS` environment variable was set by that initial entrypoint script.
This PR takes a different tack and goes back to using one `gcp.json` file, but avoids overwriting that `gcp.json` file unless it doesn't contain the expected credentials.
---
in the logs of the `manual-trigger-required-for-fork` CI task …

Don't overwrite existing `gcp.json` files unless that's actually necessary

---

bigquery_etl/shredder/config.py

This is causing some count discrepancies.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2679)

bug(): adding firefox_ios_derived.retention_clients to shredder config

---

bigquery_etl/cli/query.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2702)

Fix `bqetl query schema deploy` to find script ETLs specified as `{dataset}.{table}`

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v2/metadata.yaml

Rationale for these changes:
- Simplify the data lineage of these tables (higher grain built on top of lower grain tables)
- Only include relevant dimensions in the tables
- Include all important dimensions in the first_seen table to simplify the usage
---
Changes made:
- Added a TODO note to all v1 queries as a reminder to remove the scheduling settings once the corresponding v2 table is backfilled and verified to be healthy.
- Added scheduling settings to fxa_users_*_v2 tables
- Small clustering setting adjustments for `fxa_users_first_seen_v2` and `fxa_users_daily_v2`, `fxa_users_last_seen_v2`.
Follow-up actions required:
- Redeploy `fxa_users_first_seen_v2`, `fxa_users_daily_v2` and `fxa_users_last_seen_v2` tables (to apply new clustering settings)
- Backfiill the three tables in the …

feat(): added scheduling settings to all fxa_users_*_v2 queries

---

sql/moz-fx-data-shared-prod/telemetry/clients_first_seen/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/clients_first_seen/view.sql

Update view `telemetry.clients_first_seen` to query version 2 of the table.
This PR **should only be merged** after running all validations in the table and the closing [DS-3102](https://mozilla-hub.atlassian.net/browse/DS-3102).
[DS-3102]: https://mozilla-hub.atlassian.net/browse/DS-3102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1466)

DS-3103. Update view clients_first_seen to query v2

---

bigquery_etl/dependency.py
sql/moz-fx-data-shared-prod/mozilla_org/gclid_conversions/view.sql
tests/test_dependency.py

Census, the reverse ETL tool, requires a 1:1 mapping from source to destination. Because we're sending conversion events, we need 1 row per-conversion event.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2075)

GROWTH-101 - Update gclid_conversions view to 1-row per conversion

---

sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/query.sql

The product_download event was used for a long period only, but recently was split into 4 separate types. To not double count, before a certain date, should use the "product_download" event only, after that date, use the 4 types only.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2755)

DENG-2492 Update Product Download Event Types

---

sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v2/query.sql

The product_download event was used for a long period only, but recently was split into 4 separate types. To not double count, before a certain date, should use the "product_download" event only, after that date, use the 4 types only.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2756)

DENG-2492 Update Product Download Types for www_site_landing_page_metrics_v2

---

bigquery_etl/schema/stable_table_schema.py

The `glean/glean` schema now has `mozPipelineMetadata` as of mozilla-services/mozilla-pipeline-schemas#793, so we need to be more specific to continue excluding it.
Depends on mozilla-services/mozilla-pipeline-schemas#805.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2761)

Ignore stable table schemas without `bq_dataset_family` and `bq_table` metadata

---

sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/script.sql

Updates to try to make query process less data - old merge would update everything each day, now this is just getting all events from the last 3 days leading up to the submission date, figuring out the unique client ID / session IDs these belong to, then re-calculating the entire session's data for that session, across the whole events_ source table from Google.  
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2759)

DENG-2492 - Update logic for ga_sessions_v2

---

sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/metadata.yaml

Please refer to https://mozilla-hub.atlassian.net/browse/DENG-2770
Following a 2 weeks notice, all the related code in the bqetl repo and the actual BQ table will be deleted.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2772)

Deprecate urlbar client daily table

---

bqetl_project.yaml

Fixes [1880270](https://bugzilla.mozilla.org/show_bug.cgi?id=1880270)
bqetl_glam_refresh_aggregates failing with error
```Invalid value for '--project-id' / '--project_id': Invalid project  moz-fx-data-glam-prod-fca7 ```
This will allow the query to be executed on the project.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2771)

Bug 1880270 Allow glam-prod project queries to execute

---

bqetl_project.yaml

GLAM views added in https://github.com/mozilla/bigquery-etl/pull/5020 are failing the `dry-run-sql` test because of access restrictions.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2779)

Exclude GLAM views from dry run

---

bigquery_etl/metadata/publish_metadata.py

It looks like publish metadata airflow task is failing with `google.api_core.exceptions.NotFound` when table does not exist:  
https://workflow.telemetry.mozilla.org/dags/bqetl_artifact_deployment/grid?dag_run_id=scheduled__2024-02-14T00%3A00%3A00%2B00%3A00&task_id=publish_metadata&tab=logs
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2787)

Fix publish metadata task failing when table not found

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_content_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_gpu_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_parent_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_boolean_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_histogram_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_keyed_scalar_aggregates_v1/metadata.yaml

Attempts to fix `publish_metadata` job by removing `metadata.yaml` files from GLAM folders that are not tables. 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2797)

Bug 1880837: Remove metadata.yaml from GLAM folders that aren't tables

---

bqetl_project.yaml

We added this app in https://bugzilla.mozilla.org/show_bug.cgi?id=1879155 but it got deprecated before the process was finished.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2799)

Don't generate glean_usage queries for moso_mastodon_android

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
tests/data/dags/simple_test_dag

This is to replace `airflow-provider-fivetran` Airflow Fivetran provider which has been deprecated last year.
The following PR should be merged in parallel: https://github.com/mozilla/telemetry-airflow/pull/1914
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2725)

feat(DENG-2682): Update fivetran imports to use airflow-provider-fivetran-async

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
tests/data/dags/simple_test_dag

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2815)

fix(): Remove the usage of fivetran sensor to avoid double wait / blocking

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
tests/data/dags/simple_test_dag

This only makes sense now that we've switched to Astronomer's Fivetran Airflow provider package (https://github.com/mozilla/telemetry-airflow/pull/1922, https://github.com/mozilla/bigquery-etl/pull/5080), which allows us to have a single task that both starts the Fivetran sync and waits for it to complete.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2818)

Limit Fivetran task concurrency so it only tries to run one sync per connector at a time

---

bigquery_etl/view/__init__.py
tests/view/test_view.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1868244
This adds a dry run step to the function that checks if a view has changes to be published.  The dry run result includes the schema of the resulting view that can be compared to the active schema.
Did a quick performance test locally with this:
```python
for view in _collect_views(None, "sql", "moz-fx-data-shared-prod", False, False):
view.has_changes()
```
The dry run adds on average ~0.4s to every view that reaches that code path.  The total time to check all the views after running `./script/bqetl generate stable_views` was 526 seconds without dry run and 688 seconds with dry run.  This seems acceptable to me but I don't have all the context around how this is run other than in the airflow task.
in the logs of …

Bug 1868244 Publish views if dry run schema differs from deployed

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
tests/data/dags/simple_test_dag
tests/data/dags/test_dag_duplicate_dependencies
tests/data/dags/test_dag_with_bigquery_table_sensors
tests/data/dags/test_dag_with_check_dependencies
tests/data/dags/test_dag_with_dependencies

So that if any of the ETLs use `depends_on` to manually depend on one of those external dependencies the external task variable will be guaranteed to exist before it's referenced in the `set_upstream()` call.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2844)

Output DAG tasks for external dependencies first

---

sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/schema.yaml

update fenix feature usage events table using ping parse time logic
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2768)

feat(): Update fenix feature usage events table

---

bigquery_etl/view/__init__.py

More specific error message when unable to parse the view (`sqlparse.parse` returns an empty tuple), this lets us know which view failed to parse. 
Instead of a generic `IndexError`: e.g. https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/30667/workflows/e2d4f47e-6028-42e5-ac84-5b3c32c58d14/jobs/330932
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2884)

Preempt IndexError when unable to parse view content

---

sql_generators/glean_usage/templates/events_stream_v1.metadata.yaml
sql_generators/glean_usage/templates/events_stream_v1.query.sql

Wil pointed out that the `events_stream` tables have both `submission_date` and `submission_timestamp` fields. Currently, the tables are partitioned on `submission_date` and are requiring a partition date filter. This is causing some issues when using the explores in Looker, but is also potentially quite inconvenient for users that want to filter down to a specific timestamp range and now need to filter on both `submission_date` and `submission_timestamp`. Looker is representing timestamps and dates as dimension groups. In this case with both `submission_date` and `submission_timestamp` being present there is a naming "collision" with `submission_timestamp` taking precedence resulting in the date filter not being applied to `submission_date`.
I think it would be more convenient to remove …

Remove submission_date from events_stream tables

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/accounts_backend/users_services_last_seen/view.sql
sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_last_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_last_seen_v1/query.sql
sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_last_seen_v1/schema.yaml

https://mozilla-hub.atlassian.net/browse/DENG-2095
Before we merge this, I think we should rename `user_id` to `user_id_hashed` in `accounts_backend_derived.users_services_daily_v1` and here.
@ksiegler1 I noticed that `language` is always null in `accounts_backend_derived.users_services_daily_v1` (and also here).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2882)

DENG-2095 Add accounts_backend.users_services_last_seen_v1

---

tests/checks/is_unique.jinja

A lot of those is_unique tests only have submission_date in the where but I'm currently work on something where I want the combination of columns to be unique for `is_current= True`. There will be multiple entries for `is_current = False` so the current error message does not reflect the truth and it's only expected to be unique for the where clause.
So adding it to the error message.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2898)

improve is_unique data check message

---

sql/moz-fx-data-shared-prod/telemetry_dev_cycle_external/experiments_stats_v1/query.py

adding a `/` at the end of the URL to appease the API
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2909)

DENG-2896 Telemetry Dev Cycle fix experimenter API

---

sql/moz-fx-data-marketing-prod/ga_derived/www_site_metrics_summary_v2/query.sql

Had to refactor code to update logic to track only Firefox Desktop downloads and not all downloads (Before, the code was including Klar, Mobile, etc downloads under the product download umbrella, but to match the logic used in the old table more closely, we only want to track Desktop downloads).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2922)

DENG-2919 Change logic for measuring product downloads

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
sql/moz-fx-data-shared-prod/static/country_codes_v1/schema.json

In order to avoid the need to define which countries have sponsored tiles live, a field is added to static.country_codes_v1 to denote countries with sponsored tiles.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2923)

Add sponsored tiles available field

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
tests/data/dags/simple_test_dag

#5083 tried to limit Fivetran task concurrency so it would only run one sync per connector at a time, but that didn't actually work because task concurrency limits apparently don't apply when tasks get deferred (maybe an Airflow bug?).  This will address that.
While having the operator be deferred while waiting for the Fivetran sync to complete would be ideal from an Airflow resource usage perspective, I believe having the sync behavior work as intended is more important, and having the Fivetran operator take up a worker slot while it's waiting shouldn't be a dealbreaker since that was the behavior until very recently when we switched to Astronomer's Fivetran Airflow provider package with its deferrable operator implementation (https://github.com/mozilla/telemetry-airflow/pull/1922, …

Change Fivetran Airflow operators to run synchronously so the task concurrency limit is respected

---

sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_2_v1/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_4_v1/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_week_4_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2934)

feat(): Added ETL checks to fenix_derived.funnel_retention_* tables

---

sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/query.sql
sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/schema.yaml

Updating logic for measuring product downloads; used to be all product downloads, now updated to Firefox Desktop downloads only (with differing logic used before and after 2/16/24 due to instrumentation changes)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2937)

DENG-2924 - update product download logic

---

sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports/view.sql

I'd like to add these fields to the existing view:
Product name or app name (Fenix, Focus, etc.)
Firefox version
Firefox channel
Operating system
Example fields when running the query:
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2900)

Fixes #5126 - Add additional fields to org_mozilla_broken_site_report.user_reports view

---

bqetl_project.yaml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1873431#c9 for context
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2933)

Bug 1873431 - Don't generate glean_usage queries for tiktokreporter

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/encrypted_keys_v1/metadata.yaml

This table is currently missing this file.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2907)

feat(): Add metadata.yaml for firefox_accounts_derived.encrypted_keys_v1

---

sql/moz-fx-data-shared-prod/fenix_derived/active_users_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/fenix_derived/active_users_aggregates_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/active_users_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/active_users_aggregates_v2/metadata.yaml
sql/moz-fx-data-shared-prod/focus_android_derived/active_users_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/focus_android_derived/active_users_aggregates_v2/metadata.yaml
sql/moz-fx-data-shared-prod/focus_ios_derived/active_users_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/focus_ios_derived/active_users_aggregates_v2/metadata.yaml
sql/moz-fx-data-shared-prod/klar_ios_derived/active_users_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/klar_ios_derived/active_users_aggregates_v2/metadata.yaml

These tables are currently missing a corresponding metadata.yaml files. This change aims to add it along with a label to indicate that these tables are now deprecated. The reason for this is that we do want to persist these tables in BQ.
The required `dataset_metadata.yaml` should still be added to the folder via the existing sql generation process.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2906)

feat(): adding metadata.yaml files for old (v1 and v2, current v3) with deprecated label

---

bigquery_etl/backfill/parse.py
bigquery_etl/backfill/utils.py
bigquery_etl/backfill/validate.py
bigquery_etl/cli/backfill.py
sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
tests/backfill/backfill.yaml
tests/backfill/test_dir_multiple/backfill.yaml
tests/backfill/test_dir_valid/backfill.yaml
tests/backfill/test_parse_backfill.py
tests/cli/test_cli_backfill.py

1. Renames Drafting -> Initiate to match Complete
2. Modifies the output of `bqetl backfill scheduled` so the contact and backfill details can be used directly for `SlackOperator`s.
3. Minor renames/refactor to shorten code.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2957)

DENG-2950 - Rename drafting -> initiate, modify json output of scheduled command

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/org_mozilla_ios_tiktok_reporter/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_ios_tiktok_reporter_derived/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_ios_tiktok_reporter_tiktok_reportershare/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_ios_tiktok_reporter_tiktok_reportershare_derived/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_tiktokreporter/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_tiktokreporter_derived/dataset_metadata.yaml

Discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1873431
Companion PR: https://github.com/mozilla-services/cloudops-infra/pull/5440, likely landing on the 4th
The files were copied from the generated branch and then updated to match workgroup expectations.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2947)

Bug 1873431 - restrict access to tiktok reporter datasets

---

sql/mozfun/json/from_nested_map/README.md
sql/mozfun/json/from_nested_map/metadata.yaml
sql/mozfun/json/from_nested_map/udf.sql
sql_generators/glean_usage/templates/events_stream_v1.query.sql

I'm not entirely sure that this works. Can we add a new UDF and use it in the same PR?
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2659)

Bug 1879039 - events stream: Convert nested maps in metrics

---

bqetl_project.yaml

This will fix errors in bqetl_glean_usage.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2995)

Bug 1873431 - Don't generate glean_usage queries for tiktokreporter app variants

---

bigquery_etl/backfill/parse.py
bigquery_etl/backfill/utils.py
bigquery_etl/cli/backfill.py
tests/cli/test_cli_backfill.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2967)

DENG-2950 - Update backfill commands to allow retrieving backfills scheduled for completion 

---

sql/moz-fx-data-shared-prod/telemetry/experiments_aggregates/view.sql

Follow-up on https://github.com/mozilla/bigquery-etl/pull/5191. The deleted view references this view so dry runs are failing
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3011)

Delete telemetry.experiments_aggregates view

---

sql/moz-fx-data-shared-prod/telemetry_derived/public_data_report_user_activity_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/public_data_report_user_activity_v1/query.sql

https://mozilla-hub.atlassian.net/browse/DENG-2894
https://mozilla-hub.atlassian.net/browse/DENG-2956
Adding countries and also taking ownership of the table since it's unclaimed.  Code in https://github.com/mozilla/firefox-public-data-report-etl/ will automatically pick up countries but data should also be backfilled, probably only for these countries so existing data doesn't change.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3063)

[DENG-2956][DENG-2894] Add Spain and Canada to public user activity report

---

.circleci/config.yml
.circleci/workflows.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3087)

Separate CI workflow for pushing packages to pypi

---

.circleci/config.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3091)

CircleCI continuation for empty branches

---

sql_generators/glean_usage/templates/events_stream_v1.query.sql

I think this is fine to add manually for now but something to think about for the future is whether or not there is a better way to synchronize these fields? 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3115)

Add session_id and session_count to events_stream tables

---

sql/moz-fx-data-marketing-prod/acoustic/raw_recipient_raw_v1/schema.yaml

Currently this is causing the following error in publish_tables task:
```
[2024-03-19, 08:20:14 UTC] {pod_manager.py:466} INFO - [base] Traceback (most recent call last):
[2024-03-19, 08:20:14 UTC] {pod_manager.py:466} INFO - [base]   File "/app/bigquery_etl/cli/query.py", line 1739, in _update_query_schema_with_downstream
[2024-03-19, 08:20:14 UTC] {pod_manager.py:466} INFO - [base]     changed = _update_query_schema(
[2024-03-19, 08:20:14 UTC] {pod_manager.py:466} INFO - [base]               ^^^^^^^^^^^^^^^^^^^^^
[2024-03-19, 08:20:14 UTC] {pod_manager.py:466} INFO - [base]   File "/app/bigquery_etl/cli/query.py", line 1974, in _update_query_schema
[2024-03-19, 08:20:14 UTC] {pod_manager.py:466} INFO - [base]     existing_schema.merge(table_schema)
[2024-03-19, 08:20:14 UTC] …
```

fix(): incorrect type for event_timestamp raw_recipient_raw_v1

---

script/glam/generate_glean_sql

The previous solution works locally but fails to fetch any tables when running on Airflow. This forces grep to work as egrep, which supports extended regex.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3141)

GLAM try egrep for table fitering + more specific pattern

---

script/glam/generate_glean_sql

I made sure to test this inside the `bigquery-etl:latest` image. It works.
grep doesn't like `/d` so this is the right way to achieve it.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3150)

GLAM: Definitely fixing grep regex to filter glean tables

---

.circleci/workflows.yml
bigquery_etl/view/__init__.py
bqetl_project.yaml

It's still being skipped if the path filtering determines that no SQL etc got changed.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3145)

Remove skipping DAG validation in CI

---

bqetl_project.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3156)

fix: add everything inside data-observability-dev to dry-run skip to fix dry-run CI step failures (access denied)

---

.circleci/workflows.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3152)

Fix dry-run CI when skipping stage deploys

---

sql/moz-fx-data-marketing-prod/acoustic/suppression_list_v1/metadata.yaml

The DAG failed with 
```
Cannot read partition information from a table that is not partitioned: moz-fx-data-marketing-prod:acoustic.suppression_list_v1$20240320
```
so I'm adding a specific line that there is no partition on this table as it appears the default is partitioned tables
fix for #5246
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3184)

fix: DENG-3161 add date_partition_parameter: null to suppression list

---

sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports/view.sql

We've decided to switch to only historical tables to simplify the query as there is no immediate need to get "live" reports.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3172)

Fixes #5250 - Change broken_site_report view to only use historical table

---

bigquery_etl/cli/query.py
bigquery_etl/cli/stage.py
bigquery_etl/cli/utils.py

I did some profiling and one of the memory and time bottlenecks is
```
dependency_graph = get_dependency_graph([sql_dir], without_views=True)
```
when updating query schemas. Currently, we call the schema `update` function for each query that has changed in stage deploys. This change allows a list of files as CLI parameter so that the dependency graph can be reused when doing stage deploys
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3194)

Speed up stage deploys

---

bigquery_etl/cli/stage.py
bigquery_etl/cli/utils.py

Follow up to https://github.com/mozilla/bigquery-etl/pull/5262
This fixes table deploys by allowing tuples in `paths_matching_name_pattern` since click nargs are passed in as tuples instead of lists.  [airflow log](https://workflow.telemetry.mozilla.org/dags/bqetl_artifact_deployment/grid?root=&dag_run_id=manual__2024-03-22T00%3A47%3A18.169752%2B00%3A00&task_id=publish_new_tables&tab=logs)
Also fixes stage deploys when there are no queries ([CI log](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/31671/workflows/efa8d915-53d0-4d79-9f30-ac9a85ec739c/jobs/344716)) by not attempting to deploy.  This was the previous behaviour.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3201)

Avoid table stage deploy when there are no queries

---

sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports_live/view.sql

This is a follow up for https://github.com/mozilla/bigquery-etl/issues/5250.
I would like to create a separate live view mainly for ML classification job using bugbug that is defined in [docker-etl](https://github.com/mozilla/docker-etl/blob/main/jobs/broken-site-report-ml/broken_site_report_ml/main.py) repository.
This ETL job runs every 15 minutes and classifies reports gradually throughout the day. That worked well with the live data, but with the switch to historical table that gets updates only once a day, the script will try to classify all reports at once when they appear in the table. Given the size of the job (800-1k reports with non-empty description per day) this will take a long time, and ETL script likely will not get results during a single run. With this approach, by the …

Fixes #5266 - Add a separate view for live user_reports

---

sql_generators/glean_usage/templates/events_stream_v1.query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3155)

Bug 1886394 - Events stream: Pick glean_timestamp if available

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql

This is to prevent out of memory errors which started in [the ETL](https://workflow.telemetry.mozilla.org/dags/bqetl_main_summary/grid?root=&dag_run_id=scheduled__2024-03-21T02%3A00%3A00%2B00%3A00&task_id=telemetry_derived__clients_daily__v6&tab=logs).  In the past 3 weeks this should only filter out one client (starting on 2024-03-20): https://sql.telemetry.mozilla.org/queries/98557/source
The ETL succeeded with 3070808 but 4142944 was too much. …

Filter out clients with too many pings * addons in clients_daily

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/udf_js/main_summary_active_addons/udf.sql

A struct with only the fields used by the udf is passed in to prevent the clients_daily_v6 query from breaking each time active_addons is modified on the client side.  The only usage of `main_summary_active_addons` I could find is in clients_daily
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3224)

Pass a fixed list of fields to main_summary_active_addons in clients_daily

---

bigquery_etl/cli/backfill.py
bigquery_etl/cli/query.py
tests/cli/test_cli_query.py

There were some mismatched types between how we invoke CLI backfills causing excludes to be ignored 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3231)

fix(managed-backfills): fix date formats from CLI and from backfill initiate

---

bigquery_etl/cli/stage.py
bigquery_etl/dryrun.py

Fixes https://github.com/mozilla/bigquery-etl/issues/5289
This PR ensures that the project ID is added to the datasets deployed on stage. This way we can support multiple projects that might have the same datasets and skip dry runs for the correct ones
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3244)

Fix dryrun skip on stage deploys

---

sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_2_v1/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_clients_week_4_v1/checks.sql
sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_week_4_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_2_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_4_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/checks.sql

This is to unblock downsteam jobs from failing to run as the result of the fail checks failing (minor duplication issue that seems to come up).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3282)

feat(): convert all funnel_retention mobile checks to warn instead of fail

---

bigquery_etl/cli/backfill.py

Fixes:
```
[2024-04-01, 20:43:09 UTC] {pod_manager.py:466} INFO - [base]   File "/app/bigquery_etl/cli/backfill.py", line 490, in complete
[2024-04-01, 20:43:09 UTC] {pod_manager.py:466} INFO - [base]     Path(sql_dir / project / dataset / table / METADATA_FILE)
[2024-04-01, 20:43:09 UTC] {pod_manager.py:466} INFO - [base]          ~~~~~~~~^~~~~~~~~
[2024-04-01, 20:43:10 UTC] {pod_manager.py:483} INFO - [base] TypeError: unsupported operand type(s) for /: 'str' and 'str'
```
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3284)

fix(managed-backfills): fix unsupported type in backfill complete

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/clients_activation_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v2/checks.sql
sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql

This is to prevent blocking KPI metric generation but still maintain visibility into potential data issues.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3285)

feat: convert KPI source query checks from fail to warn

---

.circleci/workflows.yml
bigquery_etl/cli/query.py
bigquery_etl/cli/stage.py

In order to support the `is_init()` jinja statements when running the the artifact deployments, the queries should not be rendered before getting pushed to the `generated-sql` branch.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3170)

Have Jinja in generated SQL

---

bigquery_etl/cli/backfill.py
tests/cli/test_cli_backfill.py

Before we were getting `$False` as a partition string, due to a misplaced `is None` Added a test as well.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3295)

fix(managed-backfills) Incorrect type for partition string when completing backfill

---

bigquery_etl/cli/stage.py
sql/data-observability-dev/fenix/clients_last_seen_joined/view.sql
sql/data-observability-dev/fenix/dataset_metadata.yaml
sql/data-observability-dev/fenix/event_types/view.sql
sql/data-observability-dev/fenix/events_daily/view.sql
sql/data-observability-dev/fenix/firefox_android_clients/view.sql
sql/data-observability-dev/fenix/metrics_clients_last_seen/view.sql
sql/data-observability-dev/org_mozilla_firefox/dataset_metadata.yaml
sql/data-observability-dev/org_mozilla_firefox/event_monitoring_live/view.sql
sql/data-observability-dev/telemetry/dataset_metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3301)

feat(DENG-3212): add views for data-observability-dev test datasets

---

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml

The previous backfill needs to be extended to cover the full history of visits
to fill in the two new fields. The PR that added these fields merged on
'2024-03-18' (https://github.com/mozilla/bigquery-etl/pull/5224#event-12159631760),
and `newtab_visits` has the new fields populated on that date
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3330)

Extend the completed backfill

---

bigquery_etl/cli/query.py
bigquery_etl/cli/stage.py
bqetl_project.yaml
sql_generators/glean_usage/event_monitoring_live.py
sql_generators/glean_usage/events_stream.py
sql_generators/glean_usage/templates/cross_channel_events_stream.query.sql

Inverting the check, excluding tiktok just because it was excluded for the other part too and to showcase it.
What apps do we need to exclude here to begin with?
@scholtzan :
With respect to `datasets` / `skip_datasets`: I assumed we would get a merged view for `fenix` over the app IDs, but I guess that never actually happened. Will this happen with the inversion now? Is there some manual step we need to make it happen?
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3154)

Bug 1879826 - events stream: Default enable for all apps with an exclusion list

---

sql/moz-fx-data-shared-prod/monitoring_derived/average_ping_sizes_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/average_ping_sizes_v1/query.py

`monitoring_derived.stable_table_sizes_v1` stopped updating on 2022-08-07 and is now deprecated and replaced by `stable_and_derived_table_sizes`.
@scholtzan `average_ping_size` hasn't had data for nearly two years.  Do you think we should backfill it or could we take this as an opportunity to deprecate it?
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3365)

Deprecate average_ping_sizes_v1

---

sql_generators/glean_usage/templates/clients_last_seen_joined.metadata.yaml
sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql

Metric values seem to be missing in `clients_last_seen_joined` tables. The reason is that the query is looking for metric values a day into the future. Since that data doesn't exist at that point all the values are null.
This PR delays running `clients_last_seen_joined` tasks by a day so that data exists when run.
This will also delay the following tables by a day:
`unified_metrics`
`active_users_aggregates`
`active_users_deletion_request`
and their downstream dependencies …

[Bug 1889418] Delay clients_last_seen_joined runs by a day

---

sql/moz-fx-data-shared-prod/pocket_derived/events_v1/metadata.yaml

Is this all we need to do to stop the DAG from running?
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3348)

Bug 1890323 - Remove pocket_derived.events_v1 from DAG scheduling

---

sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/metadata.yaml

Remove the required partition filter for the table: moz-fx-data-shared-prod.cloudflare_derived.os_usage_v1, to be consistent with the other 2 cloudflare tables (all 3 tables are small and hold summary data only)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3421)

DENG-3096 remove required partition filter, small table

---

sql/moz-fx-data-shared-prod/telemetry_derived/public_data_report_hardware_v1/schema.yaml

Follow up to https://github.com/mozilla/bigquery-etl/pull/5332 where I copied the wrong schema.  This schema is from the test table I was using.  Table needs to be deleted before redeploying since it's not compatible
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3420)

Fix hardware report schema

---

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml

Checked for a couple of key metrics and the difference btw backfill and existing data's less than 0.05%: https://console.cloud.google.com/bigquery?sq=470293616514:94b04dcd578748f9a687cbe8f3343e38. This is fine.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3440)

Marking newtab_visits backfill as complete

---

bigquery_etl/dependency.py

What instigated this is the workaround for sqlglot not supporting byte strings causes parsing failures if the SQL contains a raw string that ends with `\b`, because it removes the `b` so the raw string ends with a backlash, which isn't valid.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3448)

Remove sqlglot workarounds which are no longer necessary

---

sql/moz-fx-data-shared-prod/braze_derived/newsletters_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/newsletters_v1/schema.yaml
sql/moz-fx-data-shared-prod/braze_derived/products_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/products_v1/schema.yaml
sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/schema.yaml
sql/moz-fx-data-shared-prod/braze_derived/suppressions_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/suppressions_v1/schema.yaml
sql/moz-fx-data-shared-prod/braze_derived/user_profiles_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/user_profiles_v1/schema.yaml
sql/moz-fx-data-shared-prod/braze_derived/users_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/users_v1/schema.yaml
sql/moz-fx-data-shared-prod/braze_derived/waitlists_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/waitlists_v1/schema.yaml

We're removing the modified timestamp because it's interfering with writing tests. We don't need it since these tables are refreshed daily and not partitioned. If/when that changes, we will add this metadata back in. We're also removing a ctms_fxa table from one of the joins in the users table that we no longer need. 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3456)

Removing modified at timestamp from all schemas

---

sql/moz-fx-data-shared-prod/braze_derived/newsletters_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/products_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/query.sql
sql/moz-fx-data-shared-prod/braze_derived/waitlists_v1/query.sql

Follow-up to https://github.com/mozilla/bigquery-etl/pull/5394.  This is causing failed checks on other prs even though CI should only check changed files.
Ran `bqetl format sql/moz-fx-data-shared-prod/braze_derived/`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3477)

Format braze_derived queries

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_2_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_4_v1/checks.sql

This is an ongoing issue, and these tables should get replaced by tables developed in:
- https://github.com/mozilla/bigquery-etl/pull/5304
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3483)

feat(bug-1887708): disable uniqueness check for retention_week_* tables

---

sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_attribution_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_device_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/metadata.yaml
sql_generators/glean_usage/templates/clients_last_seen_joined.metadata.yaml
sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql

Reverts https://github.com/mozilla/bigquery-etl/pull/5344 and https://github.com/mozilla/bigquery-etl/pull/5357 due to causing duplicate client ids in downstream tables.  Tables will be backfilled and a proper solution will be figured out later
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3484)

Revert clients_last_seen_joined date offset

---

sql/mozfun/google_ads/extract_segments_from_campaign_name/README.md

Fix #5393 
The boilerplate README does have problems with the path so the docs are failing in the CI
This is not a good fix .. there should be a README, but it will hopefull get the CI back to green.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3512)

fixing the readme

---

sql/moz-fx-data-shared-prod/braze_external/users_previous_day_snapshot_v1/script.sql

Due to lack of personal permissions, we needed to delete snapshots via the CI, now that they're gone, we don't need to run this command again.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3546)

removing unnecessary snapshot deletions that just needed to run once

---

.circleci/workflows.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3559)

Store artifacts when `test-sql` CI job fails for troubleshooting

---

.circleci/workflows.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3568)

Store artifacts when `deploy-changes-to-stage` CI job fails for troubleshooting

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/clients_activation_v1/checks.sql

This is where we end up with the same client_id showing in different channels in rare cases. Unioning the channels then results in duplication that we're observing.
As a temporary measure, commenting out this check to reduce task failure noise.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3573)

bug(1891523): comment out uniqueness check for firefox_ios clients_activation due to upstream issue

---

sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.query.sql

So it can be deployed to stage by CI.  The original init logic was removed in #5342.
This issue is currently blocking #5434 from passing CI checks.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3582)

Restore init logic for `baseline_clients_last_seen_v1`

---

bigquery_etl/view/__init__.py

This is to help us identifying the source of the following bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1894701
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3593)

feat: add a debug log statement in case TypeError is raised while formating changed view

---

.circleci/workflows.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3616)

Store debug artifacs when CI jobs downstream of SQL generation fail

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/schema.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/fenix.first_session.schema.json
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.schema.json
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_channels/expect.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_channels/fenix.first_session.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_channels/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_no_first_session_with_activations/expect.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_no_first_session_with_activations/fenix.first_session.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_baseline_no_first_session_with_activations/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_no_baseline/expect.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_no_baseline/fenix.first_session.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_no_baseline/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_seq/expect.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_seq/fenix.first_session.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_first_session_seq/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_only_metrics_ping/expect.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_only_metrics_ping/fenix.first_session.yaml
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/test_only_metrics_ping/moz-fx-data-shared-prod.fenix_derived.firefox_android_clients_v1.yaml

---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3486)

feat(DENG-3479): add meta_attribution_app field to firefox_android_clients

---

sql/moz-fx-data-shared-prod/fenix/baseline_clients_last_seen_extended_activity/view.sql
sql/moz-fx-data-shared-prod/firefox_ios/baseline_clients_last_seen_extended_activity/view.sql

This view is a temporary solution until we can make all required changes to make this PR work:
https://github.com/mozilla/bigquery-etl/pull/5434
Which would add those fields to the `baseline_clients_last_seen` view directly.
The following fields are being added to support our KPI metric calculations:
- `app_name` - application name (based on application, isp and in Fenix case on distribution_id)
- `activity_segment` - categorise a client based on their activity "levels"
- `is_dau` - sent ping and considered active on current date
- `is_wau` - sent ping and considered active in the last 7 days
- `is_mau` - sent ping and considered active in the last 28 days
- `is_daily_user` - client a baseline sent ping on current date
- `is_weekly_user` - client a baseline sent ping in the 7 days
- …

feat(DENG-3462): add baseline_clients_last_seen_extended_activity containing new activity fields to support KPI supporting metrics

---

script/glam/run_glam_sql

`glam fog` dag is currently failing because this function is replacing a dataset string that's already in a fully qualified form. This also fixes a bug by replacing colons with dots, which is the right format for fully qualified datasets in SQL code.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3660)

GLAM fix replace_dataset to account for fully qualified datasets in query

---

.pre-commit-config.yaml

If mypy checks multiple ETL `query.py` files at once it fails with the error `Duplicate module named "query"`.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3662)

Exclude ETL `query.py` files from mypy pre-commit checks

---

sql/moz-fx-data-shared-prod/fenix/retention_clients/view.sql
sql/moz-fx-data-shared-prod/firefox_ios/retention_clients/view.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/schema.yaml

fix: correct firefox_ios and fenix retention views and queries
There is a mistake in the retention queries causing the SQL validation to fail. These changes make the SQL valid.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3672)

fix: correct firefox_ios and fenix retention views and queries

---

sql/mozfun/serp_events/README.md
sql/mozfun/serp_events/ad_blocker_inferred/metadata.yaml
sql/mozfun/serp_events/ad_blocker_inferred/udf.sql
sql/mozfun/serp_events/is_ad_component/metadata.yaml
sql/mozfun/serp_events/is_ad_component/udf.sql
sql_generators/serp_events_v2/__init__.py
sql_generators/serp_events_v2/templates/view.sql

Replace the `serp_events` view with a new one pointing to the v2 table, with some additional processing at the view layer.
- Add functions for business logic
- Create array combining impressions and engagements for ad components
- Retain other impressions and engagements in separate arrays
- Add summary columns for ad impressions & engagements per SERP impression
A staging version of this view is available as `mozdata.analysis.dzeber_serp_v2` …

Update view for serp_events v2

---

bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_beta__view_clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_beta__view_clients_daily_scalar_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_nightly__view_clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_nightly__view_clients_daily_scalar_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_release__view_clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_release__view_clients_daily_scalar_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_beta__view_clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_beta__view_clients_daily_scalar_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_nightly__view_clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_nightly__view_clients_daily_scalar_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_release__view_clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_release__view_clients_daily_scalar_aggregates_v1.sql
bigquery_etl/glam/templates/view_user_counts_v1.sql

Removes backticks after `project_id` (which prevents the string replacement done in https://github.com/mozilla/bigquery-etl/pull/5517 from working fully) and adds them at the end of the fully qualified table name instead.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3681)

fix(glam) standardize project_id in templates 

---

sql_generators/glean_usage/templates/clients_last_seen_joined.metadata.yaml
sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql

In some rare cases we end up with same client_id in multiple channels in Fenix. In those cases, this union can result in client_id duplicates. This logic ensures that the resulting table only includes the client from the channel we've seen first.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3399)

feat(DENG-656): Add client_id deduplication to fenix_derived.clients_last_seen_joined query

---

sql/moz-fx-data-shared-prod/fenix_derived/retention_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/metadata.yaml

fix: correct scheduling settings for retention queries to fix task errors
This should resolve the following error:
```
INFO - [base] prod:[...]': Some rows belong to different
INFO - [base] partitions rather than destination partition
```
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3694)

fix: correct scheduling settings for retention queries to fix task errors

---

bigquery_etl/cli/query.py
sql_generators/glean_usage/templates/events_stream_v1.metadata.yaml
tests/test_run_query.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1892284
This makes all the events_stream_v1 queries run in `moz-fx-data-backfill-2` instead of shared prod because the desktop query uses a lot of compute time and relatively low bytes scanned.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3704)

[Bug 1892284] Run events_stream_v1 queries in moz-fx-data-backfill-2

---

sql_generators/glean_usage/templates/events_stream_v1.metadata.yaml

Partially reverts https://github.com/mozilla/bigquery-etl/pull/5543.  I found a bug with the destination table setting so reverting before the next run and I can fix it tomorrow
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3707)

Remove billing project from events_stream (reverts #5543)

---

bigquery_etl/cli/query.py
sql_generators/glean_usage/templates/events_stream_v1.metadata.yaml

The generated airflow dags use just the table name in `destination_table` which I forgot to test because backfill and init use the full table id
Tested this with `bqetl query run ... --billing-project moz-fx-data-backfill-2 --project_id moz-fx-data-shared-prod --destination_table benwu_dest_test --dataset_id analysis`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3711)

Add project and dataset to destination table if billing project is set

---

bqetl_project.yaml

https://mozilla-hub.atlassian.net/browse/DENG-3720
relay_backend is failing deploys because `relay_backend_stable.events_v1` doesn't have a metrics column.  This is a temporary fix to get it working while that's sorted out.  The app isn't sending any pings yet so the generated sql isn't needed
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3721)

[DENG-3720] Skip relay_backend in glean_usage generator

---

sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/query.sql

I copied this part of the query from `event_aggregates_v1` without realizing that `event_aggregates_suggest_v1` has slightly different columns, so this PR fixes that.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3734)

Fix mobile suggest in event_aggregates_suggest

---

sql/data-observability-dev/org_mozilla_firefox_derived/dataset_metadata.yaml

This is to address the following error:
```
processing bigquery-etl/sql/data-observability-dev/org_mozilla_firefox_derived/dataset_metadata.yaml
org_mozilla_firefox_derived
found org_mozilla_firefox_derived in ops config
dataset_base_acl mismatch
ops: derived_restricted
bqetl: derived
```
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3738)

fix: correct the base_acl for data-observability-dev.org_mozilla_firefox_derived

---

sql/moz-fx-data-shared-prod/telemetry/clients_last_seen_v2/view.sql

This PR fixes the definition of `is_weekly_user` is to use days_seen_bits.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3739)

Update is_weekly_user to use days_seen_bits instead of days_active_bits

---

sql/data-observability-dev/fenix/firefox_android_aggregates/view.sql
sql/data-observability-dev/fenix/firefox_android_anonymised/view.sql
sql/data-observability-dev/fenix_derived/firefox_android_aggregates_v1/metadata.yaml
sql/data-observability-dev/fenix_derived/firefox_android_aggregates_v1/query.sql
sql/data-observability-dev/fenix_derived/firefox_android_aggregates_v1/schema.yaml
sql/data-observability-dev/fenix_derived/firefox_android_anonymised_v1/metadata.yaml
sql/data-observability-dev/fenix_derived/firefox_android_anonymised_v1/query.sql
sql/data-observability-dev/fenix_derived/firefox_android_anonymised_v1/schema.yaml
sql/data-observability-dev/telemetry/firefox_aggregates/view.sql
sql/data-observability-dev/telemetry_derived/firefox_aggregates_v1/metadata.yaml
sql/data-observability-dev/telemetry_derived/firefox_aggregates_v1/query.sql
sql/data-observability-dev/telemetry_derived/firefox_aggregates_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3737)

feat: add additional firefox android queries to simulate a data lineage/flow

---

bigquery_etl/shredder/config.py
bqetl_project.yaml

Two things:
- Update shredder config since we decided to rename the table since it was first added to shredder
- Remove dryrun skip for desktop engagement clients V1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3742)

DENG-3186 Update shredder config to match updated table name

---

bigquery_etl/shredder/config.py
bigquery_etl/shredder/delete.py

https://mozilla-hub.atlassian.net/browse/DENG-3335
Sets project for experiment tables in shredder so it doesn't look for the tables in shared-prod.  Also splits experiments into it's own "environment" so it can be run as a separate airflow task.
I verified that it no longer prints `Skipping moz-fx-data-shared-prod.mozanalysis.... due to NotFound exception` and the queries look correct but I can't complete a dry run because I don't have write access to the tables. …

[DENG-3335] Set project in experiments shredder config

---

sql/data-observability-dev/fenix_derived/firefox_android_anonymised_v1/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3751)

fix: remove first_reported_country from clustering keys for firefox_android_anonymised_v1

---

sql/data-observability-dev/telemetry_derived/firefox_aggregates_v1/query.sql

fix: incorrect WHERE clause inside firefox_aggregates query
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3754)

fix: incorrect WHERE clause inside firefox_aggregates query

---

bigquery_etl/shredder/config.py
tests/shredder/test_config.py

The number of fields must match the number of sources because they get zipped, otherwise some sources will be ignored.
https://github.com/mozilla/bigquery-etl/blob/1d1addb86cd097f7c3cf03d84ec1c30537591a47/bigquery_etl/shredder/delete.py#L217
I think unit test for this is better than a runtime error because crashing shredder can be expensive
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3764)

Add unit test to verify shredder delete target and source counts

---

sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/query.sql

This is the first of a series of changes we'll need to do in order to switch to `events` ping in FxA. IN https://github.com/mozilla/bigquery-backfill/tree/main/backfill/2024-04-29-fxa_events/backend I have validated that this yields the same results as the currently used `accounts_events`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3753)

DENG-3274 Switch accounts_backend.users_services_daily to events ping

---

bigquery_etl/shredder/config.py

Adding this table to shredder as it contains client_id.
It has rows for `client_ids` that don't have rows in `clients_daily_v6` and `clients_last_seen_v1`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3768)

Add clients_last_seen_v2 to shredder config

---

bqetl_project.yaml
sql_generators/glean_usage/common.py
sql_generators/glean_usage/event_monitoring_live.py
sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql
sql_generators/glean_usage/templates/event_monitoring_live_v1.materialized_view.sql
sql_generators/search/__init__.py
sql_generators/stable_views/__init__.py

https://mozilla-hub.atlassian.net/browse/DENG-3417
This PR makes some changes to the `event_monitoring` datasets. Instead of fetching events just from the `event_v1` tables, the generation logic fetches the pings that are sending events from https://probeinfo.telemetry.mozilla.org/glean/ for each app.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3748)

[DENG-3417] Get event pings from probe info for monitoring events

---

sql/data-observability-dev/fenix_derived/firefox_android_anonymised_v1/query.sql

To fix table deploys. It seems the NULL values make the column an INT, so enforce STRING
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3795)

Cast funky_column to string in firefox_android_anonymised_v1

---

sql_generators/glean_usage/templates/baseline_clients_daily_v1.query.sql
tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_daily_v1/org_mozilla_fenix_stable.baseline_v1.schema.json
tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_first_seen_v1/org_mozilla_fenix_stable.baseline_v1.schema.json
tests/sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/baseline_clients_first_seen_v1/test_aggregation/org_mozilla_ios_firefox_stable.baseline_v1.schema.json
tests/sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/baseline_clients_first_seen_v1/test_init/org_mozilla_ios_firefox_stable.baseline_v1.schema.json

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3825)

feat: add geo.subdivision1 to baseline_clients_daily_v1 query template (glean_usage generator)

---

dags.yaml
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_beta_aggregates_v1/metadata.yaml
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_nightly_aggregates_v1/metadata.yaml
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_release_aggregates_v1/metadata.yaml

This PR adjusts the `schedule_interval` or `execution_delta` of DAGs that are downstream of `glam` because of https://github.com/mozilla/telemetry-airflow/pull/1988 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3796)

chore(glam): Adjust DAGs schedule and execution_delta 

---

sql/mozfun/marketing/parse_creative_name/README.md
sql/mozfun/marketing/parse_creative_name/metadata.yaml
sql/mozfun/marketing/parse_creative_name/udf.sql

This supports the [campaign naming proposal](https://github.com/mozilla/bigquery-etl/pull/5616). We'll probably pull this information in `firefox_android_clients`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3831)

Add creative name parsing function

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/baseline_clients_yearly_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/baseline_clients_yearly_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3839)

Bug 1897824 - Make clients_yearly schema static; add new fields

---

.circleci/post-diff.js
.circleci/workflows.yml

Links to the full `sql.diff` file have been broken since #4593 because they're using the wrong CI job ID.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3838)

Fix link to full `sql.diff` file

---

sql_generators/glean_usage/common.py
sql_generators/glean_usage/templates/baseline_clients_daily_v1.query.sql
tests/sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/baseline_clients_first_seen_v1/test_aggregation/org_mozilla_ios_firefox_stable.baseline_v1.schema.json
tests/sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/baseline_clients_first_seen_v1/test_init/org_mozilla_ios_firefox_stable.baseline_v1.schema.json

fix: baseline_clients_daily to only grab distribution_id for fenix app
This is to address an incorrect assumption that every `baseline` ping would have the same structure. It turns out the field containing distribution_id only exists for Fenix.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3829)

fix: baseline_clients_daily to only grab distribution_id for fenix app

---

sql_generators/kpi_support_metrics/__init__.py
sql_generators/kpi_support_metrics/templates/retention.query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3857)

feat: make sure we user product_specific_attribution_fields additional field list instead of app_name logic in templates

---

bigquery_etl/shredder/config.py
bigquery_etl/shredder/delete.py

DENG-3335
Fixes two issues:
- filters out tables that don't have a `client_id` column which is currently causing it to fail
- using the client to list tables takes about 20 minutes because there are 36k tables and would take hours if it also got the schema to check for client_id
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3860)

[DENG-3335] Use information_schema to find experiment tables for shredder

---

sql_generators/glean_usage/templates/baseline_clients_daily_v1.schema.yaml
sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.schema.yaml

---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3890)

Bug: add fields to baseline tables in glean usage generator

---

sql_generators/kpi_support_metrics/__init__.py
sql_generators/kpi_support_metrics/templates/union.view.sql

---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3871)

feat: update kpi_support_metrics generation to append platform to the unioned view name

---

bigquery_etl/cli/query.py

I believe this is the preferred way to do multithreading/processing while maintaining individual exception context. Adapted from the `concurrent.futures` [docs](https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor-example). 
Will update from `Exception` in a future PR to something more specific.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3893)

fix(backfills): switch to concurrent.futures to improve debuggability

---

bigquery_etl/cli/query.py

Followup to https://github.com/mozilla/bigquery-etl/pull/5653/ - re-include similar logic to fail overall if any backfill dates fail.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3894)

fix(backfills): followup to concurrent.futures, raise Error if any failed dates

---

bigquery_etl/cli/query.py

We're getting a pickling error: `Can't pickle local object 'if_exception_type.<locals>.if_exception_type_predicate'` on each concurrent invocation of `cli.query._backfill_query`. [e.g.](https://workflow.telemetry.mozilla.org/dags/bqetl_backfill_initiate/grid?search=bqetl_backfill_initiate&dag_run_id=scheduled__2024-05-23T20%3A00%3A00%2B00%3A00&task_id=initiate_backfill.process_backfill&tab=mapped_tasks&map_index=0). I haven't been able to reproduce this locally. 
Multi-threading tends to require less pickling so here's an attempt to fix it. 
As an aside, most of concurrent functionality is I/O bound (API requests to GCP) so using threads probably makes more sense anyway. 🤞
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3897)

fix(backfills): switch from process to thread to avoid pickling bigquery object

---

sql_generators/glean_usage/templates/events_stream_v1.query.sql

DENG-3889
Changes:
- replace two (out of five) of the javascript udfs usages with a sql udf
- rearrange ctes so most of the udfs are called per event ping rather than on the unnested events
1% sample (sample_id = 1) on firefox desktop for 2024-05-22:
changes | slot hours | job id (backfill-2)
-- | -- | --
base | 24.5 | bquxjob_7a85e33a_18fab4919e3
rearranged | 5.7 | bquxjob_4ababcd5_18fab3b62ea
sql udfs | 4.3 | bquxjob_129253ac_18fab52d5c9
rearranged + sql udfs | 3.4 | bquxjob_4145760d_18fab765f03
100% of firefox desktop for 2024-05-22 (both overwriting a clustered partition):
changes | slot hours | job id (backfill-2)
-- | -- | --
base (airflow run) | 3910 😵‍💫 | bqjob_r6deaccf950e8d7f5_0000018fa35c4fce_1
rearranged + sql udfs | 699 | bquxjob_5293faeb_18fab5ab707
I'm mostly confident the …

[DENG-3889] Rewrite events_stream_v1 for better performance

---

sql_generators/glean_usage/templates/events_stream_v1.query.sql

Following up on https://github.com/mozilla/bigquery-etl/pull/5659, I found the billing project option doesn't work when there are temp udfs (DENG-3905).  I'm working on a fix for that but I want to do this in the meantime to get the query working again.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3910)

[DENG-3889] Replace events_stream temp udfs with inline usages

---

.circleci/workflows.yml
README.md
pyproject.toml

The current setup of publishing PyPI packages via the CI is not working as the tag information is not accessible when using the `path-filtering` orb. This PR changes the process slightly, instead of pushing tag with new version numbers, the version number is now managed via `pyproject.toml`. Whenever the version number changes in that file a new package is published to PyPI (otherwise the step is skipped).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3915)

Fix PyPI package publishing in CI

---

sql_generators/mobile_kpi_support_metrics/templates/retention.metadata.yaml

This should resolve the following error when running the backfill command against the retention query:
```
Some rows belong to different partitions rather than destination partition
```
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3919)

fix: metadata.yaml generation change to allow backfill command execution

---

sql_generators/events_daily/templates/event_types_history_v1/templating.yaml
sql_generators/events_daily/templates/events_daily_v1/templating.yaml

While the VPN iOS network extension app isn't currently sending `main` pings with events like the other VPN apps are, it's good to include it for consistency, as the network extension app's `main` pings are automatically included in the generated `mozilla_vpn.main` view, and thus are also included in the `mozilla_vpn.events_unnested` view.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3925)

Include VPN iOS network extension app in VPN events ETLs

---

sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/query.sql

Converted all the campaign names to upper case to prevent us from seeing situations like eu and EU in our segments
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3930)

Normalizing campaign names

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/query.sql
tests/sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/moz-fx-data-shared-prod.fenix.baseline_clients_daily.schema.json

The distribution_id currently appears to be wrong inside firefox_android_clients_v1, this is a quick "solution" to try and mitigate this issue by pulling distribution_id from the baseline ping instead. The reason for this is that we decided that the baseline ping on mobile will serve as the primary source of truth in relation to KPI reporting.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3935)

feat: update firefox_android_clients_v1 to pull distribution_id only from the baseline ping

---

bigquery_etl/metadata/parse_metadata.py

This should fix the errors we are seeing in Airflow:
```
[2024-05-30, 18:00:03 UTC] {pod_manager.py:466} INFO - [base]     changed = _update_query_schema(
[2024-05-30, 18:00:03 UTC] {pod_manager.py:466} INFO - [base]               ^^^^^^^^^^^^^^^^^^^^^
[2024-05-30, 18:00:03 UTC] {pod_manager.py:466} INFO - [base]   File "/app/bigquery_etl/cli/query.py", line 2008, in _update_query_schema
[2024-05-30, 18:00:03 UTC] {pod_manager.py:466} INFO - [base]     metadata.set_bigquery_clustering(table.clustering_fields)
[2024-05-30, 18:00:03 UTC] {pod_manager.py:466} INFO - [base]   File "/app/bigquery_etl/metadata/parse_metadata.py", line 432, in set_bigquery_clustering
[2024-05-30, 18:00:03 UTC] {pod_manager.py:466} INFO - [base]     time_partitioning=time_partitioning,
[2024-05-30, 18:00:03 UTC] …
```

Fix setting partitioning metadata

---

bigquery_etl/cli/backfill.py
bigquery_etl/cli/query.py
bigquery_etl/deploy.py
bigquery_etl/metadata/publish_metadata.py
tests/cli/test_cli_backfill.py
tests/cli/test_cli_query.py
tests/test_deploy.py

Mainly introduces a `deploy` module for table deployment logic. Additionally does the following:
- Adds specific exceptions for skipped and failed deploys. 
-  Updates multiprocessing code to `concurrent.futures` to collect individual exceptions as exception handling instead of using return values. 
- Moves metadata attaching logic to metadata module. 
- Update backfill initiate tests to mock deployment. These tests currently pass because skipped deploys currently "fail" silently in the click deploy command. Running a backfill without a schema in production will skip the deploy and fail when running the backfill queries. An example of this is the conversation linked in https://github.com/mozilla/bigquery-etl/pull/5646. (Missing schemas should be fixed by …

chore: refactor schema deploys, add and use deploy utils

---

sql/moz-fx-data-shared-prod/braze_derived/products_v1/metadata.yaml
sql/moz-fx-data-shared-prod/braze_derived/users_v1/metadata.yaml

The braze dag schedule now runs 3 times a day and upstream dependencies do not. We can get by with the upstream tables having a daily cadence as the rest of the data comes from an upstream source off of bqetl
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3938)

removing upstream dependencies for now

---

sql/moz-fx-data-shared-prod/fenix_derived/retention_v1/backfill.yaml
sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/backfill.yaml

fix: update entry date to be the same as the end_date
This should address the following CI error:
```
backfill = cls(
^^^^
File "<attrs generated init bigquery_etl.backfill.parse.Backfill>", line 13, in __init__
File "/root/project/bigquery_etl/backfill/parse.py", line 112, in validate_end_date
raise ValueError(f"Invalid end date: {value}.")
ValueError: Invalid end date: 2024-05-31.
```
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3950)

fix: update entry date to be the same as the end_date

---

bigquery_etl/deploy.py
tests/test_deploy.py

Previous logic was a skip rather than a fail. This isn't mis-configuration, these are used for empty check queries, e.g. `site_metrics_empty_check_v1`. Medium-long term these could probably be migrated to a data check.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3951)

fix(deploy): skip (instead of fail) deploys with explicitly null destination_table

---

sql_generators/mobile_kpi_support_metrics/__init__.py
sql_generators/mobile_kpi_support_metrics/templates/engagement.query.sql
sql_generators/mobile_kpi_support_metrics/templates/engagement.schema.yaml
sql_generators/mobile_kpi_support_metrics/templates/engagement_clients.view.sql
sql_generators/mobile_kpi_support_metrics/templates/retention.query.sql
sql_generators/mobile_kpi_support_metrics/templates/retention.schema.yaml
sql_generators/mobile_kpi_support_metrics/templates/retention_clients.view.sql
sql_generators/mobile_kpi_support_metrics/templates/union.view.sql

The current version only generates `retention` and `engagement` artifacts for `firefox_ios` and `fenix`. This change aims to introduce these artifacts to the following mobile products:
- `klar_ios`
- `focus_ios`
- `klar_android`
- `focus_android`
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3965)

feat: make changes to generate retention and engagement for focus and klar products also

---

sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_clients_v1/backfill.yaml

This is a backfill for `moz-fx-data-shared-prod.telemetry_derived.desktop_retention_clients_v1`. This is a new table with new logic for retention/dau for 2024 KPI metrics. Table is a client level dataset that will provide data for the aggregated `moz-fx-data-shared-prod.telemetry_derived.desktop_retention_v1`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3985)

add backfill.yaml, initiate backfill for desktop_retention_clients_v1

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/backfill.yaml

feat: add backfill.yaml for firefox_ios_derived.retention_v1
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3995)

feat: add backfill.yaml for firefox_ios_derived.retention_v1

---

sql_generators/glean_usage/common.py

Cirrus apps generally don't have baseline pings.
This should resolve [bug 1888718](https://bugzilla.mozilla.org/show_bug.cgi?id=1888718) "Airflow task bqetl_glean_usage.checks__warn_accounts_cirrus_derived__baseline_clients_last_seen__v1 failing since exec_date 2024-03-23".
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3993)

Exclude `accounts_cirrus` Glean app from baseline ping checks as it has no baseline pings (bug 1888718)

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/backfill.yaml

feat: update status of firefox_ios_derived.retention_v1 to Complete
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3999)

feat: update status of firefox_ios_derived.retention_v1 to Complete

---

sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/metadata.yaml

The `kpi_forecasting` DAG doesn't currently have a `wait_for_unified_metrics` task.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4004)

Remove `external_downstream_tasks` metadata from `unified_metrics_v1`

---

sql/moz-fx-data-shared-prod/braze_external/changed_firefox_subscriptions_sync_v1/checks.sql
sql/moz-fx-data-shared-prod/braze_external/changed_newsletters_sync_v1/checks.sql
sql/moz-fx-data-shared-prod/braze_external/changed_products_sync_v1/checks.sql
sql/moz-fx-data-shared-prod/braze_external/changed_users_sync_v1/checks.sql
sql/moz-fx-data-shared-prod/braze_external/changed_waitlists_sync_v1/checks.sql

With Braze syncs now using incremental updates, we expect some duplicate external IDs
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4011)

removing uniqueness check from sync models

---

sql/moz-fx-data-shared-prod/monitoring/shredder_progress/view.sql

View currently fails because `query_info` struct is different between these projects right now (sometimes?)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4035)

Use fixed fields from jobs view in shredder_progress

---

sql_generators/urlbar_events/templates/desktop_query.sql

The bqetl_urlbar is failing 
https://workflow.telemetry.mozilla.org/dags/bqetl_urlbar/grid?dag_run_id=scheduled__2024-06-05T03%3A00%3A00%2B00%3A00&task_id=firefox_desktop_urlbar_events__v2&tab=logs
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4029)

Fix DAG failures caused due to bad int value

---

sql_generators/active_users_aggregates_v3/templates/mobile_query.sql
sql_generators/active_users_aggregates_v3/templates/mobile_view.sql

The `klar_android.active_users_aggregates` view and its underlying `klar_android_derived.active_users_aggregates_v3` table have a different schema than the rest of the apps, because it was added more recently (#5624) after some columns were removed from the `active_users_aggregates_v3` ETL (#5396).
This should fix [bug 1901121](https://bugzilla.mozilla.org/show_bug.cgi?id=1901121) "_Airflow task `bqetl_artifact_deployment.publish_views` failed for exec_date 2024-06-06_".
--- …

Fix union error in `telemetry.active_users_aggregates_mobile` view (bug 1901121)

---

bigquery_etl/cli/dryrun.py

Prints sql files that failed.  Printing the error messages would be better but needs more work
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4050)

Print list of failed queries at end of cli dry run

---

bigquery_etl/shredder/config.py

https://mozilla-hub.atlassian.net/browse/DENG-3918
Depends on https://github.com/mozilla-services/cloudops-infra/pull/5721 and https://github.com/mozilla/mozilla-schema-generator/pull/268
Skip stable tables for pings that have `include_client_id: false`.  Default to true.  This will skip 181 tables.  Tables are in the query in this comment https://mozilla-hub.atlassian.net/browse/DENG-3918?focusedCommentId=894752
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4070)

[DENG-3918] Ignore glean stable tables with no client id for shredder

---

Dockerfile
script/glam/generate_glean_sql

This fixes the currently broken `glam_fog` and `glam_fenix` ETLs
The current implementation is fragile and now broken. It relies on `schema_id` being the top label printed for the invocation of `bq ls`, which means it would belong in the same line as the `tableId`. After the [include_client_id](https://github.com/mozilla-services/cloudops-infra/pull/5721/files) label was added to the Glean tables, it took the spot of `schema_id` and consequently made the whole command print nothing.
This implementation fetches the metadata for the tables in a `JSON` format and relies only on that to fetch the tables' ids.
I had to add `jq` to the Docker image to make that possible.
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed …

fix(glam): add a more robust way to fetch glean tables

---

sql/data-observability-dev/org_mozilla_firefox_derived/dataset_metadata.yaml

This is as per the discussion inside PR https://github.com/mozilla-services/data-sandbox-terraform/pull/96
----
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4078)

Update org_mozilla_firefox_derived dataset_metadata.yaml workgroup

---

bqetl_project.yaml
sql_generators/glean_usage/templates/event_error_monitoring_aggregates_v1.query.sql
sql_generators/glean_usage/templates/event_flow_monitoring_aggregates_v1.script.sql
sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql
sql_generators/glean_usage/templates/event_monitoring_live_v1.materialized_view.sql

This will require us to manually delete and recreate `accounts_{frontend,backend}.event_monitoring_v1` materialized views.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4102)

DENG-2407 Use standard event pings for accounts in event monitoring queries

---

sql_generators/glean_usage/templates/event_flow_monitoring_aggregates_v1.script.sql

Follow up to https://github.com/mozilla/bigquery-etl/pull/5801 - this is needed because accounts send flow_id in a string metric.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4115)

DENG-2407 Use flow_id string metric for accounts event flow monitoring

---

sql_generators/glean_usage/templates/event_flow_monitoring_aggregates_v1.script.sql

Follow up to https://github.com/mozilla/bigquery-etl/pull/5812 that brings this query closer to the state before https://github.com/mozilla/bigquery-etl/pull/5801.
Because `events_unnested` views do not expose `metrics` field, we need to unnest explicitly here.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4116)

DENG-2407 Fix: Use flow_id string metric for accounts event flow monitoring

---

sql/moz-fx-data-marketing-prod/google_search_console/search_impressions_by_page/schema.yaml
sql/mozfun/google_search_console/classify_site_query/udf.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4126)
[DENG-1733]: https://mozilla-hub.atlassian.net/browse/DENG-1733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Minor Google Search Console revisions (DENG-1733)

---

sql/moz-fx-data-shared-prod/fxci_derived/worker_costs_v1/query.sql

It seems that the `resource.name` field from the billing export can sometimes take the form:
projects/<id>/instances/<name>
And other times it's simply:
<name>
Update the worker costs query to account for this.
Issue: #5759
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4111)

fix(fxci): Normalize 'resource.name' in fxci_derived.worker_costs_v1

---

.circleci/workflows.yml

Files being renamed can have similar effects as files being deleted, so we want CI to run SQL generation when files are renamed for the same reasons we do that when files are deleted.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4129)

Have CI run SQL generation if files in `sql/` were renamed

---

bigquery_etl/cli/query.py

Reverts mozilla/bigquery-etl#5640
This results in materialized views getting re-deployed whenever artifacts are being deployed. Since there is a delay when applying permissions to materialized views, they're unaccessible via Looker etc. Reverting until we find a better way to deploy materialized views. For now deployment needs to happen manually
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4133)

Revert "Fix initialize logic for materialized views"

---

sql_generators/glean_usage/glean_app_ping_views.py
sql_generators/glean_usage/templates/app_ping_view.view.sql

https://bugzilla.mozilla.org/show_bug.cgi?id=1904423
Some new pings that don't have `client_info` fields got added for Fenix. The generation template references `client_info` to get the channel. This PR should avoid referencing the field for affected pings
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4139)

[Bug 1904423] Support ohttp for generated app views

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/org_mozilla_reference_browser_derived/baseline_clients_last_seen_v1/checks.sql

This app is sending very little data, some days none at all. I updated some of the tests (like min row count), so they don't go off constantly
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4158)

[Bug 1903788] Update checks for reference_browser_derived.baseline_clients_last_seen_v1

---

.circleci/workflows.yml

See https://github.com/mozilla-it/dataservices-infra/pull/282#discussion_r1654966035
We are allowing other DAGs to be triggered via the cloud function, so dag_id should be explicitly specified
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4165)

Explicitly specify dag_id in CI for artifact deployment

---

requirements.in
requirements.txt

To try to fix "Compute Engine Metadata server call to universe/universe_domain returned 404" errors.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4172)

Upgrade `google-auth` package to v2.30.0

---

sql_generators/glean_usage/common.py

The `monitor_backend` app won't have any baseline pings.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4180)

Exclude `monitor_backend` Glean app from baseline ping checks

---

sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/query.sql
sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4184)

Add 1 more column to downloads_v2

---

bqetl_project.yaml

https://bugzilla.mozilla.org/show_bug.cgi?id=1905444
Failing deploys because. the events don't have any metrics right now.  Likely a temporary fix
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4216)

[Bug 1905444] Add monitor_backend to glean_usage skip list

---

sql_generators/mobile_kpi_support_metrics/templates/engagement.checks.sql

---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4223)

bug(1905102): disable mobile_support_kpi_metrics engagement not_null check until upstream issue is resolved

---

bigquery_etl/query_scheduling/task.py

There could be multiple tasks in a DAG with the same task ID but in different task groups.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4269)

Include task group in `TaskRef.task_key` if present

---

sql/moz-fx-data-shared-prod/monitor_frontend_derived/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/monitor_frontend_derived/event_monitoring_live_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitor_frontend_derived/monitor_dashboard_user_journey_funnels_v1/metadata.yaml

Followup to https://github.com/mozilla-services/cloudops-infra/pull/5790, specify metadata for tables that don't have `RECORD` columns.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4312)

chore(data-privacy-mapping): DSRE-1690 - ignore tables contaiing RECORD type

---

sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_clients_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v1/metadata.yaml

Fix related to PR https://github.com/mozilla/bigquery-etl/pull/5933/files
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4340)

Fix: Keep the 3 GA3 tasks unscheduled but leave parameters information in metadata.yaml

---

sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4347)

GROWTH-90 Fix Grain of New Table - can have multiple rows per client per search engine

---

sql/mozfun/serp_events/is_ad_component/udf.sql

Fix bigquery-etl CI by formatting a UDF
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4371)

Reformat sql/mozfun/serp_events/is_ad_component/udf.sql

---

sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/checks.sql

This failed today because of `cad_redirect_desktop_download` discrepancy of 68 vs 66 events (new vs old). We should bump it to avoid false positives.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4376)

Update accounts_events sql check

---

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/query.sql
tests/sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/test_aggregation/expect.yaml

The CI is failing on dry run b/c this field is missing from the struct
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4379)

adding location selected to struct

---

bigquery_etl/view/__init__.py

[ltv.firefox_desktop_client_ltv](https://github.com/mozilla/private-bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/ltv/firefox_desktop_client_ltv/view.sql) is deploying into shared-prod instead of mozdata because view publish is replacing `moz-fx-data-shared-prod` in the comment with `mozdata` instead of the view target.  Then a table is created in mozdata because of the `schema.deploy` below.
This change results in an error if the target view isn't created and makes the project replacement skip comments.  Also some error messages are written to stderr now to make them easier to find in the logs
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4391)

Update view publish to not replace project names in comments

---

bigquery_etl/schema/__init__.py
bigquery_etl/view/__init__.py

Following up on https://github.com/mozilla/bigquery-etl/pull/5969.  This currently fails for `telemetry.newtab_clients_daily` with `412 Precondition check failed` because the `client.get_table` call was moved before the schema deploy, which makes the label update call use the ETag of the old table object which fails the `If-Match` check here 
https://github.com/googleapis/python-bigquery/blob/ba61a8ab0da541ba1940211875d7ea2e9e17dfa8/google/cloud/bigquery/client.py#L1424
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4395)

Use updated table object in view publish

---

sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_beta_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_nightly_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_release_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_beta_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_nightly_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_release_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_beta_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_nightly_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_release_aggregates/view.sql

This PR filters out `boolean` probes and Metrics from the GLAM views used to serve the app. GLAM does not officially support `boolean` probes yet.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4406)

Don't fetch boolean probes since GLAM doesn't support them yet

---

bigquery_etl/shredder/config.py

These tables have seven days of retention so shredder doesn't actually do anything when it tries to delete.  I'm looking to clean up the config and be more explicit about what doesn't need shredding.
@edugfilho Does removing these tables from shredder make sense to you?
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4407)

Remove glam intermediate tables from shredder

---

sql/moz-fx-data-shared-prod/glam_derived/client_probe_counts_firefox_desktop_beta_v1/schema.yaml
sql/moz-fx-data-shared-prod/glam_derived/client_probe_counts_firefox_desktop_nightly_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/schema.yaml

percentiles columns were removed in https://github.com/mozilla/bigquery-etl/pull/5966 so this is failing dry run which wasn't caught in the original pr because these queries weren't changed.  Also updated the upstream `glam_client_probe_counts_extract_v1` schema for consistency but I don't think this uses bqetl tooling.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4410)

Remove percentiles columns from client_probe_counts schema

---

sql/moz-fx-data-shared-prod/accounts_db_external/fxa_carts_v1/schema.yaml
sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_carts_v1/schema.yaml

This is failing in table deploy because the deployed tables use INT https://workflow.telemetry.mozilla.org/dags/bqetl_artifact_deployment/grid?root=&dag_run_id=manual__2024-08-01T07%3A16%3A51.391302%2B00%3A00&task_id=publish_new_tables&tab=logs
`amount` should be an integer, per https://mozilla.github.io/ecosystem-platform/reference/database-structure#database-fxa.  I'm guessing the existing table was created using the query.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4436)

Change fxa_carts amount to int in schema

---

bqetl_project.yaml
sql_generators/table_partition_expirations/__init__.py
sql_generators/table_partition_expirations/templates/metadata.yaml
sql_generators/table_partition_expirations/templates/schema.yaml
sql_generators/table_partition_expirations/templates/table_partition_expirations.sql

Table to track stable table partition expiry as part of [the data expiry alerts proposal](https://docs.google.com/document/d/15_JR2niBY2jZqbt9wzJVrXH_EGL3D2SrS7G7gUVBei8/edit#heading=h.frvje7pnwo3v).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4454)

[DENG-577] Create monitoring table for stable table expiration

---

bqetl

Silverblue symlinks `/home` -> `/var/home`, so using `pwd -P` returns
something different than $PWD. E.g:
$ pwd -P; pwd; echo $PWD
/var/home/ahal/dev/bigquery-etl
/home/ahal/dev/bigquery-etl
/home/ahal/dev/bigquery-etl
Removing the `-P` flag respects the symlink.

fix(bqetl): issue running ./bqetl with Fedora Silverblue

---

sql/moz-fx-data-marketing-prod/google_search_console/search_impressions_by_page/schema.yaml
sql/moz-fx-data-shared-prod/google_search_console/limited_historical_search_impressions_by_page/metadata.yaml
sql/moz-fx-data-shared-prod/google_search_console/limited_historical_search_impressions_by_page/schema.yaml
sql/moz-fx-data-shared-prod/google_search_console/limited_historical_search_impressions_by_page/view.sql
sql/moz-fx-data-shared-prod/google_search_console/limited_historical_search_impressions_by_site/metadata.yaml
sql/moz-fx-data-shared-prod/google_search_console/limited_historical_search_impressions_by_site/schema.yaml
sql/moz-fx-data-shared-prod/google_search_console/limited_historical_search_impressions_by_site/view.sql
sql/moz-fx-data-shared-prod/google_search_console/search_impressions_by_page/metadata.yaml
sql/moz-fx-data-shared-prod/google_search_console/search_impressions_by_page/schema.yaml
sql/moz-fx-data-shared-prod/google_search_console/search_impressions_by_page/view.sql
sql/moz-fx-data-shared-prod/google_search_console/search_impressions_by_site/metadata.yaml
sql/moz-fx-data-shared-prod/google_search_console/search_impressions_by_site/view.sql
sql/moz-fx-data-shared-prod/google_search_console_derived/search_impressions_by_page_v1/metadata.yaml
sql/moz-fx-data-shared-prod/google_search_console_derived/search_impressions_by_site_v1/metadata.yaml

[DENG-4329]: https://mozilla-hub.atlassian.net/browse/DENG-4329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4480)

Move limited historical Google Search Console data into separate views (DENG-4329)

---

sql/moz-fx-data-shared-prod/fxci/task_run_costs/view.sql
sql/moz-fx-data-shared-prod/fxci_derived/task_run_costs_v1/metadata.yaml
sql/moz-fx-data-shared-prod/fxci_derived/task_run_costs_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4452)

Add a derived query to compute Firefox-CI task run costs

---

bigquery_etl/cli/query.py
bigquery_etl/cli/stage.py
bigquery_etl/dryrun.py
bigquery_etl/schema/__init__.py
sql_generators/glean_usage/glean_app_ping_views.py

This is fixing view deploys
Fixes some issues introduced in https://github.com/mozilla/bigquery-etl/commit/7024b6976e5f8f2f6e365107b3ef97547ee2ab0f
It turns out the dryrun function does not return the `MODE` value for table schemas. Falling back to running queries to get the schemas. This results in the app view schemas not being generated correctly and getting duplicate fields added

Fall back to running query to get view schema

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v2/query.sql

The column was added to schema in previous [PR-6025](https://github.com/mozilla/bigquery-etl/pull/6025/files#diff-6a95ab1028bac9fe9f6ff09d27107bc49d34f91e4190125f6bb57bd2df7436cb) , but earlier I missed adding it to the query itself, so this is to add it to the query. 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4506)

DENG-4482 update clients_last_seen_v2 query to include profile_group_id

---

bigquery_etl/deploy.py
tests/test_deploy.py

This was a recent deploy failure case, see `bqetl_artifact_deployment` [earlier this week](https://workflow.telemetry.mozilla.org/dags/bqetl_artifact_deployment/grid?dag_run_id=scheduled__2024-08-11T00%3A00%3A00%2B00%3A00&task_id=publish_new_tables&tab=logs). 
Raises the except `FailedDeployException` to ensure deploys that fail for this reason get added to the failed deploys list for easier debugging in the future.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4532)

chore(deploys): Catch and raise for missing dataset/project in table deploys

---

sql_generators/table_partition_expirations/__init__.py

This is to make the generated sql deterministic so it doesn't get added to the diff when nothing is changed
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4552)

Sort datasets in table_partition_expirations sql generator

---

sql/moz-fx-data-shared-prod/telemetry/events_v1/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/events_v1/schema.yaml

**Purpose:** 
* Adding profile_group_id to events_v1 view
* Adding schema.yaml for existing deprecated table in production since it's needed for CI checks to pass
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4553)

DENG-4546 - add profile_group_id to events_v1 view and add schema.yaml 

---

sql_generators/table_partition_expirations/templates/table_partition_expirations.sql

Adds stable tables that don't have partition expiration to `monitoring_derived.table_partition_expirations_v1`.  This is only a few tables in `telemetry_stable` right now but it might be useful to be able to check for glean tables that don't have retention set but should
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4585)

Include tables with no expirations in table_partition_expirations

---

bigquery_etl/dryrun.py

The following is showing up in a few places:
```
INFO - [base]  cannot access local variable 'table_metadata' where it is not associated with a value
```
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4597)

fix(dryrun): table_metadata used before reference

---

sql/moz-fx-data-shared-prod/monitor_frontend_derived/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/monitor_frontend_derived/event_monitoring_live_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitor_frontend_derived/monitor_dashboard_user_journey_funnels_v1/metadata.yaml

Reverts mozilla/bigquery-etl#5916
`RECORD` types are now supported in fides
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4592)

Revert "chore(data-privacy-mapping): DSRE-1690 - ignore tables contaiing RECORD type"

---

sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_beta_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_nightly_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_release_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_beta_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_nightly_aggregates/view.sql
sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_release_aggregates/view.sql

This is part of the preparation to make GLAM public. The spreadsheet below was used to classify which probes are `Confidential`, which means they shouldn't be displayed on GLAM.
Source:  https://docs.google.com/spreadsheets/d/1fsmqA0YfFO9gUasfDa6AvQdNgTcC0vIHzzOvLtfJunI/edit?usp=sharing
Note that FoG and Fenix have different lists.
This is the scrappy version of this work. I intend to move these to a centralized source, such as a table or a config file. …

chore(GLAM): update list of confidential probes

---

.circleci/workflows.yml

The previously used [Ubuntu 20.04 executor image](https://circleci.com/developer/machine/image/ubuntu-2004) has been [deprecated](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177) and will be removed on 2024-09-30.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4647)

Update CircleCI config to use latest Ubuntu 20.04 executor image

---

sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/query.sql
tests/sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/test_braze_subscriptions/expect.yaml
tests/sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/test_braze_subscriptions/moz-fx-data-shared-prod.braze_derived.subscriptions_map_v1.yaml
tests/sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/test_braze_subscriptions/moz-fx-data-shared-prod.braze_derived.user_profiles_v1.yaml

Reverts mozilla/bigquery-etl#6097
I need to revert this to prevent task failures while I work on the work around that will duplicate the table in a way that Airflow has access (there are permission issues). See [this PR](https://github.com/mozilla/private-bigquery-etl/pull/199) for more context
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3503)

Revert "DENG-3503 updating to use v2 table"

---

.circleci/workflows.yml

The `docker/machine` executor from v2.2 of that orb was using a [deprecated](https://discuss.circleci.com/t/linux-image-deprecations-and-eol-for-2024/50177) Ubuntu 20.04 image that CircleCI will remove on 2024-09-30.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4651)

Upgrade the CircleCI Docker orb to v2.6

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/rayserve_cost_fakespot_tenant_v1/view.sql

This PR adds a view to surface the total compute cost of all Ray Serve workloads of `fakespot` tenant that are deployed via [kuberay operator](https://docs.ray.io/en/latest/serve/production-guide/kubernetes.html) on `dataservices-high-nonprod` shared GKE cluster.
I have added the view in `monitoring_derived` following the pattern in https://github.com/mozilla/bigquery-etl/pull/5956
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4691)

DENG-4691 Add views for Ray Serve compute costs for fakespot tenant

---

sql/moz-fx-data-shared-prod/firefox_desktop_derived/review_checker_microsurvey_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_desktop_derived/review_checker_microsurvey_v1/schema.yaml

This PR does 3 things:
* Adds profile group ID to the table
* Adds a schema since one doesn't exist
* Rewrites the query slightly since, in the existing code, the first CTE is unnecessary/not doing anything
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4708)

DENG-4630 Add profile_group_id to review_checker_microsurvey_v1

---

sql_generators/events_daily/templates/events_daily_v1/query.sql

This fixes `bqetl_fenix_event_rollup.fenix_derived__events_daily__v1` that is currently failing.
I have tested this reduced threshold on `2024-08-29`, getting `20451307/20451581=~99.99%` record count vs. production. This seems like a reasonable tradeoff for a quick fix given that `events_daily` is no longer our preferred way to analyze funnels.

Bug 1915728 - Reduce overactive clients filter value in events_daily queries

---

bigquery_etl/glam/generate.py
script/glam/generate_glean_sql

This PR addresses the impact of https://github.com/mozilla/telemetry-airflow/pull/2081, which fixes the currently broken GLAM FoG and GLAM Fenix ETLs.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4715)

fix(GLAM): Fix boolean parameter passing to generate_glean_sql

---

bigquery_etl/metadata/parse_metadata.py
bigquery_etl/metadata/publish_metadata.py
tests/cli/test_cli_metadata.py
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/metadata.yaml

https://mozilla-hub.atlassian.net/browse/DENG-4601
This PR adds support for `monitoring` metadata. Initially, this will just indicate whether a table should/is monitored in Bigeye.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4710)

[DENG-4601] Add monitoring metadata support

---

bigquery_etl/glam/templates/macros.sql

Moves `where`  after `cross join`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4730)

fix(GLAM): Fix bucket_counts template generation

---

sql_generators/mobile_kpi_support_metrics/templates/new_profile_clients.view.sql

Also, use submission_date as first_seen_date so that the downstream query date filter works correctly and limits processing
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4505)

feat: include is_daily_user filter to ensure only new profiles are included

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/rayserve_cost_fakespot_tenant_prod_v1/view.sql

This PR adds a view to surface the total compute cost of all Ray Serve workloads of `fakespot` tenant that are deployed via [kuberay operator](https://docs.ray.io/en/latest/serve/production-guide/kubernetes.html) on `dataservices-high-prod` shared GKE cluster.
I have added the view in `monitoring_derived` following the pattern in https://github.com/mozilla/bigquery-etl/pull/6146
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4691)

DENG-4691: Add views for fakespot cost data in dataservices prod project

---

bigquery_etl/backfill/query_with_shredder_mitigation_template.sql

Fixes a to fix sqlglot parsing error in the CI.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4747)

Add defaults in template

---

bqetl_project.yaml

This will generate events_stream and event_monitoring_live tables for ads_backend.
We originally skipped this app because there was a delay in its ping table deployment.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4775)

Unskip ads_backend in glean_usage generator

---

dags.yaml

remove Leli from the docs for the Braze DAG
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4788)

remove leli from braze dag docs

---

bigquery_etl/deploy.py

The error from bigquery isn't logged right now which makes it hard to debug, e.g. https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/38985/workflows/ad9dac2f-8cc5-45ea-8b09-be62f635170b/jobs/443475
Example error: `Failed deploy for sql/benwubenwutest/telemetry_derived/ga3_events_v1/query.sql: (Unable to create table benwubenwutest.telemetry_derived.ga3_events_v1: 400 POST https://bigquery.googleapis.com/bigquery/v2/projects/benwubenwutest/datasets/telemetry_derived/tables?prettyPrint=false: Clustering is enabled but no fields were specified.)`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4789)

Add error message to failed deploys

---

sql_generators/glean_usage/event_error_monitoring.py
sql_generators/glean_usage/event_monitoring_live.py

This fixes the new logic for skipping Glean apps in the glean_usage generation for event monitoring. This should also unblock view deploys
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4801)

Fix skipping of apps in glean_usage

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1.sql.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/schema.yaml
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/moz-fx-data-shared-prod.telemetry_stable.main_v5.schema.json

Add profile_group_id to telemetry_derived.clients_daily_scalar_aggregates_v1 without changing existing grain of table
* [DENG-4847](https://mozilla-hub.atlassian.net/browse/DENG-4847)
[DENG-4847]: https://mozilla-hub.atlassian.net/browse/DENG-4847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4850)

feat(DENG-4847): Add profile_group_id to telemetry_derived.clients_daily_scalar_aggregates_v1

---

sql/moz-fx-data-shared-prod/monitoring_derived/shredder_rows_deleted_v1/query.py

Curly braces need to be escaped.
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1919236 and https://github.com/mozilla/bigquery-etl/pull/6197/files#diff-57d8ebcb18d45fb7886e62272db614409d5d34e58e9a77d421a94130f3ca1dcd
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4859)

Bug 1919236 - Fix Shredder monitoring query

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1.sql.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/schema.yaml

This is meant to revert prior PR https://github.com/mozilla/bigquery-etl/pull/6207 so that I can take a bit more time to make sure it works for all 3 before I push the change again.
* [DENG-4847](https://mozilla-hub.atlassian.net/browse/DENG-4847)
[DENG-4847]: https://mozilla-hub.atlassian.net/browse/DENG-4847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4867)

DENG-4847 Revert adding profile_group_id to GLAM clients daily aggregates scalar 3 generated queries

---

bigquery_etl/glam/templates/clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/clients_histogram_aggregates_v1.sql
sql/mozfun/glam/histogram_filter_high_values/metadata.yaml
sql/mozfun/glam/histogram_filter_high_values/udf.sql

This PR fixes `glam_fog.clients_daily_histogram_aggregates` by removing anomalies in histogram values that lead to overflow when summed.
* https://github.com/mozilla/glam/issues/2947

fix(glam_fog) SUM overflow

---

bigquery_etl/shredder/delete.py

I don't think it makes sense to tie the setup parallelism to the shredder query parallelism.  This reduces startup time when parallelism is low: ~35s at 6 threads vs. 140s at 1 vs. 75s at 2.  
*
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4874)

Set find_glean_targets thread count to 6 in shredder

---

sql_generators/funnels/configs/login_funnels_by_service.toml

Switches accounts login funnel to to use only `events` ping. This is required to deprecate `accounts_events` ping.
Tested by generating the query, running it on `2024-09-18`, and comparing output to production table, which matched the row count.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4880)

DENG-3274 Switch accounts login funnel to event ping

---

sql/moz-fx-data-shared-prod/monitoring/shredder_per_table_stats/view.sql
sql/moz-fx-data-shared-prod/monitoring/shredder_run_stats/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/shredder_per_job_stats_v1/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/shredder_per_job_stats_v1/schema.yaml

This will make it easier to find failed jobs and filter them out in some aggregations 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4890)

Add job error fields to shredder job monitoring

---

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_merino_extract_v1/checks.sql

* MC-1457
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4905)

removing uniqueness check on scheduled corpus item id

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1.sql.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/schema.yaml

This PR adds the new column "profile group ID" to the 3 different queries that get generated from moz-fx-data-shared-prod.telemetry_derived.clients_daily_scalar_aggregates_v1.sql.py for the 3 agg types:
- scalars
- keyed_scalars
- keyed_booleans
* [DENG-4847](https://mozilla-hub.atlassian.net/browse/DENG-4847)
* [DENG-4864](https://mozilla-hub.atlassian.net/browse/DENG-4864)
* [DENG-4868](https://mozilla-hub.atlassian.net/browse/DENG-4868)
[keyed_booleans_new.txt](https://github.com/user-attachments/files/17075872/keyed_booleans_new.txt) >>  mozdata.analysis.kwindau_test_20240920_keyed_bools
[keyed_scalars_new.txt](https://github.com/user-attachments/files/17075873/keyed_scalars_new.txt) >> mozdata.analysis.kwindau_test_20240920_keyed_scalars …

DENG-4847 - Add profile_group_id to  clients_daily_scalar_aggregates_v1

---

sql_generators/glean_usage/common.py

The Firefox crash reporter app only sends crash pings, so it won't have any baseline pings.
* [Bug 1920582](https://bugzilla.mozilla.org/show_bug.cgi?id=1920582): Airflow task `bqetl_glean_usage.checks__warn_firefox_crashreporter_derived__baseline_clients_last_seen__v1` failed for exec_date 2024-09-20
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4925)

Exclude `firefox_crashreporter` Glean app from baseline ping checks (bug 1920582)

---

sql_generators/mobile_kpi_support_metrics/__init__.py
sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.query.sql
sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.schema.yaml
sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.view.sql

We need to add this field to the attribution field to be able to identify which partnership a specific client came from.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4935)

feat(): add distribution id to attribution clients template

---

bigquery_etl/cli/monitoring.py
bigquery_etl/metadata/parse_metadata.py
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/releases_v1/bigconfig.yml
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/releases_v1/metadata.yaml

This extends the `monitoring` metadata to allow for specifying a collection that the metric should be added to.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4943)

Allow specifying a collection for monitored tables
