mozilla/bigquery-etl

sql/clients_last_seen_v1.init.sql
same output, but it uses a window to avoid doing `group by` which in turn makes it much faster
when limiting the input to 2019-02-25 and 2019-02-26 I observed ~8.5x less compute usage and ~6x less time
(I also checked on making a similar change to the non-init version, but the `full outer join` used there instead of a `group by` was more efficient)
=> Optimize clients_last_seen_v1.init.sql

sql/firefox_nondesktop_exact_mau28_by_product_by_dimensions_v1.sql
For a time, we thought we were going to use release only for KPI
calculations, but this is likely going to revert to the historical
stance of including prerelease in MAU calculations.
This PR removes the filter we had on channel, and retains normalized_channel
as a dimension so we can filter by channel if needed at the analysis level.
=> Add normalized_channel to nondesktop dimensions

sql/firefox_nondesktop_exact_mau28_by_dimensions_v1.sql, sql/firefox_nondesktop_exact_mau28_by_product_v1.sql, sql/firefox_nondesktop_exact_mau28_raw_v1.sql
This is an alternative to #13 that separates ETL to a single
dimensional `_raw_v1` table and then delays details for the presentation
layer to live views where possible.
=> Refactor nondesktop exact_mau28 tables into live views

sql/firefox_nondesktop_exact_mau28_raw_v1.sql
As discussed in the [Smoot Growth Dashboard Engineering Requirements](https://docs.google.com/document/d/1L8tWDUjccutGGAldhpypRtPCaw3kkXboPUTtTZb02OA/edit?usp=sharing):
> In order to support statistical inference (confidence intervals and hypothesis tests), we require the concept of a ID Bucket.  We divide the space of user IDs (probably client_id in most cases) into 20 buckets with equal probability of assignment into each bucket.  It is very important that this assignment is orthogonal to anything else that we care about - for example, it would be a problem if newer profiles were more likely to be assigned to particular buckets, or if profiles in certain experiment arms always ended up in particular buckets.
=> Add bucket_id to nondesktop tables

sql/firefox_nondesktop_exact_mau28_by_dimensions_v1.sql, sql/firefox_nondesktop_exact_mau28_by_product_v1.sql
Per [BQ docs on creating views](https://cloud.google.com/bigquery/docs/views#creating_a_view):
> For standard SQL views, the query must include the project ID in table and view references in the form `[PROJECT_ID].[DATASET].[TABLE]`.
We also remove the `observation_date` column. After further discussion with
the growth dashboard group, we're comfortable using the established definition
of the MAU window including the date of report; the concern is to make sure
we never include a partial day, which is already guaranteed by batch processing
only after a day is closed.
=> Update live views to use fully qualified table names

sql/firefox_desktop_exact_mau28_by_dimensions_v1.sql, sql/firefox_desktop_exact_mau28_v1.sql
Mirrors what we've done for nondesktop.
Actually rolling this out will involve getting the change merged
to `spark-parquet-to-bigquery`, then doing a manual recreation of the table
and downstream. Because there's no windowing or joining involved, though,
those recreations can each be done efficiently in a single query that takes
perhaps a few minutes to run.
This change will allow us to move the Growth Dashboard off of Spark-based
analysis of Parquet datasets and onto BQ (via Redash)!
=> Add WAU and id_bucket to desktop mau datasets

sql/firefox_accounts_exact_mau28_by_dimensions_v1.sql, sql/firefox_accounts_exact_mau28_raw_v1.sql, sql/firefox_accounts_exact_mau28_v1.sql, sql/fxa_users_daily_v1.sql, sql/fxa_users_last_seen_v1.init.sql, sql/fxa_users_last_seen_v1.sql
There will be follow-ups in the next few days to include daily imports from the FxA team's BQ projects.
=> Add first phase of FxA ETL for calculating MAU

sql/firefox_accounts_exact_mau28_raw_v1.sql, sql/fxa_users_daily_v1.sql, sql/fxa_users_last_seen_v1.sql
This allows for a true "inclusive tier 1" calculation that matches exactly with what you get from the self-join method of calculating MAU from raw events. In particular, it allows us to reproduce exactly the calculation that has been used to define the relationships goal for 2019.
=> Add seen_in_tier1_country for fxa tables

sql/firefox_accounts_exact_mau28_raw_v1.sql, sql/fxa_all_events_v1.sql, sql/fxa_users_last_seen_v1.init.sql, sql/static/README.md, sql/static/fxa_amplitude_export_users_daily.sql, sql/static/fxa_amplitude_export_users_last_seen.sql
We learned today that backfilled data contains hashed user_id
while the live Stackdriver pipeline for FxA contains unhashed ids.
Running the relevant HMAC hash would be complex, so we are instead
defining an overlap period of 28 days where we calculate intermediate
MAU tables for backfill and for stackdriver data separately,
then we union the two together.
We'll coordinate to do a final one-time import of backfill data
tomorrow morning, then use Stackdriver data from 3/28 and forward.
=> Adapt FxA ETL for merging backfill data at the raw MAU stage

sql/firefox_accounts_exact_mau28_by_dimensions_v1.sql, sql/firefox_accounts_exact_mau28_v1.sql, sql/firefox_nondesktop_exact_mau28_v1.sql
As discussed in mozilla/firefox-data-docs#258
the current column name for tier 1 mau in firefox accounts tables
uses a suffix rather than a prefix.
This renames the column in the by_dimensions view rather than in
the raw table so that we avoid having to backfill and update the
Airflow DAG.
In the exact_mau_v1 view, we continue to use the simple "tier1_mau" column
so that we have consistently named columns across the final views
for desktop, nondesktop, and fxa. And these columns are exactly
match exactly with what is presented in the growth dashboard
(we show tier 1 plots for all 3, but only FxA is using the
"seen in tier 1 country" usage criterion).
---
Also, we add a final nondesktop view that aggregates across products so that we can make the statement in the docs that these final …
=> Tweaks to exact_mau views for consistency

sql/smoot_usage_v1.sql
Implements the usage table described in [Jesse's Google Doc](https://docs.google.com/document/d/1wbcMGEw4b7GkFsNV74n-h9OK_OLRRgPdFyxdjjHDmiY/edit)
as a live view on top of `clients_daily`. This version excludes
the new profile creation usage_id which requires looking at a window of
history. 
That will wait for a subsequent change as it is more involved, likely needing a materialized table that could be unioned into this view.
This view already exists and can be queried like:
```
SELECT *
FROM `moz-fx-data-derived-datasets.telemetry.smoot_usage_v1`
WHERE date = '2019-03-01'
LIMIT 1000
```
=> Bug 1539385 Add smoot_usage_v1 view on clients_daily

sql/firefox_accounts_exact_mau28_by_dimensions_v1.sql, sql/firefox_nondesktop_exact_mau28_by_dimensions_v1.sql
This PR replaces a CASE statement we were using to partially convert
country names to country codes. Rather than maintain our own static
dataset of country data, we join with one of the public datasets
that Google maintains.
This could be a useful pattern for some other common lookups in the future, but I'm interested in thoughts on whether adding a dependency on public datasets could be problematic.
=> Join with public dataset for country code lookup

sql/firefox_accounts_exact_mau28_by_dimensions_v1.sql, sql/firefox_nondesktop_exact_mau28_by_dimensions_v1.sql
It turns out that the country codes in the US Census Bureau
public dataset are not the same as ISO 3166 codes.
They use "UK" for United Kingdom and "GB" for Gabon whereas
ISO 3166 specifies United Kingdom as "GB".
Reverts https://github.com/mozilla/bigquery-etl/pull/72
=> Revert join to US census data for country codes

pyspark/export_to_parquet.py, script/pyspark/export_to_parquet.py
This requires a dataproc cluster configured with necessary credentials and using `spark-submit --jars gs://spark-lib/bigquery/spark-bigquery-latest.jar ...`, or equivalent.
May be used with `gs://spark-lib-relud/bigquery/spark-bigquery-latest-SNAPSHOT.jar` for `NUMERIC` type support.
=> Add pyspark script for exporting to parquet

.circleci/config.yml
I forgot `+` excludes the original variable, so we had `IMAGE=/bigquery-etl:latest`, which isn't valid.
=> Fix issue with docker image name for deploy

.circleci/config.yml
*sigh* https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables
`CIRCLE_USERNAME` is the github username that triggered the build
`CIRCLE_PROJECT_USERNAME` is the username of the current project
=> Use CIRCLE_PROJECT_USERNAME

script/pyspark/export_to_parquet.py
`submission_date IS NOT NULL` isn't a sufficient where clause to prevent pushdown of `drop('submission_date')` through to the storage api request.
testing shows `submission_date = DATE 'SUBMISSION_DATE'` does what we need.
=> Fix --submission-date for export_to_parquet.py

README.md, sql/core_clients_daily_v1.sql, sql/static/fxa_amplitude_export_users_daily.sql
core_clients_daily_v1 was selecting latest row
extra:
- add recommendation to use earliest to readme
- fix mode_last in `static/fxa_amplitude_export_users_daily.sql`, not sure if I should remove this change, because it's too late because it's static.
not included:
- clients_daily_v7 already uses earliest
- fxa_users_daily_v1 doesn't deduplicate
=> Use earliest row with document_id by timestamp

sql/fxa_auth_bounce_events_v1.sql, sql/fxa_auth_events_v1.sql, sql/fxa_content_events_v1.sql
Fixes error:
> Error in query string: Error processing job 'moz-fx-data-derived-datasets:bqjob_r246b8e9136dc0b7f_0000016a8ec82840_1': Field name event_type does not exist in STRUCT<uid STRING, op STRING, action STRING, ...> at [13:26]
It looks like BigQuery was getting confused and including `auth_bounces` tables
as part of resolving schema for the `auth_*` wildcard. Adding an explicit
`20` for the century before the wildcard avoids the confusion.
=> Refined fxa table wildcards

sql/firefox_accounts_exact_mau28_by_dimensions_v1.sql, sql/firefox_desktop_exact_mau28_by_dimensions_v1.sql, sql/firefox_nondesktop_exact_mau28_by_dimensions_v1.sql, sql/static/.gitignore, sql/static/country_codes.csv, sql/static/country_codes.sh, sql/static/country_names_alternate.csv
This is exploring a potential new pattern of generating a static table based on a bash script that runs `bq mk` and `bq load` commands to load CSVs to BQ.
I am putting these in the `static` dataset, but we don't have the same permissions there for redash, etc. to be able to reach them. We could simply put them in `telemetry` for now, or we could use this as an excuse to question how we want to lay out datasets again.
=> Add static country_code and country_name tables

sql/clients_last_seen_v1.sql, tests/clients_last_seen_v1/test_single_day/clients_daily_v6.schema.json, tests/clients_last_seen_v1/test_single_day/clients_last_seen_v1.schema.json
Discussing with Google in case 19367621; this seems like a bug in BQ since this commit should give the same logical result, but we're currently seeing the job fail due to a struct schema mismatch error.
This workaround gets the query passing the parser.
=> Specify new fxa_configured field in clients_last_seen

sql/firefox_kpi_dashboard_v1.sql
The desktop forecast is temporarily frozen, so this query should
follow what's in the forecast and keep desktop data frozen at
2019-05-15 until the forecast reflects new actuals, at which point
it will automatically start pulling in the newer data.
=> Update firefox_kpi_dashboard query for missing data

sql/firefox_desktop_exact_mau28_v1.sql, sql/firefox_kpi_dashboard_v1.sql
A prototype of the KPI dashboard using these imputed values can be seen in https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/131180/dashboard/131209/present
=> Use imputed values for desktop KPIs after Armag-add-on

tests/test_longitudinal.py
this makes tests runnable in virtualenvs, etc
=> don't depend on PATH for invoking subprocess in test

tests/README.md
The test documentation did not mention that the `GOOGLE_APPLICATION_CREDENTIALS` environment variable needs to be set otherwise almost all tests will fail locally. So I added that to the docs.
=> Add setting gcloud authentication credentials to test documentation

udf/udf_js_json_extract_histogram.sql, udf/udf_json_extract_histogram.sql, udf/udf_json_extract_int_map.sql
These will be used in performance testing of the proposed main ping representation where we leave histograms as JSON strings.
=> Add UDFs for parsing histogram JSON

udf/udf_json_extract_keyed_histogram_js.sql
I suspect we won't use this other than in tests since performance tests suggest we will probably want to represent keyed histograms as map types where the values are json strings representing individual histograms, rather than representing a keyed histogram as a single json string.
But I will use this in performance testing to confirm and document what interacting with keyed histograms as single json strings looks like.
=> Add udf_json_extract_keyed_histogram_js

script/publish_persistent_udfs
Is that the idea behind https://github.com/mozilla/bigquery-etl/issues/222? The scripts iterates through all the UDFs, gets all the dependencies and publishes the UDF and dependencies as persistent UDFs. 
I haven't actually executed/tested the script in a way that it publishes the UDFs in BigQuery, yet.
=> Script to publish persistent UDFs

sql/fenix_events_amplitude_v1.sql, sql/fenix_events_v1.sql, templates/fenix_events_amplitude_v1.sql, templates/fenix_events_v1.sql
Previously, the fenix_events_amplitude_v1 query
failed because there was no partition elimination.
=> Use partition elimination with fenix_events

sql/glean_clients_daily_v1.sql, templates/glean_clients_daily_v1.sql
We've had 0 dau for fenix the last 7 days due to switching which tables
are fed by the pipeline. I've backfilled from the _live tables, and this
will allow further days to get the right data.
=> Hit _live tables for fenix data

script/copy_deduplicate
This job failed in Airflow with `NameError: name 'destination_table_spec' is not defined`, motivating this PR.
=> Support options with underscores and fix incorrect variable

tests/test_udfs.py, udf_js/json_extract_events.sql
This is.. not fast but it works. Not sure if there's a great way to do this in a sql udf, especially without hard-coding in process types (which we do add to periodically.)
=> Add json_extract_events javascript udf

script/publish_persistent_udfs
if we don't set the default project id, then the bigquery logs for updating the udfs may show up in the wrong project, which is inconvenient when tracking down errors.
=> Reuse bigquery client and set default project_id

Dockerfile
this fixes CI `deploy` builds on master.
the problem is that alpine isn't compatible with python manylinux wheels (due to using a different compiler) and there's no tarball available on pypi to build protobuf 3.9.1
=> Build docker on python-slim

.circleci/config.yml
As part of the comments in https://github.com/mozilla/bigquery-etl/pull/338 I've created a new circleci restricted context `data-eng-bigquery-etl-dockerhub` and groups `dataops` and `telemetry` have access to this context. 
I've also removed all environment variables configured `bigquery-etl` in CircleCI UI and enabled `Pass secrets to builds from forked pull requests`.
=> Update deploy circleci workflow job to use restricted context

sql/telemetry/addon_aggregates/view.sql, sql/telemetry/addon_aggregates_v2/view.sql, sql/telemetry/addons_aggregates/view.sql, sql/telemetry/addons_aggregates_v2/view.sql, templates/telemetry/addon_aggregates/view.sql, templates/telemetry/addon_aggregates_v2/view.sql, templates/telemetry/addons_aggregates/view.sql, templates/telemetry/addons_aggregates_v2/view.sql
Update views to use the updated table name in https://github.com/mozilla/telemetry-airflow/pull/596.
=> Update addon_aggregates views to fix table rename bug1579478

.circleci/config.yml, .eslintrc.yml, .gitignore, README.md, package.json, script/format-sql
This is written for node because [sql-formatter](https://github.com/zeroturnaround/sql-formatter) is the first library I found that outputs SQL compatible with [our style guide](https://docs.telemetry.mozilla.org/concepts/sql_style.html), and my attempts at writing something to do this in python have proven fruitless.
cc @mythmon because we were talking about this yesterday and I'm not familiar with node, so the more eyes checking this work the better
=> Add script to format sql

script/copy_deduplicate
fixes #367
blocks https://github.com/mozilla/telemetry-airflow/pull/617
for sept 19th splitting up deduplication hourly totaled ~9.04TiB processed, vs ~8.75TiB for the single-query deduplication, or ~3.3% increase in cost. I ran it with `--parallelism=24` so that the queries would be simultaneous, all of the queries succeeded on the first try, and the slowest query ran for 32 minutes, followed by a 14 second copy operation. For comparison, the same day took 4 tries in airflow, the final attempt ran for 48 minutes, and including time for retries usually runs for 3-5 hours on week days.
=> Add --hourly option to copy_deduplicate

sql/telemetry/fxa_content_auth_oauth_events_v1/view.sql, templates/telemetry/fxa_content_auth_oauth_events_v1/view.sql
Following on #362, I'd like to add this view which is an expansion of `fxa_content_auth_events` to also include the new oauth events. I opted to make a new view instead of replacing the existing one (just to avoid breaking existing queries), but if we'd prefer to keep views to a minimum, I'd be OK with just renaming/replacing the old view. 
sorry for the PR out of the blue, just trying to get the FxA data in BQ up to snuff before skyline.
=> create new fxa_auth_content_oauth view

script/copy_deduplicate
and delete temp tables when finished, because there's no need to leave them around for a full day.
=> Set temp table expiration in copy_deduplicate

script/copy_deduplicate
Closes https://github.com/mozilla/bigquery-etl/issues/376
Addition to datetime.date considers only the days part of a timedelta,
so we have to convert to a timestamp first.
=> Bug: datetime logic in copy_deduplicate

script/copy_deduplicate
tested against a single sample_id from sept 19th's main_v4 pings:
```bash
bq mk relud-17123:telemetry_live
bq mk relud-17123:telemetry_stable
bq show --schema moz-fx-data-shared-prod:telemetry_live.main_v4 > /tmp/live_main_v4_schema.json
bq show --schema moz-fx-data-shared-prod:telemetry_stable.main_v4 > /tmp/stable_main_v4_schema.json
bq mk --time_partitioning_field=submission_timestamp --clustering_fields=submission_timestamp relud-17123:telemetry_live.main_v4 /tmp/live_main_v4_schema.json
bq mk --time_partitioning_field=submission_timestamp --clustering_fields=sample_id relud-17123:telemetry_stable.main_v4 /tmp/stable_main_v4_schema.json
bq cp -f moz-fx-data-shared-prod:telemetry_live.main_v4'$'20190919 relud-17123:telemetry_live.main_v4'$'20190919
bq cp -f …
```
=> Add --slices option to copy_deduplicate

script/copy_deduplicate
this PR cuts the time to run `time script/copy_deduplicate --only telemetry_live.main_v4 --dry_run --date=2019-09-19 --parallelism=24 --slices=24` for me in from 26 seconds to 9 seconds.
optimizations:
- distribute `list_tables` calls to the thread pool
- skip `list_datasets` call when `--only` doesn't have globs in the datasets
- skip `list_tables` calls when `--only` doesn't have globs at all
- only compile glob patterns once, into a single regex
- distribute `get_query_job_configs` calls to 
this also makes `stable_table` a string, which is more readable for logging output
~~and fixes a bug where the `end_time` parameter was named  `start_time`~~ (moved to #383)
=> Improve list_tables speed for script/copy_deduplicate

udf/deanonymize_event.sql
Whoo, go @acmiyaguchi for getting event tuples working in BQ! This UDF renames the anonymous struct fields in event tuples into meaningful names
=> Add udf to deanonymize event tuples

sql/telemetry/sync/view.sql, templates/telemetry/sync/view.sql
Per [this pr](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/422) and [Bug 1572744](https://bugzilla.mozilla.org/show_bug.cgi?id=1572744), we should be using version `4` of the sync ping table for the unqualified table (rather than `v5`).
=> Use v4 of Sync pings

sql/telemetry_derived/fxa_users_services_first_seen_v1/init.sql, templates/telemetry_derived/fxa_users_services_first_seen_v1/init.sql
should have caught this before Jeff merged his PR, sorry :(. I think this means will will have to run the backfill again :(
this is similar to problem jeff addressed as part of https://github.com/mozilla/bigquery-etl/pull/396 that adds 'sync' for cert_signed events. I should have realized that we would have to do it for this table too. 
I'm not sure about the scope of the window clause but I hazarded a guess that I needed to repeat the `IF(` clause there. there may be a better way of doing it. 
we shouldn't have to worry about nulls creeping into service here because all the other `fxa_activity - *` events will have a non-null value for service. 
cc @ksiegler1
=> change fxa_users_services_first_seen_v1 to account for service being null for most sync events

sql/telemetry_derived/smoot_usage_new_profiles_v2/query.sql, templates/telemetry_derived/smoot_usage_new_profiles_v2/query.sql
Reverts a premature change in https://github.com/mozilla/bigquery-etl/pull/409
Airflow is not yet ready to run queries in shared-prod, which blocks us simplifying the paths here.
=> Use fully qualified table names again in smoot queries

sql/search/search_clients_daily_v8/query.sql, templates/search/search_clients_daily_v8/query.sql
Return null profile age in the case of clearly invalid date values
=> Use SAFE_SUBTRACT in search_clients_daily to prevent overflow errors

script/generate_sql, script/publish_persistent_udfs, sql/monitoring/structured_detailed_error_counts_v1/view.sql, sql/monitoring/structured_error_counts_v1/view.sql, templates/monitoring/structured_detailed_error_counts_v1/view.sql, templates/monitoring/structured_error_counts_v1/view.sql
Also cleans up a bug in the script for publishing views to get udf_js/gunzip
working, and removes accidental print statements in generate_sql.
Closes #414
=> Fix bugs in monitoring views

sql/telemetry/fxa_auth_events_v1/query.sql, sql/telemetry/fxa_oauth_events_v1/query.sql, templates/telemetry/fxa_auth_events_v1/query.sql, templates/telemetry/fxa_oauth_events_v1/query.sql
We found a dip in event counts because we were inadvertently throwing away sync events where the oauth client ID is null, but we want to include those events.
=> Handle null oauth client ID in fxa auth event query

script/format-sql
without this `<` and `>` are getting formatted as operators instead of parens
=> Fix automatic formatting for nested types

script/dryrun, script/generate_incremental_table, script/generate_views, script/publish_views
This uses python3 consistently in the script shebang headers. If I run `script/dryrun` via shell, it points to my default python installation which is python2.
=> Use `#!/usr/bin/env python3` consistently

script/run_multipart_query
and attempt to clean up temp tables on failure, and specify python3 in the `#!`, and make `clustering_fields=None` when it's not specified.
this should fix the `sql_main_summary` airflow task
=> Add --dataset_id and --project_id to script/run_multipart_query

sql/telemetry/windows_10_aggregate/view.sql, templates/telemetry/windows_10_aggregate/view.sql
Also fixes a logic error for Insider builds (should be looking at all higher build numbers).
=> Add the Windows 10 November 2019 update

bigquery_etl/pytest_plugin/sql.py
This allows testing queries which read from multiple tables with the same name but in different datasets.  e.g. `telemetry_stable.main_v4` and `telemetry_live.main_v4`
=> Combine project and dataset names with table name in test runner

sql/telemetry/main_summary/view.sql, templates/telemetry/main_summary/view.sql
This should have no functional change, but is future-proofing for the day when derived-datasets is torn down.
=> Fixup: reference the shared-prod main_summary_v4 view

script/dryrun, sql/telemetry_derived/clients_histogram_aggregates_v1/init.sql, sql/telemetry_derived/clients_histogram_aggregates_v1/query.sql, sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql, sql/telemetry_derived/clients_scalar_aggregates_v1/init.sql, sql/telemetry_derived/clients_scalar_aggregates_v1/query.sql, sql/telemetry_derived/clients_scalar_bucket_counts_v1/query.sql, sql/telemetry_derived/clients_scalar_probe_counts_v1/query.sql, sql/telemetry_derived/latest_versions/query.sql, templates/telemetry_derived/clients_histogram_aggregates_v1/init.sql, templates/telemetry_derived/clients_histogram_aggregates_v1/query.sql, templates/telemetry_derived/clients_histogram_probe_counts_v1/query.sql, templates/telemetry_derived/clients_scalar_aggregates_v1/init.sql, templates/telemetry_derived/clients_scalar_aggregates_v1/query.sql, templates/telemetry_derived/clients_scalar_bucket_counts_v1/query.sql, templates/telemetry_derived/clients_scalar_probe_counts_v1/query.sql, templates/telemetry_derived/latest_versions/query.sql
There are a bunch of changes here to speed up the glam dag computations. Here is a summary:
* Both `clients_scalar_aggregates` and `clients_histogram_aggregates` are now computed by incorporating 1 new day of data at a time with existing aggregations. This is faster than processing 90 days of data each time
* Both `clients_scalar_aggregates` and `clients_histogram_aggregates` now have `init.sql` files that include partitions and clustering
* In some cases, data was being unnested and grouped prematurely and it was more efficient to group before unnesting.
* Computations for scalar buckets were redundant and resulted in a static array anyways, so I've hardcoded it for now. We're currently in discussion with Data Science to think of better bucketing strategies for scalars so this will …
=> Address glam dag timeouts

sql/telemetry/devtools_panel_usage/view.sql, sql/telemetry_derived/devtools_panel_usage_v1/query.sql, templates/telemetry/devtools_panel_usage/view.sql, templates/telemetry_derived/devtools_panel_usage_v1/query.sql
As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1594222 this table replaces a Spark job that hit longitudinal and had some logic for building arrays and then exploding. @whd created a variant based on BQ main ping data, but looks like everything we need already exists in clients_daily. This doesn't match exactly with existing output, but the old job used approximate counts so exact matching isn't expected.
=> Bug 1594222 Recreate devtools panel Spark job as SQL

sql/telemetry/core/view.sql, templates/telemetry/core/view.sql, udf/normalize_metadata.sql
Addresses https://github.com/mozilla/gcp-ingestion/issues/631
This uses the new UDF only in the `core` view. We will need to update
the schema deploy pipeline after this is merged so that all default
views on top of historical ping tables use this function as well.
Note that this is now adding a persistent UDF call to a published view, which we had previously been avoiding, but persistent SQL UDFs have reached GA release, which should unblock us from using functions like this in views.
=> Add udf.normalize_metadata

udf/normalize_metadata.sql
=> Bug: Use SAFE.PARSE_TIMESTAMP when normalizing metadata

sql/telemetry/fxa_all_events_v1/view.sql, sql/telemetry/fxa_users_daily_v1/query.sql, sql/telemetry/fxa_users_last_seen_raw_v1/init.sql, sql/telemetry/fxa_users_last_seen_raw_v1/query.sql, sql/telemetry/fxa_users_last_seen_v1/view.sql, templates/telemetry/fxa_all_events_v1/view.sql, templates/telemetry/fxa_users_daily_v1/query.sql, templates/telemetry/fxa_users_last_seen_raw_v1/init.sql, templates/telemetry/fxa_users_last_seen_raw_v1/query.sql, templates/telemetry/fxa_users_last_seen_v1/view.sql, tests/telemetry/fxa_users_daily_v1/test_aggregation/expect.ndjson, tests/telemetry/fxa_users_daily_v1/test_aggregation/fxa_all_events_v1.ndjson
This change allows us to compare FxA MAU calculations that include or exclude the monitor email engagement events as added in https://github.com/mozilla/fxa/issues/2743
=> Add fxa usage criterion that filters out monitor email engagement

sql/telemetry/client_probe_counts_v1/view.sql, sql/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql, sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql, templates/telemetry/client_probe_counts_v1/view.sql, templates/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql, templates/telemetry_derived/clients_histogram_probe_counts_v1/query.sql
This PR includes 2 changes:
1. The histogram probe counts query has been broken up into two pieces as I've done with the scalar probe counts. The query was starting to run long on airflow and this change gives significant performance wins based on my testing so far.
2. I've updated the probe counts view to include percentiles. This is beneficial to the Glam app server so it only needs to query one place for all the data instead of 3.
The associated airflow PR is here: https://github.com/mozilla/telemetry-airflow/pull/799
=> Break up histogram processing and update probe counts view

udf/normalize_search_engine.sql
There are two approaches here.  One with a static table to map engine prefix to normalized name and the other is a udf with engines hardcoded in.  The table would work well but the issue is that outer joins require an equality from both sides of the join so something like this wouldn't work:
```sql
SELECT
normalized_engine,
COUNT(*) AS count
FROM
`moz-fx-data-shared-prod.search_derived.mobile_search_aggregates_v1`
LEFT JOIN
static.normalized_search_engine
ON 
(STARTS_WITH(engine, engine_prefix))
```
An outer join is needed because we want to treat unrecognized engines as `Other`.  I haven't thought of a good workaround for this other than not using a static table and just putting everything in a udf.
Other ideas I had are having a table of all possible engine values and scheduling a query …
=> Create udf for search engine normalization

udf/normalize_search_engine.sql
Spoke with bmiroglio and decided leaving other engine names as-is would be better for analysis.
=> Leave unrecognized engines as-is in normalize search

sql/telemetry_derived/clients_daily_v6/query.sql, templates/telemetry_derived/clients_daily_v6/query.sql, tests/telemetry_derived/clients_daily_v6/test_aggregation/expect.yaml
when this is merged, the column will need to be added to `clients_daily` and `clients_last_seen` to prevent errors in airflow
=> Bug 1598002 - add submission_timestamp_min to clients_daily

sql/telemetry_derived/devtools_events_amplitude_v1/view.sql, templates/telemetry_derived/devtools_events_amplitude_v1/view.sql
This makes all (except 'edit_rule' and 'tool_timer') new devtools
events included in Amplitude view, maintaining backward compatibility.
=> Include all Devtools events in Amplitude view

sql/search_derived/search_clients_last_seen_v1/query.sql, udf/add_monthly_searches.sql, udf/get_key_with_null.sql
Now I'm remembering why I used `"none"` instead of `null`! A full outer join with two `NULL` keys doesn't match and returns two separate rows.
=> Fix monthly_searches to account for null

sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql, templates/telemetry_derived/clients_histogram_probe_counts_v1/query.sql
The `udf_linear_buckets` function was having out of memory issues. Turns out some probes had a very high value for `nBuckets` - higher than their `max` which doesn't make much sense. So choosing the min of the two fixes the problem and makes more sense.
=> Fix out of memory in histogram_probe_counts UDF.

udf/parse_desktop_telemetry_uri.sql
Kinda internal, in that it's only useful for the `payload_bytes_error.telemetry` table but it's certainly been helpful for my current investigation
=> Add UDF to parse desktop telemetry uri components

script/generate_views, udf/normalize_glean_ping_info.sql
Closes https://github.com/mozilla/gcp-ingestion/issues/633
This PR introduces no change to non-Glean views other than some whitespace difference. For Glean pings, though, it adds a UDF call. Here's the result for fenix's baseline ping:
```
CREATE OR REPLACE VIEW
`moz-fx-data-shared-prod.org_mozilla_fenix.baseline`
AS SELECT
* REPLACE(
`moz-fx-data-shared-prod.udf.normalize_metadata`(metadata) AS metadata,
`moz-fx-data-shared-prod.udf.normalize_ping_info`(ping_info) AS ping_info)
FROM
`moz-fx-data-shared-prod.org_mozilla_fenix_stable.baseline_v1`
```
=> Add parsed start and end times to views on top of Glean schemas

.circleci/config.yml, script/generate_views, sql/telemetry/core/view.sql, sql/telemetry/sync/view.sql, sql/telemetry_derived/main_summary_v4/part1.sql, sql/telemetry_derived/main_summary_v4/part2.sql, templates/telemetry/core/view.sql, templates/telemetry/sync/view.sql, templates/telemetry_derived/main_summary_v4/part1.sql, templates/telemetry_derived/main_summary_v4/part2.sql, udf/deanonymize_event.sql, udf/normalize_main_payload.sql
As of https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/474
we will be allowing negative values for session lengths and event timestamps.
We provide some safety by modifying the user-facing view for main pings to null
out these negative values (since large negative values may cause significant
skew in aggregations).
We don't modify the user-facing view for event pings, but rather assume users
will be applying the deanonymize_events UDF and handle nulling negative values
there.
See bugs
https://bugzilla.mozilla.org/show_bug.cgi?id=1592012
and
https://bugzilla.mozilla.org/show_bug.cgi?id=1602521
=> Inject null for negative session_length and event timestamps

script/publish_views
This was not working in the production context where the target sql dir is
under /tmp as discussed in https://github.com/mozilla/bigquery-etl/pull/655#issuecomment-572789847
=> Bug: make skipping authorized views more robust

sql/telemetry/core/view.sql, sql/telemetry/focus_event/view.sql, sql/telemetry/mobile_event/view.sql, templates/telemetry/core/view.sql, templates/telemetry/focus_event/view.sql, templates/telemetry/mobile_event/view.sql
We see uppercase client_ids from some clients in core, focus_event,
and mobile_event pings. We are fixing this in the pipeline (see
https://github.com/mozilla/gcp-ingestion/pull/1069) and this PR ensures
lowercase for older data in user-facing views.
=> Ensure lowercase client_id for mobile pings

sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql, sql/telemetry_derived/clients_scalar_probe_counts_v1/query.sql, templates/telemetry_derived/clients_histogram_probe_counts_v1/query.sql, templates/telemetry_derived/clients_scalar_probe_counts_v1/query.sql
This PR contains 2 bug fixes:
1. There are new out of memory errors triggered by buckets again. This time its due to the number of buckets being too high. This query shows us a row that triggers this issue:
```
SELECT payload.histograms.memory_total
FROM `moz-fx-data-shared-prod.telemetry_stable.main_v4`
WHERE DATE(submission_timestamp) = '2020-01-08'
AND normalized_os = 'Windows'
AND application.build_id = '20191202093317'
AND normalized_channel = 'release'
AND SPLIT(application.version, '.')[OFFSET(0)] = '71'
AND client_id IS NOT NULL
AND JSON_EXTRACT(payload.histograms.memory_total, "$.bucket_count") = '813824896'
```
It looks like `813824896` is a bogus number of buckets. So I looked at the probe info service and it seems the max number of buckets is actually `10000` which explains …
=> Glam bug fixes

sql/monitoring/structured_detailed_error_counts_v1/view.sql, sql/monitoring/structured_error_counts_v1/view.sql, templates/monitoring/structured_detailed_error_counts_v1/view.sql, templates/monitoring/structured_error_counts_v1/view.sql
Previously we used inner join, which left out pings which either
had no errors or no valid pings. This change will let those
flow through to be monitored.
=> Use full outer join for error views

sql/telemetry_derived/clients_daily_histogram_aggregates_v1/query.sql, sql/telemetry_derived/clients_daily_keyed_histogram_aggregates_v1/query.sql, templates/telemetry_derived/clients_daily_histogram_aggregates_v1.sql.py, templates/telemetry_derived/clients_daily_histogram_aggregates_v1/query.sql, templates/telemetry_derived/clients_daily_keyed_histogram_aggregates_v1/query.sql
It seems Glam was affected similarly by data from Jan 15, 2020. So I'm using SAFE_CAST() as done in https://github.com/mozilla/bigquery-etl/pull/681
=> Use SAFE_CAST in Glam.

sql/telemetry/clients_last_seen_v1/view.sql, sql/telemetry/main_summary_v4/view.sql, templates/telemetry/clients_last_seen_v1/view.sql, templates/telemetry/main_summary_v4/view.sql
draft so that this isn't merged until backfilling to 2019-10-25 finishes
=> Bug 1593773 - Move the main summary cutover date back to 2019-10-25

sql/telemetry_derived/clients_histogram_aggregates_v1/query.sql, templates/telemetry_derived/clients_histogram_aggregates_v1/query.sql
There are shuffle errors happening in the Glam dag right now: https://workflow.telemetry.mozilla.org/log?execution_date=2020-01-27T00%3A00%3A00%2B00%3A00&task_id=clients_histogram_aggregates&dag_id=glam
I pin-pointed that they were coming from the join that is being changed in this PR. This change seems to reduce the amount of shuffling and my tests in the BQ console seem to be working.
=> Make histogram join in Glam more efficient.

script/publish_metadata
BigQuery supports adding labels as tags. For labels with a boolean value it makes sense to add them as tags instead of key-value pairs. This is, for example, the case for: 
```yaml
labels:
public_bigquery: true  # would appear as "public_bigquery" in the labels attached to the table 
public_json: false  # would not be part of the table labels
```
=> Add support for tags when publishing metadata

sql/telemetry_derived/clients_histogram_aggregates_merged_v1/init.sql, sql/telemetry_derived/clients_histogram_aggregates_merged_v1/query.sql, sql/telemetry_derived/clients_histogram_aggregates_new_v1/init.sql, sql/telemetry_derived/clients_histogram_aggregates_new_v1/query.sql, sql/telemetry_derived/clients_histogram_aggregates_old_v1/init.sql, sql/telemetry_derived/clients_histogram_aggregates_old_v1/query.sql, sql/telemetry_derived/clients_histogram_aggregates_v1/init.sql, sql/telemetry_derived/clients_histogram_aggregates_v1/query.sql
Note: dry-run failing until I migrate to include the new `sample_id` field
=> Add sample_id to the histogram_aggregates pipeline.

sql/telemetry_derived/ssl_ratios_v1/metadata.yaml
This adds `metadata.yaml` for the `ssl_ratios_v1` query. This will be the first table being part of the public dataset.
=> Add metadata.yaml to ssl_ratios query

script/dryrun, sql/telemetry_derived/clients_histogram_aggregates_old_v1/query.sql, sql/telemetry_derived/clients_histogram_aggregates_v1/query.sql
Build ID Filtering:
Essentially keeping only the top two build IDs each day for each channel based on client count. 
Sample ID Partitioning:
I preemptively added more of this here since those other queries were also processing 30T+. We also get the added bonus that some of the processing can run in parallel.
=> Glam: Build ID filtering and more sample_id partition usage

script/generate_views, udf/normalize_glean_baseline_client_info.sql
Glean pings now contain a client_info.locale field; baseline pings
previously reported locale as a string metric. This change provides
some historical continuity so that views on baseline pings show
client_info.locale values even if only the old metric is populated.
See the [announcement on the fx-data-dev mailing list](https://mail.mozilla.org/pipermail/fx-data-dev/2020-February/000321.html)
=> Coalesce the client_info.locale value in baseline ping views

sql/org_mozilla_firefox/clients_last_seen/view.sql
This was an omission that should have been included in #731.
This field is needed to stay in parallel with desktop clients_last_seen.
=> Add days_since_created_profile to Fenix clients_last_seen

sql/telemetry/telemetry_ip_privacy/view.sql, sql/telemetry/telemetry_ip_privacy_v2/view.sql
The ip privacy data is more of a stable table than derived but it likely needs to be modified in the future and I can't edit stable tables.
=> Add views for ip privacy data

script/publish_views
Fixes #779. The `glam_etl` dataset does not exist and breaks the `publish_views` flow. This adds the view to the ignore list.
=> Fix #779 - Ignore view deploys to glam_etl

udf/mode_last.sql, udf/mode_last_retain_nulls.sql
When aggregating columns, it may be surprising for some people
to have the most frequent non-null column be returned for
`udf_mode_last`. This introduces a new function which will
return null if that is the most frequent value.
=> Add mode_last_retain_nulls

script/run_query
[`subprocess.check_call`](https://docs.python.org/2/library/subprocess.html#subprocess.check_call) will wait for command to complete. If the return code was zero then return, otherwise raise `CalledProcessError`
https://github.com/mozilla/bigquery-etl/issues/806 https://github.com/mozilla/bigquery-etl/issues/807
=> Use subprocess.check_call when running queries

script/run_query
Destination tables names passed from telemetry-airflow can contain partitions, eg. `--destination_table=ssl_ratios_v1$20200310`. This resulted in `ssl_ratios` failing last night.
=> Allow partitions for destination_table names in run_query

sql/telemetry/active_profiles/view.sql, sql/telemetry/addon_aggregates_v2/view.sql, sql/telemetry/addons/view.sql, sql/telemetry/addons_v2/view.sql, sql/telemetry/socorro_crash_v2/view.sql, sql/telemetry/ssl_ratios_v1/view.sql
I have copied these tables over and have staged PRs such that Airflow will
start populating the shared-prod versions:
https://github.com/mozilla/telemetry-airflow/pull/893
https://github.com/mozilla/telemetry-airflow/pull/889
=> Remove final references to derived-datasets.telemetry_derived

sql/messaging_system/cfr_exact_mau28_by_dimensions/view.sql, sql/messaging_system/cfr_users_last_seen/view.sql, sql/messaging_system/onboarding_exact_mau28_by_dimensions/view.sql, sql/messaging_system/snippets_exact_mau28_by_dimensions/view.sql, sql/messaging_system_derived/cfr_exact_mau28_by_dimensions_v1/query.sql, sql/messaging_system_derived/cfr_users_last_seen_v1/query.sql, sql/messaging_system_derived/onboarding_exact_mau28_by_dimensions_v1/query.sql, sql/messaging_system_derived/snippets_exact_mau28_by_dimensions_v1/query.sql
r? @jklukas 
This is a follow up to precomputer the mau/dau/wau for those `user_last_seen` tables defined in Messaging System.
=> Add exact_mau28 tables/views for Messaging System

script/publish_metadata
I updated the `publish_metadata` to retrieve tables from BigQuery and update their metadata. This is similar to what is already done in `publish_public_data_views`.
I'm wondering if it would make sense to add this script to the docker container to be executed alongside [the other scripts](https://github.com/mozilla-services/cloudops-infra/blob/9f4bc5d4fe6c08677f75f7e4da0ca5e575f1653e/projects/data-shared/Jenkinsfile.bigquery.prod#L124)?
=> Update publish_metadata to write metadata to public tables

sql/monitoring/telemetry_missing_columns_v2/view.sql, sql/telemetry/fenix_events_v1/view.sql
These two cases look like mistakes where we should be referencing stable rather than live tables.
=> Use stable tables rather than live

sql/telemetry_derived/clients_histogram_aggregates_v1/init.sql, sql/telemetry_derived/clients_histogram_aggregates_v1/query.sql
The main point here is to be able to query the previous day's `clients_histogram_aggregates` in intermediate steps. But it's also nice to keep a history of what this table looked like in the past rather than replacing it entirely on every run.
=> Glam histogram aggregates table is partitioned by submission_date and clustered by client_id.

sql/telemetry_derived/clients_histogram_aggregates_v1/query.sql, sql/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql, sql/telemetry_derived/glam_user_counts_v1/query.sql
The filter was missing from two queries and also the date param did not need to be cast to date
=> Add submission_date filter where needed.

requirements.txt
Fixes #836 
The updates to `requirements.txt` in #766 were likely incorrect due to being generated from a python version lower than 3.8, which has different transitive dependencies.
=> Fix requirements.txt by generating from python 3.8

README.md
This hopefully makes it clearer to external users how to use `metadata.yaml` and how to make data publicly available.
=> Add information about metadata and publishing data to README

script/dryrun
fixes [dryrun failure on master](https://circleci.com/gh/mozilla/bigquery-etl/11323)
```
sql/org_mozilla_firefox_derived/migrated_clients_v1/init.sql ERROR
[{'code': 409, 'errors': [{'message': 'Already Exists: Table moz-fx-data-shared-prod:org_mozilla_firefox_derived.migrated_clients_v1', 'domain': 'global', 'reason': 'duplicate'}], 'response': {'headers': {'alt-svc': 'quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,h3-T050=":443"; ma=2592000', 'cache-control': 'private', 'content-encoding': 'gzip', 'content-type': 'application/json; charset=UTF-8', 'date': 'Wed, 25 Mar 2020 17:04:34 GMT', 'server': 'ESF', 'transfer-encoding': 'chunked', 'vary': 'Origin, X-Origin, …
```
=> Remove new init.sql from dry_run

bigquery_etl/shredder/delete.py
by changing the partition condition from `CAST(submission_timestamp AS DATE) IS NULL` to `submission_timestamp IS NULL`.
tested, fixes errors like `Cannot query over table 'moz-fx-data-shared-prod.telemetry_stable.update_v4' without a filter over column(s) 'submission_timestamp' that can be used for partition elimination`.
=> Fix null date partition condition in shredder

README.md, sql/telemetry_derived/deviations_v1/metadata.yaml, sql/telemetry_derived/ssl_ratios_v1/metadata.yaml
The `deviations_v1` and `ssl_ratios` queries should be marked as non-incremental. That way, all data will get exported to one file instead of 1 file per day. 
As a next future step, metadata about existing public datasets will be published to GCS. This metadata should also contain a link to the data review.
=> Add review links to public datasets and make deviations non-incremental

sql/telemetry_derived/events_live/view.sql
I used the name `build_id` to keep it consistent with `telemetry.events_v1` so it's easy to switch queries between the two views.
=> Add build_id column to telemetry_derived.events_live

sql/telemetry/buildhub2/view.sql
This used the wrong fully qualified name.
=> Update buildhub2 view

bigquery_etl/publish_json.py, tests/publish_public_data_json/test_publish_json.py, tests/publish_public_data_json/test_publish_public_data_json_script.py, tests/publish_public_data_json/test_sql/test/non_incremental_query_v1/query.sql
This fixes https://github.com/mozilla/bigquery-etl/issues/865
For exporting data as JSON to GCS, `extract_table` is currently used. When exporting a table, data gets exported into a lot of separate files. E.g. in the case of `ssl_ratios`, a new file is created for each date. This can result in a very large number of files.
First I suspected that this is only the case for partitioned tables, but I ran some tests and it is also the case for tables that are not partitioned
The fix here: when converting ndjson to json the output will be written to one file until the output file size limit of 1 GB is reached. If the limit is exceeded a new output file is created.
=> Fix: large number of files when exporting tables to JSON 

README.md, bigquery_etl/parse_metadata.py, bigquery_etl/publish_json.py, sql/telemetry_derived/deviations_v1/metadata.yaml, sql/telemetry_derived/ssl_ratios_v1/metadata.yaml, tests/publish_public_data_json/test_publish_public_data_json_script.py, tests/publish_public_data_json/test_sql/test/incremental_query_non_incremental_export_v1/metadata.yaml, tests/publish_public_data_json/test_sql/test/incremental_query_non_incremental_export_v1/query.sql, tests/publish_public_data_json/test_sql/test/incremental_query_v1/metadata.yaml
This addresses https://github.com/mozilla/bigquery-etl/issues/867
I think having a `incremental_export` option is the best way to go here.
=> Add incremental_export option

script/export_incline_dash
The logic for incline exports in getting too complex to handle via Airflow
operations (see https://github.com/mozilla/telemetry-airflow/pull/935).
Instead, we put the logic into this script and will invoke via docker.
=> Add script/export_incline_dash

sql/telemetry_derived/asn_aggregates_v1/query.sql
This should fix the issue that we count only whether clients report enable/disable DOH events, instead of the number of reported events.
=> Count DOH events for each user only once in ASN aggregates

udf/gzip_length_footer.sql
for efficiently extracting uncompressed length of payloads in payload_bytes_decoded
=> Add udf.gzip_length_footer

bigquery_etl/generate_views.py
Fixes https://github.com/mozilla/bigquery-etl/issues/896
`re.search` doesn't return an iterable, because of that an error is thrown in the list comprehension for determining the table version.
=> Fix generate_views version parsing

bigquery_etl/public_data/publish_json.py, script/publish_public_data_json, tests/public_data/test_publish_json.py
This makes `script/publish_json` into a shell script and moves the python logic to the already existing codebase for publishing JSON data.
=> Refactor publish_json script

bigquery_etl/broken_views.py, script/list_broken_views
Addresses #903
Note that this currently just reports on broken views, printing out a series of `bq rm` commands that could be run. We could in the future add a flag to actually run the deletions.
=> Add script for reporting on broken views

sql/telemetry/desktop_retention_1_week/view.sql
The error behavior is interesting in that the view looks like this when publishing is attempted:
-----Query Job SQL Follows-----
|    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
1:CREATE OR REPLACE VIEW
2:  `moz-fx-data-shared-prod`
3:AS
4:SELECT
5:  client_id,
6:  DATE_SUB(submission_date, INTERVAL 13 DAY) AS `date`,
7:  -- active week 1
8:  `moz-fx-data-shared-prod`.udf.active_n_weeks_ago(days_seen_bits, 0) AS retained,
9:FROM
10:  `moz-fx-data-shared-prod.telemetry.clients_last_seen`
11:WHERE
12:  -- active week 0
13:  `moz-fx-data-shared-prod`.udf.active_n_weeks_ago(days_seen_bits, 1)
|    .    |    .    |    .    |    .    |    .    |    .    |    .    |    .    |
resulting in `google.api_core.exceptions.BadRequest: 400 Table name …
=> Full qualify 1-week retention view

bigquery_etl/public_data/publish_gcs_metadata.py, bigquery_etl/public_data/publish_json.py, tests/data/all_datasets.json, tests/public_data/test_publish_gcs_metadata.py, tests/public_data/test_publish_json.py, tests/public_data/test_publish_public_data_json_script.py
This fixes https://github.com/mozilla/bigquery-etl/issues/886
This writes the timestamp of when the data of a dataset on GCS was last updated to GCS. In the `all_datasets.json` metadata file, for each dataset a `last_updated` entry got added which links to the corresponding `last_updated` file for this dataset.
=> Add last_updated to GCS datasets metadata

sql/telemetry/windows_10_aggregate/view.sql
Microsoft will be rolling out the May 2020 update (version 2004) soon. Update the query to break on the final build number for it, 19041.
=> Add the Windows 10 May 2020 Update to Windows 10 Aggregates

bigquery_etl/public_data/publish_json.py, sql/telemetry_derived/asn_aggregates_v1/metadata.yaml, sql/telemetry_derived/deviations_v1/metadata.yaml, sql/telemetry_derived/ssl_ratios_v1/metadata.yaml, tests/public_data/test_publish_json.py
This explicitly updates the Content-Type for `last_updated` files to `text/plain`. That way when the files are opened in the browser the timestamp will get displayed directly. Currently, the browser will download the file.
=> Set content type for last_updated files

.circleci/config.yml, tests/README.md
When running integration tests it currently fails with: 
```
script/entrypoint: line 25: exec: pytest: not found
```
=> CI build step for integration tests

tests/public_data/test_publish_public_data_json_script.py
I changed for `last_updated` to store the timestamp as JSON but didn't update the integration test after.
=> Fix last_updated integration test

sql/search/search_clients_last_seen_v1/view.sql
Ignored in dryrun due to being a search view, and failed on deploy like so:
google.api_core.exceptions.BadRequest: 400 GET Unrecognized name: days_clicked_ad_bytes; Did you mean days_clicked_ads_bytes? at [14:5]
Side note: https://bugzilla.mozilla.org/show_bug.cgi?id=1623180 will likely open up access to this dataset at some point.
=> Fix search view reference

sql/telemetry_derived/deviations_v1/query.sql
To ensure we are not accidentally publishing data, only approved `metric`s from `deviations` are published. If there are more metrics in the future, those can be added after there has been a data review.
cc @jmccrosky
=> Limit metrics published in deviations query

bigquery_etl/public_data/publish_json.py, tests/public_data/test_publish_public_data_json_script.py
Fixes setting the content encoding for GCS blobs. It's `content_encoding` and not `encoding`.
=> Fix gzip content-encoding

script/dryrun, sql/telemetry_derived/deviations_v1/query.sql
The anomaly detection pipeline scheduled via Airflow in https://github.com/mozilla/telemetry-airflow/pull/977 writes data to `telemetry_derived.deviations_v1`. In order for the data to get published we need to run this query. What is a bit unusual is that it will read the partition of the date to be processed and replace it at the same time.
=> Update deviations query for Airflow anomdtct pipeline usage

sql/telemetry_derived/sync_send_tab_events_v1/view.sql
Per discussion in [DS-642](https://jira.mozilla.com/browse/DS-642?focusedCommentId=62023&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-62023)
=> Use join to get 64-char fxa_uid hash

sql/firefox_accounts/fxa_amplitude_export/view.sql
This also filters out empty arrays when sending user properties.
=> Bug 1632635 - Make Amplitude properties top-level

sql/firefox_accounts/fxa_amplitude_export/view.sql, sql/firefox_accounts_derived/fxa_amplitude_export_v1/init.sql, sql/firefox_accounts_derived/fxa_amplitude_export_v1/query.sql
The FxA Amplitude project uses PDT-based days. The previous approach of using UTC-based days and casting to PDT-based is wrong, since the day offsets are actually different for the two timezones.
This approach assumes we run the airflow DAG at EOD-PDT, rather than EOD-UTC.
=> Bug 1632635 - Make FxA Amplitude export PDT-based

bigquery_etl/query_scheduling/dag_collection.py, bigquery_etl/query_scheduling/task.py, tests/query_scheduling/test_task.py
Adds support for determining task dependencies that are defined in bigquery-etl.
The next step will be determining dependencies that are defined in telemetry-airflow.
=> Lower-friction scheduled queries dependencies

script/dryrun, sql/firefox_accounts/sync_send_tab_export/view.sql, sql/firefox_accounts_derived/fxa_amplitude_user_ids_v1/init.sql, sql/firefox_accounts_derived/fxa_amplitude_user_ids_v1/metadata.yaml, sql/firefox_accounts_derived/fxa_amplitude_user_ids_v1/query.sql
And we refactor the sync send tab view to use this new table, pulling it under the `firefox_accounts` namespace.
=> Implement fxa_amplitude_user_ids table

udf_js/json_extract_missing_cols.sql
The missing columns dashboard doesn't show missing columns in arrays. I updated the missing_cols UDF to also extract those columns. Key paths with arrays would be represented like 
`first`.`array`.[...].`nested-array-element`.`nested` 
with [...] indicating that the element is an array.
=> Update json_extract_missing_cols to get missing columns from arrays

bigquery_etl/public_data/publish_gcs_metadata.py, tests/data/all_datasets.json, tests/public_data/test_publish_gcs_metadata.py
Fixes https://github.com/mozilla/bigquery-etl/issues/967
Currently the `all-datasets.json` has for each dataset two files entries:
```
"files_metadata": "https://public-data.telemetry.mozilla.org/api/v1/tables/telemetry_derived/ssl_ratios/v1/files/metadata.json",
"files_uri": "https://public-data.telemetry.mozilla.org/api/v1/tables/telemetry_derived/ssl_ratios/v1/files",
```
Opening `files_uri` currently results in an error which caused some confusion. Instead we should write the list of available files to a `files` file: 
```
"files": "https://public-data.telemetry.mozilla.org/api/v1/tables/telemetry_derived/ssl_ratios/v1/files",
```
Then we also don't have two entries and everything becomes hopefully less confusing.
If that change makes sense then I'll also update the docs in …
=> Write files metadata to /files

sql/telemetry/firefox_nondesktop_day_2_7_activation/view.sql, sql/telemetry_derived/firefox_nondesktop_day_2_7_activation_v1/query.sql
Fix-up to #979 
I forgot during review that the telemetry-airflow machinery is going to replace partitions based on `submission_date`, and I had created this table with partitions based on `cohort_date`, causing a mismatch.
We should have the underlying table retain `submission_date`, and then we can present the shifted `cohort_date` as part of the user-facing view.
cc @gkabbz
=> Bug fix: Make cohort_date a derived field

bigquery_etl/shredder/delete.py
the `deletion_request` tables generally do not contain duplicates, and deleting from `main_v4` for `2020-01-14` failed 6 times in a row due to "memory usage", which i'm hoping will be fixed by removing `DISTINCT` in this subquery expression.
=> Remove unnecessary distinct from shredder delete query

sql/telemetry_derived/glam_client_probe_counts_extract_v1/query.sql
This was mistaking producing an array of objects with a single key/value
pair instead of a single object with multiple key/value pairs.
=> Fix GLAM JSON generation.

bigquery_etl/glam/clients_daily_histogram_aggregates.py, bigquery_etl/glam/clients_daily_scalar_aggregates.py, bigquery_etl/glam/templates/clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/clients_daily_scalar_aggregates_v1.sql, bigquery_etl/glam/utils.py, sql/glam_etl/org_mozilla_fenix__clients_daily_histogram_aggregates_metrics_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_activation_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_baseline_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_bookmarks_sync_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_deletion_request_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_events_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_history_sync_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_installation_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_logins_sync_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_metrics_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_migration_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_startup_timeline_v1/query.sql, sql/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_sync_v1/query.sql
This fixes the ping type by relying on the ping type encoded in the path to the table instead of the field in the ping. See [bug 1639345](https://bugzilla.mozilla.org/show_bug.cgi?id=1639345) for more context.
=> Bug 1639345 - Fix ping type using static name from table id

script/glam/generate_and_run_desktop_sql, script/glam/run_glam_sql, sql/telemetry_derived/clients_daily_scalar_aggregates_v1.sql.py
(fixes #760)
Separate script for generating query to match fenix pattern.  So both generate and run can be run through airflow like `bash script/glam/generate_desktop_sql && script/glam/run_glam_sql`.
A follow-up to this could be to simplify tests by having some `local` argument in the generate scripts that generate the queries using constant set of probes so we don't need to update the schemas every time.  We can commit that to the repo since we don't need to keep the real queries here anymore.
=> Add script to generate desktop glam queries

sql/telemetry/clients_last_seen_v1/view.sql
These segments/user states got a DS review [when added to DTMO](https://github.com/mozilla/firefox-data-docs/pull/466).
Replaces #825.
=> Add regular_users_v3 and new_or_resurrected_v3.

script/glam/run_glam_sql
I noticed that backfilling data takes longer than I expected. This is because there is a lot of unnecessary work being done when running the jobs sequentially. I've parallelized the jobs where it makes sense, and added two options. BACKFILL_ONLY will run the queries that build up the clients aggregate state. EXPORT_ONLY will take the current clients aggregate state and generate the downstream probes tables. 
```bash
RESET=true DATASET=glam_etl_dev_perf script/glam/run_glam_sql 
16.35s user 9.30s system 8% cpu 5:02.60 total
RESET=true DATASET=glam_etl_dev_perf script/glam/run_glam_sql 
20.09s user 14.62s system 15% cpu 3:46.25 total
BACKFILL_ONLY=true RESET=true DATASET=glam_etl_dev_perf script/glam/run_glam_sql  
16.07s user 12.06s system 34% cpu 1:20.94 total
EXPORT_ONLY=true …
```
=> Parallelize run_glam_sql script for glean data

bigquery_etl/query_scheduling/dag.py, bigquery_etl/query_scheduling/task.py, dags/bqetl_kpi_dashboard.py, sql/telemetry/firefox_kpi_dashboard_v1/metadata.yaml, tests/query_scheduling/test_dag.py, tests/query_scheduling/test_task.py
Follow-up to: https://github.com/mozilla/bigquery-etl/pull/980#discussion_r432116695
Support for optionally defining a different name for scheduled tasks.
=> Lower-friction scheduled queries: Support custom task name definitions

.circleci/config.yml, requirements.txt
and enforce via CI
python dependencies are specific to the version of python installed
cc @jklukas this is why a dep is removed in https://github.com/mozilla/bigquery-etl/pull/893#discussion_r433275095
=> Generate requirements with python 3.8

sql/telemetry_derived/clients_first_seen_v1/query.sql
With the previous logic, we were always filling in second_seen_date where it was null. We should only do so if we see a ping for the given client on the current day.
cc @jmccrosky
=> Fix second_seen_date bug in clients_first_seen

bigquery_etl/query_scheduling/dag.py, bigquery_etl/query_scheduling/formatters.py, bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/templates/airflow_dag.j2, bigquery_etl/query_scheduling/utils.py, dags.yaml, dags/bqetl_deviations.py, dags/bqetl_kpi_dashboard.py, dags/bqetl_public_data_json.py, sql/telemetry_derived/deviations_v1/metadata.yaml, tests/query_scheduling/test_dag.py, tests/query_scheduling/test_task.py
Depends on https://github.com/mozilla/bigquery-etl/pull/1020
There are a few cases where queries are dependent on tasks scheduled in telemetry-airflow (for example, if data is loaded into tables by a job running on GKE). I think it might be useful to have an option in query `metadata.yaml` files to specify these external dependencies.
=> Lower-friction scheduled queries: Support manual definition of external dependencies

dags/bqetl_amo_stats.py, dags/bqetl_deviations.py, sql/telemetry_derived/deviations_v1/metadata.yaml
I moved the `anomdtct` pipeline to its own DAG in https://github.com/mozilla/telemetry-airflow/pull/1013
=> Update deviations DAG

script/dryrun, sql/default_browser_agent/default_browser/view.sql
Also see https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/557
cc @bytesized
=> Bug 1621703 - Hide deprecated client_id field in default_browser view

udf/fenix_build_to_datetime.sql
Makes it easier to plot on re:dash, especially using DATETIME_TRUNC to group builds within a specific day.
=> Add udf for converting Fenix build strings to DATETIME

bigquery_etl/query_scheduling/task.py, dags.yaml, dags/bqetl_kpi_dashboard.py, dags/bqetl_nondesktop.py, sql/telemetry/firefox_nondesktop_exact_mau28_raw_v1/metadata.yaml, sql/telemetry_derived/firefox_nondesktop_day_2_7_activation_v1/metadata.yaml, sql/telemetry_derived/firefox_nondesktop_exact_mau28_by_client_count_dimensions_v1/metadata.yaml, sql/telemetry_derived/smoot_usage_nondesktop_compressed_v2/metadata.yaml, sql/telemetry_derived/smoot_usage_nondesktop_v2/metadata.yaml, tests/query_scheduling/test_task.py
Depends on https://github.com/mozilla/bigquery-etl/pull/1040
Moves scheduled non-desktop queries to their own DAG.
=> Lower-friction scheduled queries: bqetl_nondesktop DAG

bigquery_etl/query_scheduling/templates/airflow_dag.j2, bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2, dags/bqetl_amo_stats.py, dags/bqetl_core.py, dags/bqetl_deviations.py, dags/bqetl_gud.py, dags/bqetl_mobile_search.py, dags/bqetl_nondesktop.py, dags/bqetl_public_data_json.py, dags/bqetl_vrbrowser.py, tests/data/dags/test_dag_duplicate_dependencies, tests/data/dags/test_dag_with_dependencies, tests/data/dags/test_public_data_json_dag
Right now we seem to be running into issues with Airflow as it seems we have more sensors than available slots resulting in a deadlock. We can use `mode='reschedule'` which will reschedule the task when it's blocked in free up slots.
See also: https://godatadriven.com/blog/highlights-from-the-new-apache-airflow-1-10-2-release/
=> ExternalTaskSensor use reschedule mode

dags.yaml, dags/bqetl_activity_stream.py, sql/activity_stream_bi/impression_stats_flat_v1/metadata.yaml
Scheduling `impression_stats_flat_v1` query so that it can moved out of `copy_deduplicate`.
Generates https://github.com/mozilla/telemetry-airflow/pull/1030
=> Create bqetl_activity_stream DAG

dags.yaml, dags/bqetl_search.py, sql/search_derived/search_aggregates_v8/metadata.yaml, sql/search_derived/search_clients_daily_v8/metadata.yaml, sql/search_derived/search_clients_last_seen_v1/metadata.yaml
Moving search queries into their own `bqetl_search` DAG.
Generates https://github.com/mozilla/telemetry-airflow/pull/1029
=> Add bqetl_search DAG

sql/search/search_aggregates/view.sql
Search aggregates is currently being unioned with the old v6 data for the armag.addon period.  The changes in #1062 broke the view silently because the columns were in different order.  The existing union is unreliable because columns must be in the same order.  To make that guarantee we we would have to explicitly select every column in both `SELECT`s.  Instead, we can just backfill the current table using the v6 table and not have to worry about it.
=> Remove search aggregate union with v6

sql/firefox_accounts/fxa_amplitude_email_clicks/view.sql
Airflow still rejected this query because the comment included the offending string 🤦
=> Eliminate literal '{%' in comment

sql/telemetry/clients_daily/view.sql, sql/telemetry/crash_aggregates/view.sql, sql/telemetry/crash_summary/view.sql, sql/telemetry/eng_workflow_build_parquet/view.sql, sql/telemetry/events/view.sql, sql/telemetry/experiments/view.sql, sql/telemetry/experiments_aggregates/view.sql, sql/telemetry/first_shutdown_summary/view.sql, sql/telemetry/lockwise_mobile_events_v1/view.sql, sql/telemetry/socorro_crash/view.sql, sql/telemetry/ssl_ratios/view.sql, sql/telemetry/telemetry_core_parquet/view.sql, sql/telemetry/telemetry_focus_event_parquet/view.sql, sql/telemetry/telemetry_mobile_event_parquet/view.sql, sql/telemetry/telemetry_new_profile_parquet/view.sql, sql/telemetry/telemetry_shield_study_parquet/view.sql
These references are all to views that existed in both projects or to static tables that have been copied into shared-prod.
Closes https://github.com/mozilla/bigquery-etl/pull/879 which was a previous attempt at this that got stale.
=> Remove all references to derived-datasets in views

sql/messaging_system/onboarding_events_amplitude/view.sql
The experiments in user properties were previously created as a
string in and of themselves; this led to a stringified array:
"[\"exp-1\", \"exp-2\"]"
when in fact what we want is:
["exp-1", "exp-2"]
This change fixes that.
=> Fix onboarding events user properties

udf/map_revenue_country.sql
Previously the behavior was to error on unknown search engines
in the revenue join. However this causes failures when we
add new normalized search engines but don't have revenue data
available for them.
Instead we will set the country to NULL, and let this data
fall out during the join with revenue data, which won't
have that country.
=> Set country to NULL for unknown search engines

dags/bqetl_internet_outages.py
Generated internet outages DAG for Airflow.
Generates https://github.com/mozilla/telemetry-airflow/pull/1062
=> Generate internet_outages DAG

sql/internet_outages/global_outages_v1/query.sql
BQ reports an error "Result of ORDER BY queries cannot be clustered".
=> Remove ORDER BY in global_outages query

script/publish_views
Reverts mozilla/bigquery-etl#1105
Relevant to https://github.com/mozilla/bigquery-etl/issues/1110 which discusses a regression that broke view publishing to stage.
=> Revert "Reference shared-prod views when republishing to other projects"

sql/firefox_accounts_derived/fxa_amplitude_export_v1/query.sql
* Add the new `fxa_activity - oauth_access_token_created` event to the
list of events used to generate the daily rollup of users and devices.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1649871 for more details.
=> Bug 1649871 - Add new event to FxA Amplitude export

sql/amo_prod/amo_stats_dau_v2/query.sql
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1643683
When we introduced Fenix data, we no longer are guaranteed to have values for
each of the per_* aggregations. In particular per_fenix_build will be empty
for any addon that's not compatible with Fenix. We need to use LEFT JOINS to
ensure we don't throw lose addons with no matching rows in per_fenix_build.
=> Use left joins for amo_stats_dau

sql/amo_dev/amo_stats_dau_v2/query.sql
This patch adds 6 new GUIDs to "copy" data from prod to dev for the AMO usage stats. These 6 add-ons are all Mozilla-owned add-ons and I asked their maintainers first, see [this gdoc](https://docs.google.com/document/d/1cNk_stSbpNG33XcPWIBKP8OHGyxIICFPeADmm8Vr-xY/edit?usp=sharing) for more info.
=> Add more data to `amo_dev.amo_stats_dau`

bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2, dags/bqetl_public_data_json.py, tests/data/dags/test_public_data_json_dag
This should fix the Airflow tasks failing with:
```
{logging_mixin.py:112} INFO - [2020-07-13 05:05:26,538] {pod_launcher.py:125} INFO - /app/script/entrypoint: line 38: /script/publish_public_data_json: No such file or directory
```
=> Fix public data DAG

sql/telemetry/eng_workflow_build_parquet/view.sql, sql/telemetry/telemetry_mobile_event_parquet/view.sql
:dmu reported a query using one of these views that was not working due to
a schema incompatibility. Looks like we made a mistake in pointing the view
directly at a table rather than a view that unions with more recent data.
=> Fix regressions in legacy parquet compatibility views

bigquery_etl/shredder/config.py, bigquery_etl/shredder/delete.py
This adds experiment analysis tables to shredder.
Tables for experiment analyses are stored as part of `moz-fx-data-experiments`. Currently, there is only one dataset, `mozanalysis`, with tables that are named like: `<some experiment identifier>_<day|week|overall>_<n>`. The dataset also contains some views that have names similar to the tables and tables with aggregated data that start with `statistics_` but do not contain any user identifiers.
Is there a good way to test this?
=> Add experiment analysis tables to shredder

sql/telemetry/health/view.sql
We'll go this route for now rather than trying to add the fields directly as
proposed in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/565
This structure in the view is generally compatible with the schema change that
would involve concrete fields in case we still want to go that direction in
the future.
=> Bug 1624908 Json extraction in health ping view

sql/firefox_accounts_derived/fxa_log_device_command_events_v1/query.sql
=> Include all device.command.* events in FxA log extract

sql/amo_dev/amo_stats_dau_v2/query.sql
Langpacks are Mozilla-owned add-ons and their GUIDs (`addon_id`) are normalized.
=> Add langpack data to `amo_dev.amo_stats_dau`

sql/telemetry_derived/main_summary_v4/part2.sql, udf/boolean_histogram_to_boolean.sql
This changes makes `part2.sql` fully compatible with new histogram encodings
and addresses a few more cases in `part1.sql`. There are a few remaining
cases to handle in `part1.sql` in a follow-up PR.
=> Bug 1646825 Partial support for compact histogram encodings in main_summary

bigquery_etl/query_scheduling/templates/airflow_dag.j2, bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2, dags/bqetl_activity_stream.py, dags/bqetl_addons.py, dags/bqetl_amo_stats.py, dags/bqetl_asn_aggregates.py, dags/bqetl_core.py, dags/bqetl_deviations.py, dags/bqetl_devtools.py, dags/bqetl_experiments_daily.py, dags/bqetl_gud.py, dags/bqetl_internet_outages.py, dags/bqetl_main_summary.py, dags/bqetl_messaging_system.py, dags/bqetl_mobile_search.py, dags/bqetl_nondesktop.py, dags/bqetl_public_data_json.py, dags/bqetl_search.py, dags/bqetl_ssl_ratios.py, dags/bqetl_vrbrowser.py, tests/data/dags/test_dag_duplicate_dependencies, tests/data/dags/test_dag_with_dependencies, tests/data/dags/test_public_data_json_dag
There is now a `DATA_ENG_EXTERNALTASKSENSOR` pool in Airflow which can be used for `ExternalTaskSensors`. Currently, it has 10 slots, we might need to increase this number? Or first start testing by assigning the pool to only a couple of task sensors before going all in?
=> ExternalTaskSensor pool

script/format_sql, udf/get_key.sql, udf/get_key_with_null.sql
This is a trivial follow-up PR after #1208. It removes the duplicated `map/get_key` and `map/get_key_with_null` by wrapper around mozfun functions.
=> Rewrite duplicated map udfs to mozfun shims

script/copy_deduplicate
We will also need to update monitoring queries to account for this when counting unique document_ids in decoded and live tables.
=> Bug 1657360 Exclude pings with "automation" tag from stable

script/glam/backfill_glean
This adds a script that will backfill a table for a glean product. It doesn't not check if the data has already been processed -- this means that it is possible to aggregate the same date twice. However, if the dates are being properly tracked in a log, then this should do the right amount of work to bring a table up to a current state.
=> Add script to backfill glam tables for a glean product

dags/bqetl_activity_stream.py, sql/activity_stream/impression_stats_by_experiment/view.sql, sql/activity_stream_bi/impression_stats_by_experiment_v1/init.sql, sql/activity_stream_bi/impression_stats_by_experiment_v1/metadata.yaml, sql/activity_stream_bi/impression_stats_by_experiment_v1/query.sql
This table will be a bit larger than impression_stats_flat, about 1 TB/day
uncompressed. But it will be much more efficient for the class of queries
that are concerned with evaluating performance of a single experiment.
=> Bug 1655146 Add impression_stats_by_experiment

sql/telemetry_derived/feature_usage_v1/query.sql
Add two features I need to work with.  Can we backfill with this?  It'll make my life much easier and save money as I don't keep pulling these features myself each time I run.
I realize I'm changing schema.  Would prefer to continue to call it v1 while developing, but if the schema change is a problem, let me know and I'll make this v2.
=> Add features

conftest.py
Running integration tests in parallel resulted in some of them failing since one test run deleted files that were still accessed by another test run. This should fix the problem.
=> Fix GCS integration test issues

script/publish_views
This should fix #1232 
The `VIEWS_TO_SKIP` set is the following:
```
('activity_stream/tile_id_types/view.sql', 'firefox_accounts/fxa_amplitude_email_clicks/view.sql', 'pocket/pocket_reach_mau/view.sql', 'telemetry/buildhub2/view.sql', 'glam_etl/org_mozilla_firefox__view_clients_daily_histogram_aggregates_v1/view.sql', 'glam_etl/org_mozilla_fenix_glam_release__view_user_counts_v1/view.sql', 'glam_etl/org_mozilla_fenix_glam_release__view_clients_daily_scalar_aggregates_v1/view.sql', 'glam_etl/org_mozilla_fenix_glam_release__view_probe_counts_v1/view.sql', 'glam_etl/org_mozilla_fenix_glam_release__view_clients_daily_histogram_aggregates_v1/view.sql', 'glam_etl/org_mozilla_firefox__view_clients_daily_scalar_aggregates_v1/view.sql', 'sql/shredder_state/progress/view.sql')
```
=> Fix #1232 - Ignore glam_etl directory when publishing views

bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_beta__view_clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_beta__view_clients_daily_scalar_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_nightly__view_clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_nightly__view_clients_daily_scalar_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_release__view_clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_release__view_clients_daily_scalar_aggregates_v1.sql, script/glam/test/test_glean_all_fenix, script/glam/test/test_glean_org_mozilla_firefox, sql/glam_etl/org_mozilla_fenix_glam_release__view_clients_daily_histogram_aggregates_v1/view.sql, sql/glam_etl/org_mozilla_fenix_glam_release__view_clients_daily_scalar_aggregates_v1/view.sql
Followup to #1221 
This adds a new script that runs all of the newly generated ETL. It also fixes the views so they run properly e.g. `UNION ALL` instead of `UNION`. Finally, the channel gets completely ignored for the dataset. At this point, it might actually be worth taking the union of all of the products into a single logical one.
=> Update Glam ETL for Fenix

bigquery_etl/glean_usage/templates/baseline_clients_daily_v1.sql
After merging, I will need to backfill these tables back to early April.
@harterrt formally requested this change in https://jira.mozilla.com/browse/DS-1018
=> Allow baseline pings with 'foreground' reason in KPIs

sql/telemetry_derived/firefox_nondesktop_day_2_7_activation_v1/query.sql
Fenix and Firefox Lite were previously filtered from the Day 2-7 Activation metric pending validation in https://jira.mozilla.com/browse/DS-696
=> Add Fenix, Fx Lite to Day 2-7 Activation

sql/monitoring/bigquery_etl_scheduled_queries_cost_v1/metadata.yaml, sql/monitoring/bigquery_etl_scheduled_queries_cost_v1/query.py
This adds a scripts which determines the total bytes processed for queries scheduled in bigquery-etl.
Users have previously asked about how much their newly added queries cost. While dry running the queries gives a rough idea, it is sometimes quite inaccurate (ignores sampling or some partitioning). I'm planning to add information about how much the previous run of a query cost to the new bigquery-etl CLI tool to make it easier for users to answer this question.
Additionally, this dataset might also be useful for monitoring cost (like we do with Redash scheduled queries) or for monitoring queries in general.
=> Add dataset for monitoring bigquery-etl query cost

mozfun/hist/extract/udf.sql
Airflow's publishing of mozfun definitions failed last night due to
https://github.com/mozilla/bigquery-etl/pull/1287
Long-term we should enforce that mozfun function definitions don't directly reference mozfun: see https://github.com/mozilla/bigquery-etl/issues/1293
=> Remove mozfun reference in mozfun UDF definition

bigquery_etl/dryrun.py, sql/revenue_derived/client_ltv_normalized/query.sql, sql/telemetry/client_ltv/view.sql
Adding a view for LTV that doesn't require permissions for the revenue tables. @fbertsch Please take a look when you get back. I'm not confident this is reading from the correct table.
=> Add ltv view without revenue fields

sql/firefox_accounts/fxa_amplitude_export/view.sql, sql/firefox_accounts_derived/fxa_amplitude_export_v1/query.sql
This event property can be used to determine which events activated the "active" event.
=> Bug 1649871 - Include rolled up event types

sql/org_mozilla_firefox_derived/event_types_v1/query.sql, tests/org_mozilla_firefox_derived/event_types_v1/test_new_day/expect.yaml, tests/org_mozilla_firefox_derived/event_types_v1/test_new_day/org_mozilla_firefox.events.yaml, tests/org_mozilla_firefox_derived/event_types_v1/test_new_day/org_mozilla_firefox_derived.event_types_v1.yaml, tests/org_mozilla_firefox_derived/event_types_v1/test_new_day/query_params.yaml
This query takes yesterday's events, yesterday's event_types,
and adds the new events, event_properties, and property values.
It writes it out to a new partition. This is not strictly
necessary but will aid debugging and redoes.
This depends on merging https://github.com/mozilla/bigquery-etl/pull/1289 and rebasing.
=> Query for updates to event_types_v1

sql/org_mozilla_firefox_derived/event_types_v1/init.sql, sql/org_mozilla_firefox_derived/event_types_v1/query.sql, tests/org_mozilla_firefox_derived/event_types_v1/test_init/expect.yaml, tests/org_mozilla_firefox_derived/event_types_v1/test_init/org_mozilla_firefox.events.yaml, tests/org_mozilla_firefox_derived/event_types_v1/test_new_day/expect.yaml, tests/org_mozilla_firefox_derived/event_types_v1/test_new_day/org_mozilla_firefox.events.yaml
Glean event timestamps are actually millisecond ints, starting at 0 for the first event. We account for that now.
=> Fix event timestamps

udf/fenix_build_to_datetime/metadata.yaml, udf/fenix_build_to_datetime/udf.sql
Fixes https://github.com/mozilla/bigquery-etl/issues/1248
~~Will consider this a draft until we here more from Fenix engineering in https://github.com/mozilla-mobile/fenix/issues/14031 about whether the hypothesis about epoch differences bears out.~~ This is now resolved and we have confirmation from the Fenix team that they're sticking with the modified epoch.
=> Tolerate new 10-digit Fenix app_build format

bigquery_etl/shredder/delete.py
This adds a new `environment` parameter to Shredder delete script, accepting either `telemetry` or `pioneer` values.
The goal of this parameter is to have a way for choosing different source and target tables. By default it is set to `telemetry` (which keeps current behavior unchanged).
Next step is to define logic for discovering Pioneer study tables in `config.py` and invoke it in delete script (`NotImplementedError`).
=> Bug 1661250 - prepare Shredder script for adding Pioneer support

bigquery_etl/udf/parse_udf.py, bigquery_etl/udf/publish_udfs.py, tests/data/udf/test_js_udf/metadata.yaml, tests/data/udf/test_js_udf/udf.sql, tests/udf/test_parse_udf.py, tests/udf/test_publish_udfs.py, tests/validation/hmac_sha256.py
Fixes https://github.com/mozilla/bigquery-etl/issues/1164
This turned out hairier than I would have hoped. Unlike tables, there is no API for adding descriptions to existing UDFs, so descriptions have to be added to the queries defining UDFs.
=> Publish descriptions for UDFs

sql/org_mozilla_firefox/event_types_v1/query.sql
Pretty annoying to have it in there when joining with events_daily.
=> Drop submission_date from event types view

sql/telemetry/windows_10_aggregate/view.sql
Microsoft will be rolling out the October 2020 update (version 20H2) soon. Update the query to break on the final build number for it, 19042.
=> Add the Windows 10 October 2020 Update to Windows 10 Aggregates

bigquery_etl/_version.py, bigquery_etl/cli/query.py, bigquery_etl/cli/udf.py, tests/cli/test_cli_query.py, tests/cli/test_cli_udf.py
This adds support for expressing query and UDF names with wildcards. Instead of specifying paths to queries or UDFs, the CLI now works with query and UDF names. This way, users do not necessarily need to know the underlying folder structure for using the CLI.
The CLI now supports things like:
`bqetl query info "*.clients*"` or `bqetl query info "telemetry_derived.*_v6"`
=> CLI support name patterns with wildcards

bigquery_etl/query_scheduling/task.py, dags/bqetl_account_ecosystem.py
Bug fix for #1288
Currently, the one script.sql task we have fails in Airflow due to having destination_table set in the query job, which is disallowed for scripts.
=> Disable destination_table for script.sql

bigquery_etl/_version.py, bigquery_etl/cli/udf.py, tests/cli/test_cli_udf.py
Fixes https://github.com/mozilla/bigquery-etl/issues/1341
This `bqetl udf rename` and `bqetl mozfun rename` command supports renaming UDFs and UDF datasets:
```
bqetl mozfun rename bits28 -n new_bits28
bqetl mozfun rename bits28.range -n bits28.better_range
bqetl mozfun rename bits28.range -n new_bits28.better_range
bqetl mozfun rename bits28.range -n new_bits28.range
```
=> CLI UDF rename command

sql/telemetry_derived/smoot_usage_desktop_compressed_v2/query.sql, sql/telemetry_derived/smoot_usage_fxa_compressed_v2/query.sql, sql/telemetry_derived/smoot_usage_new_profiles_compressed_v2/query.sql, sql/telemetry_derived/smoot_usage_nondesktop_compressed_v2/query.sql
See https://github.com/mozilla/gud/issues/112
Once this is merged, I will need to backfill the compressed tables from the noncompressed.
=> Add Japan to country list for GUD

udf/fenix_build_to_datetime/udf.sql
This fixes the `fenix_build_to_datetime` for 8 digit builds with invalid minutes (and hours). See #1356 for details.
=> Fix #1356 - Add extra validation before casting 8 digit build ids

bigquery_etl/_version.py, requirements.in, requirements.txt, setup.py
I removed the `incremental` dependency. It was required to be installed for `pip install mozilla-bigquery-etl` to work and was causing some confusion for people trying to install the CLI. Also added some missing dependencies that to `setup.py` that are used by the CLI.
=> Fix bqetl CLI setup

sql/account_ecosystem_derived/desktop_clients_daily_v1/query.sql, sql/account_ecosystem_derived/ecosystem_client_id_lookup_v1/query.sql, sql/account_ecosystem_derived/ecosystem_user_id_lookup_v1/script.sql, tests/account_ecosystem_derived/ecosystem_user_id_lookup_v1/test_script/telemetry_stable.account_ecosystem_v4.yaml
This fixes a bug about missing uids in the daily table as reported in
https://bugzilla.mozilla.org/show_bug.cgi?id=1637926#c5
It also adds some boolean fields to allow the daily table to specifically
address questions about whether a given client was 5-uri active per day.
=> Bug fixes for AET daily ETL

sql/search/search_clients_last_seen_v1/view.sql
The way `total_searches` is defined as sum over several other search-related metrics is not proper (but ok in determining whether user searched as used in this case). Misusage of total_searches value can be misleading, so we prefer to remove it from the view.
=> Remove `total_searches`

sql/telemetry_derived/fission_monitoring_crash_v1/query.sql, sql/telemetry_derived/fission_monitoring_main_v1/query.sql
This adds filtering by experiment slug and filters out sessions where fission hasn't yet been enabled.
=> Update ping selection criteria for fission monitoring tables

bigquery_etl/dryrun.py, dags.yaml, dags/bqetl_stripe.py, sql/moz-fx-data-shared-prod/stripe/subscription_transitions/view.sql, sql/moz-fx-data-shared-prod/stripe/subscription_volume/view.sql, sql/moz-fx-data-shared-prod/stripe_derived/plan_events/view.sql, sql/moz-fx-data-shared-prod/stripe_derived/plans_v1/init.sql, sql/moz-fx-data-shared-prod/stripe_derived/plans_v1/metadata.yaml, sql/moz-fx-data-shared-prod/stripe_derived/plans_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_derived/product_events/view.sql, sql/moz-fx-data-shared-prod/stripe_derived/products_v1/init.sql, sql/moz-fx-data-shared-prod/stripe_derived/products_v1/metadata.yaml, sql/moz-fx-data-shared-prod/stripe_derived/products_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_derived/subscription_events/view.sql, sql/moz-fx-data-shared-prod/stripe_derived/subscriptions_v1/init.sql, sql/moz-fx-data-shared-prod/stripe_derived/subscriptions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/stripe_derived/subscriptions_v1/query.sql
[Bug 1667889 - VPN subscription dashboard](https://bugzilla.mozilla.org/show_bug.cgi?id=1667889)
[Re:Dash Mozilla VPN Redux](https://sql.telemetry.mozilla.org/dashboard/mozilla-vpn-redux)
=> Bug 1667889 - Add stripe ETL to support Mozilla VPN dashboard

bigquery_etl/stripe/__init__.py
fixes an issue where stripe event imports were failing because there's a payment intent event with too many charges attached
=> Omit lists of stripe resources that have a separate table

bigquery_etl/docs/generate_docs.py
This will fix the generated docs path and drop the `sql/` part of the URL. The URL to the `event_analysis` dataset would then again be https://mozilla.github.io/bigquery-etl/mozfun/event_analysis/
=> Fix generated docs path

bigquery_etl/public_data/publish_gcs_metadata.py, tests/public_data/test_publish_gcs_metadata.py
Fixes https://github.com/mozilla/bigquery-etl/issues/1390
Something that might need a follow-up: if data from different projects is published and there are two datasets with the same name (same GCP dataset, destination table and version) then the dataset published last will overwrite previously published datasets.
=> Fix GCS metadata publishing for new project structure

sql/mozfun/event_analysis/extract_event_counts/README.md, sql/mozfun/event_analysis/extract_event_counts_with_properties/README.md, sql/mozfun/event_analysis/extract_event_counts_with_properties/metadata.yaml, sql/mozfun/event_analysis/extract_event_counts_with_properties/udf.sql, tests/assert/struct_equals/metadata.yaml, tests/assert/struct_equals/udf.sql
This is a follow-up to `extract_event_counts`. This is to support dashboards that need a breakdown of events w/ properties.
=> Create UDF for `extract_event_counts_with_properties`

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v1/query.sql
While looking at Shredder logs, I noticed that all entries for FxA-related
derived tables show 0 deletions, like:
> 712215424909 bytes and deleted 0 rows from moz-fx-data-shared-prod.firefox_accounts_derived.fxa_users_daily_v1
It appears that `account.deleted` events populate a field named `uid` rather
than `user_id`. I was able to verify this by choosing a recent `uid` value
from a deletion event and counting events where that same value appears as
`user_id` in FxA logs. There were matching messages.
=> Fix field name error causing Shredder to miss FxA account deletions

script/entrypoint
For an explanation of what quoting "$@" does (as opposed to quoting "$*"), see https://stackoverflow.com/a/12316565
this fixes an error in [the mozilla vpn waitlist job in airflow](https://workflow.telemetry.mozilla.org/log?task_id=mozilla_vpn_external__waitlist__v1&dag_id=bqetl_mozilla_vpn&execution_date=2020-10-11T00%3A00%3A00%2B00%3A00)
=> Add quotes to preserve spaces in query args

bigquery_etl/routine/publish_routines.py
mozfun is currently failing because [`glam.fenix_build_to_build_hour`](https://github.com/mozilla/bigquery-etl/blob/824ef5f6d57caa99d57d6a382bcb45ff68c77802/sql/mozfun/glam/fenix_build_to_build_hour/udf.sql#L3) calls another mozfun UDF, with project id specified
=> Fix mozfun references when publishing mozfun UDFs

sql/mozfun/norm/product_info/generate_body.sql, sql/mozfun/norm/product_info/metadata.yaml, sql/mozfun/norm/product_info/udf.sql
While testing https://github.com/mozilla/bigquery-etl/pull/1380
I was getting "query too complex" errors. It looks like that stems from the
many calls to `mozfun.norm.os` within the `product_info` function.
=> Reduce complexity of mozfun.norm.product_info

sql/moz-fx-data-shared-prod/udf/fenix_build_to_datetime/udf.sql
This was moved into into mozfun to support testing for `mozfun.glam` udfs.
=> Replace udf.fenix_build_to_datetime with mozfun reference

bigquery_etl/format_sql/format.py, sql/moz-fx-data-shared-prod/telemetry/fenix_clients_last_seen/view.sql, sql/moz-fx-data-shared-prod/telemetry/nondesktop_clients_last_seen/view.sql, sql/moz-fx-data-shared-prod/telemetry/nondesktop_clients_last_seen_v1/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_nondesktop_day_2_7_activation_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_nondesktop_exact_mau28_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_nondesktop_v2/query.sql, sql/mozfun/norm/fenix_app_info/metadata.yaml, sql/mozfun/norm/os/metadata.yaml
The `nondesktop_clients_last_seen_v1` view was developed mostly as an
internal implementation detail for downstream tables, but it has become
useful in its own right. This PR formalizes the view by providing an alias
without a version modifier and it adds a `product` field with application
names that are short but more meaningful than the `app_name` field.
See discussion in https://jira.mozilla.com/browse/DO-330 about confusion that
has resulted from the name "Fennec iOS" used in dashboards, etc. This is a
step toward reducing that kind of confusion.
This PR also adds `contributes_to_2019_kpi` and `contributes_to_2020_kpi` fields
as source of truth for how we count KPI metrics. That logic is currently
copied and pasted in several places, which could lead to errors.
This will need a fair …
=> Formalize product names in nondesktop_clients_last_seen

sql/moz-fx-data-shared-prod/org_mozilla_fenix/geckoview_version/view.sql, sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version/view.sql
Not having a `CREATE OR REPLACE VIEW` DDL statement at the top of the view breaks validation when runnning `scripts/publish_view`.
=> Add CREATE OR REPLACE VIEW clause to geckoview_versions and move it to org_mozilla_fenix

bigquery_etl/dryrun.py, sql/moz-fx-data-shared-prod/account_ecosystem_derived/fxa_logging_users_daily_v1/metadata.yaml
The dry run service can no longer perform queries with wildcard table specifications or access raw AET data. See mozilla-services/cloudops-infra#2599
=> Exempt a few files from dry run due to new table-level ACLs

bigquery_etl/cli/__init__.py, bigquery_etl/cli/dag.py, bigquery_etl/cli/dryrun.py, bigquery_etl/cli/query.py, bigquery_etl/cli/routine.py, bigquery_etl/cli/utils.py, bigquery_etl/cli/view.py, bigquery_etl/view/generate_views.py, bigquery_etl/view/publish_views.py, tests/cli/test_cli_view.py
This ports the `bigquery_etl.view.publish_view` module to use click instead of argparse and adds it to the main cli entrypoint. I've tested this using `script/publish_view --dryrun sql` and `bqetl view publish --dry-run sql`.  
The first commit sorts imports in the `cli/` and `view/` with isort. I didn't add `generate_view` because it utilizes the `bigquery_etl.standard_args` module.
=> Add `bqetl view publish`

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql, tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/test_aggregation/expect.yaml, tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/test_aggregation/main_summary_v4.schema.json
Per a data science request, adds an aggregation of `scalar_parent_telemetry_event_counts_sum` and `scalar_content_telemetry_event_counts_sum` to clients daily
=> Bug 1671517: Add event counts to clients daily

bigquery_etl/view/generate_views.py
We may want to replace this eventually with a more generalized solution for
Glean applications. See https://github.com/mozilla/bigquery-etl/issues/1466
=> Bug 1672191 Inject 'Firefox' as normalized_app_name for FOG

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py
The signature of load_table_from_json is
`load_table_from_json(json_rows, destination, num_retries=6, job_id=None, job_id_prefix=None, location=None, project=None, job_config=None, timeout=None)`
so we should pass job_config as a named parameter.
=> Truncate experiments table on load

bigquery_etl/glam/generate.py, bigquery_etl/glam/templates/clients_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/clients_scalar_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_nightly__view_clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/org_mozilla_fenix_glam_nightly__view_clients_daily_scalar_aggregates_v1.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__clients_histogram_aggregates_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__clients_scalar_aggregates_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__view_clients_daily_histogram_aggregates_v1/view.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__view_clients_daily_scalar_aggregates_v1/view.sql
Fixes #1402. Depends on #1458 due to the indiscriminate nature of the `replace_project_and_dataset` function in `run_glam_sql`. This means the reference to the geckoview_version view in shared-prod points to one in `glam-fenix-dev` which doesn't exist.
=> Fix #1402 - Use org_mozilla_fenix.geckoview_version view for app_version in GLAM

script/glam/README.md, script/glam/list_tables
I ran the following commands to prepare the `glam-fenix-dev:glam_etl` dataset to drop aggregates and unused tables.
```bash
script/glam/list_tables glam_etl | grep -v fenix_glam | grep -v clients_daily | xargs -I {} echo "bq rm -f {}"
bq rm -f glam-fenix-dev:glam_etl.org_mozilla_fennec_aurora__extract_user_counts_v1
bq rm -f glam-fenix-dev:glam_etl.org_mozilla_fennec_aurora__histogram_bucket_counts_v1
bq rm -f glam-fenix-dev:glam_etl.org_mozilla_fennec_aurora__histogram_percentiles_v1
bq rm -f glam-fenix-dev:glam_etl.org_mozilla_fennec_aurora__histogram_probe_counts_v1
bq rm -f glam-fenix-dev:glam_etl.org_mozilla_fennec_aurora__latest_versions_v1
bq rm -f glam-fenix-dev:glam_etl.org_mozilla_fennec_aurora__scalar_bucket_counts_v1
bq rm -f …
```
=> Add script to list tables in glam_etl datasets

script/glam/run_glam_sql
Fixes #1470. 
Tested by writing giberish into the clients daily SQL and running `./script/glam/test/test_glean_org_mozilla_fenix_glam_nightly`. 
```bash
...
Updated property [core/project].
running sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_baseline_v1/query.sql
running sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_bookmarks_sync_v1/query.sql
running sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_activation_v1/query.sql
running sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_deletion_request_v1/query.sql
running sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_events_v1/query.sql
running …
```
=> Fix #1470 - Wait on process ids from backgrounded tasks in run_glam_sql

sql/moz-fx-data-shared-prod/stripe_external/charges_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/credit_notes_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/customers_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/disputes_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/invoices_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/payment_intents_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/payouts_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/plans_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/prices_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/products_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/setup_intents_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/subscriptions_v1/query.sql
resources are deduped by id, but this was incorrectly using event id, causing all update events to be considered a new resource
=> Use resource id, not event id, when updating stripe resource tables

README.md, bigquery_etl/metadata/parse_metadata.py, bigquery_etl/metadata/validate_metadata.py, bigquery_etl/public_data/publish_gcs_metadata.py, sql/moz-fx-data-shared-prod/internet_outages/global_outages_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/deviations_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/italy_covid19_outage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/metadata.yaml, tests/data/all_datasets.json, tests/data/test_sql/moz-fx-data-test-project-2/test_2/test_query_v1/metadata.yaml, tests/data/test_sql/moz-fx-data-test-project/test/incremental_query_non_incremental_export_v1/metadata.yaml, tests/data/test_sql/moz-fx-data-test-project/test/incremental_query_v1/metadata.yaml, tests/data/test_sql/moz-fx-data-test-project/test/multipart_query_v1/metadata.yaml, tests/data/test_sql/moz-fx-data-test-project/test/non_incremental_query_v1/metadata.yaml, tests/metadata/test_parse_metadata.py, tests/metadata/test_validate_metadata.py, tests/public_data/test_publish_gcs_metadata.py, tests/test_run_query.py
Fixes #938.
**What I did**:
- Change `review_bugs` to list and add validator
- Update `review_bugs` in tests and metadata files to lists
- Update README
The failed build test seems to be a GCP-related issue. I tested my code locally and the only failed tests were GCP-related too. Any advice on how to fix this @scholtzan? Maybe something similar to [this](https://github.com/mozilla/bigquery-etl/pull/1481#issuecomment-716631697)? Thank you for your help.
=> Add multiple review bug support to metadata (fixes #938)

bigquery_etl/cli/routine.py
This updates `bigquery_etl.cli.routine` so the `publish` command does not fail. It uses the default project consistently across the commands, and defaults to the project-id option if provided.
=> Fix `bqetl mozfun publish`

bigquery_etl/dryrun.py, bigquery_etl/stripe/__init__.py, dags/bqetl_mozilla_vpn.py, dags/bqetl_stripe.py, sql/moz-fx-data-shared-prod/mozilla_vpn/add_device_events/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn/login_flows/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn/protected/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn/users/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/add_device_events_v1/init.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/add_device_events_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/add_device_events_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/login_flows_v1/init.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/login_flows_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/login_flows_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/protected_v1/init.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/protected_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/protected_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/users_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/users_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/init.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/query.sql, sql/moz-fx-data-shared-prod/stripe/customers/view.sql, sql/moz-fx-data-shared-prod/stripe_derived/customers_v1/metadata.yaml, sql/moz-fx-data-shared-prod/stripe_derived/customers_v1/query.sql
All of these tables feed into a redash query that combines them into a funnel: https://sql.telemetry.mozilla.org/queries/75572/source#188990
=> Add ETL for Mozilla VPN acquisition funnel

.circleci/config.yml
This fixes an issue introduced in https://github.com/mozilla/bigquery-etl/pull/1481 where a space was introduced into the tag, leading to the following issue:
```
#!/bin/bash -eo pipefail
docker build . --pull --tag "$IMAGE"
invalid argument "mozilla/ bigquery-etl:latest" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
```
https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/6662/workflows/27ab59d0-9eeb-433a-b94f-40746018e82e/jobs/33036
=>  Fix broken circleci deploy due to extra space in tag 

sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/query.sql
`COALESCE` doesn't work with table aliases, because BigQuery returns a struct with null contents for table aliases that were not matched in a `JOIN`, so instead use `IF(table_alias_2.join_key IS NULL, table_alias_1, table_alias_2)`
=> Fix join logic for mozilla_vpn_external.users_v1

bigquery_etl/run_multipart_query.py
Allow multiple schema update options, make `--destination_table` required, fix `TypeError: argument of type 'NoneType' is not iterable` when `--dataset_id` is missing, and use `get_temporary_table` from `bigquery_etl.util.temp_table`
=> Update options for script/run_multipart_query

sql/moz-fx-data-shared-prod/udf/bits_from_offsets/metadata.yaml, sql/moz-fx-data-shared-prod/udf/bits_from_offsets/udf.sql
This is relevant to the emerging "clients_all_time" work drafted in
https://github.com/mozilla/bigquery-etl/pull/1480
I'm proposing we add this under `udf` rather than in `mozfun` because I'm not
yet certain about the naming. If we want to have additional functionality to
support all-time bit patterns, I would like to have those organized under a
single `mozfun` namespace, and it's not clear yet what the interface should
look like.
This function on its own should be enough to empower a new DS workflow for
experimenting with new usage definitions before committing them to clients_daily
and clients_last_seen (evolving documentation in [the daily per-client aggregates project doc](https://docs.google.com/document/d/1Lml-hWiqhvUazjn_-sDF6TUvwAEA3jMG3LJbyIC7fEc/edit#heading=h.uqc5x9ri7ie8)).
=> Add bits_from_offsets UDF

dags.yaml, dags/bqetl_google_analytics_derived.py
I think the GA exports to bigquery are tied to a local timezone so they're affected by daylight savings.  It should have a larger buffer anyway so it's effectively two day delay.  Alternative is to use the `{{ yesterday_ds }}` airflow macro but that requires a bunch of changes to each task because of how the bigquery_etl_query operator works.
=> Change GA dag to run later

sql/mozfun/glam/histogram_fill_buckets/udf.sql, sql/mozfun/glam/histogram_fill_buckets_dirichlet/udf.sql
This attempts to fix #1521 by ordering the buckets during the `probe_counts` stage using the natural sort. This used the string sort before because of the boolean type, but ordering on the boolean type doesn't actually matter. This affects the generated percentiles because they will automatically use the ordering of the histogram in probe counts:
```sql
SELECT
* EXCEPT (aggregates) REPLACE('percentiles' AS agg_type),
ARRAY<STRUCT<key STRING, value FLOAT64>>[
('5', mozfun.glam.percentile(5, aggregates, metric_type)),
('25', mozfun.glam.percentile(25, aggregates, metric_type)),
('50', mozfun.glam.percentile(50, aggregates, metric_type)),
('75', mozfun.glam.percentile(75, aggregates, metric_type)),
('95', mozfun.glam.percentile(95, aggregates, metric_type))
] AS aggregates
FROM
glam_etl.{{ …
```
=> Use numeric order instead of string ordering when filling buckets

bigquery_etl/glam/templates/histogram_bucket_counts_v1.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__histogram_bucket_counts_v1/query.sql, sql/mozfun/glam/histogram_normalized_sum/udf.sql, sql/mozfun/glam/map_from_array_offsets/udf.sql
This should fix #1490. Running the following query results in a few rows where the number of bits exceeds 63.
glam-fenix-dev:US.bquxjob_335606eb_1759f9f0074
```sql
SELECT
x.key
FROM
`glam-fenix-dev.glam_etl.org_mozilla_fenix_glam_release__clients_histogram_aggregates_v1`,
unnest(histogram_aggregates) as agg,
unnest(agg.value) as x
order by
length(x.key) desc
limit 1000
```
```json
[
{
"key": "11961233684655493120"
},
{
"key": "16915738899553708032"
},
{
"key": "10058158527438782464"
},
{
"key": "10968499650544994304"
},
{
"key": "13043817825332967424"
},
...
```
Looking at the top result in python:
```python
>>> x = 11961233684655493120
>>> x.bit_length()
64
```
Casting happens a few places inside of the bucket counts for histogram aggregates. If we safe_cast instead, this should resolve …
=> Use SAFE_CAST with bucket values

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/users_v1/query.sql
it's needed by data science for analysis
cc @felixlawrence
=> Expose mozilla vpn users attribution column to wider audience

bigquery_etl/dryrun.py, dags.yaml, dags/bqetl_monitoring.py, sql/moz-fx-data-shared-prod/monitoring/telemetry_missing_columns_v3/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring/telemetry_missing_columns_v3/query.sql
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1676229)
This generates missing paths in the telemetry namespace using table globs. This doesn't work with the new table ACLs, so one way of getting around this is to schedule it via Airflow. I can't think of a great way to test this, I'm relying on the fact that this has already been around in `telemetry_missing_columns_v2`.
=> Bug 1676229 - Add materialized table for missing columns in telemetry dataset

sql/moz-fx-data-shared-prod/monitoring/telemetry_missing_columns_v3/init.sql, sql/moz-fx-data-shared-prod/monitoring/telemetry_missing_columns_v3/query.sql
This is a followup for #1551, which failed when running:
```bash
[2020-11-13 19:33:59,363] {pod_launcher.py:173} INFO - Event: monitoring--telemetry-missing-columns--v3-ebb05ca922b241629d1ead91cd0e4611 had an event of type Running
[2020-11-13 19:34:02,637] {pod_launcher.py:156} INFO - b"BigQuery error in query operation: Error processing job 'moz-fx-data-shared-\n"
[2020-11-13 19:34:02,638] {pod_launcher.py:156} INFO - b"prod:bqjob_r3a02ea7452eb5325_00000175c319af0d_1': Partitioning specification\n"
[2020-11-13 19:34:02,640] {pod_launcher.py:156} INFO - b'must be provided in order to create partitioned table\n'
[2020-11-13 19:34:02,846] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2020-11-13 19:34:02,847] {pod_launcher.py:156} INFO - b'  File …
```
=> Add init for telemetry_missing_columns_v3

dags/bqetl_monitoring.py, sql/moz-fx-data-shared-prod/monitoring/schema_error_counts_v2/init.sql, sql/moz-fx-data-shared-prod/monitoring/schema_error_counts_v2/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring/schema_error_counts_v2/query.sql
This adds a new materialized table for schema errors. 
I want to materialize this data to use for the normalized schema error counts, which costs ~500gb per run. https://sql.telemetry.mozilla.org/queries/69311/source
=> Materialize dataset for schema error counts

dags/bqetl_monitoring.py, sql/moz-fx-data-shared-prod/monitoring/structured_missing_columns_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring/structured_missing_columns_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring/structured_missing_columns_v1/query.py
This adds structured missing columns in the same fashion as `monitoring.telemetry_missing_columns_v3`.  I set this up in a sandbox project and ran it like so:
```bash
cd sql/moz-fx-data-shared-prod/monitoring/structured_missing_columns_v1
python query.py --project amiyaguchi-dev --date 2020-11-14 --skip-exceptions
```
The data scanned in mb, with exceptions for tables without permissions.
```json
{
"activity_stream": 53438.7,
"burnham": 0.0,
"coverage": 0.0,
"default_browser_agent": 746.3,
"edge_validator": 0.0,
"eng_workflow": 0.1,
"firefox_desktop": 2.9,
"firefox_installer": 12.6,
"firefox_launcher_process": 23.8,
"glean_js_tmp": 0.0,
"messaging_system": 13138.2,
"mobile": 1.2,
"mozdata": 0.0,
"mozilla_lockbox": 0.6,
"mozilla_mach": 0.0,
"mozphab": 0.0,
"mozza": 0.0, …
```
=> Add query for structured missing columns

sql/moz-fx-data-shared-prod/monitoring/schema_error_counts_v2/query.sql
Apparently, you cannot write into a clustered table if the query is ordered. 
```
[2020-11-17 19:56:06,125] {pod_launcher.py:173} INFO - Event: monitoring--schema-error-counts--v2-a1f3d02736144587a735dd99951f804e had an event of type Running
[2020-11-17 19:56:09,321] {pod_launcher.py:156} INFO - b'\rWaiting on bqjob_r184a361726ed5818_00000175d7c759d1_1 ... (0s) Current status: RUNNING\r                                                                                      \rWaiting on bqjob_r184a361726ed5818_00000175d7c759d1_1 ... (0s) Current status: DONE   \n'
[2020-11-17 19:56:09,322] {pod_launcher.py:156} INFO - b"Error in query string: Error processing job 'moz-fx-data-shared-\n"
[2020-11-17 19:56:09,322] {pod_launcher.py:156} INFO - b"prod:bqjob_r184a361726ed5818_00000175d7c759d1_1': …
```
=> Remove ordering clause in schema error counts

sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/query.sql
As uncovered in https://bugzilla.mozilla.org/show_bug.cgi?id=1677609#c9
this field only ever had a single bit set because it was using the wrong UDF
for combining days.
=> Bug fix for days_interacted_bits in clients_last_seen

sql/moz-fx-data-shared-prod/mozilla_vpn_external/waitlist_v1/init.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_external/waitlist_v1/query.sql
in a join, the table alias is never NULL, only the contents, so using `COALESCE` was causing all rows not updated to have all-null columns.
=> Fix mozilla vpn waitlist update logic

sql/moz-fx-data-shared-prod/messaging_system/onboarding_events_amplitude/view.sql
This fixes bug [1678344](https://bugzilla.mozilla.org/show_bug.cgi?id=1678344).
Note that we don't need to do the backfilling here since attribution is a new collection.
=> Bug 1678344 - Add attribution source and ua to onboarding_events_amplitude

sql/moz-fx-data-shared-prod/telemetry/clients_last_seen_v1/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/query.sql
Follow-up to https://github.com/mozilla/bigquery-etl/pull/1561 now that the backfill is complete.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1677609
=> Bug 1677609 Add first_seen and core active to clients_last_seen view

bigquery_etl/view/publish_views.py
(for #1583)
Validated this with the publish dry run.
One issue I see with this is that the behaviour of `--target-project` is unintuitive but I think this is acceptable because this isn't a frequently or widely used script.
=> Skip publishing non-shared-prod views if --target-project is set

bigquery_etl/dryrun.py, script/glam/run_scalar_agg_clustered_query.py, sql/moz-fx-data-shared-prod/telemetry_derived/clients_scalar_probe_counts_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/scalar_percentiles_v1/query.sql, tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_scalar_probe_counts_v1/test_aggregation/query_params.yaml
For #1432
This makes scalar_probe_counts and scalar_percentiles make multiple queries per app_version.  clients_scalar_aggregates_v1 is clustered by app_version so this is somewhat efficient.  app_versions are nicely distributed: proportions are about 0.39, 0.38, 0.19, 0.034, 0.0037.  Clustering for the larger proportions aren't very efficient and still need to scan most of the table though so this increases total query cost.
Airflow pr https://github.com/mozilla/telemetry-airflow/pull/1194
=> Separate queries on clients_scalar_aggregates by app_version

sql/moz-fx-data-shared-prod/telemetry/main_1pct/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/main_1pct_v1/query.sql
To be truly useful for quick investigations, the standard approach to views
doesn't work here.
The following query runs in 4 seconds:
```
SELECT
DATE(submission_timestamp) AS dt,
COUNT(*)
FROM
`moz-fx-data-shared-prod.telemetry_derived.main_1pct_v1`
WHERE
DATE(submission_timestamp) >= '2020-11-24'
AND subsample_id = 0
GROUP BY
1
ORDER BY
1 DESC
```
But the equivalent on top of the existing view takes more than 30 seconds,
bottlenecked on query planning.
=> Move field cleaning to table in main_1pct

script/glam/generate_glean_sql
The `bigquery_etl.glam.generate` call was missing the `--project` option with the production location.
=> Specify project when generating glam_etl sql

script/glam/generate_glean_sql
I reproduced a bug found in the last airflow dag run:
```bash
% PROJECT="test-test" PRODUCT=org_mozilla_fenix_glam_nightly GENERATE_ONLY=true STAGE=incremental script/glam/generate_glean_sql
...
File "/Users/amiyaguchi/Work/bigquery-etl/bigquery_etl/glam/generate.py", line 83, in main
raise NotADirectoryError(f"path to {dataset_path} not found")
NotADirectoryError: path to sql/test-test/glam_etl not found
```
See  https://workflow.telemetry.mozilla.org/log?task_id=incremental_org_mozilla_fenix_glam_beta&dag_id=glam_fenix&execution_date=2020-12-08T02%3A00%3A00%2B00%3A00
=> Ensure the sql directory for glam-fenix exists

dags.yaml, dags/bqetl_search_dashboard.py, sql/moz-fx-data-shared-prod/search/desktop_search_aggregates_by_userstate/view.sql, sql/moz-fx-data-shared-prod/search/desktop_search_aggregates_for_searchreport/view.sql, sql/moz-fx-data-shared-prod/search/mobile_search_aggregates_for_searchreport/view.sql, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/init.sql, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/query.sql, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/init.sql, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/query.sql, sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/init.sql, sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/query.sql
Create 3 tables for the search dashboard, these tables may not be optimized at this moment as we believe it might be short-lived considering that we are moving towards the new BI tool. 
mobile_search_aggregates_for_searchreport
desktop_search_aggregates_for_searchreport
desktop_search_aggregates_by_userstate
=> Bug 1673979 - Add Search dashboard queries

.gitignore, bigquery_etl/docs/generate_docs.py, docs/mkdocs.yml
Fixes #1242.
Per @jklukas's suggestion, I added 2 new links at the end of each function's docs: Source that takes the user to the function directory, and Edit to the metadata.yaml edit interface.
=> Add links to metadata.yaml editor and source dictory (#1242)

dags/bqetl_fenix_event_rollup.py, sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/event_types_v1/metadata.yaml
This query is failing as of 2020-11-18 due to unexpected input.
We are descheduling it until the logic is updated to handle this situation,
since new DAG runs are staying in the running state, waiting on past
runs that will never complete.
=> Deschedule fenix event_types query temporarily

dags.yaml, dags/bqetl_public_data_json.py, requirements.txt, sql/moz-fx-data-shared-prod/telemetry_derived/deviations_v1/metadata.yaml
This is not needed anymore. Currently, the `bqetl_public_data_json` DAG is paused in Airflow due to https://github.com/mozilla/bigquery-etl/issues/1638 but merging this should resolve this issue.
Depends on https://github.com/mozilla/telemetry-airflow/pull/1214
=> Remove deviations

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_amplitude_export_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_amplitude_user_ids_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_bounce_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_content_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_auth_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_device_command_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_oauth_events_v1/query.sql
ISO 8601 years are week-numbering years. Specifically, an ISO
year begins on the first Monday of Week 01; so if in the
Gregorian calendar the year starts on a Friday, the Friday,
Saturday, and Sunday will all fall in the previous year.
We run into this problem here. %g uses the ISO year, so for
2021-01-01 and 2021-01-02, that is year '20'. This has no match
in the underlying data (no 20-01-01 in FxA logs). Switching to
%y gives us year '21' for this data, and a match in the FxA logs.
https://en.wikipedia.org/wiki/ISO_8601#Week_dates
=> Bug 1684935 - Use non-ISO 8601 years for FxA Log retrieval

setup.py
This is untested, but I don't think there's any reason this shouldn't work. If there are problems, we can address
them in a followup.
=> Allow using bigquery-etl with python 3.9 (fixes #1611)

bigquery_etl/alchemer/response.schema.json, bigquery_etl/alchemer/survey.py, tests/alchemer/test_survey.py
This should fix #1647.
This adds a few columns that were originally missing from the schema (`options` and `subquestions`). When handling `subquestions`, the column is stringified into JSON because there are two different schemas for the field depending on the question type. This also adds tests that are based on api documentation examples: https://apihelp.alchemer.com/help/surveyresponse-returned-fields-v5#getobject
I tested this with the current set of surveys:
```
ids=(5572350 5205593 5829956 5187896 5111573)
for id in $ids; do
python3 -m bigquery_etl.alchemer.survey \
--date 2021-01-05 \
--survey_id $id  \
--api_token $ALCHEMER_API_TOKEN \
--api_secret $ALCHEMER_API_SECRET \
--destination_table amiyaguchi-dev.analysis.alchemer_vpn_test
done
```
Which works, but with the caveat that …
=> Update alchemer import for full set of columns

bigquery_etl/dryrun.py
Using `multiprocessing.Pool` instead of `multiprocessing.ThreadPool` does significantly improve the dry run speed. Locally, it takes `11:03.11` minutes with `multiprocessing.ThreadPool` and `1:29.26` minutes with `multiprocessing.Pool` for me. This also speeds up the DAG generation.
=> Speed up dry run

bigquery_etl/cli/dag.py, bigquery_etl/query_scheduling/dag.py, bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/utils.py
The comment (and help text) falsely implied you should prefix
them with an `@` symbol.
=> Fix suggestions for daily, weekly, ... scheduling options

bigquery_etl/cli/__init__.py, bigquery_etl/cli/alchemer.py, tests/cli/test_cli_alchemer.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1683765)
This builds on #1634 and completes the historical data import. The script was used for these commands:
```bash
bqetl alchemer backfill \
--start-date 2020-04-19 \
--end-date 2021-01-03 \
--survey_id 5572350  \
--api_token $ALCHEMER_API_TOKEN \
--api_secret $ALCHEMER_API_SECRET \
--destination_table moz-fx-data-shared-prod.mozilla_vpn_external.survey_recommend_v1
bqetl alchemer backfill \
--start-date 2019-12-09 \
--end-date 2021-01-03 \
--survey_id 5187896  \
--api_token $ALCHEMER_API_TOKEN \
--api_secret $ALCHEMER_API_SECRET \
--destination_table moz-fx-data-shared-prod.mozilla_vpn_external.survey_product_quality_v1
bqetl alchemer backfill \
--start-date 2019-12-06 \
--end-date 2021-01-03 \
--survey_id 5205593  \ …
```
=> Bug 1683765 - Backfill vpn surveys

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql, tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/test_aggregation/expect.yaml
this has been broken all along, but it probably wasn't noticeable because everything impacted is in environment, which is sent every time and changes infrequently
=> Fix null handling for structs in clients daily

dags/bqetl_experiments_hourly.py, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_hourly_v1/metadata.yaml
`ts_no_dash` timestamps have format `"%Y%m%dT%H%M%S"` (I missed the `T` before)
=> Fix ds_format for ts_nodash

dags/bqetl_experiments_hourly.py, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_hourly_v1/metadata.yaml
Currently failing on `No such file or directory: 'sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_hourly_v1$2021011320/query.sql'\n"`
=> Specify query file path for experiment enrollment aggregates hourly scheduling

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_events_v1/query.sql
This query failed on the 2021-01-18 run with:
> jsonPayload.fields.id has changed type from STRING to FLOAT
Attempts to run this query in the BQ console show errors because the wildcard
query picks up only the most recent schema, which is incompatible with
historical days. We replace the field with null for now and can investigate
with FxA folks what might have caused this schema change.
=> Remove jsonPayload.fields.id from fxa_auth query

dags/bqetl_experiments_hourly.py, script/experiments/export_experiment_monitoring_data.py, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_hourly_v1/metadata.yaml
I set up a local Airflow instance to test this. For a `2021-01-13T00:00:00Z` run timestamp the partition date part got rendered into `2021011223`
Before it was failing with ` ERROR - strptime() argument 1 must be str, not Pendulum`
=> execution_date to to_datetime_string in experiment_enrollment_aggregates_hourly scheduling

dags/bqetl_main_summary.py, sql/moz-fx-data-shared-prod/telemetry/main_nightly/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/main_nightly_v1/init.sql, sql/moz-fx-data-shared-prod/telemetry_derived/main_nightly_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/main_nightly_v1/query.sql
Should provide a significant performance improvement to queries like https://sql.telemetry.mozilla.org/queries/65380/source and sidestep redash issues with errors due to dry run timeouts.
=> Add main_nightly, similar to main_1pct

bigquery_etl/copy_deduplicate.py
Seeing this in my dry-run of copy-deduplicate on pioneer. It looks like the parameter is already a string by the time it's being logged in this statement.
```
File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/site-packages/bigquery_etl/copy_deduplicate.py", line 372, in <module>
main()
File "/usr/local/lib/python3.8/site-packages/bigquery_etl/copy_deduplicate.py", line 363, in main
results = pool.starmap(client_q.with_client, query_jobs, chunksize=1)
File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
return self._map_async(func, iterable, …
```
=> Fix copy_deduplicate logging

bigquery_etl/glean_usage/baseline_clients_daily.py, bigquery_etl/glean_usage/baseline_clients_last_seen.py, script/generate_all_views, script/generate_and_publish_views
The new `generate_all_views` script is intended to replace `generate_views`
as the entrypoint for Jenkins. Its usage is demonstrated in the
`generate_and_publish_views` script.
This supports the move to user queries in the `mozdata` project.
=> Add glean_usage ETL generation to generate_all_views

.circleci/config.yml, bigquery_etl/view/validate_views.py, script/validate_views
This adds a step to the CI to validate view definitions:
* Ensure that the view names match the directory structure. Addresses https://github.com/mozilla/bigquery-etl/pull/1681#discussion_r560419385
* Ensure that views and referenced tables are fully qualified. Addresses https://github.com/mozilla/bigquery-etl/issues/1413 which has been an issue in the past multiple times.
=> CI validate views

bigquery_etl/publish_static.py, sql/moz-fx-data-shared-prod/static/README.md
See https://bugzilla.mozilla.org/show_bug.cgi?id=1671933
It appears that the current behavior is broken for publishing to any project other than shared-prod.
=> Update publish_static script for mozdata

sql/moz-fx-data-shared-prod/telemetry/firefox_accounts_exact_mau28_by_dimensions/view.sql, sql/moz-fx-data-shared-prod/telemetry/firefox_desktop_exact_mau28/view.sql, sql/moz-fx-data-shared-prod/telemetry/firefox_desktop_exact_mau28_by_dimensions/view.sql, sql/moz-fx-data-shared-prod/telemetry/firefox_nondesktop_exact_mau28/view.sql, sql/moz-fx-data-shared-prod/telemetry/firefox_nondesktop_exact_mau28_by_dimensions/view.sql, sql/moz-fx-data-shared-prod/telemetry/firefox_nondesktop_exact_mau28_by_product/view.sql, sql/moz-fx-data-shared-prod/telemetry/lockwise_mobile_events/view.sql
These were found as part of investigating
https://bugzilla.mozilla.org/show_bug.cgi?id=1671933
They are defined in derived-datasets even though they weren't in bigquery-etl
and so there may be user queries that depend on them. These may have been
erroneously deleted in a previous refactor of this repo.
Restoring them here so that they'll be published to the new `mozdata` project.
=> Add missing non-versioned telemetry views

sql/moz-fx-data-shared-prod/telemetry_derived/main_1pct_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/main_1pct_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/main_nightly_v1/metadata.yaml
See https://github.com/mozilla/bigquery-etl/issues/1597
=> Remove "preview" warnings from main_1pct and main_nightly

bigquery_etl/dryrun.py, dags/bqetl_experiments_daily.py, sql/moz-fx-data-experiments/monitoring/query_cost_v1/metadata.yaml, sql/moz-fx-data-experiments/monitoring/query_cost_v1/query.sql
This is for adding some alerting based on the cost of queries executed by jetstream. I'll add alerts in Redash that will get triggered if the cost of a query exceeds a certain amount. Since Redash doesn't have access to `INFORMATION_SCHEMA.JOBS_BY_PROJECT` for `moz-fx-data-experiments`, we need this scheduled query which writes cost related data to a destination Redash has access to.
=> Query for monitoring experiment analysis costs

script/experiments/export_experiment_monitoring_data.py, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_live/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_base/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_hourly_v1/init.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_hourly_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_live_v1/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_recents_v1/init.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_recents_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/init.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/query.sql
The monitoring data export got stuck a few times with the following error:
```
[2021-01-28 05:49:09,586] {pod_launcher.py:156} INFO - b'Exception in thread Thread-3:\n'
[2021-01-28 05:49:09,586] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2021-01-28 05:49:09,586] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner\n'
[2021-01-28 05:49:09,586] {pod_launcher.py:156} INFO - b'    self.run()\n'
[2021-01-28 05:49:09,586] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/threading.py", line 870, in run\n'
[2021-01-28 05:49:09,587] {pod_launcher.py:156} INFO - b'    self._target(*self._args, **self._kwargs)\n'
[2021-01-28 05:49:09,587] {pod_launcher.py:156} INFO - b'  File …
```
=> Monitoring data export fixes

dags.yaml, dags/bqetl_mozilla_vpn.py
We get alert emails every day about the wait_for_firefox_accounts_derived
task, since this DAG starts at midnight and the upstream DAG doesn't start
until 1:30. This reschedules the VPN DAG to occur 15 minutes after the upstream
DAG to avoid these alerts.
@relud - I'm relying on you to determine whether there would be any ill effects of delaying these queries, or if the logic relies on the timestamp rather than just the date.
=> Delay VPN dag

bigquery_etl/glam/clients_daily_scalar_aggregates.py, bigquery_etl/glam/models.py, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_baseline_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_metrics_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_migration_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix__clients_daily_scalar_aggregates_startup_timeline_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__scalar_bucket_counts_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__scalar_probe_counts_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_nightly__clients_daily_scalar_aggregates_metrics_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fennec_aurora__clients_daily_scalar_aggregates_metrics_v1/query.sql
Fixes #1729 by adding timespans to the set of metrics. It turns out that it's not as simple as adding it to the set of unlabeled metrics due to the structure:
```sql
select metrics.timespan.startup_timeline_framework_start
from mozdata.org_mozilla_fenix.startup_timeline
where date(submission_timestamp) = "2021-01-30"
```
```json
[
{
"startup_timeline_framework_start": {
"time_unit": "nanosecond",
"value": "370000000"
}
},
{
"startup_timeline_framework_start": {
"time_unit": "nanosecond",
"value": "740000000"
}
},
...
]
```
=> Fix #1729 - Add timespan to metrics for GLAM ETL queries for Glean

sql/moz-fx-data-shared-prod/mozilla_vpn_external/devices_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_external/subscriptions_v1/query.sql
`COALESCE` can't be used because table refs in a join are never actually `NULL`
=> Fix vpn subscriptions and devices imports

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/subscriptions_v1/query.sql
turns out `ended_at` isn't useful right now, but between `is_active` and `updated_at` we can get close
=> Expose vpn subscription updated_at to redash

bigquery_etl/docs/derived_datasets/generate_derived_dataset_docs.py, bigquery_etl/docs/derived_datasets/templates/table.md
This PR fixes a bug: right now we're showing links to metadata and view files at the bottom of every entry, which is not right because some tables don't have metadata or view files. For example, this data set does not have any metadata files: https://mozilla.github.io/bigquery-etl/mozdata/default_browser_agent/
=> Show only available urls in source

sql/mozfun/norm/truncate_version/metadata.yaml, sql/mozfun/norm/truncate_version/udf.sql
This should work reliably for all the cases we care about and
allows doing things like sorting by versions reliably (since one
can't assume lexicographical ordering).
Using NUMERIC should protect us from weird floating point edge cases:
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#decimal_types
See also #1770
=> Make `truncate_version` return NUMERIC

bigquery_etl/dryrun.py
#1811 failed "Generate SQL content" in CircleCI because of the below error:
I believe this is due to `errors()` returning None when there's no result, which can't be iterated over when used here:
https://github.com/mozilla/bigquery-etl/blob/28f15e16e5168aa26540448e621265af04136644/bigquery_etl/view/generate_stable_views.py#L174
I changed the output to an empty list to fix this bug.
=> Fix 'NoneType' error when generating SQL content

.circleci/config.yml
because most of our CI steps are building a venv from scratch every time instead of using the cache
=> Restore venv from cache before build

.circleci/config.yml, bigquery_etl/view/generate_stable_views.py, script/generate_sql
generate-sql is currently the slowest CI job on this repo, usually taking 4-5min to run. This should speed that up by about 2-3 minutes.
~This is in draft because it needs data ops to set up permissions (or a cloud function) so that circleci can list stable tables in prod.~ edit: permissions no longer needed
=> Add option to generate stable views without dry run

sql/mozfun/norm/truncate_version/metadata.yaml
It looks like angle brackets get parsed as HTML tags and disappear in the rendered docs. Generally adding some backticks where it will help readability.
=> Doc fixes for truncate_version

sql/mozfun/norm/product_info/README.md, sql/mozfun/norm/product_info/generate_body.sql, sql/mozfun/norm/product_info/metadata.yaml, sql/mozfun/norm/product_info/udf.sql
See the new documentation in `product_info/metadata.yaml` for full context.
I want to use this when creating derived tables for serving 2021 KPI info for mobile products in https://github.com/mozilla/bigquery-etl/pull/1824
=> Add app_name to mozfun.norm.product_info output

bigquery_etl/docs/generate_docs.py, bigquery_etl/dryrun.py, docs/mozfun/.pages
After https://github.com/mozilla/bigquery-etl/pull/1811, docs now source files from `tmp/generated-sql` directory at build time. However, since the [SKIP](https://github.com/mozilla/bigquery-etl/blob/52ab0ea6bd903caca115eaf48390a0ef741d00c5/bigquery_etl/dryrun.py#L24) list only includes string literals such as `sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v1/view.sql`, we need to strip `tmp/generated-sql/` from file names so that they can be checked against the SKIP list successfully.
=> Strip temporary dir name from filepath for docs generation

.circleci/config.yml, bigquery_etl/docs/derived_datasets/generate_derived_dataset_docs.py, bigquery_etl/docs/generate_docs.py, bigquery_etl/dryrun.py, docs/mozfun/.pages
Resolves #1833 
This is a continuation of the work that was started in #1830: we now move the source content for docs from `tmp/generated-sql/sql/` to `sql/`. I also updated the source URL to point at the `generated-sql` branch.
=> Move `generated-sql/sql` content to `sql/` for docs deploy

bigquery_etl/dryrun.py, bigquery_etl/schema/__init__.py, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/schema.yaml
Removes `submission_date` field that was accidentally introduced in https://github.com/mozilla/bigquery-etl/pull/1879 causing the daily runs to fail.
=> Remove submission_date field from experiment_search_aggregates_v1

bigquery_etl/cli/query.py, dags.yaml, dags/bqetl_pocket.py, sql/moz-fx-data-shared-prod/pocket/rolling_monthly_active_user_counts/metadata.yaml, sql/moz-fx-data-shared-prod/pocket/rolling_monthly_active_user_counts/view.sql, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_history_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_history_v1/query.py, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_history_v1/schema.yaml, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_v1/query.sql, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_v1/schema.yaml
See https://bugzilla.mozilla.org/show_bug.cgi?id=1695336
Includes some bug fixes for `bqetl query schema`, as I was trying to follow https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows/#adding-a-new-scheduled-query in putting this together and ran into a few issues.
=> Bug 1695336 Pocket MAU import

sql/moz-fx-data-shared-prod/telemetry/experiment_search_aggregates_hourly/view.sql, sql/moz-fx-data-shared-prod/telemetry/experiment_search_aggregates_recents/view.sql
I removed the tables these views reference earlier today since we now use materialized views. 
Dry run is failing due to https://github.com/mozilla/bigquery-etl/issues/1874
=> Remove old experiment search aggregates views

bigquery_etl/cli/query.py
I ran into a situation where updating the schema during a backfill was useful to have around. This should add the functionality in a backwards compatible way.
=> Allow schema updates on backfill command

bigquery_etl/cli/query.py
I've been backfilling a table manually from my desktop and am passing through the `-n` option to the backfill command so its not as noisy. The results look something like this using `-n 0`:
```bash
Waiting on bqjob_r5cb295690726aab3_0000017842a32d80_1 ... (34s) Current status: DONE   
Run backfill for moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.legacy_mobile_core_v2$20201017 with @submission_date=2020-10-17
Waiting on bqjob_r17681e93c9b58343_0000017842a3bf38_1 ... (34s) Current status: DONE   
Run backfill for moz-fx-data-shared-prod.org_mozilla_ios_firefox_derived.legacy_mobile_core_v2$20201018 with @submission_date=2020-10-18
Waiting on bqjob_r62e1b06a2e57e4cf_0000017842a450bb_1 ... (23s) Current status: DONE   
Run backfill for …
```
=> Add option to limit max rows during backfill

bigquery_etl/shredder/delete.py
this is currently blocking shredder deletes from completing successfully in airflow
see also: #1908 which is the same thing for a different field
=> Handle job.num_dml_affected_rows is None in shredder delete summary

README.md
Addresses https://github.com/mozilla/bigquery-etl/issues/1898
The logic for pushing to this branch includes pulling down existing content and then replacing just the `sql` directory, so I expect that this PR will be sufficient to have this content continue to exist.
=> Add a README to the generated-sql branch

dags.yaml, dags/bqetl_activity_stream.py, dags/bqetl_addons.py, dags/bqetl_amo_stats.py, dags/bqetl_desktop_funnel.py, dags/bqetl_devtools.py, dags/bqetl_experiments_daily.py, dags/bqetl_fxa_events.py, dags/bqetl_google_analytics_derived.py, dags/bqetl_internal_tooling.py, dags/bqetl_internet_outages.py, dags/bqetl_main_summary.py, dags/bqetl_messaging_system.py, dags/bqetl_monitoring.py, dags/bqetl_mozilla_vpn.py, dags/bqetl_org_mozilla_fenix_derived.py, dags/bqetl_public_data_json.py, dags/bqetl_stripe.py, dags/bqetl_vrbrowser.py
This adjusts some DAG schedules in an attempt to minimize the number of
BQSensor rescheduling emails we receive under normal circumstances.
Of note, the `copy_deduplicate` DAG is often taking a little longer than an
hour to complete, meaning that DAGs starting at 02:00 are likely to hit
reschedules. We do not address that problem here in hopes that performance
improvements to copy_deduplicate can bring performance back under 1 hour.
We also make some documentation fixups, including consistently using `|`
rather than `>` or `>-` as our multi-line string indicator. This preserves
whitespace that is relevant for markdown processing.
This should partially alleviate concerns from https://github.com/mozilla/bigquery-etl/pull/1907
=> DAG scheduling and docs cleanup

bigquery_etl/dryrun.py
We're getting Permission Denied, causing CI on the default branch to show failure.
=> Skip dry run for looker forecast cache

bigquery_etl/dryrun.py
Reverts mozilla/bigquery-etl#1922
Should no longer be needed after access changes were made in https://github.com/mozilla-services/cloudops-infra/pull/2987
=> Revert "Skip dry run for looker forecast cache"

bqetl
It would previously try to run bqetl with no arguments, which led
to confusing output.
=> Exit gracefully after `bqetl bootstrap` succeeds

.circleci/config.yml
The `docs` step is currently failing with: `subprocess.CalledProcessError: Command '['which', 'javac']' returned non-zero exit status 1.`
=> Add mvn setup for circleci doc generation

bigquery_etl/glean_usage/baseline_clients_first_seen.py
Follow up for #1934. See https://workflow.telemetry.mozilla.org/log?task_id=baseline_clients_first_seen&dag_id=copy_deduplicate&execution_date=2021-04-05T01%3A00%3A00%2B00%3A00
<details>
<summary>click here for airflow error</summary>
```
[2021-04-06 02:06:35,615] {pod_launcher.py:156} INFO - b'INFO Table does not yet exist: moz-fx-data-shared-prod.org_mozilla_vrbrowser_derived.baseline_clients_first_seen_v1\n'
[2021-04-06 02:06:36,214] {pod_launcher.py:156} INFO - b'Traceback (most recent call last):\n'
[2021-04-06 02:06:36,214] {pod_launcher.py:156} INFO - b'  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main\n'
[2021-04-06 02:06:36,214] {pod_launcher.py:156} INFO - b'    return _run_code(code, main_globals, None,\n'
[2021-04-06 02:06:36,214] …
```
=> Fix clients first seen matching org_mozilla_firefoxreality

bigquery_etl/docs/derived_datasets/generate_derived_dataset_docs.py
This should fix the following error:
```
File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/root/project/bigquery_etl/docs/generate_docs.py", line 167, in <module>
main()
File "/root/project/bigquery_etl/docs/generate_docs.py", line 161, in main
generate_derived_dataset_docs.generate_derived_dataset_docs(
File "/root/project/bigquery_etl/docs/derived_datasets/generate_derived_dataset_docs.py", line 70, in generate_derived_dataset_docs
[project_id, dataset_id, table_id] = referenced_table.split(".")
ValueError: not enough values to unpack (expected 3, got 2)
```
This seems to happen for a couple …
=> Fix not enough values to unpack for referenced tables

sql/moz-fx-data-shared-prod/telemetry_derived/event_events_v1/query.sql
See https://bugzilla.mozilla.org/show_bug.cgi?id=1703362
The fix that reduces the quantity of events is scheduled to be included
in Firefox 88, released in late April. From 88 on, the rate of events
is expected to be reasonable, and the filter here will allow them again.
I will run a backfill for this table, starting from 2020-12-15.
=> Bug 1703362 Purge security.unexpectedload events

bigquery_etl/dryrun.py
The dry run for this materialized view has been timing out for a while now. Likely because it queries from `main_v4`. I think it is fine to skip the dryrun to reduce CI failures
=> Skip dryrun for telemetry_derived.experiment_search_events_live_v1

sql/moz-fx-data-shared-prod/telemetry_derived/events_live/metadata.yaml
Requires https://github.com/mozilla-services/cloudops-infra/pull/3008 
For https://bugzilla.mozilla.org/show_bug.cgi?id=1682343
=> Add ACL metadata for poucave access to live events view

bigquery_etl/dryrun.py
The new BigQuery release introduced some change which disallows using `TO_JSON_STRING` with `STRUCT` input in materialized view: "Materialized views may not use the TO_JSON_STRING function with a STRUCT input". Unfortunately, our current strategy depends on using `TO_JSON_STRING` with `STRUCT` inputs. Materialized view that have been deployed in the past are still working, for now.
To reduce CI failure noise, this will skip dry runs for materialized views
=> Ignore materialized view dry runs

sql/moz-fx-data-shared-prod/activity_stream_bi/impression_stats_by_experiment_v1/metadata.yaml, sql/moz-fx-data-shared-prod/activity_stream_bi/impression_stats_flat_v1/metadata.yaml
This uses the same workgroups identifier format as the [MPS draft PR](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/646). This metadata will give us the primitives we need to selectively grant table-level access to non-ingestion tables, which for example obviates the need for a separate `activity_stream_bi` dataset. This is intended to be illustrative as opposed to functional (this is a no-op to the dataset ACLs). It's meant to be used by the following terraform:
```terraform
locals {
project_id  = "moz-fx-data-shared-prod"
path_prefix = "bigquery-etl/sql/${local.project_id}"
metadata_all = {
for f in fileset(".", "${local.path_prefix}/*/*/metadata.yaml") :
f => yamldecode(file(f))
}
metadata = merge([for k, v in local.metadata_all :
{ for access in v.workgroup_access …
```
=> Add workgroups metadata for activity_stream_bi

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/devices_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/subscriptions_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_derived/subscriptions_v1/query.sql, sql/mozfun/iap/derive_apple_subscription_interval/metadata.yaml, sql/mozfun/iap/derive_apple_subscription_interval/udf.sql, sql/mozfun/iap/scrub_apple_receipt/udf.sql
also expose subscription id and device id for vpn tables, and product id for stripe subscriptions
`interval` maps to `Term` in [Data requirements for Finance](https://docs.google.com/document/d/1na1FlF8frDKF0_8kbc2hUwZXP9ljegYVAVVd1GPIut8/edit), uses naming consistent with Stripe, and correctly returns `"month"` for all the subs we have in prod.
the id fields are all for Looker, where it wants them to ensure it doesn't double count when one_to_many tables are joined in.
=> Expose an `interval` field on iap subscriptions

sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/metadata.yaml
For https://bugzilla.mozilla.org/show_bug.cgi?id=1704675#c2 since the taar dataflow job requires read access to telemetry.clients_last_seen which requires access to telemetry_derived.clients_last_seen_v1.
Permissions for the user-facing views have already been granted via PR https://github.com/mozilla-services/cloudops-infra/pull/3014 
r?
=> Add ACL metadata for taar access to clients_last_seen table

dags/bqetl_main_summary.py, sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/metadata.yaml
Airflow is failing due to
```
[2021-04-20 03:23:12,457] {pod_launcher.py:156} INFO - b"BigQuery error in query operation: Error processing job 'moz-fx-data-shared-\n"
[2021-04-20 03:23:12,458] {pod_launcher.py:156} INFO - b"prod:bqjob_r7a908a819004b2fe_00000178ed4da52e_1': Schema update options should\n"
[2021-04-20 03:23:12,458] {pod_launcher.py:156} INFO - b'only be specified with WRITE_APPEND disposition, or with WRITE_TRUNCATE\n'
[2021-04-20 03:23:12,458] {pod_launcher.py:156} INFO - b'disposition on a table partition.\n'
```
=> Remove allow_field_addition_on_date in clients_first_seen_v1 metadata

dags/bqetl_main_summary.py, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml
`allow_field_addition_on_date` in clients_daily changes the order of fields in the destination table schema based on how they appear in the query. This causes the schema of `clients_first_seen` and `clients_last_seen` to be different from `clients_daily` after adding new fields.
=> Remove allow_field_addition_on_date from clients_daily

bigquery_etl/cli/query.py
With `--time_partitioning_type=DAY` being set the `bqetl query backfill` fails with:
```
Incompatible table partitioning specification. Expects partitioning specification interval(type:day,field:date), but input partitioning specification is interval(type:day)
```
Simply removing it solved the problem
=> Remove time_partitioning_type from bqetl backfill

sql/moz-fx-data-shared-prod/internet_outages/global_outages_v1/query.sql
https://bugzilla.mozilla.org/show_bug.cgi?id=1706394
Directly querying from `telemetry_stable.main_v4` fixes the `Resources exceeded during query execution` error.
cc @Dexterp37
=> [Bug 1706394] Internet outages dataset query from telemetry_stable.main_v4

sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/experiment_events_live_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/experiment_search_events_live_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/experiment_events_live_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/experiment_search_events_live_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_live_v1/view.sql
Fixes https://github.com/mozilla/jetstream/issues/631
~It appears that there was a BigQuery change which prevents us from deploying new materialized views for monitoring. With the new change "Materialized views may not use the TO_JSON_STRING function with a STRUCT input", however our current strategy depends on using TO_JSON_STRING with STRUCT inputs. Materialized view that have been deployed in the past are still working, for now~
=> Monitoring views for iOS experiments

dags.yaml, dags/bqetl_fxa_events.py, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_events_v1/query.sql
This is hopefully a temporary workaround while we understand the incompatible schema change in the source table.
Very similar to the fix in https://github.com/mozilla/bigquery-etl/pull/1683
=> Bug 1707571 - Ignore isverified in fxa_auth_events

bigquery_etl/glean_usage/baseline_clients_daily.py, bigquery_etl/glean_usage/baseline_clients_first_seen.py, bigquery_etl/glean_usage/baseline_clients_last_seen.py
Originally, the only way views got published for `baseline_clients_*` tables
was as part of the query runs, but we have since implemented the `output-only`
option and integrated that into `script/generate-sql`, so these views will
get created and updated with normal view publishing runs.
Thus, we no longer need to publish the views along with the queries, which
removes a circular dependency problem we have right now between clients_daily
and clients_first_seen when we first create a new Glean app.
=> Bug 1707395 Don't publish views when running glean_usage

bigquery_etl/events_daily/query_templates/event_types_history_v1/query.sql, sql/moz-fx-data-shared-prod/messaging_system_derived/event_types_history_v1/query.sql, sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/event_types_history_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/event_types_history_v1/query.sql, tests/sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/event_types_history_v1/test_new_day/expect.yaml, tests/sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/event_types_history_v1/test_new_day/org_mozilla_firefox.events.yaml
Some event property values were not showing up in the
event_types_history_v1 table. This was because the join
was only on property and value, so when multiple events
shared properties, only one of those events would be
able to use it.
=> Bug 1707921 - Fix missing event property values

bigquery_etl/cli/query.py, sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_events_live_v1/init.sql
Using the workaround for `TO_JSON_STRING` of generating an array of indices works well for our `experiment_search_events_live_v1` materialized views. If I do the same for the `experiment_events_live_v1` materialized views I still run into the issue where `branch` is set to the `experiment` slug. So for now we have to keep using `TO_JSON_STRING` there.
For reference, this is basically the query I tried (shortened here) that returned the incorrect result:
```sql
CREATE MATERIALIZED VIEW
AS
SELECT
submission_timestamp AS `timestamp`,
event.category AS `type`,
CAST(event.extra[safe_offset(i)].value as STRING) AS branch,  -- still set to the experiment slug
CAST(event.extra[safe_offset(j)].value as STRING) AS experiment,
event.name AS event_method
FROM
fenix_all_events,
UNNEST(events) AS …
```
=> Rewrite experiment_search_events_live_v1 materialized views without TO_JSON_STRING

sql/moz-fx-data-shared-prod/amo_prod/desktop_addons_by_client_v1/query.sql, sql/moz-fx-data-shared-prod/amo_prod/fenix_addons_by_client_v1/query.sql
There was a change in the formatting logic in Fenix that introduced spaces.
See https://github.com/mozilla-mobile/fenix/pull/18529#discussion_r621903980
We also add TRIM logic to the desktop query for similar protection.
cc @willdurand
=> Bug 1708111 - Trim whitespace from addon_id in amo_prod queries

sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/experiment_events_live_v1/init.sql
We should be free of `TO_JSON_STRING` usages in materialized views with these changes
=> Remove TO_JSON_STRING usages from materialized views

bigquery_etl/cli/query.py, bigquery_etl/metadata/parse_metadata.py, bigquery_etl/metadata/validate_metadata.py, sql/moz-fx-data-shared-prod/activity_stream/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/activity_stream_bi/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/activity_stream_derived/dataset_metadata.yaml, tests/cli/test_cli_query.py
This adds the machinery to create `dataset_metadata.yaml` as part of
`bqetl query create` and to validate that these files are valid, but these
are not yet actually used for anything.
The next step will be to fill out `dataset_metadata.yaml` for all
existing derived and user-facing datasets.
=> Bug 1708264 - Add initial support for dataset_metadata.yaml

sql/moz-fx-data-shared-prod/contextual_services/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/contextual_services_derived/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/regrets_reporter/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/regrets_reporter_derived/dataset_metadata.yaml
This removes the default `projectReaders` access. We set this correctly on `subscription_platform` but not these two datasets.
=> Make restricted access datasets view_restricted

sql/mozfun/iap/parse_apple_receipt/metadata.yaml, sql/mozfun/iap/scrub_apple_receipt/udf.sql
`mozfun.iap.scrub_apple_receipt` takes the result of `mozfun.iap.parse_apple_receipt` as input: https://github.com/mozilla/bigquery-etl/blob/4c4e10bfe84462994e5f0da440d0deca09a23250/sql/mozfun/iap/parse_apple_receipt/udf.sql#L2-L78
=> Fix active dates logic for VPN IAP

sql/mozfun/iap/derive_apple_subscription_interval/udf.sql, sql/mozfun/iap/scrub_apple_receipt/udf.sql
`receipt.in_app` and `latest_receipt_info` are both needed to determine subscription periods. `provider_receipt_json` is retreived with [`"exclude-old-transactions": true,`](https://github.com/mozilla-services/guardian-website/blob/60f010b139f292496f00e8586e73daac2e23b906/server/lib/apple.ts#L124), so we use `original_purchase_date` to determine the full life of the subscription, and we assume that no subscriptions have been resurrected after they ended. That assumption is sometimes inaccurate, but it's close enough until we can pull this from a better source of truth (directly from apple, instead of indirectly via guardian)
=> Fix apple receipt logic for VPN IAP again

bigquery_etl/cli/query.py
For baseline it will try to use `derived-datasets` by default
=> Backfill explicit project

bigquery_etl/cli/query.py
Currently, the `--project_id` parameter is ignored when running a backfill. This should fix it
=> Pass project_id to run() when running backfill

bigquery_etl/search/templates/mobile_search_clients_daily.template.sql, sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/query.sql, tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_aggregation/expect.yaml, tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_namespace_union/expect.yaml
See point 3 in this comment https://bugzilla.mozilla.org/show_bug.cgi?id=1673976#c7
Core pings are still reporting search_counts so we're double counting sap and clients.  I'll backfill the last week to fix this
=> Temporarily remove glean ios from mobile search

sql/moz-fx-data-shared-prod/search/mobile_search_clients_engines_sources_daily/metadata.yaml, sql/moz-fx-data-shared-prod/search/mobile_search_clients_engines_sources_daily/view.sql, sql/moz-fx-data-shared-prod/search/mobile_search_clients_engines_sources_last_seen/metadata.yaml, sql/moz-fx-data-shared-prod/search/mobile_search_clients_engines_sources_last_seen/view.sql, sql/moz-fx-data-shared-prod/search/search_clients_engines_sources_daily/metadata.yaml, sql/moz-fx-data-shared-prod/search/search_clients_engines_sources_daily/view.sql, sql/moz-fx-data-shared-prod/search/search_clients_engines_sources_last_seen/metadata.yaml, sql/moz-fx-data-shared-prod/search/search_clients_engines_sources_last_seen/view.sql, sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_last_seen_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_clients_last_seen_v1/metadata.yaml
See https://jira.mozilla.com/projects/DO/issues/DO-500
`search_clients_daily` becomes `search_clients_engines_sources_daily`
which more accurately represents the data model. We also rename the mobile
equivalent and the related `last_seen` views.
The old views stick around for now. We will need to announce deprecation of the
old views and a timeline for turning them off.
The underlying tables are unchanged. This effort is only about changing the
user interface.
=> DO-500 Rename search_clients_daily

.circleci/config.yml
This also adds a scheduled build at midnight UTC to ensure that the generated
content is updated shortly before nightly ETL starts.
This should allow us to relieve some awkwardness like in various contexts
where we need to run `script/generate_sql` before invoking an endpoint in the
container. In particular, it will allow us to revert
https://github.com/mozilla/telemetry-airflow/pull/1312
and may allow us to remove [generation when publishing views in Jenkins](https://github.com/mozilla-services/cloudops-infra/blob/de1f9e61e2a2236904449d8c482aa238cd7bffa2/projects/data-shared/Jenkinsfile.bigquery.prod#L139).
=> Copy generated-sql content into docker container

sql/moz-fx-data-shared-prod/static/country_names_alternate.csv, sql/moz-fx-data-shared-prod/static/country_names_v1/data.csv
See #2068. Query for generating the list of names is take from https://sql.telemetry.mozilla.org/queries/80165/source
```sql
WITH storefront AS
(SELECT DISTINCT storefront,
CASE
WHEN storefront LIKE '%St.%' THEN REPLACE(storefront, 'St.', 'Saint')
WHEN storefront = 'China mainland' THEN 'China'
WHEN storefront = 'Russia' THEN 'Russian Federation'
WHEN storefront = 'Tanzania' THEN 'Tanzania, United Republic of'
WHEN storefront = 'North Macedonia' THEN 'Macedonia, the Former Yugoslav Republic of'
WHEN storefront = 'São Tomé and Príncipe' THEN 'Sao Tome and Principe'
WHEN storefront = 'Micronesia' THEN 'Micronesia, Federated States of'
WHEN storefront = 'Moldova' THEN 'Moldova, Republic of'
WHEN storefront = 'Venezuela' THEN 'Venezuela, Bolivarian Republic of'
WHEN storefront = 'Taiwan' THEN …
```
=> Fix #2068 - Add alternative country names from apple store

bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2, dags/bqetl_public_data_json.py, tests/data/dags/test_public_data_json_dag
Changing the `bqetl_public_data_json` DAG to use the new `'dedicated'` queue.
=> [Bug 1643735] Use dedicated queue for bqetl_public_data_json

bigquery_etl/query_scheduling/dag.py, bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/utils.py, tests/dags_config/test_dag_names.py, tests/query_scheduling/test_dag.py
This will allow creating DAGs in the private version of bigquery-etl repository.
Changes:
* support private_bqetl_ prefix in CLI
* add test to validate if all DAGs here (public repo) start with `bqetl_` (similar test will be added in private repo requiring `private_bqetl_` prefix)
=>  Bug 1709871 - Support private DAGs in the CLI

.circleci/config.yml
This removes failing scheduled nightly build, as discussed in https://github.com/mozilla/bigquery-etl/issues/2072#issuecomment-848803921.
Closes #2072
=>  Bug 1709871 - Remove nightly scheduled build

sql/moz-fx-data-shared-prod/mozilla_vpn_external/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/stripe_external/dataset_metadata.yaml
The safety check failed after merging https://github.com/mozilla-services/cloudops-infra/pull/3156 since I moved access to be dataset-level.
=> Add data-platform write access at the dataset level in some cases

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml, sql/moz-fx-data-shared-prod/udf/aggregate_search_counts/udf.sql, tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/test_aggregation/expect.yaml, tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/test_aggregation/telemetry_stable.main_v4.yaml
https://jira.mozilla.com/browse/DS-1600
Adds three search sources and updates clients daily schema using [these instructions](https://mozilla.github.io/bigquery-etl/cookbooks/common_workflows/#add-a-new-field-to-clients_daily).  Some weirdness in the steps because the schema is based on undeployed udf changes so I used a temp udf when updating the schema.
Before merge:
- update deployed udf
- validate query
- deploy schema
- validate again
=> Add missing search sources to clients daily

sql/moz-fx-data-shared-prod/org_mozilla_ios_fennec_derived/experiment_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_fennec_derived/experiment_events_live_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_ios_fennec_derived/experiment_search_events_live_v1/init.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_fennec_derived/experiment_search_events_live_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_live_v1/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_live_v1/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/query.sql
Missed to add ios support to the aggregates queries. This data needs to be backfilled to 2021-06-07
=> Add ios support to experiment aggregates queries

bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/templates/airflow_dag.j2, bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2, dags/bqetl_public_data_json.py, tests/data/dags/test_public_data_json_dag
Based on proposal https://docs.google.com/document/d/1V8FwVH_oZonh-SLKRbghkzglofRlec7S51QwIIsLZbQ/edit#
I think it makes sense to set an `sla` for tasks but also ensure they time out after a while, otherwise we might end up with a lot of tasks retrying taking up all the slots if not detected during triage.
=> Airflow task SLA and execution_timeout

bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/templates/airflow_dag.j2, bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2, dags/bqetl_public_data_json.py, tests/data/dags/test_public_data_json_dag
Reverts mozilla/bigquery-etl#2134
I did some testing. Turns out this doesn't really what we would expect for `ExternalTaskSensor`s. `execution_timeout` and `sla` seem to only look at the actual runtime of a task. Each time a task gets re-scheduled this runtime is reset to 0 and the time between retries doesn't count into the `sla` and `execution_timeout` time either.
I'll try some other things. Using `dagrun_timeout` probably would work. Or implementing that custom `ExternalTaskSensor` operator that detects upstream failures.
=> Revert "Airflow task SLA and execution_timeout"

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/schema.yaml, sql/mozfun/iap/scrub_apple_receipt/udf.sql
and include a timezone field, because the definition of a month is timezone sensitive
=> Expose full start and end timestamp for IAP subscriptions

dags/bqetl_mozilla_vpn.py, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/retention_by_subscription_v1/query.sql, sql/mozfun/norm/subscription_months_renewed/udf.sql
previous definition of retention required an invoice to be paid in each month to count as renewed. This definition was insufficient because invoices aren't available for IAP subs, "month" is a timezone sensitive concept and IAP subs use `America/Los_Angeles`, and for non-monthly subscriptions (e.g. 6 month and 1 year subs) we don't have an invoice for each month.
New definition is based on localized start/end datetime and grace period in days, and is defined in a UDF for ease of testing.
=> Fix vpn retention table to correctly handle periods other than 1 month

.circleci/config.yml, .github/workflows/push-to-upstream.yml
This wraps the [git-push-fork-to-upstream-branch](https://github.com/jklukas/git-push-fork-to-upstream-branch) script into a Github Action. The CircleCI config has been updated to have a failing tasks for forks that will show instructions of how to trigger the Github Actions so that integration tests will get executed for forks.
I successfully tested this approach in this repository: https://github.com/scholtzan/gh-actions-test
The main advantage here is that we don't have to share secrets with forks, however it might be a little unintuitive.
Another option that came to mind that we could try:
* All environment variables (our secrets) get moved into a restricted context
* The setup is essentially the same as described here: https://github.com/mozilla/glean.js/pull/422#issuecomment-86341179 …
=> Github Action for pushing forks to upstream

.circleci/config.yml, .github/workflows/push-to-upstream.yml
Fixes the following error
```
webfactory/ssh-agent@v0.5.1 is not allowed to be used in mozilla/bigquery-etl. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub or match the following: !/mozilla/**, !mozilla/**, ./**, aws-actions/*, docker/*, pypa/gh-action-pypi-publish@release/v1.4.2.
```
=> Fix GH action for pushing to upstream

bigquery_etl/dryrun.py, sql/moz-fx-data-shared-prod/search_derived/search_clients_last_seen_v1/init.sql, sql/moz-fx-data-shared-prod/telemetry_derived/addons_daily_v1/query.sql
The addons_daily_v1 query failed last night with an error about `ad_clicks`
being an ambiguous field name. See
[Airflow logs](https://workflow.telemetry.mozilla.org/log?execution_date=2021-06-23T04%3A00%3A00%2B00%3A00&task_id=telemetry_derived__addons_daily__v1&dag_id=bqetl_addons).
This is due to https://github.com/mozilla/bigquery-etl/pull/2151 which added
a field called ad_clicks to clients_daily and downstream tables. That new field
is present in a join.
This PR disambiguates the reference by specifying which table to pull it from.
=> Disambiguate ad_clicks in addons_daily query

.circleci/config.yml
This fixes CircleCI workflow that is failing[1] because both `generate-sql` and `private-generate-sql` jobs are persisting `sql` directory into the workspace. In order to keep these jobs concurrent, `private-...` branch of the workflow will use `/tmp/generated-sql/private-sql/`.
[1] https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/10084/workflows/a835c08d-7d06-44cc-82a1-31f05795f701/jobs/64214/parallel-runs/0/steps/0-103
=> Fix private SQL generation

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v1/query.sql
[DS-1650](https://mozilla-hub.atlassian.net/browse/DS-1650)
This won't require any backfill, because the first impacted etl date is today.
=> DS-1650 - Update vpn available geos

requirements.in, requirements.txt
fixes docker builds
dependabot isn't posting an update for this because `No update possible`:
```
updater | INFO <job_170750073> Checking if google-api-core 1.30.0 needs updating
proxy | 2021/07/12 18:07:57 [236] GET https://pypi.org:443/simple/google-api-core/
proxy | 2021/07/12 18:07:57 [236] 200 https://pypi.org:443/simple/google-api-core/
updater | INFO <job_170750073> Latest version is 1.31.0
proxy | 2021/07/12 18:08:04 [238] GET https://pypi.org:443/simple/pip/
proxy | 2021/07/12 18:08:04 [238] 200 https://pypi.org:443/simple/pip/
proxy | 2021/07/12 18:08:06 [240] GET https://pypi.org:443/simple/google-api-core/
proxy | 2021/07/12 18:08:06 [240] 304 https://pypi.org:443/simple/google-api-core/
proxy | 2021/07/12 18:08:07 [242] GET …
```
=> Update google-api-core to 1.31.0

bigquery_etl/glam/templates/clients_scalar_aggregates_v1.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__clients_scalar_aggregates_v1/query.sql, sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_nightly__clients_daily_histogram_aggregates_metrics_v1/query.sql
#2173 only fixed things half way. I'm not sure if this will fix things all the way, since the job fails in the next stage during the bucket counts.
See the [bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1719188) for some details on the failure. 
=> Bug 1719188 - Add filter for large scalars in aggregates

bigquery_etl/stripe/allowed_fields.py, tests/stripe/test_allowed_fields.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1720752)
This is causing import errors as of 2021-07-14. The `custom_field` in the invoices schema is being treated like the `metadata` object, but is actually shaped differently. 
:relud is out sick, but it would be nice to resolve the airflow failures earlier since it seems to be propagating weird to the vpn dashboard.
=> Bug 1720752 - Fix stripe import for custom_field array

dags.yaml, dags/bqetl_app_store_connect.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1720767)
This DAG has been failing since run 2021-07-13. I've manually run this later in the day, and it seems to work. The time may have to be adjusted.
From the bug:
> On run 2021-07-13, the report was ready between 2021-07-14 17:03:10,121 and 2021-07-14 23:56:17,966. On run 2021-07-14, the report was ready between 2021-07-15 14:02:24,875 and 2021-07-15 21:06:53,772.
> 
> According to the error message, "Japan, Australia, and New Zealand by 5 am Japan Standard Time; and 5 am Central European Time for all other territories." 5AM JST is 20:00 UTC and 5AM CEST is 03:00 UTC. The time on the report looks most consistent with 5AM JST.
If the job fails one more time (tomorrow morning), I think we should go ahead and adjust import time. …
=> Bug 1720767 - Adjust apple app store connect to 20:00 UTC

bigquery_etl/stripe/__init__.py
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1720938)
The schemas are already populated, so this would be the easiest way to ignore new fields and have the job running over the weekend. This needs to be followed up to determine whether to add the new fields.
=> Bug 1720938 - Allow ignore on unknown values during stripe import

sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/query.sql
Missed this.  Value in clients_daily is a `NUMERIC` but search table schema uses float
=> Cast subsession hours as float in search query

bigquery_etl/stripe/__init__.py
Reverts mozilla/bigquery-etl#2197
This doesn't seem to have helped in imports. Starting 2021-07-17, jobs started to succeed again.
=> Revert "Bug 1720938 - Allow ignore on unknown values during stripe import"

bigquery_etl/stripe/allowed_fields.yaml, sql/moz-fx-data-shared-prod/stripe_external/invoices_v1/init.sql, sql/moz-fx-data-shared-prod/stripe_external/invoices_v1/query.sql
because that is where FxA is putting billing address values from the paypal billing agreement.
also use more-correct invoice aggregation (fixes issue where "paypalTransactionId" is missing from BigQuery invoice metadata but present in Stripe)
I will need to backfill customer_address for invoices, and after that I will file a separate PR to update all_subscriptions_v1 to use it for determining subscription country for paypal customers.
=> Allow customer_address fields on invoices

bigquery_etl/stripe/event.schema.json, bigquery_etl/stripe/subscription.schema.json
new field is not being added to `allow_fields.yaml`, so final schemas won't change.
=> Update stripe subscription schema

script/generate_sql, script/glam/generate_glean_sql
This should fix #2212, which is an issue that occurs when the SQL_DIR is set to something that is not sql/
=> Fix #2212 - Write glam sql to directory specified by SQL_DIR

script/generate_sql
Removing generating sql for the glam queries because of operational issues, most recently #2214. The job requires use of MSG, which caches results in a folder in the current working directory. I'm not going to be around tomorrow to debug issues, so punting this until next week by removing the relevant code.
=> Remove generated-sql for glam

bigquery_etl/feature_usage/templates/metadata.yaml, dags/bqetl_main_summary.py, sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/query.sql
The daily Airflow runs of `telemetry_derived.feature_usage_v2` was removing all previous partitions and only updating the latest one. This PR should fix this.
=> Fix feature usage table scheduling

dags.yaml, dags/bqetl_feature_usage.py, dags/bqetl_main_summary.py, sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/metadata.yaml
Fixes https://github.com/mozilla/bigquery-etl/issues/2230
The `feature_usage_v2` task is scheduled as part to the `bqetl_main_summary` DAG. The task depends on some tasks in the `bqetl_addons` DAG. `bqetl_addons` has some tasks that depend on `bqetl_main_summary`. To resolve this circular dependency I've moved the feature usage query into a separate DAG
=> Move feature_usage_v2 to separate DAG

bigquery_etl/cli/view.py, bigquery_etl/view/__init__.py, tests/view/test_view.py
We've been running into the following error
```
Error publishing /tmp/sql/moz-fx-data-shared-prod/telemetry/clients_probe_processes/view.sql. Invalid view definition.
```
The view should be skipped by wasn't because the current logic assumed it would be stored in `sql/moz-fx-data-shared-prod/` rather than `/tmp/sql/moz-fx-data-shared-prod/`
=> Fix skipping publishing and validation of views

bigquery_etl/view/__init__.py
This should fix https://github.com/mozilla/bigquery-etl/issues/2246
=> Avoid checking view references when publishing views

bigquery_etl/operational_monitoring/__init__.py, bigquery_etl/operational_monitoring/templates/init.sql, bigquery_etl/operational_monitoring/templates/query.sql, bigquery_etl/operational_monitoring/templates/view.sql, sql/moz-fx-data-shared-prod/udf_js/jackknife_percentile_ci/udf.sql
This commit was mainly to add normalization to the histograms in a view so that each client is only counted once for a set of dimensions (their histogram values add up to 1)
However, a few other things came up and there are some other changes I made:
* The normalized histograms have float values that need to be passed into the jackknife percentile function - I needed to update this function to accept floats (couldn’t find a way to make it generic sadly)
* I changed the design of the data processing a bit - I think it didn’t quite make sense before. Now each day the last 60 days of data is aggregated (instead of 30) and there are only 5 (instead of 7) partitions (days) stored. These are mainly for backup but the view will only look at data computed most recently.
* The `init.sql` file was …
=> Add normalization to operational monitoring views.

netlify.toml, requirements.in, requirements.txt, setup.py
Now that we're using Netlify's 20.04 image (which has Python 3.8), we can remove this backwards compatibility code.
=> python38 required again

script/glam/run_glam_sql, sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_aggregates_v1/init.sql, sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_aggregates_v1/query.sql
This will fix the bug [#901](https://github.com/mozilla/bigquery-etl/issues/901)
and also some minor issues found with run_glam_sql 
1.[Missing parameter, num_partitions, that needs to be passed to run_partitioned_query] (https://github.com/mozilla/bigquery-etl/blob/9d8a7d30e6dc7c883523c8d37f274c04b361df51/script/glam/run_glam_sql#L166-L171)
2. Ideally we want the dataset to be created in destination project.[The PROJECT should be DST_PROJECT](https://github.com/mozilla/bigquery-etl/blob/305bcb27d2f54554653d44b2c5798192e3bb1912/script/glam/run_glam_sql#L321-L322)
**Running run_glam_sql for sanity check :**
1. Created a test project and dataset: 
Project - alekhya-test-1-322715
Dataset - moz_test_data
2. Created and populated the client_daily_histogram_aggregates_v1 table with minimum …
=> remove latest_version column for histogram aggregates

bigquery_etl/cli/query.py
Fixes https://github.com/mozilla/bigquery-etl/issues/2278
=> Prevent schema update downstream from dry running views

bigquery_etl/view/generate_stable_views.py
As of https://github.com/mozilla/bigquery-etl/pull/2118 we see error messages
from any `bqetl` command that calls `generate_stable_views` like:
```
Cannot get Bigquery schema for mozilla-pipeline-schemas-9e81d822064c5a8336d3f2e61cc67cdf58d4a010/schemas/glean/glean/glean.1.schema.json: "filename 'mozilla-pipeline-schemas-9e81d822064c5a8336d3f2e61cc67cdf58d4a010/schemas/glean/glean/glean.1.bq' not found"
Cannot get Bigquery schema for mozilla-pipeline-schemas-9e81d822064c5a8336d3f2e61cc67cdf58d4a010/schemas/metadata/credentials/credentials.1.schema.json: "filename 'mozilla-pipeline-schemas-9e81d822064c5a8336d3f2e61cc67cdf58d4a010/schemas/metadata/credentials/credentials.1.bq' not found"
...
```
These correspond to schema "fragments" that have no concrete BQ tables.
We need to check for the …
=> Avoid error messages in generate_stable_views

script/glam/run_glam_sql, sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_extract_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_v1/query.sql
The PR is to resolve the issue [#1240](https://github.com/mozilla/glam/issues/1240). 
As part of the change, I have added two sql queries 
1. To pull the counts from `clients_histogram_aggregates` table [query1](https://gist.github.com/alekhyamoz/031fd954469acd6020d844202c5f8ce4)
2. To dedup in case of duplicates [query 2](https://gist.github.com/alekhyamoz/c8a668430e37b32083818fb70fd1c2aa)
Testing process:
Used run_glam_sql to test the process 
1. Get sample data from `moz-fx-data-shared-prod.telemetry_derived.clients_histogram_aggregates` to `alekhya-test-1-322715.moz_test_data.clients_histogram_aggregates` [query](https://gist.github.com/alekhyamoz/e5e452185cdfe04096f03f37ff8260ff)
2. PROJECT=moz-fx-data-shared-prod DST_PROJECT=alekhya-test-1-322715 PROD_DATASET=telemetry_derived …
=> added queries for sample counts

bigquery_etl/dryrun.py, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/fxa_attribution_v1/init.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/fxa_attribution_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/fxa_attribution_v1/schema.yaml
This a separate issue that came up while investigating [FXA-3965](https://mozilla-hub.atlassian.net/browse/FXA-3965)
=> Include fxa stdout events in mozilla vpn attribution

sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/query.sql, tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/expect.yaml, tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/query_params.yaml, tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/telemetry.clients_daily.schema.json, tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/telemetry.clients_daily.yaml
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1729084
PR:
- Adds `filter_probe_counts_with_outlier_values` UDF and uses it to remove  metrics/probes in the relevant urlbar keyed scalar metrics if they pass a threshold value. 
This is similar to the approach in [`mobile_search_clients_daily_v1`](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/query.sql#L632-L633) and we use the same threshold here (10,000).
- Removed double call of `one_index` so position counts are 1-based instead of 2-based 
- Adds tests
~- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.ym …
=> Fix for Bugzilla: 1729084 - Add UDF to remove outliers

dags/bqetl_mozilla_vpn_site_metrics.py, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v1/query.sql
This change causes the query to scan ~125MB, and is needed because subscription attribution may be added after the subscription start date
=> Always update all dates in GA funnel

bigquery_etl/operational_monitoring/__init__.py, bigquery_etl/operational_monitoring/templates/histogram_query.sql, bigquery_etl/operational_monitoring/templates/scalar_query.sql
This PR adds the ability to specify in an opmon project config file that a certain boolean pref will be used instead of regular experiment branches for doing the comparative analysis.
TODO:
=> Support analysis for rollouts in opmon (by treating a boolean pref as a branch)

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml
See https://bugzilla.mozilla.org/show_bug.cgi?id=1729970
Also refactors `mozfun.map.get_key` calls to a single `UNNEST` query with multiple aggregations.
I'll add these fields to `urlbar_clients_daily` in a separate PR.
=> Bug 1729970 Add firefox suggest prefs to clients_daily

dags/bqetl_subplat.py, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/users_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/users_v1/schema.yaml
Learned in [DVPN-61](https://mozilla-hub.atlassian.net/browse/DVPN-61) that subscriptions no longer require a guardian user, so we can't depend on the guardian users table to attribute subscriptions.
=> DVPN-61 - Detect VPN attribution without guardian user

bigquery_etl/dryrun.py
Dry run is currently failing for https://github.com/mozilla/bigquery-etl/pull/2336 due to change of access.
=> Exempt monitoring.payload_bytes_error_structured from dryrun

bigquery_etl/operational_monitoring/templates/histogram_view.sql, bigquery_etl/operational_monitoring/templates/scalar_init.sql, bigquery_etl/operational_monitoring/templates/scalar_query.sql, bigquery_etl/operational_monitoring/templates/scalar_view.sql, sql/moz-fx-data-shared-prod/udf_js/jackknife_percentile_ci/udf.sql
For some background/context:
The motivation of this PR is that the `jackknife_percentile_ci()` function can get really slow when it's applied to very long lists of numbers since it produces more subsamples with larger amounts of data and computes percentiles for each subsample.
A list of scalars with a wide variety of numbers was taking a long time (3min+) to compute these percentiles. By bucketing the scalars, a histogram with fewer numbers takes less time to compute percentiles on.
I used the same [scalar bucketing strategy used in glam](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/telemetry_derived/clients_scalar_probe_counts_v1/query.sql#L69-L86) which allows for buckets that are more appropriate per metric. However, the buckets are more precise so …
=> Update jackknife_percentile_ci() for use with scalar float buckets

dags/bqetl_error_aggregates.py, sql/moz-fx-data-shared-prod/telemetry_derived/error_aggregates_v1/metadata.yaml
I did not previously notice that this dag runs every three hours, so it can't depend on stable tables at all.
This fixes a regression introduced in #2330
=> remove error aggregates dependency

sql/moz-fx-data-shared-prod/mozilla_vpn_external/vat_rates_v1/query.py
update from #2357 to fix `Access Denied: Project moz-fx-data-shared-prod: User does not have bigquery.jobs.create permission in project moz-fx-data-shared-prod`
=> Run vat_rates_v1 query in default project

sql/moz-fx-data-shared-prod/monitoring_derived/structured_distinct_docids_v1/query.py
See https://bugzilla.mozilla.org/show_bug.cgi?id=1732293
Fixes regression from https://github.com/mozilla/bigquery-etl/pull/2367
=> Bug 1732293 Fix incorrect field ref in distinct_doc_ids query

dags/bqetl_devtools.py, dags/bqetl_experiments_daily.py, dags/bqetl_search.py, dags/bqetl_urlbar.py, sql/moz-fx-data-shared-prod/telemetry/clients_daily_v6/view.sql
All the data has been backfilled (https://bugzilla.mozilla.org/show_bug.cgi?id=1732155) so there shouldn't be anything blocking us from using `telemetry_derived.clients_daily_joined_v1` as basis for `telemetry.clients_daily`.
=> Use clients_daily_joined_v1 for telemetry.clients_daily

sql/moz-fx-data-shared-prod/search_terms_derived/adm_weekly_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/search_terms_derived/aggregated_search_terms_daily_v1/query.sql
Fixes recent [Airflow error](https://workflow.telemetry.mozilla.org/log?task_id=search_terms_derived__aggregated_search_terms_daily__v1&dag_id=bqetl_search_terms_daily&execution_date=2021-09-26T03%3A00%3A00%2B00%3A00)
=> Add date clause to search terms aggregates

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
Bug fix for incorrect implementation in https://github.com/mozilla/bigquery-etl/pull/2281
Uncovered in https://mozilla-hub.atlassian.net/browse/DO-576
=> DO-576 Fix update_background in clients_daily_v6

tests/README.md
(via @ANich) It feels slightly wrong to have to set this value twice (once via environment variable and once via gcloud).
=> Add gcloud config set step for running tests

sql/mozfun/glam/map_from_array_offsets_precise/metadata.yaml, sql/mozfun/glam/map_from_array_offsets_precise/udf.sql
This is 1st step to resolve the [issue](https://github.com/mozilla/glam/issues/1576)
The udf will allow us to get values for 99 and 99.9 keys
=> added the udf for scale 1 precision

bigquery_etl/cli/query.py, bigquery_etl/cli/routine.py
Follow up to https://github.com/mozilla/bigquery-etl/pull/2348 - updates `bqetl query validate` and `bqetl routine validate` after changed signature. 
(plus auto-file formatting)
~- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)~
~- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
~- [ ] If adding a new field to a query, ensure that …
=> Changed cli.format calls in other cli commands

sql/moz-fx-data-shared-prod/search_terms_derived/adm_weekly_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/search_terms_derived/aggregated_search_terms_daily_v1/query.sql
The adm weekly query was running, but always producing null results due to the inverted date range.
Also, removing the low volume filter per https://bugzilla.mozilla.org/show_bug.cgi?id=1729524#c4
Also, forcing all terms to lowercase before grouping, as I'm observing that the client does pass through terms with casing differences.
=> Fixups for search terms aggregate tables

sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_other_events_overall_v1/view.sql
Querying `telemetry.experiment_enrollment_other_events_overall` outside of shared-prod is not possible anymore due to the query exceeding complexity limitations. Rewriting the query fixed the problem.
=> Optimize enrollment_other_events_overall

bigquery_etl/cli/query.py, bigquery_etl/dryrun.py
`$ bqetl query schema validate {table}` raises  `AttributeError: Can't pickle local object 'validate_schema.<locals>._validate_schema'` since nested functions can't be serialized. 
Kept the name definition in scope by extracting the function and using a partial. 
There was also a `TypeError: unsupported format string passed to PosixPath.__format__` since [path objects don't support formatting directly](https://bugs.python.org/issue38222). Used the suggested fix of casting in the f-string. 
~- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)~
~- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream …
=> Fix pickling error in schema validate command (and Posixpath formatting error)

sql/moz-fx-data-shared-prod/search_terms_derived/adm_weekly_aggregates_v1/query.sql
See https://bugzilla.mozilla.org/show_bug.cgi?id=1733986
The intention of this query is to each day populate a partition that
windows over the previous 7 days. The GROUP BY should not include
`submission_date` and we need to inject the `@submission_date`
parameter into the query instead.
=> Bug 1733986 Fix date logic for adm_weekly_aggregates

README.md
ZetaSQL is only [supported on x86_64/amd64](https://github.com/google/zetasql/blob/master/java/com/google/zetasql/JniChannelProvider.java#L47) at the moment, so Rosetta 2 is suggested. Also added a suggested JDK 
~- [ ] Commits should reference a bug or github issue, if relevant (if a bug is referenced, the pull request should include the bug number in the title)~
~- [ ] If the PR comes from a fork, trigger integration CI tests by running the [Push to upstream workflow](https://github.com/mozilla/bigquery-etl/actions/workflows/push-to-upstream.yml) and provide the `<username>:<branch>` of the fork as parameter. The parameter will also show up
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed instructions.~
~- [ ] If adding a …
=> Added notes about Rosetta2 and a JDK version for Apple Silicon users

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml, sql/moz-fx-data-shared-prod/udf/aggregate_search_counts/udf.sql
https://bugzilla.mozilla.org/show_bug.cgi?id=1738132
1. Account for new urlbar handoff related histogram values in the udf that reads [`SEARCH_COUNTS`](https://probes.telemetry.mozilla.org/?search=search_counts&view=detail&probeId=histogram%2FSEARCH_COUNTS). 
2. Add aggregates for sap, adclicks and withads probes
=> Bug 1738132 - Added aggregations for new urlbar handoff probes to clients_daily (and downstreams)

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml
See https://bugzilla.mozilla.org/show_bug.cgi?id=1731310
Added newtabpage user pref and contextual services probes to clients daily to prepare for updating the `feature_usage` table.
=> Bug 1731310 - Added newtabpage pref and contextual probes to clients daily

sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/query.sql, tests/sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/test_access_point_probes/expect.yaml, tests/sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/test_access_point_probes/telemetry.clients_daily.schema.json, tests/sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/test_access_point_probes/telemetry.clients_daily.yaml, tests/sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/test_aggregation/telemetry.clients_daily.schema.json
Added handoff-related sources to `search_clients_daily` eg. `urlbar-handoff`, `in-content:tagged:firefox-b-d.urlbar`, etc.
=> Bug 1738132 - Added handoff sources to search_clients_daily

bigquery_etl/view/__init__.py
Removing the multitude of tables in mozdata.glam_etl which are interim/raw tables that we would not want analysts to find/use.
=> add glam_etl to non user facing view

bigquery_etl/events_daily/query_templates/event_types_history_v1/templating.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/event_types_history_v1/init.sql, sql/moz-fx-data-shared-prod/telemetry_derived/event_types_history_v1/query.sql
I'm not sure if increasing this threshold has any implications?
=> Increase event_property threshold

README.md
Based on my experience trying to set up the project on M1 mac I decided to make minor tweaks to the `Quick Start` section to emphasize the step for running terminal with Rosetta prior to doing anything else to avoid the next person from running into the same issues as myself.
=> docs: README Quick Start section tweaked

script/generate_and_publish_views, sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_etl_scheduled_query_usage_v1/query.py, sql/moz-fx-data-shared-prod/static/README.md
My editor auto `chmod +x`'d the query.py file since it has magic at the top.
=> Remove references to moz-fx-data-derived-datasets

bigquery_etl/dryrun.py, dags/bqetl_monitoring.py, sql/moz-fx-data-shared-prod/monitoring/suggest_impression_rate_live/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/suggest_impression_rate_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring_derived/suggest_impression_rate_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/suggest_impression_rate_v1/query.sql
And merge the historical data with the live data in the `suggest_impression_rate_live` materialized view.
This is needed for the Merino operational dashboard.
This fixes [the following JIRA ticket](https://mozilla-hub.atlassian.net/browse/ROAD-133).
=> Create a stable table for Fx Suggest's impression clicks

sql/moz-fx-data-shared-prod/telemetry/windows_10_aggregate/view.sql
Windows 11 still has os_version = 10 like Windows 10, so the only way to differentiate is by the build number. Might as well keep them on the same dashboard. This also cleans up older versions which currently combine to ~5% of overall Win10 user share into one grouping to cut down on some of the clutter as the number of releases increases over time.
=> Add Windows 10/11 21H2 update to aggregates

sql/moz-fx-data-shared-prod/regrets_reporter_ucs/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/regrets_reporter_ucs_derived/dataset_metadata.yaml
https://github.com/mozilla-services/cloudops-infra/pull/3546 was sufficient to allow these schemas to be deployed, but once bqetl automation started to generate metadata as well we wound up in an inconsistent generated state.
This seems like a reasonable place to mention https://bugzilla.mozilla.org/show_bug.cgi?id=1740483#c5 / https://bugzilla.mozilla.org/show_bug.cgi?id=1654078#c45. I didn't include views here as I'm primarily concerned with unblocking the schemas pipeline, but maybe that should be considered.
=> Add regrets-reporter-ucs dataset and ACL metadata

sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/query.sql
removing the additional column 'channel' from the final select query. This is not required in the CSV file
=> removed 'channel' from the last select statement

bigquery_etl/dryrun.py, dags/bqetl_fxa_events.py, sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_stdout_events_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_stdout_events_v1/query.sql
so that mozilla vpn funnel analysis can use events like `fxa_pay_setup - *` that only appear in the stdout tables.
=> Add derived table and view for fxa stdout events

bigquery_etl/dryrun.py, bigquery_etl/view/__init__.py, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_cumulative_population_estimate_v1/view.sql
Fixes https://github.com/mozilla/jetstream/issues/924
We've been running into `Resources exceeded during query execution: Not enough resources for query planning - too many subqueries or query is too complex.` errors when querying from `mozdata.telemetry.experiment_enrollment_cumulative_population_estimate`. This change fixes the issue. I already manually deployed the view to do some testing
=> Simplify experiment_enrollment_cumulative_population_estimate query

bigquery_etl/operational_monitoring/README.md, bigquery_etl/operational_monitoring/__init__.py, bigquery_etl/operational_monitoring/templates/histogram_init.sql, bigquery_etl/operational_monitoring/templates/histogram_query.sql, bigquery_etl/operational_monitoring/templates/histogram_view.sql, bigquery_etl/operational_monitoring/templates/scalar_init.sql, bigquery_etl/operational_monitoring/templates/scalar_query.sql, bigquery_etl/operational_monitoring/templates/scalar_view.sql
I've made some changes to support monitoring a rollout in release where we want to look at data by submission date rather than build ID. I've also added a readme to provide context/explanation on how this works
=> Add start_date filter and aggregation by submission_date.

bigquery_etl/feature_usage/templates/metadata.yaml, bigquery_etl/feature_usage/templating.yaml, dags/bqetl_feature_usage.py, sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/schema.yaml
RE: https://bugzilla.mozilla.org/show_bug.cgi?id=1731310 - Added newtab related fields to `feature_usage` table
Do this look reasonable? I wasn't able to add:
- The shortcut rows pref because it isn't sent by activity stream at the moment and will probably require a data review
- Pocket impression data because it doesn't have client ids so can't be joined here.
Related probe dictionary link for contextual services - [link](https://probes.telemetry.mozilla.org/?search=contextual.services&view=detail&probeId=scalar%2Fcontextual.services.topsites.click).
Also updated the template DAG  to `bqetl_feature_usage`
=> Bug 1731310 - Added newtab related fields to feature_usage

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml
For migrating accessibility dashboards to Looker: https://mozilla-hub.atlassian.net/browse/DENG-52
Making the fields `a11y_theme`, `a11y_hcm_foreground` and `a11y_hcm_background` available in clients_daily
=> Add a11y_theme fields to clients daily

bigquery_etl/cli/query.py, bigquery_etl/metadata/parse_metadata.py
Fixes https://github.com/mozilla/bigquery-etl/issues/2536 and https://github.com/mozilla/bigquery-etl/issues/2537
This adds support for `expiration_ms` to the metadata. We can already specify `require_partition_filter` (see https://github.com/mozilla/bigquery-etl/blob/9bca48821a8a0d40b1700cc14ecd8068d132ed06/sql/moz-fx-data-shared-prod/telemetry_derived/desktop_funnel_installs_v1/metadata.yaml#L15). When running `schema deploy` this partitioning information will also be updated in the source table.
=> Allow to specify partition expiration in metadata

.circleci/config.yml
[Dependabot is resolving dependencies with python 3.9+](https://github.com/mozilla/bigquery-etl/pull/2539/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552), and this will allow that to pass CI so long as the actual dependencies are the same for python 3.8
=> Ignore comments when verifying compiled requirements

sql/moz-fx-data-shared-prod/contextual_services/quicksuggest_click_live/metadata.yaml, sql/moz-fx-data-shared-prod/contextual_services/quicksuggest_click_live/view.sql, sql/moz-fx-data-shared-prod/contextual_services/quicksuggest_impression_live/metadata.yaml, sql/moz-fx-data-shared-prod/contextual_services/quicksuggest_impression_live/view.sql, sql/moz-fx-data-shared-prod/contextual_services/topsites_click_live/metadata.yaml, sql/moz-fx-data-shared-prod/contextual_services/topsites_click_live/view.sql, sql/moz-fx-data-shared-prod/contextual_services/topsites_impression_live/metadata.yaml, sql/moz-fx-data-shared-prod/contextual_services/topsites_impression_live/view.sql
See https://mozilla-hub.atlassian.net/browse/ROAD-163
All of the underlying live tables are already accessible to the
`contextual-services` except for quicksuggest impressions, so only one of these
views is defined with authorization.
=> ROAD-163 Add live views for contextual-services pings

sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/query.sql
This is to correct the Unicode issue 
https://workflow.telemetry.mozilla.org/log?dag_id=glam&task_id=glam_import_desktop_aggs_beta&execution_date=2021-12-06T02%3A00%3A00%2B00%3A00
=> correcting the issue due to unicode

bigquery_etl/docs/derived_datasets/generate_derived_dataset_docs.py, bigquery_etl/docs/derived_datasets/templates/table.md
See title; added some helper functions, switched some references to `Path` objects and supported injecting `README` content. 
Here's a diff of the generated docs before and after the factor + readme support: [Gist](https://gist.github.com/ANich/16ea615c772a6dbac73071236bd42d23). 
The main differences in the diff are:
1. Some View+Metadata links have been removed, they were previously pointing to the wrong files because of some leftover state on iterations. Example L442-443:
```
-[Source Directory](https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/mozilla_vpn/vat_rates)  | [View Definition](https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/mozilla_vpn/vat_rates/view.sql)  | [Metadata …
```
=> Derived dataset docs generation - refactor and support READMEs

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py
See https://github.com/mozilla/jetstream/issues/972
It's easier for the Experimenter folks to debug issues if they can see where requests from the API are coming from.
cc @jaredlockhart
=> Add user-agent to experimenter request

sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v2_external/query.sql, tests/sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v2_external/test_single_day/moz-fx-data-shared-prod.contextual_services_stable.quicksuggest_impression_v1.yaml, tests/sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v2_external/test_single_day/suggest-searches-prod-a30f.logs.stdout.yaml
This better matches the current client behavior for matching.
We're currently getting `<disallowed>` in results from Merino and mixed case in results from telemetry.
I don't think preserving the casing or leading whitespace has analytical value, and it makes the results harder to work with.
Note that we'll need to also make these changes in cloudops-infra to have them take effect.
=> Lowercase and trim in suggest_impressions_sanitized_v2

bigquery_etl/dryrun.py, dags.yaml, dags/bqetl_regrets_reporter_summary.py, sql/moz-fx-data-shared-prod/regrets_reporter/regrets_reporter_summary/metadata.yaml, sql/moz-fx-data-shared-prod/regrets_reporter/regrets_reporter_summary/view.sql, sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/init.sql, sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/query.sql
=> Add regrets reporter summary table (fixes #2572)

bigquery_etl/docs/derived_datasets/generate_derived_dataset_docs.py, bigquery_etl/docs/derived_datasets/templates/dataset_header.md, bigquery_etl/docs/derived_datasets/templates/table.md, sql/moz-fx-data-shared-prod/udf_legacy/README.md
Moved dataset header to a template and added readme content 
Updated Metadata references ([see comment](https://github.com/mozilla/bigquery-etl/pull/2559#discussion_r765270244)) and added some logging
Updated a README that was causing the page title to be hidden 
=> Support dataset READMEs and metadata, cosmetic changes

bigquery_etl/docs/derived_datasets/templates/table.md
Fill absent metadata with empty string. Somehow didn't show up in my local instance on an earlier PR
=> Quick fix for null metadata descriptions

dags/bqetl_search_terms_daily.py, sql/moz-fx-data-shared-prod/search_terms/suggest_impression_sanitized/view.sql, sql/moz-fx-data-shared-prod/search_terms_derived/adm_weekly_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_terms_derived/adm_weekly_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/search_terms_derived/aggregated_search_terms_daily_v1/query.sql
See https://mozilla-hub.atlassian.net/browse/ROAD-167
The Jira ticket discusses just updating the `adm_weekly_aggregates` to include
queries sent through Merino, but the scope of this PR is a bit wider, also
updating the list of top daily queries to include Merino.
Note that suggest_impression_sanitized_v2 pulls in both search terms sent
through telemetry and through the Merino pathway, so this should be safe to
merge next week even though we do not have queries flowing through Merino in
release at this point.
=> ROAD-167 Update aggregates to use suggest_impression_sanitized_v2

bigquery_etl/stripe/__init__.py, bigquery_etl/stripe/allowed_fields.py, dags/bqetl_subplat.py, sql/moz-fx-data-shared-prod/stripe_external/events_schema_check_v1/metadata.yaml, sql/moz-fx-data-shared-prod/stripe_external/events_schema_check_v1/query.py, tests/stripe/test_allowed_fields.py
fixes #2205
this splits out the part where stripe throws an error on new fields into a separate job. It doesn't re-use the data from the stripe API because we don't want to preserve new fields anywhere unless they have been approved, lest they contain private information.
=> Allow stripe events import to succeed when schema changes

README.md
Downloading JAVA is now required in many places in our repo, such as generating docs, running dry-run, etc. I think it's time that we remove the "optionally" part from this step instruction.
=> Require downloading Java dependencies as part of setup

dags.yaml, dags/bqetl_error_aggregates.py, dags/bqetl_nondesktop.py
When collecting a list of Airflow tags we identified that some DAG owners were no longer at Mozilla. This PR updates out of date owners.
Airflow Tags Google Sheet: https://docs.google.com/spreadsheets/d/1WXo5_d8j_KfGzT07ay3gC2zAfnhRHzxoZDlwcThNvf0/edit#gid=0
=> Updated owner of DAGs as per tags google sheet

script/glam/export_csv
The glam fenix imports are failing with error 'Dependencies not met'
https://workflow.telemetry.mozilla.org/log?dag_id=glam_fenix&task_id=glam_fenix_import_glean_counts&execution_date=2021-12-10T02%3A00%3A00%2B00%3A00
The error is complaining about the upstream task 'export_org_mozilla_fenix_glam_beta'
Example:
The task starts at time 2021-12-11 02:18:35,380,
But the dependent task finishes afterward: at the time [2021-12-11 02:19:24,249]
=> adding 2m sleep to the export task for allowing it to complete

.circleci/config.yml, .circleci/post-diff.js
For https://github.com/mozilla/bigquery-etl/issues/2313
This adds a bot to the CI that will compare generated and static SQL to the `main` branch of this repository whenever a PR is opened. This hopefully makes it easier for reviewers to reason about changes made to generated SQL.
An example of what the diff looks like is shown below.
=> Show generated SQL diff in PR

bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_beta__view_clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_beta__view_clients_daily_scalar_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_nightly__view_clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_nightly__view_clients_daily_scalar_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_release__view_clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_release__view_clients_daily_scalar_aggregates_v1.sql
This commit has 2 changes:
The firefox_desktop_glam (glean) failed with the below error :
Error in query string: Error processing job 'moz-fx-data-glam-prod- fca7:bqjob_r5dc049a3ef61f64b_0000017d7b8d6f6b_1': Failed to parse input string
Link to error
It was decided to filter out pings that provide an app_build that doesn't have a valid date
Add minimum_client_count filter for firefox_desktop product (value = 10 for time being and should be corrected in the future)
=> Firefox desktop date check

.circleci/config.yml
Should fix CI failures. The diffs are only useful in PRs anyway
=> Do not generate SQL diff on main

bigquery_etl/operational_monitoring/__init__.py
After this commit https://github.com/mozilla/bigquery-etl/commit/3f0b5373ce23734c3bc9cf7487107685f8c19fa2, the way that `render()` would be called has changed a tad and is currently causing failures in the operational monitoring airflow.
These changes should address the failures
=> Fix broken opmon dag.

docs/cookbooks/common_workflows.md
See https://bugzilla.mozilla.org/show_bug.cgi?id=1727081
=> Bug 1727081 Add link to Data Access Workgroups docs

.circleci/post-diff.js
Fixes https://github.com/mozilla/bigquery-etl/issues/2620
=> Ensure diff has maximum length

bigquery_etl/docs/derived_datasets/generate_derived_dataset_docs.py, bigquery_etl/docs/derived_datasets/templates/table.md
Get the schemas for each view from the generated `schema.yaml` file. Currently only works for stable views, will make sure these get generated for non-stable views in a follow up https://github.com/mozilla/bigquery-etl/pull/2614#discussion_r779028390
=> Added schemas to derived dataset docs

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/fxa_attribution_v1/query.sql
Starting 2021-12-08 a proportion of FxA events with UTM attribution data began showing up with the `service` value "undefined_oauth" instead of null.
- [Slack thread](https://mozilla.slack.com/archives/C018SNLQP6C/p1641498560007200)
=> Include FxA events with "undefined_oauth" service for attribution

script/generate_sql, script/update_example_glean_usage
Fixes:
```
+ ./script/generate_all_views --target-project moz-fx-data-shared-prod --sql-dir /tmp/sql
+ ./script/bqetl generate stable_views --target-project moz-fx-data-shared-prod --sql-dir /tmp/sql --parallelism=20
telemetry_derived/foo/query.sql                             OK
+ ./script/bqetl generate glean_usage --project-id moz-fx-data-shared-prod --output-dir /tmp/sql
Usage: ./script/bqetl generate glean_usage [OPTIONS]
Try './script/bqetl generate glean_usage --help' for help
```
=> Update glean_usage generate parameter in scripts

dags/bqetl_regrets_reporter_summary.py, sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/init.sql, sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/query.sql
- Queries have been updated to use stable tables.
- Since the init.sql was modified and no additional data was appended I'd suggest we drop the old table (or truncate) and re-run the init script to recreate the table depending on this approach we take.
resolves #2635 
---
=> regrets-reporter queries updated to use stable tables

sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/query.sql
DAG `bqetl_regrets_reporter` failed (https://workflow.telemetry.mozilla.org/log?dag_id=bqetl_regrets_reporter_summary&task_id=regrets_reporter_summary__v1&execution_date=2022-01-09T04%3A00%3A00%2B00%3A00) with the following error:
```shell
[2022-01-10 22:31:20,925] {{pod_launcher.py:149}} INFO - Error in query string: Error processing job 'moz-fx-data-shared-
[2022-01-10 22:31:20,926] {{pod_launcher.py:149}} INFO - prod:bqjob_r20704d803590cdda_0000017e461e041b_1': No matching signature for
[2022-01-10 22:31:20,926] {{pod_launcher.py:149}} INFO - operator = for argument types: TIMESTAMP, DATE. Supported signature: ANY = ANY
```
This should address this error.
--- …
=> bug: explicitly casting dates in where clause to date

.circleci/config.yml
Regression introduced in https://github.com/mozilla/bigquery-etl/pull/2594/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47L432-R454
Fixes https://github.com/mozilla/private-bigquery-etl/issues/50
=> Fix copying private generated SQL in CI

.circleci/config.yml
We used to call the `generate_sql` script which calls `bqetl dependency record`. Now that we use the CLI, this has to be explicitly called in CI
=> Record dependencies when generating private SQL

.circleci/config.yml, Dockerfile
On Apple Silicon docker build isn't locating java when building pyjnius
=> Added JDK install to python-deps stage for pyjnius build on M1

bigquery_etl/glam/generate.py, sql/glam-fenix-dev/glam_etl/firefox_desktop_glam_nightly__view_clients_daily_histogram_aggregates_v1/view.sql, sql/glam-fenix-dev/glam_etl/firefox_desktop_glam_nightly__view_clients_daily_scalar_aggregates_v1/view.sql
correcting  the minimum count values description to include 0 
"minimum_client_count": {
"type": "integer",
"minimum": 0,
"description": "The minimum client count for each build id.",
},
=> reduced the minimum count values for firefox desktop

dags/bqetl_monitoring.py, sql/moz-fx-data-shared-prod/monitoring/stable_table_column_counts/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/stable_table_column_counts_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/stable_table_column_counts_v1/schema.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/stable_table_column_counts_v1/script.sql
The query has been migrated from https://sql.telemetry.mozilla.org/queries/76766/source
=> [Bug 1748716] Add scheduled query for stable table column count monitoring

bigquery_etl/metadata/parse_metadata.py, script/generate_sql, sql_generators/derived_view_schemas/__init__.py, tests/data/metadata.yaml, tests/metadata/test_parse_metadata.py
Specifically for views in user-facing derived datasets. Along with some metadata updates to support `references`
More context: https://bugzilla.mozilla.org/show_bug.cgi?id=1713623#c3 and https://github.com/mozilla/bigquery-etl/pull/2614#discussion_r779028390 
Along with https://github.com/mozilla/bigquery-etl/pull/2118, this should close https://github.com/mozilla/bigquery-etl/issues/1685.
=> Added sql_generators script to create (derived dataset) schema.yaml files

script/glam/export_csv
Reverts mozilla/bigquery-etl#2609. The sleep timer is no longer required and the issue has been resolved by adding a dummy task to the airflow dag.
=> Revert "adding 2m sleep to the export task for allowing it to complete"

dags/bqetl_regrets_reporter_summary.py, sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/init.sql, sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/regrets_reporter_derived/regrets_reporter_summary_v1/query.sql
modified regrets reporter summary query to run query against all data
The job is no longer "incremental", but full table reload occurs. This is because of the logic. Currently, Jesse says the query is 2.2Gib of processing to execute. He also said that this will increase a bit once this bug is resolved: https://bugzilla.mozilla.org/show_bug.cgi?id=1748284
After a quick investigation and a chat with Jesse it became apparent that the previous approach would not work for getting the data we need due to the query logic. We could see that also all the results appended by the incremental job were wrong. See comments in this issue for more information: https://github.com/mozilla/bigquery-etl/issues/2634
in the logs of the `manual-trigger-required-for-fork` CI task together …
=> modified regrets reporter summary query to run query against all data

.circleci/config.yml
If I understand the pipeline definition correctly there are no actual logic tweaks required for the dag tag validation to work in CircleCi, as soon as it's added to telemetry-airflow main branch it should also be used here.
telemetry-airflow PR for adding Airflow tags validation: https://github.com/mozilla/telemetry-airflow/pull/1446
---
=> tweaked comment in validate-dags to mention that tags are also validated

.circleci/config.yml
The `dags/` folder is currently not pushed to `generated-sql` since the DAG generation is running after SQL is pushed to the branch. Once this has been fixed I'll open a ticket with SRE to update the DAG copy script and copy DAGs to Airflow from the `generated-sql` rather than the `main` branch.
=> Push DAGs to generated-sql branch

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
This was annotated in the old Spark implementation of our ETL, but lost in the SQL rewrite.
=> Add code comment pointing to bug 1481671

bigquery_etl/docs/generate_docs.py, bigquery_etl/docs/mozfun/generate_mozfun_docs.py, tests/docs/test_generate_docs.py
Derived dataset docs were being generated multiple times in the same call, modified the call order to prevent that. Also extracted the mozfun generation to its own dir/function so it's easier to find and modify in the future. 
Generated docs locally before and after for verification and the diff was empty 
=> Extract mozfun docs generation and modify call order

.circleci/config.yml
Okay, I'm trying to solve the mystery around `dags/` not being in `generated-sql` once and for all. I wrote a CI test step to check the files exist in: https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/12979/workflows/3dad7a02-d518-49b7-b5e1-39cd6482ab02/jobs/98704
The problem was that `generate-diff` overwrote the `generated-sql` contents.
=> Ensure dags/ exists on generated-sql and speed up CI

.circleci/config.yml
Follow-up to https://github.com/mozilla/bigquery-etl/pull/2690
=> Copy generated DAGs when pushing generated SQL

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_content_v1/query.sql
This is related to the discussion of missing probe https://mozilla.slack.com/archives/CB1EQ437S/p1643899307478819
The probe video_dropped_frames_proportion_exponential is not seen in glam UI. 
The table `telemetry_derived.clients_daily_histogram_aggregates_v1` does not show the probe either
I have run the query based on https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_content_v1/query.sql however including the missing probe. 
[Here is the sample query](https://gist.github.com/alekhyamoz/0c3a252f1d8b601beec39b1ccee82e5b) which outputs the missing probe related data 
This PR updates the sql by including the missing probe
=> Add missing probes

bigquery_etl/shredder/delete.py
addresses https://github.com/mozilla/bigquery-etl/pull/2711#pullrequestreview-878074033
draft because I want to run tests to verify speed without the `DISTINCT` clause
=> Clean up shredder whitespace and unneeded DISTINCT

bigquery_etl/stripe/allowed_fields.yaml, tests/stripe/test_allowed_fields.py
needed for [DVPN-111](https://mozilla-hub.atlassian.net/browse/DVPN-111)
this will need a manual backfill, but the schema changes will be automatic, and are not exposed to any derived tables with a schema in this repo.
=> DVPN-111 - Allow stripe imports to include customer address

bigquery_etl/shredder/bug1751979.py, bigquery_etl/shredder/delete.py
See discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1751979#c13
This should be the final set of tables we need to support in shredder for sanitization. And this will only be applied to the partitions earlier than 2019-11-22.
=> Support clients_daily and search_clients_daily sanitization

.circleci/config.yml, Dockerfile, README.md, bqetl, docs/cookbooks/common_workflows.md, docs/cookbooks/testing.md, requirements.in, script/glam/README.md
to work around https://github.com/pypa/pip/issues/9644
see also https://github.com/mozilla/gcp-ingestion/pull/2001
=> Use --no-deps when installing compiled requirements files

bigquery_etl/operational_monitoring/templates/scalar_view.sql
I forgot to also fix the generated view. Follow-up to https://github.com/mozilla/bigquery-etl/pull/2761
=> [Bug 1757440] Fix opmon scalar view dimensions

bigquery_etl/stripe/__init__.py, dags/bqetl_subplat.py, sql/moz-fx-data-shared-prod/stripe_external/itemized_payout_reconciliation_v5/metadata.yaml
32 retries makes this try until 9:15am PT, so that we can at least see when it comes in before probably moving it to a separate dag.
also wait up to 30 minutes for the report to finish, because the most recent run didn't finish in 10 minutes.
=> DVPN-111 - Wait even longer for stripe report

bigquery_etl/stripe/allowed_fields.yaml, bigquery_etl/stripe/event.schema.json, bigquery_etl/stripe/invoice.schema.json
backfill by updating schemas, then in airflow: rerun `stripe_external__events__v1` and `stripe_external__invoices__v1` from march 1st onward. no further downstream tables are impacted.
schema update procedure:
```sh
sed 's/if not has_rows:/if not has_rows and False:/' -i bigquery_etl/stripe/__init__.py
script/bqetl stripe import --resource=Invoice --table=moz-fx-data-shared-prod.stripe_external.initial_invoices_v1 --date="$(date -d+1day +%F)" < /dev/null
script/bqetl stripe import --resource=Event --table=moz-fx-data-shared-prod.stripe_external.events_v1 --date="$(date -d+1day +%F)" < /dev/null
bq query --dry_run --format=json --dataset_id=moz-fx-data-shared-prod:stripe_external < sql/moz-fx-data-shared-prod/stripe_external/invoices_v1/init.sql | jq .statistics.query.schema.fields > …
```
=> Bug 1757804 - Add new stripe invoice field proration_details

bigquery_etl/stripe/allowed_fields.yaml, bigquery_etl/stripe/event.schema.json, bigquery_etl/stripe/invoice.schema.json
I forgot to verify that the schema was actually correct in #2776, and `proration_details` is a `RECORD` not a `STRING`.
documentation for the field: https://stripe.com/docs/api/invoices/line_item#invoice_line_item_object-proration_details
incorrect schema was rolled back via:
```sh
bq cp moz-fx-data-shared-prod:stripe_external.initial_invoices_v1{@1646431146000,}
bq cp moz-fx-data-shared-prod:stripe_external.events_v1{@1646431146000,}
bq cp moz-fx-data-shared-prod:stripe_external.invoices_v1{@1646431146000,}
```
same schema deploy strategy as for #2776:
```sh
sed 's/if not has_rows:/if not has_rows and False:/' -i bigquery_etl/stripe/__init__.py
script/bqetl stripe import --resource=Invoice --table=moz-fx-data-shared-prod.stripe_external.initial_invoices_v1 --date="$(date -d+1day +%F)" < …
```
=> Bug 1757804 - Fix schema for proration_details

sql/moz-fx-data-shared-prod/mozilla_vpn/active_subscriptions/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn/subscription_events/view.sql
fixes view deploy error introduced by #2782: `Queries in UNION ALL have mismatched column count; query 1 has 32 columns, query 2 has 31 columns at [19:1]`
=> DVPN-118 - Remove unintentional column from vpn aggregates views

dags/bqetl_subplat.py, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/active_subscriptions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/subscription_events_v1/metadata.yaml
`|ds_nodash` isn't available until airflow 2.2, we are on 2.1.4 so per https://airflow.apache.org/docs/apache-airflow/2.1.4/macros-ref.html we have to use `macros.ds_format(ds, input_format, output_format)`
=> DVPN-118 - Fix jinja filter for delaying vpn aggregates

bigquery_etl/dryrun.py, dags/bqetl_subplat.py, sql/moz-fx-data-shared-prod/mozilla_vpn/channel_group_proportions/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_live/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_v1/query.sql
because it's derived from `moz-fx-data-shared-prod.mozilla_vpn_derived.subscription_events_v1`, which is delayed 7 days.
=> DVPN-118 - Delay channel_group_proportions_v1

bigquery_etl/glam/templates/extract_probe_counts_v1.sql
This is a quick fix to remove the unwanted app_versions creeping into the extracts for Fenix (release channel)
Related to [the issue](https://github.com/mozilla/glam/issues/1893)
A permanent solution needs to be brainstormed and put in place.
=> remove unwanted versions from fenix etl

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_etl_scheduled_query_usage_v1/query.py
We can add `mozdata` to the query usage monitoring ETL.
=> Monitor query usage for mozdata

bigquery_etl/glam/clients_daily_histogram_aggregates.py, bigquery_etl/glam/clients_daily_scalar_aggregates.py, bigquery_etl/util/probe_filters.py, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_v1.sql.py, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1.sql.py
Fixes #2792
This implements a quick-fix to stop probes that cause error on GLAM from being aggregated.
There's upcoming work fixing [another issue](https://github.com/mozilla/glam/issues/1847) that will also allow us to replace the probe names hardcoded in this PR with api calls that will return them.
=> Exclude probes that cause error on GLAM from ETL (#2792)

dags/bqetl_internet_outages.py, sql/moz-fx-data-shared-prod/internet_outages/global_outages_staging_v1/metadata.yaml
Bug fix for https://github.com/mozilla/bigquery-etl/pull/2866
=> Remove date_partition_parameter for internet outages staging

dags/bqetl_internet_outages.py, sql/moz-fx-data-shared-prod/internet_outages/global_outages_staging_v1/metadata.yaml
fixed param name to submission_date,
the template uses `@submission_date` param, it looks like we tried to set the value for param `date` which does not exist:
https://github.com/mozilla/bigquery-etl/blob/b9a2f77eb7b5b17e9c86d6b96c90e6ea48bdd3a0/sql/moz-fx-data-shared-prod/internet_outages/global_outages_staging_v1/query.sql#L89
error message:
```[2022-04-06 08:14:10,938] {{pod_launcher.py:149}} INFO - 'submission_date' not found at [89:23]```
=> fixed param name to submission_date

dags.yaml, dags/bqetl_cjms_nonprod.py, sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/flows_live/view.sql, sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/flows_v1/metadata.yaml, sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/flows_v1/query.sql, sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/subscriptions_v1/query.sql
flows_v1 was not getting events for the previous UTC date that arrive after 00:22 UTC, this pushes back that cutoff to 02:00 UTC, and uses a live view to catch not-yet-aggregated flows from the current date.
=> DVPN-89 - Catch all flows at end of day for cjms nonprod

bigquery_etl/query_scheduling/dag.py, bigquery_etl/query_scheduling/dag_collection.py, tests/cli/test_cli_dag.py
If you add a DAG to `dags.yaml` that doesn't appear in any metadata files it won't end up having any tasks. When trying to generate the dag python file it returns invalid python, something like:
```
...
with DAG(
...
) as dag:
<EOF>
```
which makes DAG generation fail at formatting the generated python file. The error raised from `Black` is pretty esoteric, so PR adds a clearer upstream error.
In future it might be worth changing this behaviour to support DAGs that don't appear in metadata files but are still bigquery-etl related, maybe with a `DummyOperator` or something. (For context this is why I put https://github.com/mozilla/telemetry-airflow/pull/1481 in telemetry-airflow)
Also updated an unrelated f-string.
=> Added InvalidDag when generating a DAG with no tasks

sql/mozfun/norm/browser_version_info/metadata.yaml, sql/mozfun/norm/browser_version_info/udf.sql
[DENG-96](https://mozilla-hub.atlassian.net/browse/DENG-96) - Creates a `browser_version_info` UDF that adds version metadata to a struct. This is primarily for views and is mimicking an external dataset that we could use for a version source of truth. This should show up in Looker as a dimension group. 
RE: the temporary part, I initially wanted to extend `telemetry.releases` but the API it's built on is missing release data for iOS and I'm not 100% sure whether it's maintained currently. So I think this is the next best thing for now.
=> DENG-96 - Create browser_version_info UDF

sql/moz-fx-data-shared-prod/telemetry/unified_metrics/view.sql
The `country` field coming from Desktop is coalesced with `??`, but mobile isn't. This unifies the two.
=> Coalesce country in unified metrics

sql/mozfun/norm/browser_version_info/udf.sql, sql/mozfun/norm/extract_version/README.md, sql/mozfun/norm/extract_version/metadata.yaml, sql/mozfun/norm/extract_version/udf.sql
Added a new UDF to extract (rather than truncate) numerical versions - This allows analysis by patch numbers as well, given that truncating to the patch level doesn't support valid numbers. 
Also updated the `browser_version_info` UDF to use the new UDF. 
Is there any reason we shouldn't represent versions like this?
=> Added extract_version UDF, modified browser_version_info UDF

sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/query.sql
Currently, the Firefox for iOS and Fenix numbers are inflated due to considering clients not active on the given day.
This was uncovered while helping @lucia-vargas-a understand differences between this dataset and GUD.
=> Apply days_since_seen = 0 consistently in unified_metrics

bigquery_etl/schema/__init__.py, netlify.toml
Workaround for [bug 1761292](https://bugzilla.mozilla.org/show_bug.cgi?id=1761292) "Netlify tasks for bigquery-etl failing due to timeout".
=> Reduce logging to speed up Netlify CI builds (bug 1761292)

sql/moz-fx-data-shared-prod/telemetry/clients_probe_processes/view.sql
It currently conflicts with [sql/moz-fx-data-shared-prod/telemetry/client_probe_processes/view.sql](https://github.com/mozilla/bigquery-etl/blob/6558dd29565f1850ee338619b92e70e1bc9a2442/sql/moz-fx-data-shared-prod/telemetry/client_probe_processes/view.sql).
---
=> Correct `clients_probe_processes` view name.

bigquery_etl/publish_static.py
This will resolve [bug 1768018](https://bugzilla.mozilla.org/show_bug.cgi?id=1768018) "_Airflow task publish_bqetl_static.publish_static_mozdata failing on 2022-05-03_".
Also:
- Allows the `publish_static` script to work for any project rather than just `moz-fx-data-shared-prod`.
- Fixes a couple of bugs.
- Uses a more efficient approach for finding `data.csv` files.
---
=> Only publish static tables in user-facing datasets to `mozdata` (bug 1768018)

sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/schema.yaml
PR to add `first_seen_date` column to `telemetry_derived.active_users_aggregates_v1`.
=> Deng 72 add first seen date to active users

sql/mozfun/norm/browser_version_info/udf.sql, sql/mozfun/norm/extract_version/README.md, sql/mozfun/norm/extract_version/udf.sql
This is a breaking change but is more correct than the existing behaviour. See discussion here https://github.com/mozilla/bigquery-etl/issues/2917
Before the minor version of 96.10.1 would be parsed as .1 when it represents minor version 10 semantically (at least in [semver](https://semver.org/)). Now the minor version parses to 10.
This does break leading 0s in version numbers but this hasn't happened in release: https://www.mozilla.org/en-US/firefox/releases/ though we have had a number of minor version .10's
Note `truncate_version` still does have this problem for minor and patch versions > 10 but is more widely used so should probably be managed more carefully.
=> Ignore leading 0s in extract_version and browser_version UDFs

sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v1/query.sql
The `bq` command that gets run by airflow by default gets `{date_partition_parameter}={airflow run date}` as a parameter [ref](https://github.com/mozilla/telemetry-airflow/blob/480361ea03578de9e8568669b14b446862de0f91/dags/utils/gcp.py#L227). 
eg:
```
bq query --project_id=moz-fx-data-shared-prod --parameter=cohort_date:DATE:2022-05-13 --dataset_id=telemetry_derived --destination_table=rolling_cohorts_v1$20220513
```
PR updates the query to use `cohort_date`
=> Update query parameter for rolling_cohorts to match default 

dags/bqetl_analytics_aggregations.py, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v1/metadata.yaml
Updates similar to #2969 and #2968. PR explicitly adds `submission_date` as a `bq` parameter to get activity for that day.
=> Updated metadata and DAG for cohort_daily_statistics

dags/bqetl_analytics_aggregations.py, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v1/query.sql
Rollback #2970 - partitioning an activity_date probably makes more sense and is also easier - we currently don't have a way to easily specify "append to _previous_ partitions on every run". (we write to `destination_table:{partition}` directly).
=> Change partition strategy for cohort_daily_statistics

.circleci/config.yml, script/entrypoint
maybe this can solve the issue with flaky integration tests? seems unlikely, but needs fixing regardless
=> Remove redundant GOOGLE_APPLICATION_CREDENTIALS in integration

dags.yaml, dags/bqetl_acoustic_contact_export.py, dags/bqetl_acoustic_raw_recipient_export.py
pushing bqetl acoustic dags by 1 hour to see if that resolves sensor issues
for some reason the external task sensor fails to realise task completed. Noticed that other DAGs using this pattern have different intervals for upstream and downstream DAGs. Trying to see if doing the same here helps resolve the issue.
=> pushing bqetl acoustic dags by 1 hour to see if that resolves sensor issues

sql/moz-fx-data-shared-prod/telemetry/nondesktop_clients_last_seen_v1/view.sql
Replaces #2998 which had mismatched columns.
We now explicitly list all columns in the union to prevent further regressions.
The underlying problem was that `isp` appeared at the end of the column list
for existing tables, but appears mid-list for the more newly created tables.
=> Bug 1770762 - Add Focus, Firefox iOS, Klar to nondesktop_clients_last_seen

sql/moz-fx-data-shared-prod/search_terms_derived/dataset_metadata.yaml
/CC @chelseatroy @quiiver 
needs to be merged at the same time as https://github.com/mozilla-services/cloudops-infra/pull/4120, which itself depends on https://github.com/mozilla-services/cloudops-infra-terraform-modules/pull/121
=> DSRE-661 Add metadataViewer access to search_terms_derived dataset

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/active_subscription_ids_live/view.sql
As a side-effect of #3031 the `mozilla_vpn_derived.active_subscription_ids_live` view is now including a few subscriptions from the current date, which is causing the `mozilla_vpn_derived.subscription_events_live` view to consider most active subscriptions as being cancelled on the current date.
To fix this `mozilla_vpn_derived.active_subscription_ids_live` will now exclude subscriptions that started after the last ETL'd date (we can't rely on `CURRENT_DATE`, otherwise there would be a time period between UTC midnight and when the ETL runs where the same problem would occur).
--- …
=> Fix `mozilla_vpn_derived.active_subscription_ids_live` view

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/subscription_events_live/view.sql
After #3031 and #3064 the `mozilla_vpn_derived.subscription_events_live` view still contains some "New Trial" events for the current date, but no other types of events.  This will prevent it from having "New Trial" events for the current date.
---
=> Fix `mozilla_vpn_derived.subscription_events_live` view

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/query.sql
The substring that identifies the plan interval may not be at the very end (e.g. `org.mozilla.gps.mozillavpn.product.12_month_subscription_free_trial`).
---
=> Use substring match rather than suffix match for VPN Google SKUs.

sql/moz-fx-data-shared-prod/search_terms/sanitization_job_languages/metadata.yaml, sql/moz-fx-data-shared-prod/search_terms/sanitization_job_languages/view.sql
This PR adds a virtual view that offers a tabular representation, for each sanitation job, of:
- Which languages the NLP model detected in the search terms
- How many search terms got categorized as each language
We will use this on the job's Looker dashboard to visualize the language distribution in our search data, and to create an alarm if changes in the language distribution indicate that our constituency for search features might be changing.
=> Add a virtual view for the language data from the sanitization job

sql/moz-fx-data-shared-prod/telemetry_derived/latest_versions/metadata.yaml
Jira: https://mozilla-hub.atlassian.net/browse/DSRE-885
What this PR does:
* trying to setup Glam SAs for "ad hoc ETL" / ETL processing outside of WTMO & GKE to be able to access required tables & views;
* as such, added minimal metadata to a known table required by glam ETL (though i'm uncertain I'm the right person to add metadata other than the access - e.g. will this fail on missing description, and if so, gotta track down a description)
Related PR:
- https://github.com/mozilla-services/cloudops-infra/pull/4185
=> prelim commit w/access metadata to telemetry_derived.latest_versions for glam SAs

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/site_metrics_empty_check_v1/query.sql
Will fix [bug 1776716](https://bugzilla.mozilla.org/show_bug.cgi?id=1776716) "Airflow task `bqetl_mozilla_vpn_site_metrics .mozilla_vpn_derived__site_metrics_empty_check__v1` failing since 2022-06-22".
---
=> Ignore missing Google Analytics data for vpn.mozilla.org after 2022-06-21 (bug 1776716)

bigquery_etl/cli/dag.py, bigquery_etl/query_scheduling/dag_collection.py
Currently, generating a single DAG using `bqetl dag generate` doesn't include upstream/downstream dependencies. 
To reproduce try generating a DAG that depends on a stable table for eg. Generating with `bqetl generate` includes dependencies but with `bqetl generate your_dag` doesn't
=> Get DAG task dependencies when generating a single DAG

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/query.sql
Currently all subscriptions with null `customer_id` incorrectly have the same `customer_start_date` of the earliest subscription with null `customer_id`.
---
=> Fix `mozilla_vpn_derived.all_subscriptions_v1.customer_start_date` when `customer_id` is null

sql/moz-fx-data-shared-prod/search_terms/sanitization_job_data_validation_metrics/metadata.yaml, sql/moz-fx-data-shared-prod/search_terms/sanitization_job_data_validation_metrics/view.sql
The view requires tow input tables:
1. the search sanitization metadata table
2. the table that records the detected languages for each sanitization job run. 
The output table contains aggregate information describing what people searched for (total number of characters, total number of words, and total number of probably-in-English search terms versus unknown or probably-some-other-language, for example). 
We will check how these proportions vary over time to identify if our search volume is _changing_ such that the assumptions about it that we used to develop our sanitization strategy no longer apply.
**Example:** Right now, only U.S and Canada-based constituents can opt into providing their search data. Since most addresses in the U.S. and Canada contain numbers, our sanitization …
=> Data Validation Derived View

bigquery_etl/dryrun.py, dags/bqetl_fxa_events.py, sql/moz-fx-data-shared-prod/firefox_accounts/docker_fxa_admin_server_sanitized/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts/docker_fxa_customs_sanitized/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v1/query.sql
=> DENG-215 - Enable access to sanitized FxA logs

sql/moz-fx-data-shared-prod/udf/extract_schema_validation_path/udf.sql
Follow-up to #3123.  I found one more type of error message containing key names.
---
=> Include extraneous keys in schema error paths

bigquery_etl/glam/generate.py, sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/clients_scalar_probe_counts_v1/query.sql
This adds comments to provide some context behind client count values used when filtering out builds in GLAM ETL.
=> Document GLAM ETL client count filter values

bigquery_etl/glam/templates/clients_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/clients_scalar_aggregates_v1.sql
This should fix `extract_probe_counts_v1` query failing due to integer overflows on casting.
We got some big negative numbers in few histogram probes around 2022-08-04 which seem to be some random bit flips. I'm putting a lower bound for a value in a filter at 0 as we do not expect them to be negative in any case.
This is a follow up to investigation in https://colab.research.google.com/drive/1Ny6sUEeXtvyjroPCMlQeOUVSWbDWPYF3?usp=sharing
=> Bug 1783427 - GLAM ETL: filter out negative values in aggregate queries

dags/bqetl_unified.py, sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v1/metadata.yaml
`telemetry_derived.rolling_cohorts_v1` and `telemetry_derived.cohort_daily_statistics_v1` have been missing data after 2022-07-04 ([bug 1784372](https://bugzilla.mozilla.org/show_bug.cgi?id=1784372)), which turns out to be due to the `bqetl_unified.telemetry_derived__rolling_cohorts__v1` task not getting the same `date_partition_offset` as its upstream tables in #3069.
1. Merge PR and wait for CI to complete.
2. Re-run `bqetl_unified.telemetry_derived__rolling_cohorts__v1` Airflow task and downstream tasks from 2022-07-06 to date.
---
=> Set `telemetry_derived.rolling_cohorts_v1` date partition offset to match upstream tables (bug 1784372)

sql/moz-fx-data-shared-prod/search/firefox_products_search_clients_engines_sources_daily/view.sql
The [Looker dashboards](https://mozilla.cloud.looker.com/dashboards/430) are very slow and some are broken as each tile processes around 20k GB of data. 
This PR is the 1st step, creating a view, toward implementing a more efficient solution. 
The PR will be followed by exposing the view as a Looker explore and letting Looker do the heavy lifting of defining GROUP BY  expressions
=> Add mobile + desktop view for ease of calculating days of use

sql/moz-fx-data-shared-prod/mozilla_vpn/deletion_request/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn/events/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn/main/view.sql
This is an attempt to fix the generation of `mozilla_vpn/explores/main.explore.lkml`, `mozilla_vpn/views/main.view.lkml`, `mozilla_vpn/explores/deletion_request.explore.lkml`, and `mozilla_vpn/views/deletion_request.view.lkml` in [looker-hub](https://github.com/mozilla/looker-hub/tree/main/mozilla_vpn), which [got deleted](https://github.com/mozilla/looker-hub/commit/6ff45902a248d0151dd259c49771bf27beaa19e4#diff-9a13687d374409d7375c5752b9bf34e57673d21eebe6cd43e09dec724778e730) after #3140 & #3149 for [DENG-210](https://mozilla-hub.atlassian.net/browse/DENG-210).  I think this is because the views didn't match the `schema.yaml` files which include the `metrics` column.
---
in the logs of the `manual-trigger-required-for-fork` CI task together with more detailed …
=> Include `metrics` column in VPN Glean unified views (DENG-210)

sql/moz-fx-data-shared-prod/mozilla_vpn/deletion_request/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn/events/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn/main/view.sql
Fix-up for #3140.
Some `client_info` and `metadata.header` fields are in a different order in the VPN Android client ping tables, but since all the fields involved are strings the unions didn't fail, they just resulted in wrong data being selected.
---
=> Fix VPN unified views to use exact same schema (DVPN-187)

sql/moz-fx-data-shared-prod/mozilla_vpn/events_unnested/view.sql, sql_generators/glean_usage/templates/cross_channel_events_unnested.view.sql
While investigating [DVPN-187](https://mozilla-hub.atlassian.net/browse/DVPN-187) "Client info appears to not be properly integrated in the main tables" I discovered that the `mozilla_vpn.events_unnested` view is selecting wrong `client_info` and `metadata.header` fields from `org_mozilla_firefox_vpn.main` due to differences in the underlying table schemas.
I then also checked the other `events_unnested` views and found a similar problem where the `fenix.events_unnested` view is selecting wrong `client_info` fields from `org_mozilla_fenix.events` and `org_mozilla_fenix_nightly.events`.
This PR will fix both problems.
---
For modifications to schemas in restricted …
=> Fix `events_unnested` views to consistently select the correct fields

bigquery_etl/cli/query.py, bigquery_etl/cli/utils.py
This will allow dry runs from `mozdata`, like:
`./bqetl query validate --use-cloud-function=false --project-id=mozdata moz-fx-data-shared-prod.contextual_services.event_aggregates`
For example, DS don't have permissions for running queries in moz-fx-data-shared-prod, so they need to use mozdata.
=> Allow dry runs from mozdata

bigquery_etl/cli/__init__.py, bigquery_etl/cli/query.py, bigquery_etl/static.py, script/publish_static, sql/moz-fx-data-shared-prod/static/README.md
Depends on https://github.com/mozilla/telemetry-airflow/pull/1545
Related to https://github.com/mozilla/bigquery-etl/issues/3080
This moves the `publish_static` script into the bqetl CLI. The script logic is left unchanged, but this is necessary for splitting out the bqetl tooling from the query definitions in the future.
=> Move static publish script to CLI

dags/bqetl_monitoring.py, sql/moz-fx-data-shared-prod/monitoring_derived/stable_and_derived_table_sizes_v1/metadata.yaml
To allow all derived tables to get populated for the date.
Currently the Airflow task waits for `copy_deduplicate`, which works for stable tables but not the derived tables.  For example, on 2022-08-18 the task for `telemetry_derived.event_events_v1` was failing but because the task for `monitoring_derived.stable_and_derived_table_size_v1` isn't configured to wait for derived table tasks it went ahead and ran when `telemetry_derived.event_events_v1` contained no data for 2022-08-17 ([bug 1787922](https://bugzilla.mozilla.org/show_bug.cgi?id=1787922)).
A more comprehensive solution could be to configure all derived table tasks as upstream of `monitoring_derived.stable_and_derived_table_size_v1`, but that seems like it'd be pretty complex.
---
in the logs of the …
=> Delay `monitoring_derived.stable_and_derived_table_size_v1` by 1 day (bug 1787922)

sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v1/inti.sql
=> bug(1786733): added init.sql for docker_fxa_admin_server_sanitized_v1

bigquery_etl/cli/routine.py, bigquery_etl/cli/utils.py, tests/cli/test_cli_utils.py
and run isort on touched files
=> Fix exception for requiring auth with no default project

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_events_v1/query.sql
It changed type from string to float in recent `moz-fx-fxa-prod-0712.fxa_prod_logs.docker_fxa_auth_20*` tables, which is breaking the `fxa_auth_events` ETL (bugs [1791061](https://bugzilla.mozilla.org/show_bug.cgi?id=1791061), [1791062](https://bugzilla.mozilla.org/show_bug.cgi?id=1791062)), and it isn't populated for `amplitudeEvent` records anyway.
This is a follow-on from #3229, where the same problem happened with the `jsonPayload.fields.id` column.
I've now manually verified that the ETL should run successfully in this state targeting the existing `fxa_auth_events_v1` table schema.
--- …
=> Ignore `jsonPayload.fields.metricsoptoutat` column for `fxa_auth_events` (bugs 1791061, 1791062)

dags/bqetl_subplat.py, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/active_subscription_ids_v1/metadata.yaml
While the ETL doesn't depend on its own previous runs, other ETLs are built on the assumption that it's built sequentially day-by-day with no gaps.
---
=> Enable `depends_on_past` for `mozilla_vpn_derived.active_subscription_ids` ETL.

sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.init.sql, sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.query.sql, sql_generators/glean_usage/templates/macros.sql
We started seeing a large number of duplicates inside one of our datasets which started to cause ETL failures. This should ensure that this specific table only has a single entry per user.
=> bug(1788650): Added dedup step at the end of the query to ensure we only end up with a single entry per client_id

bigquery_etl/dryrun.py
Seems to be returning 500, but suspect an error related to not being able to access the table from the other GCP project.
=> added docker_fxa_customs_sanitized_v1.init.sql to dry run exception accessing different project

dags/bqetl_monitoring_airflow.py, sql/moz-fx-data-shared-prod/monitoring/airflow_dag/view.sql, sql/moz-fx-data-shared-prod/monitoring/airflow_dag_run/view.sql, sql/moz-fx-data-shared-prod/monitoring/airflow_dag_tag/view.sql, sql/moz-fx-data-shared-prod/monitoring/airflow_slot_pool/view.sql, sql/moz-fx-data-shared-prod/monitoring/airflow_task_fail/view.sql, sql/moz-fx-data-shared-prod/monitoring/airflow_task_reschedule/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_run_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_run_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_run_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_tag_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_tag_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_tag_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_slot_pool_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_slot_pool_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_slot_pool_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_fail_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_fail_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_fail_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_reschedule_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_reschedule_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_reschedule_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_user_v1/init.sql, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_user_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/airflow_user_v1/query.sql
It seems otherwise the generated DAG attempts to pass date param and results in the following error:
```
Cannot add storage to a non-partitioned table with a partition reference
```
=> bug: Forcing date param to be null

bigquery_etl/query_scheduling/task.py, tests/query_scheduling/test_task.py
=> truncating task_name to 62 characters to match the limit to allow longer dataset names derived from sql path

sql/moz-fx-data-shared-prod/dev_telemetry_derived/dataset_metadata.yaml
This intends to create a `moz-fx-data-shared-prod.dev_telemetry_derived` dataset in order to test out recent changes made on Glam ETL without overwriting Prod tables. I intend to delete this dataset after the tests.
A "dev" dataset under a "prod" project doesn't sound great. I picked such option (vs different project) because [Glam dags are already friendly to dataset parametrization](https://github.com/mozilla/telemetry-airflow/blob/36c816aeaab8f3b91c44bc955f75d5f09ce471ae/dags/glam_subdags/generate_query.py#L11)
=> Create dev_telemetry_derived dataset for testing Glam Dev ETL

sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_attribution_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_attribution_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_device_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_device_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/query.sql
This PR updated the active_users_aggregates_* tables to query unified_metrics view and adds more meaningful documentation about the table.
=> DENG-430 Update aggregates to query view

sql/moz-fx-data-shared-prod/monitoring_derived/column_size_v1/query.py
There seems to be a bug in Airflow that is triggered by this task: https://github.com/apache/airflow/issues/20966
```
File "/usr/local/lib/python3.7/site-packages/airflow/providers/cncf/kubernetes/utils/pod_launcher.py", line 148, in monitor_pod
timestamp, message = self.parse_log_line(line.decode('utf-8'))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 41: invalid continuation byte
```
This seems to be cause by certain logs. Removing logging for the time being so that this might get resolved
=> [Bug 1795092] Remove logging from column_size_v1

sql/moz-fx-data-shared-prod/telemetry_derived/suggest_clients_daily_v1/query.sql
This table is currently empty, and this will fix that. I confirmed that this will now return results:
```
SELECT 
COUNT(1)
FROM
`moz-fx-data-shared-prod.telemetry.clients_daily`
WHERE
submission_date = '2022-10-15'
--Suggest is only available for the following clients:
AND country = "US"
AND locale LIKE "en%"
AND browser_version_info.major_version >= 92
AND browser_version_info.version NOT IN ('92', '92.', '92.0', '92.0.0')
```
=> Fix typo in suggest_clients_daily_v1 query

sql_generators/glean_usage/templates/metrics_templating.yaml
This PR is to include Focus Android in the sql-generators template that retrieves the metrics data.
The columns required (`is_default_browser` and `uri_count`) are available in the source view `org_mozilla_focus.metrics`.
More details on [DENG-437](https://mozilla-hub.atlassian.net/browse/DENG-437).
=> DENG-437. Update template for sql_generators

bigquery_etl/cli/query.py
Currently, some metadata (friendly name, description, labels) isn't attached to new or existing derived tables in BigQuery. This PR makes it so new tables get metadata attached when created via `bqetl query schema deploy`. 
I'll add an inline question about whether we should update metadata on every schema deploy rather than just on create. 
Also a few cleanup tasks like closing temp file.
---
=> Add more metadata on query schema deploy create case

bigquery_etl/cli/query.py
Follow up to https://github.com/mozilla/bigquery-etl/pull/3324 - update metadata along with schema deploys. We can use this to progressively backfill tables and ensure metadata stays up to date whenever a schema changes.
---
=> Update metadata on every schema deploy

bigquery_etl/cli/query.py
=> Fix #3303: Add support to backfill monthly partition tables

README.md
docs: Tweaking Apple Silicon comment to red to make it more prominent
The objective is to make sure that this stands out and hopefully results in the first thing being read and taken action upon.
=> docs: Tweaking Apple Silicon comment to red to make it more prominent

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_live/view.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_v1/schema.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_product_page_to_subscribed_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_product_page_to_subscribed_v1/schema.yaml
With VPN+Relay bundle subscriptions now being included in VPN ETL (#3345) it's important that we be able to differentiate between the VPN-only and VPN+Relay bundle products in reports.  To facilitate that, this adds a `product_name` column to the VPN aggregate tables `channel_group_proportions` and `funnel_product_page_to_subscribed` (other applicable aggregate tables like `active_subscriptions` and `subscription_events` already include a `product_name` column).
Since none of the tables being changed are huge I plan to add/backfill the `product_name` columns by manually running the following queries to overwrite the entire table:
- `mozilla_vpn_derived.channel_group_proportions_v1`
```sql
SELECT
subscription_start_date,
country_name,
utm_medium,
utm_source,
utm_campaign,
utm_content, …
```
=> Add product name to VPN aggregate tables (DS-2185)

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_auth_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_content_events_v1/query.sql
Also, removed the field from `fxa_log_content_events` as the source table used does not have `device_id` or `deviceid` field.
=> bug: making sure device_id is hashed in fxa_log_auth_events

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_log_auth_events_v1/query.sql
bug: Removed device_id duplication in fxa_log_auth_events query
=> bug: Removed device_id duplication in fxa_log_auth_events query

sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_auth_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_content_events_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_stdout_events_v1/query.sql
=> feat(DENG-537): tweaked fxa queries to support partitioned tables instead of sharded tables - STAGING

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_events_v1/query.sql
=> bug(DENG-462): letting through some of ios sync events in the fxa_auth_events query

dags/bqetl_newtab.py, dags/bqetl_unified.py, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/schema.yaml
Additional segmentation for newtab data. Note that the legacy client id and Glean client id are different. This will only fill in client profile and segment info for Glean data that has a legacy client identifier attached.
---
=> RS-392 - Added new profiles and activitysegment via unified_metrics

sql/mozfun/glean/parse_datetime/metadata.yaml, sql/mozfun/glean/parse_datetime/udf.sql, sql_generators/stable_views/__init__.py
Datetime metrics are stored in BigQuery tables as strings, which is not very user friendly.  This will change the generated stable views to replace those string fields with timestamp fields, while still providing the original string values in fields prefixed with `raw_`.  For example, a `metrics.datetime.foo` string field would be replaced with a timestamp field, and the string value would be available in an additional `metrics.datetime.raw_foo` field.
Note that despite the title of the bug, we're parsing the datetime metrics as _timestamps_ to preserve their accuracy in representing an exact point in time.  However, all BigQuery timestamps are inherently in UTC, so the original time zone isn't readily available, but could be retrieved from the original string value if needed.
--- …
=> Have Glean stable views parse datetime metrics as timestamps (bug 1771733)

sql/moz-fx-data-shared-prod/firefox_ios/dataset_metadata.yaml
Undoes the metadata changes in #3347 except for the description and friendly name
=> Fix metadata for firefox_ios dataset

bigquery_etl/schema/__init__.py, sql_generators/stable_views/__init__.py
After #3343 `schema.yaml` files are failing to be generated for the Glean stable views because the step to merge Glean stable table schemas with their view schemas is failing due to the datetime metric column types being different.  That schema merge is only being done to copy the column descriptions to the view, so this tweaks that schema merge logic to only copy the `description` attributes (ignoring other attributes like `type`).
---
=> Only merge descriptions from Glean stable table schemas to views

sql/moz-fx-data-shared-prod/telemetry_derived/deanonymized_events/view.sql
Follow up to https://github.com/mozilla/bigquery-etl/pull/3401. This should fix [telemetry_derived.events_daily_v1](https://workflow.telemetry.mozilla.org/log?dag_id=bqetl_event_rollup&task_id=telemetry_derived__events_daily__v1&execution_date=2022-12-02T03%3A00%3A00%2B00%3A00) that crashed during the weekend most likely due to increased volume of events sent from Normandy.
=> Bug 1803833 - Filter out Normandy invalid-feature events from deanonymized_events view

sql/moz-fx-data-shared-prod/udf/bits_to_days_since_first_seen/udf.sql, sql/moz-fx-data-shared-prod/udf/bits_to_days_since_seen/udf.sql
The interim bits algorithm which unnested an array, one value per-bit, was extremely slow.
This new algorithm is roughly 300x faster on large datasets.
=> Use fast versione of bytes algorithm

docs/cookbooks/common_workflows.md
This is now required since https://github.com/mozilla/bigquery-etl/pull/3143
An alternative to this would be making `--force` also skip dryruns. That seems like it should be okay but I don't have strong thoughts about it.
=> Update docs, Deploying clients_last_seen now requires skipping dryrun

bigquery_etl/cli/query.py
=> Prevent bqetl query schema deploy to deploy views with schema.yaml

sql/moz-fx-data-shared-prod/fenix/attributable_clients/view.sql, sql/moz-fx-data-shared-prod/fenix/marketing_attributable_metrics/view.sql
References in views need to be fully qualified. The main reason is that views get deployed to both `shraed-prod` and `mozdata`, but in `mozdata` the `_derived` datasets do not exist. Also there is a CI check that is failing
=> Add project ID qualifiers to Fenix views

requirements.txt
Update wheel hash for yamllint
This wheel was published on 2022-10-11.
This was documented in https://github.com/adrienverge/yamllint/issues/501
The hash is taken from https://pypi.org/project/yamllint/
=> Deps: Update wheel hash for yamllint

dags/bqetl_fxa_events.py, sql/moz-fx-cjms-prod-f3c7/cjms_bigquery/flows_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts/fxa_all_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/funnel_events_source_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/init.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_daily_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_daily_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v1/init.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_product_page_to_subscribed_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/fxa_attribution_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/login_flows_v1/query.sql
This is part 2 to deprecate the following views:
- `firefox_accounts.fxa_content_auth_events`
- `firefox_accounts.fxa_content_auth_oauth_events`
- `firefox_accounts.fxa_content_auth_stdout_events`
This PR depends on PR#3407, once it has been merged this PR can be rebased and reviewed.
Related PR links:
- Part 1: https://github.com/mozilla/bigquery-etl/pull/3407
- Part 2: https://github.com/mozilla/bigquery-etl/pull/3408
- Part 3: https://github.com/mozilla/bigquery-etl/pull/3409
----
The next step will be to wait until the new deprecation process in in place and then continue this deprecation with:
- Part 4: Changing the fxa event views to be deprecated to throw an error when queried (comment out the existing logic and add select ERROR(deprecation error))
- Part 5: After a time period …
=> feat(DENG-582): Updated fxa_content_* references to use fxa_all_events view instead

dags/bqetl_fxa_events.py, sql/moz-fx-cjms-prod-f3c7/cjms_bigquery/flows_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts/fxa_all_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_oauth_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/funnel_events_source_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/init.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_daily_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_daily_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v1/init.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_product_page_to_subscribed_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/fxa_attribution_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/login_flows_v1/query.sql
This is part 3 to deprecate the following views:
- `firefox_accounts.fxa_content_auth_events`
- `firefox_accounts.fxa_content_auth_oauth_events`
- `firefox_accounts.fxa_content_auth_stdout_events`
This PR depends on PR#3408, once it has been merged this PR can be rebased and reviewed.
Related PR links:
- Part 1: https://github.com/mozilla/bigquery-etl/pull/3407
- Part 2: https://github.com/mozilla/bigquery-etl/pull/3408
- Part 3: https://github.com/mozilla/bigquery-etl/pull/3409
----
The next step will be to wait until the new deprecation process in in place and then continue this deprecation with:
- Part 4: Changing the fxa event views to be deprecated to throw an error when queried (comment out the existing logic and add select ERROR(deprecation error))
- Part 5: After a time period …
=> feat(DENG-582): Updated fxa_content_* views to include deprecation notice comment

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_last_seen_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_last_seen_v1/schema.yaml
`timestamp` field can contain a value which corresponds to a day in the past. Fixing this by setting the value of the field by which the table is partitioned to be equal the the partition processed by bqetl.
=> bug: fixing partition field containing value for multiple partitions error

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_table_storage_timeline_daily_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_table_storage_timeline_daily_v1/schema.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_table_storage_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_table_storage_v1/schema.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_tables_inventory_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v1/query.py
The tables are used for monitoring data usage and storage costs.   More clarity is added to the schema to allow better understanding for column fields and source tables.
=> Added more definitions and clarity to schema

bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2, dags/bqetl_public_data_json.py, tests/data/dags/test_public_data_json_dag
@scholtzan I'm not sure how the CI works for this repo, but this is the fix. (e.g. maybe i dont need to update the dags file because it gets rendered from a template into another branch?) idk. but please r
=> Replace references of deprecated custom task_sensor with upstream airflows externaltasksensor

bigquery_etl/cli/query.py
This PR makes some improvements to unblock table deploys:
If a deploy fails for some table, then this changes ensures that the deploys for the remaining tables will keep running instead of stopping immediately.
=> Don't stop updating and deploying schemas if one has failed

sql/mozfun/glean/parse_datetime/metadata.yaml, sql/mozfun/glean/parse_datetime/udf.sql, sql_generators/stable_views/__init__.py
This reapplies #3343, which was temporarily reverted in #3394 because it had the unfortunate side effect of causing the `search_derived.mobile_search_clients_daily_v1` ETL query to exceed the query complexity limit in the `moz-fx-data-shared-prod` project ([bug 1803534](https://bugzilla.mozilla.org/show_bug.cgi?id=1803534)).
Now the query complexity limit in the `moz-fx-data-shared-prod` project has been [increased](https://console.cloud.google.com/support/cases/detail/v2/42514957?project=moz-fx-data-shared-prod), and I've confirmed that the `search_derived.mobile_search_clients_daily_v1` ETL won't exceed the query complexity limit with this change applied.
--- …
=> Reapply "Have Glean stable views parse datetime metrics as timestamps (bug 1771733) (#3343)"

sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox/unified_metrics_v1/query.py
As a result of #3453 the `org_mozilla_ios_firefox.unified_metrics` ETL is failing ([bug 1805485](https://bugzilla.mozilla.org/show_bug.cgi?id=1805485)) because the generated legacy telemetry subqueries contain a Glean datetime metric column as a string (based on the stable table schema) while the Glean metrics view now selects the datetime metric column as a timestamp.
This changes the generated legacy telemetry subqueries to apply the `mozfun.glean.parse_datetime()` function to the column (even though the column contains no data), like the Glean metrics view does.
---
=> Fix Firefox iOS `unified_metrics` view (bug 1805485)

.yamllint.yaml
I don't know what the best length is, the default 80 characters max has been causing some friction. We can double it for now and see.
=> Increase yamllint max line length

bigquery_etl/query_scheduling/templates/airflow_dag.j2
Python doesn't allow dashes in variable names and some of our Airflow task IDs contain dashes.  If a task ID containing dashes is referenced in an ETL's `depends_on` config then it would currently generate invalid Python and DAG generation would fail with an error.  This fixes that.
---
=> Fix DAG generation error when dependency task ID contains dashes

bigquery_etl/query_scheduling/dag.py
In particular, this will allow the correct `repo/private-bigquery-etl` tag to be configured for DAGs in the [private-bigquery-etl](https://github.com/mozilla/private-bigquery-etl) repo.
---
=> Allow default `repo/bigquery-etl` DAG tag to be overridden

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_all_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts_derived/funnel_events_source_v1/metadata.yaml
This is due to the fact that oauth log event table no longer exists and has been merged into auth server/event log. This change aims to reflect this change.
=> feat(DENG-609): Added extra note in fxa_all_events around oauth events

dags/bqetl_analytics_tables.py, sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/metadata.yaml
Correct the query parameter for DAG runs and backfill for `fenix.firefox_android_clients`.
=> DENG-178 Backfill query parameter

dags/bqetl_analytics_tables.py, sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/metadata.yaml
Fixed DAG run, looking ofr parameter "None".
=> DENG-178 set date_partition_parameter as null

bigquery_etl/query_scheduling/templates/airflow_dag.j2, dags/bqetl_cjms_nonprod.py, dags/bqetl_monitoring_airflow.py, dags/bqetl_subplat.py, tests/data/dags/simple_test_dag
And use the [`airflow-provider-fivetran` package](https://github.com/fivetran/airflow-provider-fivetran)'s new feature to pass the timestamp of the last sync from the Fivetran operator to the Fivetran sensor via XCom so the sensor doesn't miss syncs that finish before it can check.
`airflow-provider-fivetran` 1.1.2 was recently installed ([DSRE-921](https://mozilla-hub.atlassian.net/browse/DSRE-921)), making this possible.
CCing other DAG owners for visibility: @kik-kik 
---
=> Use the `airflow-provider-fivetran` package instead of our backport

bigquery_etl/query_scheduling/templates/airflow_dag.j2, dags/bqetl_cjms_nonprod.py, dags/bqetl_monitoring_airflow.py, dags/bqetl_subplat.py, tests/data/dags/simple_test_dag
We use an [Airflow operator & sensor provided by Fivetran](https://github.com/fivetran/airflow-provider-fivetran), where the operator starts a Fivetran sync and the sensor monitors the sync until it completes.  The problem is when a Fivetran sync fails for some reason the Airflow sensor task will fail and possibly retry, but unless the Airflow operator task is also retried the Fivetran sync won't be restarted so the retried sensor won't find a sync and will ultimately fail again.
This PR adds a retry callback to Fivetran sensor tasks to also clear the associated Fivetran operator task when the sensor is being retried.
This should wait until #3479 and mozilla/telemetry-airflow#1629 are merged (and this PR will be re-targeted to the `main` branch at that point).
CCing other DAG owners for …
=> Retry Fivetran syncs when they fail

bigquery_etl/query_scheduling/templates/airflow_dag.j2, dags/bqetl_cjms_nonprod.py, dags/bqetl_monitoring_airflow.py, dags/bqetl_subplat.py, tests/data/dags/simple_test_dag
Using a poke interval of 5 seconds means only 7 Fivetran sensors polling for an hour would exceed [Fivetran's rate limit](https://fivetran.com/docs/rest-api/rate-limiting) of 5,000 API requests per hour.  Increasing the poke interval to 30 seconds will allow for up to 41 Fivetran sensors polling for an hour.
This should wait until #3480 is merged (and this PR will be re-targeted to the `main` branch at that point).
CCing other DAG owners for visibility: @kik-kik
---
=> Increase Fivetran sensors' poke interval to 30 seconds

bigquery_etl/query_scheduling/dag.py, bigquery_etl/query_scheduling/templates/airflow_dag.j2
To support more accurate DAG generation for the [private-bigquery-etl](https://github.com/mozilla/private-bigquery-etl/) repo.
---
=> Allow DAG repo to be configured

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_oauth_events/view.sql, sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql
revert: fxa_content_* views commented out where clause raising error
This is due to  Looker dashboards breaking, once they have been migrated this will be done again.
=> revert: fxa_content_* views commented out where clause raising error

sql/moz-fx-data-shared-prod/relay_derived/subscription_events_live/view.sql
A non-aggregated column was accidentally omitted from the `GROUP BY` clause in #3482.
---
=> Fix `relay_derived.subscription_events_live` view

bigquery_etl/dependency.py, dags/bqetl_fog_decision_support.py, dags/bqetl_main_summary.py, dags/bqetl_sponsored_tiles_clients_daily.py
While we don't want people to reference such views in `mozdata` and will be removing existing references to such views (#3496), if people do reference them then the task dependencies should still be generated correctly.
---
=> Fix bug generating task dependencies when queries reference stable views in `mozdata`

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_content_events_v1/query.sql
This is because it appears the partitioned version of the table is partially missing data. There is an open issue for this and will be investigated by the right engineer. Until then we will continue using the sharded table.
=> bug(FXA-6593): reverted fxa_content_events query to use sharded table
