mozilla/bigquery-etl

- sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2102)
> Update dataset_metadata.yaml for broken site reports

- sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2109)
> Fix jinja templating in glean usage metadata

- sql/moz-fx-data-shared-prod/telemetry/socorro_crash/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2143)
> DSRE-1488 - Authorize view and add workgroup access for taskcluster

- CODEOWNERS
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2148)
> DENG-1352 - Temporarily add curtis to CODEOWNERS until he can be added to group

- sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2159)
> Remove referenced_table from firefox_android_clients

- sql/moz-fx-data-shared-prod/telemetry_derived/crash_signatures_v1/query.py
- sql/moz-fx-data-shared-prod/telemetry_derived/crash_symbols_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2184)
> DENG-965 - Fix crash processing scripts incorrectly assuming submission_date is a string

- sql/mozfun/mobile_search/normalize_app_name/udf.sql
Should fix UDF deploys
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2187)
> Mark tests for mobile_search.normalize_app_name

- sql/moz-fx-data-shared-prod/firefox_desktop/newtab_live/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop/newtab_live/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2186)
> MSDO-65 adding live view on glean fx new tab live table

- sql/moz-fx-data-shared-prod/search/mobile_search_clients_engines_sources_daily/view.sql
- sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2189)
> Add normalized engine to mobile search daily table

- sql/mozfun/mobile_search/normalize_app_name/udf.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2192)
> Fix normalize search udf

- sql/moz-fx-data-shared-prod/dap_collector_derived/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2197)
> FXCTO-13 Add dataset for DAP Collector data

- sql/moz-fx-data-shared-prod/mdn_rumba/dataset_metadata.yaml
This was missed in #4663 and makes docs fail
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2213)
> Add missing description for mdn_rumba syndication dataset

- sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2247)
> Fix bq function name

- bqetl_project.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2257)
> Skip all fxa_accounts in dryrun 

- dags.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2284)
> DENG-2262 - Fixing bqetl_desktop_installs_v1 DAG start time

- sql_generators/use_counters/templates/query_fenix.sql
- sql_generators/use_counters/templates/query_ff_desktop.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2288)
> 1866834 - use counters v2 - fix small bug in regex formula

- sql/moz-fx-data-shared-prod/fenix_derived/fenix_use_counters_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/firefox_desktop_use_counters_v1/query.sql
- sql_generators/use_counters/templates/query_fenix.sql
- sql_generators/use_counters/templates/query_ff_desktop.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2289)
> 1866834 - Use Counter Tables - Update Usage Rate Formula

- bigquery_etl/cli/__init__.py
- bigquery_etl/cli/alchemer.py
- bigquery_etl/cli/dag.py
- bigquery_etl/cli/dryrun.py
- bigquery_etl/cli/format.py
- bigquery_etl/cli/generate.py
- bigquery_etl/cli/query.py
- bigquery_etl/cli/routine.py
- bigquery_etl/cli/stage.py
- bigquery_etl/cli/view.py
- bigquery_etl/dependency.py
- bigquery_etl/docs/__init__.py
- bigquery_etl/glam/cli.py
- bigquery_etl/static.py
- bigquery_etl/stripe/__init__.py
- bigquery_etl/subplat/apple.py
- requirements.in
- requirements.txt
- tests/test_entrypoint.py
Add [`rich_click`](https://github.com/ewels/rich-click) to Bqetl CLI. Excluded `copy_deduplicate` because it mostly runs in Airflow.
> Bqetl on rich-click ✨💸

- sql/moz-fx-data-shared-prod/subscription_platform_derived/apple_subscriptions_v1/query.sql
The existing Apple subscription ETL logic can incorrectly associate Apple subscription trial periods with later unrelated subscription periods, making it look like such later subscriptions started when the previous trial ended, when in fact there was a gap in the user's subscription.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2296)
> Correlate Apple subscription trial periods with the specific subscription period they occurred in

- dags.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_metrics_summary_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2306)
> Update bqetl_google_analytics_derived_ga4 yaml configs

- sql_generators/use_counters/templates/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2340)
> 1866834 - add public BQ flag to 2 sql generated use counter tables

- sql_generators/use_counters/templates/query_fenix.sql
- sql_generators/use_counters/templates/query_ff_desktop.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2342)
> 1866834 - Update usage rate formula to include deprecated metrics

- sql/moz-fx-data-shared-prod/fenix/fenix_use_counters/view.sql
- sql/moz-fx-data-shared-prod/fenix_derived/fenix_use_counters_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop/firefox_desktop_use_counters/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/firefox_desktop_use_counters_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry/fenix_and_firefox_use_counters/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2347)
> 1866834 - deprecate V1 versions and update view to use new V2 tables

- sql/moz-fx-data-shared-prod/fenix/fenix_use_counters/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop/firefox_desktop_use_counters/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2351)
> 1866834 - Use Counter Views - Re-add 2 views

- sql/moz-fx-data-shared-prod/telemetry_derived/active_users_aggregates_v1/metadata.yaml
Deprecate telemetry_derived.active_users_aggregates_v1, as this table has been replaced by new versions per-browser in [DENG-682](https://mozilla-hub.atlassian.net/browse/DENG-682).
[DENG-682]: https://mozilla-hub.atlassian.net/browse/DENG-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2350)
> Deprecated active_users_aggregates_v1.

- sql_generators/use_counters/templates/query_fenix.sql
- sql_generators/use_counters/templates/query_ff_desktop.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2353)
> 1866834 - update usage rate formula for use.counter.doc metrics

- bigquery_etl/cli/query.py
- tests/cli/test_cli_query.py
Closes https://github.com/mozilla/bigquery-etl/issues/4532
> Support backfilling unpartitioned tables and non-date query parameters

- sql_generators/glean_usage/templates/baseline_clients_daily_v1.query.sql
To match the clustering config in the associated `metadata.yaml` files and the currently deployed tables.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2362)
> Correct `baseline_clients_daily` clustering config in `init.sql` files

- sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v1/metadata.yaml
Reverts mozilla/bigquery-etl#4738
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2383)
> Revert "start deprecation process by editing the metadata.yaml file"

- sql/moz-fx-data-shared-prod/telemetry_dev_cycle/data_review_stats/view.sql
[ticket](https://mozilla-hub.atlassian.net/browse/DENG-1729)
adding a view without any additional logic
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2389)
> DENG-1729 add data-review-stats view to telemetry dev cycle

- sql_generators/glean_usage/templates/event_flow_monitoring_aggregates_v1.metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2391)
> [Bug 1874442] Fix event_flow_monitoring metadata template

- sql/moz-fx-data-shared-prod/monitoring_derived/structured_detailed_error_counts_v1/view.sql
There is now a `structured_error_counts_v2`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2392)
> Fix references in structured_detailed_error_counts

- sql_generators/glean_usage/templates/events_stream_v1.query.sql
To unblock table deploys
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2413)
> Remove duplicate sample_id from events stream tables

- sql_generators/use_counters/templates/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2423)
> Bug: 1866834 - Add public json = true flag

- sql_generators/use_counters/templates/metadata.yaml
> 1866834 - remove flag

- bigquery_etl/shredder/config.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2401)
> feat(DENG-1776): added fenix client funnels to shredder config

- bigquery_etl/shredder/config.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2430)
> feat(DENG-2086): added firefox_ios_derived.firefox_ios_clients_v1 to shredder config

- sql_generators/use_counters/templates/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2435)
> 1866834 - add public json true flag

- sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2438)
> add  deprecated: true to metadata.yaml to deprecate bigquery_usage_v1

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_metrics_summary_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2455)
> WWW Site Metrics Summary V2 - update query logic

- bigquery_etl/cli/backfill.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2461)
> Use rich for backfill CLI

- sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v2/query.sql
The `fxa_delete_events` ETLs have been looking for log messages with `type = 'activityEvent'` and `fields.event = 'account.deleted'` which are normally recorded when someone deletes their own account ([code](https://github.com/mozilla/fxa/blob/e54ec667ad1a5fa0309f54e74667074379ded1f1/packages/fxa-auth-server/lib/routes/account.ts#L1838)).
However, those log messages won't be recorded in a few scenarios:
1. If the user opted out of FxA data collection ([code](https://github.com/mozilla/fxa/blob/3da48c22935d2b8d8ea843bf03a0f9919f29d1db/packages/fxa-auth-server/lib/metrics/events.js#L113-L115)).
2. If the `delete-account.ts` script is used ([code](https://github.com/mozilla/fxa/blob/3da48c22935d2b8d8ea843bf03a0f9919f29d1db/packages/fxa-auth-server/scripts/delete-account.ts#L166-L168)).
3. If …
> Look for additional FxA deletion events (DENG-2422)

- sql/mozfun/ltv/android_states_v2/metadata.yaml
- sql/mozfun/ltv/android_states_v2/udf.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2471)
> Add android_states_v2 function

- sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v2/query.sql
I found two more cases where accounts could be deleted with log messages different than the ones `fxa_delete_events_v2` currently looks for ([code](https://github.com/mozilla/fxa/blob/e54ec667ad1a5fa0309f54e74667074379ded1f1/packages/fxa-auth-server/lib/routes/emails.js#L661-L664), [code](https://github.com/mozilla/fxa/blob/e54ec667ad1a5fa0309f54e74667074379ded1f1/packages/fxa-auth-server/lib/routes/utils/account.ts#L39-L42)).
---
[DENG-2422]: https://mozilla-hub.atlassian.net/browse/DENG-2422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> Look for even more FxA deletion events (DENG-2422)

- sql/moz-fx-data-marketing-prod/ga/www_site_hits/view.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2490)
> Create new GA4 www_site_hits_v2 derived table

- sql_generators/glean_usage/templates/events_stream.metadata.yaml
- sql_generators/glean_usage/templates/events_stream_v1.metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2486)
> Bug 1876010 - Call out the tiny gotcha our analysis made clear

- bigquery_etl/cli/query.py
- sql/moz-fx-data-shared-prod/fenix/client_ltv/view.sql
- sql/moz-fx-data-shared-prod/fenix/ltv_state_values/view.sql
- sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v2/checks.sql
- sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v2/query.sql
- sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v2/schema.yaml
- tests/cli/test_cli_query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2489)
> Use state_values_v2 for Android LTV pipeline

- sql/moz-fx-data-marketing-prod/ga/www_site_downloads/view.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2504)
> DENG-2492 - Create new GA4 derived table: www_site_downloads_v2

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2508)
> Minor updates to www_site_downloads_v2 DENG-2492

- sql/moz-fx-data-marketing-prod/ga/www_site_events_metrics/view.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2527)
> DENG-2492 - create new table www_site_events_metrics_v2

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2537)
> DENG-2492 initial commit for fixing exit data

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/schema.yaml
> DENG-2492 Improve metadata for new table www_site_events_metrics_v2

- sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/init.sql
- sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/query.sql
Reverts mozilla/bigquery-etl#4901
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2554)
> Revert "AD-178 quick_suggest query type field"

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2567)
> DENG-2492 - filter out null session IDs

- sql_generators/glean_usage/templates/events_stream_v1.query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2556)
> events stream: Expose additional metrics as a new JSON column

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2569)
> DENG-2492 - update logic for www_site_events_metrics_v2

- .circleci/config.yml
- bigquery_etl/cli/generate.py
- bigquery_etl/cli/metadata.py
- bigquery_etl/cli/query.py
- bigquery_etl/schema/stable_table_schema.py
- sql_generators/glean_usage/__init__.py
- sql_generators/glean_usage/baseline_clients_first_seen.py
- sql_generators/glean_usage/common.py
- sql_generators/glean_usage/event_error_monitoring.py
- sql_generators/glean_usage/event_flow_monitoring.py
- sql_generators/glean_usage/event_monitoring_live.py
- sql_generators/glean_usage/events_stream.py
- sql_generators/glean_usage/events_unnested.py
- sql_generators/glean_usage/glean_app_ping_views.py
- sql_generators/urlbar_events/__init__.py
- tests/cli/test_cli_metadata.py
This is to speed up the `generate-sql` task. With the changes it finishes in about ca 7 min vs the usual 14 min
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2550)
> Speed up generate-sql

- sql/moz-fx-data-marketing-prod/ga/www_site_landing_page_metrics/view.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2591)
> DENG-2492 - create new www_site_landing_page_metrics_v2

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/schema.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v2/query.sql
The definition for a bounce changed from GA3 -> GA4, so updating the logic to match the new GA4 logic, and adding a new column to see what the old GA3 bounce defintion (single page session) was also, in case people still want to look at that metric.  Then also editing the logic in a downstream table.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2604)
> GA4 bounce logic updates - www_site_hits_v2 and www_site_landing_page_metrics_v2

- bigquery_etl/view/__init__.py
- sql_generators/derived_view_schemas/__init__.py
- tests/data/test_sql/moz-fx-data-test-project/test/default/view.sql
- tests/view/test_view.py
Reverts mozilla/bigquery-etl#4848
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2600)
> Revert "Restrict derived view schema generation to views with upstream schema files and directly copy reference schemas for simple views."

- sql/moz-fx-data-shared-prod/moso_mastodon_backend/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/moso_mastodon_backend_derived/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/moso_mastodon_web/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/moso_mastodon_web_derived/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2624)
> Add moso datasets with dbt workgroup access

- bqetl_project.yaml
I re-ordered the list alphabetically.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2637)
> Bug 1875819 - events stream: Add bedrock

- .circleci/config.yml
Typo in circleci
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2665)
> fix typo in CI

- .circleci/config.yml
Tags need to be pushed to `generated-sql`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2669)
> Push tags for commits on generated-sql branch

- sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v2/checks.sql
See https://mozilla-hub.atlassian.net/browse/DS-3102
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2664)
> DS-3102 Add checks to clients_first_seen_v2

- bqetl_project.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/checks.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/query.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2650)
> Deng 2579 gclid conversions v2 creation

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/script.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2686)
> DENG-2492 - fix time_on_site formula to convert to seconds

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/script.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2689)
> DENG-2492 update the product download types and the clustering

- tests/checks/revenue_period_over_period_change.jinja
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2692)
> Adds absolute value to check for unreasonable increase

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2703)
> DENG-2492 fix offsets for page levels, they were all off by 1

- sql/moz-fx-data-marketing-prod/ga/firefox_whatsnew_summary/view.sql
- sql/moz-fx-data-marketing-prod/ga_derived/firefox_whatsnew_summary_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/firefox_whatsnew_summary_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/firefox_whatsnew_summary_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2705)
> DENG-2492 create new GA4 derived table firefox_whatsnew_summary_v2

- sql/moz-fx-data-marketing-prod/ga/blogs_sessions/view.sql
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2734)
> DENG-2492 Create new GA4 derived table: blogs_sessions_v2

- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2740)
> DENG-2492 blogs sessions v2

- bqetl_project.yaml
- sql_generators/glean_usage/event_error_monitoring.py
- sql_generators/glean_usage/event_monitoring_live.py
- sql_generators/glean_usage/templates/event_error_monitoring_aggregates_v1.query.sql
- sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql
- sql_generators/glean_usage/templates/event_monitoring_live_v1.init.sql
https://mozilla-hub.atlassian.net/browse/DENG-2620 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2706)
> Add event monitoring for VPN [DENG-2620]

- sql_generators/events_daily/templates/event_types_history_v1/init.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2751)
> Quote `values` column reference to avoid sqlglot parsing error

- sql/moz-fx-data-shared-prod/telemetry_derived/event_types_history_v1/init.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2752)
> Quote another `values` column reference to avoid sqlglot parsing error

- .circleci/config.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2753)
> Run SQL checks when requirements change

- .circleci/config.yml
- .circleci/workflows.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2758)
> Add parameter to skip stage depoys in CI

- sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v1/query.sql
- sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v1/schema.yaml
update fenix feature usage metrics using the same logic applied to ios feature usage metrics
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2724)
> update fenix feature usage metrics using ping parse time logic

- bigquery_etl/cli/query.py
- bigquery_etl/schema/__init__.py
- tests/schema/test_schema.py
Adds utils for converting from BigQuery schema to local `Schema` and vice-versa.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2757)
> Add BigQuery schema conversion util

- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2773)
> DENG-2492 - remove unnecessary filter from blogs_sessions_v2

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2783)
> DENG-2492 add missing date partition parameter null

- sql/moz-fx-data-marketing-prod/google_search_console_derived/search_impressions_by_page_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/google_search_console_derived/search_impressions_by_site_v2/metadata.yaml
Fixup for #5039.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2786)
> Correct `partition_id` expressions for Google Search Console table partition sensors

- sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2792)
> bug(): Remove browserstack filter as this causes the fenix query to return no results

- sql_generators/search/__init__.py
Generate mobile_search query to file so it doesn't need to be manually exported.
It also helps reading logs as thee query is not printed to stdout e.g. [during Triage](https://workflow.telemetry.mozilla.org/log?dag_id=bqetl_glean_usage&task_id=moso_mastodon_android.moso_mastodon_android_derived__metrics_clients_daily__v1&execution_date=2024-02-14T02%3A00%3A00%2B00%3A00).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2778)
> Generate search query to file in favour of stdout.

- sql/moz-fx-data-shared-prod/firefox_desktop/urlbar_events_daily/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_v1/schema.yaml
Creating PR to replace [this](https://github.com/mozilla/bigquery-etl/pull/4949). 
> Create new table urlbar_events_daily

- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2805)
> DENG-2492 update column metadata

- sql/moz-fx-data-marketing-prod/ga/blogs_landing_page_summary/view.sql
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_landing_page_summary_v2/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_landing_page_summary_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_landing_page_summary_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2804)
> DENG-2492 Create new GA4 derived table: blogs_landing_page_summary_v2

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2824)
> DENG-2577 fix typo in schema

- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_beta_aggregates/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_nightly_aggregates/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_release_aggregates/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_beta_aggregates/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_nightly_aggregates/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_release_aggregates/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_beta_aggregates/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_nightly_aggregates/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_release_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_desktop_beta_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_desktop_nightly_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_desktop_release_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_beta_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_nightly_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_fenix_release_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_fog_beta_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_fog_nightly_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_etl/glam_fog_release_aggregates/metadata.yaml
Adds metadata to production views and grants GLAM access to their syndicated views in `moz-fx-data-shared-prod`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2835)
> Add metadata for GLAM views

- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2850)
> add filter on session_date for backfilling purposes

- .circleci/workflows.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2885)
> Fix validate-routine CI

- sql/moz-fx-data-marketing-prod/ga_derived/blogs_goals_v2/checks.sql
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v2/checks.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/checks.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/checks.sql
Reverts mozilla/bigquery-etl#5102
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2887)
> Revert "DENG-2837 add data checks to new ga4 tables"

- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_last_seen_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2895)
> DENG-2095 Fix accounts_backend.users_services_daily_v1

- sql/moz-fx-data-shared-prod/firefox_accounts/funnel_events_source/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2903)
> feat(): add firefox_accounts.funnel_events_source to version control

- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2904)
> Add estimate for number of devices to accounts_backend.users_services_daily_v1

- .circleci/workflows.yml
This adds a CircleCI step to trigger `bqetl_artifact_deployment` DAG in WTMO after completing the `deploy` job.
Example of DAG triggering with note including context:
[Link to successful job](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/30819/workflows/73d5e209-1333-4b77-a962-c875d04d5d0c/jobs/332851)
https://mozilla-hub.atlassian.net/browse/DSRE-1504
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2910)
> feat(ci): Add artifact-deployment to CircleCI workflows

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_metrics_summary_v2/query.sql
Prior to 2/16/24, filter on platform type = desktop to limit to only Firefox Desktop downloads
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2926)
> DENG-2919 Minor change to product download logic

- sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2939)
> Fix unified metrics check

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2941)
> DENG-2940 Add 2 new columns to www_site_hits_v2

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v2/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2943)
> DENG-2938 Update product download logic to limit to Firefox Desktop downloads only in www_site_landing_page_metrics_v2

- sql/moz-fx-data-marketing-prod/ga_derived/blogs_goals_v2/checks.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v2/checks.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2949)
> DENG-2837 - add 3 new data checks

- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2953)
> DENG-2579 move gclid_conversions_v2 from GA3 dag to GA4 dag

- sql/mozfun/json/from_nested_map/udf.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2984)
> Fix assert function name in UDF test

- sql/moz-fx-data-shared-prod/stub_attribution_service_derived/dl_token_ga_attribution_lookup_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/stub_attribution_service_derived/dl_token_ga_attribution_lookup_v1/moz-fx-stubattribut-prod-32a5.stubattribution_prod.stdout.schema.json
- tests/sql/moz-fx-data-shared-prod/stub_attribution_service_derived/dl_token_ga_attribution_lookup_v1/test_single_day/expect.yaml
- tests/sql/moz-fx-data-shared-prod/stub_attribution_service_derived/dl_token_ga_attribution_lookup_v1/test_single_day/moz-fx-stubattribut-prod-32a5.stubattribution_prod.stdout.yaml
- tests/sql/moz-fx-data-shared-prod/stub_attribution_service_derived/dl_token_ga_attribution_lookup_v1/test_single_day/query_params.yaml
- tests/sql/moz-fx-data-shared-prod/stub_attribution_service_derived/dl_token_ga_attribution_lookup_v1/test_single_day/stub_attribution_service_derived.dl_token_ga_attribution_lookup_v1.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2987)
> DENG-2979 Update dl_token_ga_attribution_lookup_v1 to use new GA4 client ID after switch to GA4

- sql/mozfun/json/from_nested_map/udf.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2991)
> Fix from_nested_map

- bqetl_project.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2733)
> events stream: Deploy for Firefox for Android Beta (the correct app id)

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/schema.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/script.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3016)
> DENG-2944 Add new column for # of Firefox Desktop downloads to ga_sessions_v2

- sql/data-observability-dev/fenix_derived/dataset_metadata.yaml
- sql/data-observability-dev/org_mozilla_firefox_derived/dataset_metadata.yaml
- sql/data-observability-dev/telemetry_derived/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3038)
> feat(DENG-2863): Add data-observability-dev project along with datasets/namespaces nominated for testing

- .circleci/workflows.yml
feat(): Upgrade Python version used for validate-dags step to match telemetry-airflow
depends on: https://github.com/mozilla/telemetry-airflow/pull/1942
related to: https://github.com/mozilla/private-bigquery-etl/pull/362
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3019)
> feat(): Upgrade Python version used for validate-dags step to match telemetry-airflow

- sql/moz-fx-data-shared-prod/mozilla_vpn_derived/site_metrics_summary_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3131)
> DENG-2581 - Small fix to logic in new VPN derived GA4 table

- bqetl_project.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3130)
> Remove dry run skipping for restricted datasets

- dags.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3143)
> fix: add missing impact tag to the bqetl_data_observability_test_data_copy DAG

- sql/moz-fx-data-marketing-prod/ga/www_site_downloads/view.sql
- sql/moz-fx-data-marketing-prod/ga/www_site_metrics_summary/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3163)
> DENG-3162 - limit 2 views to only go back to 10/1/23

- dags.yaml
- sql/moz-fx-data-marketing-prod/acoustic/suppression_list_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/acoustic/suppression_list_v1/query.sql
create a suppression list table consisting of the historic upload and fivetran data 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3164)
> DENG-3161 create full suppression list Accoustic

- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.query.sql
Follow-up for [PR-5225](https://github.com/mozilla/bigquery-etl/pull/5225)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3179)
> Update query template for baseline_clients_last_seen tables.

- sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3190)
> Fix user_reports formatting

- sql/moz-fx-data-shared-prod/ctms_braze/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3196)
> Resolves DSRE-1560 to syndicate ctms mirror of braze

- sql/moz-fx-data-shared-prod/udf_js/main_summary_active_addons/udf.sql
The telemetry_derived__clients_daily__v6 step in bqetl_main_summary  is failing with the following error 
```No matching signature for function udf_js.main_summary_active_addons for argument types: ARRAY<STRUCT<key STRING, value STRUCT<app_disabled BOOL, blocklisted BOOL, description STRING, ...>>>, NULL. Supported signature: udf_js.main_summary_active_addons(ARRAY<STRUCT<key STRING, value STRUCT<app_disabled BOOL, blocklisted BOOL, description STRING, ...>>>, STRING) at [1:9] ```
A new field `signed_types` has been added.
This PR should fix the issue. …
> Fix main summary udf - add signed_types col

- sql/moz-fx-data-shared-prod/billing_syndicate/dataset_metadata.yaml
Jira Ticket: https://mozilla-hub.atlassian.net/browse/OPST-1215
Related PR https://github.com/mozilla-it/global-platform-admin/pull/1200
r?
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3223)
> Add cloud_pricing_export to billing_syndicate

- sql/moz-fx-data-shared-prod/braze_external/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3197)
> Resolves DENG-3134 to create a dataset for Braze ingestions

- sql/moz-fx-data-shared-prod/backfills_staging_derived/dataset_metadata.yaml
https://mozilla-hub.atlassian.net/browse/DSRE-1575?focusedCommentId=853097
Companion to https://github.com/mozilla-services/cloudops-infra/pull/5497
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3216)
> Grant backfill SAs write access to backfills_staging_derived

- sql/mozfun/ltv/get_state_ios_v2/metadata.yaml
- sql/mozfun/ltv/get_state_ios_v2/udf.sql
Create a new UDF for getting the iOS LTV state
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3239)
> GROWTH-147 Add new LTV UDF called "get_state_ios_v2"

- bqetl_project.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/schema.yaml
To fix the table deploys
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3240)
> Fix telemetry_derived.clients_daily_scalar_aggregates_v1 schema

- bigquery_etl/alchemer/survey.py
- tests/alchemer/test_survey.py
This is to print the error response instead of just the error code like [here in attempts 1-3](https://workflow.telemetry.mozilla.org/dags/bqetl_subplat/grid?dag_run_id=scheduled__2024-03-26T01%3A45%3A00%2B00%3A00&task_id=mozilla_vpn_derived__survey_recommend__v1&tab=logs).
The failed tasks succeeded on retry so this won't be useful this time.  The only thing I found in the api doc is that a 400 response is returned on calls following a timeout and 500 response: https://apihelp.alchemer.com/help/api-request-limits.  But I didn't see a 500 in the logs. …
> Print alchemer api error response before failing

- sql/moz-fx-data-shared-prod/telemetry_derived/mobile_usage_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3242)
> DENG-2978 remove external downstream task wait_for_mobile_usage

- sql/moz-fx-data-shared-prod/cloudflare/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3264)
> DENG-3263 - create cloudflare datasets - derived & view

- sql/moz-fx-data-shared-prod/cloudflare/device_usage/view.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3266)
> DENG-3112 cloudflare device usage

- bqetl_project.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3270)
> Dry run skip experiment_enrollment_cumulative_population_estimate_v1

- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3271)
> DENG-3112 fix data types from date to numeric

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3283)
> chore: complete newtab_visit_v1 backfill 2023-08-16

- sql_generators/funnels/configs/email_first_reg_login_funnels_by_service.toml
- sql_generators/funnels/configs/login_funnels_by_service.toml
- sql_generators/funnels/configs/pwd_reset_funnels_by_service.toml
- sql_generators/funnels/configs/registration_funnels_by_service.toml
@scholtzan can I please get these backfilled starting from the first of this year, when you have the time? 🙏
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3267)
> Add configs for Mozilla Accounts funnels including service dimension

- sql/mozfun/norm/result_type_to_product_name/udf.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3222)
> Add MDN to product result mapping

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
Backfills `newtab_visits_v1` to:
1. Populate the table with the full history of the `newtab` ping
2. Populate the `locale` and `had_non_search_engagement` fields that were recently added
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3294)
> `newtab_visits` backfill to Nov 2022

- sql/moz-fx-data-shared-prod/cloudflare/browser_usage/view.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3297)
> DENG-3113 new browser usage cloudflare table

- sql/moz-fx-data-shared-prod/cloudflare/os_usage/view.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/query.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3299)
> DENG-3265 cloudflare os usage

- sql/moz-fx-data-shared-prod/acoustic_derived/dataset_metadata.yaml
fix #5316 for the dataset_base_acl
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3304)
> fix: DENG-3287 change dataset_base_acl to derived for acoustic_derived

- sql/moz-fx-data-shared-prod/fenix_derived/meta_attribution_country_counts_v1/query.sql
follow-up to: https://github.com/mozilla/bigquery-etl/pull/5295#discussion_r1548761905
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3305)
> Fix meta_attribution_country_counts_v1

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3309)
> Complete backfill

- bqetl_project.yaml
To make CI on main happy
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3323)
> Skip dry run for acoustic contact_raw_v1

- dags.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3331)
> fix: DENG-3287 change start date for DAGs acoustic

- sql/moz-fx-data-shared-prod/braze_derived/dataset_metdata.yaml
Creating the derived dataset to support the Braze migration
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3354)
> adding braze derived dataset

- bigquery_etl/cli/query.py
Follow up to https://github.com/mozilla/bigquery-etl/pull/5346
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3364)
> fix: range_partitioning typo

- dags.yaml
just adding a note to the DAG's docs 
[Ticket](https://mozilla-hub.atlassian.net/browse/DENG-3361)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3363)
> doc: DENG-3361 add documentation to telemetry dev cyle DAG

- sql/moz-fx-data-marketing-prod/ga_derived/www_site_metrics_summary_v1/query.sql
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_metrics_summary_v1/schema.yaml
Use the new partnership UDFs to add the 3 new columns to the table www_site_metrics_summary_v1:
- funnel_derived
- distribution_model
- partner_org
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3373)
> DENG-3370 add 3 new "partnership" columns to GA3 www_site_metrics_summary_v1

- sql/moz-fx-data-shared-prod/udf/funnel_derived_clients/udf.sql
- sql/moz-fx-data-shared-prod/udf/partner_org_clients/udf.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3375)
> DENG-3367 Fix assert stub tests in 2 UDFs

- sql/moz-fx-data-shared-prod/udf/partner_org_clients/udf.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3379)
> DENG-3367-fix typo

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3408)
> [RS-1158] Backfill of newtab_visits_v1 to include missing pref

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3426)
> DENG-3425 - add new column to cloudflare browser_usage_v1

- dags.yaml
- sql/moz-fx-data-shared-prod/braze_external/hard_bounces_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/hard_bounces_v1/query.py
[DENG-3412](https://mozilla-hub.atlassian.net/browse/DENG-3412)
Trying it in bigquery-etl now 
[DENG-3412]: https://mozilla-hub.atlassian.net/browse/DENG-3412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3431)
> DENG-3412 braze sync hard bounce to bigquery with bqetl

- sql/moz-fx-data-shared-prod/braze_derived/newsletters_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_derived/products_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_derived/suppressions_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_derived/user_profiles_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_derived/users_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_derived/waitlists_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3432)
> fixing timestamp issue

- sql/moz-fx-data-shared-prod/braze_external/unsubscribes_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/unsubscribes_v1/query.py
[DENG-3435](https://mozilla-hub.atlassian.net/browse/DENG-3435)
Adding the unsubscribe events from braze to bigquery 
[DENG-3435]: https://mozilla-hub.atlassian.net/browse/DENG-3435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3438)
> DENG-3435 braze sync unsubscribes to bigquery

- sql/moz-fx-data-shared-prod/braze_derived/newsletters_v1/schema.yaml
- sql/moz-fx-data-shared-prod/braze_derived/products_v1/schema.yaml
- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/schema.yaml
- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/schema.yaml
- sql/moz-fx-data-shared-prod/braze_derived/suppressions_v1/schema.yaml
- sql/moz-fx-data-shared-prod/braze_derived/user_profiles_v1/schema.yaml
- sql/moz-fx-data-shared-prod/braze_derived/users_v1/schema.yaml
- sql/moz-fx-data-shared-prod/braze_derived/waitlists_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3441)
> updating all fields to nullable

- dags.yaml
- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3442)
> adding an active user filter to subscriptions

- sql/moz-fx-data-shared-prod/braze_external/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3458)
> Granting Braze development workspace access to data for testing

- sql/moz-fx-data-shared-prod/firefox_ios_derived/ltv_states_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3490)
> GROWTH-147 managed backfill

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3494)
> Backfill new `newtab_clients_daily_v1` table

- sql/moz-fx-data-shared-prod/firefox_ios_derived/ltv_states_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3495)
> GROWTH-147 complete backfill of firefox_ios_derived.ltv_states_v1

- dags.yaml
- sql/moz-fx-data-shared-prod/marketing_suppression_list_external/campaign_monitor_suppression_list_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/marketing_suppression_list_external/campaign_monitor_suppression_list_v1/query.py
- sql/moz-fx-data-shared-prod/marketing_suppression_list_external/campaign_monitor_suppression_list_v1/schema.yaml
- sql/moz-fx-data-shared-prod/marketing_suppression_list_external/dataset_metadata.yaml
[DENG-3471](https://mozilla-hub.atlassian.net/browse/DENG-3471)
Downloading suppression list data from Campaign Monitor API and adding it to BigQuery. 
[DENG-3471]: https://mozilla-hub.atlassian.net/browse/DENG-3471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3498)
> DENG-3471 suppression list from campaign monitor

- sql/moz-fx-data-shared-prod/udf/funnel_derived_clients/udf.sql
…dated private bqetl
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3513)
> DENG-3511 update funnel_derived_clients to remove channel

- sql/moz-fx-data-shared-prod/telemetry/clients_first_seen/view.sql
- sql/moz-fx-data-shared-prod/telemetry/clients_first_seen_28_days_later/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3514)
> DENG-3511 update views to use updated udfs

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_client_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3517)
> DENG-3168 backfill new desktop_engagement_client_v1 table

- sql/moz-fx-data-shared-prod/braze_external/users_previous_day_snapshot_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3533)
> fixing schema mismatch

- sql/moz-fx-data-shared-prod/marketing_suppression_list_derived/main_suppression_list_v1/metadata.yaml
DAG currently failing
fix #5423 
Adding no time partition to metadata
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3534)
> fix DENG 3410 main suppression list failing DAG

- sql/moz-fx-data-shared-prod/telemetry/clients_last_seen_v2/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3535)
> DENG-3462 update clients_last_seen_v2 view

- sql/moz-fx-data-shared-prod/braze_external/users_previous_day_snapshot_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3537)
> Make fxa_id a string

- bqetl_project.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_installs_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3547)
> DENG-2262 Update desktop installs to no longer rely on a GA3 table

- sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3563)
> Fix dry-run sql

- sql/moz-fx-data-shared-prod/internet_outages/global_outages_v1/metadata.yaml
This adds a gotchas to the docs.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3572)
> Document outages data duplication

- sql/moz-fx-data-shared-prod/firefox_ios_derived/client_ltv_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3576)
> GROWTH-147 add new column to schema

- sql/moz-fx-data-shared-prod/firefox_ios_derived/ltv_states_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3577)
> GROWTH-147 complete backfill of ltv_states_v1

- sql/moz-fx-data-shared-prod/firefox_ios_derived/client_ltv_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_ios_derived/ltv_states_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3583)
> GROWTH-147 switch from mozdata to moz-fx-data-shared-prod

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_errors_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_errors_v1/schema.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_errors_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_errors_v1/schema.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_errors_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_errors_v1/schema.yaml
Working on new DAG to load Cloudflare data to BigQuery, want to have error tables to catch if the API returns any errors, so we can go back and reprocess specific combinations if needed.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3587)
> DENG-3096 - build error tables for new DAGs

- sql/moz-fx-data-shared-prod/braze_derived/products_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_derived/products_v1/schema.yaml
- tests/sql/moz-fx-data-shared-prod/braze_derived/products_v1/test_braze_products/expect.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3590)
> removing active subscriptions count attribute

- sql/moz-fx-data-shared-prod/braze_external/changed_products_sync_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3592)
> removing count column

- sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/query.sql
- sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/schema.yaml
- tests/sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/test_suppression_list_time_parsing/expect.yaml
- tests/sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/test_suppression_list_time_parsing/moz-fx-data-bq-fivetran.acoustic_sftp.suppression_export_v_1.yaml
- tests/sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/test_suppression_list_time_parsing/moz-fx-data-shared-prod.acoustic_external.2024-03-20_main_suppression_list.yaml
adding the timestamp and reason to the suppression list
also adding tests
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3602)
> DENG-3600 Acoustic suppression list add timestamp

- sql/moz-fx-data-shared-prod/braze_derived/user_profiles_v1/schema.yaml
The dryrun step in the CI is failing because the schema has changed in #5471 for an underlying struct
This should now be fixed 🤞
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3614)
> fix PR 5471 dryrun failure

- dags.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3620)
> Assign kwindau as owner of bqetl_google_analytics

- sql/moz-fx-data-shared-prod/braze_external/users_previous_day_snapshot_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3626)
> changing field name in schema to match snapshot

- bigquery_etl/cli/stage.py
This reverts commit 792eb24ec2aea9c596620a3d72481e0a3137b8e7.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3646)
> Revert "Deploy referenced views to stage (#5497)"

- sql/moz-fx-data-shared-prod/treeherder_db/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3664)
> DSRE-1620 Update Treeherder syndicated datasets

- sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3682)
> fix: firefox_ios.retention_v1 is_suspicious_device_client field type

- sql/moz-fx-data-shared-prod/treeherder_db/dataset_metadata.yaml
This reverts commit 440c6f0078ca6acaa1d54389583ca8669e60c747.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3696)
> Revert "DSRE-1620 Temporarily disable treeherder_db syndication (#5524)"

- sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_aggregates_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3697)
> GLAM fix CTE on query

- sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/test_suppression_list_time_parsing/expect.yaml
- tests/sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/test_suppression_list_time_parsing/moz-fx-data-bq-fivetran.acoustic_sftp.suppression_export_v_1.yaml
- tests/sql/moz-fx-data-shared-prod/acoustic_external/suppression_list_v1/test_suppression_list_time_parsing/moz-fx-data-shared-prod.acoustic_external.2024-03-20_main_suppression_list.yaml
After the pruning of the suppression list in Acoustic.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3702)
> DENG-3701 prune acoustic suppression list

- sql/moz-fx-data-shared-prod/fakespot/amazon_analyses/metadata.yaml
- sql/moz-fx-data-shared-prod/fakespot/amazon_products/metadata.yaml
- sql/moz-fx-data-shared-prod/fakespot/bestbuy_analyses/metadata.yaml
- sql/moz-fx-data-shared-prod/fakespot/bestbuy_products/metadata.yaml
- sql/moz-fx-data-shared-prod/fakespot/walmart_analyses/metadata.yaml
- sql/moz-fx-data-shared-prod/fakespot/walmart_products/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3706)
> Add authorized label to fakespot user facing views.

- sql/moz-fx-data-shared-prod/braze_external/changed_newsletters_sync_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_external/changed_users_sync_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/schema.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_waitlists_sync_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/test_braze_changed_users/expect.yaml
- tests/sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/test_braze_changed_users/moz-fx-data-shared-prod.braze_derived.users_v1.yaml
- tests/sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/test_braze_changed_users/moz-fx-data-shared-prod.braze_external.users_previous_day_snapshot_v2.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3713)
> DENG 3182 braze ingestion fixes

- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/checks.sql
- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/script.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3714)
> updating subscription map and adding to dag

- sql/moz-fx-data-shared-prod/braze_external/changed_users_sync_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3717)
> adding filter for changed users

- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/script.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3723)
> adding about-addons subscription

- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/script.sql
fix for #5558 
hopefully this will allow the dryrun to run
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3727)
> fix-5558-addons_subscriptions

- bqetl_project.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3740)
> DENG-3186 skip dryrun for desktop engagement clients V1

- sql/moz-fx-data-shared-prod/braze_external/changed_users_sync_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/test_braze_changed_users/expect.yaml
- tests/sql/moz-fx-data-shared-prod/braze_external/changed_users_v1/test_braze_changed_users/moz-fx-data-shared-prod.braze_derived.users_v1.yaml
DENG-3755
add new users to changed users
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3756)
> DENG-3755 fix braze changed users to include new users

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_clients_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_clients_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_v1/schema.yaml
Adding some fields from the latest updates and changing how we deal with the missing data from clients_first_seen.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3758)
> Updates to desktop retention fields

- sql/data-observability-dev/fenix_derived/firefox_android_anonymised_v1/schema.yaml
This should unblock table deploys
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3759)
> Update schema.yaml for firefox_android_anonymised

- sql/moz-fx-data-shared-prod/firefox_desktop/urlbar_events_daily_engagement_by_position/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_position_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_position_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_position_v1/schema.yaml
supersedes and closes #5435. seeing if having the branch on the main repo this resolves the CI issues. 
This table will be used to power top-line metrics for the urlbar in Looker. Since this table is conveniently small, it will allow for Looker to load with no performance issues (as opposed to the urlbar_events table, which is rather large comparatively).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3757)
> [MRG] Create daily aggregates table

- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/script.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3766)
> updating subscription map to add mozilla builder

- sql/moz-fx-data-shared-prod/marketing_campaign_names/asa_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/marketing_campaign_names/asa_v1/udf.sql
- sql/moz-fx-data-shared-prod/marketing_campaign_names/google_ads_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/marketing_campaign_names/google_ads_v2/udf.sql
- sql/moz-fx-data-shared-prod/marketing_campaign_names/meta_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/marketing_campaign_names/meta_v2/udf.sql
This supports the [versioned campaign name proposal](https://docs.google.com/document/d/1lnZ6iMT091fq37SmnbpD9IcREMpGupae19Euqu94Low/edit).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3770)
> Initialize new campaign segment extraction functions

- sql/moz-fx-data-shared-prod/marketing_suppression_list_external/send_suppression_list_update_to_campaign_monitor_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/marketing_suppression_list_external/send_suppression_list_update_to_campaign_monitor_v1/query.py
Add DAG order and logging
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3771)
> fix DENG-3472 sync suppression list fo MoFo add log and order

- sql_generators/experiment_monitoring/templates/experiment_search_aggregates_v1/query.sql
This updates the `experiment_search_aggregates` template to pick up the search metric that are configured in the `templating.yaml` file for the `telemetry` namespace.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3776)
> [RS-649] Update experiment_search_aggregates to pick up metric configuration for telemetry

- sql/moz-fx-data-shared-prod/telemetry_derived/mobile_engagement_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/mobile_engagement_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3778)
> add is_suspicious_device_client to mobile engagement

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_position_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3777)
> [MRG] Engagement by position backfill

- sql/moz-fx-data-shared-prod/marketing_campaign_names/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3784)
> Add metadata for campaign names dataset

- sql_generators/glean_usage/templates/baseline_clients_daily_v1.query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3813)
> feat: add distribution_id to baseline_clients_daily_v1 query template (glean_usage generator)

- sql/moz-fx-data-shared-prod/search/mobile_search_clients_last_seen/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3775)
> RS-236_Normalize engine values in mobile_search_clients_last_seen

- docs/mkdocs.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3833)
> Add missing references to docs

- sql/moz-fx-data-shared-prod/firefox_ios_derived/baseline_clients_yearly_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3840)
> Properly newline col names

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_position_v1/backfill.yaml
Reviewed the table and it LGTM
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3850)
> [MRG] Update backfill.yaml

- sql/data-observability-dev/fenix_derived/metrics_clients_last_seen_v1/query.sql
I created some rules in both BigEye and Acryl to:
* monitor volumes
* client_id uniqueness
* normalized_channel non-nullness
This PR injects some errors to see how the tools will react
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3854)
> Inject some errors to fenix metrics_clients_last_seen_v1 to test observability tooling

- sql/moz-fx-data-shared-prod/search_terms_derived/merino_log_sanitized_v3/metadata.yaml
- sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v3/metadata.yaml
Change control ticket with details: https://mozilla-hub.atlassian.net/browse/DSRE-1635.
Note: @jasonthomas will need to approve this PR if we decide to implement it since he's the other change control CODEOWNER.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3749)
> Update retention of search terms sanitized datasets

- sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3861)
> Be explicit about columns in clients_yearly

- sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1/schema.yaml
To fix https://bugzilla.mozilla.org/show_bug.cgi?id=1898347
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3862)
> [Bug 1898347] Add distribution_id and geo_subdivision to clients_yearly schema

- sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3864)
> Added two new fields to col list

- sql/moz-fx-data-shared-prod/org_mozilla_fennec_aurora_derived/baseline_clients_daily_v1/backfill.yaml
A limited test running the managed backfill process against query that is part of the sql_generation.
Once we confirm everything is in order the following can be merged:
https://github.com/mozilla/bigquery-etl/pull/5628
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3856)
> feat: add backfill.yaml to org_mozilla_fennec_aurora_derived.baseline_clients_daily_v1

- sql/moz-fx-data-shared-prod/telemetry_derived/mobile_engagement_clients_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/mobile_engagement_clients_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/mobile_engagement_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/mobile_engagement_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3875)
> DENG-3288 Add "is_mobile" to mobile_engagement_clients_v1 and mobile_engagement_v1

- dags.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3868)
> Update `bqetl_subplat` DAG description with new expected Stripe report error message

- sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/query.py
I noticed some jobs in the table are listed as running and don't have a `total_slot_ms` because they were still running at 2:00 UTC.  This will query an additional previous day of jobs to update running jobs, which to me seems better than delaying the task by 4 hours or introducing an additional day delay.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3892)
> Reprocess past two days in jobs_by_organization_v1

- sql/moz-fx-data-shared-prod/telemetry/desktop_retention_clients/view.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_clients_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_clients_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_clients_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_clients_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3899)
> Add is_desktop to engagement and retention tables

- sql/data-observability-dev/fenix_derived/metrics_clients_last_seen_v1/query.sql
Some more error data for evaluating the observability tools
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3906)
> Add more null channels for metrics_clients_last_seen test

- sql/data-observability-dev/telemetry_derived/latest_versions_v1/metadata.yaml
- sql/data-observability-dev/telemetry_derived/latest_versions_v1/query.sql
- sql/data-observability-dev/telemetry_derived/latest_versions_v1/schema.yaml
Add a non-incremental table to the observability sandbox. The updates are scheduled via telemetry-airflow.
Scheduled via https://github.com/mozilla/telemetry-airflow/pull/1999
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3907)
> Add telemetry_derived.latest_version to data-observability-dev

- sql/moz-fx-data-shared-prod/telemetry/desktop_active_users/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3923)
> Update desktop active_users view to make dimensions available for KPIs.

- sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/query.sql
- sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/schema.yaml
- sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/mobile_search_clients_daily_v1.schema.json
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/test_aggregation/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/test_aggregation/mobile_search_clients_daily_v1.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_aggregation/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_ios_version_filter/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_namespace_union/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_overactive_filter/expect.yaml
Reverts mozilla/bigquery-etl#5598
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3924)
> Revert "RS-788 Add support for organic searches with ads to the mobile search counts tables"

- sql/moz-fx-data-shared-prod/org_mozilla_fennec_aurora_derived/baseline_clients_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3921)
> feat: remove backfill.yaml for org_mozilla_fennec_aurora_derived/baseline_clients_daily_v1 as it was not used

- sql/moz-fx-data-shared-prod/telemetry/desktop_active_users/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3936)
> Add isp name to desktop_active_users

- sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_aggregation/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_ios_version_filter/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_namespace_union/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_overactive_filter/expect.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3933)
> adding search_with_ads_organic to mobile_clients_daily table

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_clients_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3941)
> DENG-3186 start managed backfill of desktop_engagement_clients_v1

- sql/moz-fx-data-shared-prod/fenix_derived/retention_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3928)
> feat: add backfill.yaml to fenix and firefox_ios retention_v1 query

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_clients_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3945)
> DENG-3186 complete managed backfill of destkop_engagement_clients_v1

- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3949)
> Reverted EXPANSION to Expansion

- sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_aggregation/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_ios_version_filter/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_namespace_union/expect.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/test_overactive_filter/expect.yaml
Reverts mozilla/bigquery-etl#5683
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3953)
> Revert "adding search_with_ads_organic to mobile_clients_daily table"

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3944)
> DENG-3186 initiate managed backfill for desktop_engagement_v1

- sql_generators/funnels/configs/registration_funnels_legacy_events.toml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3946)
> Add registration funnels config using legacy events

- sql/moz-fx-data-shared-prod/braze_external/changed_firefox_subscriptions_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_newsletters_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_products_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_waitlists_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/delete_users_sync_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3959)
> updating labels for incrementing sync tables

- sql/moz-fx-data-shared-prod/fenix_derived/retention_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3964)
> feat: moving 2024-05-31 fenix_derived.retention_v1 backfill entry to Complete

- sql/moz-fx-data-shared-prod/braze_external/changed_firefox_subscriptions_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_newsletters_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_products_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_users_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_waitlists_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/delete_users_sync_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3984)
> updating metadata for incremental runs

- sql/moz-fx-data-shared-prod/braze_external/changed_firefox_subscriptions_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_newsletters_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_products_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_users_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/changed_waitlists_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/delete_users_sync_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3986)
> updating to remove partition parameter and add append table and no replace flags

- sql/moz-fx-data-shared-prod/telemetry/desktop_active_users/view.sql
All the data in `telemetry.desktop_active_users` corresponds to Firefox Desktop. Normalizing it here for all downstream aggregates & analysis.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3987)
> The app_name is Firefox Desktop in all cases.

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_clients_v1/backfill.yaml
data checked. Ready to populate table
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3991)
> complete managed backfill for desktop-client-retetion-v1

- dags.yaml
- sql_generators/mobile_kpi_support_metrics/templates/engagement.metadata.yaml
- sql_generators/mobile_kpi_support_metrics/templates/retention.metadata.yaml
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-3981)
> feat: add bqetl_mobile_kpi_metrics DAG and schedule mobile_kpi_metrics using it

- dags.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4000)
> feat: update bqetl_mobile_kpi_metrics DAG start date

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_v1/backfill.yaml
Finishing backfill of desktop_retention_v1.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4001)
> change status from Intitiate to Complete

- dags.yaml
- sql/moz-fx-data-shared-prod/google_ads/conversion_event_categorization/view.sql
- sql/moz-fx-data-shared-prod/google_ads_derived/conversion_event_categorization_v1/checks.sql
- sql/moz-fx-data-shared-prod/google_ads_derived/conversion_event_categorization_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/google_ads_derived/conversion_event_categorization_v1/query.sql
- sql/moz-fx-data-shared-prod/google_ads_derived/conversion_event_categorization_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4003)
> GROWTH-143 Create new desktop conversion event table

- sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/bootstrap.py
- tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/metrics.schema.json
- tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/org_mozilla_fenix.metrics.schema.json
- tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/org_mozilla_fenix_nightly.metrics.schema.json
- tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/org_mozilla_fennec_aurora.metrics.schema.json
- tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/test_aggregation/org_mozilla_fenix.metrics.yaml
- tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/test_aggregation/org_mozilla_fenix_nightly.metrics.yaml
- tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/test_aggregation/org_mozilla_fennec_aurora.metrics.yaml
Fixes https://github.com/mozilla/glam/issues/2843
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4006)
> fix(fenix_derived): Replace geckoview.version field with valid gecko.version

- sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4009)
> Backfill geckoview_version_v1

- sql_generators/active_users_deletion_requests/templates/metadata_deletion_request.yaml
Implements [DENG-3998](https://mozilla-hub.atlassian.net/browse/DENG-3998)
[DENG-3998]: https://mozilla-hub.atlassian.net/browse/DENG-3998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4019)
> Deprecate active_users_aggregates_deletion_requests

- sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4021)
> Update schema for schema_error_counts_v2

- sql/moz-fx-data-shared-prod/google_ads_derived/conversion_event_categorization_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4030)
> GROWTH-143 - Fix column name typo in query

- sql/moz-fx-data-shared-prod/google_ads_derived/conversion_event_categorization_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4032)
> GROWTH-143 - Add new filter

- docs/cookbooks/creating_a_derived_dataset.md
adding a note to the docs after the discussion in the infra meeting
feel free to change the wording
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4036)
> docs: add note about no_triage while unedr development

- dags.yaml
- sql/moz-fx-data-shared-prod/mozilla_org/ga_desktop_conversions/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v1/query.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4038)
> GROWTH-143 Productionalize Census feed

- bigquery_etl/glam/templates/extract_probe_counts_v1.sql
- bigquery_etl/glam/templates/histogram_percentiles_v1.sql
Includes re-formatting of files. I've added comments where things actually changed.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4048)
> fix(glam): add missing fields for percentiles and probe counts with non-norm data

- bigquery_etl/glam/templates/histogram_percentiles_v1.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4049)
> fix(glam): remove extra space that breaks table name

- dags.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4051)
> DENG-3111 new cloudflare browser usage query.py and DAG

- bigquery_etl/glam/templates/probe_counts_v1.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4054)
> fix(glam): disambiguate column name

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4059)
> DENG-3111 fix configs and add try/except

- sql/moz-fx-data-shared-prod/telemetry/clients_daily/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry/clients_daily_joined/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry/clients_daily_v6/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/events_live/metadata.yaml
https://github.com/mozilla-services/cloudops-infra/pull/5700
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4028)
> Remove poucave access

- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/query.sql
Removed the campaign id from the join
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4066)
> campaign id fix

- sql/moz-fx-data-shared-prod/search_terms_derived/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/search_terms_derived/search_term_data_validation_reports_v1/metadata.yaml
/CC @chelseatroy 
This is step 8 from  https://mozilla-hub.atlassian.net/browse/DSRE-1667
See also https://mozilla-hub.atlassian.net/browse/DSRE-1646 for change control approval
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4069)
> Add outerbounds write access to search terms data validation reports

- dags.yaml
- sql/moz-fx-data-shared-prod/fxci/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/fxci/worker_costs/view.sql
- sql/moz-fx-data-shared-prod/fxci_derived/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/fxci_derived/worker_costs_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/fxci_derived/worker_costs_v1/query.sql
- sql/moz-fx-data-shared-prod/fxci_derived/worker_costs_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4033)
> feat: Create new derived query for Firefox-CI worker costs

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4088)
> DENG-3096 Add where clause to all 3 Cloudflare tests

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4089)
> DENG-3096 switch parameter from @date to @dte

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4091)
> DENG-3096 update cloudflare DAGs

- sql/moz-fx-data-shared-prod/google_ads_derived/conversion_event_categorization_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4092)
> GROWTH-143 fix logic in query.sql

- sql/moz-fx-data-shared-prod/microsoft_derived/app_acquisitions_v1/query.py
- sql/moz-fx-data-shared-prod/microsoft_derived/app_conversions_v1/query.py
- sql/moz-fx-data-shared-prod/microsoft_derived/app_installs_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4106)
> take out 'microsoft' from table name.

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/query.py
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/query.py
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4104)
> DENG-3096 Cloudflare

- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4109)
> DENG-3096 rename column name

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4112)
> GROWTH-143 add 3 new conversion events

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4113)
> GROWTH-143 add census permissions

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4118)
> GROWTH-143 add mozilla confidential work group

- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4117)
> Gclid Conversions - update time offset

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/query.py
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/query.py
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4123)
> DENG-3096 cloudflare - minor updates

- CODEOWNERS
When https://github.com/mozilla/bigquery-etl/pull/5008/ landed it renamed some files that were subject to KPI change control, and the new paths were not annotated as subject to change control. Therefore https://github.com/mozilla/bigquery-etl/pull/5808/ was not subject to change control and apparently caused a KPI outage.
KPI reviewers need to be aware that CODEOWNERS needs to be updated in the event paths related to sql generation for KPIs are moved.
CI failures are due to a Dockerhub outage.
┆Issue is synchronized with this …
> Fix CODEOWNERS for active user aggregates sql generation

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4132)
> DENG-3096 Cloudflare - Browser Usage

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/query.py
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/query.py
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/query.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4136)
> DENG-3096 reduce timeouts

- sql/moz-fx-data-shared-prod/microsoft_derived/app_conversions_v1/metadata.yaml
In reviewing files, I realized that the friendly name was App Acquisitions when this is clearly App Conversions
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4137)
> fix friendly name. This is Conversions, not acquisitions

- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4144)
> DENG-3273 Add check to validate backend event counts in accounts_events vs events pings

- sql/mozfun/glam/histogram_cast_json/udf.sql
Cover cases in which the input is an empty array.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4160)
> Fix histogram_cast_json udf

- sql/mozfun/glam/histogram_cast_json/udf.sql
fixes [1904841](https://bugzilla.mozilla.org/show_bug.cgi?id=1904841)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4163)
> bug 1904841: fix sql udf cast_json breaking w string keys

- dags.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_daily_summary_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_empty_check_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_goals_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_landing_page_summary_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/firefox_whatsnew_summary_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_downloads_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_empty_check_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_events_metrics_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_hits_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_landing_page_metrics_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_metrics_summary_v1/metadata.yaml
- sql/moz-fx-data-marketing-prod/ga_derived/www_site_page_metrics_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_clients_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4166)
> DENG-2492 Deprecate GA3 tables since GA3 feed ending 2024-06-30

- bqetl_project.yaml
- sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/query.sql
- sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/schema.yaml
- tests/sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/test_aggregation/expect.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4169)
> Add normalized_app_name_os to mobile search aggregate table

- sql/mozfun/glam/percentile/udf.sql
Covers a case in which all bucket values are zero, and adds a test for it.
Here's a test comparing it with the old JS version of this udf:
https://sql.telemetry.mozilla.org/queries/100986/source 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4174)
> bug 1904841: Fix glam_percentile udf

- sql/moz-fx-data-shared-prod/ads_backend/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/ads_backend_derived/dataset_metadata.yaml
See also https://github.com/mozilla-services/cloudops-infra/pull/5759
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4182)
> Update ads_backend workgroup_access

- sql/moz-fx-data-shared-prod/search/mobile_search_aggregates/view.sql
Field got added to referenced table
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4183)
> Remove normalized_app_name_os from mobile_search_aggregates view

- sql/moz-fx-data-shared-prod/firefox_accounts/fxa_delete_events/view.sql
- sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v2/query.sql
- sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_delete_events_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4190)
> Bug 1889144 - Add unhashed user id to fxa_delete_events

- sql/moz-fx-data-shared-prod/mozilla_vpn_external/devices_v1/query.sql
- sql/moz-fx-data-shared-prod/mozilla_vpn_external/subscriptions_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4192)
> Bug 1905357: use table alias to fix references in query

- sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4209)
> RS 1247- Mark 2 months backfill as complete for search client level tables

- dags.yaml
The Braze DAG fails intermittently. Increasing the number of retries for less manual intervention.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4217)
> adding retries and decreasing delay

- sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4232)
> RS 1247- Backfill search mobile client level table

- sql/moz-fx-data-shared-prod/app_store/firefox_app_store_territory_source_type_report/view.sql
- sql/moz-fx-data-shared-prod/app_store/firefox_app_store_territory_web_referrer_report/view.sql
- sql/moz-fx-data-shared-prod/app_store/firefox_downloads_territory_source_type_report/view.sql
- sql/moz-fx-data-shared-prod/app_store/firefox_downloads_territory_web_referrer_report/view.sql
- sql/moz-fx-data-shared-prod/app_store/firefox_usage_territory_source_type_report/view.sql
- sql/moz-fx-data-shared-prod/app_store/firefox_usage_territory_web_referrer_report/view.sql
- sql/moz-fx-data-shared-prod/app_store_syndicate/dataset_metadata.yaml
In the previous https://github.com/mozilla/bigquery-etl/pull/5773, we forgot to update the references in the views inside `app_store` dataset to fit the new syndicate structure which resulted in invalid views. This fix resolves this.
We also decided to limit the syndication to only specific tables in the source project to reduce the noise the analytics BQ project, and some YAML validation errors have been fixed.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4244)
> fix(): incorrect source in app_store_syndication views and limit the number of syndicated views created to reduce noise

- sql/moz-fx-data-shared-prod/snowplow_external/dataset_metadata.yaml
https://mozilla-hub.atlassian.net/browse/DSRE-1682
Requires https://github.com/mozilla-it/global-platform-admin/pull/1541 and https://github.com/mozilla-services/cloudops-infra/pull/5765
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4243)
> Add snowplow_external dataset

- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4257)
> DENG-3273 Add check to validate frontend event counts in accounts_events vs events pings

- sql/moz-fx-data-shared-prod/telemetry_derived/event_events_v1/metadata.yaml
https://mozilla-hub.atlassian.net/browse/DENG-4090
For possible performance improvements to shredder, see ticket for details.  Clustering is only applied to new data so this will probably take a couple shredder runs to take effect.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4263)
> [DENG-4090] Add client_id clustering to event_events_v1

- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_beta_aggregates_v1/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_nightly_aggregates_v1/metadata.yaml
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_release_aggregates_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/glam_derived/client_probe_counts_firefox_desktop_beta_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4267)
> GLAM update dags to depend on tasks inside a task group

- sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4273)
> Backfill desktop search aggregates from 2022-01-01

- sql/moz-fx-data-shared-prod/ads/ppa_measurements/view.sql
This is in reference to https://mozilla-hub.atlassian.net/browse/AD-325
Switching the view to point to the prod source.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4277)
> (feat): Update view.sql to point to prod source for AD-325

- sql/moz-fx-data-shared-prod/fxci_derived/task_runs_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/fxci_derived/task_runs_v1/schema.yaml
- sql/moz-fx-data-shared-prod/fxci_derived/tasks_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/fxci_derived/tasks_v1/schema.yaml
- sql/moz-fx-data-shared-prod/fxci_derived/worker_metrics_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/fxci_derived/worker_metrics_v1/schema.yaml
Bug: 1904928
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4276)
> feat(fxci): add metadata / schemas for new fxci-etl tables

- sql/moz-fx-data-shared-prod/glam_derived/client_probe_counts_firefox_desktop_nightly_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4284)
> fix(glam_export): Update a task dep on task_group that forgot

- sql/moz-fx-data-shared-prod/monitor_backend/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/monitor_backend_derived/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/monitor_cirrus/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/monitor_cirrus_derived/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/monitor_frontend/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/monitor_frontend_derived/dataset_metadata.yaml
These datasets will be monitored first
> chore(data-privacy-mapping): DSRE-1690 - Add dataset_metadata.yaml for monitor datasets

- sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/backfill.yaml
We are making further changes to the search_aggregates_v8 table. Will backfill once all the changes are merged.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4302)
> Remove the backfill yaml for desktop search aggregates

- sql/mozfun/ltv/desktop_states_v1/metadata.yaml
- sql/mozfun/ltv/desktop_states_v1/udf.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4294)
> add desktop ltv udf

- dags.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop/adclick_history/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/checks.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4323)
> Create new firefox_desktop_derived.adclick_history_v1 table and DAG

- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4330)
> Update accounts_events sql check

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4332)
> GROWTH-90 Add "client_id" as a cluster column to "moz-fx-data-shared-prod.firefox_desktop_derived.adclick_history_v1"

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/adclick_history_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4336)
> GROWTH-90 add depends_on_past = true to metadata.yaml

- bqetl_project.yaml
- sql/moz-fx-data-shared-prod/mozilla_org/downloads_with_attribution/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/downloads_with_attribution_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/downloads_with_attribution_v1/query.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/downloads_with_attribution_v1/schema.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/downloads_with_attribution_v2/checks.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/downloads_with_attribution_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/downloads_with_attribution_v2/query.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/downloads_with_attribution_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4337)
> DENG-4201 Create downloads_with_attribution_v1 and _v2 in shared prod (to prep for removing from mktg prod)

- sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4338)
> Mark the search revenue levers backfill complete

- CODEOWNERS
- sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4343)
> [RS-1091: client-level DAU] update query to adjust for default engine bugs

- sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4348)
> RS 1091 - Backfill search revenue levers after bug fix

- sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4354)
> RS1091 - Mark backfill search revenue levers bug fix complete

- sql/moz-fx-data-shared-prod/firefox_desktop/ltv_states/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/ltv_states_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/ltv_states_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/ltv_states_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4351)
> GROWTH-90 Create Firefox Desktop ltv_states_v1 table & and ltv_states view

- sql/moz-fx-data-shared-prod/firefox_desktop/ltv_states/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/ltv_states_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4355)
> GROWTH-90 Minor follow-ups to PR # 5943 (new LTV table for Firefox Desktop)

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/schema.yaml
- sql/mozfun/serp_events/is_ad_component/udf.sql
Adds a new event to `newtab_visits_v1`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4369)
> Add location selected field

- bigquery_etl/shredder/config.py
- tests/shredder/test_config.py
New client ltv tables are based on `main_v5` derived tables so should be using `telemetry_stable.deletion_request_v4` instead of `firefox_desktop_stable.deletion_request_v1`.  This also makes `find_glean_targets` skip targets that were manually added, otherwise it would attempt multiple deletions only run the first it sees.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4375)
> Update shredder config for new ltv tables to use legacy deletions

- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_beta_aggregates/view.sql
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_nightly_aggregates/view.sql
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_release_aggregates/view.sql
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_beta_aggregates/view.sql
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_nightly_aggregates/view.sql
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_release_aggregates/view.sql
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_beta_aggregates/view.sql
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_nightly_aggregates/view.sql
- sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_release_aggregates/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4380)
> fix(GLAM): Fix udf name

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4389)
> Add location selected telemetry to clients daily

- sql/mozfun/glam/histogram_cast_struct/udf.sql
this is not the perfect solution but for now i just want the CI to work ;)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4393)
> (dirty) fix for PR 5957

- bigquery_etl/glam/templates/extract_probe_counts_v1.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4403)
> fix(GLAM): remove dangling comma that breaks a query

- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_accounts_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_accounts_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_recovery_codes_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_recovery_codes_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_recovery_keys_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_recovery_keys_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_security_events_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_security_events_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_session_tokens_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_session_tokens_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_totp_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_totp_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_accounts_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_accounts_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_recovery_keys_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_recovery_keys_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_security_events_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_security_events_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_session_tokens_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_session_tokens_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4124)
> DENG-3492 Update schemas of synced accounts databases

- sql/moz-fx-data-shared-prod/mozilla_org/www_site_downloads/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_downloads_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_downloads_v2/query.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_downloads_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4431)
> DENG-4194 add new column

- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4435)
> Update accounts events checks

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4437)
> GROWTH-141 Give census access to table

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_errors_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_errors_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_errors_v1/checks.sql
- sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4453)
> DENG-3096 add uniqueness checks to all 6 cloudflare tables

- sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_goals_v2/checks.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_goals_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_goals_v2/query.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_goals_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4464)
> add blogs_goals_v2 checks, metadata, query, schema files to shared_prod

- sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_metrics_summary_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_metrics_summary_v2/query.sql
- sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_metrics_summary_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4467)
> copy code for metadata, query, schema from marketing-prod to shared-prod

- sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4489)
> DENG-4446 Fix CI issue - take out column added to schema incorrectly

- bigquery_etl/dependency.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4504)
> Remove parallelism parameter from dependency CLI command

- sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v2/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4513)
> DENG-4491 part 1 - add profile_group_id to schema

- dags.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_merino_extract_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4521)
> Mc 1256 adding filter on recommended at

- sql/moz-fx-data-shared-prod/cloudflare/browser_usage/view.sql
- sql/moz-fx-data-shared-prod/cloudflare/device_usage/view.sql
- sql/moz-fx-data-shared-prod/cloudflare/os_usage/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4522)
> DENG-3096 Add country names to the 3 cloudflare views

- sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4527)
> DENG-4515 fix cast null as string to match schema

- sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4528)
> Fix search_aggregates_v8 schema

- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v2/metadata.yaml
Adding subscription map as a Google Sheet
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4531)
> DENG-3503 add braze subscription map v2

- sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v3/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v3/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4537)
> DENG-4514 add profile group ID to clients_first_seen_v3

- sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/schema.yaml
- tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/moz-fx-data-shared-prod.telemetry_derived.clients_daily_joined_v1.schema.json
- tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/expect.yaml
- tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/moz-fx-data-shared-prod.telemetry_derived.clients_daily_joined_v1.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4565)
> DENG-4564 add profile_group_id to urlbar_clients_daily_v1

- dags.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4584)
> adding tag for triage to record only

- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v2/schema.yaml
Updating according to [docs](https://docs.telemetry.mozilla.org/cookbooks/operational/connecting_external_data_bigquery.html#connecting-sheets)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4587)
> updating files according to workbook

- sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4586)
> DENG-4568 add profile_group_id to sponsored_tiles_clients_daily_v1

- sql_generators/funnels/configs/account_pref_delete_funnel.toml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4591)
> Add account deletion funnel

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/query.sql
- tests/sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/test_aggregation/expect.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4593)
> updating query to match schema

- sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/query.sql
Minor follow up fix to [PR-6085](https://github.com/mozilla/bigquery-etl/pull/6085)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4596)
> DENG-4568 - fix typo in query for sponsored_tiles_clients_daily_v1

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/schema.yaml
- tests/sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/moz-fx-data-shared-prod.firefox_desktop_stable.newtab_v1.schema.json
- tests/sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/test_aggregation/expect.yaml
- tests/sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/test_aggregation/moz-fx-data-shared-prod.firefox_desktop_stable.newtab_v1.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4598)
> DENG-4588 add profile_group_id to newtab_visits_v1

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4599)
> DENG-4556 Add profile_group_id to telemetry_derived.newtab_interactions_v1

- sql_generators/urlbar_events/templates/desktop_query.sql
- sql_generators/urlbar_events/templates/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4608)
> DENG-4607 add profile_group_id to urlbar_events_v2

- sql_generators/glean_usage/events_stream.py
- sql_generators/glean_usage/templates/events_stream_v1.query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4609)
> DENG-4560 Add profile_group_id to events_stream_v1

- sql_generators/serp_events_v2/templates/desktop_query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4615)
> DENG-4613 update serp_events_v2 generator to include profile_group_id

- bigquery_etl/glam/clients_daily_scalar_aggregates.py
Fixes https://github.com/mozilla/glam/issues/2927
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4628)
> Fix(GLAM): Cast scalar values as NUMERIC to avoid SUM overflow

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/review_checker_clients_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/review_checker_clients_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4621)
> DENG-4620 add profile_group_id to review_checker_clients_v1

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/review_checker_events_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/review_checker_events_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4627)
> DENG-4626 add profile_group_id to review_checker_events_v1

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4629)
> add thumb_voting event name to pocket events

- sql_generators/glean_usage/templates/metrics_clients_daily.query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4634)
> DENG-4632 - add profile_group_id to firefox desktop & format query.sql

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4640)
> Complete backfill for newtab_visits

- sql/moz-fx-data-shared-prod/mozilla_org/blogs_daily_summary/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/blogs_goals/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/blogs_landing_page_summary/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/blogs_sessions/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/firefox_whatsnew_summary/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/www_site_events_metrics/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/www_site_hits/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/www_site_landing_page_metrics/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/www_site_metrics_summary/view.sql
- sql/moz-fx-data-shared-prod/mozilla_org/www_site_page_metrics/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4642)
> DENG-4152 Create GA4 views and update existing shared prod views from GA3 to GA4

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/metrics_clients_last_seen_v1/schema.yaml
- sql_generators/glean_usage/templates/metrics_clients_last_seen.query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4639)
> DENG-4631 - add profile_group_id to metrics_clients_last_seen_v1

- sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4643)
> Backfill search revenue levers to pull from agg

- sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_event_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_event_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_event_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4645)
> DENG-4644 Add profile_group_id to clients_daily_event_v1

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4650)
> Initiate backfill for newtab client daily

- sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4655)
> Fix the filter for mobile search aggregates

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4656)
> DENG-4652 add profile_group_id to newtab_clients_daily_v1

- sql/moz-fx-data-shared-prod/telemetry_derived/suggest_clients_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/suggest_clients_daily_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4670)
> DENG-4657 add profile_group_id to suggest_clients_daily_v1

- sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4672)
> Backfill search_agg desktop post acer fix

- sql/moz-fx-data-shared-prod/telemetry_derived/experiments_v1/metadata.yaml
**This table is being deprecated because:**
**1. It builds off of an already deprecated table**
It builds off of the view `moz-fx-data-shared-prod.telemetry.main_summary` which builds off of `moz-fx-data-shared-prod.telemetry.main_summary_v4` which builds off of `moz-fx-data-shared-prod.telemetry_derived.main_summary_v4` which is already deprecated
**2. It only has data through 2020-03-02**
> Deprecate telemetry_derived.experiments_v1

- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/checks.sql
This updates sql check by filtering out non-production/stage data that appeared recently.
Also removes some no-longer necessary workarounds for bugs that are now fixed in production.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4679)
> Bug 1915724 - Update accounts events sql check 

- sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/checks.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4690)
> Bug 1915724 - Update accounts events checks

- sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4700)
> Backfill search aggregates

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_clients_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_clients_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4712)
> DENG-4711 add profile_group_id to desktop_engagement_clients_v1

- sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4713)
> Complete search aggregates backfill

- sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4686)
> Backfill search revenue levers post aggs update

- sql_generators/glean_usage/common.py
- sql_generators/glean_usage/templates/baseline_clients_daily_v1.query.sql
- sql_generators/glean_usage/templates/baseline_clients_daily_v1.schema.yaml
- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4719)
> DENG-4718 Add profile_group_id to baseline_clients_daily_v1, baseline_clients_last_seen_v1

- sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_events_metrics_v2/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4742)
> DENG-4152 fix SQL to read from new shared-prod path

- sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v3/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4737)
> update comment to be clients_first_seen_v2 to clients_first_seen_v3

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_new_profiles_aggregates_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_new_profiles_aggregates_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_new_profiles_aggregates_v1/schema.yaml
This PR is related to this document: https://docs.google.com/document/d/1tQOhsak2ZKGRnedKB1U5Rnp07vp6kvodi88o3NlIV54/edit
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4735)
> initial add of query.sql and metadata.yaml files. 

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/schema.yaml
- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/script.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4755)
> DENG-4754 Add 2 new columns to ga_sessions_v2

- sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/script.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4756)
> DENG-4754 update ga sessions v2 logic

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_new_profiles_aggregates_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4758)
> add CTEs, change join to get all the data, add coalesce for is_dau

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_new_profiles_aggregates_v1/query.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4759)
> reformat query file

- sql/moz-fx-data-shared-prod/sumo_ga/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/sumo_ga_derived/dataset_metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4760)
> DSRE-1681 Create 2 new datasets, sumo_ga_derived & sumo_ga

- sql/moz-fx-data-shared-prod/sumo_ga_derived/ga4_events_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4795)
> DSRE-1681 Add sensor for GA4 SUMO table to wait for source data to arrive

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_clients_v2/backfill.yaml
This PR will backfill data for `moz-fx-data-shared-prod.telemetry_derived.desktop_retention_clients_v2` back to 2021-01-01
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4809)
> add backfill.yaml file

- sql/moz-fx-data-shared-prod/telemetry_derived/events_live/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4808)
> DENG-4807 Add profile_group_id to events_live view

- .github/pull_request_template.md
- .github/reviewer_checklist.md
This PR updates the Pull Request template of this repo with the intention to make users write more descriptive PRs.
* https://github.com/mozilla/bigquery-etl/issues/6185
> chore: update PR template

- .circleci/workflows.yml
- bigquery_etl/cli/monitoring.py
This triggers `bqetl monitoring update` in the CI to generate the Bigconfig files for the tables that should be monitored
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4806)
> Generate Bigeye monitoring configs in CI

- dags.yaml
- sql/moz-fx-data-shared-prod/activity_stream_bi/impression_stats_by_experiment_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/activity_stream_bi/impression_stats_flat_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/metadata.yaml
- sql/moz-fx-data-shared-prod/search_derived/search_clients_last_seen_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry/newtab_visits/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/metadata.yaml
- sql_generators/feature_usage/templates/metadata.yaml
This PR updates ownership for anicholson owned assets, based on recent modifications and context. Feel free to change if I'm missing something!
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4875)
> chore: update anicholson ownership

- sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/query.sql
This PR seeks to improve memory utilization of `sponsored_tiles_clients_daily_v1` in response to recent job failures.
Working query: https://console.cloud.google.com/bigquery?sq=470293616514:f9d4c9d6c32f4637b3faf16c4c3a17ca
FWIW, new query form reduced slot milliseconds by ~50%, still producing congruent results.
* [AD-483](https://mozilla-hub.atlassian.net/browse/AD-483)
[AD-483]: https://mozilla-hub.atlassian.net/browse/AD-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [AD-483] Improving efficiency of `sponsored_tiles_clients_daily_v1`

- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_aggregates_v2/backfill.yaml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4902)
> mark the backfill complete so data will go into the table

- sql/moz-fx-data-shared-prod/telemetry_derived/segmented_dau_28_day_rolling_v1/query.sql
This PR fixes the query for this new table so it doesn't overcount DAU
* [DENG-4883](https://mozilla-hub.atlassian.net/browse/DENG-4883)
[DENG-4883]: https://mozilla-hub.atlassian.net/browse/DENG-4883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4903)
> DENG-4883 Update query logic in new table

- sql/moz-fx-data-shared-prod/sumo_ga/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/sumo_ga_derived/dataset_metadata.yaml
https://mozilla-hub.atlassian.net/browse/DSRE-1681?focusedCommentId=940939
* DSRE-1681
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4977)
> chore: add sumo SA access to sumo GA datasets

- sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.view.sql
- sql_generators/mobile_kpi_support_metrics/templates/engagement_clients.view.sql
- sql_generators/mobile_kpi_support_metrics/templates/new_profile_clients.view.sql
- sql_generators/mobile_kpi_support_metrics/templates/retention_clients.view.sql
- sql_generators/mobile_kpi_support_metrics/templates/union.view.sql
Updating the Mobile KPI Support Metric Generator so that all models use the new attribution table.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5020)
> feat(DENG-5017): update engagement, and retention to use the new attribution table

- sql/moz-fx-data-shared-prod/telemetry/desktop_retention/view.sql
- sql/moz-fx-data-shared-prod/telemetry/desktop_retention_clients/view.sql
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5025)
> update views to point to v2 tables

- bigquery_etl/query_scheduling/dag.py
- bqetl_project.yaml
- tests/data/dags/python_script_test_dag
This was using the warehouse ID from the Bigeye POC. Fixes the failing Airflow task
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5149)
> Update Bigeye warehouse ID

- sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/metadata.yaml
Wrong dataset.  fix for https://github.com/mozilla/bigquery-etl/pull/6289
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5159)
> Change shredder_targets dataset to monitoring_derived

- sql/moz-fx-data-shared-prod/mozilla_org/desktop_conversion_events/view.sql
This PR creates a new view for use in sending desktop conversion events to operate ads off of.  
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5313)
> Create new view for desktop conversion events

- sql/moz-fx-data-shared-prod/org_mozilla_ios_focus_derived/baseline_clients_last_seen_v1/bigconfig.yml
- sql/moz-fx-data-shared-prod/org_mozilla_ios_focus_derived/baseline_clients_last_seen_v1/metadata.yaml
Add bigeye config file to org_mozilla_ios_focus_derived and set the monitoring metadata to true.
This PR is a sample one before we set up the checks on all of the glean tables
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5314)
> Add bigeye config file to org_mozilla_ios_focus_derived

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/schema.yaml
- tests/sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/test_aggregation/expect.yaml
Adds new telemetry for New Tab window size and for card placement for Pocket content.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5315)
> Add window rectangle to newtab visits

- sql/moz-fx-data-shared-prod/org_mozilla_ios_focus_derived/baseline_clients_last_seen_v1/bigconfig.yml
project ID typo 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5391)
> Fix typo in Bigconfig

- sql/moz-fx-data-shared-prod/sumo_ga_derived/ga4_events_v1/schema.yaml
CI is throwing some dry run errors for this table due to schema issues. This should fix it
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5434)
> Fix schema for sumo ga4_events

- sql/moz-fx-data-shared-prod/stripe_external/dataset_metadata.yaml
~~Not~~ ready to merge, requires https://github.com/mozilla-services/cloudops-infra/pull/5959/ among other dependencies
* DSRE-1755
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5109)
> DSRE-1755 switch to v2 workgroup for stripe

- bigquery_etl/metadata/parse_metadata.py
- sql/moz-fx-data-shared-prod/analysis/dataset_metadata.yaml
To match https://github.com/mozilla-services/cloudops-infra/pull/5992
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5483)
> Set analysis dataset default retention to 180 days

- sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5546)
> Adding 5 new countries with sponsored tiles as of 10/3

- sql/moz-fx-data-shared-prod/fxci_derived/task_run_costs_v1/query.sql
I noticed a SQL error where I was aggregating after joining, causing us to count worker costs / uptime more than once.
I'm a bit unclear if this was actually causing the data to be wrong or not because we really only care about the cost / time (and this bug was overcounting both by the same factor).
But regardless, it's best to fix the problem by doing the aggregation prior to joining.
Bug: 1926017
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5625)
> fix: SUM after join error in fxci_derived.task_run_costs_v1

- sql/moz-fx-data-shared-prod/static/key_tentpole_dates/data.csv
- sql/moz-fx-data-shared-prod/static/key_tentpole_dates/metadata.yaml
- sql/moz-fx-data-shared-prod/static/key_tentpole_dates/schema.yaml
Track Key Tentpole dates to bring table into larger model
* https://mozilla-hub.atlassian.net/browse/AD-208
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AD-208)
> Create key_tentpole_dates file

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/schema.yaml
Add engagement fields to more easily measure HNT KPIs.
> add engagement fields

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/backfill.yaml
> fix dates for newtab_clients_daily backfill

- bqetl_project.yaml
https://mozilla-hub.atlassian.net/browse/DSRE-1784?focusedCommentId=955281
* DSRE-1784
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5798)
> chore: skip publishing search terms view that shouldn't actually exist

- sql/moz-fx-data-shared-prod/mozilla_org/desktop_conversion_events/view.sql
This PR adjusts the feed being sent to Google ads for marketing optimization, to look only at click IDs originating from the US and also to only look at those clicks in the last 28 days.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5943)
> feat(desktop_conv_events): Update to US only and last 28 days only

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/backfill.yaml
Complete backfill of newtab_clients_daily
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5911)
> Complete newtab_clients_daily backfill

- bigquery_etl/cli/view.py
For `./bqetl view clean` a significant amount of time is needed to list all available views. This can be sped up by querying against `INFORMATION_SCHEMA` to get existing views.
As an example, for `moz-fx-data-experiments` this process currently takes around 20minutes (as there are a ton of tables). This change brings it down to a few seconds
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6067)
> Use INFORMATION_SCHEMA to get existing views for cleaning

- bigquery_etl/cli/stage.py
I've noticed more frequent timeouts of the reset-stage-env CI step ([example](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/41024/workflows/7490a250-a11e-4e60-ae57-7851c8e94c86/jobs/469904)) due to `Too long with no output (exceeded 10m0s): context deadline exceeded`.  I think it takes most of the time in the `list(client.list_datasets())` call because of the accumulation of datasets. The `--delete-expired` flag currently does the opposite and doesn't delete expired datasets when set.
This adds logs so it doesn't timeout and we can see what it's doing.  This also flips the `--delete-expired` behaviour so datasets are deleted ongoingly which I think is what's intended but I'm not sure …
> Add logging to stage clean and fix --delete-expired

- sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_logical_subscriptions_v1/query.sql
The `monthly_active_logical_subscriptions_v1` ETL has been relying on the latest `daily_active_logical_subscriptions_v1.was_active_at_day_end` field value for each subscription in the month to calculate its own `was_active_at_month_end` field, but that wouldn't work correctly if the subscription ended at midnight on a day that isn't the first of the month.  That's because when a subscription ends exactly at midnight there will be no `daily_active_logical_subscriptions_v1` record for it that day (since it wasn't active at any point during that day), and its `daily_active_logical_subscriptions_v1` record for the preceding day will have `was_active_at_day_end = TRUE` because it hadn't yet ended by the last instant of that day.
This PR fixes that problem by changing the …
> Fix the `monthly_active_logical_subscriptions_v1` ETL to correctly calculate `was_active_at_month_end` when a subscription ends exactly at midnight

- sql/moz-fx-data-shared-prod/static/key_tentpole_dates/data.csv
Add more dates for 2023
* [AD-208
](https://mozilla-hub.atlassian.net/browse/AD-208)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6389)
> Add more dates to Key Tentpoles data.csv

- bigquery_etl/cli/monitoring.py
This makes some improvements to the Bigeye error reporting. If applying the Bigeye configs fails, this change will print out the content of `moz-fx-data-shared-prod_APPLY.yml`. 
I also added a `--dry-run` option to run a Bigeye plan.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6392)
> Improve Bigeye error reporting

- docs/cookbooks/creating_a_derived_dataset.md
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6368)
> remove backtick

- sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/metadata.yaml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6412)
> replace metadata file

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6416)
> complete backfill to fix Pocket click error

- sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/query.py
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6422)
> Deng 6360 add arguments to metadata file

- sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/query.py
This is causing the target detection to incorrectly expect deletion request tables for the glean server apps.  Just noticed today because of the new syncstorage app
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6425)
> Don't set shredder target for datasets with no deletion requests

- sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/metadata.yaml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6430)
> add date partition parameter to scheduling in metadata

- sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/query.py
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6436)
> add in os.environ.get to get bearer_token

- sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/schema.yaml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6461)
> change types ofr created_at and job_created_at from STRING to DATE

- CODEOWNERS
- sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/schema.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_week_4_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_position_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_position_v1/schema.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_v1/schema.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/query.sql
- sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/schema.yaml
- sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/query.sql
- sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_funnel_installs_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_funnel_installs_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_new_profiles_aggregates_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_aggregates_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_aggregates_v2/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/firefox_nondesktop_exact_mau28_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/firefox_nondesktop_exact_mau28_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_fxa_compressed_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_fxa_compressed_v2/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_new_profiles_compressed_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_new_profiles_compressed_v2/schema.yaml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6463)
> break ios onboarding funnel into two smaller funnels

- bigquery_etl/cli/query.py
- tests/cli/test_cli_query.py
Materialized views currently aren't deployed at all and this change deploys them only if they don't exist.
This also adds a check to see if the deployed view sql matches the sql matches the file which can be used to redeploy changed materialized views in the future to resolve https://github.com/mozilla/bigquery-etl/issues/5804.  I want to test if this works well though because recreating materialized views can be expensive
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6472)
> Deploy materialized views if they do not exist

- sql/moz-fx-data-shared-prod/firefox_ios_derived/ios_onboarding_main_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/ios_onboarding_multiple_choice_v1/backfill.yaml
Configurations to trigger ios onboarding funnel backfills.
cc @rhythmofrain63 
> Backfill iOS onboarding funnels

- sql/moz-fx-data-shared-prod/firefox_ios_derived/ios_onboarding_main_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/ios_onboarding_multiple_choice_v1/backfill.yaml
Complete backfill for iOS onboarding funnels. The data looks good to me.
cc @rhythmofrain63 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6539)
> Complete backfills for ios onboarding funnels

- requirements.in
- requirements.txt
- sql/moz-fx-data-shared-prod/firefox_ios/app_store_choice_screen_engagement/view.sql
- sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_engagement_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_engagement_v1/query.py
- sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_engagement_v1/schema.yaml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6431)
> feat: add app_store_choice_screen_engagement_v1 query to firefox_ios_derived

- sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_engagement_v1/query.py
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6590)
> fix: replace escaped new line char with new line char

- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/query.sql
- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/schema.yaml
feat(DENG-6549): convert campaign stats to be incremental android
This PR also adds 2 columns that were present in the final select statement of the query but were missing inside `schema.yaml`.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6602)
> feat(DENG-6549): convert campaign stats to be incremental android

- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/schema.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6729)
> fix: update campaign_segments and ad_group_segments to be repeated record of key, value pair type

- sql/bigconfig.yml
- sql_generators/glean_usage/__init__.py
- sql_generators/glean_usage/common.py
- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.checks.sql
- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.metadata.yaml
---
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6815)
> feat(DENG-4975): Move baseline clients last seen v1 checks to bigconfig

- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
> fix: remove duplication check for country that was added accidentally

- sql/moz-fx-data-shared-prod/accounts_backend/monitoring_db_counts/metadata.yaml
- sql/moz-fx-data-shared-prod/accounts_backend/monitoring_db_counts/view.sql
Follow up to https://github.com/mozilla/bigquery-etl/pull/6511, will make accessing this data a bit easier.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6816)
> DSRE-1779 Add user-facing view to accounts_backend_derived.monitoring_db_counts_v1

- sql/moz-fx-data-shared-prod/ltv_state_values_derived/dataset_metadata.yaml
Being consistent is hard :disappointed: https://mozilla-hub.atlassian.net/browse/DSRE-1755
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6924)
> Fix DS workgroup identifier

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
> Requesting newtab_visits backfill

- sql/bigconfig.yml
- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6955)
> feat: add row_creation_times to sql/bigconfig.yml

- bigquery_etl/copy_deduplicate.py
Related to DENG-6967.  This adds a `copy_dedup_` prefix to job ids from copy_deduplicate to make them easier to find.  Job id and slot usage is also added to the logs.
tested this with:
```
bqetl copy_deduplicate --project-id benwubenwutest --only org_mozilla_fenix_nightly_live.baseline_v1 --date 2024-12-08 
bqetl copy_deduplicate --project-id benwubenwutest --only org_mozilla_fenix_nightly_live.baseline_v1 --date 2024-12-08 --slices 5 --temp-dataset benwubenwutest.tmp
```
* DENG-6967
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6968)
> [DENG-6967] Add job id prefix and additional logs to copy deduplicate

- sql/moz-fx-data-shared-prod/monitoring/bigeye_usage/view.sql
- sql/moz-fx-data-shared-prod/monitoring/bigquery_usage/view.sql
- sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/query.sql
- sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/schema.yaml
> feat: add bq job labels to bigquery_usage and bigeye_usage views

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml
Query check: https://console.cloud.google.com/bigquery?sq=470293616514:4147ab6beabf4736990a224f030e4077
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6971)
> Newtab visits dec backfill completed

- sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v2/query.sql
* DENG-6985
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6986)
> change datasource from clients_first_seen_v2 to clients_first_seen_v3

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/backfill.yaml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6984)
> Initiating backfill of `newtab_clients_daily`

- sql_generators/search_v2/templates/android_focus.template.sql
- sql_generators/search_v2/templates/android_klar.template.sql
- sql_generators/search_v2/templates/fenix.template.sql
- sql_generators/search_v2/templates/ios.template.sql
- sql_generators/search_v2/templates/ios_focus.template.sql
- sql_generators/search_v2/templates/ios_klar.template.sql
- sql_generators/search_v2/templates/mobile_search_clients_daily.template.sql
- sql_generators/search_v2/templates/mobile_search_clients_engines_sources_daily.metadata.yaml
This is to enable us analysing the impact of our partnerships.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6997)
> feat(DENG-6963): pull distribution_id inside combined_search_clients for Fenix

- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v3/query.sql
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6999)
> change from clients_first_seen_v2 to v3

- sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/query.sql
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7003)
> change gclid_conversions to pull from clients_first_seen_v2 to v3

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/review_checker_microsurvey_v1/query.sql
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7012)
> change datasource from clients_first_seen_v2 to cfs_v3

- sql/moz-fx-data-shared-prod/adjust_derived/adjust_cohort_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/adjust_derived/adjust_deliverables_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/microsoft_derived/app_acquisitions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/microsoft_derived/app_conversions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/microsoft_derived/app_installs_v1/metadata.yaml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7031)
> added table_type:aggregate to these adjust and microsoft tables

- sql_generators/funnels/templates/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7032)
> Add aggregate label to funnel metadata template

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_desktop_daily_engagement_by_tile_id_position_v1/schema.yaml
This fixes the dry-run errors
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7033)
> Fix newtab_desktop_daily_engagement_by_tile_id_position_v1 schema

- sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/bigconfig.yml
- sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/bigconfig.yml
- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7052)
> feat: introduce bigconfig to android_app_campaign_stats_v1 and ios_app_campaign_stats_v1

- sql/bigconfig.yml
- sql_generators/glean_usage/templates/baseline_clients_daily_v1.bigconfig.yml
- sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.bigconfig.yml
> feat(DENG-4975): add bigconfig to baseline clients daily and first seen

- dags.yaml
- sql/moz-fx-data-shared-prod/telemetry/event_aggregates/view.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/schema.yaml
This PR creates a new table: 
- moz-fx-data-shared-prod.telemetry_derived.event_aggregates_v1
* [DENG-6892](https://mozilla-hub.atlassian.net/browse/DENG-6892)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7062)
[DENG-6892]: https://mozilla-hub.atlassian.net/browse/DENG-6892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-6892): Create new event_aggregates_v1 table

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/query.sql
This PR fixes an error in the group by clause of the sql logic
[AD-517](https://mozilla-hub.atlassian.net/browse/AD-517)
[AD-517]: https://mozilla-hub.atlassian.net/browse/AD-517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7071)
> fixing error in group by causing abundance of records

- bigquery_etl/metadata/validate_metadata.py
Temporarily removing the expiration check on `client_level` tables to prevent CI failure.
This PR can be reverted once the data retention project has been implemented.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7109)
> Temp remove client level code

- sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_new_profiles_by_os/view.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_new_profiles_by_os_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_new_profiles_by_os_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_new_profiles_by_os_v1/schema.yaml
This PR creates the following new aggregate table: 
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_new_profiles_by_os_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7141)
> Create new aggregate table for Firefox Health Indicator dashboard

- sql/moz-fx-data-shared-prod/pocket/pocket_usage/view.sql
- sql/moz-fx-data-shared-prod/pocket_derived/pocket_usage_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/pocket_derived/pocket_usage_v1/query.sql
- sql/moz-fx-data-shared-prod/pocket_derived/pocket_usage_v1/schema.yaml
Aggregations table for Pocket interactions on Firefox Android
- pocket_usage_v1: Has the Pocket usage by event type for each channel
* [DENG-7061](https://mozilla-hub.atlassian.net/browse/DENG-7061)
[DENG-7061]: https://mozilla-hub.atlassian.net/browse/DENG-7061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7145)
> DENG-7061- aggregate table for Pocket interactions on Firefox Android

- bigquery_etl/shredder/delete.py
The shredder job currently stores a `QueryJob` instance for each deletion (one per partition) which is used at the end of the job to log some stats.  Each `QueryJob` has a lot of large unneeded objects in it like table schemas and the query string, plan, and timeline which adds up because there are hundreds of thousands of jobs.  
[The last shredder-all run](https://console.cloud.google.com/monitoring/metrics-explorer;startTime=2024-12-10T17:05:36.733Z;endTime=2024-12-24T17:05:36.733Z?pageState=%7B%22xyChart%22:%7B%22constantLines%22:%5B%5D,%22dataSets%22:%5B%7B%22legendTemplate%22:%22$%7Bresource.labels.pod_name%7D%20mem%22,%22plotType%22:%22LINE%22,%22targetAxis%22:%22Y1%22,%22timeSeriesFilter%22:%7B%22aggregations%22:%5B%7B%22crossSeriesReducer%22:%22REDUCE_SUM%22,%22groupByFields%22:%5 …
> [DENG-6891] Reduce shredder memory usage by not storing full job objects

- docs/cookbooks/common_workflows.md
Fixes a typo in the documentation. (And I wanted to check that I still have permission to create PRs.)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7136)
> fix typo in workflow documentation

- sql/moz-fx-data-shared-prod/jira_service_desk/field_option/metadata.yaml
- sql/moz-fx-data-shared-prod/jira_service_desk/field_option/view.sql
- sql/moz-fx-data-shared-prod/jira_service_desk_syndicate/dataset_metadata.yaml
Syndication logic to pull in Jira service desk field option data.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7173)
> [DENG-6141] Syndication config for Jira service desk field options

- sql/moz-fx-data-shared-prod/jira_service_desk/issue/view.sql
Join request, field and issue tables to make it easier to work with in Looker
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7178)
> [DENG-6141] Jira service desk join requests, fields and issues

- sql/moz-fx-data-shared-prod/fenix/locale_aggregates/view.sql
- sql/moz-fx-data-shared-prod/fenix_derived/locale_aggregates_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/locale_aggregates_v1/query.sql
- sql/moz-fx-data-shared-prod/fenix_derived/locale_aggregates_v1/schema.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop/locale_aggregates/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/locale_aggregates_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/locale_aggregates_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/locale_aggregates_v1/schema.yaml
Implements analysis by full locale that will be covered with shredder mitigation.
* [DENG-6875](https://mozilla-hub.atlassian.net/browse/DENG-6875)
[DENG-6875]: https://mozilla-hub.atlassian.net/browse/DENG-6875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DENG-6875 create agg locale

- bqetl_project.yaml
- sql_generators/stable_views/__init__.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1940489
related to https://github.com/mozilla/bigquery-etl/commit/caf20b4544db4531ace5a93fc7f9b4714916e72c
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7174)
> [Bug 1940489] Logic to skip stable view generation for specific apps

- sql/moz-fx-data-shared-prod/fenix_derived/locale_aggregates_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/locale_aggregates_v1/metadata.yaml
Label locale_aggregates for shredder mitigation and scheduler for a 2 day lag.
[DENG-6875](https://mozilla-hub.atlassian.net/browse/DENG-6875).
[DENG-6875]: https://mozilla-hub.atlassian.net/browse/DENG-6875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Apply shredder_mitigation label and +1 day offset in scheduling.

- sql_generators/glean_usage/templates/baseline_clients_daily_v1.bigconfig.yml
- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
- sql_generators/glean_usage/templates/metrics_clients_daily.bigconfig.yml
- sql_generators/glean_usage/templates/metrics_clients_last_seen.bigconfig.yml
- sql_generators/mobile_kpi_support_metrics/templates/engagement.bigconfig.yml
- sql_generators/mobile_kpi_support_metrics/templates/new_profiles.bigconfig.yml
- sql_generators/mobile_kpi_support_metrics/templates/retention.bigconfig.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7438)
> feat(DENG-7335): Remove bigconfig null metric for normalized channel country and local

- sql/moz-fx-data-shared-prod/monitoring_derived/shredder_rows_deleted_v1/query.py
`firefox_accounts_derived.funnel_events_source_v1` was deleted after the shredder jobs ran so it can't get the table
* https://bugzilla.mozilla.org/show_bug.cgi?id=1942093
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7504)
> Bug 1942093 - Ignore deleted tables in shredder_rows_deleted

- sql/moz-fx-data-shared-prod/telemetry/network_usage/view.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/install_vs_uninstall_by_os_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/network_usage_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/network_usage_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/network_usage_v1/schema.yaml
This PR creates a new aggregate table:
- moz-fx-data-shared-prod.telemetry_derived.network_usage_v1
* [DENG-6893](https://mozilla-hub.atlassian.net/browse/DENG-6893)
[DENG-6893]: https://mozilla-hub.atlassian.net/browse/DENG-6893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7508)
> DENG-6893 Create private browsing aggregate tables

- bigquery_etl/shredder/config.py
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7086)
> DENG-6441 Handle usage_deletion_request in Shredder

- sql/moz-fx-data-shared-prod/telemetry_derived/prvt_brwsng_mode_retention_v1/query.sql
This PR just fixes a comment on a previous PR - https://github.com/mozilla/bigquery-etl/pull/6852
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7628)
> Fix outdated comment

- sql/mozfun/norm/result_type_to_product_name/udf.sql
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7629)
> Add ml_yelp to yelp suggestions

- sql/moz-fx-data-shared-prod/addons/addon_events_clients/metadata.yaml
- sql/moz-fx-data-shared-prod/addons/addon_events_clients/view.sql
- sql/moz-fx-data-shared-prod/addons/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/addons/search_detection/metadata.yaml
- sql/moz-fx-data-shared-prod/addons/search_detection/view.sql
- sql/moz-fx-data-shared-prod/addons_derived/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/addons_derived/search_detection_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/addons_derived/search_detection_v1/query.sql
- sql/moz-fx-data-shared-prod/addons_derived/search_detection_v1/schema.yaml
- sql/moz-fx-data-shared-prod/amo_prod/amo_stats_installs_v3/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7457)
> feat(DENG-7038): Addons Search Detection aggregate

- bigquery_etl/metadata/validate_metadata.py
- tests/cli/test_cli_metadata.py
the failure when calling get_table for tables with restricted permissions, see [example](https://app.circleci.com/pipelines/github/mozilla/private-bigquery-etl/5850/workflows/04bbcfdd-c2ff-4d07-ac78-9ca398cdbfbb/jobs/11024?invite=true#step-106-4244_145).
* DENG-7329
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7640)
> DENG-7329 CI check

- bigquery_etl/metadata/validate_metadata.py
- tests/cli/test_cli_metadata.py
Capture Forbidden exception to fix failure due to permissions.
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7659)
> Fix: Capture exception Forbidden

- bigquery_etl/metadata/validate_metadata.py
- tests/cli/test_cli_metadata.py
Capture generic exception to fix [CI failure](https://app.circleci.com/pipelines/github/mozilla/private-bigquery-etl/5862/workflows/42522a21-f759-4e22-a0fc-e22bb168df2c/jobs/11068?invite=true#step-106-5023_145).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7661)
> Fix: capture generic exception

- sql/moz-fx-data-shared-prod/org_mozilla_ios_fennec_derived/baseline_clients_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7669)
> feat(DENG-7650): add backfill.yaml for /org_mozilla_ios_fennec_derived/baseline_clients_daily_v1

- sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v2/query.sql
Adds label to metadata.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7691)
> Add label to metadata

- sql/moz-fx-data-shared-prod/org_mozilla_fenix_nightly_derived/baseline_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/baseline_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/baseline_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/baseline_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/baseline_clients_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7670)
> feat(DENG-7649): add backfill.yaml for baseline_clients_daily_v1 for fenix and firefox_ios app

- sql/moz-fx-data-shared-prod/org_mozilla_fenix_nightly_derived/baseline_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_ios_fennec_derived/baseline_clients_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7712)
> feat: Update backfill entry to Complete for baseline_clients_daily_v1 for firefox_ios and fenix nightly app ids

- sql/moz-fx-data-shared-prod/addons_derived/search_detection_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7721)
> feat: move addons_derived.search_detection_v1 backfill to Complete

- sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v2/query.sql
- sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v2/query.sql
Fix ping joining to avoid double counting on the same day and across days
* [DENG-7535](https://mozilla-hub.atlassian.net/browse/DENG-7535)
[DENG-7535]: https://mozilla-hub.atlassian.net/browse/DENG-7535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7736)
> Fix mobile feature usage v2

- sql/moz-fx-data-shared-prod/fenix_derived/engagement_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/new_profiles_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/retention_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/engagement_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profiles_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/backfill.yaml
feat(DENG-6890): move over mobile_kpi_support_metric_backfills to Complete
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7757)
> feat(DENG-6890): move over mobile_kpi_support_metric_backfills to Complete

- dags.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activation_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v1/metadata.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7800)
> chore: remove bani from bqetl_mobile_activation email list

- bqetl_project.yaml
- sql/moz-fx-data-shared-prod/acoustic_derived/contact_current_snapshot_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/acoustic_derived/contact_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/acoustic_derived/raw_recipient_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/acoustic_external/contact_raw_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/acoustic_external/raw_recipient_raw_v1/metadata.yaml
As part of this PR, I have added acoustics related tables
Set the partition expiration to 775
Add a label table_type: client_level
This PR will be merged after January 28th.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7768)
> DENG-7767 - Set retention on Acoustic client level tables.

- sql/moz-fx-data-shared-prod/fenix_derived/ltv_android_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/ltv_ios_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/ltv_desktop_aggregates_v1/backfill.yaml
As part of https://mozilla-hub.atlassian.net/browse/DENG-7550, this PR marks the backfill as complete
> DENG-7550 - Mark LTV agg backfill complete

- bigquery_etl/shredder/config.py
This should fix https://bugzilla.mozilla.org/show_bug.cgi?id=1945487.
Context: usage-deletion-request pings, unlike regular deletion-request pings are defined in application code so they might lack the client_id field used for joins by Shredder. This will make Shredder handle such misconfigurations.
We should also add usage_profile_id field to a check that detects tables not covered by Shredder.
cc @BenWu
> Bug 1945487 - Properly handle misconfigured usage_deletion_request pings

- sql/moz-fx-data-shared-prod/amo_prod/desktop_addons_by_client_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/amo_prod/fenix_addons_by_client_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/addon_aggregates_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/addons_v2/metadata.yaml
As part of this PR, I have added Addons client_level tables.
Set the partition expiration to 775
This PR will be merged after January 28th.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7725)
> [DO NOT merge] - DENG-7724 - Set retention on client_level tables related to Addons

- sql_generators/mobile_kpi_support_metrics/templates/engagement_clients.view.sql
- sql_generators/mobile_kpi_support_metrics/templates/retention_clients.view.sql
> feat: add os and os_version to retention_clients and engagement_clients

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/metadata.yaml
- sql_generators/glean_usage/templates/baseline_clients_daily_v1.metadata.yaml
- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.metadata.yaml
- sql_generators/glean_usage/templates/events_stream_v1.metadata.yaml
- sql_generators/glean_usage/templates/metrics_clients_daily.metadata.yaml
Add retention of 775 days on Newtab tables
> Add retention of 775 days on Newtab tables

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/metadata.yaml
- sql_generators/glean_usage/templates/baseline_clients_daily_v1.metadata.yaml
- sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.metadata.yaml
- sql_generators/glean_usage/templates/events_stream_v1.metadata.yaml
- sql_generators/glean_usage/templates/metrics_clients_daily.metadata.yaml
Reverts mozilla/bigquery-etl#6962
> Revert "Add retention of 775 days on Newtab tables"

- sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.metadata.yaml
> fix: set submission_date as the partition field

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/metadata.yaml
Apply retention on Newtab tables - https://mozilla-hub.atlassian.net/browse/DENG-7816
> DENG 7816- Apply retention on Newtab tables

- sql/moz-fx-data-shared-prod/external/holidays/view.sql
This PR adds additional holidays to the holiday view:
- Mexico's Independence Day
- Mexico's Revolution Day
- France's May Day
- France's Victory Day
- India's Republic Day
- US Superbowl Dates
* [DENG-7810](https://mozilla-hub.atlassian.net/browse/DENG-7810)
[DENG-7810]: https://mozilla-hub.atlassian.net/browse/DENG-7810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-7810): Add 6 more holidays to view external.holidays

- sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activations_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activations_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/focus_android_derived/new_profile_activations_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/focus_ios_derived/new_profile_activations_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/klar_android_derived/new_profile_activations_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/klar_ios_derived/new_profile_activations_v1/backfill.yaml
> feat(DENG-7805): move new_profile_activations_v1 backfill entry to Complete

- sql/moz-fx-data-shared-prod/microsoft_derived/app_acquisitions_v1/query.py
- sql/moz-fx-data-shared-prod/microsoft_derived/app_conversions_v1/query.py
- sql/moz-fx-data-shared-prod/microsoft_derived/app_installs_v1/query.py
This PR fixes the error of trying to subtract a timedelta from a string, thus stopping the Microsoft Store job from running
* DENG-XXXX
* DSRE-XXXX
> converts strings to dates

- sql/moz-fx-data-shared-prod/fenix_derived/new_profile_metrics_marketing_geo_testing_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_metrics_marketing_geo_testing_v1/backfill.yaml
> feat: move new_profile_metrics_marketing_geo_testing_v1 backfills to Complete

- sql/moz-fx-data-shared-prod/external/calendar/view.sql
- sql/moz-fx-data-shared-prod/external/holidays/view.sql
- This PR adds day of week and week number to the calendar view.
- This PR adds Easter Monday to the holidays view.
* [DENG-7810](https://mozilla-hub.atlassian.net/browse/DENG-7810)
* [DENG-7811](https://mozilla-hub.atlassian.net/browse/DENG-7811)
[DENG-7810]: https://mozilla-hub.atlassian.net/browse/DENG-7810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DENG-7811]: https://mozilla-hub.atlassian.net/browse/DENG-7811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Calendar & holiday view additions

- sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
- sql_generators/glean_usage/templates/baseline_clients_last_seen.view.sql
Adding view for active users based on baseline ping
* DENG-7840
> DENG-7840 - Adding baseline active users

- sql/moz-fx-data-shared-prod/external/gdp/view.sql
- sql/moz-fx-data-shared-prod/external_derived/gdp_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/external_derived/gdp_v1/query.py
- sql/moz-fx-data-shared-prod/external_derived/gdp_v1/schema.yaml
- sql/moz-fx-data-shared-prod/external_derived/inflation_v1/query.py
This PR creates:
- moz-fx-data-shared-prod.external_derived.gdp_v1
* [DENG-7790](https://mozilla-hub.atlassian.net/browse/DENG-7790)
[DENG-7790]: https://mozilla-hub.atlassian.net/browse/DENG-7790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-7780): Create new gdp_v1 table to load IMF data

- sql/moz-fx-data-shared-prod/monitoring/payload_bytes_error_all/metadata.yaml
- sql/moz-fx-data-shared-prod/monitoring/payload_bytes_error_all/view.sql
> chore: authorize payload_bytes_error_all

- sql/moz-fx-data-shared-prod/fenix_derived/profile_dau_metrics_marketing_geo_testing_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/profile_dau_metrics_marketing_geo_testing_v1/backfill.yaml
> feat(DENG-7842): add backfill entry for profile_dau_metrics_marketing_geo_testing_v1 (fenix and ios)

- sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/query.sql
This adds channel values for structured schema errors by parsing channel from the payload of structured payload_bytes_error since channel isn't in the uri like for telemetry.  This should let us see error counts per channel for glean
I tested this with `moz-fx-data-shared-prod.errors.structured_firefox_desktop__metrics_v1` since I can't query PBE anymore
* DENG-7209
> [DENG-7209] Add channel value to schema errors from structured

- sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/backfill.yaml
> Complete schema_error_counts_v2 backfill

- sql_generators/usage_reporting/templates/app_union.view.sql.jinja
> fix: make sure firefox_desktop app_id is set correctly in the union view

- sql/moz-fx-data-shared-prod/telemetry/cohort_daily_statistics/view.sql
This PR adds additional fields to the cohort_daily_statistics view
* [DENG-2986](https://mozilla-hub.atlassian.net/browse/DENG-2986)
[DENG-2986]: https://mozilla-hub.atlassian.net/browse/DENG-2986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-2986): Update cohort_daily_statistics view

- sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py
* Normandy was retired, so we don't need to import Normandy experiments anymore from the Experimenter v1 API
* Uses the new v8 API to fetch Nimbus experiments, which was created specifically for data/analysis so that v6 can be exclusively for clients
* DENG-7922
> chore: remove normandy experiments; use v8 API for nimbus

- sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.metadata.yaml.jinja
- sql_generators/usage_reporting/templates/usage_reporting_clients_last_seen_v1.metadata.yaml.jinja
Set retention for `usage_reporting_clients_daily_v1` and `usage_reporting_clients_last_seen_v1` to `775` days.
> feat: apply retention on usage_reporting_clients daily and last_seen

- sql/moz-fx-data-shared-prod/fenix/tos_rollout_enrollments/view.sql
- sql/moz-fx-data-shared-prod/fenix_derived/tos_rollout_enrollments_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/tos_rollout_enrollments_v1/query.sql
- sql/moz-fx-data-shared-prod/fenix_derived/tos_rollout_enrollments_v1/schema.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop/tos_rollout_enrollments/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/tos_rollout_enrollments_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/tos_rollout_enrollments_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/tos_rollout_enrollments_v1/schema.yaml
- sql/moz-fx-data-shared-prod/firefox_ios/tos_rollout_enrollments/view.sql
- sql/moz-fx-data-shared-prod/firefox_ios_derived/tos_rollout_enrollments_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/tos_rollout_enrollments_v1/query.sql
- sql/moz-fx-data-shared-prod/firefox_ios_derived/tos_rollout_enrollments_v1/schema.yaml
In support of [this ticket](https://mozilla-hub.atlassian.net/browse/DS-3987).
> Creating ToS enrollments tables for monitoring of ToS rollout

- sql/moz-fx-data-shared-prod/fenix_derived/tos_rollout_enrollments_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/tos_rollout_enrollments_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/tos_rollout_enrollments_v1/backfill.yaml
complete backfill of tos_rollout_enrollments (see #7090)
N/A
> chore: complete tos_rollout_enrollments backfill

- sql/moz-fx-data-shared-prod/telemetry/fx_accounts_active_daily_clients/view.sql
This PR updates the view:
- moz-fx-data-shared-prod.telemetry.fx_accounts_active_daily_clients`
* [DENG-7899](https://mozilla-hub.atlassian.net/browse/DENG-7899)
[DENG-7899]: https://mozilla-hub.atlassian.net/browse/DENG-7899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-7899): Add join to baseline_active_users

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/backfill.yaml
This PR completes the managed backfill for:
- moz-fx-data-shared-prod.firefox_desktop_derived.baseline_active_users_aggregates_v1
> Complete backfill of baseline_active_users_aggregates_v1

- dags.yaml
- sql/moz-fx-data-shared-prod/external/population/view.sql
- sql/moz-fx-data-shared-prod/external/population_by_country/view.sql
- sql/moz-fx-data-shared-prod/external_derived/population_v1/checks.sql
- sql/moz-fx-data-shared-prod/external_derived/population_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/external_derived/population_v1/query.py
- sql/moz-fx-data-shared-prod/external_derived/population_v1/schema.yaml
This PR creates:
- moz-fx-data-shared-prod.external_derived.population_v1
- moz-fx-data-shared-prod.external.population_v1
Plus, a new DAG that loads the latest population data each year annually on February 15th.
* [DENG-7787](https://mozilla-hub.atlassian.net/browse/DENG-7787)
[DENG-7787]: https://mozilla-hub.atlassian.net/browse/DENG-7787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-7787): Create external_derived.population_v1

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/backfill.yaml
This PR completes the managed backfill of:
- moz-fx-data-shared-prod.firefox_desktop_derived.baseline_active_users_aggregates_v1
* [DENG-7860](https://mozilla-hub.atlassian.net/browse/DENG-7860)
[DENG-7860]: https://mozilla-hub.atlassian.net/browse/DENG-7860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DENG-7860 - complete managed backfill for firefox_desktop_derived.baseline_active_users_aggregates_v1

- sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja
> feat: add and rename some fields to make them more consistent with baseline_active_users for consistency

- sql/moz-fx-data-shared-prod/fxci_derived/task_run_costs_v1/query.sql
> fix(fxci): update task_run_costs/query.sql to point to base tables

- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_recovery_phones_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_recovery_phones_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_external/fxa_recovery_phones_v1/schema.yaml
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_recovery_phones_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_recovery_phones_v1/query.sql
- sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_recovery_phones_v1/schema.yaml
Adds recoveryPhones table to accounts database
* SVCSE-2521
/cc @akkomar @sean-rose
> Add recoveryPhones to accounts db. Fix SVCSE-2521

- bqetl_project.yaml
Adding release channel to the usage_reporting generation.
> feat(): add release channel to usage_reporting fenix and ios configuration

- bqetl_project.yaml
- sql/moz-fx-data-shared-prod/telemetry/fx_accounts_linked_clients/view.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_v1/schema.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_v1/script.sql
This PR creates a new table and view:
- moz-fx-data-shared-prod.telemetry_derived.fx_accounts_linked_clients_v1
- moz-fx-data-shared-prod.telemetry.fx_accounts_linked_clients
* [DENG-7900](https://mozilla-hub.atlassian.net/browse/DENG-7900)
[DENG-7900]: https://mozilla-hub.atlassian.net/browse/DENG-7900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-7900): Create fx_accounts_linked_clients_v1

- sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users_aggregates/view.sql
- sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates.view.sql.jinja
- sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.metadata.yaml.jinja
- sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.query.sql.jinja
- sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.schema.yaml.jinja
> feat: add usage_reporting_active_users_aggregates templates

- sql/moz-fx-data-shared-prod/telemetry_derived/cohort_weekly_statistics_v1/query.sql
This PR updates the query logic to fix some issues with the original logic.
* DENG-7970
> fix(DENG-7970): Update SQL logic for cohort_weekly_statistics_v1

- sql/moz-fx-data-shared-prod/external/holidays/view.sql
This PR adds 1 new column called "holiday_array" to the view mozdata.external.holidays
* [DENG-7906](https://mozilla-hub.atlassian.net/browse/DENG-7906)
[DENG-7906]: https://mozilla-hub.atlassian.net/browse/DENG-7906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-7906): Add new column to view

- sql_generators/usage_reporting/__init__.py
- sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja
- sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates.view.sql.jinja
- sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.query.sql.jinja
- sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.schema.yaml.jinja
depends on: https://github.com/mozilla/bigquery-etl/pull/7072
> feat(DENG-7865): make sure the usage_reporting_active_users_aggregates templates are rendered and writen to file

- sql_generators/mobile_kpi_support_metrics/__init__.py
- sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.metadata.yaml
- sql_generators/mobile_kpi_support_metrics/templates/engagement.metadata.yaml
- sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.metadata.yaml
- sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.metadata.yaml
- sql_generators/mobile_kpi_support_metrics/templates/new_profiles.metadata.yaml
- sql_generators/mobile_kpi_support_metrics/templates/retention.metadata.yaml
> feat(DENG-7989): disable Bigeye monitoring for all mobile products except firefox_ios and fenix

- sql/moz-fx-data-shared-prod/bugzilla_metrics/dataset_metadata.yaml
See https://mozilla-hub.atlassian.net/browse/DENG-8042?focusedCommentId=1028332
> DENG-8042 Set phabricator-metrics/external workgroup access on bugzilla_metrics dataset

- sql/moz-fx-data-shared-prod/external_derived/monthly_inflation_v1/query.py
- sql/moz-fx-data-shared-prod/external_derived/quarterly_inflation_v1/query.py
This PR adds more countries to pull inflation data for.
* [DENG-7785](https://mozilla-hub.atlassian.net/browse/DENG-7785)
[DENG-7785]: https://mozilla-hub.atlassian.net/browse/DENG-7785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-7785): Add more countries to pull inflation data for

- sql/moz-fx-data-shared-prod/external_derived/imf_exchange_rates_v1/query.py
This PR adds a few more countries to pull data for into:
- moz-fx-data-shared-prod.external_derived.imf_exchange_rates_v1
* [DENG-8067](https://mozilla-hub.atlassian.net/browse/DENG-8067)
[DENG-8067]: https://mozilla-hub.atlassian.net/browse/DENG-8067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-8067): Add more countries to IMF Exchange Rates

- sql/moz-fx-data-shared-prod/google_play_store/dataset_metadata.yaml
- sql/moz-fx-data-shared-prod/google_play_store_derived/dataset_metadata.yaml
This PR creates 2 new datasets:
- google_play_store
- google_play_store_derived
These will be used to store multiple tables generated from data loaded from the Google Play Store developer reporting API.
> feat(DENG-7931): Create 2 new datasets

- sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_and_version_v1/query.py
- sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_v1/query.py
- sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_v1/schema.yaml
This PR adds a new column "nbr_distinct_users" to the table: 
- moz-fx-data-shared-prod.google_play_store_derived.slow_startup_events_by_startup_type_v1
> Add new column to slow_startup_events_by_startup_type_v1

- sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/query.py
This is a minor follow up to [PR-7211](https://github.com/mozilla/bigquery-etl/pull/7211) , fixing 1 issue that was missed in the last PR that was causing duplicates inserted in the final table
> Fix parsing of updated API logic

- sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/query.py
* Cloudflare recently changed the URL for browser data, so this PR updates the URL, and also adds logic to raise an error if more than 10% of the rows returned are errors.
> Update Cloudflare Browser API URL - also changed recently

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/schema.yaml
This PR adds UAPI data for Ads reporting
[AD-318](https://mozilla-hub.atlassian.net/browse/AD-681)
[AD-318]: https://mozilla-hub.atlassian.net/browse/AD-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> AD-318 adding uapi data

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/backfill.yaml
Testing backfilling `newtab_interactions_hourly_v1`
> Run test backfill of newtab_interactions_hourly_v1

- sql/moz-fx-data-shared-prod/telemetry/cohort_daily_statistics/view.sql
This PR adds the new column `play_store_attribution_install_referrer_response` to the view:
- moz-fx-data-shared-prod.telemetry.cohort_daily_statistics
> Expose new column in view

- sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/usage_reporting_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_focus_derived/usage_reporting_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/usage_reporting_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_ios_focus_derived/usage_reporting_clients_daily_v1/backfill.yaml
> feat: add backfill entry for usage_reporting clients daily focus android and ios

- sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/usage_reporting_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_focus_derived/usage_reporting_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/usage_reporting_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_ios_focus_derived/usage_reporting_clients_daily_v1/backfill.yaml
> feat: update focus usage_reporting_daily backfill to Complete status

- bqetl_project.yaml
> feat: add more apps to glean generation bigconfig skip apps

- sql/mozfun/marketing/parse_campaign_name/udf.sql
This PR updates the logic for the UDF and adds 1 more test to check it's working as expected
- mozfun.marketing.parse_campaign_name
* [DENG-8083](https://mozilla-hub.atlassian.net/browse/DENG-8083?linkSource=email)
[DENG-8083]: https://mozilla-hub.atlassian.net/browse/DENG-8083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-8083): Update UDF logic

- sql/moz-fx-data-shared-prod/sumo_ga_derived/ga4_events_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/sumo_ga_derived/ga4_events_v1/query.sql
This PR updates the source for GA4 SUMO data to the correct property ID. 
> SUMO GA4 update

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/schema.yaml
This PR adds the form_factor field from UAPI data into `newtab_interactions_hourly_v1`
* [AD-681](https://mozilla-hub.atlassian.net/browse/AD-681)
[AD-681]: https://mozilla-hub.atlassian.net/browse/AD-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> adding new column form_factor

- sql_generators/glean_usage/glean_app_ping_views.py
In https://github.com/mozilla/bigquery-etl/pull/7234, the metadata for [fenix.broken_site_report](https://github.com/mozilla/bigquery-etl/pull/7234/files#diff-8a5e413301d99fc5429e17a1daa1d2641aa6f38f76b2ec8129368f73323289a0) gets overwritten by the app ping view generation.  This change should merge the existing metadata.  sql.diff isn't showing the full file diff but I tested this locally and it works
* DENG-8101
> [DENG-8101] Merge existing metadata.yaml in glean app union views

- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v2/checks.sql
- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v2/metadata.yaml
- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v2/query.sql
- sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v2/schema.yaml
This PR creates the following new table:
- moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v2
* [DENG-8173](https://mozilla-hub.atlassian.net/browse/DENG-8173)
[DENG-8173]: https://mozilla-hub.atlassian.net/browse/DENG-8173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-8173): Create android_app_campaign_stats_v2

- sql/moz-fx-data-shared-prod/google_ads/android_app_campaign_stats/view.sql
This commit is to modify the view of the campaign reporting table to use GCLID methodology
* DENG-XXXX
* DSRE-XXXX
> Update view.sql to leverage v2 of the underlying table

- sql/moz-fx-data-shared-prod/google_ads/android_app_campaign_stats/view.sql
This PR extends the view for:
- moz-fx-data-shared-prod.google_ads.android_app_campaign_stats
* [DENG-8173](https://mozilla-hub.atlassian.net/browse/DENG-8173)
[DENG-8173]: https://mozilla-hub.atlassian.net/browse/DENG-8173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DENG-8173 - Add to google_ads.android_app_campaign_stats view

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_dau_distribution_id_history_v1/metadata.yaml
- sql_generators/usage_reporting/templates/usage_reporting_clients_first_seen_v1.metadata.yaml.jinja
> feat(DENG-7895): apply retention rules on datasets that were created as part of tos workstream

- sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_active_daily_clients_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_active_daily_clients_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_active_daily_clients_v1/schema.yaml
This PR updates the schema and query for fx_accounts_active_daily_clients_v1 to include the new "attribution" and "distribution" fields
> Update schema for fx_accounts_active_daily_clients_v1

- sql_generators/usage_reporting/usage_reporting.py
> feat(DENG-8074): add testing to usage reportin generator (part 2)

- sql/moz-fx-data-shared-prod/telemetry_derived/newtab_merino_priors_v1/query.sql
This PR fixes a bug in the Merino job where the `recommended_at` timestamp is picking up values outside of an allowed range
Additionally restructuring to use a CTE in place of the subquery
[bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1958880)
> filtering out invalid dates

- sql/moz-fx-data-shared-prod/fenix_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/focus_android_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/focus_ios_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
> feat: mark usage_reporting_active_users_aggregates_v1 2025-04-03 backfill entry as Complete

- sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_active_daily_clients_v1/schema.yaml
This PR updates the schema.yaml file for telemetry_derived.fx_accounts_active_daily_clients_v1 to include the newly added fields ext in each that were added via [PR-7293](https://github.com/mozilla/bigquery-etl/pull/7293)
> Update schema to match added columns

- sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users_aggregates/view.sql
- sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja
- sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates.view.sql.jinja
> fix: use version extract instead of truncate UDF for expected behaviour

- sql/moz-fx-data-shared-prod/external/chrome_extensions/view.sql
- sql/moz-fx-data-shared-prod/external_derived/chrome_extensions_v1/schema.yaml
* This PR adds the new column `featured` to the table `moz-fx-data-shared-prod.external_derived.chrome_extensions_v1`
* It also adds 2 columns to the view `moz-fx-data-shared-prod.external.chrome_extensions`, `featured` and `trader_status`
* [DENG-8090](https://mozilla-hub.atlassian.net/browse/DENG-8090)
[DENG-8090]: https://mozilla-hub.atlassian.net/browse/DENG-8090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-8090): Add featured column to chrome_extensions_v1

- sql/moz-fx-data-shared-prod/udf/hr_cost_center_to_steering_committee/udf.sql
- sql/moz-fx-data-shared-prod/udf/hr_steering_committee_to_group_name/udf.sql
This PR adds arguments to the UDFs that were missing before
* DENG-8249
* DSRE-XXXX
> add argument to UDF

- sql/moz-fx-data-shared-prod/external/chrome_extensions/view.sql
- sql/moz-fx-data-shared-prod/external_derived/chrome_extensions_v1/schema.yaml
This PR adds the new column `manifest_json` to:
- moz-fx-data-shared-prod.external_derived.chrome_extensions_v1
- moz-fx-data-shared-prod.external.chrome_extensions
* [DENG-8090](https://mozilla-hub.atlassian.net/browse/DENG-8090)
[DENG-8090]: https://mozilla-hub.atlassian.net/browse/DENG-8090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-8090): Add manifest json

- bigquery_etl/format_sql/format.py
To make it easier to find and fix the problem in the SQL file.
n/a
> fix(bqetl): Have `bqetl format` print any parse errors it runs into

- sql/moz-fx-data-shared-prod/search/mobile_search_clients_engines_sources_daily/view.sql
This appear to be causing the view deploy to error.
> Remove trailing semicolon

- sql/moz-fx-data-shared-prod/crash_ping_ingest_external/dataset_metadata.yaml
This PR adds a bit of extra information to the description of the crash_ping_ingest_external dataset.
> Elaborate the description of the crash_ping_ingest_external dataset

- sql_generators/usage_reporting/usage_reporting.py
- tests/sql_generators/usage_reporting/test_usage_reporting.py
> feat: move render loading, rendering, and writing to file to a separate function

- dags.yaml
- sql/moz-fx-data-shared-prod/telemetry/ech_adoption_rate/view.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/ech_adoption_rate_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/telemetry_derived/ech_adoption_rate_v1/query.sql
- sql/moz-fx-data-shared-prod/telemetry_derived/ech_adoption_rate_v1/schema.yaml
This PR publishes the dataset ECH adoption rate.
See bug: [1957082](https://bugzilla.mozilla.org/show_bug.cgi?id=1957082)
* DENG-8381
> bug 1957082: Publish ECH adoption rate

- dags.yaml
- sql/moz-fx-data-shared-prod/external/us_unemployment/view.sql
- sql/moz-fx-data-shared-prod/external_derived/us_unemployment_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/external_derived/us_unemployment_v1/query.py
- sql/moz-fx-data-shared-prod/external_derived/us_unemployment_v1/schema.yaml
- sql_generators/stable_views/__init__.py
This PR creates a new table and view:
- moz-fx-data-shared-prod.external_derived.us_unemployment_v1
- moz-fx-data-shared-prod.external.us_unemployment_v1
* [DENG-8324](https://mozilla-hub.atlassian.net/browse/DENG-8324)
[DENG-8324]: https://mozilla-hub.atlassian.net/browse/DENG-8324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-8324): Create external_derived.us_unemployment_v1

- sql/moz-fx-data-shared-prod/fenix/nimbus_recorded_targeting_context/view.sql
- sql/moz-fx-data-shared-prod/fenix_derived/nimbus_recorded_targeting_context_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/fenix_derived/nimbus_recorded_targeting_context_v1/query.sql
This PR adds the Nimbus recorded targeting context query for `fenix`.
* https://mozilla-hub.atlassian.net/browse/EXP-5486
> Nimbus recorded targeting context v1 for Fenix

- sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_joined_v1/query.sql
Reservation names are being changed in https://mozilla-hub.atlassian.net/browse/DSRE-1918 and could change again in the future so we can just filter based on the shredder project ids
* DSRE-1918
> Change shredder job filtering in shredder_targets

- sql/moz-fx-data-shared-prod/org_mozilla_fenix_nightly_derived/baseline_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/baseline_clients_daily_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/baseline_clients_daily_v1/backfill.yaml
follow-up to: https://github.com/mozilla/bigquery-etl/pull/7443
> feat: update baseline_clients_daily_v1 2025-05-14 backfill entries to Complete

- sql/moz-fx-data-shared-prod/fenix_derived/nimbus_recorded_targeting_context_v1/backfill.yaml
Add backfill for nimbus_recorded_targeting_context_v1
* https://mozilla-hub.atlassian.net/browse/EXP-5497
> feat: add nimbus_recorded_targeting_context_v1 fenix backfill

- sql/moz-fx-data-shared-prod/fenix_derived/nimbus_recorded_targeting_context_v1/backfill.yaml
Updating the status of my backfill to complete!
* https://mozilla-hub.atlassian.net/browse/EXP-5497
> update nimbus targeting context fenix backfill status to complete

- sql/moz-fx-data-shared-prod/glean_telemetry/active_users_aggregates/view.sql
This PR fixes an incorrect change I made in [PR-7464](https://github.com/mozilla/bigquery-etl/pull/7464)
* [DENG-8439](https://mozilla-hub.atlassian.net/browse/DENG-8439)
[DENG-8439]: https://mozilla-hub.atlassian.net/browse/DENG-8439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(DENG-8439): Update glean_telemetry.active_users_aggregates

- sql/moz-fx-data-shared-prod/fenix_derived/attribution_clients_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/attribution_clients_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/focus_android_derived/attribution_clients_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/focus_ios_derived/attribution_clients_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/klar_android_derived/attribution_clients_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/klar_ios_derived/attribution_clients_v1/backfill.yaml
depends on: https://github.com/mozilla/bigquery-etl/pull/7395
> feat(DENG-8556): add backfill.yaml to attribution_clients_v1 queries

- sql/mozfun/norm/windows_version_info/udf.sql
> DENG-8571 - Fix for mozfun.norm.windows_version_info

- .pre-commit-config.yaml
- bigquery_etl/cli/backfill.py
- tests/cli/test_cli_backfill.py
> feat: add bqetl_backfill_validate pre-commit hook

- sql/moz-fx-data-shared-prod/udf/organic_vs_paid_mobile_gclid_attribution/metadata.yaml
- sql/moz-fx-data-shared-prod/udf/organic_vs_paid_mobile_gclid_attribution/udf.sql
This PR creates a new UDF:
- moz-fx-data-shared-prod.udf.organic_vs_paid_mobile_gclid_attribution
* [DENG-8140](https://mozilla-hub.atlassian.net/browse/DENG-8140)
[DENG-8140]: https://mozilla-hub.atlassian.net/browse/DENG-8140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-8140): Create new UDF organic_vs_paid_mobile_gclid_attribution

- sql_generators/active_users_deletion_requests/templates/metadata_deletion_request.yaml
Minor follow-up fix to [PR-7502](https://github.com/mozilla/bigquery-etl/pull/7502)
> Add parameters back

- sql/moz-fx-data-shared-prod/firefoxdotcom/www_site_hits/view.sql
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_hits_v1/checks.sql
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_hits_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_hits_v1/query.sql
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_hits_v1/schema.yaml
> add files for firefox.com www_site_hits

- sql/moz-fx-data-shared-prod/firefox_desktop/newtab_clients_daily/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop/newtab_clients_daily_aggregates/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop/newtab_clients_daily_aggregates/view.sql
- sql/moz-fx-data-shared-prod/firefox_desktop/newtab_visits_daily/metadata.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop/newtab_visits_daily/view.sql
Create a view newtab_visits for newtab_visits_daily_v2 in firefox_desktop and introduce a placeholder field app_name with value “Firefox Desktop”
* DENG-8758
> DENG-8758-Add app_name for newtab views

- sql/moz-fx-data-shared-prod/firefoxdotcom/www_site_landing_page_metrics/view.sql
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_landing_page_metrics_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_landing_page_metrics_v1/query.sql
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_landing_page_metrics_v1/schema.yaml
This PR creates the new table and corresponding view:
`moz-fx-data-shared-prod.firefoxdotcom_derived.www_site_landing_page_metrics_v1`
`moz-fx-data-shared-prod.firefoxdotcom.www_site_landing_page_metrics`
* DENG-8679
* DSRE-XXXX
> initial add of files

- sql/moz-fx-data-shared-prod/telemetry/experiment_enrollment_cumulative_population_estimate_v2/view.sql
- sql/moz-fx-data-shared-prod/telemetry/experiment_enrollment_daily_active_population_v2/view.sql
- sql/moz-fx-data-shared-prod/telemetry/experiment_enrollment_other_events_overall_v2/view.sql
- sql/moz-fx-data-shared-prod/telemetry/experiment_enrollment_overall_v2/view.sql
- sql/moz-fx-data-shared-prod/telemetry/experiment_unenrollment_overall_v2/view.sql
Should be the final updates needed to fully reconstruct the experiment enrollments dashboard with only glean. Follow-on to https://github.com/mozilla/bigquery-etl/pull/7557 and https://github.com/mozilla/bigquery-etl/pull/7534
* EXP-4979
> feat: add final views for enrollment dashboard fully glean

- sql/moz-fx-data-shared-prod/glean_auto_events_derived/daily_auto_events_metadata_v1/query.sql
> Add pageload events to Glean Dictionary auto_events_metadata for FxA

- sql/moz-fx-data-shared-prod/remote_settings_logs_agggregates_syndicate/dataset_metadata.yaml
Fixes https://github.com/mozilla/bigquery-etl/pull/7584
> fixup: feat(DENG-8567): create a dataset syndicate for Remote Settings CDN logs aggregates

- sql/moz-fx-data-shared-prod/firefoxdotcom/ga_desktop_conversions/view.sql
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/ga_desktop_conversions_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/ga_desktop_conversions_v1/query.sql
- sql/moz-fx-data-shared-prod/firefoxdotcom_derived/ga_desktop_conversions_v1/schema.yaml
This PR creates the following table & associated view:
- `moz-fx-data-shared-prod.firefoxdotcom_derived.ga_desktop_conversions_v1`
- `moz-fx-data-shared-prod.firefoxdotcom.ga_desktop_conversions`
* [DENG-8690](https://mozilla-hub.atlassian.net/browse/DENG-8690)
[DENG-8690]: https://mozilla-hub.atlassian.net/browse/DENG-8690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-8690): Create firefoxdotcom.ga_desktop_conversions

- sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_items_updated_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/snowflake_migration_derived/rejected_corpus_items_v1/backfill.yaml
confirm/complete the backfill process from #7622.
> complete backfill of snowflake models:

- sql/moz-fx-data-shared-prod/snowflake_migration_derived/stg_reviewed_corpus_items_v1/schema.yaml
This is failing dry runs because a field is missing from the schema https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/49870/workflows/c7bb2c51-2947-4451-b833-019f8adb059a/jobs/596743
I'm not sure about the field description
> Add excerpt to stg_reviewed_corpus_items schema

- sql/moz-fx-data-shared-prod/bigeye_derived/dataset_metadata.yaml
> feat: add bigeye_derived namespace

- sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/script.sql
This PR adds the new ten tabs newsletter to the subscription map.
* DENG-8906
> DENG-8906 Adding ten tabs subscription to braze subscription map

- sql/moz-fx-data-shared-prod/snowflake_migration_derived/scheduled_articles_report_v1/query.sql
remove ORDER BY clause causing errors
> fix(scheduled articles ETL): remove ORDER BY clause causing errors

- sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_logical_subscriptions_history_v1/query.sql
- sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_history_v1/query.sql
This PR makes use of a workaround SubPlat has implemented for Fivetran not syncing the data related to Stripe's multi-currency prices feature ([FXA-10382](https://mozilla-hub.atlassian.net/browse/FXA-10382)).
* DENG-4218: Update SubPlat ETL to support Stripe multi-currency plans
* [FXA-10382](https://mozilla-hub.atlassian.net/browse/FXA-10382): DE: Add currency and amount to subscription metadata
[FXA-10382]: https://mozilla-hub.atlassian.net/browse/FXA-10382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FXA-10382]: https://mozilla-hub.atlassian.net/browse/FXA-10382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> feat(SubPlat): Update SubPlat ETLs to use workaround for Stripe multi-currency prices (DENG-4218)

- sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospects_v1/query.sql
add app id verification when building prospects_v1 model
* DENG-9044
> chore(DENG-9044): add app id verification when building prospects_v1 model

- dags.yaml
- sql/moz-fx-data-shared-prod/braze_external/add_ons_devs_users_sync_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/braze_external/add_ons_devs_users_sync_v1/query.sql
- sql/moz-fx-data-shared-prod/braze_external/add_ons_devs_users_sync_v1/schema.yaml
This PR builds the sync table to sync Add-ons developers to Braze for a one-off email send.
* DENG-8894
> DENG-8894 Build table to sync Add-ons developers list to Braze

- .circleci/workflows.yml
I messed up.  Fix for https://github.com/mozilla/bigquery-etl/pull/7758
> Fix PRIVATE_BIGQUERY_ETL_SHA path in CI

- dags.yaml
This PR updates the start date and removes catchup on the DAG
> Fix: test moving model to public

- sql/moz-fx-data-shared-prod/fenix_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_desktop_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/firefox_ios_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/focus_android_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
- sql/moz-fx-data-shared-prod/focus_ios_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
https://mozilla-hub.atlassian.net/browse/DENG-9112. Marking the backfills as complete
> DENG-9112- Mark backfills as complete

- tests/sql_generators/mobile_kpi_support_metrics/expected/moz-fx-data-shared-prod/fenix_derived/new_profile_activation_clients_v1/bigconfig.yml
- tests/sql_generators/mobile_kpi_support_metrics/expected/moz-fx-data-shared-prod/fenix_derived/new_profile_activations_v1/bigconfig.yml
- tests/sql_generators/mobile_kpi_support_metrics/expected/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_clients_v1/bigconfig.yml
- tests/sql_generators/mobile_kpi_support_metrics/expected/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activations_v1/bigconfig.yml
> fix: correct new_profile_activations and activation_clients expected test results

- bigquery_etl/shredder/delete.py
Some things I noticed while looking at DENG-9170.  Creating a separate PR because I don't think that ticket is going to be done
- copy jobs aren't being waited on correctly so they can fail silently
- the temp tables don't have dataset so there could be collisions
> Fix copy job waiting in shredder

- sql/moz-fx-data-shared-prod/shepherd/dataset_metadata.yaml
This PR adds syndication for the shepherd dataset.
* DENG-9005
> DENG-9005 adding shepherd syndication

- sql/moz-fx-data-shared-prod/bigeye_derived/group_service_v1/schema.yaml
- sql/moz-fx-data-shared-prod/bigeye_derived/issue_service_v1/schema.yaml
This PR is a minor follow-up fix to [PR-7808](https://github.com/mozilla/bigquery-etl/pull/7808), it updates the schema.yaml file to match the desired schema already in production.
* [DENG-9041](https://mozilla-hub.atlassian.net/browse/DENG-9041)
[DENG-9041]: https://mozilla-hub.atlassian.net/browse/DENG-9041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(DENG-9041): Update issue_service_v1 schema to match prod table

- sql/moz-fx-data-shared-prod/bigeye_derived/collection_service_v1/schema.yaml
This PR corrects the schema.yaml file for the table: 
- `moz-fx-data-shared-prod.bigeye_derived.collection_service_v1`
> feat(DENG-9037): Update schema to match prod table

- sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
Fixing typos introduced in https://github.com/mozilla/bigquery-etl/pull/7863
* DENG-XXXX
* DSRE-XXXX
> [AD-984] Correcting typos

- sql/moz-fx-data-shared-prod/monitoring_derived/metadata_standardization_v1/query.sql
- sql/moz-fx-data-shared-prod/monitoring_derived/metadata_standardization_v1/schema.yaml
Count standardization ignoring NULLs, only counting not-null descriptions.
ads-data-asset: Table to monitoring improvements in metadata completeness and standardization.
AD-987
> Follow up for precision.

- sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
- sql/moz-fx-data-shared-prod/static/country_codes_v1/schema.yaml
Undoing my shenanigans:
- https://github.com/mozilla/bigquery-etl/pull/7882
- https://github.com/mozilla/bigquery-etl/pull/7863
- https://github.com/mozilla/bigquery-etl/pull/7354
* DENG-XXXX
* DSRE-XXXX
> [AD-984] Regressing to previous schema and updating flags as per latest contractual sheet

- sql/bigconfig.yml
> add composite_key_uniqueness_3_column to the list of saved metrics in sql/bigconfig.yml

- sql/moz-fx-data-shared-prod/app_store_v2_syndicate/dataset_metadata.yaml
feat(DENG-9250): add syndicate dataset for firefox_app_store_v2
* DENG-XXXX
* DSRE-XXXX
> feat(DENG-9250): add syndicate dataset for firefox_app_store_v2

- sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v1/schema.yaml
This is a PR to correct a typo in a PR from yesterday, [PR-7991](https://github.com/mozilla/bigquery-etl/pull/7991) , where I was adding some column descriptions to existing tables.
> fix(metadata-completeness): Fix typo in schema.yaml

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_clients_daily_v2/query.sql
Bug Fix for [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1985368) related to recent changes newtab visits view 
> Fix for Bug 1985368 associated with newtab visits view updates

- docs/reference/recommended_practices.md
This PR adds documentation regarding creation of UDFs in `private-bigquery-etl` and the need to create stub files for said UDFs in `bigquery-etl`
* DENG-8576
> deng-8576 add details about how to add udfs in private-bqetl

- docs/reference/recommended_practices.md
This PR adds back the location of the stub file, written explicitly so readers do not have to click a link
* DENG-8576
> deng-8576 add in the location of where the stub file should be placed

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_component_content_v1/backfill.yaml
This PR backfills this new table
> backfilling new table

- dags.yaml
- requirements.in
- requirements.txt
- sql/moz-fx-data-shared-prod/external/fred_daily_exchange_rates/view.sql
- sql/moz-fx-data-shared-prod/external_derived/fred_daily_exchange_rates_v1/metadata.yaml
- sql/moz-fx-data-shared-prod/external_derived/fred_daily_exchange_rates_v1/query.py
- sql/moz-fx-data-shared-prod/external_derived/fred_daily_exchange_rates_v1/schema.yaml
This PR creates the new table and view: 
- `moz-fx-data-shared-prod.external_derived.fred_daily_exchange_rates_v1`
- `moz-fx-data-shared-prod.external.fred_daily_exchange_rates`
* [DENG-9518](https://mozilla-hub.atlassian.net/browse/DENG-9518)
[DENG-9518]: https://mozilla-hub.atlassian.net/browse/DENG-9518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(DENG-9518): Create new daily exchange rate table

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_component_content_v1/backfill.yaml
This PR completes the backfill on `newtab_component_content`
> completing backfill

- sql_generators/events_daily/templates/events_daily_v1/query.sql
Quick workaround to stop this query failing in some cases.
Note: this is eventually [planned for removal ](https://mozilla-hub.atlassian.net/browse/DENG-7638) so I didn't spend too much time optimizing it.
> Bug 1986081 - Fix events_daily generator

- bigquery_etl/routine/publish_routines.py
This publishes UDFs in parallel using `ParallelTopologicalSorter`, which still considers any dependencies a UDF might have and publishes them first. 
When I tested this locally deploying UDFs to `moz-fx-data-shared-prod` the time it took to publish was around 50s vs 3.5minutes when running the deploys sequentially.
This should have some impact on stage deploys as well as artifact deploys.
> [DENG-9397] Publish UDFs in parallel using ParallelTopologicalSorter

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_content_items_daily_v1/backfill.yaml
> complete newtab content items daily backfill

- sql/moz-fx-data-shared-prod/firefox_desktop_derived/enterprise_metrics_clients_v1/backfill.yaml
blocks: https://github.com/mozilla/bigquery-etl/pull/8156
> feat: mark enterprise_metrics_clients_v1 2025-09-21 backfill entry as complete

- sql_generators/glean_usage/templates/events_stream_v1.query.sql
> Add client_info.windows_build_number to events_stream
