dags/desktop_clients_daily.py

This is a work in progress, but I'm posting to get some review

Add first airflow DAG

---

README.md

I thought this would be bigger, but it isn't, so it felt appropriate to embed it in the README

Add backfill section to README

---

udf/udf_country_code_to_flag.sql

I just stumbled upon regional indicator symbols and thought this was too fun not to share.

Add udf_country_code_to_flag

---

script/generate_incremental_table
script/pyspark/export_to_parquet.py
sql/clients_last_seen_v1.init.sql

Add script to automate generating incremental tables

---

.bigqueryrc
Dockerfile
script/entrypoint

Create ~/.bigqueryrc without GCLOUD_SERVICE_KEY

---

script/generate_incremental_table

Make generate_incremental_table less platform-dependent

---

sql/fxa_content_events_v1.sql

fixes https://github.com/mozilla/bigquery-etl/issues/144

remove null uid filter on FxA content server ETL job

---

script/pyspark/export_to_parquet.py

We implemented a view-based solution for creating clients_last_seen
from clients_last_seen_raw in Athena and Presto, but this made the
table unavailable from Spark.
By adding in these options, we can materialize view logic at the
time of writing to Parquet, so that it will be available to all
Parquet consumers.

Add --destination-table and selectExprs options to export_to_parquet

---

sql/firefox_nondesktop_exact_mau28_raw_v1.sql

Fix table name regression

---

README.md
sql/firefox_kpi_dashboard_v1.sql
templates/firefox_kpi_dashboard_v1.sql
udf/udf_json_extract_histogram.sql
udf/udf_json_extract_histogram_js.sql
udf/udf_sum_buckets_with_ci_js.sql

Fixup to #200 where I missed @relud's comments before merging.

Rename js udf to match conventions

---

README.md
sql/firefox_nondesktop_exact_mau28_raw_v1.sql
sql/smoot_usage_all_mtr_v1.sql
sql/smoot_usage_nondesktop_raw_v1.sql
sql/smoot_usage_nondesktop_v1.sql
templates/firefox_nondesktop_exact_mau28_raw_v1.sql
templates/smoot_usage_all_mtr_v1.sql
templates/smoot_usage_nondesktop_raw_v1.sql
templates/smoot_usage_nondesktop_v1.sql

Also adds some documentation on how to contribute now that the contents of `sql/` have to be generated by the developer.

Small improvements in prep for initial GUD demo

---

bigquery_etl/parse_udf.py
sql/fenix_events_v1.sql
templates/fenix_events_v1.sql
udf/udf_kv_array_to_json_string.sql

I attempted to add a generated test for this query, but it's proving to be too much work (I think due to the dataset being in a different project).

Fenix events

---

README.md
sql/core_clients_daily_v1.sql
sql/firefox_accounts_exact_mau28_raw_v1.sql
sql/firefox_desktop_exact_mau28_by_dimensions_v1.sql
sql/firefox_nondesktop_exact_mau28_raw_v1.sql
sql/fxa_users_daily_v1.sql
sql/glean_clients_daily_v1.sql
sql/smoot_usage_desktop_raw_v1.sql
sql/smoot_usage_fxa_raw_v1.sql
sql/smoot_usage_nondesktop_raw_v1.sql
templates/core_clients_daily_v1.sql
templates/firefox_accounts_exact_mau28_raw_v1.sql
templates/firefox_desktop_exact_mau28_by_dimensions_v1.sql
templates/firefox_nondesktop_exact_mau28_raw_v1.sql
templates/fxa_users_daily_v1.sql
templates/glean_clients_daily_v1.sql
templates/smoot_usage_desktop_raw_v1.sql
templates/smoot_usage_fxa_raw_v1.sql
templates/smoot_usage_nondesktop_raw_v1.sql

See discussion in #211
This may not be exhaustive, but converts most of the incremental queries where days are independent of one another.

Accept null submission_date to reprocess all history

---

sql/fenix_events_amplitude_v1.sql
sql/fenix_events_v1.sql
templates/fenix_events_amplitude_v1.sql
templates/fenix_events_v1.sql

Fix leftover submission_date in amplitude export.

Use fenix_live for events view

---

script/copy_deduplicate
script/entrypoint

Closes #220
A PR to add schedule this script in Airflow to follow.

Add copy_deduplicate script

---

tests/test_generated.py

fixes issues like: https://circleci.com/gh/mozilla/bigquery-etl/1426

sort generated tests

---

bigquery_etl/parse_udf.py
pytest.ini
script/generate_sql
script/publish_persistent_udfs
tests/test_udfs.py
tests/util.py

this is only testing support, actually using persistent UDFs will come later.

Add support for testing queries with persistent UDFs

---

script/copy_deduplicate

Make copy_deduplicate query more efficient for large tables

---

script/generate_views
script/publish_views

Update generate_view script for new directory structure

---

udf_legacy/date_trunc.sql

One more legacy function which should knock out a couple more compatibility cases

Add semi-compatible date_trunc version to udf_legacy

---

script/publish_persistent_udfs

I tried publishing the udf_legacy directory today and this script had a few issues that prevented it from running.
Might be worth adding a basic test for the script if we expect it to be in use for perpetuity

Fix UDF publisher script

---

sql/telemetry/smoot_usage_fxa_raw_v1/query.sql
templates/telemetry/smoot_usage_fxa_raw_v1/query.sql

Use country codes for fxa data in smoot tables

---

sql/telemetry/sync_bmk_total_per_day/view.sql
sql/telemetry/sync_bmk_total_per_day_v1/view.sql
templates/telemetry/sync_bmk_total_per_day/view.sql
templates/telemetry/sync_bmk_total_per_day_v1/view.sql

Add sync_bmk_total_per_day views bug1578581

---

udf_js/crc32.sql
udf_js/sample_id.sql

Add crc32 and sample_id as JS UDFs

---

script/dryrun
sql/telemetry/fxa_all_events_v1/view.sql
sql/telemetry/fxa_oauth_events_v1/query.sql
templates/telemetry/fxa_all_events_v1/view.sql
templates/telemetry/fxa_oauth_events_v1/query.sql

I've already created the new table and backfilled existing dates.
Addresses #348

Import events from FxA oauth server

---

sql/telemetry/firefox_kpi_dashboard_v1/query.sql
templates/telemetry/firefox_kpi_dashboard_v1/query.sql

Matches updates made to https://dbc-caf9527b-e073.cloud.databricks.com/#notebook/67817/command/95274

Update kpi_dashboard query to exclude FirefoxForFireTV

---

udf_js/gunzip.sql

Fix bug in gunzip udf

---

script/dryrun
sql/telemetry/fxa_content_auth_events_v1/view.sql
sql/telemetry/fxa_content_auth_oauth_events_v1/view.sql
sql/telemetry/fxa_users_services_daily/view.sql
sql/telemetry/fxa_users_services_last_seen/view.sql
sql/telemetry_derived/fxa_users_services_daily_v1/query.sql
sql/telemetry_derived/fxa_users_services_first_seen_v1/init.sql
sql/telemetry_derived/fxa_users_services_last_seen_v1/init.sql
sql/telemetry_derived/fxa_users_services_last_seen_v1/query.sql
templates/telemetry/fxa_content_auth_events_v1/view.sql
templates/telemetry/fxa_content_auth_oauth_events_v1/view.sql
templates/telemetry/fxa_users_services_daily/view.sql
templates/telemetry/fxa_users_services_last_seen/view.sql
templates/telemetry_derived/fxa_users_services_daily_v1/query.sql
templates/telemetry_derived/fxa_users_services_first_seen_v1/init.sql
templates/telemetry_derived/fxa_users_services_last_seen_v1/init.sql
templates/telemetry_derived/fxa_users_services_last_seen_v1/query.sql

[Per design discussed in a sheet](https://docs.google.com/spreadsheets/d/1R1UgiD1_Ol-AbSyTcEgz2pnVM3tkISNV6Sch9wnv0DQ/edit#gid=1573769019), this adds new ETL for supporting FxA per user per service metrics.

fxa_users_services tables

---

bigquery_etl/__init__.py
bigquery_etl/parse_udf.py
bigquery_etl/pytest_plugin/__init__.py
bigquery_etl/pytest_plugin/script_lint/__init__.py
bigquery_etl/pytest_plugin/script_lint/black.py
bigquery_etl/pytest_plugin/script_lint/docstyle.py
bigquery_etl/pytest_plugin/script_lint/flake8.py
bigquery_etl/pytest_plugin/script_lint/mypy.py
bigquery_etl/pytest_plugin/sql.py
bigquery_etl/pytest_plugin/udf.py
conftest.py
pytest.ini
script/copy_deduplicate
script/dryrun
script/generate_incremental_table
script/generate_sql
script/generate_views
script/json_to_table_ddl
script/publish_persistent_udfs

Add pytest plugins to lint python scripts

---

script/json_to_table_ddl

Tried to run this and ran into some issues >_<

Fixes to json -> table ddl generator script

---

script/dryrun

Fix CI by skipping slow-to-validate queries

---

udf/extract_count_histogram_value.sql

This will make some of the longitudinal migration queries a bit more readable

Add convenience function to extract count histogram values

---

sql/telemetry_derived/main_summary_v4/part1.sql
udf_js/main_summary_active_addons.sql
udf_js/main_summary_addon_scalars.sql
udf_js/main_summary_disabled_addons.sql

`JSON.parse` throws an error when it gets to `{\"\u0017...`, so this catches that and returns null

Catch errors in main summary javascript udfs

---

script/dryrun
sql/search/search_aggregates/view.sql
sql/search/search_clients_daily/view.sql
templates/search/search_aggregates/view.sql
templates/search/search_clients_daily/view.sql

Union search aggregates with v6 for armag-addon period

Add views for search dataset

---

sql/search_derived/search_clients_daily_v8/query.sql
templates/search_derived/search_clients_daily_v8/query.sql

Filter out overactive clients in search clients daily

---

sql/telemetry_derived/main_summary_v4/part1.sql
templates/telemetry_derived/main_summary_v4/part1.sql

includes new location for sync as well
cc @irrationalagent

 Bug 1593773 - Update main_summary to use new location of FXA_CONFIGURED

---

sql/telemetry_derived/core_live/view.sql
templates/telemetry_derived/core_live/view.sql

To match core view so the two can be unioned

Add normalize_metadata to core live view

---

script/generate_views

Merging this change will cause the changes to be used on the next deploy of the schema generation pipeline.
See https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-shared/Jenkinsfile.bigquery.prod#L105
Closes https://github.com/mozilla/gcp-ingestion/issues/631

Normalize metadata in generated views on historical ping tables

---

.circleci/config.yml
Dockerfile
tests/README.md

I'd rather unpin the python minor version, but it doesn't pass CI 😢

Upgrade to python 3.8

---

sql/telemetry_derived/experiments_v1/query.sql
templates/telemetry_derived/experiments_v1/get_experiment_list.py
templates/telemetry_derived/experiments_v1/query.sql

and use black to format the script

Fix order of arguments for udf.get_key

---

sql/telemetry/fxa_auth_events_v1/query.sql
sql/telemetry/fxa_oauth_events_v1/query.sql
templates/telemetry/fxa_auth_events_v1/query.sql
templates/telemetry/fxa_oauth_events_v1/query.sql

Allow some sync service events through FxA ETL

---

script/entrypoint

and add spaces to avoid issues with empty variables

Fix case expected for XCOM_PUSH

---

sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql
templates/telemetry_derived/clients_histogram_probe_counts_v1/query.sql

This should fix a divide by 0 failure currently happening in the glam dag

Fix divide by 0 errors.

---

script/dryrun
sql/monitoring/document_sample_nonprod_v1/query.sql
templates/monitoring/document_sample_nonprod_v1/query.sql

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1601139)

Bug 1601139 - Add query to sample documents per doctype 

---

sql/telemetry/fennec_ios_events_v1/view.sql
sql/telemetry/fire_tv_events_v1/view.sql
sql/telemetry/focus_android_events_v1/view.sql
sql/telemetry/rocket_android_events_v1/view.sql
templates/telemetry/fennec_ios_events_v1/view.sql
templates/telemetry/fire_tv_events_v1/view.sql
templates/telemetry/focus_android_events_v1/view.sql
templates/telemetry/rocket_android_events_v1/view.sql

This adds mobile views introduced in https://github.com/mozilla/bigquery-etl/pull/510

Bug 1574490 - Add Amplitude-compatible views for mobile events

---

sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql
templates/telemetry_derived/clients_histogram_probe_counts_v1/query.sql

The glam dag was failing due to mismatching of names.

Rename total_clients to total_users.

---

sql/telemetry/simpleprophet_forecasts/view.sql
templates/telemetry/simpleprophet_forecasts/view.sql

Add simpleprophet_forecasts view

---

sql/telemetry/fxa_users_daily_v1/query.sql
templates/telemetry/fxa_users_daily_v1/query.sql

Fix accidental capitalization

---

sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql
templates/telemetry_derived/clients_histogram_probe_counts_v1/query.sql

Similar issue to the one with `udf_linear_buckets()`

Fix out of memory in udf_exponential_buckets().

---

sql/activity_stream/tile_id_types/view.sql
templates/activity_stream/tile_id_types/view.sql

Background information can be found at https://bugzilla.mozilla.org/show_bug.cgi?id=1604643
r?

Add tile_id_types view Bug 1604643

---

script/dryrun

Fix #653 - CI failing on activity_stream/tile_id_types/views.sql

---

script/publish_views
sql/activity_stream/tile_id_types/view.sql
templates/activity_stream/tile_id_types/view.sql

Related to CI failures addressed in https://github.com/mozilla/bigquery-etl/issues/653

Add list of authorized views to exempt from publishing

---

sql/telemetry/attitudes_daily/view.sql
templates/telemetry/attitudes_daily/view.sql

Adding a pointer view for attitudes_daily for now so it's discoverable from the STMO schema browser

Add view in derived-datasets pointing to attitudes daily v1 table

---

sql/activity_stream/impression_stats_flat/view.sql
sql/activity_stream_derived/impression_stats_flat_v1/query.sql
templates/activity_stream/impression_stats_flat/view.sql
templates/activity_stream_derived/impression_stats_flat_v1/query.sql

Based on a query provided by @kirill-demtchouk

Add view on impression_stats data

---

script/format_sql
sql/telemetry_derived/error_aggregates/query.sql
sql/telemetry_derived/main_summary_v4/part1.sql
sql/telemetry_derived/main_summary_v4/part2.sql
udf/json_extract_int_map.sql

See https://bugzilla.mozilla.org/show_bug.cgi?id=1609666
I am running main_summary with this change right now to verify whether it fixes the exception we saw in last night's runs.

Bug 1609666 Use SAFE_CAST in udf.json_extract_int_map

---

script/generate_views

Syntax error in publish_views for fenix

---

README.md

Document intent to have new user-facing views without version indirection

---

script/generate_incremental_table

by specifying --start as a date after --end

Allow generate_incremental_table to backfill days in reverse

---

bigquery_etl/format_sql/tokenizer.py
sql/activity_stream_derived/impression_stats_flat_v1/query.sql
sql/org_mozilla_fenix_derived/clients_daily_v1/query.sql
sql/org_mozilla_vrbrowser_derived/baseline_daily_v1/query.sql
sql/org_mozilla_vrbrowser_derived/metrics_daily_v1/query.sql
sql/telemetry_derived/clients_daily_v6/query.sql
sql/telemetry_derived/core_clients_daily_v1/query.sql
templates/activity_stream_derived/impression_stats_flat_v1/query.sql
tests/assert/array_equals.sql
udf/json_mode_last.sql

Fix unholy WITH OFFSET format

---

sql/telemetry_derived/smoot_usage_desktop_compressed_v2/query.sql
sql/telemetry_derived/smoot_usage_fxa_compressed_v2/query.sql
sql/telemetry_derived/smoot_usage_nondesktop_compressed_v2/query.sql
templates/telemetry_derived/smoot_usage_desktop_compressed_v2/query.sql
templates/telemetry_derived/smoot_usage_fxa_compressed_v2/query.sql
templates/telemetry_derived/smoot_usage_nondesktop_compressed_v2/query.sql

This is a performance optimization for GUD.
Relies on https://github.com/mozilla/telemetry-airflow/pull/847 for scheduling.

Add compressed Smoot tables

---

script/dryrun
script/publish_views

Parallelize scripts/publish_views

---

README.md

This updates documentation to reflect changes made in https://github.com/mozilla/bigquery-etl/pull/723

Update README with persistent UDF changes

---

sql/telemetry_derived/clients_histogram_aggregates_merged_v1/query.sql

Since this is a full outer join, we want to keep rows that are null for one table or another. I've updated the join to reflect that.

Fixing join in clients_histogram_aggregates_merged.

---

sql/telemetry_derived/clients_histogram_aggregates_merged_v1/query.sql

Brain fart! Field name was wrong. Sorry to bug you again @jklukas XD

Glam field for clients_histogram_aggregates_merged is channel_enum not channel_id

---

.circleci/config.yml

issue introduced by #736 because `constraints.txt` is no longer present

Fix CI cache

---

sql/telemetry_derived/smoot_usage_desktop_compressed_v2/query.sql
sql/telemetry_derived/smoot_usage_desktop_v2/query.sql
sql/telemetry_derived/smoot_usage_fxa_compressed_v2/query.sql
sql/telemetry_derived/smoot_usage_fxa_v2/query.sql
sql/telemetry_derived/smoot_usage_new_profiles_compressed_v2/query.sql
sql/telemetry_derived/smoot_usage_nondesktop_compressed_v2/query.sql
sql/telemetry_derived/smoot_usage_nondesktop_v2/query.sql

Will allow GUD to display "light funnel" vs. "dark funnel".

Add 'attributed' dimensions to smoot tables

---

udf/days_seen_bytes_to_rfm.sql

from https://github.com/mozilla/bigquery-etl/pull/611#issuecomment-567178921

Add RFM definition to udf_days_seen_bytes_to_rfm

---

sql/telemetry/fxa_oauth_events_v1/query.sql

Deprecate fxa_oauth_events query

---

sql/telemetry/fennec_ios_events_v1/view.sql
sql/telemetry/fire_tv_events_v1/view.sql
sql/telemetry/firefox_accounts_exact_mau28_by_dimensions_v1/view.sql
sql/telemetry/firefox_desktop_exact_mau28_v1/view.sql
sql/telemetry/firefox_nondesktop_exact_mau28_by_dimensions_v1/view.sql
sql/telemetry/focus_android_events_v1/view.sql
sql/telemetry/rocket_android_events_v1/view.sql
sql/telemetry_derived/devtools_events_amplitude_v1/view.sql
sql/telemetry_derived/smoot_usage_fxa_v2/query.sql

This is part of the overall effort in https://bugzilla.mozilla.org/show_bug.cgi?id=1612543

Remove references to views and static data in derived-datasets

---

bigquery_etl/shredder/delete.py

fixes #797
fixes #799
This should fix an issue where shredder isn't fully utilizing the available reserved slots in bigquery-batch-prod because DELETE jobs against the same table get automatically delayed after the first two to avoid metadata update conflicts, even when --priority=INTERACTIVE

Sort shredder jobs by partition_id then table_id

---

script/copy_deduplicate

Closes https://github.com/mozilla/bigquery-etl/issues/834

Filter out temporary tables created by the Beam BigQuery sink job

---

bigquery_etl/shredder/delete.py
bigquery_etl/util/exceptions.py

Use streaming inserts for shredder state

---

sql/messaging_system_derived/cfr_users_last_seen_v1/query.sql

Closes https://github.com/mozilla/bigquery-etl/issues/841
cc @ncloudioj

Construct non-null join key for cfr_users_last_seen query

---

sql/telemetry/health/view.sql

See https://bugzilla.mozilla.org/show_bug.cgi?id=1624353#c1

Bug 1624353 telemetry.health view should look at v4

---

script/glam/run_glam_sql

@acmiyaguchi I noticed you cherry picked this in a different PR. I think we can just go ahead and put it in on its own. What do you think?

Convert run_fenix_sql to run_glam_sql

---

bigquery_etl/glean_usage/baseline_clients_daily.py
bigquery_etl/glean_usage/baseline_clients_last_seen.py
bigquery_etl/glean_usage/templates/baseline_clients_daily_v1.sql
bigquery_etl/glean_usage/templates/baseline_clients_last_seen_v1.sql
script/dryrun
sql/org_mozilla_fenix_nightly/baseline_clients_last_seen/view.sql
sql/org_mozilla_fenix_nightly_derived/baseline_clients_daily_v1/init.sql
sql/org_mozilla_fenix_nightly_derived/baseline_clients_daily_v1/query.sql
sql/org_mozilla_fenix_nightly_derived/baseline_clients_last_seen_v1/init.sql
sql/org_mozilla_fenix_nightly_derived/baseline_clients_last_seen_v1/query.sql
sql/org_mozilla_firefox_derived/incline_executive_v1/query.sql
sql/telemetry/firefox_nondesktop_exact_mau28_raw_v1/query.sql
sql/telemetry/nondesktop_clients_last_seen_v1/view.sql
sql/telemetry_derived/smoot_usage_nondesktop_v2/query.sql

This implements the [proposed Fenix KPI reporting changes](https://docs.google.com/document/d/1Ym4eZyS0WngEP6WdwJjmCoxtoQbJSvORxlQwZpuSV2I/edit#heading=h.69hvvg35j8un) in GUD.

Use baseline_clients_last_seen for Fenix

---

script/format_sql
sql/telemetry/nondesktop_clients_last_seen_v1/view.sql
sql/telemetry_derived/smoot_usage_nondesktop_v2/query.sql

We will be adding some of these to the frontend via https://github.com/mozilla/GUD/pull/77

Add additional Glean apps to GUD tables

---

script/dryrun
script/publish_views
sql/pocket/pocket_reach_mau/view.sql

https://bugzilla.mozilla.org/show_bug.cgi?id=1629151.
This will be added as a authorized view manually.

Add Pocket MAU view Bug 1629151

---

sql/pocket/pocket_reach_mau/view.sql

Fix dateset reference for pocket_reach_mau view

---

script/entrypoint

Run publish_public_data_json as bash script in entrypoint

---

README.md
bigquery_etl/public_data/publish_json.py

Updated the public data section now that the final public domain is set up

Update public data section in README

---

sql/telemetry_derived/sync_send_tab_events_v1/view.sql

Amplitude folks indicated that `time` must always be populated and they cannot have duplicate `device_id` fields.

Address Amplitude feedback on sync_send_tab_events

---

udf/bits_to_active_n_weeks_ago.sql

This is for use with the search_clients_last_seen dataset.

Add udf for if user was active n weeks ago from BYTE

---

sql/activity_stream_bi/impression_stats_flat_v1/query.sql

Add experiments to impression_stats_flat

---

bigquery_etl/shredder/config.py
bigquery_etl/shredder/cost.py
script/shredder_cost

generates the Cost section from https://docs.google.com/document/d/1JvRtWbcq9xTSNg19628O_SAk9pL8CwAvkOHCOvEEAcY/edit# in markdown.
also removes the `fogotype` tables from the shredder config, because they no longer exist.
cc @mreid-moz

Add script for reporting shredder cost

---

README.md
bigquery_etl/public_data/publish_gcs_metadata.py
bigquery_etl/public_data/publish_json.py
tests/data/incremental_query_gcs_metadata.json
tests/data/non_incremental_query_gcs_metadata.json
tests/public_data/test_publish_gcs_metadata.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1632857
cc @wlach

[Bug 1632857] Set content-type for public data to json and encoding to gzip

---

bigquery_etl/shredder/config.py
bigquery_etl/shredder/delete.py

Also remove deleted tables from config
Also add --partition-limit option for faster --dry-run

Skip NotFound tables in shredder

---

script/dryrun
sql/telemetry/clients_first_seen/metadata.yaml
sql/telemetry/clients_first_seen/view.sql
sql/telemetry/clients_last_seen/view.sql
sql/telemetry_derived/clients_first_seen_v1/init.sql
sql/telemetry_derived/clients_first_seen_v1/metadata.yaml
sql/telemetry_derived/clients_first_seen_v1/query.sql

Draft of a new table that may be useful in
https://github.com/mozilla/bigquery-etl/pull/949
If we have no immediate use, we can table this for now.

clients_first_seen

---

sql/telemetry/fennec_ios_events_v1/view.sql

The formatting caused a big change, so I split that into a separate commit. There are no changes in that commit other than reformatting.

Bug 1636231 - Remove background events from ios Amplitude export

---

sql/firefox_accounts/fxa_amplitude_export/view.sql

This should resolve the last outstanding issue. We'll resolve the top-level columns issue with Amplitude (hopefully).

Make FxA export use PDT

---

udf/active_values_from_days_seen_map.sql
udf/bits28_active_in_range.sql
udf/bits28_days_since_seen.sql
udf/bits28_from_string.sql
udf/bits28_range.sql
udf/bits28_retention.sql
udf/bits28_to_dates.sql
udf/bits28_to_string.sql
udf/pos_of_trailing_set_bit.sql

This is the implementation of the new interface documented in https://github.com/mozilla/firefox-data-docs/pull/462
These two PRs are co-evolving drafts.

Bit pattern UDFs (bits28_*)

---

sql/telemetry_derived/sync_send_tab_events_v1/view.sql

Based on feedback in [DS-642](https://jira.mozilla.com/browse/DS-642?focusedCommentId=61469&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-61469)

Update sync send tab schema

---

sql/telemetry_derived/sync_send_tab_events_v1/view.sql
udf/normalize_os.sql

The test suite is identical to that used in gcp-ingestion.

Add udf.normalize_os

---

sql/telemetry_derived/clients_first_seen_v1/init.sql
sql/telemetry_derived/clients_first_seen_v1/query.sql

@jmccrosky reported that the first_seen_dates were not necessarily
correct. I neglected an important ORDER BY clause in init.sql.
This also simplifies the logic in the incremental query.

Refactor clients_first_seen

---

sql/firefox_accounts/fxa_amplitude_export/view.sql

I forgot the manufactured timestamp! Thank god for views.

Add timestamp to fxa export

---

sql/telemetry_derived/clients_histogram_probe_counts_v1/query.sql

The glam desktop dag is failing with shuffle errors for `clients_histogram_probe_counts_v1` at the moment. This was odd because I tested it locally with the `run_glam_sql` script and it seemed fine.
It turns out that when I triggered `run_glam_desktop` to process the queries in parallel, I could trigger the same shuffle errors. When they are run sequentially, the errors do not occur. I suppose the shuffle issue is project-wide not just per query, as the error says `Quota exceeded: Your project exceeded quota for total shuffle size limit`
So we can run them sequentially by removing the use of default executor here: https://github.com/mozilla/telemetry-airflow/pull/991/files
However, the queries were taking 20 min each and this change brings them down to ~10min each which is more reasonable …

Simplify clients_histogram_probe_counts_v1.

---

bigquery_etl/shredder/config.py

fixes [bug  1610925](https://bugzilla.mozilla.org/show_bug.cgi?id=1610925)

Bug 1610925 - Add activity stream tables to shredder

---

sql/telemetry/rocket_android_events_v1/view.sql

1. Event ping for [ Firefox Lite 4-5 milestone](https://github.com/mozilla-tw/FirefoxLite/milestone/65) & [Firefox Lite 4-6 milestones.](https://github.com/mozilla-tw/FirefoxLite/milestone/66)

TelemetryToAmplitude-2020-05-21

---

script/glam/generate_and_run_desktop_sql

Add noreplace to glam query

---

bigquery_etl/shredder/config.py

Bug 1635221 - Delete sync data on request

---

sql/telemetry/amo_stats_dau/view.sql
sql/telemetry/amo_stats_installs/view.sql
sql/telemetry_derived/amo_stats_dau_v1/query.sql
sql/telemetry_derived/amo_stats_installs_v1/query.sql

See https://bugzilla.mozilla.org/show_bug.cgi?id=1572873
These two tables provide all the raw data needed to replicate the existing AMO stats page with the following caveat:
- We do not provide downloads broken down by source

Bug 1572873 Add tables for powering AMO stats dashboard

---

tests/data/dags/test_dag_with_dependencies

I forgot to update the expected test output.
Also making sure for this PR to avoid merging from a fork so that integration tests get actually executed.

Update DAG test expected output

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
tests/data/dags/test_dag_duplicate_dependencies
tests/data/dags/test_dag_with_dependencies
tests/query_scheduling/test_dag_collection.py

Fixes the duplicate tasks issues in https://github.com/mozilla/bigquery-etl/pull/1027/files
Fixes https://github.com/mozilla/bigquery-etl/issues/1028

Lower-friction scheduled queries: fix duplicate tasks

---

sql/telemetry/rocket_android_events_v1/view.sql

1. Event ping for Firefox Lite [4-7 milestone ](https://github.com/mozilla-tw/FirefoxLite/milestone/67)

TelemetryToAmplitude-2020-06-05

---

bigquery_etl/query_scheduling/templates/airflow_dag.j2
bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2
dags.yaml
dags/bqetl_amo_stats.py
dags/bqetl_deviations.py
dags/bqetl_public_data_json.py
dags/bqetl_vrbrowser.py
sql/org_mozilla_vrbrowser_derived/baseline_daily_v1/metadata.yaml
sql/org_mozilla_vrbrowser_derived/clients_daily_v1/metadata.yaml
sql/org_mozilla_vrbrowser_derived/clients_last_seen_v1/metadata.yaml
sql/org_mozilla_vrbrowser_derived/metrics_daily_v1/metadata.yaml
tests/data/dags/test_dag_duplicate_dependencies
tests/data/dags/test_dag_with_dependencies
tests/data/dags/test_public_data_json_dag

This migrates VR browser related queries to a separate DAG.

Lower-friction scheduled queries: VR browser DAG

---

dags.yaml
dags/bqetl_mobile_search.py
sql/search_derived/mobile_search_aggregates_v1/metadata.yaml
sql/search_derived/mobile_search_clients_daily_v1/metadata.yaml

Continuing with automatically generating Airflow DAGs, I added a `bqetl_mobile_search` DAG.
Generates DAG in https://github.com/mozilla/telemetry-airflow/pull/1017

bqetl_mobile_search DAG

---

udf/normalize_search_engine.sql

Updating this UDF per feedback from mconnor and the finance team. Ideally we would backfill this for a few months.

Update normalize_search_engine UDF

---

sql/telemetry_derived/clients_daily_histogram_aggregates_v1/query.sql
tests/telemetry_derived/clients_daily_histogram_aggregates_v1/test_aggregation/moz-fx-data-shared-prod.telemetry_stable.main_v4.schema.json
tests/telemetry_derived/clients_daily_histogram_aggregates_v1/test_build_id_filter/moz-fx-data-shared-prod.telemetry_stable.main_v4.schema.json

I tested that the query can run

Update clients_daily_histogram_agg without use counters in the query

---

sql/search/mobile_search_aggregates/view.sql
sql/search/mobile_search_clients_daily/view.sql
sql/search/search_aggregates/view.sql
sql/search/search_clients_daily/view.sql

Fully qualify UDF references

---

sql/messaging_system/onboarding_events_amplitude/view.sql

- Make experiments a list of experiment-branch strings
rather than one property per-experiment
- Update platform to just be the os name, and not the version

Update onboarding events user properties

---

sql/telemetry/clients_daily/view.sql
sql/telemetry/crash_aggregates/view.sql
sql/telemetry/crash_summary/view.sql
sql/telemetry/events/view.sql
sql/telemetry/experiments/view.sql
sql/telemetry/experiments_aggregates/view.sql
sql/telemetry/socorro_crash/view.sql
sql/telemetry/ssl_ratios/view.sql
sql/telemetry/telemetry_core_parquet/view.sql
sql/telemetry/telemetry_focus_event_parquet/view.sql
sql/telemetry/telemetry_new_profile_parquet/view.sql
sql/telemetry/telemetry_shield_study_parquet/view.sql

Fixes several view regressions introduced in https://github.com/mozilla/bigquery-etl/pull/1092

Fix view regressions

---

script/publish_views

Retry once on "invalid snapshot time" when publishing views

---

sql/firefox_accounts/fxa_amplitude_email_clicks/view.sql

I got some more context from :lniolet about the EmailName format and was able to improve this regex.

Better regex for Amplitude email click export

---

script/publish_views

Fixes https://github.com/mozilla/bigquery-etl/issues/1075

Reference shared-prod views when republishing to other projects

---

script/dryrun

We no longer have any destination tables in derived-datasets.

Bug 1649754 Remove reference to derived-datasets dry run url

---

sql/amo_dev/amo_stats_dau/view.sql
sql/amo_prod/amo_stats_dau/view.sql

See https://github.com/mozilla/addons-server/issues/14790

Replace null keys with 'Unknown' in amo_stats_dau

---

sql/telemetry_derived/main_summary_v4/part1.sql
udf/extract_count_histogram_value.sql
udf/extract_histogram_sum.sql
udf/histogram_max_key_with_nonzero_value.sql
udf/histogram_to_threshold_count.sql
udf/keyed_histogram_get_sum.sql

Reduce complexity of getting histogram sum in main_summary

---

bigquery_etl/query_scheduling/generate_airflow_dags.py
bigquery_etl/query_scheduling/task.py
bigquery_etl/query_scheduling/templates/airflow_dag.j2
dags.yaml
dags/bqetl_addons.py
dags/bqetl_amo_stats.py
dags/bqetl_clients_daily.py
dags/bqetl_experiments.py
dags/bqetl_experiments_daily.py
dags/bqetl_main_summary.py
dags/bqetl_search.py
sql/amo_prod/desktop_addons_by_client_v1/metadata.yaml
sql/search_derived/search_clients_daily_v8/metadata.yaml
sql/telemetry_derived/addon_aggregates_v2/metadata.yaml
sql/telemetry_derived/addon_names_v1/metadata.yaml
sql/telemetry_derived/addons_v2/metadata.yaml
sql/telemetry_derived/clients_daily_v6/metadata.yaml
sql/telemetry_derived/experiments_daily_active_clients_v1/metadata.yaml
sql/telemetry_derived/main_summary_v4/metadata.yaml
tests/data/test_sql/test/multipart_query_v1/metadata.yaml
tests/data/test_sql/test/multipart_query_v1/part1.sql
tests/data/test_sql/test/multipart_query_v1/part2.sql
tests/query_scheduling/test_generate_airflow_dags.py
tests/query_scheduling/test_task.py

Adds support for scheduling multipart queries and moves queries out of the `main_summary` DAG.
Generates https://github.com/mozilla/telemetry-airflow/pull/1047

bqetl_main_summary DAG

---

bigquery_etl/parse_udf.py
bigquery_etl/pytest_plugin/udf.py
mozfun/json/extract_int_map/udf.sql
pytest.ini

Fixes https://github.com/mozilla/bigquery-etl/issues/1133

Run pytest on mozfun UDFs

---

bigquery_etl/query_scheduling/dag_collection.py

Fixes https://github.com/mozilla/bigquery-etl/issues/1141
51s (this PR) vs 2:18 (current, sequential version)

Parallelize Airflow DAG generation

---

sql/telemetry_derived/public_data_report_user_activity_v1/query.sql

This makes this query consistent with others.

Rename week_start column to submission_date in user_activity query

---

bigquery_etl/query_scheduling/task.py
sql/amo_prod/desktop_addons_by_client_v1/metadata.yaml
sql/internet_outages/global_outages_v1/metadata.yaml
sql/telemetry_derived/addon_aggregates_v2/metadata.yaml
sql/telemetry_derived/addon_names_v1/metadata.yaml
sql/telemetry_derived/addons_v2/metadata.yaml
sql/telemetry_derived/error_aggregates_v1/metadata.yaml
sql/telemetry_derived/main_summary_v4/metadata.yaml
sql/telemetry_derived/ssl_ratios_v1/metadata.yaml

because queries that reference main_v4 are slow to dry run

Optionally provide referenced_tables in metadata.yaml

---

bigquery_etl/query_scheduling/task.py
dags.yaml
dags/bqetl_asn_aggregates.py
sql/telemetry_derived/asn_aggregates_v1/metadata.yaml

Migrating `asn_aggregates` query to their own DAG
Generates https://github.com/mozilla/telemetry-airflow/pull/1086

bqetl_asn_aggregates DAG

---

dags.yaml
dags/bqetl_fxa_events.py
dags/bqetl_gud.py
sql/firefox_accounts_derived/exact_mau28_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_auth_bounce_events_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_auth_events_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_content_events_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_delete_events_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_log_auth_events_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_log_content_events_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_users_daily_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_users_last_seen_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_users_services_daily_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_users_services_first_seen_v1/metadata.yaml
sql/firefox_accounts_derived/fxa_users_services_first_seen_v1/query.sql
sql/firefox_accounts_derived/fxa_users_services_last_seen_v1/metadata.yaml
sql/telemetry_derived/smoot_usage_fxa_compressed_v2/metadata.yaml
sql/telemetry_derived/smoot_usage_fxa_v2/metadata.yaml

Replaces the fxa_events DAG in telemetry-airflow: https://github.com/mozilla/telemetry-airflow/pull/1092

Add bqetl_fxa_events DAG

---

script/glam/generate_glean_sql

I just noticed that the docker image doesn't have jq

Replace jq in generate_glean_sql

---

udf/glean_timespan_nanos.sql
udf/glean_timespan_seconds.sql

Fixes https://github.com/mozilla/bigquery-etl/issues/1175

Fix mozfun Glean wrappers

---

sql/amo_prod/desktop_addons_by_client_v1/query.sql

cc @willdurand I've created this table with one day of data (2020-07-14) for comparison.

Bug 1653499 Base AMO usage stats on payload.info.addons

---

sql/telemetry_derived/main_summary_v4/part1.sql

It appears that #1191 which changes mozfun.hist.extract caused complexity
to tip over the threshold for main_summary again.
The `threshold_count` UDF uses mozfun.hist.extract under the hood and also
itself involves a subquery, so bundling multiple thresholds together in
a single function call reduces complexity.

Reduce main_summary complexity by bundling threshold counts

---

sql/revenue_derived/client_ltv_v1/query.sql

adding tagged search to the current value of LTV

Add tagged_search current to LTV

---

mozfun/norm/metadata/udf.sql

As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1657360#c1

Add parsed_x_source_tags to metadata in user-facing views

---

bigquery_etl/dryrun.py
sql/monitoring/structured_distinct_docids_v1/init.sql
sql/monitoring/structured_distinct_docids_v1/query.py
sql/monitoring/telemetry_distinct_docids_v1/init.sql
sql/monitoring/telemetry_distinct_docids_v1/query.sql

Example usage: https://sql.telemetry.mozilla.org/queries/69317/source
https://github.com/mozilla/telemetry-airflow/pull/1125

Add distinct docid count queries

---

sql/telemetry_derived/devtools_accessiblility_panel_usage_v1/query.sql

This makes backfilling inside a sandbox project easier

Use qualified table names and udf functions

---

sql/monitoring/structured_distinct_docids_v1/query.py

This fixes the missing doc id counts for firefox installer install_v1

Add decoded stub installer to structured docid count

---

bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2
dags/bqetl_public_data_json.py

Fixes https://github.com/mozilla/bigquery-etl/issues/1236

Fix intermittent verify-dags-up-to-date failures

---

sql/telemetry_derived/experiment_search_aggregates_base/view.sql
sql/telemetry_derived/experiment_search_aggregates_live_v1/view.sql.py
sql/telemetry_derived/experiment_search_aggregates_v1/query.sql

Move experiments_search_aggregates logic to a view

---

mozfun/norm/examples/fenix_app_info.sql
mozfun/norm/fenix_app_info/README.md
mozfun/norm/fenix_app_info/metadata.yaml

fenix_app_info documentation fixups

---

mozfun/norm/examples/fenix_app_info.sql
mozfun/norm/fenix_app_info/metadata.yaml

More complete docs for fenix_app_info

---

sql/telemetry/desktop_retention_1_week/view.sql

Follow-up to [this comment](https://mozilla.slack.com/archives/C4D5ZA91B/p1598296054010400).

Add sample_id to desktop retention view

---

bigquery_etl/run_query.py
script/entrypoint

We should add some tests for the `entrypoint` script. I'll look into it.

Fix entrypoint run_query call

---

.circleci/config.yml
tests/test_entrypoint.py

We were running into some issues with making changes and the `entrypoint` script not working properly anymore a couple of times in the past. This adds integration tests to (hopefully) prevent more issues in the future.

Add integration tests for entrypoint run query

---

bigquery_etl/public_data/publish_json.py
tests/public_data/test_publish_json.py
tests/public_data/test_publish_public_data_json_script.py

Fixes https://github.com/mozilla/bigquery-etl/issues/1271

Fix writing to temporary table when publishing JSON

---

bigquery_etl/udf/publish_udfs.py

Fixes https://github.com/mozilla/bigquery-etl/issues/1286
cc @whd

Fix publishing UDFs

---

bigquery_etl/_version.py
bigquery_etl/cli/__init__.py
bigquery_etl/cli/udf.py
bigquery_etl/docs/validate_docs.py
bigquery_etl/udf/publish_udfs.py
tests/cli/test_cli_udf.py

Adds some CLI commands for working with mozfun and internal UDFs:
```
Commands:
create    Create a new UDF
info      Get UDF information
publish   Publish UDFs to BigQuery.
validate  Validate a UDF.
```

CLI commands for UDFs

---

sql/org_mozilla_firefox_derived/events_daily_v1/init.sql

CI is currently failing for other PRs.

Allow dry runs to succeed for events daily init.sql

---

README.md
dags/bqetl_fenix_event_rollup.py
sql/org_mozilla_firefox/event_types_v1/metadata.yaml

Wow, we should definitely store the `bigquery_etl_query` function in this repo.

Add submission date parameter

---

sql/org_mozilla_firefox/events_daily/view.sql

Fixes https://github.com/mozilla/bigquery-etl/issues/1318

Add project ID to events_daily view definition

---

bigquery_etl/shredder/config.py

fixes [Bug 1658028](https://bugzilla.mozilla.org/show_bug.cgi?id=1658028)

Bug 1658028 - Handle legacy IDs from glean apps in shredder

---

bigquery_etl/glam/cli.py

this is breaking stripe imports

Don't assert on import when running bqetl command

---

bigquery_etl/udf/parse_udf.py
bigquery_etl/udf/publish_udfs.py

This is going to fail by default right now. I'm not seeing a description option for stored procedures, but perhaps we can file an issue with Google.

Add support for publishing procedures

---

bigquery_etl/docs/generate_docs.py
mozfun/event_analysis/README.md
mozfun/event_analysis/create_events_view/README.md
mozfun/event_analysis/create_events_view/metadata.yaml

Add docs for `create_events_view` procedure.
@wlach, can you look over the contents of these docs and give me some feedback?

Allow documentation for stored procedures

---

sql/monitoring/bigquery_etl_scheduled_query_usage_v1/query.py

I renamed the query but forgot to update the destination table name...

Update destination table for bigquery_etl_scheduled_query_usage

---

script/publish_public_udfs

I re-ran a few tasks in Airflow that all completed successfully. main_summary is still running

Update path for publishing public UDFs

---

sql/moz-fx-data-shared-prod/mozilla_vpn/waitlist/view.sql
sql/moz-fx-data-shared-prod/stripe/subscription_transitions/view.sql
sql/moz-fx-data-shared-prod/stripe/subscription_volume/view.sql
sql/moz-fx-data-shared-prod/stripe_derived/plan_events/view.sql
sql/moz-fx-data-shared-prod/stripe_derived/product_events/view.sql
sql/moz-fx-data-shared-prod/stripe_derived/subscription_events/view.sql

Fully qualify stripe and mozilla_vpn views

---

bigquery_etl/query_scheduling/generate_airflow_dags.py
sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/metadata.yaml
sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Scheduled via https://github.com/mozilla/telemetry-airflow/pull/1167

Query for importing experimenter experiments

---

sql/moz-fx-data-shared-prod/stripe_derived/plan_events/view.sql
sql/moz-fx-data-shared-prod/stripe_derived/product_events/view.sql
sql/moz-fx-data-shared-prod/stripe_derived/subscription_events/view.sql

Fix backticks in stripe derived views

---

bigquery_etl/cli/dag.py
bigquery_etl/cli/query.py
bigquery_etl/query_scheduling/generate_airflow_dags.py
tests/data/test_sql/moz-fx-data-test-project-2/test_2/test_query_v1/metadata.yaml
tests/data/test_sql/moz-fx-data-test-project-2/test_2/test_query_v1/query.sql
tests/query_scheduling/test_generate_airflow_dags.py

Fixes https://github.com/mozilla/bigquery-etl/issues/1421

Fix DAG generation for different projects

---

sql/mozfun/norm/product_info/generate_body.sql
sql/mozfun/norm/product_info/metadata.yaml
sql/mozfun/norm/product_info/udf.sql

Factoring this out from https://github.com/mozilla/bigquery-etl/pull/1380
since this UDF needs to be published before I can properly test the rest of the changes there.

Add mozfun.norm.product_info UDF

---

bigquery_etl/dryrun.py
sql/moz-fx-data-shared-prod/regrets_reporter/regrets_reporter_update/view.sql

See https://bugzilla.mozilla.org/show_bug.cgi?id=1654078#c45

Bug 1654078 Limit geo to country level in regrets-reporter view

---

dags.yaml
dags/bqetl_org_mozilla_fenix_derived.py
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/geckoview_version_v1/metadata.yaml

This schedules the query in #1419 in support of #1402

Add daily schedule for geckoview versions

---

sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_nondesktop_v2/query.sql

Fixes https://github.com/mozilla/bigquery-etl/issues/1453

Revert field order in smoot nondesktop

---

bigquery_etl/metadata/parse_metadata.py
bigquery_etl/metadata/validate_metadata.py
tests/data/metadata.yaml
tests/metadata/test_parse_metadata.py

- Issue #924
- What I did:
- refactor parse_metadata with `attr` validation
- add file check for `is_metadata_file()`
- update metadata tests
- Looking forward to review and feedback @scholtzan. Thank you!

Update metadata validation logic (issue #924)

---

dags/bqetl_main_summary.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/metadata.yaml

Allows Airflow to apply https://github.com/mozilla/bigquery-etl/pull/1455

Allow field addition for one day of clients_daily and friends

---

bigquery_etl/dryrun.py
dags/bqetl_mozilla_vpn.py
sql/moz-fx-data-shared-prod/mozilla_vpn_external/devices_v1/init.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_external/devices_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_vpn_external/devices_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_external/subscriptions_v1/init.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_external/subscriptions_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_vpn_external/subscriptions_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/init.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_vpn_external/users_v1/query.sql

configured to match the waitlist table import

Setup more imports from Mozilla VPN CloudSQL

---

bigquery_etl/stripe/__init__.py

stripe imports are failing because of new event types that don't have a defined schema, and we can ignore those events because we don't need them (yet).

Only import stripe events for which we have a schema

---

sql/mozfun/glam/histogram_fill_buckets_dirichlet/metadata.yaml
sql/mozfun/glam/histogram_generate_functional_buckets/metadata.yaml

Fixes https://github.com/mozilla/bigquery-etl/issues/1495
I think we should add some checks in the CI for this.

Fix GLAM UDF descriptions

---

bigquery_etl/dryrun.py
sql/moz-fx-data-marketing-prod/ga_derived/blogs_sessions_v1/query.sql

oops
dryrun capability coming soon hopefully

Change entryPage to entry_page in blogs GA

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/protected_v1/query.sql

reusing the pattern from https://github.com/mozilla/bigquery-etl/blob/415ee2f/sql/moz-fx-data-shared-prod/mozilla_vpn_derived/login_flows_v1/query.sql

Use union instead of join to make query more readable

---

bigquery_etl/run_multipart_query.py

For `run_multipart_query` we need to add explicit support for `--schema_update_option`

Add support for --schema_update_option in run_multipart_query.py

---

bigquery_etl/run_multipart_query.py

Fixes https://github.com/mozilla/bigquery-etl/issues/1517

[Bug 1675293] Fix schema_update_option in main_summary

---

bigquery_etl/glam/templates/extract_probe_counts_v1.sql
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__extract_probe_counts_v1/query.sql
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_nightly__clients_daily_scalar_aggregates_metrics_v1/query.sql

This filters probes where there are less than 10 users in the dimension.

Add total_user filter on glam exports

---

sql/mozfun/norm/product_info/README.md
sql/mozfun/norm/product_info/generate_body.sql
sql/mozfun/norm/product_info/udf.sql

Reported by @gkabbz as currently being incorrectly categorized.
cc @zerokarmaleft

Bug 1675824 Remove FirefoxReality from list of apps included in KPIs

---

sql/moz-fx-data-shared-prod/udf_js/glean_percentile/udf.sql

Fixes #1527 as a result of #1523.

Fix #1527 - Add missing semicolon between udf and test

---

dags/bqetl_google_analytics_derived.py
sql/moz-fx-data-marketing-prod/ga_derived/www_site_empty_check_v1/metadata.yaml

Add submission_date to ga query

---

bigquery_etl/query_scheduling/task.py
dags.yaml
dags/bqetl_monitoring.py
sql/moz-fx-data-shared-prod/monitoring/bigquery_etl_scheduled_queries_cost_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/bigquery_etl_scheduled_query_usage_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/column_size_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/stable_table_sizes_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/structured_distinct_docids_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/telemetry_distinct_docids_v1/metadata.yaml

Depends on https://github.com/mozilla/telemetry-airflow/pull/1181

Schedule monitoring tasks

---

bigquery_etl/routine/parse_routine.py
tests/routine/test_parse_routine.py
tests/validation/hmac_sha256.py

Work in progress (fixes #1476)
Hey @scholtzan could you review if I'm on the right track for routine validation. If this looks okay I'll go ahead and add tests. Thanks!

Update routine metadata handling and validation (fixes #1476)

---

sql/mozfun/hist/string_to_json/metadata.yaml
sql/mozfun/hist/string_to_json/udf.sql

Will be used here: https://github.com/FirefoxGraphics/telemetry/pull/9

Add mozfun.hist.string_to_json

---

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Same issue that was also solved in https://github.com/mozilla/jetstream/pull/323

Experimenter V6 timestamp parsing

---

dags.yaml
dags/bqetl_marketing_fetch.py
sql/moz-fx-data-marketing-prod/fetch/fetch_deduped/view.sql
sql/moz-fx-data-marketing-prod/fetch/latest_metric/view.sql
sql/moz-fx-data-marketing-prod/fetch/latest_spending/view.sql
sql/moz-fx-data-marketing-prod/fetch/latest_trafficking/view.sql
sql/moz-fx-data-marketing-prod/fetch/spend_alignment_by_campaign_v1/metadata.yaml
sql/moz-fx-data-marketing-prod/fetch/spend_alignment_by_campaign_v1/query.sql
sql/moz-fx-data-marketing-prod/fetch/spend_alignment_by_month_v1/metadata.yaml
sql/moz-fx-data-marketing-prod/fetch/spend_alignment_by_month_v1/query.sql

Marketing spend data in moz-fx-data-marketing-prod:fetch

Add queries and views for fetch marketing spend data

---

sql/moz-fx-data-shared-prod/telemetry_derived/addons_daily_v1/query.sql

Reduce complexity of addons_daily

---

sql/moz-fx-data-shared-prod/telemetry/client_probe_counts_v1/view.sql

(fixes #1483)
For reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1623180

Remove filter for search metrics in glam

---

bigquery_etl/shredder/config.py
dags/bqetl_main_summary.py
sql/moz-fx-data-shared-prod/telemetry/main_1pct/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/main_1pct_v1/init.sql
sql/moz-fx-data-shared-prod/telemetry_derived/main_1pct_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/main_1pct_v1/query.sql

Discussed with BQ engineering in [support case 25679061](https://console.cloud.google.com/support/cases/detail/25679061?project=moz-fx-data-shared-prod)

Add main_1pct view

---

bigquery_etl/docs/generate_docs.py
docs/index.md

Update index page (#1590)

---

sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/query.sql

Add a filter to remove outliers in search count for `desktop_search_aggregates_by_userstate` table

[Bug 1673979] Add filter to remove outliers in search count

---

bigquery_etl/cli/query.py

Fixes problems described in https://github.com/mozilla/bigquery-etl/pull/1670

Fix bqetl query schedule --task_name option

---

sql/moz-fx-data-shared-prod/monitoring/shredder_progress/view.sql

produce completion time estimates, instead of percent complete, and group results by airflow task and run

Update shredder_progress view

---

README.md

Not sure if this is the best way of describing things, but at least we're writing it down.

Add some data engineering specific setup instructions

---

sql/moz-fx-data-shared-prod/monitoring/structured_detailed_error_counts/view.sql

From #1677, see also https://github.com/mozilla/bigquery-etl/issues/1413

Fix errant backtick

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_first_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_last_seen_v1/metadata.yaml

See https://github.com/mozilla/bigquery-etl/issues/1713

Deschedule fxa_users_services_* for now

---

bigquery_etl/dryrun.py

Fixes https://github.com/mozilla/bigquery-etl/issues/1620

Dry run init.sql files

---

dags.yaml
dags/bqetl_account_ecosystem.py
dags/bqetl_activity_stream.py
dags/bqetl_amo_stats.py
dags/bqetl_core.py
dags/bqetl_devtools.py
dags/bqetl_fxa_events.py
dags/bqetl_gud.py
dags/bqetl_main_summary.py
dags/bqetl_messaging_system.py
dags/bqetl_vrbrowser.py

Follow-up to https://github.com/mozilla/bigquery-etl/issues/1534

Add descriptions for several DAGs

---

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Facilitates https://github.com/mozilla/jetstream/issues/456.

Add app_name and app_id to Experimenter tables

---

sql/moz-fx-data-shared-prod/telemetry/clients_daily/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/clients_first_seen/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/clients_last_seen/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/main_1pct/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry/main_nightly/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/metadata.yaml

In support of https://github.com/mozilla/bigquery-etl/pull/1735

Add descriptions for major desktop views

---

dags/bqetl_experiments_daily.py
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_base/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_hourly_v1/init.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_live/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_recents_v1/init.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_v1/init.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_base/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_hourly_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_live_v1/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_recents_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiments_daily_active_clients_v1/query.sql

Fixes https://github.com/mozilla/jetstream/issues/477

Add Fenix experiments to experiment monitoring datasets

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/users_v1/query.sql

Expose join key between vpn subscriptions and users tables

---

bigquery_etl/view/generate_stable_views.py

Part of https://github.com/mozilla/bigquery-etl/issues/1790

Format output of generate_stable_views

---

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Fixes https://github.com/mozilla/jetstream/issues/487

Fix experimenter experiments import

---

bigquery_etl/dryrun.py

Fix dry run permission filtering

---

sql/moz-fx-data-shared-prod/org_mozilla_mozregression_derived/mozregression_aggregates_v1/query.sql

Use truncation function in mozregression_aggregates incremental query (fixes #1806)

---

bigquery_etl/docs/derived_datasets/templates/table.md

Fix table-level links

---

.circleci/config.yml
bigquery_etl/view/validate_views.py

Use zetasql to validate view references

---

.circleci/config.yml
.dockerignore
README.md
bigquery_etl/cli/dag.py
bigquery_etl/dependency.py
bigquery_etl/query_scheduling/task.py
bigquery_etl/view/generate_stable_views.py
script/generate_airflow_dags
tests/cli/test_cli_query.py
tests/data/dags/test_dag_external_dependency
tests/data/dags/test_dag_with_dependencies
tests/query_scheduling/test_dag_collection.py
tests/query_scheduling/test_task.py

Use zetasql to get dependencies for dag generation

---

sql/moz-fx-data-shared-prod/telemetry_derived/mobile_usage_v1/query.sql

Follow-up to https://github.com/mozilla/bigquery-etl/pull/1824

Remove CREATE TABLE statement from mobile_usage_v1

---

.circleci/config.yml

using a modified version of the step we use to skip tests in gcp-ingestion: https://github.com/mozilla/gcp-ingestion/blob/329c0fa/.circleci/config.yml#L48-L67

Skip dag validation if unmodified

---

docs/cookbooks/creating_a_derived_dataset.md
sql/moz-fx-data-shared-prod/org_mozilla_mozregression_derived/mozregression_aggregates_v1/init.sql

Fixes https://github.com/mozilla/bigquery-etl/issues/1836

Set mozilla-public-data project in mozregression_aggregates_v1 init.sql

---

docs/mkdocs.yml

This should give us a better idea of how the users are using the docs.

Add Google Analytics to track docs usage

---

dags/bqetl_search.py
sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/metadata.yaml

Forgot about this piece re: the backfill

Allow field addition for backfill

---

bigquery_etl/dryrun.py
tests/test_dryrun.py

Depends on https://github.com/mozilla-services/cloudops-infra/pull/2916 ; marking as draft until that's merged.

Bug 1695654: Add a method to fetch dataset labels from dryrun service results

---

bigquery_etl/glean_usage/baseline_clients_daily.py
bigquery_etl/glean_usage/baseline_clients_last_seen.py
bigquery_etl/glean_usage/common.py

Builds on the new affordance for pulling dataset labels in dry runs from https://github.com/mozilla/bigquery-etl/pull/1863

Use prod MPS archive to list baseline tables for Glean usage ETL

---

sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_usage_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/mobile_usage_v1/query.sql

Fixes https://github.com/mozilla/bigquery-etl/issues/1871

Bug: Incorrect window frame for CDOU calculations

---

sql/moz-fx-data-shared-prod/telemetry/firefox_desktop_usage_2021/view.sql
sql/moz-fx-data-shared-prod/telemetry/mobile_usage_2021/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_usage_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_usage_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/mobile_usage_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/mobile_usage_v1/query.sql

Additional bug fix on https://github.com/mozilla/bigquery-etl/pull/1872

Bug: Fill in transient slices in CDOU calculations

---

sql/mozfun/bytes/extract_bits/udf.sql

- Make tests actually run
- Fix extract of first byte
- Fix extract for long byte strings
- Fix extract for begin=0

Correct extract_bits

---

sql/moz-fx-data-shared-prod/amo_prod/desktop_addons_by_client_v1/query.sql
sql/moz-fx-data-shared-prod/amo_prod/fenix_addons_by_client_v1/query.sql

See https://bugzilla.mozilla.org/show_bug.cgi?id=1693308#c2

Bug 1693308 Use highest seen versions in AMO stats

---

dags/bqetl_pocket.py
sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_v1/metadata.yaml

Fix date partition param of pocket mau query

---

sql/moz-fx-data-shared-prod/telemetry/firefox_desktop_usage_2021/view.sql

@irrationalagent is this the correct defn?

Add attributed to fx_usage

---

.circleci/config.yml
dags/bqetl_adm_engagements_daily.py

This came up in https://github.com/mozilla/bigquery-etl/pull/1899
Here's a failed ls diff https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/8550/workflows/eeead784-b8f2-490c-b341-e8684a531f93/jobs/49732

Add check for ungenerated and untracked dags

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
sql/moz-fx-data-shared-prod/static/country_codes_v1/description.txt
sql/moz-fx-data-shared-prod/static/country_names_alternate.csv
sql/moz-fx-data-shared-prod/static/country_names_v1/data.csv

This addresses the missing code discovered in https://github.com/mozilla/looker-spoke-default/pull/7

Add XK for Kosovo to country_codes

---

sql/moz-fx-data-shared-prod/telemetry/firefox_desktop_usage_2021/view.sql
sql/moz-fx-data-shared-prod/telemetry/mobile_usage_2021/view.sql

As discussed in https://github.com/mozilla/looker-spoke-default/pull/7#issuecomment-801891077

Add country_name to KPI views

---

bigquery_etl/shredder/delete.py

this is currently blocking shredder deletes from completing successfully in airflow

Handle job.total_bytes_processed is None in shredder delete summary

---

bigquery_etl/shredder/config.py

As discussed in the [Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1697454#c4), this requires unioned deletion request views to be provisioned in each `_derived` dataset in Rally environment:
```sql
WITH
pioneer_enrollments AS (
SELECT
DISTINCT submission_timestamp,
pioneer_id,
additional_properties,
JSON_VALUE(additional_properties,
'$.deletionId') AS deletion_id -- TODO: switch to deletion_id when it's added to schema
FROM
pioneer_core_stable.pioneer_enrollment_v1
WHERE
DATE(submission_timestamp)>="2021-03-01" ),
uninstall_deletion_pings AS (
SELECT
submission_timestamp,
document_id,
deletion_id
FROM
pioneer_core_stable.uninstall_deletion_v1
WHERE
DATE(submission_timestamp)>="2021-03-01" )
SELECT
uninstall_deletion_pings.submission_timestamp,
pioneer_enrollments.pioneer_id, …
```

Bug 1697454 - Shredder: use derived deletion request views as sources when deleting Rally data

---

bigquery_etl/query_scheduling/task.py
dags/bqetl_stripe.py
sql/moz-fx-data-shared-prod/stripe_external/charges_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/credit_notes_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/customers_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/disputes_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/invoices_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/payment_intents_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/payouts_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/plans_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/prices_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/products_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/setup_intents_v1/metadata.yaml
sql/moz-fx-data-shared-prod/stripe_external/subscriptions_v1/metadata.yaml

this unblocks #1919 from the issue described in #1920

Fix execution_delta for stripe_external queries

---

bigquery_etl/glean_usage/templates/baseline_clients_daily.view.sql
bigquery_etl/glean_usage/templates/baseline_clients_first_seen.view.sql
bigquery_etl/glean_usage/templates/baseline_clients_last_seen.view.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix/baseline_clients_daily/view.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix/baseline_clients_last_seen/view.sql

Follow-up to https://github.com/mozilla/bigquery-etl/pull/1941

Use fully-qualified targets in glean_usage view creation

---

bigquery_etl/public_data/publish_json.py

Fixes https://github.com/mozilla/bigquery-etl/issues/1927

Public data export temporary stage directory

---

sql/mozfun/norm/product_info/README.md
sql/mozfun/norm/product_info/udf.sql

We are tracking a more limited set of apps for 2021:
- Firefox for Android
- Firefox for iOS
- Firefox Focus for Android
- Firefox Focus for iOS

Update contributes_to_2021_kpi values

---

dags/bqetl_main_summary.py
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/metadata.yaml
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/test_aggregation/expect.yaml
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/test_aggregation/telemetry_stable.main_v4.schema.json
tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/test_aggregation/telemetry_stable.main_v4.yaml

https://bugzilla.mozilla.org/show_bug.cgi?id=1704543
Before merging, the new clients_daily schema needs to be deployed

[Bug 1704543] Add is_taskbar_pinned and launch_method to clients_daily

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_events_v1/query.sql

Bug 1707571 Ignore additional fields in fxa_auth_events

---

bigquery_etl/glean_usage/templates/baseline_clients_first_seen_v1.init.sql
bigquery_etl/glean_usage/templates/baseline_clients_first_seen_v1.query.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_first_seen_v1/init.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_first_seen_v1/query.sql
tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_first_seen_v1/test_aggregation/expect.yaml
tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_first_seen_v1/test_init/expect.yaml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1707640#c8

Bug 1707640 - Calculate sample_id in baseline_clients_first_seen

---

bigquery_etl/stripe/__init__.py
bigquery_etl/stripe/allowed_fields.py
tests/stripe/test_allowed_fields.py

and add a cli command for printing filtered schemas

Fix recursion bug in bigquery_etl.stripe.allow_fields

---

.pre-commit-config.yaml
bigquery_etl/stripe/allowed_fields.py
bigquery_etl/stripe/event.schema.json
setup.py
tests/stripe/test_allowed_fields.py

also fix schemas and don't check schema for empty values

Add stripe yaml and json files to bqetl

---

bigquery_etl/generate_incremental_table.py

fixes an issue where `script/generate_incremental_table` has been broken since the content was moved to `bigquery_etl/generate_incremental_table.py`

Remove generate_incremental_table dependency on script/entrypoint

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/metadata.yaml

See https://github.com/mozilla/bigquery-etl/issues/2021

Add back workgroup_access to clients_last_seen

---

requirements.txt

this should fix https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/9313/workflows/87c97852-936f-4950-9261-962edab01e87/jobs/56935

Update transitive dependency to fix deploy CI

---

script/generate_sql

This is causing view deploys to fail with:
> Please run ./bqetl bootstrap
Fixup from #2027

Fix inconsistent invocation of bqetl in script

---

bigquery_etl/cli/utils.py

Should fix failures in
https://github.com/mozilla/telemetry-airflow/blob/8be7a8493f77001e075b094d5eab8bc7060cf943/dags/copy_deduplicate.py#L165

Optional project_id parameter for is_authenticated

---

bigquery_etl/cli/query.py

`bqetl query backfill` always writes results to a partition. This doesn't work for clients_first_seen tables though. I added a `--no-partition` option to write to the destination table instead.

Add --no-partition option to backfill

---

bigquery_etl/cli/glean_usage.py
bigquery_etl/glean_usage/baseline_clients_daily.py
bigquery_etl/glean_usage/baseline_clients_first_seen.py
bigquery_etl/glean_usage/baseline_clients_last_seen.py
bigquery_etl/glean_usage/common.py
bigquery_etl/glean_usage/events_unnested.py
bigquery_etl/glean_usage/templates/cross_channel.view.sql
bigquery_etl/glean_usage/templates/cross_channel_events_unnested.view.sql

https://bugzilla.mozilla.org/show_bug.cgi?id=1710088
Creates `events_unnested` views for each app dataset as part of `./bqetl glean_usage generate`.

[Bug 1710088] Generate events_unnested views for app datasets

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_auth_bounce_events_v1/metadata.yaml

See https://github.com/mozilla/bigquery-etl/issues/2051#issuecomment-845362964

Deschedule fxa_auth_bounce_events query

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/query.sql

Bug 1712027 - Fix incorrect country on VPN subscriptions

---

bigquery_etl/glean_usage/templates/baseline_clients_daily_v1.query.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_daily_v1/init.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_daily_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/baseline_clients_first_seen_v1/init.sql
tests/sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/baseline_clients_first_seen_v1/test_init/expect.yaml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1712541

Bug 1712541 Guard against baseline_clients_daily duration overflow

---

requirements.in
requirements.txt

Add transitive google deps for dependabot updates

---

.circleci/config.yml

The case of the missing sql/ directory

---

bigquery_etl/cli/dryrun.py
bigquery_etl/dryrun.py
bigquery_etl/schema/__init__.py
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/init.sql

Fix schema validation for CREATE TABLE statements

---

bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2
dags/bqetl_public_data_json.py
tests/data/dags/test_public_data_json_dag

Reverts mozilla/bigquery-etl#2075

Revert "[Bug 1643735] Use dedicated queue for bqetl_public_data_json"

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/site_metrics_summary_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/site_metrics_summary_v1/schema.yaml
sql/mozfun/norm/vpn_attribution/udf.sql

https://jira.mozilla.com/browse/DS-1594
not planning to merge this until after the long weekend.

DS-1549 - Update VPN attribution logic

---

.circleci/config.yml

This is a first step on a way to transitioning bigquery-etl to private GCR repository.

Bug 1713631 - Publish Docker image to private GCR repository

---

bigquery_etl/cli/__init__.py
bigquery_etl/format_sql/format.py
bigquery_etl/glean_usage/common.py
bigquery_etl/operational_monitoring/__init__.py
bigquery_etl/operational_monitoring/templates/init.sql
bigquery_etl/operational_monitoring/templates/query.sql
bigquery_etl/util/common.py

This PR is in progress. Here are the items that need to be done for it to be ready for review:

Operational Monitoring.

---

bigquery_etl/shredder/config.py
bigquery_etl/shredder/delete.py

confirmed via dry run this works as expected and doesn't break other tables.
[Bug 1714995](https://bugzilla.mozilla.org/show_bug.cgi?id=1714995)

Bug 1714995 - add regrets reporter to shredder

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_histogram_aggregates_v1.sql.py

Fixes: https://github.com/mozilla/glam/issues/1390
Other half is https://github.com/mozilla/telemetry-airflow/pull/1324

Add GPU process histogram aggregations to GLAM

---

README.md

Should be helpful for efforts like https://github.com/mozilla/bigquery-etl/pull/2105 in the future

Add documentation for dataset_metadata.yaml

---

bigquery_etl/dryrun.py
bigquery_etl/schema/__init__.py
bigquery_etl/view/generate_stable_views.py
bigquery_etl/view/publish_views.py

https://bugzilla.mozilla.org/show_bug.cgi?id=1713623

[Bug 1713623] Add field descriptions to stable views

---

dags/bqetl_mozilla_vpn.py
sql/moz-fx-data-shared-prod/mozilla_vpn/funnel_fxa_login_to_protected/view.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_fxa_login_to_protected_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_fxa_login_to_protected_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_fxa_login_to_protected_v1/schema.yaml

originally defined in: https://sql.telemetry.mozilla.org/queries/76251/source#190143
Moving it here so it can be re-used in Looker

Add VPN funnel query from redash

---

bigquery_etl/cli/__init__.py
bigquery_etl/subplat/__init__.py
bigquery_etl/subplat/apple.py
dags.yaml
dags/bqetl_app_store_connect.py
requirements.in
requirements.txt
setup.py
sql/moz-fx-data-marketing-prod/apple_app_store/report_subscriber_detailed_v13/metadata.yaml
sql/moz-fx-data-marketing-prod/apple_app_store/report_subscriber_detailed_v13/query.py

testing the auth parts of this is blocked on [Bug 1710928](https://bugzilla.mozilla.org/show_bug.cgi?id=1710928)

Bug 1709742 - Add command to import subscriber report from apple

---

bigquery_etl/subplat/apple.py

also fix typo, and update schema to match types provided in https://help.apple.com/app-store-connect/#/itcf20f3392e

Add report date as time partitioning field for apple reports

---

bigquery_etl/stripe/event.schema.json
bigquery_etl/stripe/invoice.schema.json
bigquery_etl/stripe/subscription.schema.json

fixes stripe events import for 2021-06-15

Add field to stripe subscription and invoice schemas

---

sql/moz-fx-data-shared-prod/telemetry_derived/experiments_daily_active_clients_v1/query.sql

Also needs to be backfilled to 2021-06-07

[Bug 1716895] Add ios to experiments_daily_active_clients

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v1/query.sql

[DS-1650](https://mozilla-hub.atlassian.net/browse/DS-1650)

DS-1650 - Update available geos

---

bigquery_etl/shredder/config.py

This fixes two issues:
* automatic discovery of derived and analysis tables with nested `rally_id`
* incorrect handling of `rally_zero_one` study (Shredder query failed when it tried to access `metrics.uuid.rally_id` in `rally_zero_one_stable` table)

Shredder fixes for Rally on Glean

---

sql/moz-fx-data-shared-prod/search/mobile_search_clients_daily/view.sql
sql/moz-fx-data-shared-prod/search/search_clients_daily/view.sql
sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/metadata.yaml
sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/query.sql
sql/moz-fx-data-shared-prod/search_derived/search_metric_contribution_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/addons_daily_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/adm_engagements_daily_v1/query.sql

Final step to finish https://mozilla-hub.atlassian.net/browse/DS-1613
After this is merged, I will run the following to make sure
the views no longer exist:
```
bq rm -f moz-fx-data-shared-prod:search.search_clients_daily
bq rm -f moz-fx-data-shared-prod:search.mobile_search_clients_daily
bq rm -f mozdata:search.search_clients_daily
bq rm -f mozdata:search.mobile_search_clients_daily
```

[DS-1613] Remove search_clients_daily

---

.circleci/config.yml
.github/workflows/push-to-upstream.yml

Fixes the `/home/runner/work/_temp/a76e427e-af4c-4f69-8779-c68e2869d4ad.sh: line 52: /home/runner/.ssh/known_hosts: No such file or directory` error

Fix Github workflow

---

.circleci/config.yml
.github/pull_request_template.md
README.md

Docs for how to use the workflow + PR template. I'm not sure if there should be more items on the PR checklist.

Update docs and add pull request template

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql

[Bug 1719168] Limit max pings in clients_daily to 150000

---

bigquery_etl/dependency.py

Fix jvm startup race condition

---

dags/bqetl_iprospect.py
sql/moz-fx-data-marketing-prod/iprospect/detail_export_v1/metadata.yaml

I forgot to specify the `date` parameter

Add date parameter for iprospect import

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_first_seen/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/init.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_first_seen_v1/query.sql

Bug 1719698 - Fxa users first seen

---

tests/README.md

Small update to testing docs

---

dags/bqetl_subplat.py
sql/moz-fx-data-shared-prod/stripe_external/events_v1/metadata.yaml

Fix typo in stripe events arguments

---

.circleci/config.yml
script/generate_sql

This generates the SQL for all of the incremental GLAM Glean queries ahead of time, to facilitate queries [that take advantage of the backfill command from the generated-sql branch](https://github.com/mozilla/telemetry-airflow/blob/161dda0bf5839c5a929bb9c8659cede32361accb/dags/copy_deduplicate.py#L166-L177). I'd like to decouple the queries so rerunning the jobs doesn't lead to weirdness.
An alternative would be to run generate the sql and run the query every time.
[here's a diagram of tasks as found by `bqetl dependency show sql/glean-fenix-dev`](https://mermaid-js.github.io/mermaid-live-editor/view/#eyJjb2RlIjoiZ3JhcGggVERcbiBvcmdfbW96aWxsYV9mZW5peF9fY2xpZW50c19kYWlseV9oaXN0b2dyYW1fYWdncmVnYXRlcyogLS0-IG9yZ19tb3ppbGxhX2Zlbml4X192aWV3X2NsaWVudHNfZGFpbHlfaGlzdG9ncmFtX2FnZ3JlZ2F0ZXNfdjFcbiB …

Add statements to generate glam queries for fenix

---

bigquery_etl/copy_deduplicate.py

Add partition id to intermediate copy job sources

---

bigquery_etl/copy_deduplicate.py

This seems to have resolved itself. I tried `copy_table()` again on yesterday's tmp tables and it worked without any issues.

Revert copy_deduplicate tmp table stages

---

bigquery_etl/copy_deduplicate.py

Reverts mozilla/bigquery-etl#2229
It happened again....

Revert "Revert copy_deduplicate tmp table stages"

---

bigquery_etl/copy_deduplicate.py

GCP support said they have fixed the issue causing internal server errors. I ran a quick test and everything worked without problems. I guess we can go back to the old copy_dedup version of the script.

Revert copy_deduplicate workaround

---

bigquery_etl/view/__init__.py

Fix typo in comment

---

bigquery_etl/view/__init__.py

Fix skipping view validations when publishing

---

requirements.in
requirements.txt

Need to do work and can't wait for dependabot

Manual bump of google-api-core

---

requirements.in
requirements.txt

Bump google-api-core dependency to 1.31.2

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml

Bug 1725394 Add background update to clients_daily

---

bigquery_etl/events_daily/query_templates/event_types/templating.yaml
bigquery_etl/events_daily/query_templates/event_types/view.sql
bigquery_etl/events_daily/query_templates/events_daily/templating.yaml
bigquery_etl/events_daily/query_templates/events_daily/view.sql
sql/moz-fx-data-shared-prod/fenix/migrated_clients/view.sql

Currently release channel only. 
* events_daily
* event_types
* migrated_clients
Motivation: https://github.com/mozilla/lookml-generator/pull/200

Add or generate various app-data specific views for fenix

---

bigquery_etl/glean_usage/glean_app_ping_views.py

Fixes https://github.com/mozilla/bigquery-etl/issues/2290

Check bq_dataset_family and app name for GleanAppPingViews

---

.circleci/config.yml
Dockerfile

also use docker orb and build docker images on branches, but only deploy on main and tags
Fixes #2287

Fix non-private image builds

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml

For this PR https://github.com/mozilla/bigquery-etl/pull/1537, based on this doc https://docs.google.com/document/d/1UYjvzuARWKhgkuM9mvsxGO0PgKE-Ehil3Sqqksl0qlI/edit

Add urlbar prefs to clients_daily

---

sql/moz-fx-data-shared-prod/telemetry/urlbar_clients_daily/view.sql

Forgot to put this in https://github.com/mozilla/bigquery-etl/pull/1537

Create view for urlbar_clients_daily

---

sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/query.sql
tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/telemetry.clients_daily.schema.json

Follow-up to https://github.com/mozilla/bigquery-etl/pull/2332

Bug 1729970 Add quicksuggest prefs to urlbar_clients_daily

---

sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_extract_v1/query.sql

The glam_sample_counts_extract_v1 had been modified to include the entire result set than using ranking

modified the sample counts extract query

---

sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v1/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/structured_detailed_error_counts_v1/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/structured_error_counts_v1/view.sql

See https://mozilla-hub.atlassian.net/browse/DSRE-153
Follow-up to https://github.com/mozilla/bigquery-etl/pull/2331

Move monitoring queries to hit authorized errors view

---

sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_extract_v1/query.sql

Added the app_version and total_samples filter to reduce the output file size on gcs

modified glam sample counts extract query for performance

---

bigquery_etl/query_scheduling/task.py
bigquery_etl/query_scheduling/templates/airflow_dag.j2
dags/bqetl_subplat.py
sql/moz-fx-data-shared-prod/mozilla_vpn_external/vat_rates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_vpn_external/vat_rates_v1/query.py
sql/moz-fx-data-shared-prod/mozilla_vpn_external/vat_rates_v1/schema.yaml

Import VAT rates from Google Sheets

---

sql/moz-fx-data-shared-prod/contextual_services/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/contextual_services_derived/dataset_metadata.yaml

For https://mozilla-hub.atlassian.net/browse/DSRE-152
Depends on https://github.com/mozilla-services/cloudops-infra/pull/3376

Remove dataset workgroup_access for contextual services

---

bigquery_etl/dryrun.py
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_all/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_all/view.sql
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_structured/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_structured/view.sql
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_stub_installer/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_stub_installer/view.sql
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_telemetry/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_telemetry/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/deletion_request_volume_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/deletion_request_volume_v1/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/structured_distinct_docids_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/structured_distinct_docids_v1/query.py
sql/moz-fx-data-shared-prod/monitoring_derived/structured_error_counts_v1/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/telemetry_distinct_docids_v1/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/telemetry_distinct_docids_v1/query.sql
tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/telemetry.clients_daily.yaml

See https://mozilla-hub.atlassian.net/browse/DSRE-174

Pbd monitoring

---

sql/moz-fx-data-shared-prod/contextual_services/event_aggregates/metadata.yaml
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/metadata.yaml

Fixes a regression from https://github.com/mozilla/bigquery-etl/pull/2361

Add table-level ACLs for contextual services aggregates

---

sql/moz-fx-data-shared-prod/mlhackweek_search/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/mlhackweek_search_derived/dataset_metadata.yaml

Needed for https://github.com/mozilla-services/cloudops-infra/pull/3395

Set mlhackweek-search dataset-level ACLs

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/query.sql

[Bug 1732708] Fix clients_daily_joined date filtering

---

sql/moz-fx-data-shared-prod/monitoring_derived/structured_distinct_docids_v1/query.py

Follow-up to https://github.com/mozilla/bigquery-etl/pull/2372

Bug 1732293 Fixup for distinct_docids query

---

bigquery_etl/cli/query.py
bigquery_etl/cli/utils.py
docs/cookbooks/common_workflows.md

Motivated by this: https://gist.github.com/wlach/1da0a4769c5cc9f73897c0ee1555f145

Specify that --project-id is required for bqetl backfill

---

bigquery_etl/glean_usage/common.py
bigquery_etl/glean_usage/templates/clients_last_seen_joined.metadata.yaml
bigquery_etl/glean_usage/templates/metrics_clients_daily.metadata.yaml
bigquery_etl/glean_usage/templates/metrics_clients_last_seen.metadata.yaml

Fix metadata for derived app-name datasets

---

bigquery_etl/cli/glean_usage.py
bigquery_etl/glean_usage/templates/clients_last_seen_joined.metadata.yaml
bigquery_etl/glean_usage/templates/clients_last_seen_joined.query.sql
bigquery_etl/glean_usage/templates/metrics_clients_daily.metadata.yaml
bigquery_etl/glean_usage/templates/metrics_clients_daily.query.sql
bigquery_etl/glean_usage/templates/metrics_clients_last_seen.metadata.yaml
bigquery_etl/glean_usage/templates/metrics_clients_last_seen.query.sql

Having `normalized_channel` will probably come in handy

Add normalized_channel to generated metrics datasets

---

bigquery_etl/dryrun.py
sql/moz-fx-data-shared-prod/revenue_derived/client_ltv_normalized_v1/query.sql

This is a copy of client_ltv_normalized that currently exists in this repository. The latter will be removed later on when ETL is fully switched over.

Bug 1714471 - Add client_ltv_normalized_v1 query

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v1/query.sql

https://mozilla-hub.atlassian.net/browse/DVPN-69

DVPN-69 - Add Wave IV countries

---

dags.yaml
dags/bqetl_iprospect.py

Adding shong and echo to get notified if there is a problem with the iProspect import.

Update notifications for bqetl_iprospect

---

.circleci/config.yml
bigquery_etl/cli/dryrun.py
bigquery_etl/cli/view.py
bigquery_etl/events_daily/query_templates/event_types_history_v1/templating.yaml
bigquery_etl/query_scheduling/dag_collection.py
script/entrypoint

This reduces the runtime of CI by ~50% (~8min vs ~16min)

Speed up ci

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/query.sql
tests/sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/test_overactive_filter/telemetry.clients_daily.schema.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1737374#c3

Bug 1737374 Add new Suggest data prefs to clients_daily etc

---

bigquery_etl/stripe/allowed_fields.yaml
bigquery_etl/stripe/event.schema.json
bigquery_etl/stripe/product.schema.json

[Bug 1740545](https://bugzilla.mozilla.org/show_bug.cgi?id=1740545)

Bug 1740545 - Add tax code field to stripe product table

---

sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/urlbar_clients_daily_v1/schema.yaml

This will help prevent errors when we add new fields in the future, as seen in https://bugzilla.mozilla.org/show_bug.cgi?id=1740722

Bug 1740722 Add schema.yaml to urlbar_clients_daily

---

sql/moz-fx-data-shared-prod/monitoring_derived/topsites_click_rate_live_v1/init.sql
sql/moz-fx-data-shared-prod/monitoring_derived/topsites_impression_rate_live_v1/init.sql

This fixes [CONSVC-1367](https://mozilla-hub.atlassian.net/browse/CONSVC-1367).

CONSVC-1367: exclude non-adM advertisers from the TopSites rate monitors

---

sql/moz-fx-data-shared-prod/search_terms_derived/remotesettings_suggestions_v1/metadata.yaml

Update docs for remotesettings table

---

bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_release__view_clients_daily_histogram_aggregates_v1.sql
bigquery_etl/glam/templates/logical_app_id/firefox_desktop_glam_release__view_clients_daily_scalar_aggregates_v1.sql

Corrected the channel name from 'nightly' to 'release'

corrected the channel name in the release views

---

.circleci/config.yml

This step didn't get run in development, so we didn't notice it until now.

Fix ci in production

---

bigquery_etl/operational_monitoring/__init__.py
bigquery_etl/operational_monitoring/templates/histogram_view.sql
bigquery_etl/operational_monitoring/templates/scalar_view.sql
bigquery_etl/operational_monitoring/templates/where_clause.sql

Filter out builds with not enough clients given a set of thresholds.

Filter builds in opmon with fewer clients than the given threshold

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql

needed by @YeonjooSmith for vpn funnel work

Add plan_id and product_id to fxa_content_auth_stdout_events

---

bigquery_etl/cli/query.py
bigquery_etl/metadata/parse_metadata.py
tests/metadata/test_parse_metadata.py

Follow-up to https://github.com/mozilla/bigquery-etl/pull/2541#discussion_r760572447

Partition expiration in days

---

sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v1/metadata.yaml

Using the new feature in https://github.com/mozilla/bigquery-etl/pull/2543

Set expiration metadata for suggest impressions

---

dags/bqetl_main_summary.py
dags/bqetl_public_data_json.py
sql/moz-fx-data-shared-prod/telemetry/client_probe_processes/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/client_probe_processes_v1/init.sql
sql/moz-fx-data-shared-prod/telemetry_derived/client_probe_processes_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/client_probe_processes_v1/query.sql

This will power some upcoming ETL in the Glean Dictionary. See
bug for details.

Bug 1744840 - Client probe processes public dataset

---

docs/cookbooks/common_workflows.md

Added instructions on building and serving docs

---

bigquery_etl/feature_usage/templating.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/schema.yaml

Added urlbar handoff search count to feature usage

---

sql/moz-fx-data-shared-prod/telemetry_derived/glam_client_probe_counts_extract_v1/query.sql

The glam imports are taking longer than usual and I would like to revert this code.

Revert "correcting the issue due to unicode (#2554)"

---

sql/moz-fx-data-shared-prod/search_terms_derived/remotesettings_suggestions_v1/metadata.yaml

Grant sanitizer service account access to remotesettings suggestions SVCSE-229

---

sql/mozfun/hist/merge/udf.sql

Merged histograms should order by key.

---

requirements.in
requirements.txt

Update google-api-core dependency

---

sql/moz-fx-data-shared-prod/org_mozilla_mozregression_derived/mozregression_aggregates_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/client_probe_processes_v1/metadata.yaml

Hopefully will help people understand why they exist.

Add some extra description data for some of the tables I created

---

.github/pull_request_template.md
CODEOWNERS
CONTRIBUTING.md

I'm open to any feedback on better or additional places to put this info as well as content.

Add CODEOWNERS and restricted access datasets documentation

---

sql/moz-fx-data-shared-prod/monitoring_derived/column_size_v1/query.py

Plus some changes required by linting 

Bug 1742513 Modify column size query to get columns for all stable datasets

---

dags/bqetl_error_aggregates.py
sql/moz-fx-data-shared-prod/telemetry_derived/error_aggregates_v1/metadata.yaml

Swaps wlachance out for wkahngreene as owner of error_aggregates after PR #2608.

Update error_aggregates DAG ownership

---

sql_generators/stable_views/__init__.py

Fix schema generation when generating SQL

---

sql/moz-fx-data-shared-prod/revenue_derived/dataset_metadata.yaml

https://github.com/mozilla/private-bigquery-etl/pull/51/files#r781668229

Update revenue_derived description

---

dags/bqetl_pocket.py
sql/moz-fx-data-shared-prod/pocket/spoc_tile_ids/metadata.yaml
sql/moz-fx-data-shared-prod/pocket/spoc_tile_ids/view.sql
sql/moz-fx-data-shared-prod/pocket_derived/spoc_tile_ids_history_v1/metadata.yaml
sql/moz-fx-data-shared-prod/pocket_derived/spoc_tile_ids_history_v1/query.py
sql/moz-fx-data-shared-prod/pocket_derived/spoc_tile_ids_history_v1/schema.yaml
sql/moz-fx-data-shared-prod/pocket_derived/spoc_tile_ids_v1/metadata.yaml
sql/moz-fx-data-shared-prod/pocket_derived/spoc_tile_ids_v1/query.sql
sql/moz-fx-data-shared-prod/pocket_derived/spoc_tile_ids_v1/schema.yaml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1743493

Bug 1743493 Import pocket spoc tile ID data

---

sql_generators/derived_view_schemas/__init__.py

Some schemas are not being written because of dry-running with no partition key even though the partition key is there. I think this is because `bqetl dependency record` runs after schema generators. We can dynamically get the references from the view file instead of waiting for metadata to be written to fix that here.
Also skip views to stable tables since there's another generator for that and skip udfs.
Missing schemas on https://mozilla.github.io/bigquery-etl/mozdata/introduction/ should fall into these categories now: 
- Views to tables that don't have defined partition keys
- Views that can't easily be dry-run (eg. views to multiple tables each with partition keys)
- Nested views (view -> view -> table)
Will be tackling these in follow-ups (as much as possible)
Checklist for …

Skip udfs and views to stable tables; dynamically extract view refs

---

dags/bqetl_feature_usage.py
sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/feature_usage_v2/query.sql
sql/mozfun/norm/truncate_version/udf.sql
sql_generators/feature_usage/templates/query.sql

Closes https://github.com/mozilla/bigquery-etl/issues/2523
Also added a test for truncate app version 

Changed feature_usage string to number comparisons

---

bigquery_etl/stripe/allowed_fields.yaml
bigquery_etl/stripe/event.schema.json
bigquery_etl/stripe/invoice.schema.json

fixes [Bug 1750010](https://bugzilla.mozilla.org/show_bug.cgi?id=1750010)

Bug 1750010 - Add new field for stripe invoices

---

sql/moz-fx-data-shared-prod/monitoring/suggest_impression_rate_live/view.sql
sql/moz-fx-data-shared-prod/monitoring_derived/suggest_click_rate_live_v1/init.sql
sql/moz-fx-data-shared-prod/monitoring_derived/suggest_impression_rate_live_v1/init.sql
sql/moz-fx-data-shared-prod/monitoring_derived/suggest_impression_rate_v1/init.sql
sql/moz-fx-data-shared-prod/monitoring_derived/suggest_impression_rate_v1/query.sql

See https://mozilla-hub.atlassian.net/browse/SUGGEST-178

SUGGEST-178 Add impression and click counts per release channel

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_oauth_events/view.sql

Add `utm_content` field to `fxa_content_auth_oauth_events` table

---

dags/bqetl_subplat.py
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/exchange_rates_v1/metadata.yaml

Add MYR to base currencies for VPN

---

dags/bqetl_pocket.py
sql/moz-fx-data-shared-prod/pocket/twice_weekly_active_user_counts/metadata.yaml
sql/moz-fx-data-shared-prod/pocket/twice_weekly_active_user_counts/view.sql
sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_history_v1/metadata.yaml
sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_history_v1/query.py
sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_history_v1/schema.yaml
sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_v1/metadata.yaml
sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_v1/query.sql
sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_v1/schema.yaml

Pocket twice weekly active user (TWAU) import

---

sql/moz-fx-data-shared-prod/activity_stream/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/activity_stream_bi/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/activity_stream_derived/dataset_metadata.yaml

This also grants access to derived even though there's nothing there and they didn't ask for it.

Grant pocket prefect access to activity stream datasets DSRE-532

---

bigquery_etl/shredder/bug1751979.py
bigquery_etl/shredder/delete.py

See https://bugzilla.mozilla.org/show_bug.cgi?id=1751979#c7
Relies on https://github.com/mozilla/bigquery-etl/pull/2711

Shredder sanitize

---

sql/moz-fx-data-shared-prod/monitoring_derived/shredder_progress/view.sql

task names changed in https://github.com/mozilla/telemetry-airflow/pull/1467

Update shredder task names in progress view

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_v1/schema.yaml

Fix renamed fields in vpn channel_group_proportions_v1

---

sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/schema.yaml

Fixes https://github.com/mozilla/bigquery-etl/issues/2716

Add active_hours_sum to unified metrics query

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v1/query.sql

fixes [DVPN-110](https://mozilla-hub.atlassian.net/browse/DVPN-110)

DVPN-110 - Update available geos for vpn data studio funnel dashboard

---

sql/moz-fx-data-shared-prod/mozilla_vpn/channel_group_proportions/view.sql
sql/moz-fx-data-shared-prod/mozilla_vpn/funnel_product_page_to_subscribed/view.sql

fixes [DVPN-82](https://mozilla-hub.atlassian.net/browse/DVPN-82)

DVPN-82 - Add views of new vpn funnel tables

---

script/generate_sql

Make sure generate_sql script is compatible with cloud pipeline

---

bigquery_etl/glam/models.py
bigquery_etl/glam/templates/extract_sample_counts_v1.sql
bigquery_etl/glam/templates/view_sample_counts_v1.sql
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__extract_sample_counts_v1/query.sql
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__extract_sample_counts_v1/schema.yaml
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__view_sample_counts_v1/schema.yaml
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__view_sample_counts_v1/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_extract_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_v1/query.sql

Corrected the logic for sample counts and added the same for scalars (desktop and glean products)
relates to [glam issue](https://github.com/mozilla/glam/issues/1240)

 added sample counts for desktop and glean products (both scalars and histograms)

---

bigquery_etl/glam/templates/extract_sample_counts_v1.sql
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__extract_sample_counts_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_v1/query.sql

add process to sample counts glam tables. 
Will need to create a subsequent PR to add to the extract tables.

add process to sample counts glam tables

---

bigquery_etl/glam/templates/extract_sample_counts_v1.sql
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__extract_sample_counts_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/glam_sample_counts_extract_v1/query.sql

Fixes the issue in fenix dag: https://workflow.telemetry.mozilla.org/log?dag_id=glam_fenix&task_id=query_org_mozilla_fenix_glam_beta__extract_sample_counts_v1&execution_date=2022-02-24T02%3A00%3A00%2B00%3A00

added client_agg_type column

---

bigquery_etl/operational_monitoring/templates/scalar_query.sql

See https://bugzilla.mozilla.org/show_bug.cgi?id=1757440

[Bug 1757440] Fix opmon scalar grouping

---

bigquery_etl/shredder/config.py
bigquery_etl/shredder/delete.py

Addresses issues identified in
https://github.com/mozilla/bigquery-etl/pull/2731/files#r815128890

Fixups for clients_daily and search_clients_daily sanitization

---

bigquery_etl/dryrun.py
sql/moz-fx-data-shared-prod/stripe/itemized_payout_reconciliation/view.sql

[DVPN-111](https://mozilla-hub.atlassian.net/browse/DVPN-111)

DVPN-111 - Add view of stripe report with state information

---

bigquery_etl/dryrun.py

Exempt mobile topsites views from dry run

---

sql/moz-fx-data-shared-prod/mozilla_vpn/channel_group_proportions/view.sql

Fix copypasta in channel_group_proportions view

---

bigquery_etl/dryrun.py
dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts/nonprod_fxa_content_auth_stdout_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_auth_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_auth_events_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_content_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_content_events_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_stdout_events_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/nonprod_fxa_stdout_events_v1/query.sql

DVPN-119 - Add ETL and view for Non-Prod FxA events

---

sql_generators/glean_usage/events_unnested.py

Fixes https://mozilla.slack.com/archives/C4D5ZA91B/p1647627120789569

Ignore VPN when generating events_unnested

---

bigquery_etl/shredder/delete.py

Bug 1759019 - Don't drop partitions when shredding whole tables

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/all_subscriptions_v1/query.sql

Update stripe billing grace period

---

bigquery_etl/dryrun.py
dags.yaml
dags/bqetl_cjms_nonprod.py
sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/flows_v1/metadata.yaml
sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/flows_v1/query.sql
sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/refunds_v1/metadata.yaml
sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/refunds_v1/query.sql
sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/subscriptions_v1/metadata.yaml
sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/subscriptions_v1/query.sql

DVPN-119 - Add ETL for Non-Prod CJMS

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
sql/moz-fx-data-shared-prod/static/country_codes_v1/description.txt
sql/moz-fx-data-shared-prod/static/country_codes_v1/schema.json

Source: https://unstats.un.org/unsd/methodology/m49/overview. Diff best viewed side-by-side.

Added UNSD data to country_codes table

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv

Quick follow-up to https://github.com/mozilla/bigquery-etl/pull/2839, missed a comma!

Missing comma from #2839

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
sql/moz-fx-data-shared-prod/static/country_names_v1/data.csv
sql_generators/country_code_lookup/aliases.yaml

Added a missing data entry and aliases for unknown country values.

Added unknown country aliases and entry

---

bigquery_etl/shredder/config.py

Bug 1761553 - Fix client_id field discovery in Rally analysis tables

---

pom.xml

alternative to #2879 that only partially reverts #2862 but hopefully may still fix #2878

Revert zetasql to 2021.09.1

---

.circleci/config.yml
Dockerfile
README.md
bigquery_etl/dependency.py
conftest.py
docs/cookbooks/testing.md
netlify.toml
pom.xml
src/main/java/com/mozilla/telemetry/ZetaSqlHelper.java

Reapply "Update to zetasql 2022.02.1 (#2862)"

---

sql/moz-fx-data-shared-prod/search/mobile_search_clients_engines_sources_daily/view.sql
sql/moz-fx-data-shared-prod/search/search_clients_engines_sources_daily/view.sql
sql/moz-fx-data-shared-prod/telemetry/clients_daily_v6/view.sql
sql/moz-fx-data-shared-prod/telemetry/events_v1/view.sql

For downstream access to numerical version data for search data scientists/analysts

Added brower_version_info to a few search and client views

---

dags.yaml
dags/bqetl_main_summary.py

Update main_summary DAG emails

---

dags.yaml
dags/bqetl_nondesktop.py

Marissa has left, updating owners

Update DAG owners

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/nonprod_fxa_content_auth_stdout_events/view.sql

DS-1982 - Fix dimensions names in fxa_content_auth_stdout_events

---

script/glam/export_csv
script/glam/generate_and_run_desktop_sql
script/glam/generate_glean_sql
script/glam/run_glam_sql

I'd like to log statements to better understand ETL process.

Glam-ETL: print out script statements

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml

See https://bugzilla.mozilla.org/show_bug.cgi?id=1756917#c3

Bug 1756917 Add browser.urlbar.suggest.bestmatch to clients_daily

---

netlify.toml

Fail Netlify build if any subcommand fails

---

.gitignore
docs/cookbooks/common_workflows.md

This PR updates the instructions to add and remove fields from a table schema, with the purpose of:
- Make instructions generic, and clear that they apply to any table schema.
- Add some recommendations and links that can be useful while deleting a field.
- Highlight a bit the important steps.
- Also a tiny update of the gitignore file to include Pycharm's generated folder .idea/

Update bigquery-etl cookbooks

---

sql/moz-fx-data-marketing-prod/acoustic/raw_recipient_raw_v1/metadata.yaml
sql/moz-fx-data-marketing-prod/acoustic/raw_recipient_raw_v1/query.sql

addressing comments raised by @jklukas in #2939
https://github.com/mozilla/bigquery-etl/pull/2939

addressing comments raised by @jklukas in #2939

---

bigquery_etl/cli/query.py

Ignore country_code_lookup generator on backfill started by query backfill

---

bigquery_etl/cli/query.py

Similar to the dryrun module. For queries that have date partitions other than `submission-date`

Use the query metadata's defined date_partition_parameter for CLI backfills

---

sql/moz-fx-cjms-nonprod-9a36/cjms_bigquery/subscriptions_v1/query.sql

https://mozilla-hub.atlassian.net/browse/DVPN-142

Account for coupons for non-prod CJMS subscriptions (DVPN-142)

---

dags/bqetl_acoustic_contact_export.py
dags/bqetl_acoustic_raw_recipient_export.py
sql/moz-fx-data-marketing-prod/acoustic/contact_raw_v1/metadata.yaml
sql/moz-fx-data-marketing-prod/acoustic/contact_v1/metadata.yaml
sql/moz-fx-data-marketing-prod/acoustic/raw_recipient_raw_v1/metadata.yaml
sql/moz-fx-data-marketing-prod/acoustic/raw_recipient_v1/metadata.yaml

fixing parameter passing for the bqetl process

---

dags.yaml
dags/bqetl_subplat.py

Bug 1768419 - Add note to subplat dag docs for airflow triage

---

docs/reference/airflow_tags.md

Removed link to docs

---

sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v2/query.sql

Motivated by the [Merino processing incident](https://docs.google.com/document/d/1z1RnSt-YRv_fQh1fj7cYi7xGPW5iv6ffVO7kPz4sKY0/edit#heading=h.p64b1qfksx4w)

Check for log routing issues in sanitized queries

---

sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/init.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/query.sql
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_aggregation/contextual_services.quicksuggest_click.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_aggregation/contextual_services.quicksuggest_impression.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_aggregation/expect.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_overactive_filter/contextual_services.quicksuggest_click.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_overactive_filter/contextual_services.quicksuggest_impression.yaml
tests/sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/test_overactive_filter/expect.yaml

Bug 1757768: add match_type to contextual services derived dataset

---

dags/bqetl_search_terms_daily.py
sql/moz-fx-data-shared-prod/search_terms_derived/merino_log_sanitized_v3/metadata.yaml
sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v3/metadata.yaml

This time I learned my lesson about not pushing to a fork!

Add scheduling for the merino log sanitized table population

---

bigquery_etl/glam/templates/scalar_bucket_counts_v1.sql
sql/glam-fenix-dev/glam_etl/org_mozilla_fenix_glam_nightly__scalar_bucket_counts_v1/query.sql

`scalar_bucket_counts_v1` queries started failing in 2022-06 for FOG and Fenix.
They started exceeding BQ disk and memory limits available for shuffle operations, most likely because of growing number of clients, metrics, and values.
This commit introduces HyperLogLog for estimating number of clients in `scalar_bucket_counts`. In my tests, after this change, query was finishing in 30-70 minutes while the current production query fails after 4-6 hours.
I have run this query before and after the change on a 50% sample of input table.
In terms of BQ slots used, this uses ~700 vs. ~2100 before - although not exact, this can be treated as an approximation of the run time.
In terms of errors, this notebook compares both outputs and user counts: …

 Bug 1772532 - Use HLL for user counts in GLAM scalar_bucker_counts_v1 

---

sql/moz-fx-data-shared-prod/search_terms_derived/suggest_impression_sanitized_v3/init.sql

[Bug 1775029] Update init.sql to match metadata.yaml

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql

The array-batching technique used here is pretty subtle, so adding commentary to explain the technique and caution about the chance for subtle bugs.

Add code comments to clients_daily_v6 query

---

sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/experiment_events_live_v1/init.sql
sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/experiment_events_live_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/experiment_search_events_live_v1/init.sql
sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/experiment_search_events_live_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/experiment_events_live_v1/init.sql
sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/experiment_events_live_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/experiment_search_events_live_v1/init.sql
sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/experiment_search_events_live_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_live_v1/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_live_v1/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/experiments_daily_active_clients_v1/query.sql
sql_generators/experiment_monitoring/templates/templating.yaml

Fixes https://github.com/mozilla/jetstream/issues/1265
Most of this has been generated, manual changes were made to `templating.yaml`

Add experiment enrollment and search monitoring for focus nightly and beta

---

sql/moz-fx-data-shared-prod/search_terms_derived/sanitization_job_metadata_v2/init.sql
sql/moz-fx-data-shared-prod/search_terms_derived/sanitization_job_metadata_v2/metadata.yaml

Apropos of [this ticket](https://mozilla-hub.atlassian.net/browse/DENG-205). 
@quiiver and I agreed that the least disruptive way to do this is to create a new table, manually copy over the data from the old table once we know the new table is working, and then remove the old table.

Add new table with changed column names

---

sql/moz-fx-data-shared-prod/mozilla_vpn/survey_lifecycle_28d_desktop/view.sql
sql/moz-fx-data-shared-prod/mozilla_vpn/survey_lifecycle_28d_mobile/view.sql

Add views for new VPN surveys

---

sql/moz-fx-data-shared-prod/telemetry/newtab_interactions/view.sql

Normalize search engine for newtab interactions

---

sql/moz-fx-data-shared-prod/udf/extract_schema_validation_path/udf.sql

Include missing required keys in schema error paths

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_admin_server_sanitized_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v1/query.sql

Use correct partition filtering for fxa

---

sql/moz-fx-data-shared-prod/monitoring_derived/stable_and_derived_table_sizes_v1/query.py

Resolves the [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1784105) which is causing the `monitoring_derived__stable_and_derived_table_sizes__v1 ` task to fail in airflow. 
Error logs are available [here](https://workflow.telemetry.mozilla.org/log?dag_id=bqetl_monitoring&task_id=monitoring_derived__stable_and_derived_table_sizes__v1&execution_date=2022-08-10T02%3A00%3A00%2B00%3A00)

Fix the error caused due to date filter (submission_date vs submission_timestamp)

---

bigquery_etl/dryrun.py

This supports the [dont require up-to-date branches proposal](https://docs.google.com/document/d/1Dlvxl1uaxVNjdXccarHZDOmq6Js2ZRiIhTQ1pb_qcdM/edit#heading=h.5x0d5h95i329). This query usually times out.

Ignore cls query in dryrun

---

bigquery_etl/cli/query.py

Fix passing project_id when running query

---

bigquery_etl/cli/dryrun.py

Running `./bqetl query validate --use-cloud-function=false <dataset>.<table>` results in:
```
File "venv/bin/bqetl", line 33, in <module>
sys.exit(load_entry_point('mozilla-bigquery-etl', 'console_scripts', 'bqetl')())
File "/Users/.../bigquery-etl/bigquery_etl/cli/__init__.py", line 52, in cli
group(prog_name=prog_name)
File "/Users/.../bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/Users/.../bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/Users/.../bigquery-etl/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File …
```

Fix dry run without cloud function

---

sql/moz-fx-data-shared-prod/fenix/marketing_attributable_metrics/view.sql

Marketing attributable metrics view

---

bigquery_etl/dryrun.py

This is a followup to a previous change to ensure that DS can run `./bqetl query validate` even without having `dataset.get` permissions in shared-prod.

Fix dataset.get permission check in dryrun

---

bigquery_etl/query_scheduling/dag.py
bigquery_etl/query_scheduling/templates/airflow_dag.j2
bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2

https://jinja.palletsprojects.com/en/3.1.x/templates/#expression-statement
---

Use Jinja's expression statement extension

---

sql/moz-fx-data-shared-prod/telemetry/unified_metrics/view.sql

Add browser info to unified metrics

---

docs/cookbooks/common_workflows.md

docs for data scientists

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql

To allow dry runs from another project, like in #3193.
---

Fully qualify `telemetry_stable.main_v4` in `telemetry_derived/clients_daily_v6/query.sql`

---

dags/bqetl_subplat.py
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/subscription_events_v1/metadata.yaml

Delay subscription events by additional day for cancel events

---

bigquery_etl/cli/utils.py
tests/cli/test_cli_utils.py

This is a follow up to https://github.com/mozilla/bigquery-etl/pull/3186

Fix table pattern matching logic

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_first_seen/view.sql

adding a view for selecting from fxa-users-services-first-seen table

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml

See [DS-2098](See https://mozilla-hub.atlassian.net/browse/DS-2098)

MR 2022 Add columns for Felt Privacy

---

bigquery_etl/shredder/config.py

Fix typo in shredder pioneer logic

---

bigquery_etl/routine/publish_routines.py

Proposal: Write access to mozfun for DE

---

sql/moz-fx-data-shared-prod/fenix/marketing_attributable_metrics/view.sql

This updated marketing_attributable_metrics to match the data in the current dashboard.
Main changes are using the country from first seen table and doing an outer join for search.

Update marketing_attributable_metrics to match dashboard

---

bigquery_etl/cli/query.py

Remove bq output during backfills

---

.pre-commit-config.yaml
bigquery_etl/dryrun.py
dags/bqetl_ctxsvc_derived.py
dags/bqetl_main_summary.py
dags/bqetl_unified.py
sql/moz-fx-data-shared-prod/contextual_services/adm_forecasting/metadata.yaml
sql/moz-fx-data-shared-prod/contextual_services/adm_forecasting/view.sql
sql/moz-fx-data-shared-prod/contextual_services_derived/adm_forecasting_v1/metadata.yaml
sql/moz-fx-data-shared-prod/contextual_services_derived/adm_forecasting_v1/query.sql

https://mozilla-hub.atlassian.net/browse/RS-346

RS-346 AdM Forecasting Data

---

sql/moz-fx-data-shared-prod/domain_metadata_derived/dataset_metadata.yaml

[DENG-358] Add new dataset for domain metadata.

---

sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_suggest_v1/query.sql

[ADPRODUCTS-367] fill NAs with False

---

README.md

feat: updated badge status url

---

sql/moz-fx-data-shared-prod/telemetry_derived/suggest_clients_daily_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/suggest_clients_daily_v1/schema.yaml

[ADPRODUCTS-367] replace NULL with FALSE

---

sql/moz-fx-data-shared-prod/search_terms_derived/remotesettings_suggestions_v1/metadata.yaml

I'm no longer working on this and it might be wiser for folks more deep-in into the topic to own it!
I believe @chelseatroy and @quiiver are probably the right folks (or know who the right folks should be!)

Change the ownership of remotesettings_suggestions

---

sql_generators/country_code_lookup/__init__.py

Ensure target path exists when generating country_code_lookup

---

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Add targeting to experimenter_experiments

---

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Add enrolllment end date to experimenter_experiments

---

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Add targeted percent to experimenter_experiments

---

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py

Add namespace to experimenter_experiments

---

bigquery_etl/cli/query.py
bigquery_etl/dryrun.py

Make ./bqetl query schema deploy work for Python scripts without --force

---

sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_run_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_tag_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_slot_pool_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_fail_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_reschedule_v1/schema.yaml

This field is not being populated by the query and should not be there.

removed is_deleted as this field is not being generated/used

---

bigquery_etl/cli/__init__.py
bigquery_etl/cli/dryrun.py
bigquery_etl/cli/generate.py
bigquery_etl/cli/view.py
bigquery_etl/metadata/validate_metadata.py
bigquery_etl/pytest_plugin/sql.py
bigquery_etl/util/common.py
bigquery_etl/util/standard_args.py
bigquery_etl/view/__init__.py
docs/cookbooks/testing.md
script/entrypoint
tests/cli/test_cli_query.py
tests/test_run_query.py
tests/view/test_view.py

we are already installing `pytest-isort`, but we weren't actually running it

Enforce isort via pytest

---

sql/moz-fx-data-shared-prod/fenix/clients_yearly/view.sql

Add clients_yearly view

---

.vscode/launch.json.default
README.md

Add Visual Studio Code debug configuration for bqetl

---

dags/bqetl_org_mozilla_firefox_derived.py
sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1/metadata.yaml

Fix dependency for clients_yearly

---

sql/moz-fx-data-shared-prod/udf/bits_to_days_since_seen/udf.sql

Bug 1803786 - Temp fix for days_since_seen

---

sql/moz-fx-data-shared-prod/telemetry_derived/event_events_v1/query.sql

See https://bugzilla.mozilla.org/show_bug.cgi?id=1803833

[Bug 1803833] Filter out Normandy invalid-feature events sent from Nimbus QA

---

sql/moz-fx-data-shared-prod/telemetry_derived/event_events_v1/query.sql

Fix event_category filter typo

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_first_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_first_seen_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_first_seen_v1/schema.yaml

Added a new model for FxA data which contains records of when a specific user, service, device was first observed.

feat(DENG-351): added model for fxa_users_services_devices_first_seen

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_daily_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_last_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_last_seen_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_last_seen_v1/schema.yaml

feat(DENG-554): added a new model: fxa_users_services_devices_last_seen_v1

---

bigquery_etl/cli/query.py
bigquery_etl/schema/__init__.py
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_run_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_tag_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_slot_pool_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_fail_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_reschedule_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_user_v1/schema.yaml

bqetl update all query schemas and deploy new tables

---

bigquery_etl/cli/query.py

Allow deploys for tables without metadata.yaml

---

bigquery_etl/dryrun.py

Set project when dryrunning not with cloud function

---

sql/moz-fx-data-shared-prod/fenix/marketing_attributable_metrics/view.sql

Keep marketing view backwards-compatible

---

bigquery_etl/cli/view.py
bigquery_etl/view/__init__.py

to remove managed views from BigQuery when they are removed from sql dir

Add `bqetl views clean` command

---

sql/mozfun/glam/histogram_fill_buckets_dirichlet/metadata.yaml
sql/mozfun/glam/histogram_fill_buckets_dirichlet/udf.sql

As per Slack, I have made this VERY explicit, such that someone who reads this without much context should hopefully not mixup the lowercase p/k with the upper case ones.

For #3430 - Improve clarity of documentation around Dirichlet UDF

---

sql/moz-fx-data-shared-prod/telemetry/test_query/view.sql
sql/moz-fx-data-shared-prod/telemetry/test_query_ref/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/test_query_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/test_query_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/test_query_v1/schema.yaml

This is only for testing the deployment and every dataset and view created will be deleted

Add test query to test BigQuery artifact deployment

---

.circleci/config.yml

fixes https://github.com/mozilla/bigquery-etl/pull/3384#issuecomment-1335859354

enforce isort in CI

---

.vscode/launch.json.default

Add Visual Studio Code debug configuration for current Python file

---

sql/moz-fx-data-shared-prod/fenix/firefox_android_clients/view.sql

Fix duplicate column name in fenix_android_clients (bug 1805723)

---

dags/bqetl_org_mozilla_firefox_derived.py
sql/moz-fx-data-shared-prod/fenix_derived/attributable_clients_v1/metadata.yaml

Change execution_delta for upstream task

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/login_flows_v1/query.sql

feat(): updated logic_flows_v1 query reference mozdata project
Other vpn_derived queries seem to be using mozdata. Updating this reference for improved consistency.

feat(): updated logic_flows_v1 query reference mozdata project

---

sql/moz-fx-data-shared-prod/fenix_derived/attributable_clients_v1/init.sql
sql/moz-fx-data-shared-prod/fenix_derived/attributable_clients_v1/query.sql

Use new attribution table

---

sql_generators/stable_views/__init__.py

fixes https://github.com/mozilla/bigquery-etl/issues/3452

Skip main and its clones when autogenerating stable view schemas

---

sql/moz-fx-data-shared-prod/fenix/firefox_android_clients/view.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/init.sql
sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/query.sql

DENG-618, DENG-619. Collect all first_session pings and more attribution from metrics ping.

DENG-618, DENG-619. Collect all first_session pings and more attribution from metrics ping

---

sql/moz-fx-data-shared-prod/google_ads/dataset_metadata.yaml

Add dataset for google_ads

---

sql/moz-fx-data-shared-prod/google_ads/campaign_conversions_by_date/metadata.yaml
sql/moz-fx-data-shared-prod/google_ads/campaign_conversions_by_date/view.sql

Add view for conversions_by_date

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_daily_v1/schema.yaml

feat(DENG-582): Added schema.yaml for fxa_users_daily_v1

---

dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v1/init.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v1/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_last_seen_v1/schema.yaml

feat(DENG-582): adding schema to fxa users last seen v1 + updating description

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_oauth_events/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_content_auth_stdout_events/view.sql

feat(DENG-582): commented out fxa_content_ views logic and raising error using them
The error contains a deprecation message along with additional information.

feat(DENG-582): commented out fxa_content_ views logic and raising error using them

---

.circleci/config.yml

Update bigquery-etl deploy key

---

sql/moz-fx-data-shared-prod/fenix_derived/google_ads_campaign_cost_breakdowns_v1/query.sql

Add date to join

---

.circleci/config.yml

follow up to https://github.com/mozilla/bigquery-etl/pull/3508#discussion_r1072677728

Fix copying DAGs in CI

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_daily_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_daily_v1/query.sql

updated fxa_users_services_devices_daily_v1 description and added extra context to the query

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_devices_daily/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_devices_first_seen/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_devices_last_seen/view.sql

feat: added views for fxa_users_services_devices tables

---

.circleci/config.yml

Disable gh-pages

---

bigquery_etl/cli/query.py
bigquery_etl/metadata/publish_metadata.py
bigquery_etl/view/__init__.py
docs/reference/recommended_practices.md
tests/cli/test_cli_query.py

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1812301 and should unblock artifact deploys

[Bug 1812301] Publish only string typed labels

---

sql/mozfun/map/extract_keyed_scalar_sum/README.md
sql/mozfun/map/extract_keyed_scalar_sum/metadata.yaml
sql/mozfun/map/extract_keyed_scalar_sum/udf.sql

Pulled this out of #3513 because that PR can't successfully build without this function existing. I plan to rerun bqetl_artifact_deployment after deploying this change, then #3513 

Add extract_keyed_scalar_sum UDF

---

docs/cookbooks/testing.md

Adding some notes for testing and also update the paths for tests

add to documentation cookbook for testing

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_daily_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_first_seen_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_last_seen_v1/schema.yaml

docs: device_id field description updated for fxa_users_services_devices

---

sql_generators/glean_usage/glean_app_ping_views.py

Fix for https://github.com/mozilla/bigquery-etl/pull/3545#discussion_r1093854094

Fix Glean Usage view generation for repeated nested fields

---

sql_generators/README.md

Deployment details relevant when working with the sql generators.

DENG-601 Update sql-generators README with deployment info.

---

sql_generators/glean_usage/glean_app_ping_views.py

`NULL`s within `STRUCT` are always considered as `INT`, it turns out, so we have to be explicit with the type information. This should fix the failing view deploys in Airflow

Add type information to glean usage generated app views

---

sql/moz-fx-data-shared-prod/telemetry_derived/unified_metrics_v1/query.sql

DENG-601
This PR changes the unified_metrics query to collect data from Klar iOS for the columns that are now available.

DENG-601 Update unified_metrics' query for KlariOS

---

bigquery_etl/cli/generate.py
sql_generators/country_code_lookup/__init__.py
sql_generators/derived_view_schemas/__init__.py
sql_generators/events_daily/__init__.py
sql_generators/experiment_monitoring/__init__.py
sql_generators/feature_usage/__init__.py
sql_generators/glean_usage/__init__.py
sql_generators/glean_usage/baseline_clients_first_seen.py
sql_generators/glean_usage/common.py
sql_generators/glean_usage/events_unnested.py
sql_generators/glean_usage/glean_app_ping_views.py
sql_generators/search/__init__.py
sql_generators/stable_views/__init__.py

For https://github.com/mozilla/telemetry-airflow/pull/1639
`fenix.topsites_impression` got removed because it was using the dry-run function

Add --use_cloud_function option when generating SQL queries

---

requirements.in
requirements.txt

Pin Black Python package to avoid unexpected code formatting changes

---

sql/moz-fx-data-shared-prod/firefox_accounts_derived/fxa_users_services_devices_first_seen_v1/metadata.yaml

Added additional information/context around this table.

Updating metadata.yaml for fxa_users_services_devices_first_seen

---

sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1/init.sql
sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1/query.sql

Disinclude new field from clients_yearly

---

bigquery_etl/format_sql/format.py

Include instructions on how to format when checking
---

Update bqetl format messages

---

bigquery_etl/cli/dag.py
docs/reference/airflow_tags.md

Part of: https://github.com/mozilla/telemetry-airflow/pull/1642

docs: added description for triage/record_only && triage/no_triage tags

---

sql/moz-fx-data-shared-prod/fivetran_costs_derived/daily_active_rows_v1/schema.yaml

Fixing schema error from #3570

Fix schema error in fivetran_costs_derived/daily_active_rows_v1

---

sql/moz-fx-data-shared-prod/monitoring/bigquery_usage_costs/view.sql

[DENG-683](https://mozilla-hub.atlassian.net/browse/DENG-683):
* Additional columns were added to the view to align with [billing.bigquery_usage_by_user](https://github.com/mozilla-services/dataops/blob/main/bigquery/billing/billing.bigquery_usage_by_user.sql) table
[DENG-683]: https://mozilla-hub.atlassian.net/browse/DENG-683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DENG-683 Added more columns to bq cost view

---

sql_generators/glean_usage/glean_app_ping_views.py

Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1816621
Casting nested records to NULL requires the exact type information. That information needs to be generated based on the unioned schema

[Bug 1816621] Generate nested type information for unioned Glean ping views

---

.circleci/config.yml

Related to https://github.com/mozilla/bigquery-etl/pull/3594

Update SSH key for pushing generated SQL

---

sql/moz-fx-data-shared-prod/mdn_yari_derived/mdn_popularities_v1/query.py

bug(MP-267): correcting mdn bucket name

---

script/entrypoint

bug: added a debug message to entrypoint

---

bigquery_etl/cli/stage.py
bigquery_etl/dryrun.py

Followup to https://mozilla.slack.com/archives/C01E8GDG80N/p1677171113619619
Tested in https://github.com/mozilla/bigquery-etl/pull/3615

Fix stage deploy test file names

---

bigquery_etl/cli/stage.py

Related to https://github.com/mozilla/bigquery-etl/pull/3632

Fix stage identifiers - only encapsulate project name in "`"

---

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_tables_inventory_v1/schema.yaml

Fixed schema added from PR #3638

DENG-590 Fixed schema mode for owners field

---

bigquery_etl/cli/stage.py

Fix staging UDFs

---

dags/bqetl_org_mozilla_firefox_derived.py
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/client_deduplication_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/client_deduplication_v1/metadata.yaml
sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/client_deduplication_v1/metadata.yaml

Create scheduling for client_dedupe anonymizing

---

docs/cookbooks/common_workflows.md
docs/reference/stage-deploys-continuous-integration.md

Stage deploy docs

---

sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/client_deduplication_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/client_deduplication_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/client_deduplication_v1/query.sql

Add partition filters to client_dedupe queries

---

sql/moz-fx-data-shared-prod/fenix/client_deduplication/view.sql

Fix client_deduplication view

---

sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_daily/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts/fxa_users_services_last_seen/view.sql

feat(DENG-734): added views for fxa_users_daily and fxa_users_services_last_seen

---

sql/moz-fx-data-shared-prod/mdn_yari_derived/mdn_popularities_v1/query.py

MP-267 - Sync query and destination with popularitiesCron

---

sql/moz-fx-data-shared-prod/fenix/client_deduplication/view.sql

Fix view definition for client_dedupe

---

bigquery_etl/routine/publish_routines.py
sql/moz-fx-data-shared-prod/udf/pseudonymize_ad_id/udf.sql

and add optional argument to publish routines script to allow test publishing specific routines

Bug 1824188 - Allow udf.pseudonymize_ad_id to be published outside shared-prod

---

sql/moz-fx-data-marketing-prod/ga_derived/downloads_with_attribution_v1/metadata.yaml
sql/moz-fx-data-marketing-prod/ga_derived/downloads_with_attribution_v1/schema.yaml

Fixed schema types

---

sql/moz-fx-data-shared-prod/mdn_yari_derived/mdn_popularities_v1/query.py

MP-267 - Use os.path.join() + fix copy_blob() parameter + update description

---

sql/moz-fx-data-shared-prod/static/country_names_v1/data.csv
sql_generators/country_code_lookup/aliases.yaml

DENG-658 Adding 3 more Google Analytic country spellings.

---

dags.yaml
dags/bqetl_mdn_yari.py

`mdn@mozilla.com` does not actually exist.

fix: replace MDN contact email address

---

.circleci/config.yml
bigquery_etl/cli/query.py
bigquery_etl/dependency.py
bigquery_etl/dryrun.py
bigquery_etl/format_sql/formatter.py
bigquery_etl/format_sql/tokenizer.py
bigquery_etl/pytest_plugin/sql.py
bigquery_etl/routine/parse_routine.py
bigquery_etl/util/common.py
bigquery_etl/view/__init__.py
sql/mozfun/hist/string_to_json/udf.sql
sql_generators/active_users/__init__.py
sql_generators/glean_usage/common.py
tests/cli/test_cli_dependency.py
tests/format_sql/jinja_example/expect.sql
tests/routine/test_parse_routine.py
tests/test_entrypoint.py
tests/test_run_query.py

Reverts https://github.com/mozilla/bigquery-etl/pull/3689
The issues that caused queries to fail are fixed via https://github.com/mozilla/bigquery-etl/pull/3691/commits/bf8c51810f4cdfcb3d36288b041f17e8990ca1b9
Once merged I'll rerun some of the queries in Airflow that failed yesterday, just to make sure it's also running on Airflow

Jinja queries support

---

.circleci/config.yml
bigquery_etl/cli/query.py
bigquery_etl/format_sql/formatter.py
bigquery_etl/util/common.py
tests/test_entrypoint.py

Follow-up to https://github.com/mozilla/bigquery-etl/pull/3691#pullrequestreview-1365513402

Jinja related improvements

---

bigquery_etl/metrics.py
docs/reference/recommended_practices.md

Depends on https://github.com/mozilla/bigquery-etl/pull/3696
I'm planning to add more elaborate docs to dtmo that would be useful for data scientists, for example. These docs are more of a reference/quick overview of best practices.

Metric hub integration docs

---

docs/reference/recommended_practices.md

Metric-hub doc tweaks

---

docs/reference/recommended_practices.md

Fix metrics docs formatting

---

dags/bqetl_domain_meta.py
sql/moz-fx-data-shared-prod/domain_metadata_derived/top_domains_v1/metadata.yaml

remove the allow_field_addition parameter

---

sql/moz-fx-data-shared-prod/telemetry/active_users_aggregates/view.sql

default appname to 'Firefox Desktop'

---

sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/query.sql

Forgot to update this when we updated the forecasting table

[RS-689] Update mobile in sponsored_tiles_clients_daily

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_product_page_to_subscribed_v1/query.sql

Updating fxa events from Subplat P1 product metrics

---

sql/moz-fx-data-shared-prod/udf_js/parse_sponsored_interaction/udf.sql
sql/mozfun/norm/extract_version/udf.sql

💩💩💩💩💩💩💩💩💩💩💩
follow-up to: https://github.com/mozilla/bigquery-etl/pull/3741
follow-up to: https://github.com/mozilla/bigquery-etl/pull/3742

bug(): fixing assertion testing the json field in parse_sponsored_interaction

---

sql/moz-fx-data-marketing-prod/acoustic/contact_current_snapshot_v1/schema.yaml
sql/moz-fx-data-marketing-prod/acoustic/contact_v1/schema.yaml
sql/moz-fx-data-marketing-prod/acoustic/raw_recipient_v1/schema.yaml

Fix acoustic schemas

---

sql/moz-fx-data-marketing-prod/ga_derived/downloads_with_attribution_v2/query.sql

DENG-658 Fixed TABLE_SUFFIX parsing to handle GA intraday tables

---

sql/moz-fx-data-shared-prod/udf_js/parse_sponsored_interaction/udf.sql

Quick fix for the CI failure https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/20473/workflows/719ab074-384f-48af-8b4d-28c5dd7e1a81/jobs/199869

fix parse sponsored interaction udf

---

Dockerfile

Pin cloud sdk version

---

.circleci/config.yml

To catch Dockerfile issues prior to merging.
---

Build Docker image in CI

---

sql/moz-fx-data-shared-prod/fenix_external/dataset_metadata.yaml

Make fenix_external dataset

---

bigquery_etl/dryrun.py
dags.yaml
dags/bqetl_fenix_external.py
sql/moz-fx-data-shared-prod/fenix/installs_by_country/metadata.yaml
sql/moz-fx-data-shared-prod/fenix/installs_by_country/view.sql
sql/moz-fx-data-shared-prod/fenix_external/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/fenix_external/installs_by_country_v1/metadata.yaml
sql/moz-fx-data-shared-prod/fenix_external/installs_by_country_v1/query.sql

DENG-871 - Add installs_by_country for Fenix

---

sql/moz-fx-data-shared-prod/fenix_external/installs_by_country_v1/query.sql

Remove order by clause

---

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/active_subscription_ids_v1/schema.yaml
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_live/view.sql
sql/moz-fx-data-shared-prod/mozilla_vpn_derived/channel_group_proportions_v1/schema.yaml

For DS-2876 adding country/plan interval/plan interval count

---

bigquery_etl/pytest_plugin/sql.py
bigquery_etl/pytest_plugin/sql_test.py

Reduces `test-sql` CI job runtime from ~8 minutes to ~5 minutes.
---

Parallelize SQL test table/view loads.

---

bigquery_etl/cli/query.py

Closes https://github.com/mozilla/bigquery-etl/issues/1776

Add error message for unmatched query files on bqetl query intialize

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/init.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/query.sql

Feat(): tweaking firefox ios clients and adding init

---

sql/moz-fx-data-shared-prod/apple_ads/ad_group_report/metadata.yaml
sql/moz-fx-data-shared-prod/apple_ads/ad_group_report/view.sql
sql/moz-fx-data-shared-prod/apple_ads/campaign_report/metadata.yaml
sql/moz-fx-data-shared-prod/apple_ads/campaign_report/view.sql
sql/moz-fx-data-shared-prod/apple_ads/dataset_metadata.yaml
sql/moz-fx-data-shared-prod/apple_ads/keyword_report/metadata.yaml
sql/moz-fx-data-shared-prod/apple_ads/keyword_report/view.sql
sql/moz-fx-data-shared-prod/apple_ads/organization_report/metadata.yaml
sql/moz-fx-data-shared-prod/apple_ads/organization_report/view.sql
sql/moz-fx-data-shared-prod/apple_ads/search_term_report/metadata.yaml
sql/moz-fx-data-shared-prod/apple_ads/search_term_report/view.sql

feat(DENG-789): added authorized views for accessing apple_ads datasets

---

bigquery_etl/cli/stage.py
bigquery_etl/view/__init__.py

Fixes stage deploy issues where updated views reference UDFs. With this UDFs will be published to the stage project.

Deploy UDF references to stage for views

---

sql/moz-fx-data-shared-prod/telemetry/install/view.sql

Reason for change:
Task: `publish_views` in DAG: `bqetl_artifact_deployment` failing.

Added `moz-fx-data-shared-prod` prefix to udf_js.decode_uri_attribution

---

CODEOWNERS

Implements [DENG-930](https://mozilla-hub.atlassian.net/browse/DENG-930) to comply with the CI metadata validation for change controlled sql-generated queries.
[DENG-930]: https://mozilla-hub.atlassian.net/browse/DENG-930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DENG-930 Update CODEOWNERS.

---

bigquery_etl/cli/stage.py
sql_generators/glean_usage/common.py
sql_generators/glean_usage/glean_app_ping_views.py
sql_generators/glean_usage/templates/app_ping_view.view.sql

Bug 1823627 - Normalize the channel based on probeinfo data in UNIONized views

---

sql/moz-fx-data-shared-prod/google_ads/daily_campaign_stats/view.sql

Remove NULL suffix from campaigns

---

bigquery_etl/glam/generate.py
bigquery_etl/glam/templates/latest_versions_v1.sql

This reverts commit 8ad45a0592f5d05e7a5105be30e41b6d2b0d8119.

Revert "Simplify GLAM template for getting latest versions (#3880)"

---

sql/moz-fx-data-shared-prod/backfills_staging_derived/dataset_metadata.yaml

[DENG-984](https://mozilla-hub.atlassian.net/browse/DENG-984): Created a big query dataset to store backfill data.
[DENG-984]: https://mozilla-hub.atlassian.net/browse/DENG-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DENG-984 Added backfill staging dataset

---

bigquery_etl/cli/check.py

**Summary:**
If a checks.sql file contains multiple checks separated by `;` each check will be executed regardless if a previous check failed.

Process subsequent checks for a table if a prior check fails for that table

---

bigquery_etl/cli/query.py
bigquery_etl/util/common.py
dags/bqetl_org_mozilla_firefox_derived.py
sql/moz-fx-data-shared-prod/fenix/attributable_clients_v2/view.sql
sql/moz-fx-data-shared-prod/fenix_derived/attributable_clients_v2/metadata.yaml
sql/moz-fx-data-shared-prod/fenix_derived/attributable_clients_v2/query.sql
sql/moz-fx-data-shared-prod/fenix_derived/attributable_clients_v2/schema.yaml

Fixes to Android attributable_clients

---

sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1076)

[RS-744] Add search with ads, monetizable sap, and organic search/ ad clicks/ search with ads

---

sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/schema.yaml

Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1841068
The schema.yaml has been fixed to add the other required columns.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1086)

Fix schema.yaml for search_revenue_levers_daily table

---

dags/bqetl_main_summary.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1113)

Fix DAG formatting

---

sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_history_v1/query.sql

This updates the `subscription_platform_derived.stripe_subscriptions_history_v1` ETL to use the same [address hierarchy as Stripe Tax](https://stripe.com/docs/tax/customer-locations#address-hierarchy) after the point when SubPlat first enabled [Stripe Tax](https://stripe.com/docs/tax) in production on 2022-12-01.
- On 2022-12-01 Stripe Tax was enabled for new US and EU-zone customers ([FXA-5457](https://mozilla-hub.atlassian.net/browse/FXA-5457)).
- Stripe Tax was subsequently enabled for other new customers and existing customers ([FXA-5791](https://mozilla-hub.atlassian.net/browse/FXA-5791)).
- On 2023-02-13 an [incident](https://docs.google.com/document/d/1iLUUAIMp-jbUYyXQLRDwf5eNmLbeWivc7_VEJ1I5alw/edit) was opened for Stripe not properly handling the automatic geo-location of …

Update Stripe subscriptions ETL to use customer shipping addresses (DENG-1083)

---

bqetl_project.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1120)

Remove stray commas from skip list

---

bigquery_etl/cli/check.py
bigquery_etl/cli/query.py
bigquery_etl/cli/stage.py
bigquery_etl/query_scheduling/dag_collection.py
bigquery_etl/util/common.py
dags/bqetl_ssl_ratios.py
sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/checks.sql
tests/checks/in_range.jinja
tests/checks/is_unique.jinja
tests/checks/min_rows.jinja
tests/checks/not_null.jinja
tests/util/test_common.py

This adds support for defining data checks as macros and making them reusable.
I also implemented a few checks from https://mozilla-hub.atlassian.net/browse/DENG-945
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1075)

[DENG-948] Macro support for data checks

---

dags.yaml
dags/bqetl_adjust.py
sql/moz-fx-data-shared-prod/adjust/adjust_derived/view.sql
sql/moz-fx-data-shared-prod/adjust/adjust_derived_v1/view.sql
sql/moz-fx-data-shared-prod/adjust/adjust_kpi_deliverables/view.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1131)

take rbaffourawuah@mozilla.com off of email list for DAG

---

bigquery_etl/cli/query.py
bigquery_etl/format_sql/format.py
bigquery_etl/format_sql/tokenizer.py
bqetl_project.yaml
sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/query.sql
sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/checks.sql
sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/query.sql
sql/mozfun/norm/get_earliest_value/udf.sql

Move the files for which formatting should be skipped to the new `bqetl_project.yaml`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1130)

Move format skip files to bqetl_project.yaml

---

sql/moz-fx-data-shared-prod/adjust_derived/adjust_derived_v1/query.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1143)

change api_token variable to adjust_api_token

---

sql/moz-fx-data-shared-prod/adjust_derived/adjust_derived_v1/query.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1144)

take out ending underscore from table name

---

bigquery_etl/cli/backfill.py
bigquery_etl/cli/dryrun.py
bigquery_etl/cli/generate.py
bigquery_etl/cli/query.py
bigquery_etl/cli/utils.py
bigquery_etl/cli/view.py
bigquery_etl/dependency.py
bigquery_etl/docs/__init__.py
bigquery_etl/docs/derived_datasets/generate_derived_dataset_docs.py
bigquery_etl/docs/mozfun/generate_mozfun_docs.py
bigquery_etl/metadata/publish_metadata.py
bigquery_etl/metadata/validate_metadata.py
bigquery_etl/public_data/publish_gcs_metadata.py
bigquery_etl/public_data/publish_json.py
bigquery_etl/public_data/publish_public_data_views.py
bigquery_etl/query_scheduling/generate_airflow_dags.py
bigquery_etl/routine/publish_routines.py
bigquery_etl/schema/stable_table_schema.py
bigquery_etl/static.py
bigquery_etl/util/common.py
bigquery_etl/util/standard_args.py
bigquery_etl/view/__init__.py
bqetl_project.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1157)

Move view, schema and remaining configs to bqetl_project.yaml

---

bigquery_etl/routine/publish_routines.py

typo
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1162)

Fix getting skipped routines from config

---

sql/moz-fx-data-shared-prod/stripe/itemized_tax_transactions/view.sql

DS2642 - Add stripe tax report view

---

bigquery_etl/metadata/parse_metadata.py

See title
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1235)

Publish dag name as a label

---

sql/moz-fx-data-shared-prod/telemetry_derived/main_use_counter_1pct_v1/schema.yaml

Missing fields
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1262)

CI fix update main_use_counter_1pct_v1 schema

---

sql/moz-fx-data-shared-prod/google_ads_derived/daily_ad_group_stats_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1279)

Ad group str

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml

Update some schemas missed here https://github.com/mozilla/bigquery-etl/pull/4092
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1297)

Update clients_last_seen_joined schema

---

bigquery_etl/dryrun.py

Implements [DENG-1307](https://mozilla-hub.atlassian.net/browse/DENG-1307).
[DENG-1307]: https://mozilla-hub.atlassian.net/browse/DENG-1307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1308)

Enable using more definitions e.g. macros in scheduling parameters.

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1362)

bug(1847233): updated checks.sql for app_store_funnel_v1

---

sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_v1/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_fail_v1/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_fail_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_reschedule_v1/query.sql
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_reschedule_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1382)

bug(DENG-1358): fixing ETL errors for airflow metadata queries

---

sql/moz-fx-data-shared-prod/monitoring_derived/airflow_dag_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1393)

[Bug 1848655] Set next_dagrun as TIMESTAMP field

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_non_norm_histogram_bucket_counts_v1/query.sql

See https://github.com/mozilla/bigquery-etl/pull/4078 for context. This PR adds what was missing there.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1399)

Glam ETL client count filter considers sampling for non-normalized data

---

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/backfill.yaml

For testing purposes 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1413)

Add backfill for newtab_visits_v1

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv

Like most mappings, this should definitely be done via an actual API or by processing data. 
Are there any reliable data sources for this?
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1422)

July 4th update VPN Countries

---

dags.yaml
dags/bqetl_default.py

Follow up PR to remove an unavailable option in the DAG description.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1447)

DS-2947. Update DAG bqetl_defaul description

---

bigquery_etl/routine/parse_routine.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1453)

Fix publishing udfs that use backticks in identifiers

---

README.md

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1458)

Fix Status Badge on README

---

sql/moz-fx-data-shared-prod/telemetry/clients_daily_v6/view.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1460)

Add has_adblocker_enabled to clients_daily

---

sql/moz-fx-data-shared-prod/telemetry/crashes_daily/view.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1471)

DENG-906 - Ceiling crashes in crashes_daily

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1478)

Update downstream schemas from clients_daily

---

dags/bqetl_monitoring.py
sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1494)

Bug 1852068 add date argument

---

sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_structured/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_structured/view.sql
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_stub_installer/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_stub_installer/view.sql
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_telemetry/metadata.yaml
sql/moz-fx-data-shared-prod/monitoring/payload_bytes_decoded_telemetry/view.sql

These new tables will be empty to start with. They were added in https://github.com/mozilla-services/cloudops-infra/pull/5051.
Changes to these authorized views will be [skipped](https://github.com/mozilla/bigquery-etl/blob/main/bigquery_etl/cli/view.py#L194) by airflow but should automatically deploy from jenkins once the docker image is updated. Actually, reviewing [that config](https://github.com/mozilla-services/cloudops-infra/blob/master/projects/data-shared/Jenkinsfile.bigquery#L255) they might not get updated automatically so I'll double check after merge.
For modifications to schemas in restricted namespaces (see [`CODEOWNERS`](https://github.com/mozilla/bigquery-etl/blob/main/CO …

Add per-pipeline-family PBD datasets to monitoring authorized views

---

sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/query.py
sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1499)

Deng 1202 change project id to project: changing camelCase to snake_case

---

.github/.ISSUE_TEMPLATE/data_checks.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1543)

docs(): added github issue template for reporting data checks bugs

---

sql/moz-fx-data-shared-prod/firefox_desktop_derived/onboarding_v2/backfill.yaml

Added backfill for https://mozilla-hub.atlassian.net/browse/DENG-1207
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1593)

Backfill for onboarding_v2 (Messaging System Reinstrumentation)

---

.circleci/config.yml

Update to latest orb version
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1606)

chore(ci): Update Docker orb to v2.2.

---

docs/reference/data_checks.md

docs(): Minor tweaks to the data checks docs
- Small tweaks to the marker information
- Removed trailing white spaces
- Making sure examples contain markers
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1579)

docs(): Minor tweaks to the data checks docs

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1549)

docs(): added a comment to fenix_derived.firefox_android_clients_v1 for future improvement

---

.circleci/config.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1616)

Push generated private-bigquery-etl DAGs to repo

---

dags/bqetl_firefox_ios.py
sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1611)

feat(DENG-1599): more checks added to firefox_ios_derived.app_store_funnel_v1

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/metadata.yaml

tweak(): firefox_ios_derived.app_store_funnel_v1 small tweak to the uniqueness check
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1638)

tweak(): firefox_ios_derived.app_store_funnel_v1 small tweak to the uniqueness check

---

bigquery_etl/shredder/config.py

[DENG-476](https://mozilla-hub.atlassian.net/browse/DENG-476)
[DENG-476]: https://mozilla-hub.atlassian.net/browse/DENG-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1656)

DENG-476 - Add main_v5 et al to shredder

---

bigquery_etl/query_scheduling/task.py
dags/bqetl_download_funnel_attribution.py
dags/bqetl_firefox_ios.py
dags/bqetl_fivetran_costs.py
dags/bqetl_ssl_ratios.py
tests/data/dags/test_dag_external_check_dependency
tests/data/dags/test_dag_with_check_dependencies

Most of the time a failed check will be the result of the check working correctly and catching an error in the data. Retrying these is going to unnecessarily spam us with error messages. So I think we should set checks to not retry.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1671)

Don't retry check tasks

---

bqetl_project.yaml
dags/bqetl_fxa_events.py
sql/moz-fx-data-shared-prod/firefox_accounts/docker_fxa_customs_sanitized/view.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v1/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v1/schema.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v2/metadata.yaml
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v2/query.sql
sql/moz-fx-data-shared-prod/firefox_accounts_derived/docker_fxa_customs_sanitized_v2/schema.yaml

feat(DENG-1578): docker_fxa_customs_sanitized_v2 query added and view updated
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1586)

feat(DENG-1578): docker_fxa_customs_sanitized_v2 query added and view updated

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/firefox_ios_clients_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1678)

feat(): added checks for firefox_ios_clients_v1

---

dags/bqetl_firefox_ios.py

Forgot to regenerate the DAG as part of https://github.com/mozilla/bigquery-etl/pull/4365
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1679)

bug(): regenerated bqetl_firefox_ios DAG

---

sql/moz-fx-data-shared-prod/firefox_accounts/docker_fxa_customs_sanitized/view.sql

feat(): Added jsonPayload.errno to docker_fxa_customs_sanitized view
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1682)

feat(): Added jsonPayload.errno to docker_fxa_customs_sanitized view

---

sql/moz-fx-data-shared-prod/firefox_accounts/docker_fxa_customs_sanitized/view.sql

feat(): Added jsonPayload.foundin to docker_fxa_customs_sanitized view
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1684)

feat(): Added jsonPayload.foundin to docker_fxa_customs_sanitized view

---

dags.yaml
dags/bqetl_main_summary.py
sql/moz-fx-data-shared-prod/telemetry/hcm_clients/view.sql
sql/moz-fx-data-shared-prod/telemetry_derived/hcm_clients_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/hcm_clients_v1/query.sql

so that they no longer need to depend on main summary
[DENG-476](https://mozilla-hub.atlassian.net/browse/DENG-476)
[DENG-476]: https://mozilla-hub.atlassian.net/browse/DENG-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1685)

DENG-476 - Create derived table for HCM clients dashboards

---

.github/dependabot.yml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1704)

Set dependabot reviewers to wg team

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1724)

fix(): fixing firefox_ios app_store_funnel_v1 checks config

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_2_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_clients_week_4_v1/checks.sql
sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/checks.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1725)

fix(): fixing firefox_ios funnel_retention checks config

---

sql/moz-fx-data-shared-prod/stripe/itemized_payout_reconciliation/view.sql
sql_generators/derived_view_schemas/__init__.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1080)

DS-2642 - Add plan, product, and customer shipping info to stripe itemized report

---

sql/moz-fx-data-shared-prod/stripe/itemized_payout_reconciliation/view.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1735)

Fix syntax in stripe.itemized_payout_reconciliation

---

bigquery_etl/cli/stage.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1739)

Filter files with multiple suffixes in stage deploy

---

sql/moz-fx-data-shared-prod/telemetry_derived/error_aggregates_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1793)

DENG-476 - Update error aggregates to reference main_v5

---

sql/moz-fx-data-shared-prod/telemetry_derived/latest_versions/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1795)

DENG-476 - Update latest versions to reference main_v5

---

sql/moz-fx-data-shared-prod/amo_prod/desktop_addons_by_client_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/addon_aggregates_v2/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/addon_names_v1/metadata.yaml
sql/moz-fx-data-shared-prod/telemetry_derived/addons_v2/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1788)

DENG-476 - Remove unnecessary references to main_v4 in addons ETL

---

sql/moz-fx-data-shared-prod/udf_js/main_summary_active_addons/metadata.yaml
sql/moz-fx-data-shared-prod/udf_js/main_summary_active_addons/udf.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1794)

DENG-476 - Update UDF to reference main pings instead of main_v4

---

sql/moz-fx-data-shared-prod/telemetry_derived/fog_decision_support_percentiles_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1790)

DENG-476 - Update FoG decision ETL to reference main_v5

---

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv

Change the pocket_available field to `TRUE` for new Pocket markets -- France, Italy, and Spain.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1854)

Change pocket_available for new Pocket markets

---

bqetl_project.yaml
dags/bqetl_accounts_backend_external.py
sql/moz-fx-data-shared-prod/accounts_backend_external/nonprod_emails_v1/metadata.yaml
sql/moz-fx-data-shared-prod/accounts_backend_external/nonprod_emails_v1/query.sql
sql/moz-fx-data-shared-prod/accounts_backend_external/nonprod_emails_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1880)

DENG-1879 Setup import of emails table from FxA stage CloudSQL

---

bqetl_project.yaml
dags/bqetl_accounts_backend_external.py
sql/moz-fx-data-shared-prod/accounts_backend_external/emails_v1/metadata.yaml
sql/moz-fx-data-shared-prod/accounts_backend_external/emails_v1/query.sql
sql/moz-fx-data-shared-prod/accounts_backend_external/emails_v1/schema.yaml

Should be merged after a quick validation of https://github.com/mozilla/bigquery-etl/pull/4493
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1882)

DENG-1879 Setup import of emails table from FxA prod CloudSQL

---

dags/bqetl_search_dashboard.py
sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1878)

RS-844 Remove mmccorquodale from DAG owners

---

sql/mozfun/norm/glean_ping_info/udf.sql

Turns out I broke the tests! Oops.
(Also reformatted)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1893)

Fix test for norm.glean_ping_info

---

sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_joined_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1920)

chore(): updated schema for telemetry_derived/clients_last_seen_joined_v1 to align it with the query results

---

sql/moz-fx-data-shared-prod/fenix_derived/client_adclicks_history_v1/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1933)

Add submission_date param to adclicks history

---

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql
sql_generators/glean_usage/templates/event_monitoring_live_v1.init.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1938)

Fix comments in event monitoring queries

---

sql/moz-fx-data-shared-prod/org_mozilla_fenix/review_checker_clients/view.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1947)

Add missing clients view to fenix review checker

---

sql/moz-fx-data-shared-prod/monitoring_derived/airflow_task_instance_v1/schema.yaml
sql/moz-fx-data-shared-prod/monitoring_derived/airflow_trigger_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1953)

feat(DENG-1823): updated two affected fields across task_instance and trigger airflow metadata tables to type JSON

---

sql/moz-fx-data-shared-prod/firefox_ios_derived/attributable_clients_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1958)

Use correct submission_* field

---

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/query.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1968)

change filter on final query to go back to May 2023 - the min date in the Jobs by Project table as of 11/13/23

---

sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/review_checker_clients_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/review_checker_clients_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1984)

summing sap and ad clicks

---

sql/mozfun/ga/nullify_string/README.md
sql/mozfun/ga/nullify_string/metadata.yaml
sql/mozfun/ga/nullify_string/udf.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1965)

Add ga.nullify_string UDF

---

bigquery_etl/shredder/config.py

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1977)

feat(): added fenix_derived.firefox_android_clients_v2 to shredder config

---

sql_generators/glean_usage/templates/event_error_monitoring_aggregates_v1.query.sql

This line got accidentally removed in https://github.com/mozilla/bigquery-etl/pull/4575/files
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1994)

Add back normalized_app_id for event error aggregates

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/query.sql
tests/sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/moz-fx-data-marketing-prod.65789850.ga_sessions_intraday_20230331.schema.json
tests/sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/test_single_day/expect.yaml
tests/sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/test_single_day/moz-fx-data-marketing-prod.65789850.ga_sessions_intraday_20230331.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1996)

Include GA intraday sessions tables

---

tests/checks/min_row_count.jinja

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2000)

Update min_row_count error text

---

bqetl_project.yaml
sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v1/query.sql
sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-1998)

Add conversion event; fix gclid conversions query

---

sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v1/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2001)

Remove duplicate BQ query param

---

sql/moz-fx-data-shared-prod/accounts_db_external/fxa_security_events_v1/schema.yaml
sql/moz-fx-data-shared-prod/accounts_db_external/fxa_session_tokens_v1/schema.yaml
sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_recovery_codes_v1/schema.yaml
sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_security_events_v1/schema.yaml
sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_session_tokens_v1/schema.yaml
sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_totp_v1/schema.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2039)

SVCSE-1595 Update more accounts_db schemas to match deployed tables

---

sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_clients_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2074)

Add init clause to ga_clients table

---

sql/moz-fx-data-shared-prod/mozilla_org/gclid_conversions/metadata.yaml
sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v1/metadata.yaml

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2076)

GROWTH-101 - Give census access to gclid conversions data

---

sql/moz-fx-data-shared-prod/fenix_derived/firefox_android_clients_v1/checks.sql

feat(): added ETL checks to fenix_derived.firefox_android_clients_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2043)

feat(): added ETL checks to fenix_derived.firefox_android_clients_v1

---

sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/review_checker_clients_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/review_checker_events_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/review_checker_clients_v1/query.sql
sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/review_checker_events_v1/query.sql

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-2092)

Fix the source table to point to unified view to include all apps
