sql_generators/mobile_kpi_support_metrics/__init__.py, sql_generators/mobile_kpi_support_metrics/templates/engagement.query.sql, sql_generators/mobile_kpi_support_metrics/templates/engagement.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.query.sql, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/retention.query.sql, sql_generators/mobile_kpi_support_metrics/templates/retention.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/union.view.sql
This is to ensure that the following fields are also available on the client level tables/views:
- `play_store_attribution_content`
- `play_store_attribution_term`
- `play_store_attribution_install_referrer_response`
These fields however get excluded from aggregate views and tables as the values there can be too unique which would defeat the purpose of the aggregations.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4941)
=> feat: add more granual attribution fields to the mobile_kpi_metric generator

sql_generators/glean_usage/events_stream.py, sql_generators/glean_usage/templates/events_stream_v1.query.sql
This PR adds the new column "legacy_telemetry_client_id" to the glean_usage generator for the various "events_stream_v1" tables.
* [DENG-4962](https://mozilla-hub.atlassian.net/browse/DENG-4962)
[DENG-4962]: https://mozilla-hub.atlassian.net/browse/DENG-4962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4963)
=> DENG-4962 Add legacy telemetry client ID to events_stream

sql_generators/events_daily/templates/events_daily_v1/query.sql
An overactive Fenix client on 2024-09-24 had 289,653 events, which is causing the `fenix_derived.events_daily_v1` ETL to fail with the error "*Cannot query rows larger than 100MB limit*".
* [Bug 1921117](https://bugzilla.mozilla.org/show_bug.cgi?id=1921117): Airflow task `bqetl_fenix_event_rollup.fenix_derived__events_daily__v1` failed for exec_date 2024-09-24
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4965)
=> Reduce overactive clients threshold in `events_daily_v1` ETLs (bug 1921117)

sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.checks.sql, sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.query.sql
fix(DENG-4904): mobile kpi generator attribution clients duplication
Duplication was accidentally introduced via: https://github.com/mozilla/bigquery-etl/pull/6251
This change fixes it.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4969)
=> fix(DENG-4904): mobile kpi generator attribution clients duplication

bqetl_project.yaml
Dry runs have been failing from https://github.com/mozilla/bigquery-etl/pull/6215 (although it didn't start failing right away) because the dry run service account doesn't have the permissions to read from the information schema view ([doc](https://cloud.google.com/bigquery/docs/information-schema-column-field-paths)). [Example failure](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/39602/workflows/f5991ead-ad2c-4492-a983-396e43ea2d5c/jobs/451705)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4971)
=> Add missing column views to dry run skip

sql/moz-fx-data-shared-prod/static/country_codes_v1/metadata.yaml
This PR is to grant the table moz-fx-data-shared-prod.static.country_codes_v1 permission to be read by our Census data feed tool.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4976)
=> Give Census access to country codes table

sql/moz-fx-data-shared-prod/braze_derived/subscriptions_map_v1/script.sql
Adds a new waitlist subscription to mapping for Braze subscriptions
* DENG-4978
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4983)
=> DENG-4978-adding nothing personal subscription to map

.pre-commit-config.yaml
#6211 upgraded packages in `requirements.in`, and corresponding packages in `.pre-commit-config.yaml` should be upgraded to match.
* #6211
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4985)
=> fix: Upgrade pre-commit dependencies to match `requirements.in`

bqetl_project.yaml, sql/moz-fx-data-shared-prod/sumo_ga/analytics_314096102/metadata.yaml, sql/moz-fx-data-shared-prod/sumo_ga/analytics_314096102/view.sql, sql/moz-fx-data-shared-prod/sumo_ga/analytics_432581103/metadata.yaml, sql/moz-fx-data-shared-prod/sumo_ga/analytics_432581103/view.sql
This PR creates 2 new views in the sumo_ga schema, that read from moz-fx-data-marketing-prod, since we no longer want to allow end users to query directly from moz-fx-data-marketing-prod.
* [DSRE-1681](https://mozilla-hub.atlassian.net/browse/DSRE-1681)
[DSRE-1681]: https://mozilla-hub.atlassian.net/browse/DSRE-1681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5014)
=> DSRE-1681 Create 2 new SUMO Google Analytics views in shared prod

sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/backfill.yaml
Kicks off a backfill of `search_revenue_levers_daily_v1` to populate the `serp_events` fields with historical data.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5063)
=> search_levers_daily initiate backfill

sql_generators/glean_usage/templates/event_monitoring_live.view.sql, sql_generators/glean_usage/templates/event_monitoring_live_v1.materialized_view.sql
Set partitioning and clustering for `event_monitoring` materialized views to improve refresh performance. Partitioning is recommended, especially when underlying tables have partition expiration set (which is the case for live tables): https://cloud.google.com/bigquery/docs/materialized-views-create#partitioned_materialized_views
https://mozilla.slack.com/archives/GE83ZMSAW/p1727875140069709
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5034)
=> Add partitioning and clustering for event_monitoring materialized views

.circleci/workflows.yml, bigquery_etl/query_scheduling/dag.py, bigquery_etl/query_scheduling/dag_collection.py, bigquery_etl/query_scheduling/formatters.py, bigquery_etl/query_scheduling/generate_airflow_dags.py, bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/templates/airflow_dag.j2, bqetl_project.yaml, tests/data/dags/python_script_test_dag, tests/data/dags/simple_test_dag, tests/data/dags/test_dag_duplicate_dependencies, tests/data/dags/test_dag_external_check_dependency, tests/data/dags/test_dag_external_dependency, tests/data/dags/test_dag_with_bigquery_table_sensors, tests/data/dags/test_dag_with_check_dependencies, tests/data/dags/test_dag_with_check_table_dependencies, tests/data/dags/test_dag_with_dependencies, tests/data/dags/test_dag_with_secrets, tests/data/test_sql/moz-fx-data-test-project/test/python_script_query_v1/bigconfig.yml, tests/query_scheduling/test_dag_collection.py, tests/query_scheduling/test_generate_airflow_dags.py
Changes to add bigeye tasks to trigger BigEye Metric runs for a specific dataset if a corresponding `bigconfig.yml` exists in the datasets directory.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5031)
=> feat(DENG-4602): add BigEye RunMetricOperator to DAG generation

sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/backfill.yaml
The entry date must be larger than the end date of the backfill. This should fix failing CI
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5113)
=> Fix backfill date

dags.yaml, requirements.in, requirements.txt, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/schema.yaml
Initial attempt at a new script for finding id tables for shredder.  Currently only looks for `*client_id` tables.  This uses table lineage to determine which deletion requests to use based on the upstream stable tables, compares it to the deletion sources in the shredder config, and then writes the results to a bigquery table.  If this works, the plan is to have a daily diff and create alerts/airflow failures when there are new tables that need to be added
* DENG-4256
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5107)
=> [DENG-4256] Search for shredder targets using table lineage

sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/query.py, sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/query.py, sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/query.py
* This PR makes use of the new functionality in [PR-6241](https://github.com/mozilla/bigquery-etl/pull/6241/files) 
* It changes from using Airflow environment variables passed in via CLI parameters and now uses Cloudflare auth token pulled from GSM instead.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5024)
=> feat(Cloudflare): Switch to using GSM secrets instead of airflow vars

sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/metadata.yaml, sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/query.sql, sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/schema.yaml
This PR adds the client distribution_id. This is necessary to count app push notification events and set to default events to support mobile distribution deals.
Adds engagement with the sponsored tiles feature.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5013)
=> Add distribution_id to feature_usage_events_v1

bigquery_etl/shredder/config.py
client id field in events stream is at the top-level, not in  `client_info`.  This has been causing shredder to repeatedly crash but it wasn't noticed until now because this is the first full run that has been completed in the last couple of months due to bigquery issues in August
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5312)
=> Fix client id field in accounts_frontend events_stream shredder config

sql/moz-fx-data-shared-prod/telemetry/releases/metadata.yaml
Turns out when deploying monitors to views in Bigeye `table_deployments` aren't supported. Instead we'll have to deploy a config similar to this:
```
type: BIGCONFIG_FILE
row_creation_times:
column_selectors:
- name: moz-fx-data-shared-prod.moz-fx-data-shared-prod.telemetry.releases.date
saved_metric_definitions:
metrics:
- saved_metric_id: FRESHNESS_DATA
metric_type:
type: PREDEFINED
predefined_metric: FRESHNESS_DATA
metric_name: Freshness (data)
threshold:
type: AUTO
sensitivity: MEDIUM
upper_bound_only: true
lower_bound_only: false
lookback:
lookback_window:
interval_type: DAYS
interval_value: 2
lookback_type: METRIC_TIME
bucket_size: HOUR
rct_overrides:
- date
- saved_metric_id: VOLUME_DATA
metric_type:
type: PREDEFINED
predefined_metric: VOLUME_DATA
metric_name: Volume (data) …
```
=> Disable Bigeye monitoring for telemetry.releases

sql/moz-fx-data-shared-prod/sumo_ga_derived/ga4_events_v1/metadata.yaml, sql/moz-fx-data-shared-prod/sumo_ga_derived/ga4_events_v1/schema.yaml
This PR adds the new "publisher" column to the table sumo_ga_derived.ga4_events_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5317)
=> Update schema for sumo_ga_derived.ga4_events_v1 since GA4 added a new field

bigquery_etl/cli/monitoring.py, sql/moz-fx-data-shared-prod/telemetry/releases/metadata.yaml
The BigConfig files that should be applied for views are different from those applied to tables.
This PR handles the generation of these config files for views.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5316)
=> Generate BigConfig files for views

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/query.sql
Fixes ETL errors by replacing instances of CAST with SAFE_CAST
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5404)
=> replace CAST with SAFE_CAST

bigquery_etl/query_scheduling/generate_airflow_dags.py, bigquery_etl/query_scheduling/task.py, tests/data/test_sql/moz-fx-data-test-project/test/python_script_query_v1/metadata.yaml
In the previous iteration we forgot to check if monitoring is enabled in the metadata prior to generating a monitoring task.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5403)
=> fix: only generate Airflow task for BigEye if monitoring enabled in the metadata

.circleci/workflows.yml
We've hit the no-output timeout in the `private-generate-sql` CI step a few times in recent days. I don't like doing this, but I think this is necessary.
recent CI failure: https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/40085/workflows/33829912-f544-48de-a040-f84db3ef0d33/jobs/458121
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5429)
=> Extend timeout for no output for private-generate-sql CI step

sql/moz-fx-data-shared-prod/mozilla_vpn/events_unnested/view.sql
This adds events in `vpnsession` and `daemonsession` pings to events unnested so they be viewed in the events looker explore.  This is a quick fix instead of updating the sql generator to handle these cases because `events_unnested` should be replaced by events stream anyway
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5431)
=> Add vpnsession and daemonsession pings to vpn events unnested

sql/moz-fx-data-shared-prod/monitoring/shredder_targets/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring/shredder_targets/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_joined_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_joined_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_joined_v1/schema.yaml
This adds some table metadata to `monitoring_derived.shredder_targets_v1` created in https://github.com/mozilla/bigquery-etl/pull/6289.  I decided to do this in an additional derived table so there isn't bunch of sql embedded in the python script
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5412)
=> Create shredder_targets_joined table with additional table metadata

.github/pull_request_template.md
This landed nearly a month ago so is a somewhat strong signal that most reviewers don't actually follow the checklist. I was looking at it because I'm about to review https://github.com/mozilla/bigquery-etl/pull/6330 which needs CI to run via the second item on the checklist.
**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/.github/reviewer_checklist.md)** <- fixed by this PR
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5433)
=> Fix PR checklist link

.circleci/workflows.yml
Bumps up the resource class size used for the `private-generate-sql` CI task that is currently failing running out of memory
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5476)
=> Add more memory for private-generate-sql task

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_merino_extract_to_gcs_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_merino_priors_to_gcs_v1/metadata.yaml
This PR adds dependencies on tables for the Merino tasks that land files in GCS. Currently, the tasks aren't waiting for the tables to be created.
[MC-1458](https://mozilla-hub.atlassian.net/browse/MC-1458)
[MC-1256](https://mozilla-hub.atlassian.net/browse/MC-1256)
[MC-1458]: https://mozilla-hub.atlassian.net/browse/MC-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MC-1256]: https://mozilla-hub.atlassian.net/browse/MC-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5482)
=> adding dependecies on upstream tables

sql_generators/glean_usage/templates/baseline_clients_daily_v1.query.sql, sql_generators/glean_usage/templates/baseline_clients_daily_v1.schema.yaml, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.schema.yaml, sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql, tests/sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/baseline_clients_daily_v1/moz-fx-data-shared-prod.org_mozilla_fenix_stable.baseline_v1.schema.json
As a follow-up this property will be added to the mobile attribution table.
---
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-4761)
=> feat: tweak glean_usage generator to include install_source in derived baseline tables

sql_generators/mobile_kpi_support_metrics/__init__.py, sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/engagement.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/engagement.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/retention.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/retention.metadata.yaml
This adds a bigeye config to all tables in the template to have freshness and volume checks.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5430)
=> feat: add bigconfig.yml to all mobile_kpi_metric tables only

sql_generators/mobile_kpi_support_metrics/__init__.py, sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/engagement.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/retention.bigconfig.yml
This is a follow-up to: https://github.com/mozilla/bigquery-etl/pull/6337 where we forgot to include this prefix.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5499)
=> fix: add missing project id prefix in the bigconfig templates in the fq_table_name

sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.query.sql
Updating the attribution_clients model so that install_source is also pulled from the baseline ping (this info is now available for fenix in the baseline ping).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5511)
=> feat: add install_source to new_profiles selection as baseline ping now contains this info on the fenix app

sql/moz-fx-data-shared-prod/fxci_derived/worker_costs_v1/backfill.yaml
I've verified that the data in the `backfills_staging_derived` table is exactly what I expect.
Bug 1923976
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5544)
=> Bug 1923976 - Mark fxci worker_costs_v1 backfill complete

sql_generators/search_v2/templates/mobile_search_clients_daily.template.sql
The PR fixes the discrepancy in `engine` coding between metrics and baseline pings.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5512)
=> Search Mobile - Fix engine coding from baseline tables

bqetl_project.yaml, sql_generators/glean_usage/common.py, sql_generators/glean_usage/event_error_monitoring.py, sql_generators/glean_usage/events_stream.py, sql_generators/glean_usage/events_unnested.py, sql_generators/glean_usage/templates/cross_channel_events_unnested.view.sql, sql_generators/glean_usage/templates/event_error_monitoring_aggregates_v1.query.sql, sql_generators/glean_usage/templates/events_stream_v1.query.sql
This adds glean apps that have events with no metrics to glean usage (currently just relay_backend since monitor_backend now has metrics).  Metrics with events are determined using the mps generated schemas
* https://bugzilla.mozilla.org/show_bug.cgi?id=1905938
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5519)
=> Bug 1905938 Support events with no metrics in glean_usage generator

sql/moz-fx-data-shared-prod/mozilla_org/desktop_conversion_events/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v2/metadata.yaml, sql/moz-fx-data-shared-prod/static/country_codes_v1/metadata.yaml
This PR fixes the workgroup names that were incorrectly put in via [PR-6361](https://github.com/mozilla/bigquery-etl/pull/6361/files)
* [DSRE-1774](https://mozilla-hub.atlassian.net/browse/DSRE-1774)
[DSRE-1774]: https://mozilla-hub.atlassian.net/browse/DSRE-1774?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5563)
=> DSRE-1774 fix workgroup names

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_tables_inventory_v1/query.py
The column is all null since https://github.com/mozilla/bigquery-etl/pull/4179
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5597)
=> Add missing last_modified_date to bigquery_tables_inventory

sql/moz-fx-data-shared-prod/monitoring_derived/outerbounds_gpu_hours_v1/schema.yaml
So it turns out, google sheets ingestion to BQ out of the box only supports converting date strings to dates if they are in the format YYYY-MM-DD, which the one in this sheet is not. So let's ingest it as a regular string and then do any necessary date conversions on the querying end.
In the future the plan is to use this data as a _substrate_ for a more _specific_ table for a looker dashboard anyway, so we can do the date conversion in the job that we create to generate that more specific table. 
* [DENG-4871](https://mozilla-hub.atlassian.net/jira/software/c/projects/DENG/boards/1996?selectedIssue=DENG-4871)
* DSRE-XXXX
[DENG-4871]: …
=> Change date data type to string

docs/bqetl.md, script/.bqetl_complete.zsh, script/bqetl_complete
I often forget the exact command names while writing them so I think this would be useful. Based on these [click docs](https://click.palletsprojects.com/en/8.1.x/shell-completion/) combining the bash and zsh scripts into one.  This works for me on macos with bash and zsh but it's kind of slow (like `bqetl --help`) possibly due to all the imports in the cli files
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5622)
=> Add shell completion script for bqetl

sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/query.py
Currently reading from the wrong delete source set so all the `detected_sources` here have the same wrong value
=> Fix detected shredder sources for tables not in shredder config

sql/moz-fx-data-shared-prod/mozilla_org/desktop_conversion_events/view.sql
To better integrate with Google Ads, we made the "activity_date" column an integer in terms of unix seconds, and then added the new column "activity_date_ts" so we also have a more human readable column of the actual event timestamp.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5628)
=> Update new "desktop conversion events" view to be more compatible with Google Ads expected format

sql/moz-fx-data-shared-prod/static/monitoring_schema_errors_notes_v1/metadata.yaml
I'm not sure why this is working currently, but I noticed in https://github.com/mozilla-services/cloudops-infra/pull/6012 that the plan included what looks like this bogus value. Other references to the same spreadsheet don't have the trailing `]`.
```
static/monitoring_schema_errors_notes_v1/metadata.yaml:13:    - https://docs.google.com/spreadsheets/d/1wMKyIyzp8yW7YpNz6hpFe0sHueeeLHdHr3p-1br2TbA]
static/monitoring_missing_document_namespaces_notes_v1/metadata.yaml:13:    - https://docs.google.com/spreadsheets/d/1wMKyIyzp8yW7YpNz6hpFe0sHueeeLHdHr3p-1br2TbA
static/monitoring_missing_columns_notes_v1/metadata.yaml:13:    - https://docs.google.com/spreadsheets/d/1wMKyIyzp8yW7YpNz6hpFe0sHueeeLHdHr3p-1br2TbA
static/monitoring_distinct_docids_notes_v1/metadata.yaml:13:    - …
```
=> chore(monitoring): fix schema errors notes URI

sql/moz-fx-data-shared-prod/firefox_desktop_derived/pageload_1pct_v1/schema.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/pageload_nightly_v1/schema.yaml
This PR is a follow-up to [PR-6390](https://github.com/mozilla/bigquery-etl/pull/6390), it updates the schema of 2 downstream tables that now pull in the 3 columns added to the Glean stable views.
* [DENG-4678](https://mozilla-hub.atlassian.net/browse/DENG-4768)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5688)
=> DENG-4768 update schemas to include 3 new columns

sql_generators/experiment_monitoring/templates/experiment_search_events_live_v1/materialized_view.sql
https://github.com/mozilla/bigquery-etl/pull/6286 seems to be doing something positive for `firefox_desktop_derived.event_monitoring_live_v1`:
Although it takes 30 days for slot time to actually blow up:
from
```sql
SELECT
creation_time,
project_id,
job_id,
total_bytes_processed / 1024 / 1024 / 1024 / 1024 AS tib_processed,
total_slot_ms / 1000 / 60 / 60 AS slot_hours,
FROM
`moz-fx-data-shared-prod.region-us.INFORMATION_SCHEMA.JOBS`
WHERE
creation_time > '2024-08-01'
AND query = "CALL BQ.REFRESH_MATERIALIZED_VIEW('moz-fx-data-shared-prod.firefox_desktop_derived.event_monitoring_live_v1')"
```
I noticed the materialized views are doing one expensive query per day, usually a little after midnight UTC possibly coinciding with the live partition being dropped. …
=> Add date partitioning to experiment_search_events materialized views

bigquery_etl/shredder/delete.py
`partition.id` is actually `"__NULL__"` and not `None` so it's sampling on the null partition and then eventually failing on the final copy.  This didn't fail last run because the null partition was already processed before this change was introduced.  Failing now because the `with-sampling` task has reached the end
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5631)
=> Prevent shredder sampling for null partition

bigquery_etl/cli/dag.py, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_alert_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_alert_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_new_mismatched_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_new_mismatched_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_new_mismatched_v1/schema.yaml
Script that fails when there are new potentially misconfigured tables in `monitoring_derived.shredder_targets_v1` compared to the previous day.  The plan is to have these fail in airflow so they can be triaged but I'm not sure if this is going to be noisy so dag is still tagged with `no_triage`
example output:
```
moz-fx-data-shared-prod.mozilla_vpn_derived.events_daily_v1: 
created on 2021-10-13, owners: ['wlachance', 'akomar']
current deletion sources:          ['org_mozilla_firefox_vpn_stable.deletion_request_v1: client_info.client_id', 'org_mozilla_ios_firefoxvpn_stable.deletion_request_v1: client_info.client_id', 'mozillavpn_stable.deletion_request_v1: client_info.client_id', 'org_mozilla_ios_firefoxvpn_network_extension_stable.deletion_request_v1: client_info.client_id']
deletion …
```
=> Create query and script for alerts for missing shredder targets

bigquery_etl/cli/query.py, bqetl_project.yaml
This introduces a skip list for skipping deploys of certain query schemas. This is a follow-up to https://github.com/mozilla/bigquery-etl/pull/6402#issuecomment-2438949491 where the table is deployed through a different process.
=> Skip list for schema deploys

sql/moz-fx-data-shared-prod/monitoring/metadata_completeness_summary/view.sql
This PR creates a new view called: 
- moz-fx-data-shared-prod.monitoring.metadata_completeness_summary
* [DENG-5757](https://mozilla-hub.atlassian.net/browse/DENG-5757)
[DENG-5757]: https://mozilla-hub.atlassian.net/browse/DENG-5757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5942)
=> DENG-5757 add new summary view of metadata completeness by project/schema

bigquery_etl/cli/query.py
Follow up to https://github.com/mozilla/bigquery-etl/pull/6404#issuecomment-2439055682
We recently introduced a skip list for skipping schema deploys. This PR ensures that these skipped schemas also do not get updated.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5934)
=> Skip updating schemas of tables that are skipped for deploys

bigquery_etl/cli/view.py
This speeds up view deploys by around 3x (in some of my local tests). Looking at the `cProfile` profile using `ThreadPool` here comes with some significant overhead.
=> Speed up view deploys by using processing pool

bigquery_etl/cli/metadata.py, tests/cli/test_cli_metadata.py
This runs the metadata for multiple artifacts in parallel. Locally I got a significant speed up. Publishing metadata for shared-prod only takes around a minute now (though that is without generated SQL content, down from 5 minutes).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5832)
=> Parallelize metadata publish

sql_generators/experiment_monitoring/templates/experiment_events_live_v1/materialized_view.sql
`experiment_events_live_v1` is one of the less expensive materialized views (~140 slots hours per day across all apps) but adding partitioning should be an easy improvement
* DENG-5931
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5946)
=> [DENG-5931] Add partitioning to experiment_events_live_v1

sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/query.sql, sql_generators/glean_usage/templates/baseline_clients_daily_v1.query.sql
This filters out overactive clients for `baseline_clients_daily` and `sponsored_tiles_clients_daily` causing memory limits to be exceeded during aggregation steps.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5945)
=> Filter overactive clients for `baseline_clients_daily` and `sponsored_tiles_clients_daily`

bigquery_etl/cli/view.py, bigquery_etl/view/__init__.py
This makes some more tweaks to the view deploy/update process by re-using the credentials for instantiating `bigquery.Client` instances. Testing this locally I got speedups of around 15%. 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5961)
=> Reuse GCP API credentials for view updates

.circleci/workflows.yml
I was looking at [this failure](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/40272/workflows/538d222d-570a-4cad-b007-5a1812f61be4/jobs/460435/steps) and noticed that empty files don't get uploaded with the circleci  artifact storage which was confusing because the failure was due to some empty `query.py` getting created during the stage deploy.  This change adds a line to all the empty `query.py` in the sql directory
Tested with [sql/query.py](https://output.circle-artifacts.com/output/job/3027b69e-d7d7-4076-a1fa-48813d4578df/artifacts/0/sql/query.py) in https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/40718/workflows/5dc2c8c4-7f32-4f86-8f16-f2a557a334fa/jobs/466045/artifacts …
=> Add line to empty query.py in CI copy_debug_sql

bigquery_etl/cli/query.py, bigquery_etl/dependency.py, bigquery_etl/schema/__init__.py, tests/cli/test_cli_dependency.py
This makes some optimizations to speed up table deploys:
- build the table dependency graph in parallel 
- reuse GCP client credentials
- use the GCP API to get table schemas when not using the cloud function, instead of doing a dry run 
These improvements shave off a few minutes for `./bqetl schema update` runs (around 10-15% faster in local runs). The main bottleneck for schema updates are the query dry runs though.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6011)
=> Speed up schema updates

bigquery_etl/cli/view.py
This fixes view deploys. The `INFORMATION_SCHEMA` tables need to be fully qualified.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6093)
=> Fully-qualify INFORMATION_SCHEMA datasets in ./bqetl view clean

bigquery_etl/dependency.py
follow-up for https://github.com/mozilla/bigquery-etl/pull/6418.  The references in the generated sql flipping around (https://github.com/mozilla/bigquery-etl/commit/d8eb3ad214af684d13e612368d6370289611999b) because the `itertools.groupby` in the dependency updating expects identical keys to be consecutive
=> Sort query references result when parallelism > 0

bigquery_etl/cli/query.py, bigquery_etl/dependency.py, bigquery_etl/schema/__init__.py, tests/cli/test_cli_dependency.py
This reverts https://github.com/mozilla/bigquery-etl/pull/6418
Looking at the run logs for the table deploys, there wasn't any speed up, so we can revert the change to fix CI.
=> Revert #6418

bigquery_etl/stripe/tax.transactions.itemized.1.schema.json, sql/moz-fx-data-shared-prod/stripe_external/itemized_tax_transactions_v1/schema.yaml
Some historical Stripe tax transactions contain exchange rates with 16 digits after the decimal, which exceeds the normal NUMERIC type's maximum scale of 9 digits after the decimal.
This is currently preventing 13 days of data from being [backfilled](https://github.com/mozilla/telemetry-airflow/pull/2117) into the `stripe_external.itemized_tax_transactions_v1` table to support the response to the SubPlat tax incident ([FXA-10591](https://mozilla-hub.atlassian.net/browse/FXA-10591)):
* 2022-12-14
* 2022-12-28
* 2022-12-29
* 2023-01-01
* 2023-01-13
* 2023-01-15
* 2023-01-22
* 2023-01-24
* 2023-02-03
* 2023-02-08
* 2023-02-13
* 2023-02-15
* 2023-02-27
* https://github.com/mozilla/telemetry-airflow/pull/2117
* [FXA-10591](https://mozilla-hub.atlassian.net/browse/FXA-10591): 2024 10 17 …
=> Change Stripe tax transaction exchange rate to BIGNUMERIC type

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/exchange_rates_v1/metadata.yaml
USD exchange rates for 17 additional currencies need to be added for the VPN wave 7 expansion scheduled to launch Nov 4 ([VPN-6623](https://mozilla-hub.atlassian.net/browse/VPN-6623)).
* DENG-5883: Update the `mozilla_vpn_derived.exchange_rates_v1` ETL to include VPN wave 7 expansion country currencies
* [VPN-6623](https://mozilla-hub.atlassian.net/browse/VPN-6623): Wave 7 Mozilla VPN Expansion
[VPN-6623]: https://mozilla-hub.atlassian.net/browse/VPN-6623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-6623]: https://mozilla-hub.atlassian.net/browse/VPN-6623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> Update `mozilla_vpn_derived.exchange_rates_v1` to include VPN wave 7 expansion country currencies (DENG-5883)

bigquery_etl/cli/monitoring.py, sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/releases_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/org_mozilla_ios_focus_derived/baseline_clients_last_seen_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/metadata.yaml
This adds a temporary CLI `bqetl monitoring migrate` command which will translate default ETL checks to BigConfig configurations. This is not 100% accurate and doesn't support custom SQL (as BigConfig doesn't support it). Migrated checks should still be checked manually for correctness. But this is at least a starting point and should cover a large portion of default ETL checks
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-5548)
=> CLI command to automate some migration of ETL checks to Bigeye

sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/metadata.yaml
`ssl_ratios_v1` is actually a view (pointing to the public `ssl_ratios_v1` table), and Bigeye requires a partition column to be configured explicitly on views. This should fix the failing Airflow deployment task
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6161)
=> Specify partition column for Bigeye monitoring for ssl_ratios

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/vat_rates_v2/data.csv
Some VPN VAT rates which are outdated or incorrect need to be updated, some new VAT rates need to be added for countries that VPN will soon be expanding to ([VPN-6623](https://mozilla-hub.atlassian.net/browse/VPN-6623)), and I also decided to preemptively add all other VAT rates which Accounting has provided to us even if VPN isn't currently technically available in those countries just to help cover the bases for potential future market expansions.
* DENG-2707: Update VPN VAT rates
* [VPN-6623](https://mozilla-hub.atlassian.net/browse/VPN-6623): Wave 7 Mozilla VPN Expansion
[VPN-6623]: https://mozilla-hub.atlassian.net/browse/VPN-6623?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> Add and update VPN VAT rates (DENG-2707)

sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_daily_historical_pre202408/metadata.yaml
[Dry runs have been failing](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/40882/workflows/d34c3981-9994-4666-a0dd-03646fab9a77/jobs/468103) because [the deployed table](https://console.cloud.google.com/bigquery?ws=!1m5!1m4!4m3!1smoz-fx-data-shared-prod!2ssearch_derived!3smobile_search_clients_daily_historical_pre202408) has a required partition filter but metadata doesn't
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6162)
=> Add time partitioning spec to mobile_search_clients_daily_historical_pre202408

sql/moz-fx-data-shared-prod/monitoring/bigquery_usage/view.sql
The base table has one row per referenced table per job id which makes the looker explore hard to work with because the cost values are duplicated.  This adds a referenced table number to make it easier to dedupe without using custom measures
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6195)
=> Add reference table number to bigquery_usage view

sql/moz-fx-data-shared-prod/monitoring/bigquery_usage/view.sql
Fix for https://github.com/mozilla/bigquery-etl/pull/6439 which gives an error when trying to query that column: `Cannot query over table 'moz-fx-data-shared-prod.monitoring_derived.bigquery_usage_v2' without a filter over column(s) 'submission_date' that can be used for partition elimination`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6242)
=> Add submission_date partition to ref table number in bigquery_usage

sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v1/query.sql, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/funnel_ga_to_subscriptions_v2/query.sql
VPN is launching in 24 new countries today ([VPN-6623](https://mozilla-hub.atlassian.net/browse/VPN-6623)), so the `in_available_geos` ETL logic needs to be updated to reflect that.
Also, VPN previously launched in 16 countries in July 2023 ([VPN-4948](https://mozilla-hub.atlassian.net/browse/VPN-4948)), but the `in_available_geos` ETL logic wasn't updated at that time, so I'm taking this opportunity to update it for those 16 countries as well now.
* DENG-5484: Update VPN ETL `in_available_geos` logic for when VPN became available in various countries
* [VPN-4948](https://mozilla-hub.atlassian.net/browse/VPN-4948): Wave 6 Mozilla VPN Expansion
* [VPN-6623](https://mozilla-hub.atlassian.net/browse/VPN-6623): Wave 7 Mozilla VPN Expansion …
=> Update VPN ETL `in_available_geos` logic for when VPN became available in various countries (DENG-5484)

sql/moz-fx-data-shared-prod/static/country_codes_v1/data.csv
VPN is launching in 24 new countries today ([VPN-6623](https://mozilla-hub.atlassian.net/browse/VPN-6623)), so the `country_codes_v1.mozilla_vpn_available` column needs to be updated to reflect that.
* DENG-5882: Update the `country_codes_v1.mozilla_vpn_available` column for VPN wave 7 expansion countries
* [VPN-6623](https://mozilla-hub.atlassian.net/browse/VPN-6623): Wave 7 Mozilla VPN Expansion
[VPN-6623]: https://mozilla-hub.atlassian.net/browse/VPN-6623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[VPN-6623]: https://mozilla-hub.atlassian.net/browse/VPN-6623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> Update the `country_codes_v1.mozilla_vpn_available` column for VPN wave 7 expansion countries (DENG-5882)

sql/moz-fx-data-shared-prod/stripe_external/customer_discount_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/discount_v1/query.sql
In the process of handling Fivetran changing how Stripe discounts are synced (DENG-2116) it was discovered that Fivetran's Stripe connector used to have a bug where it synced subscription discounts as customer discounts.  This PR excludes those incorrect records in the SubPlat ETLs that copy Fivetran's raw Stripe records into the `stripe_external` dataset.
The downstream incremental ETLs `stripe_external.customers_changelog_v1` and `subscription_platform_derived.stripe_customers_revised_changelog_v1` shouldn't be rebuilt unless absolutely necessary, so I plan to remove the incorrect customer discounts with the following `UPDATE` statements:
```sql
UPDATE `moz-fx-data-shared-prod.stripe_external.customers_changelog_v1`
SET customer.discount = NULL
WHERE customer.discount.subscription_id IS …
```
=> Exclude Fivetran's incorrect Stripe customer discount records from SubPlat ETLs

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_funnel_v1/checks.sql
Removing this check as it is not something we can act upon and is quite noisy causing a lot of duplicate bugs to be created during the triage process resulting in confusion.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6268)
=> bug(1926038): remove check causing a lot of noise that is unactionable from app_store_funnel_v1

sql/moz-fx-data-shared-prod/stripe_external/nonprod_discount_v1/query.sql
Follow-up to #6443, as I forgot to update the non-prod ETLs as well.
* [DENG-2116](https://mozilla-hub.atlassian.net/browse/DENG-2116): Handle Fivetran changing how Stripe discounts are synced
[DENG-2116]: https://mozilla-hub.atlassian.net/browse/DENG-2116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6265)
=> Exclude Fivetran's incorrect Stripe customer discount records from non-prod SubPlat ETLs

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.metadata.yaml
This is our most expensive etl due to event size going up and there's a large difference between slot and on-demand cost (see DENG-6243).  This would have saved ~$80 on 2024-11-05.
DENG-6243 also proposes a way to make this more efficient but it requires a bit more testing so moving it to on-demand will work in the meantime
- DENG-6243
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6276)
=> Move event_monitoring_aggregates_v1 to run in on-demand billing

bigquery_etl/shredder/delete.py
shredder-all is taking a very long time to finish due to the increase in data over the last few months but I still want to test https://github.com/mozilla/telemetry-airflow/pull/2109 in prod, especially to see if it affects [writes to clustered tables](https://mozilla-hub.atlassian.net/browse/DENG-5962) at all.  Changing the state query to only look at end_date should safely make it not restart the current run
* DENG-6308
* DENG-5962
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6312)
=> [DENG-5962] Change shredder state to only use end_date

sql/moz-fx-data-shared-prod/telemetry/active_profiles/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/experiment_error_aggregates/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/experiments/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/experiments_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/main_summary/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/main_summary_v3/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/main_summary_v4/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/simpleprophet_forecasts/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/telemetry_anonymous_parquet/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/telemetry_downgrade_parquet/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/telemetry_heartbeat_parquet/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/telemetry_new_profile_parquet_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/telemetry_shield_study_parquet_v1/metadata.yaml
We're planning to delete some tables and associated views soon that have been marked as deprecated for some time now, all with a deletion date of May 2024.  See list here: https://docs.google.com/spreadsheets/d/1bdixeOSfss90jTxy0wGpcma7g1xs0UjKDrOt22axCuA/edit?usp=sharing
To prepare for this, first we want to mark these views as "deprecated" so anyone currently using them has warning before they get truly deleted soon.
This works spun out of the Ethyca work, since we have to classify data, we want to delete deprecated tables that we can so we don't have to spend time classifying their data unnecessarily.
* [DENG-4835](https://mozilla-hub.atlassian.net/browse/DENG-4835)
**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/blob/main/.github/reviewer_checklist.md …
=> DENG-4835 - Deprecate views associated with already deprecated tables

sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_revised_changelog_v1/backfill.yaml
To propagate the bug fix from #6458 to historical data.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6329)
=> Initiate backfill of `subscription_platform_derived.stripe_subscriptions_revised_changelog_v1`

sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_revised_changelog_v1/backfill.yaml
Complete backfill initiated in #6460 to propagate the bug fix from #6458 to historical data.
* https://github.com/mozilla/bigquery-etl/pull/6460
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6333)
=> Complete backfill of `subscription_platform_derived.stripe_subscriptions_revised_changelog_v1`

sql/moz-fx-data-shared-prod/subscription_platform_derived/logical_subscription_events_v1/backfill.yaml
To propagate the bug fix from #6458 to historical data.
This backfill shouldn't be initiated until the `stripe_subscriptions_revised_changelog_v1` backfill started in #6460 has been completed and the latest daily `stripe_subscriptions_revised_changelog_v1` ETL has been (re)run plus downstream ETLs to rebuild the intermediate subscription history tables.
* https://github.com/mozilla/bigquery-etl/pull/6460
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6330)
=> Initiate backfill of `subscription_platform_derived.logical_subscription_events_v1`

sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_logical_subscriptions_v1/backfill.yaml
To propagate the bug fix from #6458 to historical data.
This backfill shouldn't be initiated until the `stripe_subscriptions_revised_changelog_v1` backfill started in #6460 has been completed and the latest daily `stripe_subscriptions_revised_changelog_v1` ETL has been (re)run plus downstream ETLs to rebuild the intermediate subscription history tables.
* https://github.com/mozilla/bigquery-etl/pull/6460
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6331)
=> Initiate backfill of `subscription_platform_derived.daily_active_logical_subscriptions_v1`

sql/moz-fx-data-shared-prod/telemetry/experiment_error_aggregates_v1/view.sql, sql/moz-fx-data-shared-prod/telemetry/telemetry_new_profile_parquet/view.sql, sql/moz-fx-data-shared-prod/telemetry/telemetry_shield_study_parquet/view.sql
This PR is a follow up to [PR-6455](https://github.com/mozilla/bigquery-etl/pull/6455) , related to deleting a set of deprecated views and tables.  This PR deletes 3 views that were missed in the previous PR.
- telemetry.experiment_error_aggregates_v1
- telemetry.telemetry_new_profile_parquet
- telemetry.telemetry_shield_study_parquet
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6340)
=> DENG-4835 - delete 3 views missed in previous PR

sql/moz-fx-data-shared-prod/stripe_external/subscriptions_changelog_v1/metadata.yaml, sql/moz-fx-data-shared-prod/stripe_external/subscriptions_changelog_v1/query.sql
While [QAing a backfill of `stripe_subscriptions_revised_changelog_v1`](https://github.com/mozilla/bigquery-etl/pull/6464#issuecomment-2465659329) I discovered that because the `subscriptions_changelog_v1` ETL was only getting the records from the previous date rather than all available records, the `stripe_subscriptions_revised_changelog_v1` ETL ended up missing records that [got adjusted](https://github.com/mozilla/bigquery-etl/blob/d0e6d6c1ee146c931e5f530061e1b96e7a5439e7/sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_revised_changelog_v1/query.sql#L131-L141) across a date boundary and ended up in the prior day.
This PR tries to avoid that problem by changing the `subscriptions_changelog_v1` ETL to add all available incremental records in append-only …
=> Change `subscriptions_changelog_v1` ETL to add all available incremental records in append-only mode

sql/moz-fx-data-shared-prod/mozilla_org/desktop_conversion_events/view.sql
This PR updates the desktop_conversion_events view to point to the new V2 desktop conversions table instead of the old V1 table.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6362)
=> Update Desktop Conversion Events View to reference new V2 table

sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_logical_subscriptions_v1/backfill.yaml
Complete backfill initiated in #6462 to propagate the bug fix from #6458 to historical data.
* https://github.com/mozilla/bigquery-etl/pull/6462
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6354)
=> Complete backfill of `subscription_platform_derived.daily_active_logical_subscriptions_v1`

sql/moz-fx-data-shared-prod/subscription_platform_derived/logical_subscription_events_v1/backfill.yaml
Complete backfill initiated in #6461 to propagate the bug fix from #6458 to historical data.
* https://github.com/mozilla/bigquery-etl/pull/6461
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6355)
=> Complete backfill of `subscription_platform_derived.logical_subscription_events_v1`

sql/moz-fx-data-shared-prod/net_thunderbird_android_beta_derived/baseline_clients_last_seen_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/net_thunderbird_android_daily_derived/baseline_clients_last_seen_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/net_thunderbird_android_derived/baseline_clients_last_seen_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/thunderbird_desktop_derived/baseline_clients_last_seen_v1/bigconfig.yml
The[ Bigeye monitors ](https://workflow.telemetry.mozilla.org/dags/bqetl_artifact_deployment/grid?dag_run_id=manual__2024-11-13T05%3A04%3A56.400545%2B00%3A00&task_id=publish_bigeye_monitors&tab=logs)are failing with error `Duplicate saved_metric_id`
This PR should fix.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6367)
=> Fix bigeye checks to de-dup metric names

sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_history_v2/query.sql
In #6458 I tweaked the `stripe_subscriptions_history_v2` ETL to exclude customer changes that occur after the subscription has ended ([code change](https://github.com/mozilla/bigquery-etl/pull/6458/files#diff-10bf24b2789e1a1c6268b8a35001967b785ee431c5d271b824751341c0df63aeR62-R63)).  However, I neglected to update the logic for the `valid_to` column to compensate, which resulted in ended subscriptions with subsequent customer changes having their final `stripe_subscriptions_history_v2` record with `valid_to` set to the timestamp of the next customer change rather than the max timestamp value as intended.  This PR fixes that issue. …
=> Fix `stripe_subscriptions_history_v2.valid_to` getting cut short for ended subscriptions with subsequent customer changes

sql/moz-fx-data-shared-prod/net_thunderbird_android_beta_derived/baseline_clients_last_seen_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/net_thunderbird_android_daily_derived/baseline_clients_last_seen_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/net_thunderbird_android_derived/baseline_clients_last_seen_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/thunderbird_desktop_derived/baseline_clients_last_seen_v1/bigconfig.yml
Reverts mozilla/bigquery-etl#6485
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6384)
=> Revert "Fix bigeye checks to de-dup metric names"

sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_logical_subscriptions_v1/backfill.yaml
To propagate the bug fix from #6458 to historical data.
This backfill shouldn't be initiated until the `daily_active_logical_subscriptions_v1` backfill started in #6462 has been completed.
* https://github.com/mozilla/bigquery-etl/pull/6462
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6332)
=> Initiate backfill of `subscription_platform_derived.monthly_active_logical_subscriptions_v1`

sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_logical_subscriptions_v1/backfill.yaml
Complete backfill initiated in #6463 to propagate the bug fixes from #6458 and #6489 to historical data.
* https://github.com/mozilla/bigquery-etl/pull/6463
* https://github.com/mozilla/bigquery-etl/pull/6489
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6391)
=> Complete backfill of `subscription_platform_derived.monthly_active_logical_subscriptions_v1`

sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v2/query.sql
This PR is to prevent sending a google click ID / conversion name combination more than once to Google ads.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6398)
=> Updating Google Ads Desktop Conversions Event Logic

sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_logical_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/logical_subscription_events_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_logical_subscriptions_v1/backfill.yaml
To populate the new subscription discount fields which were added in #6474.
* https://github.com/mozilla/bigquery-etl/pull/6474
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6394)
=> Initiate backfill of logical subscription ETLs to populate new discount fields (DENG-974)

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_visits_v1/query.sql
The merge of [this PR](https://github.com/mozilla/bigquery-etl/pull/6445/files) broke some reporting where pocket clicks aren’t correctly counting. It appears to be due to null values in is_list_card (tested in BQ)
* DENG-6400
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6401)
=> Fix newtab reporting issues caused by the is_list_card filter

sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v2/metadata.yaml
This PR adds "depends on past" = True to ga_desktop_conversions_v2 so that it runs in order during backfills.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6402)
=> Desktop Conversion Events - Add depends on past = true

sql/moz-fx-data-shared-prod/static/key_tentpole_dates/data.csv
Fixes a date added in https://github.com/mozilla/bigquery-etl/pull/6491 that's causing it to fail to deploy https://workflow.telemetry.mozilla.org/dags/publish_bqetl_static/grid?dag_run_id=scheduled__2024-11-13T00%3A00%3A00%2B00%3A00&task_id=publish_static_mozdata&tab=logs
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6406)
=> Fix Christmas date in tentpole dates csv

sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_logical_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/logical_subscription_events_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_logical_subscriptions_v1/backfill.yaml
Complete backfill initiated in #6495 to populate the new subscription discount fields which were added in #6474.
* https://github.com/mozilla/bigquery-etl/pull/6474
* https://github.com/mozilla/bigquery-etl/pull/6495
* [DENG-974](https://mozilla-hub.atlassian.net/browse/DENG-974): Stripe subscriptions ETL v2
[DENG-974]: https://mozilla-hub.atlassian.net/browse/DENG-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6407)
=> Complete backfill of logical subscription ETLs to populate new discount fields (DENG-974)

bigquery_etl/backfill/shredder_mitigation.py, bigquery_etl/backfill/shredder_mitigation_checks_template.sql, tests/backfill/test_shredder_mitigation.py
Columns [city, country] are occasionally set to '??' when NULL, unfortunately not always.
In this PR, the shredder mitigation process & checks account for both cases to make a correct comparison.
* [DENG-877](https://mozilla-hub.atlassian.net/browse/DENG-877)
[DENG-877]: https://mozilla-hub.atlassian.net/browse/DENG-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6409)
=> Improve checks to account for null replacements

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/backfill.yaml
Initiate `newtab_clients_daily` backfill to fix the Pocket click error
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6421)
=> initiate backfill

sql/moz-fx-data-shared-prod/firefox_desktop_derived/pageload_1pct_v1/metadata.yaml
https://mozilla-hub.atlassian.net/browse/DSRE-1639?focusedCommentId=962362
Using the same value for 25mo as in https://github.com/mozilla/bigquery-etl/pull/6509
I don't actually know how this retention mechanism is implemented. Will this metadata update automatically get applied to the existing table?
* DSRE-1639
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6417)
=> Set retention to 25 months on firefox_desktop_derived.pageload_1pct_v1

sql/moz-fx-data-shared-prod/sumo_ga_derived/ga4_events_v1/query.sql
This PR changes the query for sumo_ga_derived.ga4_events_v1 to be an explicit select list instead of select *.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6429)
=> fix(SUMO GA4): Make select explicit because GA keeps adding columns

tests/checks/matches_pattern.jinja
The check divides by zero if there are no rows matching the where clause which I don't think is the right behaviour when we have the `min_row_count` check that should be used for that case.  This changes it so the the fail rate is 0 when there are no rows
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6427)
=> Support results with no rows in matches_pattern check

sql_generators/active_users_aggregates_v4/templates/metadata.yaml
This PR removes the scheduler for v4, as the tables must be moved to production via a backfill with shredder mitigation.
The scheduler for v4 will be added with the PR that completes this backfill.
This PR doesn't fix the forecasting failure, that is fixed in [PR-2126](https://github.com/mozilla/telemetry-airflow/pull/2126).
PR 2/2 for [Bug-1932176](https://bugzilla.mozilla.org/show_bug.cgi?id=1932176).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6439)
=> Remove scheduler for active_users_aggregates_v4

sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/query.sql, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/schema.yaml, sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/schema.yaml, sql/moz-fx-data-shared-prod/search_derived/search_dau_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_dau_aggregates_v1/schema.yaml, sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_revenue_levers_daily_v1/schema.yaml
This PR adds shredder_mitigation = True (which requires explicit group bys and all columns to have a column description) to the following tables: 
- search_derived.desktop_search_aggregates_by_userstate_v1
- search_derived.mobile_search_aggregates_v1
- search_derived.search_aggregates_v8
- search_derived.search_dau_aggregates_v1
- search_revenue_levers_daily_v1
* [DO-1887](https://mozilla-hub.atlassian.net/browse/DO-1887)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6440)
[DO-1887]: https://mozilla-hub.atlassian.net/browse/DO-1887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> chore(DO-1887): Add shredder mitigation to search aggregate tables

CODEOWNERS
This PR temporarily adds  active_users v3 to the codeowners until v4's backfill is completed via a separate PR.
Resolves [CI error](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/41579/workflows/faed17de-a448-44b0-a72c-ef4398d12f03/jobs/477106).
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6447)
=> Add active_users v3 to codeowners

bigquery_etl/cli/backfill.py, bigquery_etl/cli/query.py, bigquery_etl/cli/utils.py, bigquery_etl/deploy.py, bigquery_etl/metadata/publish_metadata.py, tests/cli/test_cli_backfill.py, tests/cli/test_cli_query.py, tests/test_deploy.py
This adds support for deploying queries that do not have a query file. We have more instances where tables get populated outside of bigquery-etl (e.g. through outerbounds), but still get deployed through bigquery-etl. The current workaround is to add an empty `query.py` file. This PR removes the requirement for that.
One such example where this happened is: https://github.com/mozilla/private-bigquery-etl/pull/487
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6438)
=> Support for deploying queries consisting of only metadata.yaml and schema.yaml

sql_generators/mobile_kpi_support_metrics/templates/engagement.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/engagement.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/retention.metadata.yaml
This PR adds shredder_mitigation = True for the following SQL generated tables: 
- fenix_derived.retention_v1
- firefox_ios_derived.retention_v1
- klar_ios_derived.retention_v1
- focus_android_derived.retention_v1
- focus_ios_derived.retention_v1
- klar_android_derived.retention_v1
- fenix_derived.engagement_v1
- firefox_ios_derived.engagement_v1
- focus_android_derived.engagement_v1
- focus_ios_derived.engagement_v1
- klar_ios_derived.engagement_v1
- klar_android_derived.engagement_v1
* [DO-1886](https://mozilla-hub.atlassian.net/browse/DO-1886)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6465)
[DO-1886]: …
=> chore(DO-1886): Add shredder_mitigation to mobile engagement and retention tables

bigquery_etl/query_scheduling/templates/airflow_dag.j2, tests/data/dags/python_script_test_dag, tests/data/dags/simple_test_dag, tests/data/dags/test_dag_duplicate_dependencies, tests/data/dags/test_dag_external_check_dependency, tests/data/dags/test_dag_external_dependency, tests/data/dags/test_dag_with_bigquery_table_sensors, tests/data/dags/test_dag_with_check_dependencies, tests/data/dags/test_dag_with_check_table_dependencies, tests/data/dags/test_dag_with_dependencies, tests/data/dags/test_dag_with_secrets
This removes the Bigeye Airflow dependencies from the generated Airflow DAGs. The Bigeye Airflow operators have been replaced by `bqetl` commands.
=> Remove Bigeye Airflow dependency

bigquery_etl/cli/monitoring.py
It looks like the Bigeye API changed slightly. When setting a partition column for a dataset that already has a partition column set, then Bigeye returns an error. This error message has changed to `Dataset already requires a partition filter` and will just be skipped during deploys.
=> Update logic for handling errors when Bigeye partitioning is already set

bigquery_etl/cli/monitoring.py
This condition made a wrong assumption that the `metric_type` must always be a not null value after parsing the config. This is incorrect, for example when `saved_metric_id` is referenced in the config the object created will have `metric_type` value of `None`.
=> feat: remove the condition resulting in exception if no metric_type value is defined

sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/query.py
The default client project when running in the pod is `moz-fx-data-airflow-gke-prod` instead of shared-prod so this doesn't find any tables
=> Set client project in shredder_targets

sql_generators/table_partition_expirations/templates/schema.yaml, sql_generators/table_partition_expirations/templates/table_partition_expirations.sql
Column to indicate if the expiration settings have changed for the current day.  To be used with the expiry alerts so it doesn't raise an error when there's a mismatch between the metadata and the actual table
=> Add expiration_changed column to table partition expirations

sql/moz-fx-data-shared-prod/mdn_yari_derived/mdn_popularities_v1/query.py
yari stopped populating the user_agent field so stop filtering for it.
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6586)
=> fix: update mdn_yari_derived/mdn_popularities_v1

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_engagement_v1/query.py
fix: remove trailing slash and add issued at to payload (ios engagement choice screen)
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6587)
=> fix: remove trailing slash and add issued at to payload (ios engagement choice screen)

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_engagement_v1/metadata.yaml
I double checked the secret values in GSM look fine.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6588)
=> chore: fix app_store_choice_screen_engagement_v1 secrets

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_engagement_v1/query.py
This is to ensure that we do not accidentally match any future choice screen related reports for newer ios versions
=> chore: update the report_title to use the full report name 

bqetl_project.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/issue/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/issue/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk/issue_type/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/issue_type/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk/project/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/project/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk/resolution/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/resolution/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk/status/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/status/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk_syndicate/dataset_metadata.yaml
This adds a configuration for syndicating the jira service desk data that is imported via Fivetran. At this moment the data is coming from a Jira sandbox project. Once it has been validated, we'll switch over to the production instance and put some workgroups in place to restrict access.
=> [DENG-6141] Add syndicate configuration and public views for Service Desk Jira data

sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/metadata.yaml, sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/query.sql, sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/schema.yaml
This PR aims to update the `apple_ads_external.ios_app_campaign_stats_v1` query to be incremental query instead of rebuilding the complete table on each run (overwriting).
This PR also:
- Updated the field descriptions coming from Apple to use the Apple provided definitions.
- Adds `bigconfig.yml` config file to this query and enabled monitoring.
=> feat(DENG-6549): Convert campaign stats to be incremental (ios)

dags.yaml
bqetl_glean_usage which is a dependency now runs longer than before. This will make search_dashboard start after glean_usage usually finishes.
=> Reschedule bqetl_search_dashboard DAG

bigquery_etl/shredder/config.py, sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/query.py, tests/shredder/test_config.py
Fix for https://github.com/mozilla/bigquery-etl/pull/6541
project shouldn't be in the DeleteSource because it doesn't match what's in the shredder config.py and also breaks the table and dataset properties of the object.  I also added a check to the constructor to validate the table value
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6620)
=> Remove project from DeleteSource table in shredder_targets

bigquery_etl/cli/query.py
There's an issue deploying the tables from https://github.com/mozilla/bigquery-etl/pull/6561 and https://github.com/mozilla/bigquery-etl/pull/6570 where the init query is running but the partitioning from the metadata isn't applied.  It seems like it's because the deploy is skipped due to dry run skip so the table is being created by the query.
Ignoring dry run skip should make it match the `query schema deploy` command in artifact deployment.  I tested this locally with 
```
bqetl query initialize sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/query.sql --skip-existing --project-id=moz-fx-data-shared-prod
```
and it deploys properly and then fails at the query because I can't query the ltv table. …
=> Ignore dry run skip when deploying tables during init

sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/bigconfig.yml
Dataset name doesn't have `_derived` so [publish_bigeye_monitors](https://workflow.telemetry.mozilla.org/dags/bqetl_artifact_deployment/grid?dag_run_id=manual__2024-12-02T17%3A50%3A58.875840%2B00%3A00&task_id=publish_bigeye_monitors&tab=logs) is failing with 
```
- invalidCohort:
entityType: CATALOG_ENTITY_TYPE_FIELD
schemaNamePattern: moz-fx-data-shared-prod.apple_ads_external_derived
tableNamePattern: ios_app_campaign_stats_v1
columnNamePattern: date
errorMessage: No matching schemas found.
...
```
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6734)
=> Fix dataset in ios_app_campaign_stats_v1 bigconfig.yml

dags.yaml
bqetl_mobile_feature_usage depends on bqetl_mobile_kpi_metrics which is scheduled to run at 12:00. Having the first one scheduled at 6:00 caused its sensors to idle for 6 hours. This reschedules it at 12:00.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6806)
=> Reschedule mobile_feature_usage DAG

bigquery_etl/glam/clients_daily_histogram_aggregates.py, bigquery_etl/glam/templates/clients_daily_histogram_aggregates_v1.sql
fixes: https://github.com/mozilla/glam/issues/3003
This PR adds `labeled_custom_distribution` and `labeled_timing_distribution` support to GLAM ETL.
These Metric types are "new" to Glean and have been requested by users
* DENG-6817
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6819)
=> feat(glam): support labeled distributions

sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6855)
=> feat: move all bigeye metric definition under the same definition as the same collection is used

sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6859)
=> fix: reduce lookback window for COUNT_DUPLICATES metric, it looks like with interval 1 we look at two submission_dates

dags.yaml, sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/checks.sql
Recently, we changed this table to load in increments with a 28 day delay, as opposed to full rebuilds each day (due to the retention project).  This is a fix to make sure the QA check runs with the same 28 day delay.
This PR also changes ownership of the DAG `bqetl_fivetran_google_ads` from Frank to Katie.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6878)
=> Update checks.sql for android_app_campaign_stats_v1 since this was changed to run incrementally

requirements.in, requirements.txt
Libraries to request and test data using Kevel API.
* [AD-295](https://mozilla-hub.atlassian.net/browse/AD-295)
[AD-295]: https://mozilla-hub.atlassian.net/browse/AD-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6881)
=> requirements for ads kevel api

sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/metadata.yaml, sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/checks.sql, sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/metadata.yaml
This PR removes the Bigeye checks for the table `android_app_campaign_stats_v1` & `ios_app_campaign_stats_v1` since they don't work out of the box because this table has a 28 day lag, so we need to write a new bigeye config YAML file to make this check work properly (otherwise it is failing the DAG in airflow). For now removing until we have the time to write this new YAML file - made a ticket so we don't lose track of adding it back - https://mozilla-hub.atlassian.net/browse/DENG-6886
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6885)
=> fix: Temporarily remove bigeye checks on android_app_campaign_stats_v1 & ios_app_campaign_stats_v1 until we can update with 28 day lookback

sql/moz-fx-data-shared-prod/jira_service_desk/field/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/field/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk/issue_field_history/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/issue_field_history/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk/request/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/request/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk/request_type/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/request_type/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk/status_category/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/status_category/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk_syndicate/dataset_metadata.yaml
There was a request to add syndication configurations for additional tables that are synced from Jira via Fivetran
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6896)
=> [DENG-6141] Syndicate additional Service Desk Jira tables

bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/templates/airflow_dag.j2, sql/moz-fx-data-shared-prod/telemetry_derived/crash_symbols_v1/metadata.yaml
This PR fixes two issues:
* When per-ETL configs for GKE container resources, node selectors, and startup timeouts were added in #4642 the DAG logic was accidentally added for data quality check tasks, not for ETL tasks as intended.
* Specifying GKE container resources as a dictionary apparently doesn't work anymore. This PR switches to the new way using `kubernetes.client.models.V1ResourceRequirements` objects, which I've verified works in mozilla/telemetry-airflow#2131.
* A similar change is being made for manually maintained DAGs in mozilla/telemetry-airflow#2133.
* https://github.com/mozilla/bigquery-etl/pull/4642
* https://github.com/mozilla/telemetry-airflow/pull/2133
**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/blob/main/.github/reviewer_checkli …
=> Fix GKE container resource, node selector, and startup timeout configs so they work properly

sql/bigconfig.yml, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
=> feat: Make sure row_creation_time field is specified for the metrics, comment out UUID as currently contains a bug

bigquery_etl/cli/monitoring.py
Currently, the logic does not consider that freshness or volume checks could come from a saved_metric. This change prevents freshness and volume metric definitions from being appended to the bigconfig in such cases.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6906)
=> fix: Do not add default freshness and volume checks to bigconfig if freshness or volume saved metric are already used

sql/moz-fx-data-shared-prod/ltv_state_values_derived/dataset_metadata.yaml
This PR is intended to create a new dataset in shared-prod where the data science team has write access.
In discussion with Leif, learned that they may be soon replacing these models with new models, so not worth the effort to productionalize their existing models, but rather move them to a safe place in shared-prod until the new ones are ready to replace the old ones.
We will be moving 3 tables from analysis into this dataset since they are used downstream in other production ETL for the Fenix, Firefox Desktop, and iOS LTV models.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6915)
=> Create new dataset ltv_state_values_derived

sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_daily_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_goals_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_landing_page_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_sessions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/firefox_whatsnew_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_downloads_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_events_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_hits_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_landing_page_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_metrics_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_page_metrics_v1/metadata.yaml
This PR undeprecates the old GA3 tables so that data science can still have permissions to query them and use them for analysis, even though they are no longer updated, for historical analysis.
=> Undeprecate these as data science would still like to use the old data

bigquery_etl/glam/templates/histogram_bucket_counts_v1.sql, bigquery_etl/glam/templates/probe_counts_v1.sql, bigquery_etl/glam/utils.py
This PR adds support to `labeled_distributions` to the GLAM ETL mechanism that fetches metric metadata.
* DENG-6817
=> fix(glam): properly fetch labeled_distribution metadata

sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v2/query.sql
This PR updates the Fenix LTV ETL to use the data provided by data science from a production table instead of an analysis table.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6927)
=> Update fenix LTV to use new location

sql/moz-fx-data-shared-prod/google_ads_derived/daily_campaign_stats_v1/checks.sql, sql/moz-fx-data-shared-prod/google_ads_derived/daily_campaign_stats_v1/metadata.yaml, sql/moz-fx-data-shared-prod/google_ads_derived/daily_campaign_stats_v1/query.sql, sql/moz-fx-data-shared-prod/google_ads_derived/daily_campaign_stats_v1/schema.yaml
This table is a full delete and rebuild each day from Google Ads.  When the connection breaks, the DAG doesn't throw an error, it still marks the run as successful.  This logic change should ensure that if no data is loaded for the current submission date, an error will be thrown in the future.
=> feat: Add minimum row count check to google ads table google_ads_derived.daily_campaign_stats_v1

sql/bigconfig.yml
* DENG-XXXX
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6957)
=> fix: update percentage thresholds from 100 to 1 (1 == 100 percent in the tool) in bigconfig

sql/moz-fx-data-shared-prod/monitoring/bigquery_usage/view.sql
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6982)
=> fix: remove labels from select sattement in bigquery usage (selected twice)

sql/moz-fx-data-shared-prod/mozilla_org/desktop_conversion_events/metadata.yaml
This PR adds permissions for the Census tool to access the data in this view `moz-fx-data-shared-prod.mozilla_org.desktop_conversion_events`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6970)
=> feat: Add Census permissions to desktop_conversion_events

sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/metadata.yaml, sql/moz-fx-data-shared-prod/cloudflare_derived/browser_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/cloudflare_derived/os_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_daily_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_daily_summary_v2/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_landing_page_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/blogs_landing_page_summary_v2/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_landing_page_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_landing_page_metrics_v2/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_metrics_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_metrics_summary_v2/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_page_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_page_metrics_v2/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/site_metrics_summary_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_vpn_derived/site_metrics_summary_v2/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_dau_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_engagement_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_installer_aggregates_v1/metadata.yaml, sql_generators/use_counters/templates/metadata.yaml
This PR adds labels to the following aggregate tables:
**Aggregate Table Only (since these aren't impacted by shredder)**
* moz-fx-data-shared-prod.cloudflare_derived.browser_usage_v1
* moz-fx-data-shared-prod.cloudflare_derived.device_usage_v1
* moz-fx-data-shared-prod.cloudflare_derived.os_usage_v1
* moz-fx-data-shared-prod.mozilla_org_derived.blogs_daily_summary_v1
* moz-fx-data-shared-prod.mozilla_org_derived.blogs_daily_summary_v2
* moz-fx-data-shared-prod.mozilla_org_derived.blogs_landing_page_summary_v1
* moz-fx-data-shared-prod.mozilla_org_derived.blogs_landing_page_summary_v2
* moz-fx-data-shared-prod.mozilla_org_derived.www_site_landing_page_metrics_v1
* moz-fx-data-shared-prod.mozilla_org_derived.www_site_landing_page_metrics_v2
* …
=> Add metadata labels to aggregate tables

bigquery_etl/metadata/validate_metadata.py
Related to the data retention project - This PR adds a function that 
1. will fail the CI if a table has `table_type:aggregate` in the `metadata.yaml` file but has the `expiration_days` set 
2. will fail CI if a table labelled as  `table_type: client_level` and has no` expiration_days` set
This would ensure that retention policies are not inadvertently set on aggregate tables.
Additionally, the table_type label would be added alongside the existing shredder_mitigation=true label, which is used to prevent accidental backfills of these tables.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6987)
=> Add retention validate func

bigquery_etl/query_scheduling/templates/airflow_dag.j2, bigquery_etl/query_scheduling/templates/public_data_json_airflow_dag.j2, tests/data/dags/test_dag_duplicate_dependencies, tests/data/dags/test_dag_with_check_dependencies, tests/data/dags/test_dag_with_dependencies
Default `poke_interval` is 60s. [Airflow docs](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/sensors/base/index.html#airflow.sensors.base.BaseSensorOperator) recommend it to be more than that in `reschedule` mode to decrease load on scheduler. In our case worker pods take up 30s to start so it seems wasteful to restart them every 60s. We also have [some issues with git-sync init on worker pods](https://mozilla-hub.atlassian.net/browse/DENG-6838) potentially related to too many pods running at the same time which this bump might help with.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7002)
=> Wait 5 minutes between task sensor retries

sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_beta_aggregates_v1/script.sql, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_nightly_aggregates_v1/script.sql, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_desktop_release_aggregates_v1/script.sql, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_beta_aggregates_v1/script.sql, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_nightly_aggregates_v1/script.sql, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_release_aggregates_v1/script.sql, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_beta_aggregates_v1/script.sql, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_nightly_aggregates_v1/script.sql, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_release_aggregates_v1/script.sql
This is the first step to migrate GLAM ETL to GCP V2.
This PR loads GLAM ETL data to GCP V2, so GLAM (the app) can fetch up-to-date data, since it's already on GCP V2.
I'll file another PR tomorrow with more changes that will make GLAM ETL execute entirely on GCP V2.
* DSRE-1783
=> chore(glam): Load aggregates to GCP V2

sql/moz-fx-data-shared-prod/jira_service_desk/issue_multiselect_history/metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk/issue_multiselect_history/view.sql, sql/moz-fx-data-shared-prod/jira_service_desk_syndicate/dataset_metadata.yaml
This adds syndication configuration for the Jira issue multiselect history table synced via Fivetran
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7006)
=> [DENG-6141] Add Jira issue multiselect history table

sql/moz-fx-data-shared-prod/fenix_derived/funnel_retention_week_4_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_position_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_cohort_daily_retention_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_funnel_installs_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_exact_mau28_by_client_count_dimensions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_exact_mau28_by_client_count_dimensions_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_exact_mau28_by_dimensions_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_exact_mau28_by_dimensions_v2/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_nondesktop_exact_mau28_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_desktop_compressed_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_desktop_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_fxa_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_new_profiles_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_nondesktop_compressed_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_nondesktop_v2/metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/engagement.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/retention.metadata.yaml
This PR adds aggregate table labels to the following tables:
- moz-fx-data-shared-prod.fenix_derived.funnel_retention_week_4_v1
- moz-fx-data-shared-prod.search_derived.desktop_search_aggregates_by_userstate_v1
- moz-fx-data-shared-prod.search_derived.desktop_search_aggregates_for_searchreport_v1
- moz-fx-data-shared-prod.search_derived.mobile_search_aggregates_for_searchreport_v1
- moz-fx-data-shared-prod.telemetry_derived.desktop_funnel_installs_v1
- moz-fx-data-shared-prod.telemetry_derived.firefox_nondesktop_exact_mau28_v1
- moz-fx-data-shared-prod.telemetry_derived.desktop_cohort_daily_retention_v1
- moz-fx-data-shared-prod.telemetry_derived.firefox_desktop_usage_v1
- moz-fx-data-shared-prod.telemetry_derived.smoot_usage_desktop_v2
- …
=> Add aggregate table labels to aggregate tables

dags.yaml, sql/moz-fx-data-shared-prod/ads/fakespot_daily_events_rollup/metadata.yaml, sql/moz-fx-data-shared-prod/ads/nt_visits_to_sessions_conversion_factors_daily/metadata.yaml, sql/moz-fx-data-shared-prod/ads/ppa_measurements/metadata.yaml, sql/moz-fx-data-shared-prod/ads/ppa_measurements_limited/metadata.yaml, sql/moz-fx-data-shared-prod/ads_derived/nt_visits_to_sessions_conversion_factors_daily_v1/metadata.yaml, sql/moz-fx-data-shared-prod/reference/macroeconomic_indices/metadata.yaml, sql/moz-fx-data-shared-prod/reference_derived/macroeconomic_indices_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/acer_cohort_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_by_userstate_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/desktop_search_aggregates_for_searchreport_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_for_searchreport_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/mobile_search_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_last_seen_v1/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_aggregates_v8/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/metadata.yaml, sql/moz-fx-data-shared-prod/search_derived/search_clients_last_seen_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/metadata.yaml
Adds @chelseybeck @lucia-vargas-a and @sergiosonline to table owners and airflow notification emails for Ads tables, and also adds @alekhyamoz to table owners for search tables
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7004)
=> Update table owners for ads and search tables

sql/bigconfig.yml, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
This reverts commit 3e5f14493965eda1aea5d4b8da1e363448f2cc45.
This config change seems to cause the Bigeye monitor deploy to hang
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7013)
=> Revert "feat: add row_creation_times to sql/bigconfig.yml (#6630)"

sql/moz-fx-data-shared-prod/firefox_ios_derived/funnel_retention_week_4_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_new_profiles_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_retention_aggregates_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_fxa_compressed_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/smoot_usage_new_profiles_compressed_v2/metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.metadata.yaml
This PR adds table_type: aggregate labels to the following tables: 
- moz-fx-data-shared-prod.firefox_ios_derived.funnel_retention_week_4_v1
- moz-fx-data-shared-prod.telemetry_derived.desktop_new_profiles_aggregates_v1
- moz-fx-data-shared-prod.telemetry_derived.desktop_retention_aggregates_v2
- moz-fx-data-shared-prod.telemetry_derived.smoot_usage_fxa_compressed_v2
- moz-fx-data-shared-prod.telemetry_derived.smoot_usage_new_profiles_compressed_v2
It also adds the aggregate label & shredder mitigation to the SQL generator for mobile new_profiles_v1:
- sql_generators/mobile_kpi_support_metrics/templates/new_profiles.metadata.yaml
┆Issue is synchronized with this …
=> Add retention mitigation to aggregate tables

sql/bigconfig.yml, sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/bigconfig.yml
This sets the schedule for metrics to "No" that will be triggered via Airflow. This way we don't run checks twice. 
Volume and freshness checks are still run independently.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7014)
=> Un-schedule Bigeye metrics that get triggered via Airflow

dags.yaml, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_release_aggregates_v1/metadata.yaml
The release aggregates table is being recalculated nightly, but release channel builds happen infrequently enough that we can reduce this cadence to weekly without meaningful loss in usability.
This PR extracts `bqetl_refresh_aggregates`.`release` into `bqetl_glam_refresh_aggregates_fog_release` so it can follow `glam_fog_release`'s schedule. (https://github.com/mozilla/telemetry-airflow/pull/2135)
* DENG-6752
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6992)
=> feat(glam): extract refresh_aggregates_fog_release

dags.yaml, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_desktop_dau_by_device_type/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_fqueze_cpu_info/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_mau_per_os/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_win_instll_by_instll_typ/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_win_uninstll/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_desktop_dau_by_device_type_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_desktop_dau_by_device_type_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_desktop_dau_by_device_type_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_fqueze_cpu_info_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_fqueze_cpu_info_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_mau_per_os_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_mau_per_os_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_mau_per_os_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_win_instll_by_instll_typ_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_win_instll_by_instll_typ_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_win_instll_by_instll_typ_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_win_uninstll_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_win_uninstll_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_win_uninstll_v1/schema.yaml
This PR creates the following new tables:
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_desktop_dau_by_device_type_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_win_instll_by_instll_typ_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_win_uninstll_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_fqueze_cpu_info_v1 (static table, they used to keep in analysis, copied here to be safer)
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_mau_per_os_v1
It also creates the new DAG: 
- bqetl_fx_health_ind_dashboard - starting 2024-12-15, with a schedule of  `0 16 * * *`
**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/blob/main/.github/revie …
=> Create aggregate tables for Firefox Health Indicator dashboard

sql/bigconfig.yml, sql/moz-fx-data-shared-prod/telemetry_derived/ssl_ratios_v1/bigconfig.yml
This seems to break Bigconfig deploys. The config is valid but the deploy doesn't support 
```
schedule_frequency:
interval_type: MINUTES
interval_value: 0
```
I will open an issue with Bigeye
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7030)
=> Revert "Un-schedule Bigeye metrics that get triggered via Airflow"

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_clients_daily_by_os/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_v1/schema.yaml
This PR creates the new table:
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_clients_daily_by_os_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7034)
=> Create clients daily aggregate for Firefox Health Indicators dashboard

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_clients_daily_by_os_version/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_version_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_version_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_version_v1/schema.yaml
This PR creates the following new aggregate table: 
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_clients_daily_by_os_version_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7043)
=> Create new aggregate table for Firefox Health Indicator dashboard

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_clients_daily_by_country/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_country_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_country_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_country_v1/schema.yaml
This PR creates the new aggregate table called: 
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_clients_daily_by_country_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7046)
=> Create new aggregate table for Firefox Health Indicators dashboard

sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_beta_aggregates_v1/metadata.yaml, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_nightly_aggregates_v1/metadata.yaml, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fenix_release_aggregates_v1/metadata.yaml, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_beta_aggregates_v1/metadata.yaml, sql/moz-fx-data-glam-prod-fca7/glam_etl/glam_fog_nightly_aggregates_v1/metadata.yaml
This PR fixes the upstream dependency for `bqetl_glam_refresh_aggregates`.`glam_fog_nightly_aggregates` after https://github.com/mozilla/telemetry-airflow/pull/2135 removed the `export` task, which used to be the upstream.
* DENG-6752
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7045)
=> fix(glam): update beta and nightly refresh aggregates upstream task_id

sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_country_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_country_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_version_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_clients_daily_by_os_version_v1/schema.yaml
This PR adds 5 new columns to 3 tables: 
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_clients_daily_by_country_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_clients_daily_by_os_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_clients_daily_by_os_version_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7047)
=> Add additional columns to new fx_health_indicator aggregate tables

requirements.in, requirements.txt
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7066)
=> feat: bump up version of bigeye-sdk to 0.4.94

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_vid_plybck_by_country/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_vid_plybck_by_os/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_vid_plybck_by_os_version/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_country_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_country_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_country_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_os_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_os_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_os_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_os_version_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_os_version_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_vid_plybck_by_os_version_v1/schema.yaml
This PR creates 3 new aggregate tables:
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_vid_plybck_by_country_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_vid_plybck_by_os_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_vid_plybck_by_os_version_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7074)
=> Create aggregate tables for Firefox Health Indicators dashboard

sql/moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_28_days_later_v3/metadata.yaml
* DENG-6985
* DSRE-XXXX
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7079)
=> add depends on past = true to metadata

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_searches_by_provider/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v1/schema.yaml
This PR creates the following new table: 
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_searches_by_provider_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7078)
=> Create new aggregate table fx_health_ind_searches_by_provider_v1

sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/schema.yaml
This PR adds a new column to the following table:
- moz-fx-data-shared-prod.telemetry_derived.event_aggregates_v1
It also removes the old managed backfill YAML since we will need to redo the backfill again with the new column.
* [DENG-6892](https://mozilla-hub.atlassian.net/browse/DENG-6892)
[DENG-6892]: https://mozilla-hub.atlassian.net/browse/DENG-6892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7089)
=> Add new column counting # of events to table

sql/moz-fx-data-shared-prod/jira_service_desk_derived/dataset_metadata.yaml
The `dataset_metadata.yaml` is missing for the `jira_service_desk_derived` dataset. This should unblock artifact deploys.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7090)
=> Add missing dataset_metadata.yaml for jira_service_desk_derived

sql/moz-fx-data-shared-prod/ads_derived/dataset_metadata.yaml
This PR adds write access to `ads_derived` dataset to the `ads/writers` workgroup subgroup as added [here](https://github.com/mozilla-it/global-platform-admin/blob/1832540ce4b6b86804322db30bf6b65679667dff/google-workspace-management/tf/workgroups/ads.yaml#L90)
* DSRE-1852
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7096)
=> adding write access to ads derived dataset

sql/moz-fx-data-shared-prod/ads_derived/nt_visits_to_sessions_conversion_factors_daily_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/adm_engagements_daily_v1/metadata.yaml
Adds shredder mitigation and `table_type: aggregate` to 2 tables per https://docs.google.com/spreadsheets/d/1L78FtSaNoVowGhNU_-OJruoNFZalqBeo/edit?gid=1929010979#gid=1929010979
* DENG-7092
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7094)
=> DENG-7092 Add shredder mitigation and table type to certain ads tables

sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/schema.yaml
This PR adds more columns to the moz-fx-data-shared-prod.telemetry_derived.event_aggregates_v1, since these are needed for use in the Firefox Health Indicator dashboard.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7098)
=> Add more columns to event aggregate table

dags.yaml, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/broken_site_root_domain_daily_aggregates/view.sql, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/broken_site_root_domain_weekly_trend/view.sql, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report_derived/broken_site_root_domain_daily_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report_derived/broken_site_root_domain_daily_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report_derived/broken_site_root_domain_daily_aggregates_v1/schema.yaml, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report_derived/broken_site_root_domain_weekly_trend_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report_derived/broken_site_root_domain_weekly_trend_v1/query.sql, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report_derived/broken_site_root_domain_weekly_trend_v1/schema.yaml, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report_derived/dataset_metadata.yaml
Aggregations and Weekly trends for broken site reporting
- broken_site_root_domain_daily_aggregates: Has the daily aggregations by root domain
- broken_site_root_domain_weekly_trend: Computes the weekly trends
* [DENG-6887](https://mozilla-hub.atlassian.net/browse/DENG-6887)
[DENG-6887]: https://mozilla-hub.atlassian.net/browse/DENG-6887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7077)
=> DENG-6887-broken site reports-aggregations and weekly trends

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_webcompat/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_webcompat_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_webcompat_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_webcompat_v1/schema.yaml
This PR creates the new table:
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_webcompat_v1
Note: This one can't fit into the existing new desktop `events_aggregate_v1` table because it counts unique users by day and country, so it's a different grain; that's why a new table is needed
=> Create new webcompat_v1 aggregate table

sql/moz-fx-data-shared-prod/monitoring/bigeye_usage/view.sql
This is to enable usage of this field in a Looker dashboard.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7102)
=> feat: add a new field task_duration_seconds to bigeye_config

sql/moz-fx-data-shared-prod/telemetry_derived/addon_aggregates_v2/metadata.yaml
This was set to true by a mistake.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7106)
=> fix: remove shredder_mitigation lavel from telemetry_derived/addon_aggregates_v2 as this is client_level table

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_bookmarks_by_country/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_bookmarks_by_os/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_bookmarks_by_os_version/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_country_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_country_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_country_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_version_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_version_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_version_v1/schema.yaml
This PR creates the 3 new tables:
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_bookmarks_by_os_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_bookmarks_by_os_version_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_bookmarks_by_country_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7107)
=> Create fx_health_ind_bookmarks_by_os_v1, by_os_version, and by country

bqetl_project.yaml, sql_generators/glean_usage/common.py, sql_generators/glean_usage/templates/baseline_clients_daily_v1.metadata.yaml, sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.metadata.yaml, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.metadata.yaml, sql_generators/glean_usage/templates/metrics_clients_daily.metadata.yaml, sql_generators/glean_usage/templates/metrics_clients_last_seen.metadata.yaml
This is preventing Bigconfig from generated for baseline and metrics tables for some of the apps. This could be because some of them are failing due to not actively populating those pings. For example, because it was added accidentally. Or is no longer used, or the app itself has retired.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7088)
=> feat: exclude some apps from including bigconfig in glean_usage generator

sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/event_aggregates_v1/schema.yaml
This PR adds 2 new columns to the table:
- moz-fx-data-shared-prod.telemetry_derived.event_aggregates_v1
* [DENG-6892](https://mozilla-hub.atlassian.net/browse/DENG-6892)
[DENG-6892]: https://mozilla-hub.atlassian.net/browse/DENG-6892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7112)
=> Add 2 new columns to event_aggregates_v1

sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_installs_v1/metadata.yaml, sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_nondesktop_day_2_7_activation_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/segmented_dau_28_day_rolling_v1/metadata.yaml
This PR adds shredder mitigation & an aggregate table label to: 
- moz-fx-data-shared-prod.telemetry_derived.segmented_dau_28_day_rolling_v1
- moz-fx-data-shared-prod.firefox_desktop_derived.desktop_installs_v1
- moz-fx-data-shared-prod.google_ads_derived.android_app_campaign_stats_v1
- moz-fx-data-shared-prod.telemetry_derived.firefox_nondesktop_day_2_7_activation_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7117)
=> Add shredder mitigation

sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_events_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_hits_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/www_site_landing_page_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/releases_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_funnel_activation_day_6_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_funnel_new_profiles_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/devtools_panel_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_daily_active_population_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_desktop_exact_mau28_by_dimensions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/firefox_nondesktop_exact_mau28_by_client_count_dimensions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/latest_versions_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/mobile_usage_v1/metadata.yaml, sql_generators/experiment_monitoring/templates/experiment_enrollment_aggregates_v1/metadata.yaml, sql_generators/experiment_monitoring/templates/experiment_search_aggregates_v1/metadata.yaml, sql_generators/experiment_monitoring/templates/experiments_daily_active_clients_v1/metadata.yaml
https://docs.google.com/spreadsheets/d/1L78FtSaNoVowGhNU_-OJruoNFZalqBeo/edit?gid=1929010979#gid=1929010979
Adding the labels and shredder mitigation to tables owned by ascholtz
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7118)
=> Add labels and shredder-mitigation config to datasets owned by ascholtz

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_page_reloads/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_page_reloads_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_page_reloads_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_page_reloads_v1/schema.yaml
This PR creates a new aggregate table for the Firefox Health Indicator dashboard
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_page_reloads_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7119)
=> Create new aggregate table fx_health_ind_page_reloads_v1

sql/bigconfig.yml
This removes schedules for Bigeye metrics that are already being triggered via Airflow runs. This should save some money as we no longer run them twice.
Previously, there was a bug which caused the Bigeye deploy to stall, however Bigeye fixed this on their side: https://portal.usepylon.com/bigeye?durationMs=31536000000&tab=issues&conversationID=c1ba0bd5-8929-4faf-bf28-8a530625a584 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7140)
=> Remove default schedule for Bigeye metrics (except freshness and volume)

sql/moz-fx-data-shared-prod/search/mobile_search_clients_engines_sources_daily/view.sql
This PR fixes the `normalized_app_name_os` column in the `mobile_search_clients_engines_sources_daily` view definition by getting `normalized_app_name_os` instead of `normalized_app_name`. Currently, both `normalized_app_name` and `normalized_app_name_os` columns in the view are the same.
Preventing `search_count` results for experiment analysis in iOS experiments (example: https://experimenter.services.mozilla.com/nimbus/ios-optimize-onboarding-card-order/results) because none of the records in this view have `normalized_app_name_os` populated with `"Firefox iOS"` as expected. …
=> fix: normalized_app_name_os definition in mobile_search_clients_engines_sources_daily

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_antivirus/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_antivirus_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_antivirus_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_antivirus_v1/schema.yaml
This PR creates the new aggregate table for the Firefox Health Indicator dashboard: 
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_antivirus_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7143)
=> Create new antivirus aggregate table for Firefox Health Indicator dashboard

.pre-commit-config.yaml
Follow-up to https://github.com/mozilla/bigquery-etl/pull/6751/files#diff-de469cc9cf8992ffaec661b4e087cfded3ec6da722072ec1fdf11f61690fd1b8R49
We could have a test to verify these dependencies are in sync.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7149)
=> Update pre-commit-config dependencies to match requirements.txt

sql/moz-fx-data-shared-prod/pocket_derived/pocket_usage_v1/query.sql
Fix for pocket_usage_v1 table. Removing the order by clause
* DENG-7061
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7151)
=> pocket_usage table fix - removing the order by clause

sql/moz-fx-data-shared-prod/telemetry/user_cancelled_install_share/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/user_cancelled_install_share_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/user_cancelled_install_share_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/user_cancelled_install_share_v1/schema.yaml
This PR creates the new aggregate table: 
- moz-fx-data-shared-prod.telemetry_derived.user_cancelled_install_share_v1 
* DENG-6883 (https://mozilla-hub.atlassian.net/browse/DENG-6883)
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7157)
=> DENG-6883 - build share of user cancelled installs aggregate table

sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_channel_aggregates/view.sql, sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_country_aggregates/view.sql, sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_os_ver_aggregates/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_channel_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_channel_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_channel_aggregates_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_country_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_country_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_country_aggregates_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_os_ver_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_os_ver_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_os_ver_aggregates_v1/schema.yaml
This PR creates the following new aggregate tables: 
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_country_aggregates_v1
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_channel_aggregates_v1
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_os_ver_aggregates_v1
* [DENG-6883](https://mozilla-hub.atlassian.net/browse/DENG-6883)
[DENG-6883]: https://mozilla-hub.atlassian.net/browse/DENG-6883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7159)
=> DENG-6883: Create new aggregate table for uninstalls by country

bigquery_etl/util/common.py, tests/util/test_common.py
`bigconfig.yml` is causing a non-fatal error in dag generation ([example](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/43407/workflows/1f33549d-cc8b-4009-89cb-4a64329969f6/jobs/501846?invite=true#step-108-6354_11)) because it's being returned by the `project_dirs` function
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7160)
=> Exclude files from bigquery_etl project_dirs listing

sql/moz-fx-data-shared-prod/telemetry/install_vs_uninstall_ratio/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/install_vs_uninstall_ratio_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/install_vs_uninstall_ratio_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/install_vs_uninstall_ratio_v1/schema.yaml
This PR creates the following new aggregate table: 
- moz-fx-data-shared-prod.telemetry_derived.install_vs_uninstall_ratio_v1
* [DENG-6883](https://mozilla-hub.atlassian.net/browse/DENG-6883)
[DENG-6883]: https://mozilla-hub.atlassian.net/browse/DENG-6883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7161)
=> DENG-6884 Create new aggregate table install_vs_uninstall_ratio

sql/moz-fx-data-shared-prod/monitoring/event_counts_glean/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring/event_counts_glean/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/event_counts_glean_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/event_counts_glean_v1/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/event_counts_glean_v1/schema.yaml, tests/sql/moz-fx-data-shared-prod/monitoring_derived/event_counts_glean_v1/test_aggregation/expect.yaml, tests/sql/moz-fx-data-shared-prod/monitoring_derived/event_counts_glean_v1/test_aggregation/moz-fx-data-shared-prod.monitoring_derived.event_monitoring_aggregates_v1.yaml, tests/sql/moz-fx-data-shared-prod/monitoring_derived/event_counts_glean_v1/test_aggregation/query_params.yaml
Monitoring table with event counts for glean apps.  Based on `monitoring_derived.event_monitoring_aggregates_v1` because it's a lot cheaper and simpler than using events stream.
* DENG-7019
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7163)
=> [DENG-7019] Create glean event count table

sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/bigconfig.yml, sql/moz-fx-data-shared-prod/google_ads_derived/android_app_campaign_stats_v1/bigconfig.yml
These `bigconfig.yml` have been showing up in every `sql.diff` because generate-sql in CI runs `bqetl monitoring update` but `main-generate-sql-and-dags` doesn't so the checked in files don't match the [generated sql](https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/bigconfig.yml).
Might make sense to validate this as part of CI but I'm not sure how the files are made/used.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7166)
=> Update campaign stats bigconfigs with `bqetl monitoring update sql`

sql/moz-fx-data-shared-prod/telemetry/experiment_cumulative_ad_clicks/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/experiment_cumulative_search_count/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/experiment_cumulative_search_with_ads_count/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_cumulative_ad_clicks_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_cumulative_search_count_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_cumulative_search_with_ads_count_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_live_v1/metadata.yaml, sql_generators/experiment_monitoring/templates/experiment_search_aggregates_v1/metadata.yaml, sql_generators/experiment_monitoring/templates/experiment_search_events_live_v1/metadata.yaml
Merge after https://github.com/mozilla/lookml-generator/pull/1122 has been merged
Experiment search monitoring is no longer needed and looked at by stakeholders, so we can deprecate all the related datasets to delete them eventually.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6993)
=> Remove experiment search monitoring

sql/moz-fx-data-shared-prod/mozilla_org/desktop_conversion_events/view.sql
This PR updates the view: `moz-fx-data-shared-prod.mozilla_org.desktop_conversion_events`
It: 
* removes the activity_date column (the unix seconds version of the timestamp) 
* changes the activity_date_timestamp column to use a different formatting that works better in Google Ads
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7169)
=> Change timestamp format in desktop_conversion_events view

sql/moz-fx-data-shared-prod/telemetry/clients_daily/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/clients_daily_joined/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/clients_daily_v6/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml
[Slack discussion](https://mozilla.slack.com/archives/C4D5ZA91B/p1736357134311699)
Caused by https://github.com/mozilla/bigquery-etl/issues/5830. I've opted to fix this by removing telescope's access to this data, since [it isn't using it](https://github.com/search?q=repo%3Amozilla-services%2Ftelescope%20moz-fx-data-shared-prod&type=code). That should ensure that the default `default_table_workgroup_access` gets applied to all these tables.
I'm a bit surprised that this started to be an issue recently, since https://sql.telemetry.mozilla.org/queries/101394/source#249849 was working until this year. I found that 465dcee33fc is what actually triggered the issue, since before that the user-facing telemetry dataset didn't have any deprecated tables. We've gone back and forth about whether we …
=> Remove unused telescope access

sql/moz-fx-data-shared-prod/telemetry/install_vs_uninstall_by_os/view.sql, sql/moz-fx-data-shared-prod/telemetry/uninstalls_to_dau_ratio_by_country/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/install_vs_uninstall_by_os_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/install_vs_uninstall_by_os_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/install_vs_uninstall_by_os_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_to_dau_ratio_by_country_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_to_dau_ratio_by_country_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_to_dau_ratio_by_country_v1/schema.yaml
This PR creates the following 2 aggregate tables:
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_to_dau_ratio_by_country_v1
- moz-fx-data-shared-prod.telemetry_derived.install_vs_uninstall_by_os_v1
* [DENG-6883](https://mozilla-hub.atlassian.net/browse/DENG-6883)
[DENG-6883]: https://mozilla-hub.atlassian.net/browse/DENG-6883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is …
=> DENG-6683 & DENG-6884 - Create aggregate tables for installs/uninstalls

sql/moz-fx-data-shared-prod/monitoring_derived/event_counts_glean_v1/query.sql, sql/mozfun/norm/app_channel/README.md, sql/mozfun/norm/app_channel/metadata.yaml, sql/mozfun/norm/app_channel/udf.sql
The dropdown menu in looker has some 😳 words because `event_monitoring_aggregates_v1` uses `client_info.app_channel` instead on `normalized_channel`.
udf based on https://github.com/mozilla/gcp-ingestion/blob/fb7e9ed9e891e3e2320d85e05d7c1a1aedb57780/ingestion-beam/src/main/java/com/mozilla/telemetry/transforms/NormalizeAttributes.java#L34
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7182)
=> Create normalize app channel function

sql_generators/experiment_monitoring/templates/experiment_crash_rates_live/view.sql
The number of crashes per enrolled user is not super useful and is slowing down the `experiment_crash_rates_live` view quite significantly. Sticking to total crash counts per experiment for now, so the logic of the view can be simplified.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7184)
=> Simplify experiment crash rates view logic

sql/moz-fx-data-shared-prod/telemetry/active_users_aggregates/view.sql, sql_generators/active_users_aggregates_v4/templates/mobile_view.sql, sql_generators/active_users_aggregates_v4/templates/view.sql
This change ads an additional field to the active_users_aggregates view which maps the distribution_id to a device partner to enable filtering of the KPI dashboards for this specific user segment.
This is an alternative to turning the active_users_aggregates in lookml to support this filtering. For more info on this approach see: https://github.com/mozilla/looker-spoke-default/pull/984
=> feat: add partnership field to the active_users_aggregates view template

dags.yaml, sql/moz-fx-data-shared-prod/telemetry/desktop_acquisition_funnel_aggregates/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_acquisition_funnel_aggregates_v1/checks.sql, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_acquisition_funnel_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_acquisition_funnel_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/desktop_acquisition_funnel_aggregates_v1/schema.yaml
This PR creates the following new table: 
- moz-fx-data-shared-prod.telemetry_derived.desktop_acquisition_funnel_aggregates_v1
And it also creates a new DAG:  `bqetl_dsktp_acqstn_fnnl` which runs daily
* [DENG-6883](https://mozilla-hub.atlassian.net/browse/DENG-6883)
[DENG-6883]: https://mozilla-hub.atlassian.net/browse/DENG-6883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized …
=> DENG-6883 & DENG-6884 - Create desktop_acquisition_funnel_aggregates table

bigquery_etl/cli/metadata.py, bqetl_project.yaml, tests/cli/test_cli_metadata.py, tests/sql/moz-fx-data-shared-prod/telemetry_derived/dataset_metadata.yaml
See https://github.com/mozilla/bigquery-etl/issues/6716
If I understand the issue correctly, we want to retain dataset permissions of some roles when tables get deprecated. Currently, `workgroup_access` is set to `[]` in `dataset_metadata.yaml` when a table gets deprecated. 
This change adds a configuration option where we can list roles whose permissions should be retained on deprecation. I added `roles/bigquery.dataEditor` for now. 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7186)
=> [#6716] Retain workgroup permissions

sql/moz-fx-data-shared-prod/pocket/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/dataset_metadata.yaml
Adding missing dataset metadata files for `pocket` and `pocket_derived` datasets
=> Adding dataset metadata for `pocket` and `pocket_derived`

sql/moz-fx-data-shared-prod/legal_derived/dataset_metadata.yaml
We identified legal tables in the analysis dataset as part of the data retention project. Although these tables do not contain sensitive data, it has been decided to relocate them to a more secure location, since the analysis dataset is primarily meant as temporary storage.
The tables will be manually moved once the dataset is created in `shared-prod`
=> DENG-6814 - Create a new legal_derived dataset

sql/moz-fx-data-shared-prod/jira_service_desk/issue/view.sql
The join between field option ID and field history needs to happen on the `value` field
=> [DENG-6141] Tweak Jira join logic

sql_generators/experiment_monitoring/templates/experiment_enrollment_aggregates_v1/query.sql, sql_generators/experiment_monitoring/templates/experiment_events_live_v1/materialized_view.sql, sql_generators/experiment_monitoring/templates/templating.yaml
Experiment validation was fixed in Fx 109, so validation error events before that version are not useful and can cause confusion in experiment monitoring. This PR ignores them in counts.
- for Cirrus apps, we keep all validation errors
* validation fix: https://bugzilla.mozilla.org/show_bug.cgi?id=1803838
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7224)
=> Experiment validation errors version filter

sql/moz-fx-data-shared-prod/telemetry/socorro_crash/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/socorro_crash_v2/metadata.yaml
Should fix https://mozilla.slack.com/archives/C4D5ZA91B/p1736538436459249.  These are the only non-default access views in `telemetry` so we shouldn't see this again for now.  Related to https://github.com/mozilla/bigquery-etl/issues/5830
=> Grant mozilla-confidential access to socorro views

sql_generators/events_daily/templates/event_types/templating.yaml, sql_generators/events_daily/templates/event_types_history_v1/templating.yaml, sql_generators/events_daily/templates/event_types_v1/templating.yaml, sql_generators/events_daily/templates/events_daily/templating.yaml, sql_generators/events_daily/templates/events_daily_v1/templating.yaml
Events Daily tables for legacy Accounts data are [no longer in use](https://mozilla.acryl.io/dataset/urn:li:dataset:(urn:li:dataPlatform:bigquery,moz-fx-data-shared-prod.firefox_accounts_derived.events_daily_v1,PROD)/Lineage?is_lineage_mode=false) after Glean migration and switch to bqetl-generated funnel tables.
This needs https://github.com/mozilla/lookml-generator/pull/1141 to land first to avoid LookML generation errors.
=> Remove legacy Accounts event analysis tables

sql/moz-fx-data-shared-prod/telemetry/uninstalls_on_day_of_install_by_cpu_core_count/view.sql, sql/moz-fx-data-shared-prod/telemetry/uninstalls_on_day_of_install_by_os_install_yr/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_on_day_of_install_by_cpu_core_count_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_on_day_of_install_by_cpu_core_count_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_on_day_of_install_by_cpu_core_count_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_on_day_of_install_by_os_install_yr_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_on_day_of_install_by_os_install_yr_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_on_day_of_install_by_os_install_yr_v1/schema.yaml
This PR creates 2 uninstall aggregate tables:
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_on_day_of_install_by_os_install_yr_v1
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_on_day_of_install_by_cpu_core_count_v1
=> DENG-6884 Create last 2 uninstall aggregate tables

sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_browser_aggregates/view.sql, sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_day/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_browser_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_browser_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_browser_aggregates_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_country_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_country_aggregates_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_day_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_day_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_day_v1/schema.yaml
This PR creates the 2 following uninstall aggregate table: 
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_day_v1
- moz-fx-data-shard-prod.telemetry_derived.uninstalls_by_browser_aggregates_v1
It also adds a new column to the table
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_country_aggregates_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7282)
=> DENG-6884 - Uninstall aggregates continued

bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/templates/airflow_dag.j2, tests/data/dags/python_script_test_dag
Sets the Bigeye task execution timeout to an hour. We have had instances were these tasks get stuck, blocking downstream tasks. Usually restarting them does the trick.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7286)
=> Set Bigeye Airflow task timeouts to 1h

sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_addon/view.sql, sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_attr_src/view.sql, sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_dflt_srch/view.sql, sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_dlsource/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_addon_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_addon_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_addon_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_attr_src_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_attr_src_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_attr_src_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_dflt_srch_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_dflt_srch_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_dflt_srch_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_dlsource_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_dlsource_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_dlsource_v1/schema.yaml
This PR creates the following aggregate tables: 
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_addon_v1
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_attr_src_v1
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_dflt_srch_v1
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_dlsource_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7301)
=> DENG-6884 uninstall aggregates

sql/moz-fx-data-shared-prod/firefox_ios/app_store_choice_screen_selection/view.sql, sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_selection_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_selection_v1/query.py, sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_selection_v1/schema.yaml
Apple made some changes which resulted in Choice Screen related report evolving and completely changing its shape. This report include all clients on iOS 18.2 and above and those will not be available in the previous version `app_store_choice_screen_engagement` ETL.
Once this change is merged we should backfill the data starting `2024-12-05`.
* Note: Branch name is incorrect, and this report starts with ios 18.2 users.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7218)
=> feat: add app_store_choice_screen_selection ETL to pull the new version of DMA related report

sql/moz-fx-data-shared-prod/telemetry/uninstalls_by_cpu_cores/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_cpu_cores_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_cpu_cores_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/uninstalls_by_cpu_cores_v1/schema.yaml
This PR creates the table: 
- moz-fx-data-shared-prod.telemetry_derived.uninstalls_by_cpu_cores_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7334)
=> DENG-6884 Create uninstalls_by_cpu_cores_v1

sql_generators/mobile_kpi_support_metrics/templates/active_users.view.sql, sql_generators/mobile_kpi_support_metrics/templates/engagement.query.sql, sql_generators/mobile_kpi_support_metrics/templates/engagement.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/engagement_clients.view.sql, sql_generators/mobile_kpi_support_metrics/templates/new_profile_clients.view.sql, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.query.sql, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/retention.query.sql, sql_generators/mobile_kpi_support_metrics/templates/retention.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/retention_clients.view.sql
This change aims to add the following two fields to engagement, retention and new_profiles KPI support metric aggregated datasets to support DMA related analysis needed.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7188)
=> feat(DENG-6890): Update mobile kpi support metric aggregates to support dma analysis

sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_selection_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/app_store_choice_screen_selection_v1/query.py
This is to make it easier to understand the issue and handle the reports arriving with a 2 day delay.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7371)
=> fix: log a more useful message in cases where no reports are found and add 2 day lag to the date of the report being pulled

bigquery_etl/cli/metadata.py, tests/cli/test_cli_metadata.py, tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/metadata.yaml
Fixes https://github.com/mozilla/bigquery-etl/issues/5830
Update the `metadata update` logic to union `default_table_workgroup_access` entries with table-level `workgroup_access` entries
=> #5830 Union default_table_workgroup_access with table-level workgroup_accesss in metadata generation logic

sql/moz-fx-data-shared-prod/telemetry_derived/event_events_v1/query.sql, sql_generators/glean_usage/templates/events_stream_v1.query.sql
This event is probably incorrectly being sent and causing a increase in event table size.  The event is going to stop being sent from release clients with https://bugzilla.mozilla.org/show_bug.cgi?id=1942005 so going to do the same thing for older clients.  Filtering these out in the derived events will reduce storage and shredder load.
Some prior art in https://github.com/mozilla/bigquery-etl/pull/1942
* DENG-7513
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7536)
=> [DENG-7513] Filter unexpectedload events from desktop derived events

sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports/view.sql, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports_live/view.sql
We use this view as our point of ingestion for user reports. Recently, we also shipped the reporter to Fenix, and we want to ingest that data, too. Not sure if this is the most efficient way of doing this - I originally wanted to UNION the main query, but that'd have me duplicate everything, which felt wrong.
This also replaces the `app_name` with a static string for desktop and mobile. For desktop, this is not changing anything - but for mobile, the `normalized_app_name` column is always `null`. After chatting with @badboy, I learned that [this column is kinda legacy anyway](https://bugzilla.mozilla.org/show_bug.cgi?id=1672191#c1), and we only really need it to see which product the reports came from, so this is an easy way to make sure this is set right.
r? @scholtzan, please :)
n/a …
=> feat(org_mozilla_broken_site_report): Add mobile reports to the unified view.

bigquery_etl/shredder/config.py, sql/moz-fx-data-shared-prod/telemetry_derived/clients_profile_per_install_affected_v1/metadata.yaml
Looked at this as part of DENG-7480.  This table doesn't have any queries in the last two years and no code references.  I don't know what this is for but the data is from 2019-01-31 to 2019-08-04 which is pre-shredder/deletion requests so I don't know what the description means.  I'm pretty sure it's not used for anything though
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7594)
=> Deprecate telemetry_derived.clients_profile_per_install_affected_v1

sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v2/schema.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v2/schema.yaml
This PR is a follow up PR to [PR-6834](https://github.com/mozilla/bigquery-etl/pull/6834) that adds column descriptions to 2 new tables to fix the shredder mitigation error:
- moz-fx-data-shared-prod.fenix_derived.feature_usage_metrics_v2
- moz-fx-data-shared-prod.firefox_ios_derived.feature_usage_metrics_v2
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7605)
=> Add column descriptions to deal with CI shredder mitigation error

sql/moz-fx-data-shared-prod/firefox_accounts_derived/health_lighthouse_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_accounts_derived/health_lighthouse_v1/schema.yaml
Adds Accounts Lighthouse Health data.  This is my first PR here so please let me know if I did anything wrong.
When I add a spreadsheet as a source directly in bigquery I can specify what tab to use.  I didn't see that in [the instructions](https://docs.telemetry.mozilla.org/cookbooks/operational/connecting_external_data_bigquery.html#connecting-sheets) and I'm not sure where to add it to the yaml.  The data is on the "Lighthouse" tab in my spreadsheet.  
Tagging @sean-rose because we were already discussing this earlier.  Thanks
none
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7600)
=> Add accounts health lighthouse data

docs/cookbooks/creating_a_derived_dataset.md
Clarification in managed backfill docs.
* DENG-7329
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7619)
=> Clarifiction in docs for managed backfills.

sql/moz-fx-data-shared-prod/telemetry/prvt_brwsng_mode_retention/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/prvt_brwsng_mode_retention_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/prvt_brwsng_mode_retention_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/prvt_brwsng_mode_retention_v1/schema.yaml
This PR creates the following new aggregate table that calculates retention over time for private browsing mode users vs not.  
- moz-fx-data-shared-prod.telemetry_derived.prvt_brwsng_mode_retention_v1
* [DENG-6893](https://mozilla-hub.atlassian.net/browse/DENG-6893)
[DENG-6893]: https://mozilla-hub.atlassian.net/browse/DENG-6893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7627)
=> Create last aggregate table for retention of PBM users

bigquery_etl/metadata/validate_metadata.py, tests/cli/test_cli_metadata.py
CI check to apply the label shredder-mitigation only to existing and non-empty tables.
* DENG-7625
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7626)
=> CI check to apply label for shredder mitigation

bigquery_etl/dryrun.py
The `bqetl dryrun` command doesn't currently support queries which use any non-date query parameters.  This PR adds support for such queries by passing all expected query parameters when dry-running queries.
This depends on mozilla-services/cloudops-infra#6189 to update the `bigquery_etl_dryrun` Google Cloud function to accept query parameters as an argument.
* https://github.com/mozilla-services/cloudops-infra/pull/6189
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7559)
=> feat(dryrun): Pass all query parameters when dry-running queries

dags.yaml, sql/moz-fx-glam-prod/glam_etl/glam_fenix_release_aggregates_v1/metadata.yaml, sql/moz-fx-glam-prod/glam_etl/glam_fog_release_aggregates_v1/metadata.yaml
fixes https://github.com/mozilla/bigquery-etl/issues/6849
Similar to https://github.com/mozilla/bigquery-etl/pull/6646, this PR:
* Transforms `bqetl_glam_refresh_aggregates_fog_release` into `bqetl_glam_refresh_aggregates_release` so both Fenix and FOG load jobs can run there
* Extracts `bqetl_refresh_aggregates.glam_fenix_release_aggregates` into `bqetl_glam_refresh_aggregates_release` so it can follow `glam_fenix_release`'s schedule.
* DENG-7623
=> chore(glam): generalize refresh_agg_release and move fenix_release there

sql/moz-fx-data-shared-prod/addons_derived/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/addons_derived/search_detection_v1/schema.yaml
follow-up to: https://github.com/mozilla/bigquery-etl/pull/6827
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7660)
=> fix: incorrect user_facing setting for addons_derived

sql/moz-fx-data-shared-prod/search/mobile_search_clients_daily/view.sql
This PR fixes the value of `normalized_app_name_os` being incorrectly set to `normalized_app_name` insode `mobile_search_clients_daily`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7597)
=> fix(DO-1924): wrong struct value set as normalized_app_name_os

sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activation_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activation_v2/query.sql
depends on: https://github.com/mozilla/bigquery-etl/pull/6841
---
Making sure we are filtering for the correct application when pulling out client's search counts for activation calculation.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7599)
=> fix: make sure the correct filter is applied when selecting search counts when calculating profile activation

sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v2/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_searches_by_provider_v2/schema.yaml
This PR creates a new aggregate table:
- moz-fx-data-shared-prod.telemetry_derived.fx_health_ind_searches_by_provider_v2 
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7663)
=> Create v2 agg table to test shredder mitigated backfill

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql
[Dry run](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/44269/workflows/4b6ec306-8298-405a-bb6c-e3eacedbae88/jobs/513223) is failing with
```
[{'code': 400, 'errors': [{'message': 'Column 6 in UNION ALL has incompatible types: STRUCT<end_time STRING, ...> at [627:5]'
```
because of the new `home_v1` table which has a different order of fields in `ping_info`.  
Sean pointed out that we could reuse [Schema.generate_compatible_select_expression()](https://github.com/mozilla/bigquery-etl/blob/fcc07de2d2f982d1f573b284e5de9be035a21ec7/bigquery_etl/schema/__init__.py#L299-L426) here but due to urgency I'm putting this PR up for now
┆Issue is synchronized …
=> Specify ping_info fields in event_monitoring_aggregates

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql, sql_generators/glean_usage/templates/event_monitoring_live_v1.materialized_view.sql
Same issue as https://github.com/mozilla/bigquery-etl/pull/6878 where the ping_info fields don't match for the union.  This is just failing dry run because the materialized views don't get redeployed.  This seems to have a significant impact on query performance for `event_monitoring_aggregates_v1` (+200 to 250 slot hours comparing week-over-week but it runs with on-demand) so there's some risk if `firefox_desktop_derived.event_monitoring_live_v1` gets redeployed since it's already expensive.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7695)
=> Specify ping info fields in event_monitoring_live

sql/moz-fx-data-shared-prod/addons_derived/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/addons_derived/search_detection_v1/backfill.yaml, sql/moz-fx-data-shared-prod/addons_derived/search_detection_v1/metadata.yaml
Adding the backfill entry to populate the new table with historical data.
depends on: https://github.com/mozilla/bigquery-etl/pull/6869
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7658)
=> feat(DENG-7656): add backfill.yaml to addons_derived.search_detection_v1

sql/moz-fx-data-shared-prod/addons_derived/search_detection_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7717)
=> fix: add override_retention_limit setting to search_detection_v1 backfill

sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/schema.yaml
Fixes schema deploy failures for `moz-fx-data-shared-prod.addon_moderations_derived.cinder_decisions_raw_v1`: `Schema does not match Table moz-fx-data-shared-prod:addon_moderations_derived.cinder_decisions_raw_v1. Field created_at has changed type from TIMESTAMP to STRING)`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7718)
=> Update cinder_decisions_raw_v1 schema

sql/moz-fx-data-shared-prod/search_terms_derived/adm_daily_aggregates_v1/query.sql
suggest_impression_sanitized_v3 renames sanitized_query to query, which broke this job after https://github.com/mozilla/bigquery-etl/pull/6845.
This should fix it.
* [AE-689](https://mozilla-hub.atlassian.net/browse/AE-689)
[AE-689]: https://mozilla-hub.atlassian.net/browse/AE-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7720)
=> Fix adm_daily_aggregates_v1

sql/moz-fx-data-shared-prod/search_terms_derived/adm_daily_aggregates_v1/query.sql
Missed one more reference to sanitized query in https://github.com/mozilla/bigquery-etl/pull/6898
* [DSRE-1890](https://mozilla-hub.atlassian.net/browse/DSRE-1890)
* [AE-689](https://mozilla-hub.atlassian.net/browse/AE-689)
[DSRE-1890]: https://mozilla-hub.atlassian.net/browse/DSRE-1890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AE-689]: https://mozilla-hub.atlassian.net/browse/AE-689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7728)
=> Bug 1944385 - Further fix adm_daily_aggregates_v1

.circleci/workflows.yml, bigquery_etl/cli/dryrun.py, bigquery_etl/cli/query.py, bigquery_etl/metadata/validate_metadata.py
fixes #6875.  `sys.exit(0)` in the dry run command causes the metadata validation to exit early so it doesn't actually validate more than one metadata file ([example](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/44363/workflows/f0517bc1-771b-4591-8b97-bd7d914ccdf4/jobs/514580)).
CI step changes:
- added `--no-dryrun` to the `validate-metadata` CI step because it's redundant in CI
- added `--skip-format-sql` option because it takes too long to run for every query
- removed `--respect-dryrun-skip` becaus queries aren't run so it should work
I didn't find any other uses of dryrun or `sys.exit(0)` that would have similar behaviour.
* #6875
┆Issue is …
=> Make validate-metadata run on all files

sql_generators/experiment_monitoring/templates/experiments_daily_active_clients_v1/query.sql
This PR updates the id for the application using Cirrus. Instead of using `user_id`, renaming it to `nimbus_user_id`
https://mozilla-hub.atlassian.net/browse/EXP-5006
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-6781)
=> feat(nimbus): Update user_id to nimbus_user_id

CODEOWNERS, bigquery_etl/metadata/validate_metadata.py
With metadata validation fixed in https://github.com/mozilla/bigquery-etl/pull/6891, there are some failing shredder mitigation checks.  The check is still being worked on so commenting them out for now
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7732)
=> Remove shredder mitigation metadata check

sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/baseline_clients_daily_v1/backfill.yaml, sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/baseline_clients_daily_v1/backfill.yaml, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/baseline_clients_daily_v1/backfill.yaml, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/baseline_clients_daily_v1/backfill.yaml
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7714)
=> feat: Move baseline_clients_daily_v1 backfill entry to Complete for firefox_ios and fenix beta and release channels

sql/moz-fx-data-shared-prod/fenix_derived/engagement_v1/backfill.yaml, sql/moz-fx-data-shared-prod/fenix_derived/new_profiles_v1/backfill.yaml, sql/moz-fx-data-shared-prod/fenix_derived/retention_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/engagement_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profiles_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/retention_v1/backfill.yaml, sql_generators/mobile_kpi_support_metrics/templates/engagement.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/retention.metadata.yaml
New fields were added to the tables in order to support DMA analysis. As part of this we need to backfill the corresponding tables for both firefox_ios and fenix. This includes backfill the following tables for both products with data starting 2024-03-05:
- engagement_v1
- retention_v1
- new_profiles_v1
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7618)
=> feat(DENG-6890): mobile kpi support metrics managed backfill 20250122

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_daily_interactions_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_daily_interactions_aggregates_v1/schema.yaml
This is failing dry run because of missing columns in the schema: https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/44507/workflows/1fc67c4c-0ff4-4b28-8e12-d497e258f1d1/jobs/516324
I updated it with: `bqetl query schema update telemetry_derived.newtab_daily_interactions_aggregates_v1`
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7737)
=> Update schema for newtab_daily_interactions_aggregates_v1

sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v2/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v2/backfill.yaml
Backfill feature_usage_metrics_v2 with new ping join logic
[DENG-7535](https://mozilla-hub.atlassian.net/browse/DENG-7535)
[DENG-7535]: https://mozilla-hub.atlassian.net/browse/DENG-7535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7738)
=> Backfill feature_usage_metrics_v2

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_antivirus/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_antivirus_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_antivirus_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_antivirus_v1/schema.yaml
This PR adds the normalized OS column to the group by in fx_health_ind_antivirus_v1 to make the table more usable for other use cases, while keeping the filter in the view to the same as before so the Firefox Health Indicator dashboard continues to work as expected.
* [DENG-7723](https://mozilla-hub.atlassian.net/browse/DENG-7723)
[DENG-7723]: https://mozilla-hub.atlassian.net/browse/DENG-7723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7756)
=> DENG-7723: Add OS group by to fx_health_ind_antivirus_v1 

sql/moz-fx-data-shared-prod/telemetry/fx_health_ind_bookmarks_by_os_version/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_version_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_version_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_health_ind_bookmarks_by_os_version_v1/schema.yaml
This PR adds the normalized_os and normalized_os_version to the group by on the table telemetry_derived.fx_health_ind_bookmarks_by_os_version, while adding the old filters to the view level so as not to impact the existing dashboard.  This will help us have a historical table of bookmarks by different OS types and versions over time.
* [DENG-7723](https://mozilla-hub.atlassian.net/browse/DENG-7723)
[DENG-7723]: https://mozilla-hub.atlassian.net/browse/DENG-7723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7760)
=> DENG-7723: Add OS and OS version to group by on fx_health_ind_bookmarks_by_os_version_v1

sql/moz-fx-data-shared-prod/fenix/feature_usage_metrics/view.sql, sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v2/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_ios/feature_usage_metrics/view.sql, sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v2/metadata.yaml
Point view to new version and change logic of labeled counters to use the UDFs.
* [DENG-7535](https://mozilla-hub.atlassian.net/browse/DENG-7535)
[DENG-7535]: https://mozilla-hub.atlassian.net/browse/DENG-7535?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7697)
=> Update feature metrics to v2

sql/moz-fx-data-shared-prod/fenix_derived/ltv_android_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/ltv_ios_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/ltv_desktop_aggregates_v1/metadata.yaml
Adds date partitions to the LTV aggregates tables.
* DENG-7550
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7794)
=> [DENG-7550] add date partitions to ltv aggregates tables

sql/moz-fx-data-shared-prod/fenix_derived/ltv_android_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/ltv_ios_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/ltv_desktop_aggregates_v1/metadata.yaml
Follow-up to https://github.com/mozilla/bigquery-etl/pull/6934, I just tested a backfill locally with 
```
bqetl query backfill moz-fx-data-shared-prod.firefox_ios_derived.ltv_ios_aggregates_v1 --dry-run --project-id moz-fx-data-shared-prod --start-date 2025-01-20 --end-date 2025-01-22 --destination_table=benwubenwutest.tmp.backfill_test
```
and I got `BigQuery error in query operation: Duplicate query parameters named submission_date` so this might be needed
* DENG-7550
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7797)
=> [DENG-7550] Remove submission_date parameter from ltv aggregates

sql/moz-fx-data-shared-prod/search_terms_derived/adm_daily_aggregates_v1/checks.sql
This PR adds a check for a minimum row count of at least 100 per day.  We were alerted in the data-help channel that this ETL job was silently failing with very small # of rows for over a year, so we'd like to add a row count check to be alerted sooner next time if row counts start to drop.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7782)
=> Add minimum row count check for at least 100 rows

bqetl_project.yaml
This PR adds the table moz-fx-data-shared-prod/telemetry_derived/clients_first_seen_28_days_later_v3 to the retention exclusion list, per Su's request.
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7801)
=> Add clients_first_seen_28_days_later_v3 to retention exclusion

sql_generators/mobile_kpi_support_metrics/__init__.py, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.query.sql, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.view.sql, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.query.sql, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.view.sql
This PR introduced the following templates to `mobile_kpi_support_metrics` generator:
- activation_clients.query.sql
- activation_clients.view.sql
- activation_clients.metadata.yaml
- activation_clients.bigconfig.yaml
- activation_clients.schema.yaml
- activations.query.sql
- activations.view.sql
- activations.metadata.yaml
- activations.bigconfig.yaml
- activations.schema.yaml
The fields used in these is consistent with all the other templates in this generator.
Here's an overview of each template type:
- `query.sql` - for creating a query used to generate new partitions.
- `metadata.yaml` - for defining table definition and scheduling options.
- `bigconfig.yaml` - for generating bigeye metrics.
- `schema.yaml` - for defining table schema, also used to create empty tables in combination …
=> feat(DO-1935): add activation_clients and activations templates

sql/moz-fx-data-shared-prod/telemetry/experiment_cumulative_ad_clicks/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/experiment_cumulative_search_count/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/experiment_cumulative_search_with_ads_count/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_cumulative_ad_clicks_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_cumulative_search_count_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_cumulative_search_with_ads_count_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_search_aggregates_live_v1/metadata.yaml, sql_generators/experiment_monitoring/templates/experiment_search_aggregates_v1/metadata.yaml, sql_generators/experiment_monitoring/templates/experiment_search_events_live_v1/metadata.yaml
Reverts mozilla/bigquery-etl#6647
We want to add them back to experiment enrollment monitoring
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7803)
=> Revert "Remove experiment search monitoring"

sql_generators/mobile_kpi_support_metrics/__init__.py, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.metadata.yaml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.schema.yaml
The schema deploy for the new tables is failing with https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/44834/workflows/958b330c-4780-4ddb-997c-1c200290cbfa/jobs/520487
This should fix the issue.
And update fenix friendly name to work as a join key with the search data.
=> DENG-6756 - Fix the schema for the new profile clients activation tables and update fenix friendly name

sql/moz-fx-data-shared-prod/microsoft_derived/app_acquisitions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/microsoft_derived/app_acquisitions_v1/query.py, sql/moz-fx-data-shared-prod/microsoft_derived/app_conversions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/microsoft_derived/app_conversions_v1/query.py, sql/moz-fx-data-shared-prod/microsoft_derived/app_installs_v1/metadata.yaml, sql/moz-fx-data-shared-prod/microsoft_derived/app_installs_v1/query.py
* [DENG-7011](https://mozilla-hub.atlassian.net/browse/DENG-7011)
* DSRE-XXXX
[DENG-7011]: https://mozilla-hub.atlassian.net/browse/DENG-7011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Microsoft add delay when job is run for all three scripts

sql/moz-fx-data-shared-prod/external/calendar/view.sql, sql/moz-fx-data-shared-prod/external/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/external_derived/calendar_v1/metadata.yaml, sql/moz-fx-data-shared-prod/external_derived/calendar_v1/query.sql, sql/moz-fx-data-shared-prod/external_derived/calendar_v1/schema.yaml, sql/moz-fx-data-shared-prod/external_derived/dataset_metadata.yaml
This PR creates a new dataset which will be used to store a variety of new tables being pulled from external sources, such as, CPI data, GDP data, exchange rate data, population data, and holiday data.
This first PR does 3 things: 
- Creates the new datasets - external_derived and external
- Creates the new calendar table that has 1 row for every date from start of Mozilla to end of year 2100
- This table is a prequisite for DENG-7810 (creating a global holiday/event table which will flag key dates to help better understand deviances in Firefox usage due to holidays, internet outages, large events, etc.)
* [DENG-7811](https://mozilla-hub.atlassian.net/browse/DENG-7811)
**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/blob/main/.github/reviewer_checklist.md …
=> DENG-7811-Calendar Table

sql/moz-fx-data-marketing-prod/adjust_derived/firefox_mobile_installs_v1/metadata.yaml
=> take out scheduling in metadata.yaml file

sql/moz-fx-data-shared-prod/external_derived/calendar_v1/metadata.yaml
This PR removes partitioning from a new table:
- moz-fx-data-shared-prod.external_derived.calendar_v1`
* [DENG-7811](https://mozilla-hub.atlassian.net/browse/DENG-7811)
[DENG-7811]: https://mozilla-hub.atlassian.net/browse/DENG-7811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove partitioning, doesn't make sense in this case

sql_generators/mobile_kpi_support_metrics/__init__.py, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.query.sql
reverting change introduced in this commit: https://github.com/mozilla/bigquery-etl/pull/6948/commits/7d0851f33adfebb26f59a8a8ecf390345946c85c
Also, adding `search_join_key` property to allow joining with search dataset.
=> fix: revert the friendly name change for fenix and create a new field instead of joining with the search dataset

sql/moz-fx-data-shared-prod/monitoring_derived/outerbounds_flow_description_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/outerbounds_flow_description_v1/schema.yaml
In service of [this ticket](https://mozilla-hub.atlassian.net/browse/DENG-5180) to surface Flow descriptions on the MLOps cost dashboard, this PR adds a table to yoink data from [this google sheet](https://docs.google.com/spreadsheets/d/1E0kDpHwwtDnkMxAXbeEIzMTajckSHWJ2swF39JdRR1g) into Bigquery. I followed [this documentation](https://docs.telemetry.mozilla.org/cookbooks/operational/connecting_external_data_bigquery.html?highlight=spreadsh#connecting-sheets) to execute the task.
I have added the service account listed in the documentation as an editor to the spreadsheet.
* DENG-5180
=> DENG-5180 (mlops) Add a table to record Flow descriptions

sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activations_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/new_profile_activations_v1/backfill.yaml, sql/moz-fx-data-shared-prod/focus_android_derived/new_profile_activations_v1/backfill.yaml, sql/moz-fx-data-shared-prod/focus_ios_derived/new_profile_activations_v1/backfill.yaml, sql/moz-fx-data-shared-prod/klar_android_derived/new_profile_activations_v1/backfill.yaml, sql/moz-fx-data-shared-prod/klar_ios_derived/new_profile_activations_v1/backfill.yaml
Wait until backfill via: https://github.com/mozilla/bigquery-etl/pull/6941 is completed prior to merging.
Do not merge until the following change is merged: https://github.com/mozilla/bigquery-etl/pull/6965
=> feat: add backfill entry for mobile products for new_profile_activations

sql/moz-fx-data-shared-prod/monitoring/table_storage_trends/view.sql
This PR creates a new view to help track changes in partitions over the last few time periods: 
- over last 3 days
- over last 7 days
- over last 14 days
The new view is: `moz-fx-data-shared-prod.monitoring.table_storage_trends`
* [DENG-7601](https://mozilla-hub.atlassian.net/browse/DENG-7601)
[DENG-7601]: https://mozilla-hub.atlassian.net/browse/DENG-7601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Create view monitoring.table_storage_trends

sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql
=> fix(bug-1946076): handle the case of is_default_browser existing in both baseline and metrics now

sql/moz-fx-data-shared-prod/jira_service_desk/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk_derived/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/jira_service_desk_syndicate/dataset_metadata.yaml
https://mozilla-hub.atlassian.net/browse/DENG-7814
This restricts access to the Jira Service Desk datasets to the `service-desk` workgroup.
=> Set service-desk workgroup access on jira service desk datasets (DENG-7814)

sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_clients_daily_v1/backfill.yaml
Backfill firefox_desktop_derived. baseline_clients_daily_v1 from 2021-12-01
* DENG-7838
=> DENG-7838 - Backfill baseline_clients_daily for desktop from 2021-12-01

sql/moz-fx-data-shared-prod/glam_etl/dataset_metadata.yaml
Requires https://github.com/mozilla-services/cloudops-infra/pull/6201 and  https://github.com/mozilla-services/cloudops-infra/pull/6202/. See https://mozilla-hub.atlassian.net/browse/DSRE-1886 for details.
* DSRE-1886
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7686)
=> chore(DSRE-1886): add treeherder access to glam_etl data

bqetl_project.yaml, sql/moz-fx-data-shared-prod/zoom/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/zoom/meeting_participants/metadata.yaml, sql/moz-fx-data-shared-prod/zoom/meeting_participants/schema.yaml, sql/moz-fx-data-shared-prod/zoom/meeting_participants/view.sql, sql/moz-fx-data-shared-prod/zoom/meeting_reports/metadata.yaml, sql/moz-fx-data-shared-prod/zoom/meeting_reports/schema.yaml, sql/moz-fx-data-shared-prod/zoom/meeting_reports/view.sql, sql/moz-fx-data-shared-prod/zoom/meetings/metadata.yaml, sql/moz-fx-data-shared-prod/zoom/meetings/schema.yaml, sql/moz-fx-data-shared-prod/zoom/meetings/view.sql, sql/moz-fx-data-shared-prod/zoom/users/metadata.yaml, sql/moz-fx-data-shared-prod/zoom/users/schema.yaml, sql/moz-fx-data-shared-prod/zoom/users/view.sql
Adds authorized views for Zoom data synced by Fivetran.
* DENG-6964: Integrate Zoom into BigQuery/Looker using FiveTran (API)
=> feat: Add authorized views for Zoom data synced by Fivetran (DENG-6964)

dags.yaml, sql/moz-fx-data-shared-prod/external/inflation/view.sql, sql/moz-fx-data-shared-prod/external_derived/inflation_v1/checks.sql, sql/moz-fx-data-shared-prod/external_derived/inflation_v1/metadata.yaml, sql/moz-fx-data-shared-prod/external_derived/inflation_v1/query.py, sql/moz-fx-data-shared-prod/external_derived/inflation_v1/schema.yaml
This PR creates the following new table which will contain data pulled from the IMF CPI API (basically CPI by month and country).
- moz-fx-data-shared-prod.external_derived.inflation_v1
* [DENG-7789](https://mozilla-hub.atlassian.net/browse/DENG-7789)
[DENG-7789]: https://mozilla-hub.atlassian.net/browse/DENG-7789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-7789): Create new inflation_v1 table with data from IMF CPI API

sql/moz-fx-data-shared-prod/microsoft_derived/app_acquisitions_v1/query.py, sql/moz-fx-data-shared-prod/microsoft_derived/app_conversions_v1/query.py, sql/moz-fx-data-shared-prod/microsoft_derived/app_installs_v1/query.py
This PR fixes the error of data being put into the wrong partition. Originally, the timedelta was put into the section where the script would download the data from Microsoft store. Since there is a 3 day delay, the date for the data did not match the partition date.
Move the timedelta out of the download function and into main. This will ensure that the data goes into the right partition
Added comments to explain why the delay is used
Added the date to the output message to make the date of the data clearer
* DENG-XXXX
* DSRE-XXXX
=> move the timedelta to main so data goes into the proper partition

sql/moz-fx-data-shared-prod/monitoring_derived/outerbounds_flow_description_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/outerbounds_flow_description_v1/query.py
- See this for details: https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/45227/workflows/5d48eff8-5933-4c59-a960-d082ae86fd31/jobs/525621
Ran into the issue https://mozilla-hub.atlassian.net/browse/DSRE-1247 after trying to merge https://github.com/mozilla/bigquery-etl/pull/6958
`monitoring_derived.outerbounds_flow_description_v1` (landed in https://github.com/mozilla/bigquery-etl/pull/6957) connects a spreadsheet to BigQuery, but Airflow won't be able to query it due to the scopes issue. So, taking [inspiration from the past](https://github.com/mozilla/bigquery-etl/blob/e26ee766a7c9e3f5d9d935a88a12597a0b4f63d5/sql/moz-fx-data-shared-prod/mozilla_vpn_derived/vat_rates_v1/query.py) to import the data from the spreadsheet via a `query.py` script.
Thanks @scholtzan for all the …
=> DENG-5180 Outerbounds Flow description: Script to import data from spreadsheet

sql/moz-fx-data-shared-prod/monitoring_derived/outerbounds_cost_per_flow_run_v1/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/outerbounds_cost_per_flow_v1/view.sql
This PR adds flow description field to the existing `outerbounds_cost_per_flow_v1` view.
The flow descriptions are coming from the `outerbounds_flow_description_v1` BQ table which was created in https://github.com/mozilla/bigquery-etl/pull/6957.
* DENG-5180
=> DENG-5180 (mlops) Add outerbounds flow description to cost per flow View

sql/moz-fx-data-shared-prod/jira_service_desk_derived/user_v1/query.py
Change the jira URL to point to PROD
[DENG-6141](https://mozilla-hub.atlassian.net/browse/DENG-6141)
[ASP-6006]: https://mozilla-hub.atlassian.net/browse/ASP-6006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DENG-6141]: https://mozilla-hub.atlassian.net/browse/DENG-6141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(code):Change base_jira_url to the jira PROD url

sql/moz-fx-data-shared-prod/microsoft_derived/app_acquisitions_v1/query.py, sql/moz-fx-data-shared-prod/microsoft_derived/app_conversions_v1/query.py, sql/moz-fx-data-shared-prod/microsoft_derived/app_installs_v1/query.py
This PR removes the timedelta and adds more descriptive comments to understand what date's data is being downloaded
* DENG-XXXX
* DSRE-XXXX
=> revert changes to delay, so can add delay to airflow job instead

sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_clients_daily_v1/backfill.yaml
Complete and move to prod: backfill of firefox_desktop_derived.baseline_clients_daily_v1 from 2021-12-01 to 2025-02-03
I have done spot checks on the backfill staging table `moz-fx-data-shared-prod.backfills_staging_derived.firefox_desktop_derived__baseline_clients_daily_v1_2025_02_05` and the prod table `moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_daily_v1`. The generated backfill table seems good to move to prod for those dates.
* DENG-7838
=> DENG-7838 - firefox_desktop_derived.baseline_clients_daily_v1 complete

sql/moz-fx-data-shared-prod/backfills_staging_derived/baseline_clients_last_seen_v1_20211130/metadata.yaml, sql/moz-fx-data-shared-prod/backfills_staging_derived/baseline_clients_last_seen_v1_20211130/query.sql
Fix for https://github.com/mozilla/bigquery-etl/pull/7010.  Also updates the query to query itself instead of the prod table
=> Fix format errors in baseline_clients_last_seen_v1_20211130

sql/moz-fx-data-shared-prod/fenix_derived/profile_dau_metrics_marketing_geo_testing_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/profile_dau_metrics_marketing_geo_testing_v1/backfill.yaml
feat: add backfill entries for new_profile_metrics_marketing_geo_testing_v1
depends on: https://github.com/mozilla/bigquery-etl/pull/6970
=> Mark - backfill for profile_dau_metrics_marketing_geo_testing_v1 (fenix and ios) as Complete

sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/backfill.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/query.sql
Adding channel for firefox installer errors since those are high volume as well.  Also doing a backfill of 100 days so the health check dashboard graphs are consistent
* DENG-7209
=> [DENG-7209] Add channel to firefox-installer schema errors

bigquery_etl/shredder/config.py
This PR adds the new client level table `moz-fx-data-shared-prod.telemetry_derived.rolling_cohorts_v2` (which contains both desktop and mobile client IDs) to shredder configuration.
* [DENG-2986](https://mozilla-hub.atlassian.net/browse/DENG-2986)
[DENG-2986]: https://mozilla-hub.atlassian.net/browse/DENG-2986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add rolling_cohorts_v2 to shredder config

.pre-commit-config.yaml
This would add a local pre-commit hook to run bqetl format --check automatically on each commit on modified sql files. The idea here is to prevent situations in which a developer commit sql code changes to the repository only to find out during the CI run that their SQL needs to be reformatted. This however, is not perfect as currently it results in a Exception stack trace being printed out instead of just filenames of filed that would need to be reformatted. Ideally this would work similarly to something like `black` where pre-commit would detect files would need to be reformatted, actually do the formatting and require us to run the commit cmd again.
No real risk to this change as this just involved executing bqetl format command locally during when attempting to commit staged changes …
=> feat: add bqetl_format pre-commit

sql_generators/glean_usage/common.py
Some `print`s slipped through the review in https://github.com/mozilla/bigquery-etl/pull/6708
=> Remove debug print statements

bigquery_etl/format_sql/format.py, tests/cli/test_cli_format.py
Currently, if SQL is found to be invalid we end up with an exception being raised when running bqetl format command and an exception stack trace being printed.
This change is meant to handle these cases more gracefully.
=> feat: handle cases when SQL syntaxt is invalid and add invalid to the final report

bigquery_etl/shredder/config.py
This PR updates the shredder mitigation set up for telemetry_derived.rolling_cohorts_v2 to include legacy sources
=> Add legacy sources to rolling_cohorts_v2 delete sources - shredder mitigation

bigquery_etl/shredder/config.py, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v2/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v2/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v2/checks.sql, sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v2/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v2/schema.yaml
This PR does some primary key handling for the rare cases where a client ID is used across multiple channels and/or multiple apps on the same first seen date. It also adds 1 new column to both tables called "row_source" (this is a flag for desktop vs mobile at a high level).
It also adds a data check to ensure that it's 1 row per cohort date, client ID, and row source in rolling_cohorts_v2.
This also updates the shredder mitigation config for rolling_cohorts_v2 to add the Focus additional deletion sources.
* [DENG-2986](https://mozilla-hub.atlassian.net/browse/DENG-2986)
* [Bug 1947555](https://bugzilla.mozilla.org/show_bug.cgi?id=1947555)
[DENG-2986]: …
=> fix(DENG-2986) Minor tweaks to new rolling_cohorts_v2 and cohort_daily_statistics_v2 tables

sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_dau_distribution_id_history_v1/backfill.yaml
Backfill Legacy to GLEAN distribution ID mapping table `desktop_dau_distribution_id_history_v1`
* DENG-7859
=> DENG-7859 - Backfill Legacy to GLEAN distribution ID mapping table

tests/cli/test_cli_backfill.py
Diff is probably going to be hard to read but the main change is to use fixtures to replace a lot of the boilerplate in each test case which writes test files to `sql/moz-fx-data-shared-prod/test/test_query_v1/`.  This removes about 1000 lines and should make these tests a bit less intractable
=> Clean up redundant code from backfill cli tests

sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_dau_distribution_id_history_v1/backfill.yaml
Backfill for Legacy to GLEAN distribution ID mapping table `desktop_dau_distribution_id_history_v1` has been staged in `backfills_staging_derived.firefox_desktop_derived__desktop_dau_distribution_id_history_v1_2025_02_13`
This PR will deploy to the prod table `firefox_desktop_derived.desktop_dau_distribution_id_history_v1`
Did spot checks to verify the presence of the data for the backfill days in the stage table.
* DENG-7859
=> DENG-7859 - Complete backfill for Legacy to GLEAN distribution ID mapping table

sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports/view.sql, sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports_live/view.sql
We originally did that to keep compatibility with another data format that we planned to import. We never imported that data, and we're actually destructing the JSON again on the receiver side, so this isn't super useful.
Exposing all metrics as the new `details` "column" (i.e. record) will allow us to consume all data on our end, but we don't have to maintain that large block of boilerplate code.
This will break existing consumers of the details values - that's fine, as far as we know, we're in full control over everything.
r? @scholtzan
n/a
=> chore(org_mozilla_broken_site_report): Drop the JSON-building from the views.

requirements.in, requirements.txt, sql/moz-fx-data-shared-prod/monitoring/looker_dashboard_load_times/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/looker_dashboard_load_times_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/looker_dashboard_load_times_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/looker_dashboard_load_times_v1/schema.yaml
This adds a new dataset for pulling in Looker dashboard performance data from the Looker activity explores via the Looker API. This data is used to analyse different percentiles of dashboard performances.
Doing the same analysis within Looker is not possible due to it not being able to aggregate different percentiles and due to running into the 5000 rows limit 
=> Add dataset for Looker dashboard performance

sql/moz-fx-data-shared-prod/glean_auto_events_derived/apps_auto_events_metadata_v1/metadata.yaml
This fixes a current issue with [bqetl_public_data_json.export_public_data_json_glean_auto_events_derived__apps_auto_events_metadata__v1](https://workflow.telemetry.mozilla.org/dags/bqetl_public_data_json/grid?task_id=export_public_data_json_glean_auto_events_derived__apps_auto_events_metadata__v1&tab=logs&dag_run_id=scheduled__2025-02-17T05%3A00%3A00%2B00%3A00)
```
google.api_core.exceptions.NotFound: 404 GET https://bigquery.googleapis.com/bigquery/v2/projects/mozilla-public-data/datasets/glean_auto_events_derived/tables/apps_auto_events_metadata_v1?prettyPrint=false: Not found: Dataset mozilla-public-data:glean_auto_events_derived
```
=> Add public dataset glean_auto_events_derived.apps_auto_events_metadata

bigquery_etl/dryrun.py
`fog_decision_support_percentiles_v1` is still timing out after increasing the limit in DENG-7843 but it succeeded once in https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/45776/workflows/c424911e-96ef-4ecc-8b3c-2a3459b2723c/jobs/533134
It would be useful to log how long it takes to dry run so we can see changes over time when a query suddenly starts consistently failing like in this case.
* DENG-7843
=> Log dryrun run time in bqetl dryrun

sql/moz-fx-data-shared-prod/telemetry/cohort_daily_statistics/view.sql
This PR updates the view telemetry.cohort_daily_statistics to exclude app names ending in BrowserStack or MozillaOnline (since those will always have is_dau = False, not useful in this view)
* [DENG-2986](https://mozilla-hub.atlassian.net/browse/DENG-2986)
[DENG-2986]: https://mozilla-hub.atlassian.net/browse/DENG-2986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DENG-2986 - Update cohort_daily_statistics view

sql/moz-fx-data-shared-prod/glean_auto_events_derived/apps_auto_events_metadata_v1/metadata.yaml
This PR fixes the tag for making `apps_auto_events_metadata` public.
* [Bug 1948422](https://bugzilla.mozilla.org/show_bug.cgi?id=1948422)
=> Fix(bqetl_glean_dictionary): fix tag to make table public on bigquery

dags.yaml, sql/moz-fx-data-shared-prod/telemetry/baseline_active_users_aggregates/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/baseline_active_users_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/baseline_active_users_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/baseline_active_users_aggregates_v1/schema.yaml
This PR creates the new table:
- moz-fx-data-shared-prod.telemetry_derived.baseline_active_users_aggregates_v1
And associated view: 
- moz-fx-data-shared-prod.telemetry.baseline_active_users_aggregates
* [DENG-7860](https://mozilla-hub.atlassian.net/browse/DENG-7860)
[DENG-7860]: https://mozilla-hub.atlassian.net/browse/DENG-7860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-7860):  Create baseline_active_users_aggregates_v1

dags.yaml
Adds an Airflow triage note to `bqetl_public_data_json` DAG
=> Update triage instructions for bqetl_public_data_json DAG

sql_generators/usage_reporting/__init__.py, sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja
This introduced a new template to the usage_reporting generator for creating an usage_reporting_active_users view for all the products (a step towards reproducing KPI reporting table).
=> feat(DENG-7869): add usage_reporting_active_users template to usage_reporting generator

sql/moz-fx-data-shared-prod/monitoring_derived/looker_dashboard_load_times_v1/metadata.yaml
Fixes the failing airflow task: https://workflow.telemetry.mozilla.org/dags/bqetl_monitoring/grid?search=bqetl_monitoring&dag_run_id=scheduled__2025-02-19T02%3A00%3A00%2B00%3A00&task_id=monitoring_derived__looker_dashboard_load_times__v1&tab=logs
=> Fix looker_dashboard_load_times_v1 arguments

bigquery_etl/cli/query.py, bigquery_etl/metadata/parse_metadata.py, bigquery_etl/metadata/validate_metadata.py, tests/cli/test_cli_metadata.py
- This PR adds a check to ensure new tables have column descriptions enforced (this check can be turned off if needed).
- When someone runs `./bqetl query create` it will now add a new key to the metadata.yaml file called: `require_column_descriptions=True`
- If this is left as True, when the metadata validation step runs, it will check to ensure column descriptions are on all tables where this is set to True.  If you set to False, it will not run this check.
- Note: In tables where this is not specified, the default value for require_column_descriptions is False
* [DENG-7908](https://mozilla-hub.atlassian.net/browse/DENG-7908)
[DENG-7908]: …
=> Add logic to enforce column descriptions on new tables

bigquery_etl/backfill/parse.py, bigquery_etl/backfill/utils.py, bigquery_etl/backfill/validate.py, bigquery_etl/cli/backfill.py, sql/moz-fx-data-shared-prod/telemetry_derived/core_clients_last_seen_v1/backfill.yaml, tests/backfill/test_dir_depends_on_past/backfill.yaml, tests/backfill/test_dir_depends_on_past/metadata.yaml, tests/backfill/test_parse_backfill.py, tests/backfill/test_validate_backfill.py, tests/cli/test_cli_backfill.py
Adds managed backfill support for `depends_on_past=True` tables by copying the previous partition (month or day) to the staging table.  This allows backfilling of `clients_last_seen` type tables.  A check was added to look for backfill end dates in the past to attempt to make users think about data continuity issues but it doesn't cover everything.
Tables with null date_partition_parameter like `clients_first_seen` still aren't supported because there isn't a "previous" partition.  A lot of these can be recreated in a single query (e.g. `is_init`) so I don't know if they need managed backfill support but that can be added later if needed.
Also added a backfill for core_clients_last_seen since it's a small table to test the airflow run with.  The backfill won't be set to completed so it …
=> [DENG-3656] Support depends on past in managed backfills

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users_aggregates/view.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/schema.yaml
This PR creates the new table: 
- moz-fx-data-shared-prod.firefox_desktop_derived.baseline_active_users_aggregates_v1
- moz-fx-data-shared-prod.firefox_desktop.baseline_active_users_aggregates
* [DENG-7860](https://mozilla-hub.atlassian.net/browse/DENG-7860)
[DENG-7860]: https://mozilla-hub.atlassian.net/browse/DENG-7860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DENG-7860: Create baseline_active_users_aggregates_v1

sql/moz-fx-data-shared-prod/monitoring/structured_missing_columns/view.sql, sql/moz-fx-data-shared-prod/udf/remove_label_from_metric_path/metadata.yaml, sql/moz-fx-data-shared-prod/udf/remove_label_from_metric_path/udf.sql
This bug showed up in https://bugzilla.mozilla.org/show_bug.cgi?id=1949480 where the column name of a labeled metric looks like `metrics.labeled_counter.update.can_use_bits_notify.CanUseBits` where `CanUseBits` is one of the labels and the actual column name would be `metrics.labeled_counter.update_can_use_bits_notify` which is a struct with key and value fields.  The view currently looks for a column named `CanUseBits` so `column_exists_in_schema` will be false even if `update_can_use_bits_notify` is in the schema.
Another way to do this is to remove the labels from the paths in `monitoring_derived.structured_missing_columns_v1` but I'm not sure if there's value in having the label there.
Also I'm not sure what the proposed "labeled labeled counters" will look like and if this will work …
=> [DENG-7933] Ignore labels in column_exists_in_schema check

sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.query.sql.jinja, sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.schema.yaml.jinja
This field is needed to accurately determine os version on Windows.
=> feat: add windows_build_number to usage_reporting_clients_daily template

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
=> feat: add desktop_dau_distribution_id_history_v1 as one of the sources for distribution_id to baseline_active_users

sql/moz-fx-data-shared-prod/firefox_desktop_derived/baseline_active_users_aggregates_v1/backfill.yaml
depends on: https://github.com/mozilla/bigquery-etl/pull/7099
=> feat: add backfill entry for firefox_desktop_derived.baseline_active_users_aggregates_v1

bqetl_project.yaml
=> feat: add beta channels to fenix and firefox_ios usage_reporting configuration

sql/moz-fx-data-shared-prod/external_derived/population_v1/query.py
This PR:
- cleans up the comments
- changes the column "last updated" in the table to be the date that the DAG actually ran on, not the logical dag date (which is 1 year prior). 
- It also makes sure the year it pulls data for is the next year, not the year of the logical dag date (for example, when it runs for the logical dag date of 2024-02-15, it will now pull data for 2025, not 2024, which is the desired behavior)
- Adds more countries to the list of countries we pull population data for
* [DENG-7787](https://mozilla-hub.atlassian.net/browse/DENG-7787)
[DENG-7787]: https://mozilla-hub.atlassian.net/browse/DENG-7787?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
=> fix(DENG-7787): Clean up comments, change last updated date logic

bigquery_etl/shredder/config.py, bigquery_etl/shredder/delete.py
This adds a temporary workaround for Relay table that has `fxa_id` in event extras.
I initially wanted to go with https://mozilla-hub.atlassian.net/browse/DENG-7964 first to move the field to a regular metric, but this might require updates to glean_parser first.
This isn't great, but I haven't found a simpler way. I tried putting an expression to select any `fxa_id` key in `DeleteTarget.field`, but this resulted in correlated subquery which BQ does not support.
I tested this by generating the query locally with `script/shredder_delete --dry_run --start-date=2024-01-01 --end-date=2025-03-02 --only=relay_backend_stable.events_v1` and running it on copied tables.
=> DENG-7965 - Add custom temporary support for relay_backend.events in Shredder

sql/moz-fx-data-shared-prod/telemetry/active_users_aggregates/view.sql
default to null as it resents the meaning of the value than other (other may imply another meaning rather than lack of partnership)
=> feat: add dt to partnership mapping and default to null

sql/moz-fx-data-shared-prod/fxci/task_runs/view.sql, sql/moz-fx-data-shared-prod/fxci/tasks/view.sql, sql/moz-fx-data-shared-prod/fxci/worker_metrics/view.sql, sql/moz-fx-data-shared-prod/fxci_derived/task_runs_v1/schema.yaml, sql/moz-fx-data-shared-prod/fxci_derived/tasks_v1/schema.yaml, sql/moz-fx-data-shared-prod/fxci_derived/tasks_v2/metadata.yaml, sql/moz-fx-data-shared-prod/fxci_derived/tasks_v2/schema.yaml
I changed the schema of the tasks table, so a `v2` was necessary. I'll attempt to backfill the data from the old `v1` table later. I also added some missing user facing views for tasks and task_runs.
=> Add metadata.yml for tasks_v2 + add missing user facing views

sql_generators/funnels/configs/android_onboarding.toml
Fixes change from https://github.com/mozilla/bigquery-etl/pull/7069.  [Query is failing](https://workflow.telemetry.mozilla.org/dags/bqetl_generated_funnels/grid?dag_run_id=scheduled__2025-02-27T05%3A00%3A00%2B00%3A00&task_id=fenix_derived__android_onboarding__v1&tab=logs) with `Column client_id in USING clause not found on right side of join at [45:12]`.  This query is in the dry run skip list because it takes a long time to dry run so it wasn't caught
=> Fix join in android_onboarding funnel

bigquery_etl/query_scheduling/templates/airflow_dag.j2
When I added support for table sensors in #5039 I chose 8 hours as the default timeout so that when combined with the common DAG-level defaults of 2 retries it would result in the sensor waiting for ~24 hours total before giving up and failing entirely.  However, it turns out I was wrong about sensors retrying when they hit their timeout, as that behavior was [changed way back in Airflow 2.2.0](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#if-a-sensor-times-out-it-will-not-retry) so that sensors don't retry when they hit their timeout.
So to get the original intended behavior of table sensors waiting for up to 24 hours by default this PR is increasing the table sensors' default timeout to 24 hours.
* [Bug …
=> fix: Increase table sensor timeout defaults to 24 hours

sql/moz-fx-data-shared-prod/telemetry/cohort_weekly_statistics/view.sql, sql/moz-fx-data-shared-prod/telemetry/cohort_weekly_statistics_by_app/view.sql, sql/moz-fx-data-shared-prod/telemetry/cohort_weekly_statistics_by_app_channel_version/view.sql
This PR creates 3 new views that track retention at a weekly level.
The first view tracks it at the grain of: app, channel, and Firefox version.
- `moz-fx-data-shared-prod.telemetry.cohort_weekly_statistics_by_app_channel_version`
The second view tracks it at the grain of normalized app name only.
- `moz-fx-data-shared-prod.telemetry.cohort_weekly_statistics_by_app`
The second view tracks it at the grain of all available attributes in rolling_cohorts_v2:
- `moz-fx-data-shared-prod.telemetry.cohort_weekly_statistics`
* [DENG-7970](https://mozilla-hub.atlassian.net/browse/DENG-7970)
[DENG-7970]: https://mozilla-hub.atlassian.net/browse/DENG-7970?atlOrigin=eyJpIjoiNWRk …
=> feat(DENG-7970): Add cohort_weekly_statistics views

sql/moz-fx-data-shared-prod/fxci_derived/task_runs_v1/schema.yaml
Follow-up to https://github.com/mozilla/bigquery-etl/pull/7094.  These fields are already set to nullable in the table and changing to required isn't supported so this is [failing table deploys](https://workflow.telemetry.mozilla.org/dags/bqetl_artifact_deployment/grid?dag_run_id=manual__2025-02-28T18%3A24%3A04.991678%2B00%3A00&task_id=publish_new_tables&tab=logs).  Error is `Provided Schema does not match Table moz-fx-data-shared-prod:fxci_derived.task_runs_v1. Field started has changed mode from NULLABLE to REQUIRED`
@ahal is it ok to keep these as nullable?  Otherwise we would need to recreate the table
=> Change nullable columns in fxci.task_runs

sql/moz-fx-data-shared-prod/telemetry/cohort_weekly_statistics/view.sql
This PR removes the column from the view so that we can put it instead in Looker so the end user can calculate at different grains and get the correct result.
* [DENG-7970](https://mozilla-hub.atlassian.net/browse/DENG-7970)
[DENG-7970]: https://mozilla-hub.atlassian.net/browse/DENG-7970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-7970): Remove column, move % retained calc to Looker for flexibility

sql/moz-fx-data-shared-prod/accounts_db_external/fxa_recovery_phones_v1/schema.yaml, sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_recovery_phones_v1/schema.yaml
The `schema.yaml` files for `fxa_recovery_phones_v1` tables added in #7104 had the wrong type for the `uid` columns.  This fixes that.
* [Bug 1951400](https://bugzilla.mozilla.org/show_bug.cgi?id=1951400): Airflow task bqetl_artifact_deployment.publish_new_tables failing for 3/1 - 3/3
* https://github.com/mozilla/bigquery-etl/pull/7104
=> fix: Correct type of `fxa_recovery_phones_v1.uid` columns (bug 1951400)

sql/moz-fx-data-shared-prod/org_mozilla_focus_beta_derived/additional_deletion_requests_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_focus_derived/additional_deletion_requests_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_focus_nightly_derived/additional_deletion_requests_v1/metadata.yaml
Per policy discussion in https://mozilla-hub.atlassian.net/browse/DSRE-1799, the retention of deletion requests should be equal to the longest retained data subject to the deletion request.  That would be 760 for pings https://github.com/mozilla/probe-scraper/blob/cf4abcf2e94e1453315f44e2b2d45ab1ba8a29d2/repositories.yaml#L1336-L1342 and eventually 775 for derived data
cc @akkomar 
* DSRE-1799
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/DENG-7726)
=> Set additional_deletion_requests_v1 retention to 775 days

sql/moz-fx-data-shared-prod/phabricator_metrics/dataset_metadata.yaml
See https://mozilla-hub.atlassian.net/browse/DENG-7966
Requires https://github.com/mozilla-it/global-platform-admin/pull/2647 for the group to be created.
=> DENG-7966 Set phabricator-metrics/external workgroup access on phabricator_metrics dataset

bigquery_etl/glam/templates/histogram_bucket_counts_v1.sql, bigquery_etl/glam/templates/macros.sql
This moves the static combos cross join to after the aggregation step so the things that get cross joined are the aggregated buckets instead of the entire histograms.
[Comparing the results](https://sql.telemetry.mozilla.org/queries/106039/source), most buckets are the same so I feel confident that the math works but there are some buckets where they don't match which might be from clients not being included from either side.  I'm still trying to figure out how that's happening.
Query improvements are suspiciously good (release sample id 0 goes from 4400 slot hours to 78) so I'm still kind of skeptical:
old or new query | channel | sample id | job id | bytes processed | run time | slot hours | shuffled | spilled to disk
-- | -- | -- | -- | -- | -- | -- | -- | --
old | release | 0 | …
=> Move static_combos to end of glam histogram buckets query

bigquery_etl/shredder/config.py
This PR adds 2 new tables to Shredder:
- moz-fx-data-shared-prod.telemetry_derived.fx_accounts_linked_clients_staging_v1
- moz-fx-data-shared-prod.telemetry_derived.fx_accounts_linked_clients_v1
* [DENG-7982](https://mozilla-hub.atlassian.net/browse/DENG-7982)
[DENG-7982]: https://mozilla-hub.atlassian.net/browse/DENG-7982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DENG-7982 - add 2 new tables to shredder config

sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_v1/script.sql
This PR fixes the logic used in the merge statement for the linkage_last_seen_date column.  The old logic wasn't working correctly for new rows (it would insert a null for linkage last seen date for a newly added client ID / linked client ID, instead of the desired date).
* [DENG-7900](https://mozilla-hub.atlassian.net/browse/DENG-7900)
[DENG-7900]: https://mozilla-hub.atlassian.net/browse/DENG-7900?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DENG-7900): Adjust linkage_last_seen_date logic

sql/moz-fx-data-shared-prod/monitoring_derived/looker_dashboard_load_times_v1/query.py
Adds a missing `dashboard_page_session` field to the Looker API query
=> Add missing dashboard_page_session field to looker_dashboard_load_times

sql/moz-fx-data-shared-prod/telemetry/fx_accounts_linked_clients_ordered/view.sql
This PR creates the new view:
- moz-fx-data-shared-prod.telemetry.fx_accounts_linked_clients_ordered
* [DENG-7987](https://mozilla-hub.atlassian.net/browse/DENG-7987)
[DENG-7987]: https://mozilla-hub.atlassian.net/browse/DENG-7987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-7987): Create fx_accounts_linked_clients_ordered

sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.query.sql
This change is to fix the location of the isp column in the last_seen view. Making this change as currently this results in dry run failure for focus_nightly, focus_beta and klar.
blocks: https://github.com/mozilla/bigquery-etl/pull/7072
=> fix: isp column appears to be out of order between last_seen and daily table for some products

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.metadata.yaml
event_monitoring_aggregates runs at the same time as desktop events stream in the backfill-2 project.  The events stream query failed on the first attempt yesterday due to memory so running them on different projects should give each query more resources.
backfill 3 and 4 were changed to on-demand in https://github.com/mozilla-it/global-platform-admin/pull/2672 and I just ran a query in them to verify that it worked.
* DENG-8033
=> [DENG-8033] Run event_monitoring_aggregates in backfill-3

sql/moz-fx-data-shared-prod/crash_ping_ingest_external/dataset_metadata.yaml
https://mozilla-hub.atlassian.net/browse/DSRE-1900?focusedCommentId=1023642
This is going to be written to from taskcluster via tasks not owned by DE, see the above ticket for details.
Requires https://github.com/mozilla-services/cloudops-infra/pull/6313.
* DSRE-1900
=> chore: add crash_ping_ingest_external dataset

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql, sql_generators/mobile_kpi_support_metrics/templates/active_users.view.sql, sql_generators/usage_reporting/__init__.py, sql_generators/usage_reporting/templates/composite_active_users.view.sql.jinja, sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja, sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates.view.sql.jinja
Will convert from draft PR once we agree on what the filter should be for the union.
blocked by: https://github.com/mozilla/bigquery-etl/pull/7157
=> feat(): add composite active users to usage reporting generator

sql/moz-fx-data-shared-prod/monitoring/missing_namespaces_and_document_types/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring/missing_namespaces_and_document_types/view.sql
This view is based on the derived Looker view in https://github.com/mozilla/looker-spoke-default/blob/main/monitoring/views/missing_namespaces_and_document_types.view.lkml
Having this as a BigQuery view will allow us to set alerts in Bigeye
=> Add view for missing namespaces and document types

dags.yaml, sql/moz-fx-data-shared-prod/external/chrome_extensions/view.sql, sql/moz-fx-data-shared-prod/external_derived/chrome_extensions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/external_derived/chrome_extensions_v1/query.py, sql/moz-fx-data-shared-prod/external_derived/chrome_extensions_v1/schema.yaml
This PR pulls Chrome extension data from the Chrome webstore and loads into the following table and corresponding view:
- moz-fx-data-shared-prod.external_derived.chrome_extensions_v1
- moz-fx-data-shared-prod.external.chrome_extensions
It also creates a new DAG `bqetl_chrome_extensions_scraper` that only runs weekly since this data doesn't change very often.
* [DENG-7788](https://mozilla-hub.atlassian.net/browse/DENG-7788)
[DENG-7788]: https://mozilla-hub.atlassian.net/browse/DENG-7788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-7788): Create external_derived.chrome_extensions_v1

sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/query.sql
Adjusting the overactive clients threshold. This fixed the `Resources exceeded during query execution` and will unblock the Airflow task
=> Adjust overactive clients threshold for sponsored_tiles_clients_daily_v1

sql/moz-fx-data-shared-prod/telemetry/fx_accounts_linked_clients/view.sql, sql/moz-fx-data-shared-prod/telemetry/fx_accounts_linked_clients_ordered/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_ordered_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_ordered_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_ordered_v1/schema.yaml
This PR physicalizes a view that was a bit slow and makes it a table that over-writes daily in full.
It also adds 2 new columns (last seen date for each client ID)
Note - the reason it does a full overwrite is because one of the tables is built on top of a merge statement, so it's not built incrementally.
New table:
- `moz-fx-data-shared-prod.telemetry_derived.fx_accounts_linked_clients_ordered_v1`
Updated view now does a direct pull from the new table:
- `moz-fx-data-shared-prod.telemetry.fx_accounts_linked_clients_ordered`
* [DENG-7987](https://mozilla-hub.atlassian.net/browse/DENG-7987)
[DENG-7987]: https://mozilla-hub.atlassian.net/browse/DENG-7987?atlOrigin=eyJ …
=> feat(DENG-7987): Create fxa_accounts_linked_clients_ordered_v1

bigquery_etl/shredder/config.py, sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_ordered_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_linked_clients_v1/metadata.yaml
This PR adds a new table to shredder
- `moz-fx-data-shared-prod.telemetry_derived.fx_accounts_linked_clients_ordered_v1`
It also updates labels on 2 tables:
* It removes the incremental labels on both `fx_accounts_linked_clients_v1` and `fx_accounts_linked_clients_ordered_v1`
* It adds table_type: client_level label to `fx_accounts_linked_clients_ordered_v1`
(I already redeployed the tables with the updated labels, this is just making the files match)
* [DENG-7982](https://mozilla-hub.atlassian.net/browse/DENG-7982)
[DENG-7982]: https://mozilla-hub.atlassian.net/browse/DENG-7982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …
=> feat(DENG-7982): Add new table fx_accounts_linked_clients_ordered_v1 to shredder

bqetl_project.yaml
Adding focus_android and focus_ios to the usage_reporting generator.
=> feat(DENG-7984): add focus_android and focus_ios to usage_reporting generator configuration

dags.yaml, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_and_version_v1/checks.sql, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_and_version_v1/metadata.yaml, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_v1/checks.sql, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_v1/metadata.yaml
This PR is a follow up to [PR-7197](https://github.com/mozilla/bigquery-etl/pull/7197)
* It renames the DAG from `bqetl_google_play_store_developer_reporting_api_data` -> `bqetl_google_play_store`
* It also removes the 2 checks.sql files since they always fail when running via a query.py with passed in parameters.
=> feat(DENG-7931) Minor tweaks

dags.yaml, sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.metadata.yaml.jinja, sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.metadata.yaml.jinja, sql_generators/usage_reporting/templates/usage_reporting_clients_first_seen_v1.metadata.yaml.jinja, sql_generators/usage_reporting/templates/usage_reporting_clients_last_seen_v1.metadata.yaml.jinja
For a less cluttered job and avoid mixing with more broader glean related materialization tasks.
=> feat: add a new bqetl_usage_reporting DAG and schedule usage_reporting related queries in it.

sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_and_version_v1/query.py, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_and_version_v1/schema.yaml
This PR adds a new column, `nbr_distinct_users` to the table:
- moz-fx-data-shared-prod.google_play_store_derived.slow_startup_events_by_startup_type_and_version_v1
=> feat(DENG-7931): Add # distinct users to slow_startup_events_by_startup_type_and_version

sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.query.sql, sql_generators/glean_usage/templates/event_monitoring_live_v1.materialized_view.sql
The [current event_monitoring_live definition](https://github.com/mozilla/bigquery-etl/blob/generated-sql/sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/event_monitoring_live_v1/materialized_view.sql) doesn't work because materialized views don't support array and struct constructors (added to the view in #6887).  This restructures the query so events from each ping are unnested before unioning them to avoid the initial problem.  The same thing is done to `event_monitoring_aggregates` for consistency and because I found this uses 15% less slot time.
I tested equivalence by full joining the outputs of the before and after which looks fine.  `Mozilla VPN` is the normalized name of multiple apps so it messes up the join a bit but it seems correct.
* DENG-6990
**Reviewer, please …
=> [DENG-6990] Fix/optimize event monitoring live and aggregates

bqetl_project.yaml
=> feat: Disable monitoring (Bigeye metrics) for focus_ios, klar_ios, focus_android, and klar_android (telemetry changes).

sql/moz-fx-data-shared-prod/cloudflare_derived/device_usage_v1/query.py
This PR does 3 things:
- The API changed its URL path, so this updates to the new URL path
- With the change Cloudflare made, they started also sending 2 days worth of data for the time period instead of only 1 like they used to, so to deal with this, I make it take the 1st day of data only (which is what it was doing before)
- This fixes the error handling issue so that if there are errors, it still can write them to the database (had an incorrect timestamp data type instead of date data type before)
- Lastly, we added logic to raise an error if there are more than 5 errors in the whole job, even after it writes the error rows to BQ
=> fix(Cloudflare Device API): Update cloudflare device URL & error handling

sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v2/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_daily_statistics_v2/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_weekly_statistics_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/cohort_weekly_statistics_v1/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v2/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/rolling_cohorts_v2/schema.yaml
This PR adds a new column "play_store_attribution_install_referrer_response" to 3 tables:
- moz-fx-data-shared-prod.telemetry_derived.rolling_cohorts_v2 
- moz-fx-data-shared-prod.telemetry_derived.cohort_weekly_statistics_v1
- moz-fx-data-shared-prod.telemetry_derived.cohort_daily_statistics_v2
=> Add play store install referrer response to rolling_cohorts_v2 & cohort weekly statistics

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/query.sql
Adds initialization SQL for `newtab_interactions_hourly_v1`. Because managed backfills aren't currently fully supported for hourly tables, this is the easiest way to initially backfill this table.
* [AD-681](https://mozilla-hub.atlassian.net/browse/AD-681)
[AD-681]: https://mozilla-hub.atlassian.net/browse/AD-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add initialization SQL for newtab_interactions_hourly_v1

sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_version_and_device_v1/query.py, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_version_and_device_v1/schema.yaml
This PR adds the column "version_code" to the below new table:
- moz-fx-data-shared-prod.google_play_store_derived.slow_startup_events_by_startup_type_version_and_device_v1
=> fix(DENG-7931): Add version_code column to new table

sql/moz-fx-data-shared-prod/addon_moderations_derived/cinder_decisions_raw_v1/schema.yaml
This PR changes the TYPE of the entity_id from INTEGER to STRING. Since this is an ID, it should be a string and immutable. I caught this error when I was working on the DSA report due in February, noticed the type when I was reviewing the data that was available.
* DENG-8156
* DSRE-XXXX
=> change type of entity_id from INTEGER to STRING

sql/moz-fx-data-shared-prod/accounts_db_external/fxa_carts_v1/query.sql, sql/moz-fx-data-shared-prod/accounts_db_external/fxa_carts_v1/schema.yaml, sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_carts_v1/query.sql, sql/moz-fx-data-shared-prod/accounts_db_nonprod_external/fxa_carts_v1/schema.yaml
These queries are going to break once https://github.com/mozilla/fxa/pull/18559 rolls out to stage/production.  This removes the column.  @akkomar r?
=> fix carts table

sql/moz-fx-data-shared-prod/monitoring_derived/shredder_targets_v1/query.py
There are some tables that are derived from GCS files so they should be skipped
* https://bugzilla.mozilla.org/show_bug.cgi?id=1956622
=> Bug 1956622 - Ignore GCS sources in shredder targets lineage

bigquery_etl/shredder/config.py
This PR adds 3 new tables to shredder: 
- moz-fx-data-shared-prod.ltv_derived.firefox_desktop_new_profile_ltv_v1
- moz-fx-data-shared-prod.ltv_derived.fenix_new_profile_ltv_v1
- moz-fx-data-shared-prod.ltv_derived.firefox_ios_new_profile_ltv_v1
* [DENG-8171](https://mozilla-hub.atlassian.net/browse/DENG-8171)
[DENG-8171]: https://mozilla-hub.atlassian.net/browse/DENG-8171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8171): Add 3 new tables to shredder

sql/moz-fx-data-shared-prod/monitoring/payload_bytes_error_all/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/query.sql
This moves the channel parsing for errors from the schema errors query to the `payload_bytes_error_all` authorized view which lets us get channel info for all errors and not just schema errors.  
This also removes stub installer parse errors from the schema errors table (added in https://github.com/mozilla/bigquery-etl/pull/7015) because I found that it's confusing to have different exception classes in the graphs and stub installer errors show up in their own graph in the dashboard anyway.
Needed to grant the circleci account access to the gcs bucket with the JS libs: https://github.com/mozilla-services/cloudops-infra/pull/6343  I manually did it for now
=> Move channel logic from schema_error_counts to payload_bytes_error_all

script/glam/generate_glean_sql
The glam `daily_*` tasks use a lot of memory and occasionally get OOM'd.  I found that it's because the sql generation runs a two python processes per stable table of the target app so fenix spawns 64 processes and each uses a bit of memory.  This changes it to run for 2 tables at a time so max 4 processes.
Memory usage running in a container:
First bump is with 2 table concurrency (570MB), second is 3 (900MB), and last two are unlimited (3GB and 6.5GB).
* DENG-8051
* https://bugzilla.mozilla.org/show_bug.cgi?id=1957121
=> [DENG-8051] Limit concurrency of glam sql generation

sql/moz-fx-data-shared-prod/external/macroeconomic_indices/metadata.yaml, sql/moz-fx-data-shared-prod/external/macroeconomic_indices/view.sql, sql/moz-fx-data-shared-prod/external_derived/macroeconomic_indices_v1/metadata.yaml, sql/moz-fx-data-shared-prod/external_derived/macroeconomic_indices_v1/query.py, sql/moz-fx-data-shared-prod/external_derived/macroeconomic_indices_v1/schema.yaml
This PR:
- creates the table `macroeconomic_indices_v1` in `external_derived`
- creates the view `macroeconomic_indices` in `external`
Once these have been created and downstream dependencies updated to reference this new location, we'll remove the table and view from reference_derived & reference.
=> chore: Create macroeconomic_indices_v1 in external_derived

sql/moz-fx-data-shared-prod/fenix/crash/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_crashreporter/crash/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop/crash/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop/desktop_crashes/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_fenix/crash/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_fenix_nightly/crash/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_fennec_aurora/crash/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_firefox/crash/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_firefox_beta/crash/metadata.yaml, sql_generators/desktop_crashes/__init__.py
Similar to https://github.com/mozilla/bigquery-etl/pull/7234, this gives read access to the crash ping stable tables.  The stable views are authorized so that the stable table permissions don't need to be changed.
* DENG-8189
=> [DENG-8189] Give read access for crash pings to crash-ping-ingest

bqetl_project.yaml, sql_generators/experiment_monitoring/templates/templating.yaml
We want to add accounts_cirrus to include in the bigquery
=> feat(nimbus): Add accounts cirrus app name

sql/moz-fx-data-shared-prod/external_derived/chrome_extensions_v1/query.py
This PR replaces NOT FOUND strings with nulls in BigQuery when information isn't available about certain aspects of an extension.
* [DENG-8221](https://mozilla-hub.atlassian.net/browse/DENG-8221)
[DENG-8221]: https://mozilla-hub.atlassian.net/browse/DENG-8221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update to replace NOT FOUND with null

sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/schema.yaml
This adds more projects and materialized view stats to the jobs_by_organization derived table.  These projects are the most expensive one that are currently missing ([comparison with billing data](https://sql.telemetry.mozilla.org/queries/106900/source)) so including them should gives us a more complete view of bigquery spend with this table.
For change control, the projects being added are:
- moz-fx-glam-prod
- moz-fx-glam-nonprod
- moz-fx-data-sumo-prod
- moz-fx-data-sumo-nonprod
- moz-fx-mozsocial-dw-prod
* DENG-8214
=> [DENG-8214] Add additional projects and fields to jobs_by_organization

dags.yaml, sql/moz-fx-data-shared-prod/external_derived/chrome_extensions_v1/query.py, sql/moz-fx-data-shared-prod/external_derived/chrome_extensions_v1/schema.yaml
This PR adds the new column `category` to the table:
- moz-fx-data-shared-prod.external_derived.chrome_extensions_v1
It also changes the DAG from running weekly to daily
* [DENG-8090](https://mozilla-hub.atlassian.net/browse/DENG-8090)
[DENG-8090]: https://mozilla-hub.atlassian.net/browse/DENG-8090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8090): Add category column to chrome_extensions_v1

sql/moz-fx-data-shared-prod/fenix_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/focus_android_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/focus_ios_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
depends on: https://github.com/mozilla/bigquery-etl/pull/7146
=> feat: add backfill.yaml for usage_reporting_active_users_aggregates fx ios, fenix, desktop, focus android and ios

sql/moz-fx-data-shared-prod/org_mozilla_fenix/broken_site_report/metadata.yaml
Permission issues while deploying this view started on 2025-04-04 that seem to be related to this being an authorized view.  View deploys started working again a couple hours ago but I don't know why the issue started and stopped.  Removing the authorization should remove this point of failure.  The views this references are authorized so this one shouldn't need to be authorized
* https://bugzilla.mozilla.org/show_bug.cgi?id=1958887
=> Bug 1958887 - Remove view authorization for fenix.broken_site_report

sql_generators/experiment_monitoring/templates/experiment_search_aggregates_v1/query.sql
Fixes https://workflow.telemetry.mozilla.org/dags/bqetl_experiments_daily/grid?dag_run_id=scheduled__2025-04-04T03%3A00%3A00%2B00%3A00&task_id=telemetry_derived__experiment_search_aggregates__v1
https://bugzilla.mozilla.org/show_bug.cgi?id=1958883
The  `experiment_search_aggregates_v1` was failing due to metadata complexity being to large. This query removes applications that don't have any search metrics defined. I tested the generated query in BigQuery and it ran successfully. 
The only impact this should have is that instead of showing 0 values for search metrics on the experiment monitoring dashboard for these applications, it will show no data at all. This should be fine.
**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/blob/main/.github/reviewer_chec …
=> [Bug 1958883] Filter out applications in experiment search monitoring that don't have search metrics defined

sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_items_daily_v1/query.sql
This fix relates to https://github.com/mozilla/bigquery-etl/pull/7257
The filter `section IS NOT NULL` is not needed was accidentally applied. The `section` attribute is a very recent addition to the `newtab` ping and does not apply to older FF versions
=> Removing unwanted section filer

sql/moz-fx-data-shared-prod/telemetry/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/clients_last_seen_v2/metadata.yaml, tests/data/test_sql/moz-fx-data-test-project/test/non_incremental_query_v1/metadata.yaml, tests/metadata/test_parse_metadata.py
This is a follow up to https://github.com/mozilla/telemetry-airflow/pull/2169 where all TAAR DAGs were removed. There were some references to these DAGs and related workgroup left in this repo.
Blocks https://github.com/mozilla-services/cloudops-infra/pull/6356
https://mozilla-hub.atlassian.net/browse/DENG-7245
=> DENG-7245: Remove TAAR references

sql/mozfun/norm/glean_client_info_attribution/README.md, sql/mozfun/norm/glean_client_info_attribution/metadata.yaml, sql/mozfun/norm/glean_client_info_attribution/udf.sql, sql_generators/stable_views/__init__.py
This changes the stable views to mirror glean attribution and distribution metrics into `client_info` per [this doc](https://docs.google.com/document/d/1TIZhpBeZcJSEnIZJwj0Cj9saL2Tfs0X6oi_4gFU35eM/edit?tab=t.0#heading=h.dc06cblplbtl).
The metrics are `metrics.object.glean_attribution_ext` and `metrics.object.glean_distribution_ext` and they get added to client info as `client_info.attribution.ext` and `client_info.distribution.ext` as JSON fields.  If the metrics don't exist in the schema, the fields are still added as nulls.
@chutten can you confirm the field names and structure is what you expect?
* https://bugzilla.mozilla.org/show_bug.cgi?id=1957476
=> Bug 1957476 - Add attr/dist metrics to client_info in stable views

pyproject.toml, sql_generators/usage_reporting/usage_reporting.py, tests/sql_generators/usage_reporting/test_usage_reporting.py
Thanks @ogzillla for your input to simplify the import logic.
To verify these changes locally:
```shell
venv/bin/python -m pip install --upgrade pip
venv/bin/python -m pip install -e .
venv/bin/python -m pytest -W ignore::DeprecationWarning tests/sql_generators/usage_reporting/test_usage_reporting.py
```
Both generation via the ./bqetl generate command and when calling the module directly.
=> fix: remove the additional custom import logic from usage_reporting and patch correct object in unit tests

sql/bigconfig.yml, sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.bigconfig.yaml.jinja, sql_generators/usage_reporting/templates/usage_reporting_clients_daily_v1.bigconfig.yaml.jinja, sql_generators/usage_reporting/templates/usage_reporting_clients_first_seen_v1.bigconfig.yaml.jinja, sql_generators/usage_reporting/templates/usage_reporting_clients_last_seen_v1.bigconfig.yaml.jinja
This is to avoid creating metrics for each column for freshness and volume.
=> feat: use table metrics for freshness and volume, and use table deployments

bqetl_project.yaml
Subscription platform backend telemetry is added in https://github.com/mozilla/probe-scraper/pull/885
This will make their events_stream tables consistent with FxA.
=> Store metrics as struct in SubPlat backend's events_stream

sql/moz-fx-data-shared-prod/external/chrome_extensions/view.sql
This PR adds 3 new columns to the view `mozdata.external.chrome_extensions` that help normalize the scraped strings into an expected format.  The 3 new columns are: 
- star_rating_numeric
- number_of_ratings_numeric
- number_of_users_numeric
* [DENG-8069](https://mozilla-hub.atlassian.net/browse/DENG-8069)
[DENG-8069]: https://mozilla-hub.atlassian.net/browse/DENG-8069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8069): Add normalized columns

bigquery_etl/cli/monitoring.py, sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/releases_v1/bigconfig.yml
Previously only metrics defined under the `tag_deployments` would be considered when determining if any of the default metrics should be added to the configuration. This change ensures that metrics defined under `table_deployments` are also considered.
=> feat(): include bigconfig table deployments when setting default metrics

sql_generators/glean_usage/templates/event_flow_monitoring_aggregates_v1.script.sql
https://bugzilla.mozilla.org/show_bug.cgi?id=1960649
Airflow was failing due to some clients sending to many events that exceeded the limit of what `ARRAY_AGG` can do (10k+ events). This adds a limit to how many events are being aggregated
=> [Bug 1960649] Limit number of events that are aggregated in event_flow_monitoring_aggregates

sql/moz-fx-data-shared-prod/org_mozilla_fenix/nimbus_recorded_targeting_context/view.sql, sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/nimbus_recorded_targeting_context_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/nimbus_recorded_targeting_context_v1/query.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox/nimbus_recorded_targeting_context/view.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/nimbus_recorded_targeting_context_v1/metadata.yaml, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/nimbus_recorded_targeting_context_v1/query.sql
This PR adds two queries — a query to obtain the previous day's Nimbus recorded targeting contexts for Fenix, and an equivalent one for Firefox iOS.
* [EXP-4608](https://mozilla-hub.atlassian.net/browse/EXP-4608)
[EXP-4608]: https://mozilla-hub.atlassian.net/browse/EXP-4608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add nimbus_recorded_targeting_context queries for fenix and firefox ios

bigquery_etl/query_scheduling/dag.py, dags.yaml, tests/data/dags/python_script_test_dag, tests/data/dags/simple_test_dag, tests/data/dags/test_dag_duplicate_dependencies, tests/data/dags/test_dag_external_check_dependency, tests/data/dags/test_dag_external_dependency, tests/data/dags/test_dag_with_bigquery_table_sensors, tests/data/dags/test_dag_with_check_dependencies, tests/data/dags/test_dag_with_check_table_dependencies, tests/data/dags/test_dag_with_dependencies, tests/data/dags/test_dag_with_secrets, tests/data/dags/test_public_data_json_dag
Task runs sometime overlap due to DENG-8332 which can cause failures.  This changes the dag to run at most one instance of each task.
This also adds `"max_active_tis_per_dag": None` to the default args of every existing dag. `None` is the default value so I think that should be fine 
* https://bugzilla.mozilla.org/show_bug.cgi?id=1960934
* DENG-8332
=> Bug 1960934 - Limit materialized_view_refresh task concurrency

sql_generators/glean_usage/event_monitoring_live.py
event monitoring queries depends on the experiments in the `ping_info` field.  The newtab-content ping has events in it but uses the glean min ping schema that doesn't have `ping_info` so the query is failing.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1961183
=> Bug 1961183 - Skip glean min pings in event_monitoring queries

sql/moz-fx-data-shared-prod/org_mozilla_fenix_derived/nimbus_recorded_targeting_context_v1/query.sql
This PR fixes an issue in which the nimbus_recorded_targeting_context_v1 query selected two pieces of data with the same column name.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1961168 
=> Fix 1961168

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/query.sql
This PR removes a filter on placement so that we can bring in all placements to filter on downstream and accommodate the mmm data feed
[AD-706](https://mozilla-hub.atlassian.net/browse/AD-706)
[AD-706]: https://mozilla-hub.atlassian.net/browse/AD-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> removing placement filter to bring in tiles

sql/moz-fx-data-shared-prod/external_derived/imf_exchange_rates_v1/query.py
The DAG failed today on a non-duplicate check, turned out it was because I accidentally had listed 1 country (GB) 2x in the list of countries to pull data for.
* [Bug 1961364](https://bugzilla.mozilla.org/show_bug.cgi?id=1961364)
=> fix(imf_exchange_rates): Remove duplicate country from country list

sql/moz-fx-data-shared-prod/org_mozilla_fenix/nimbus_recorded_targeting_context/view.sql, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox/nimbus_recorded_targeting_context/view.sql
This PR updates the nimbus recorded targeting context views to have a where clause so they can be queried.
=> add where clause to nimbus recorded targeting context views

sql/bigconfig.yml, sql_generators/glean_usage/templates/baseline_clients_daily_v1.bigconfig.yml, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml, sql_generators/glean_usage/templates/metrics_clients_daily.bigconfig.yml, sql_generators/glean_usage/templates/metrics_clients_last_seen.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/engagement.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/new_profiles.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/retention.bigconfig.yml, sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.bigconfig.yml.jinja
This is primarily to reduce noise from those metrics as a very small number of nulls or other values for normalized_channel may be present
=> feat(DENG-8247): Set up 99 percent valid channel and 99 percent not null metrics

sql_generators/glean_usage/templates/baseline_clients_daily_v1.bigconfig.yml, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.bigconfig.yml
This is because this specific column contains mostly only null values for this particular channel causing it to constantly fail.
=> feat: do not include normalized_channel bigeye metric for baseline tables for ios nightly dataset

sql_generators/mobile_kpi_support_metrics/templates/new_profiles.bigconfig.yml, sql_generators/mobile_kpi_support_metrics/templates/retention.bigconfig.yml
This is to avoid a full table scan on each metric run.
=> feat: ensure partition field is specific for bigeye metrics set on retention and new_profiles

sql/moz-fx-data-shared-prod/acoustic/contact_current_snapshot/metadata.yaml, sql/moz-fx-data-shared-prod/acoustic/contact_current_snapshot/view.sql
This is because the underlaying table has been marked as deprecated and causes view deploy to error.
=> fix: drop acoustic.contact_current_snapshot view definition 

sql/moz-fx-data-shared-prod/org_mozilla_broken_site_report/user_reports_live/view.sql
Previously, the view only selected from `org_mozilla_fenix_live.broken_site_report_v1`, which I think is only the Nightly channel? For the non-live data, we have the `moz-fx-data-shared-prod.fenix.broken_site_report` view, which is an aggregate of multiple other datasets. Specifically, that view queries from
- `moz-fx-data-shared-prod.org_mozilla_fenix_nightly.broken_site_report`
- `moz-fx-data-shared-prod.org_mozilla_fenix.broken_site_report`
- `moz-fx-data-shared-prod.org_mozilla_fennec_aurora.broken_site_report`
- `moz-fx-data-shared-prod.org_mozilla_firefox_beta.broken_site_report`
- `moz-fx-data-shared-prod.org_mozilla_firefox.broken_site_report`
since all those datasets have a `_live` variant with a `broken_site_report_v1` table, I expanded this view to also include those. I'm not …
=> fix(org_mozilla_broken_site_report): Add all channel-specific datasets to the live view.

sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.query.sql, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.schema.yaml
* This PR adds the new columns `attribution` and `distribution` to the SQL generator template for `baseline_clients_last_seen_v1`
* This PR is a follow up PR to fix issues caused by [PR-7376](https://github.com/mozilla/bigquery-etl/pull/7376) which accidentally allowed these new columns to flow into the downstream table `baseline_clients_last_seen_v1` before the code was updated to handle them
* [DENG-8415](https://mozilla-hub.atlassian.net/browse/DENG-8415)
[DENG-8415]: https://mozilla-hub.atlassian.net/browse/DENG-8415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8415): Add attribution to baseline_clients_last_seen_v1

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
This PR adds 2 new columns, `first_seen_attribution` and `first_seen_distribution` to the view:
- `moz-fx-data-shared-prod.firefox_desktop.baseline_active_users`
* [DENG-8416](https://mozilla-hub.atlassian.net/browse/DENG-8416)
[DENG-8416]: https://mozilla-hub.atlassian.net/browse/DENG-8416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8416): Add columns to baseline_active_users view

sql_generators/funnels/configs/android_onboarding.toml
This generated funnel query was failing to run due to too many subqueries. Using the `events_stream` table complexity has been reduced and it's running fine.
Fixes Airflow failures
=> Use events_stream tables for android onboarding funnel

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
This PR breaks out the new attribution and distribution struct columns into separate string fields in the view:
- moz-fx-data-shared-prod.firefox_desktop.baseline_active_users
* [DENG-8416](https://mozilla-hub.atlassian.net/browse/DENG-8416)
[DENG-8416]: https://mozilla-hub.atlassian.net/browse/DENG-8416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8416): Update baseline_active_users view

sql/moz-fx-data-shared-prod/telemetry_derived/sponsored_tiles_clients_daily_v1/metadata.yaml
`sponsored_tiles_clients_daily_v1` has been failing due to out of memory errors. This table looks to be no longer needed -- the only downstream use is one look within an Ads dashboard, and I have confirmed with users of that dashboard that the look in question is no longer looked at.
I think we can probably fully deprecate this table, but I want to investigate a little more before doing that. In the meantime, I think we can safely unschedule it.
[AD-775](https://mozilla-hub.atlassian.net/browse/AD-775)
[AD-775]: https://mozilla-hub.atlassian.net/browse/AD-775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AD-775 Unschedule sponsored_tiles_clients_daily

sql/moz-fx-data-shared-prod/mozsoc_ml_prod_articles_zyte_cache/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/mozsoc_ml_prod_rss_news/dataset_metadata.yaml
This PR adds syndication for two datasets/tables in the `moz-fx-mozsoc-ml-prod` BigQuery project into the `moz-fx-data-shared-prod` BigQuery project in order to make the data available to Looker reports.
The intention is to have a full copy of the referenced tables residing in the `moz-fx-data-shared-prod` BigQuery project.
* [DENG-8408](https://mozilla-hub.atlassian.net/browse/DENG-8408)
* [DENG-8127](https://mozilla-hub.atlassian.net/browse/DENG-8127)
* [DENG-8085](https://mozilla-hub.atlassian.net/browse/DENG-8085)
[DENG-8408]: https://mozilla-hub.atlassian.net/browse/DENG-8408?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> feat(DENG-8048): replicate ML RSS ingestion data to prod-shared project

sql_generators/glean_usage/templates/events_stream_v1.query.sql
See https://mozilla-hub.atlassian.net/browse/DENG-8432
We saw an increase in `nimbus_events.validation_failed` and `normandy.validation_failed_nimbus_experiment` events that could no longer be processed for `firefox_desktop_background_update.events_stream`. This issue has since been fixed on the FF client (https://phabricator.services.mozilla.com/D247864), but we'll need to filter out these events in the meantime to unblock `firefox_desktop_background_update.events_stream`
=> [DENG-8432] Filter out nimbus_events.validation_failed and normandy.validation_failed_nimbus_experiment for firefox_desktop_background_update

sql/moz-fx-data-shared-prod/telemetry/socorro_crash/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry/socorro_crash_v2/metadata.yaml
Gives read access to socorro_crash for crash-ping-ingest, similar to #7267.
* DENG-8350
=> [DENG-8350] read access on socorro_crash for crash-ping-ingest

sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.query.sql, sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.schema.yaml
* This PR adds 2 new columns, `attribution_ext` & `distribution_ext`, to the SQL generator template for `baseline_clients_first_seen_v1` - but only for the app firefox_desktop (it does not add the columns to other apps since there is no data yet for other apps)
* [DENG-8425](https://mozilla-hub.atlassian.net/browse/DENG-8425)
[DENG-8425]: https://mozilla-hub.atlassian.net/browse/DENG-8425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8425): Add 2 columns to baseline_clients_first_seen_v1

dags.yaml
Removes the `bqetl_sponsored_tiles_clients_daily` DAG. This only ran the `bqetl_sponsored_tiles_clients_daily_v1` table, which has been rescheduled.
=> Remove bqetl_sponsored_tiles_clients_daily DAG

sql/moz-fx-data-shared-prod/glean_telemetry/dataset_metadata.yaml
This is a follow up to [PR-7409](https://github.com/mozilla/bigquery-etl/pull/7409) which caused issues by accidentally using a reserved namespace.  This renames the dataset to `glean_telemetry` instead of `glean`.
=> fix: Rename dataset glean to glean_telemetry

dags.yaml, sql/moz-fx-data-shared-prod/telemetry/active_users_rollup_shredder/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_rollup_shredder_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_rollup_shredder_v1/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/active_users_rollup_shredder_v1/schema.yaml
This PR creates a new table and view whose purpose is to record the impact of Shredder over time.
- `moz-fx-data-shared-prod.telemetry_derived.active_users_rollup_shredder_v1`
- `moz-fx-data-shared-prod.telemetry.active_users_rollup_shredder_v1`
It also creates a new DAG to populate this table weekly, scheduled to run on Sundays:
- `bqetl_shredder_impact_measurement`
=> Create new table telemetry_derived.active_users_rollup_shredder_v1

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
This PR adds the column "is_desktop" to the view:
- moz-fx-data-shared-prod.firefox_desktop_derived.baseline_active_users
This is needed for some of the upcoming KPI reporting tables.
* [DENG-8026](https://mozilla-hub.atlassian.net/browse/DENG-8026)
[DENG-8026]: https://mozilla-hub.atlassian.net/browse/DENG-8026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add is_desktop column to baseline_active_users view.sql

dags.yaml
Adds triage notes for `bqetl_experimenter_experiments_import` DAG
=> Add triage notes for bqetl_experimenter_experiments_import

.github/dependabot.yml, CODEOWNERS
https://mozilla-hub.atlassian.net/browse/DENG-8480
Dependabot reviewers configuration is being removed, and instead they are recommending to rely on CODEOWNERS files to assign reviewers
=> [DENG-8480] Use CODEOWNERS for dependabot reviewer tagging

sql/moz-fx-data-shared-prod/accounts_backend_derived/users_services_daily_v1/checks.sql
This will fix intermittent check failures.
Now when `accounts_events` explores are hidden and no key/new dashboards use them it's enough if these checks validate that all new events are implemented in `events` ping. We can ignore cases when new event is not implemented in legacy `accounts_events` ping.
=> feat(DENG-2407): relax FxA events sql checks

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_historical_legacy_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_historical_legacy_v1/query.py
This PR fixes the script to bring in the source file name
[AD-706](https://mozilla-hub.atlassian.net/browse/AD-706)
[AD-706]: https://mozilla-hub.atlassian.net/browse/AD-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AD-706-fix: adding source file name

dags.yaml, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_and_version_v1/query.py, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_v1/query.py, sql/moz-fx-data-shared-prod/google_play_store_derived/slow_startup_events_by_startup_type_version_and_device_v1/query.py
This PR updates the delay for 3 jobs loading data from the Google Play Store, to run with a 2 day delay instead of a 3 day delay from the execution time of the DAG.
=> Adjust delay to get data sooner for team using it 1 day sooner

sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/schema.yaml
BigQuery has added a new `query_dialect` column to the [`JOBS_BY_ORGANIZATION` view](https://cloud.google.com/bigquery/docs/information-schema-jobs-by-organization), which this PR passes through to the `jobs_by_organization_v1` ETL.
* [OPST-2485](https://mozilla-hub.atlassian.net/browse/OPST-2485): Set organization default for BQ SQL dialect to standard SQL
[OPST-2485]: https://mozilla-hub.atlassian.net/browse/OPST-2485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(monitoring): Add `query_dialect` column to `jobs_by_organization_v1` ETL

sql/moz-fx-data-shared-prod/telemetry_derived/cohort_weekly_statistics_v1/query.sql
The table `moz-fx-data-shared-prod.telemetry_derived.cohort_weekly_statistics_v1` has logic to pull all cohorts starting in last 180 days, but extending this to be a larger time range (now all cohorts starting in last 775 days). Note, using 768 here because the logic gets the start of the week so this ensures the start will be within the 775 day range.
=> Increase history from 180 days to last 768 days

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/query.sql
This PR adds historical data for newtab telemetry collected from the legacy ping going back further than 6 months (current expiration on _stable tables. the further back we go, the more data was flowing through (before clients updated to glean). 
For the ads media mix modeling, we need to be able to go back further than 6 months, so data was imported from Snowflake to Bigquery to accommodate this.
`newtab_interactions_historical_legacy` was copied from Snowflake 
[AD-706](https://mozilla-hub.atlassian.net/browse/AD-706)
[AD-706]: https://mozilla-hub.atlassian.net/browse/AD-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> updating model to bring in historical data for backfilling

dags.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_interactions_hourly_v1/metadata.yaml
`telemetry_derived.newtab_interactions_hourly_v1` (a table that runs daily) is currently not running because it is waiting on `telemetry_derived.newtab_interactions_historical_legacy_v1`, which runs daily. Additionally, it's missing a dependency that should be there. There are two changes here:
* Stop running `telemetry_derived.newtab_interactions_historical_legacy_v1` altogether. It only needs to run on an ad hoc basis
* Make the depencies for `newtab_interactions_hourly_v1` in the metadata to:
* Remove the automatically generated depenency on `newtab_interactions_historical_legacy_v1` by setting `referenced_tables` to `[]`
* Manually add a dependency on `ads_derived.interaction_aggregates_hourly_v1`
* [AD-850](https://mozilla-hub.atlassian.net/browse/AD-850)
**Reviewer, please follow …
=> AD-850 Fix dependencies on newtab_interactions_hourly_v1

sql/mozfun/norm/glean_windows_version_info/README.md, sql/mozfun/norm/glean_windows_version_info/metadata.yaml, sql/mozfun/norm/glean_windows_version_info/udf.sql
This PR creates a new UDF, `norm.glean_windows_version_info`, and creates tests of the UDF.
This UDF helps parse Windows version information but for Glean inputs which are slightly different than what the Legacy inputs were (particularly for the "os" column).
* [DENG-8439](https://mozilla-hub.atlassian.net/browse/DENG-8439)
[DENG-8439]: https://mozilla-hub.atlassian.net/browse/DENG-8439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8439): Create Glean UDF for parsing Windows OS version

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
This PR updates the OS UDF functions used in the view:
- `moz-fx-data-shared-prod.firefox_desktop.baseline_active_users`
There are 3 changes:
1. It simplifies the logic for OS version major and OS version minor.  
2. It also fixes the logic for os_build to use the new "glean_windows_version_info" UDF.
3. It adds a new column to help keep consistency with the old AUA table to make swapping Looker dashboards easier.
* [DENG-8439](https://mozilla-hub.atlassian.net/browse/DENG-8439)
[DENG-8439]: https://mozilla-hub.atlassian.net/browse/DENG-8439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8438): Update OS UDFs in baseline_active_users view

bigquery_etl/schema/__init__.py
I found this bug while looking at the desktop_crashes generator: https://github.com/mozilla/bigquery-etl/blob/730e33d3d43854f6bee38d38aacf0412927982d9/sql_generators/desktop_crashes/__init__.py#L44-L51
Multiple source schemas are merged into a target schema but since it uses a shallow copy, the  dict references in the target are the same as the ones in the sources so the source schemas get updated unexpectedly.
Deep copying the desktop metrics dict takes ~6.5 ms so performance shouldn't performance shouldn't matter.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1920544
=> Use deep copy when merging schemas

bigquery_etl/glam/templates/probe_counts_v1.sql
This PR fixes the release All OS client counts on GLAM. 
* DENG-8486
=> fix(glam): re-adjust client_count for sampling only on scalars

.pre-commit-config.yaml, bigquery_etl/cli/backfill.py, tests/cli/test_cli_backfill.py
Reverts mozilla/bigquery-etl#7448
If more than one backfill is modified in a single commit this fails.
=> Revert "feat: add bqetl_backfill_validate pre-commit hook"

sql/mozfun/norm/glean_windows_version_info/udf.sql
This PR updates the UDF for Glean Windows Version to change the output when the windows build # is null and it's Windows 10 or 11.
* [DENG-8439](https://mozilla-hub.atlassian.net/browse/DENG-8439)
[DENG-8439]: https://mozilla-hub.atlassian.net/browse/DENG-8439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8439): Update UDF

sql_generators/mobile_kpi_support_metrics/templates/new_profile_activations.query.sql
=> fix: new_profile_activations query validation error (schema / query mismatch)

sql/moz-fx-data-shared-prod/fenix_derived/attribution_clients_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/attribution_clients_v1/backfill.yaml, sql/moz-fx-data-shared-prod/focus_android_derived/attribution_clients_v1/backfill.yaml, sql/moz-fx-data-shared-prod/focus_ios_derived/attribution_clients_v1/backfill.yaml, sql/moz-fx-data-shared-prod/klar_android_derived/attribution_clients_v1/backfill.yaml, sql/moz-fx-data-shared-prod/klar_ios_derived/attribution_clients_v1/backfill.yaml, sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.metadata.yaml
Also including a note in the schema and description that normalized_channel is null prior to the backfill start date
=> feat: mark attribution_clients backfill complete

requirements.in, requirements.txt
This PR reverts the dependabot upgrade from [PR-7472](https://github.com/mozilla/bigquery-etl/pull/7472) since this caused some issues.
=> Revert gcsfs upgrade (go from 2025.5.0 -> 2025.3.2)

sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_logical_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_service_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/logical_subscription_events_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_logical_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_service_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/service_subscription_events_v1/backfill.yaml
Initiates backfills of the logical subscription and service subscription tables.
* DENG-975: Google subscriptions ETL v2
=> chore(SubPlat): Initiate backfills to add historical Google subscription records to SubPlat consolidated reporting tables (DENG-975)

requirements.in, requirements.txt
Reverts mozilla/bigquery-etl#7485
=> Revert "chore(deps): bump bigeye-sdk from 0.5.1 to 0.5.2"

bigquery_etl/glam/client_side_sampled_metrics.py, bigquery_etl/glam/clients_daily_histogram_aggregates.py, bigquery_etl/glam/clients_daily_scalar_aggregates.py, bigquery_etl/glam/templates/clients_daily_histogram_aggregates_v1.sql, bigquery_etl/glam/templates/clients_daily_scalar_aggregates_v1.sql
This PR adapts the GLAM ETL to not further sample a static list of metrics that are already getting sampled on the client-side via server knobs. More in the ticket below.
* DENG-8046
=> feat(glam): Add support to client-sampled metrics

bigquery_etl/query_scheduling/task.py, bigquery_etl/query_scheduling/templates/airflow_dag.j2
The existing DAG generation logic assumes ETLs using `date_partition_offset` are partitioned by date, which is causing two monthly partitioned SubPlat ETLs to fail ([bug 1968341](https://bugzilla.mozilla.org/show_bug.cgi?id=1968341), [bug 1968342](https://bugzilla.mozilla.org/show_bug.cgi?id=1968342)) after I set `date_partition_offset` for them (#7471).
* DENG-975: Google subscriptions ETL v2
* https://github.com/mozilla/bigquery-etl/pull/7471
* [Bug 1968341](https://bugzilla.mozilla.org/show_bug.cgi?id=1968341): Airflow task bqetl_subplat.subscription_platform_derived__monthly_active_logical_subscriptions__v1 failed for exec_date 2025-05-22
* [Bug 1968342](https://bugzilla.mozilla.org/show_bug.cgi?id=1968342): Airflow task bqetl_subplat.subscription_platform_derived__monthly_active_servi …
=> fix: Support using `date_partition_offset` with monthly partitioned ETLs

sql/moz-fx-data-shared-prod/monitoring/looker_dashboard_load_times/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/looker_dashboard_load_times_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/looker_dashboard_load_times_v1/schema.yaml
We had another session with Looker support and they explained how the recorded dashboard performance times need to be normalized/subtracted/offset. This PR implements these changes in the view and pulls in some more fields into the source table.
=> Normalize looker dashboard perf metrics

bigquery_etl/glam/clients_daily_histogram_aggregates.py, bigquery_etl/glam/clients_daily_scalar_aggregates.py, bigquery_etl/glam/templates/clients_daily_scalar_aggregates_v1.sql
Fix for #7503. Sampled metrics are currently be added to queries for all the pings but the metrics are only in the metrics ping.  This change makes it so that only metrics that exist are added
* https://bugzilla.mozilla.org/show_bug.cgi?id=1968556
=> Bug 1968556 - Check if exists before adding sampled metric to glam queries

bigquery_etl/glam/generate.py
GLAM aggregations have a minimum client count threshold that is 0.5% of WAU. So, based on current values of [Firefox Desktop DAU/WAU/MAU by release channel](https://mozilla.cloud.looker.com/dashboards/1845?Submission%20Date=after%2060%20weeks%20ago&Browser%20Name=Firefox%20Desktop), I'm updating the threshold values.
* DENG-8646
=> chore(glam): update fog minimum_client_count according to current WAU

bigquery_etl/backfill/parse.py, bigquery_etl/cli/backfill.py, tests/backfill/test_parse_backfill.py
Managed backfills currently always take an ETL's `date_partition_offset` setting into account, but that has some downsides:
* When specifying the backfill start/end dates you need to account for the offset, which makes it less obvious what table partitions are being backfilled and trickier to get that right.
* Managed backfills don't currently support `date_partition_offset` with monthly partitioned ETLs.
While it is necessary for managed backfills to take the `date_partition_offset` setting into account for some ETLs with custom date parameters, for ETLs simply using the standard date partition parameter it would be better if the backfill start/end dates could map directly to the table partitions (e.g. #7496), so this PR adds an optional `ignore_date_partition_offset` backfill setting to …
=> feat(backfill): Add `ignore_date_partition_offset` backfill option

sql/moz-fx-data-shared-prod/ads_derived/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/ads_derived/nt_visits_to_sessions_conversion_factors_daily_v1/metadata.yaml
Complements [https://github.com/mozilla/private-bigquery-etl/pull/736] -- the `ads_derived` dataset is almost entirely defined in `private-bigquery-etl`, but one table is defined here.
I believe this table is no longer in use, so my plan is to initiate the [deprecation process](https://docs.google.com/document/d/1ek-XNCKpxMK47mjc_RU-RNvUwHNOhNlbQHig8MZh6fk/edit) for this table and then remove this folder from `bigquery-etl` entirely, but that's going to take a little longer to do, and I'd like to get this permission change in first.
* DENG-8048
=> DENG-8048 Add default access to ads_derived dataset to ads WG

sql/moz-fx-data-shared-prod/firefox_desktop/desktop_engagement_aggregates/view.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_aggregates_v1/schema.yaml
This PR creates the following new table and associated view:
- `moz-fx-data-shared-prod.firefox_desktop_derived.desktop_engagement_aggregates_v1`
- `moz-fx-data-shared-prod.firefox_desktop.desktop_engagement_aggregates`
* [DENG-8405](https://mozilla-hub.atlassian.net/browse/DENG-8405)
[DENG-8405]: https://mozilla-hub.atlassian.net/browse/DENG-8405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8405): Create desktop_engagement_aggregates_v1

sql/moz-fx-data-shared-prod/firefox_desktop/desktop_retention_aggregates/view.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_retention_aggregates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_retention_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_retention_aggregates_v1/schema.yaml
This PR creates the following new table and associated view:
- `moz-fx-data-shared-prod.firefox_desktop_derived.desktop_retention_aggregates_v1`
- `moz-fx-data-shared-prod.firefox_desktop.desktop_retention_aggregates`
* [DENG-8401](https://mozilla-hub.atlassian.net/browse/DENG-8401)
[DENG-8401]: https://mozilla-hub.atlassian.net/browse/DENG-8401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8401): Create desktop_retention_aggregates_v1

sql/moz-fx-data-shared-prod/firefoxdotcom/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/dataset_metadata.yaml
This PR creates 2 new datasets, intended to store data from the new GA4 property for Firefox.com:
- firefoxdotcom
- firefoxdotcom_derived
* [DENG-8668](https://mozilla-hub.atlassian.net/browse/DENG-8668)
[DENG-8668]: https://mozilla-hub.atlassian.net/browse/DENG-8668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8668): Create datasets for new Firefox.com GA4 data

dags.yaml, sql/moz-fx-data-shared-prod/firefoxdotcom/www_site_downloads/view.sql, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_downloads_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_downloads_v1/query.sql, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_downloads_v1/schema.yaml
This PR also creates the new DAG that we will use to store all of the Firefox.com tasks, `bqetl_ga4_firefoxdotcom`.
This PR creates the new table and view:
- `moz-fx-data-shared-prod.firefoxdotcom_derived.www_site_downloads_v1`
- `moz-fx-data-shared-prod.firefoxdotcom.www_site_downloads`
* [DENG-8673](https://mozilla-hub.atlassian.net/browse/DENG-8673)
[DENG-8673]: https://mozilla-hub.atlassian.net/browse/DENG-8673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8673): Create firefox.com www_site_downloads_v1

sql_generators/mobile_kpi_support_metrics/templates/new_profile_activation_clients.view.sql
This PR adds a column `paid_vs_organic_via_gclid_attribution` to the view:
* `moz-fx-data-shared-prod.fenix.new_profile_activation_clients`
* [DENG-8720](https://mozilla-hub.atlassian.net/browse/DENG-8720)
[DENG-8720]: https://mozilla-hub.atlassian.net/browse/DENG-8720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add UDF to new_profile_activation_clients view for Fenix

sql_generators/experiment_monitoring/templates/experiment_events_live_v1/materialized_view.sql
This udf usage was added in https://github.com/mozilla/bigquery-etl/pull/6791. Materialized views don't support udfs so deploys are failing with `Materialized views do not support routines`.  Only new materialized views get deployed so it hasn't failed until now.
=> Remove udf usage from experiment_events_live

sql_generators/glean_usage/templates/events_stream_v1.query.sql
Firefox 139 release and these events are still very high volume so events stream is failing
* DENG-8432
=> Add version 139 to nimbus events_stream filter

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users_aggregates/view.sql, sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users_aggregates_full/view.sql
This PR essentially creates 2 views, each with different purposes, on top of the table `moz-fx-data-shared-prod.firefox_desktop_derived.baseline_active_users_aggregates_v2`
The views:
* `moz-fx-data-shared-prod.firefox_desktop.baseline_active_users_aggregates`
* Has reduced cardinality by removing dimensions less frequently used in order to speed up Looker performance
* `moz-fx-data-shared-prod.firefox_desktop.baseline_active_users_aggregates_full`
* Has all the same dimensions as the base table, in case users need to do a deep dive into lower level granularity
* [DENG-8723](https://mozilla-hub.atlassian.net/browse/DENG-8723)
[DENG-8723]: …
=> Make 2 versions of baseline active users aggregates view

sql/moz-fx-data-shared-prod/glean_telemetry/active_users_aggregates/view.sql
This PR is a follow up to [PR-7548](https://github.com/mozilla/bigquery-etl/pull/7548)
* [DENG-8396](https://mozilla-hub.atlassian.net/browse/DENG-8396)
* [DENG-8723](https://mozilla-hub.atlassian.net/browse/DENG-8723)
[DENG-8396]: https://mozilla-hub.atlassian.net/browse/DENG-8396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DENG-8723]: https://mozilla-hub.atlassian.net/browse/DENG-8723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DENG-8723): Switch glean_telemetry view to use full baseline AUA table instead of slimmed version

sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_logical_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_service_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/logical_subscription_events_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_logical_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_service_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/service_subscription_events_v1/backfill.yaml
Completes backfills of the logical subscription and service subscription tables initiated in #7496.
In addition to adding records for Google subscriptions, these backfills also have minor side effects on some existing records for Stripe subscriptions:
- `first_touch_attribution.impression_at` and `last_touch_attribution.impression_at` timestamps have been truncated to milliseconds for 2,978 subscriptions.
- This appears to be due to `users.created_at` timestamp values from the VPN Guardian database having been truncated to millisecond resolution instead of microsecond resolution.
- `has_refunds` has changed from false to true for 461 subscriptions.
- This is somewhat to be expected given how Stripe charges can be belatedly refunded, but the `stripe_logical_subscriptions_history_v1` ETL's …
=> chore(SubPlat): Complete backfills to add historical Google subscription records to SubPlat consolidated reporting tables (DENG-975)

bigquery_etl/shredder/delete.py, tests/shredder/test_delete.py
This PR is meant to fix Bug 1967599, which allows Shredder to accept context_id UUIDs with braces, like `{decafbad-0cd1-0cd2-0cd3-decafbad1000}`, as well as without braces like `decafbad-0cd1-0cd2-0cd3-decafbad1000`.
It should also _delete_ context IDs from the deletion tables with the brace and non-brace variants.
I am notably _very new_ to this repository and project, so please advise if there are better / more correct ways of doing what I'm trying to do here.
* https://bugzilla.mozilla.org/show_bug.cgi?id=1967599
* https://bugzilla.mozilla.org/show_bug.cgi?id=1967505
* https://github.com/mozilla/application-services/pull/6746
=> Bug 1967599 - Have Shredder normalize context_ids to deal with brace and non-brace variants.

sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_clients_v1/query.sql
* This table `moz-fx-data-shared-prod.firefox_desktop_derived.desktop_engagement_clients` is a new table, and since being built, we've noticed that it tends to have a small number of clients with 2 or more rows (each with different first seen dates) which causes the uniqueness check to fail daily.  These clients with duplicates are ones who have submitted deletion requests, and were previously shredded from the first seen table, but then show up with a new first seen date.  This PR should help prevent issues by preventing clients who have submitted deletion requests from being included in the table.
Related PRs:
* [DENG-8404](https://mozilla-hub.atlassian.net/browse/DENG-8404)
**Reviewer, please follow [this checklist](https://github.com/mozilla/bigquery-etl/blob/main/.github/reviewer_chec …
=> fix(DENG-8404): Add logic to not include client IDs with new-ish deletion requests

sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospects_v1/query.sql
- this removed part of the WHERE clause was causing the model to incorrectly skip rows that have an expected value of NULL in `reviewed_at`.
- the removed code was intended to fix an out of range error when calling TIMESTAMP_SECONDS in the SELECT clause - but this was remedied by dividing the `reviewed_at` value by 1000 (as it was in milliseconds, unlike `created_at` which is in seconds).
* DENG-8738
=> fix(DENG-8738): NULL date checking in WHERE clause skipping necessary rows

sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_cumulative_population_estimate_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_cumulative_population_estimate_v2/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_daily_active_population_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_daily_active_population_v2/query.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_daily_active_population_v2/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_other_events_overall_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_other_events_overall_v2/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_overall_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_enrollment_overall_v2/view.sql, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_unenrollment_overall_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/experiment_unenrollment_overall_v2/view.sql, sql_generators/experiment_monitoring/templates/experiments_daily_active_clients_v2/metadata.yaml, sql_generators/experiment_monitoring/templates/experiments_daily_active_clients_v2/query.sql, sql_generators/experiment_monitoring/templates/templating.yaml
Creates more (see [previous PR](https://github.com/mozilla/bigquery-etl/pull/7534)) glean-only versions of experiment datasets.
* EXP-4979
=> feat: create glean-only v2 versions of experiment datasets

sql/moz-fx-data-shared-prod/monitoring/looker_usage_explores/view.sql, sql/moz-fx-data-shared-prod/monitoring/looker_usage_models/view.sql, sql/moz-fx-data-shared-prod/monitoring/looker_usage_unused_explores/view.sql, sql/moz-fx-data-shared-prod/monitoring_derived/looker_usage_explores_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/looker_usage_explores_v1/schema.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/looker_usage_models_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/looker_usage_models_v1/schema.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/looker_usage_unused_explores_v1/metadata.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/looker_usage_unused_explores_v1/schema.yaml, sql/moz-fx-data-shared-prod/udf/looker_approx_percentile_distinct_disc/metadata.yaml, sql/moz-fx-data-shared-prod/udf/looker_approx_percentile_distinct_disc/udf.sql
This adds views for 3 Looker usage tables that are being created and populated via docker-etl: https://github.com/mozilla/docker-etl/tree/main/jobs/looker-utils
The views change some of the column names to support auto lookml generation (which doesn't support spaces)
=> [DENG-8625] Add views for Looker usage tables

sql/moz-fx-data-shared-prod/firefox_desktop/desktop_engagement_aggregates/view.sql, sql/moz-fx-data-shared-prod/firefox_desktop/desktop_retention_aggregates/view.sql
This PR adds 2 columns, `lifecycle_stage` & `paid_vs_organic` to the 2 views:
- `moz-fx-data-shared-prod.firefox_desktop.desktop_retention_aggregates`
- `moz-fx-data-shared-prod.firefox_desktop.desktop_engagement_aggregates`
* [DENG-8402](https://mozilla-hub.atlassian.net/browse/DENG-8402)
* [DENG-8406](https://mozilla-hub.atlassian.net/browse/DENG-8406)
[DENG-8402]: https://mozilla-hub.atlassian.net/browse/DENG-8402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DENG-8406]: https://mozilla-hub.atlassian.net/browse/DENG-8406?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8402): Add lifecycle_stage and paid_vs_organic to views

.pre-commit-config.yaml, bigquery_etl/backfill/validate.py, bigquery_etl/cli/backfill.py, tests/cli/test_cli_backfill.py
`validate_multiple` command added to support multiple backfill file paths being passed into bqetl for backfill config validation. Example usage:
```shell
/bqetl backfill validate-multiple \
sql/moz-fx-data-shared-prod/org_mozilla_fenix_nightly_derived/baseline_clients_daily_v1/backfill.yaml \
sql/moz-fx-data-shared-prod/org_mozilla_firefox_derived/baseline_clients_daily_v1/backfill.yaml
```
This will run validation for all files passed in and exist with status code 1 if any errors are found by the upstream `validate` command.
=> feat: add bqetl_backfill_validate pre-commit hook

sql/moz-fx-data-shared-prod/remote_settings_logs_aggregates/dataset_metadata.yaml
We don't expect to need to create any derived tables from this so for simplicity we can make the whole dataset user facing (like https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/mdn_rumba/dataset_metadata.yaml#L4).
This will require operator input at deployment.
=> chore(DENG-8567): make remote settings syndicate dataset user-facing

sql/moz-fx-data-shared-prod/firefoxdotcom/www_site_page_metrics/view.sql, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_page_metrics_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_page_metrics_v1/query.sql, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_page_metrics_v1/schema.yaml
This PR creates the new table and the corresponding view:
`moz-fx-data-shared-prod.firefoxdotcom_derived.www_site_page_metrics_v1`
`moz-fx-data-shared-prod.firefoxdotcom.www_site_page_metrics`
* DENG-8681
* DSRE-XXXX
=> add files for firefoxdotcom.www_site_page_metrics_v1 and view

sql/moz-fx-data-shared-prod/subscription_platform_derived/active_subscriptions_v1/query.sql
To avoid double-counting bundle subscriptions.
* DENG-8391: Privacy Product Bundle
=> fix(SubPlat): Update `active_subscriptions_v1` ETL to account for "Privacy protection plan" bundle (DENG-8391)

dags.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospect_item_feed_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospect_item_feed_v1/query.sql, sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospect_item_feed_v1/schema.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospects_v1/metadata.yaml
migrate prospect_item_feed table from snowflake.
this job is intended to execute after the `prospects_v1` [source table](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospects_v1/metadata.yaml) is updated.
* DENG-8338
=> feat(DENG-8338): migrate prospect_item_feed table from snowflake

sql/moz-fx-data-shared-prod/snowflake_migration_derived/stg_scheduled_corpus_items_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/stg_scheduled_corpus_items_v1/query.sql, sql/moz-fx-data-shared-prod/snowflake_migration_derived/stg_scheduled_corpus_items_v1/schema.yaml
migrates the `stg_scheduled_corpus_items` snowflake table. does a bit of optimizing/refactoring of the original DBT model ([GitHub link](https://github.com/Pocket/dbt-snowflake/blob/e7880781e1c31a23e4afccabab008857edba2499/models/staging/curation/curation_base/stg_scheduled_corpus_items.sql), requires Pocket org access).
just like in #7591, as a verification, i ran the model in this PR in BigQuery and the original DBT model in Snowflake against the same date range (`BETWEEN '2025-06-01' AND '2025-06-05'`) and got the exact same number of rows in each warehouse. 🎉 
* DENG-8340
=> feat(DENG-8340): migrate stg_scheduled_corpus_items from snowflake

sql/moz-fx-data-shared-prod/mozilla_org/ga_desktop_conversions/view.sql, sql/moz-fx-data-shared-prod/mozilla_org/gclid_conversions/view.sql, sql/moz-fx-data-shared-prod/mozilla_org/gclid_conversions_v2/view.sql, sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_desktop_conversions_v1/metadata.yaml, sql/moz-fx-data-shared-prod/mozilla_org_derived/gclid_conversions_v2/metadata.yaml
This PR does 3 things:
1.  It updates the view `moz-fx-data-shared-prod.mozilla_org.ga_desktop_conversions` to point at `moz-fx-data-shared-prod.mozilla_org_derived.ga_desktop_conversions_v2`, and deprecates `moz-fx-data-shared-prod.mozilla_org_derived.ga_desktop_conversions_v1`
2. It updates the view `moz-fx-data-shared-prod.mozilla_org.gclid_conversions` to point to the latest table `moz-fx-data-shared-prod.mozilla_org_derived.gclid_conversions_v3`.
3. It deletes the view `moz-fx-data-shared-prod.mozilla_org.gclid_conversions_v2`.
It also deprecates the V1 version of the table.
=> Switch mozilla_org.ga_desktop_conversions to point to latest, deprecate V1

sql/moz-fx-data-shared-prod/firefox_accounts_derived/recent_fxa_gcp_stderr_events_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_accounts_derived/recent_fxa_gcp_stdout_events_v1/metadata.yaml
I just added these hourly ETLs in #7582, but BigQuery doesn't like the `ALLOW_FIELD_ADDITION` schema update option being specified when overwriting the entire table, so the ETLs are failing.
* https://github.com/mozilla/bigquery-etl/pull/7582
* DENG-3736: Increase frequency for product/subplat data updates
=> fix(SubPlat): Remove schema update option from `recent_fxa_gcp_*_events` ETLs (DENG-3736)

sql/moz-fx-data-shared-prod/telemetry_derived/active_users_rollup_shredder_v1/metadata.yaml, sql_generators/events_daily/templates/event_types_history_v1/metadata.yaml, sql_generators/events_daily/templates/event_types_v1/metadata.yaml, sql_generators/events_daily/templates/events_daily_v1/metadata.yaml
This queries use a lot of slots so running with on-demand is cheaper https://sql.telemetry.mozilla.org/queries/107355
cc @akkomar and @kwindau as owners but there shouldn't be any noticeable changes
Also cleaned up owners in events_daily
* DENG-8859, DENG-8862, and the associated epic
=> Run fenix events_daily and active_users_rollup_shredder with on-demand

bigquery_etl/backfill/parse.py, docs/cookbooks/creating_a_derived_dataset.md
Adding some details on how the slack username lookup works for managed backfills.  This is somewhat unclear so I want to document this somewhere.
=> Add slack username details to backfill watchers doc

sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_retention_clients_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_retention_clients_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_retention_clients_v1/schema.yaml
This PR adds the new column `legacy_telemetry_client_id` to the table and corresponding view:
- `moz-fx-data-shared-prod.firefox_desktop_derived.desktop_retention_clients_v1`
- `moz-fx-data-shared-prod.firefox_desktop.desktop_retention_clients`
* [DENG-8869](https://mozilla-hub.atlassian.net/browse/DENG-8869)
[DENG-8869]: https://mozilla-hub.atlassian.net/browse/DENG-8869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8869): Add column to desktop_retention_clients

sql/moz-fx-data-shared-prod/firefox_desktop/desktop_engagement_clients/view.sql, sql/moz-fx-data-shared-prod/firefox_desktop/desktop_retention_clients/view.sql
This PR adds the new column `lifecycle_stage` to the 2 views:
- `moz-fx-data-shared-prod.firefox_desktop.desktop_retention_clients`
- `moz-fx-data-shared-prod.firefox_desktop.desktop_engagement_clients`
=> Add lifecycle_stage to OKR client level views

bigquery_etl/cli/metadata.py, tests/cli/test_cli_metadata.py, tests/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1/metadata.yaml
https://mozilla-hub.atlassian.net/browse/DENG-8843
This updates the metadata generation logic for `workgroup_access`. This will only remove `roles/bigquery.dataViewer` access on table metadata while keeping `roles/bigquery.dataEditor` intact.
This will also translate `roles/bigquery.dataViewer` to dataset-level `roles/bigquery.metadataViewer` if there is a deprecated table in the dataset.
=>  [DENG-8843] Retain dataEditor workgroup_access and map metadataViewer permissions on deprecated tables

sql/moz-fx-data-shared-prod/snowflake_migration_derived/dismissed_prospects_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/dismissed_prospects_v1/query.sql, sql/moz-fx-data-shared-prod/snowflake_migration_derived/dismissed_prospects_v1/schema.yaml
migrate `dismissed_prospects` snowflake table. verified row number parity between snowflake and bigquery for sample data range of `2025-06-01` to `2025-06-11`.
* DENG-8136
=> feat(DENG-8136): migrate dismissed_prospects snowflake table

sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_item_schedules_updated_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_item_schedules_updated_v1/query.sql, sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_item_schedules_updated_v1/schema.yaml
migrate the `corpus_item_schedules_updated` snowflake table.
* DENG-8131
=> feat(DENG-8131): migrate corpus_item_schedules_updated snowflake table

sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_clients_v1/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_clients_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_clients_v1/schema.yaml
This PR adds 2 new columns, `legacy_telemetry_client_id` & `windows_version` to:
- `moz-fx-data-shared-prod.firefox_desktop_derived.desktop_engagement_clients_v1`
- `moz-fx-data-shared-prod.firefox_desktop.desktop_engagement_clients`
This also adds clustering first by Glean sample_id.
* [DENG-8870](https://mozilla-hub.atlassian.net/browse/DENG-8870)
* [DENG-8887](https://mozilla-hub.atlassian.net/browse/DENG-8887)
[DENG-8870]: https://mozilla-hub.atlassian.net/browse/DENG-8870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DENG-8887]: https://mozilla-hub.atlassian.net/browse/DENG-8887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> feat(DENG-8870 + DENG-8887): Add 2 columns to desktop_engagement_clients

sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_aggregates_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_engagement_aggregates_v1/schema.yaml
This PR adds the new column `windows_version` to the table and corresponding view:
- `moz-fx-data-shared-prod.firefox_desktop_derived.desktop_engagement_aggregates_v1`
- `moz-fx-data-shared-prod.firefox_desktop.desktop_engagement_aggregates`
* [DENG-8888](https://mozilla-hub.atlassian.net/browse/DENG-8888)
[DENG-8888]: https://mozilla-hub.atlassian.net/browse/DENG-8888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8888): Add windows_version to desktop_engagement_aggregates_v1

sql/moz-fx-data-shared-prod/marketing_suppression_list_derived/main_suppression_list_v1/query.sql, tests/sql/moz-fx-data-shared-prod/marketing_suppression_list_derived/main_suppression_list_v1/test_main_suppression_list/expect.yaml, tests/sql/moz-fx-data-shared-prod/marketing_suppression_list_derived/main_suppression_list_v1/test_main_suppression_list/moz-fx-data-shared-prod.braze_external.braze_currents_firefox_hard_bounces_v1.yaml, tests/sql/moz-fx-data-shared-prod/marketing_suppression_list_derived/main_suppression_list_v1/test_main_suppression_list/moz-fx-data-shared-prod.braze_external.braze_currents_mozilla_hard_bounces_v1.yaml, tests/sql/moz-fx-data-shared-prod/marketing_suppression_list_derived/main_suppression_list_v1/test_main_suppression_list/moz-fx-data-shared-prod.braze_external.braze_currents_pocket_hard_bounces_v1.yaml, tests/sql/moz-fx-data-shared-prod/marketing_suppression_list_derived/main_suppression_list_v1/test_main_suppression_list/moz-fx-data-shared-prod.braze_external.braze_currents_pocket_unsubscribe_v1.yaml, tests/sql/moz-fx-data-shared-prod/marketing_suppression_list_derived/main_suppression_list_v1/test_main_suppression_list/moz-fx-data-shared-prod.marketing_suppression_list_external.campaign_monitor_suppression_list_v1.yaml
This PR adds unsubscribes and hard bounces from the Pocket workspace in Braze to the suppression list
* DENG-8922
=> Adding unsubscribes and hard bounces from pocket workspace to suppression list

bqetl_project.yaml
Reverts mozilla/bigquery-etl#7659
The `moz-fx-data-shared-prod.firefox_desktop_stable.sync_v1` table does now exists, so we no longer need to skip it in the generation.
=> Revert "Skip generating event monitoring for sync pings"

bigquery_etl/backfill/parse.py, sql/moz-fx-data-shared-prod/fenix_derived/new_profile_activation_clients_v1/backfill.yaml
The backfill staging table for https://github.com/mozilla/bigquery-etl/pull/7499 is about to expire so this backfill will need to be redone if it's still needed
=> Cancel expired new_profile_activation_clients_v1 backfill

sql/moz-fx-data-shared-prod/monitoring_derived/stable_and_derived_table_sizes_v1/query.py
Fix for https://github.com/mozilla/bigquery-etl/pull/7668.  I forgot to set the default destination_project
=> Set default dest project in stable_and_derived_table_sizes

sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/schema_error_counts_v2/schema.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/structured_missing_columns_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/structured_missing_columns_v1/schema.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/telemetry_missing_columns_v3/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/telemetry_missing_columns_v3/schema.yaml
Adds stable table row counts to the schema error and missing columns tables so they can be used to get affected ping %.
* DENG-7602
=> [DENG-7602] Add ping counts to schema error and missing columns tables

sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_history_v2/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_revised_changelog_v1/query.sql, sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_revised_changelog_v1/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_v2/schema.yaml
SubPlat 3 is setting some additional Stripe subscription metadata fields as workarounds to help us preserve the accuracy of the subscription products reporting in the face of the changes to how SubPlat works.
This PR updates the incremental `stripe_subscriptions_revised_changelog_v1` ETL to save the new metadata fields going forward so we can use them in future updates to the SubPlat ETLs' logic.
* DENG-4218: Update SubPlat ETL to support Stripe multi-currency plans
* DENG-8885: Update SubPlat ETLs to use Stripe subscription attribution metadata
=> feat(SubPlat): Save new Stripe subscription metadata fields (DENG-4218, DENG-8885)

dags.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_item_schedules_updated_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_items_updated_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/dismissed_prospects_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospect_item_feed_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospects_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/rejected_corpus_items_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/scheduled_articles_report_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/stg_reviewed_corpus_items_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/stg_scheduled_corpus_items_v1/metadata.yaml
increases frequency to every hour for DAG that updates models migrated from snowflake. this matches the frequency that was running in DBT.
* DENG-8889
=> feat(DENG-8889): increase snowflake migration DAG frequency to hourly

sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_logical_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/daily_active_service_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/logical_subscription_events_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_logical_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/monthly_active_service_subscriptions_v1/backfill.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/service_subscription_events_v1/backfill.yaml
Initiates backfills of the logical subscription and service subscription tables.
* DENG-976: Apple subscriptions ETL v2
=> chore(SubPlat): Initiate backfills to add historical Apple subscription records to SubPlat consolidated reporting tables (DENG-976)

dags.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/approved_corpus_items/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_item_schedules_updated_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_items_updated_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/curator_actions/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/dismissed_prospects_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospect_item_feed_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/prospects_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/rejected_corpus_items_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/scheduled_articles_report_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/scheduled_corpus_items/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/stg_reviewed_corpus_items_v1/metadata.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/stg_scheduled_corpus_items_v1/metadata.yaml
update DAG & ETL owners for snowflake migrated tables
* DENG-8986
=> fix(DENG-8986): update DAG & ETL owners for snowflake migrated tables

sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_items_updated_v1/backfill.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_items_updated_v1/query.sql
attempt to fix bug in LEFT JOIN and backfill `corpus_items_updated_v1` table.
* DENG-9032
=> fix(DENG-9032): attempt to fix bug in LEFT JOIN and backfill table

sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_items_updated_v1/backfill.yaml
complete backfill of `corpus_items_updated_v1`.
* DENG-9032
=> chore(DENG-9032): complete backfill of corpus_items_updated_v1

sql_generators/events_daily/templates/events_daily_v1/query.sql
This should fix `bqetl_fenix_event_rollup .fenix_derived__events_daily__v1` failing today.
=> Reduce overactive clients threshold in `events_daily_v1` ETLs

sql/moz-fx-data-shared-prod/snowflake_migration_derived/corpus_item_schedules_updated_v1/backfill.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/rejected_corpus_items_v1/backfill.yaml
complete backfills for two snowflake tables
- corpus_item_schedules_updated_v1
- rejected_corpus_items_v1
* DENG-9033
=> chore(DENG-9033): complete backfills for two snowflake tables

sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v1/metadata.yaml, sql/moz-fx-data-shared-prod/fenix_derived/ltv_state_values_v2/checks.sql
* This PR deprecates and un-schedules the build of:`moz-fx-data-shared-prod.fenix_derived.ltv_state_values_v1`
* It also fixes an issue we found, where the checks.sql of the ltv_state_values_v2 table was for some reason referenecing ltv_state_values_v1, so we fixed it to reference ltv_state_values_v2 instead.
* [Bug 1974938](https://bugzilla.mozilla.org/show_bug.cgi?id=1974938)
=> Deprecate & unschedule fenix_derived.ltv_state_values_v1

sql/moz-fx-data-shared-prod/snowflake_migration_derived/dismissed_prospects_v1/backfill.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/dismissed_prospects_v1/query.sql, sql/moz-fx-data-shared-prod/snowflake_migration_derived/scheduled_articles_report_v1/backfill.yaml, sql/moz-fx-data-shared-prod/snowflake_migration_derived/scheduled_articles_report_v1/query.sql
fix ETL bugs and backfill third tier snowflake models
- fixes dismissed_prospects_v1 and scheduled_articles_report_v1
* DENG-9035
=> chore(DENG-9035): fix ETL bugs and backfill third tier snowflake models

bqetl_project.yaml, sql/moz-fx-data-shared-prod/subscription_platform/firestore_stripe_subscriptions_status/view.sql, sql/moz-fx-data-shared-prod/subscription_platform_derived/firestore_stripe_subscriptions_status_v1/metadata.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/firestore_stripe_subscriptions_status_v1/query.sql, sql/moz-fx-data-shared-prod/subscription_platform_derived/firestore_stripe_subscriptions_status_v1/schema.yaml
To allow the status of the Firestore Stripe subscription records to be monitored via Grafana.
This is related to the “[Relay Incomplete Subscriptions](https://mozilla.slack.com/archives/CFBDGQXV5/p1751491690591279)” incident.
* DENG-9071: Surface SubPlat's Firestore Stripe subscription status data in `mozdata` for monitoring
=> feat(SubPlat): Implement `firestore_stripe_subscriptions_status_v1` ETL (DENG-9071)

bigquery_etl/shredder/config.py
Supersedes https://github.com/mozilla/bigquery-etl/pull/7329 - I'm filing a new PR because that one is forked and now has conflicts.
Generated query:
```
DELETE
`moz-fx-data-shared-prod.firefox_desktop_stable.search_with_v1`
WHERE
(
metrics.uuid.search_with_context_id IN (
SELECT
metrics.uuid.contextual_services_context_id
FROM
`moz-fx-data-shared-prod.firefox_desktop_stable.context_id_deletion_request_v1`
WHERE
DATE(submission_timestamp) >= '2025-01-01'
AND DATE(submission_timestamp) < '2025-03-02'
)
OR metrics.uuid.search_with_context_id IN (
SELECT
metrics.uuid.quick_suggest_context_id
FROM
`moz-fx-data-shared-prod.firefox_desktop_stable.quick_suggest_deletion_request_v1`
WHERE
DATE(submission_timestamp) >= '2025-01-01'
AND DATE(submission_timestamp) < '2025-03-02'
)
)
AND …
```
=> Bug 1957735 - Add search-with table to shredder

sql/moz-fx-data-shared-prod/telemetry/firefox_crashes/metadata.yaml
These workgroups aren't in moz-confidential so they can't query the views in `telemetry` by default
* DENG-8594
=> [DENG-8594] Update workgroup access for telemetry.firefox_crashes

sql/moz-fx-data-shared-prod/firefox_desktop/glean_baseline_clients_first_seen/view.sql, sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.query.sql, sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.schema.yaml
This PR adds the following columns to `moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_first_seen_v1`
- `country`
- `distribution_id`
- `windows_build_number`
- `locale`
- `normalized_os`
It also adds these new columns to the view: 
- `moz-fx-data-shared-prod.firefox_desktop.glean_baseline_clients_first_seen`
* [DENG-9078](https://mozilla-hub.atlassian.net/browse/DENG-9078)
[DENG-9078]: https://mozilla-hub.atlassian.net/browse/DENG-9078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9078): Add columns to baseline_clients_first_seen_v1

sql/moz-fx-data-shared-prod/firefox_desktop/baseline_active_users/view.sql
This PR fixes the view `moz-fx-data-shared-prod.firefox_desktop.baseline_active_users` to use aliases for columns since some of these columns are now in multiple tables used in the join, when before they were only in one.
This is related to prior PR https://github.com/mozilla/bigquery-etl/pull/7748 where we added 5 new columns to `moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_first_seen_v1`.
* [DENG-9078](https://mozilla-hub.atlassian.net/browse/DENG-9078)
[DENG-9078]: https://mozilla-hub.atlassian.net/browse/DENG-9078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9078): Follow up fixes, use fully qualified CTE names

bigquery_etl/routine/publish_routines.py
The old pre-v1 workgroup was just deleted. https://mozilla-hub.atlassian.net/browse/SVCSE-3363
* SVCSE-3363
=> chore: switch to v2 workgroup for DE write access

sql/moz-fx-data-shared-prod/subscription_platform_derived/google_subscriptions_changelog_v1/query.sql
To avoid repeatedly adding duplicate Firestore delete operation changelog records.
Fixup for #7750.
* DENG-975: Google subscriptions ETL v2
* https://github.com/mozilla/bigquery-etl/pull/7750
=> fix(SubPlat): Fix join in `google_subscriptions_changelog_v1` ETL (DENG-975)

dags.yaml, sql/moz-fx-data-shared-prod/apple_ads_external/ios_app_campaign_stats_v1/metadata.yaml
This PR deprecates and un-schedules:
- `moz-fx-data-shared-prod.apple_ads_external.ios_app_campaign_stats_v1`
It also deletes the associated DAG `bqetl_ios_campaign_reporting` since this was the only task scheduled using this DAG.
* [DENG-9101](https://mozilla-hub.atlassian.net/browse/DENG-9101)
[DENG-9101]: https://mozilla-hub.atlassian.net/browse/DENG-9101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9101): Deprecate / unschedule apple_ads_external.ios_app_campaign_stats_v1

bigquery_etl/metadata/validate_metadata.py, sql_generators/active_users_aggregates_v3/templates/mobile_view.sql, sql_generators/active_users_aggregates_v4/templates/mobile_view.sql, sql_generators/usage_reporting/templates/usage_reporting_active_users.view.sql.jinja, sql_generators/usage_reporting/usage_reporting.py, tests/cli/test_cli_metadata.py, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/fenix/usage_reporting_active_users/view.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_desktop/usage_reporting_active_users/view.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_ios/usage_reporting_active_users/view.sql
This is related to changes to focus product telemetry data collection changes. This change should enable us to continue measuring the usage of the focus products.
=> feat(DENG-8914): update mobile_view templates inside active_users_aggregates generators so that focus products use composite dataset

sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/query.sql, sql/moz-fx-data-shared-prod/monitoring_derived/bigquery_usage_v2/schema.yaml, sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/query.py, sql/moz-fx-data-shared-prod/monitoring_derived/jobs_by_organization_v1/schema.yaml
I just found out jobs_by_organization doesn't even have a `query` field: https://cloud.google.com/bigquery/docs/information-schema-jobs-by-organization#schema. So moving to bigquery_usage
=> Move is_materialized_view_refresh to bigquery_usage

tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/fenix/composite_active_users/view.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/fenix/usage_reporting_active_users/view.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_desktop/usage_reporting_active_users/view.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_desktop_derived/usage_reporting_clients_last_seen_v1/schema.yaml, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_ios/composite_active_users/view.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_ios/usage_reporting_active_users/view.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/org_mozilla_firefox_beta_derived/usage_reporting_clients_last_seen_v1/schema.yaml, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/org_mozilla_firefox_derived/usage_reporting_clients_last_seen_v1/schema.yaml, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/org_mozilla_ios_firefoxbeta_derived/usage_reporting_clients_last_seen_v1/schema.yaml
[PR-7776](https://github.com/mozilla/bigquery-etl/pull/7776) changed the logic for the views `composite_active_users` & `usage_reporting_active_users` but didn't update the corresponding tests. This PR is a follow up PR to update the corresponding tests to match the new logic.
* [DENG-9112](https://mozilla-hub.atlassian.net/browse/DENG-9112)
[DENG-9112]: https://mozilla-hub.atlassian.net/browse/DENG-9112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(DENG-9112): Update tests for composite_active_users & usage_reporting_active_users

.circleci/workflows.yml, Dockerfile
This should fix the [build error](https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/50793/workflows/e2156eec-be81-4109-93f1-05e1f3bc8ff0/jobs/614600/parallel-runs/0/steps/0-107) occurring because Debian Buster has reached its end of life and its package repositories have been archived.
=> Update Docker base image and CircleCI executor image

sql/moz-fx-data-shared-prod/fenix_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/focus_android_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml, sql/moz-fx-data-shared-prod/focus_ios_derived/usage_reporting_active_users_aggregates_v1/backfill.yaml
Related to https://mozilla-hub.atlassian.net/browse/DENG-9112
This PR backfills the `usage_reporting_active_users_aggregates_v1` derived tables
=> [DENG-9112] Backfill usage reporting AUA v1 derived tables

bqetl_project.yaml
These queries have been timing out in dry run for a while and are creating noise whenever a PR gets merged. Adding them to the dry run skip list for now.
=> Skip dryrun of queries that are timing out

sql_generators/usage_reporting/templates/usage_reporting_active_users_aggregates_v1.query.sql.jinja, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/fenix_derived/usage_reporting_active_users_aggregates_v1/query.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_desktop_derived/usage_reporting_active_users_aggregates_v1/query.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_ios_derived/usage_reporting_active_users_aggregates_v1/query.sql
This PR removes a line no longer needed after https://github.com/mozilla/bigquery-etl/pull/7776. 
* DENG-9112
=> fix usage_reporting_active_users_aggregates

sql_generators/usage_reporting/templates/composite_active_users_aggregates.view.sql.jinja, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/fenix/composite_active_users_aggregates/view.sql, tests/sql_generators/usage_reporting/expected/moz-fx-data-shared-prod/firefox_ios/composite_active_users_aggregates/view.sql
Fixes an additional filter similar to what was done in https://github.com/mozilla/bigquery-etl/pull/7776
Intention is to match the behavior [here](https://github.com/mozilla/bigquery-etl/blob/main/sql_generators/usage_reporting/templates/composite_active_users.view.sql.jinja#L72-L76)
* DENG-9112
=>  fix composite_active_users_aggregates.view.sql.jinja

sql/moz-fx-data-shared-prod/snowflake_migration_derived/dataset_metadata.yaml
add dataEditor access to the `snowflake_migration_derived` dataset.
* DENG-9132
=> chore(DENG-9132): add dataEditor access to snowflake migration dataset

sql/moz-fx-data-shared-prod/firefoxdotcom/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/dataset_metadata.yaml
This PR grants the external-ads-dataproc service account "roles/bigquery.metadataViewer" access to the below 2 datasets: 
- `moz-fx-data-shared-prod.firefoxdotcom`
- `moz-fx-data-shared-prod.firefoxdotcom_derived`
This is needed to finish setting up permissions to switch from the old marketing feed based on mozilla.org to the new feed based on firefox.com. (The old datasets mozilla_org and mozilla_org_derived had the same permissions before).
* [DENG-9073](https://mozilla-hub.atlassian.net/browse/DENG-9073)
[DENG-9073]: https://mozilla-hub.atlassian.net/browse/DENG-9073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Grant external-ads-dataproc SA metadataViewer access to firefoxdotcom & firefoxdotcom_derived

bigquery_etl/glam/generate.py, bigquery_etl/glam/models.py, bigquery_etl/glam/templates/clients_histogram_aggregates_v1.sql, sql/moz-fx-glam-prod/glam_etl/firefox_desktop_glam_release__clients_histogram_aggregates_snapshot_v1/init.sql, sql/moz-fx-glam-prod/glam_etl/org_mozilla_fenix_glam_release__clients_histogram_aggregates_snapshot_v1/init.sql
This PR fixes two things:
1 - Only release `clients_histogram_aggregates` queries read from the snapshot
2 - Adds backticks around the fully qualified table name to avoid bad replacement of project name due to peculiar GNU sed implementation.
=> GLAM ETL fix snapshot

sql/moz-fx-data-shared-prod/pocket_derived/events_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/pocket_usage_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_history_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/spoc_tile_ids_history_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_history_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_v1/metadata.yaml
This PR marks the following tables as deprecated:
* `moz-fx-data-shared-prod.pocket_derived.events_v1`
* `moz-fx-data-shared-prod.pocket_derived.rolling_monthly_active_user_counts_v1`
* `moz-fx-data-shared-prod.pocket_derived.rolling_monthly_active_user_counts_history_v1`
* `moz-fx-data-shared-prod.pocket_derived.spoc_tile_ids_history_v1`
* `moz-fx-data-shared-prod.pocket_derived.twice_weekly_active_user_counts_v1`
* `moz-fx-data-shared-prod.pocket_derived.twice_weekly_active_user_counts_history_v1`
The lineage of what each of these is used in can be seen here: [Pocket Deprecation](https://docs.google.com/document/d/13asqR2f7R0oVl3xwg5gU4phJ8Ei0-OrcFbqaW1tD0bI/edit?usp=sharing)
The goal is to deprecate them for awhile, make sure no one still needs them, before permanently deleting them. …
=> feat(DENG-9088): Deprecate Pocket tables

bqetl_project.yaml, sql_generators/glean_usage/common.py, sql_generators/glean_usage/templates/baseline_clients_daily_v1.metadata.yaml, sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.metadata.yaml, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.metadata.yaml, sql_generators/glean_usage/templates/clients_last_seen_joined.metadata.yaml, sql_generators/glean_usage/templates/metrics_clients_daily.metadata.yaml, sql_generators/glean_usage/templates/metrics_clients_last_seen.metadata.yaml
This PR adds a new config option to glean_usage, called "deprecated_apps".  You can include an "app_id" or "app_name" in bqetl_project.yaml under generate > glean_usage > deprecated_apps.
It uses this config file information to label tables with "deprecated: true".
This change should add this label to the following tables: 
- `moz-fx-data-shared-prod.firefox_reality_derived.metrics_clients_daily_v1`
- `moz-fx-data-shared-prod.firefox_reality_derived.metrics_clients_last_seen_v1`
- `moz-fx-data-shared-prod.firefox_reality_derived.clients_last_seen_joined_v1`
- `moz-fx-data-shared-prod.firefox_reality_pc_derived.metrics_clients_daily_v1`
- `moz-fx-data-shared-prod.firefox_reality_pc_derived.metrics_clients_last_seen_v1`
- `moz-fx-data-shared-prod.firefox_reality_pc_derived.clients_last_seen_ …
=> feat(DENG-9088): Deprecate some glean tables in firefox_reality, firefox_reality_pc, org_mozilla_firefoxreality, & org_mozilla_vrbrowser

sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_product_result_type_v1/backfill.yaml
https://mozilla-hub.atlassian.net/browse/DO-2049
Start backfill for urlbar_events_daily_engagement_by_product_result_type_v1
=> [DO-2049] Backfill urlbar_events_daily_engagement_by_product_result_type_v1

sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_product_result_type_v1/backfill.yaml, sql/moz-fx-data-shared-prod/firefox_desktop_derived/urlbar_events_daily_engagement_by_product_result_type_v1/metadata.yaml
Shredder mitigation is not needed for this dataset and is blocking the backfill.
=> Remove shredder mitigation from urlbar_events_daily_engagement_by_product_result_type_v1

sql/moz-fx-data-shared-prod/firefox_desktop_derived/desktop_retention_clients_v1/query.sql
This PR updates the query logic for `moz-fx-data-shared-prod.firefox_desktop_derived.desktop_retention_clients_v1` to pull from `moz-fx-data-shared-prod.firefox_desktop.glean_baseline_clients_first_seen` rather than `moz-fx-data-shared-prod.firefox_desktop.baseline_clients_first_seen`.
* [DENG-9077](https://mozilla-hub.atlassian.net/browse/DENG-9077)
[DENG-9077]: https://mozilla-hub.atlassian.net/browse/DENG-9077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9077): Update desktop_retention_clients query

dags.yaml
This PR updates 2 DAGs and changes their run times:
- DAG 1: bqetl_desktop_engagement_model (moves from 12 UTC to 5 UTC)
- DAG 2: bqetl_desktop_retention_model (moves from 12 UTC to 5 UTC)
The goal of this change is to make the following 3 tables all finish updating close to each other, since they are all used in the Desktop OKR dashboard.  
- `moz-fx-data-shared-prod.telemetry_derived.desktop_engagement_v1`
- `moz-fx-data-shared-prod.telemetry_derived.desktop_retention_aggregates_v2`
- `moz-fx-data-shared-prod.telemetry_derived.desktop_new_profiles_aggregates_v1` (this DAG starts at 2AM UTC and this task typically finishes around 4AM UTC)
* [DENG-8206](https://mozilla-hub.atlassian.net/browse/DENG-8206) …
=> feat(DENG-8206): Update DAG run times for 2 DAGs

sql/moz-fx-data-shared-prod/firefox_ios_derived/clients_activation_v1/metadata.yaml
=> fix: undeprecate clients_activation_v1 as still in use

sql/moz-fx-data-shared-prod/ads/fakespot_daily_events_rollup/metadata.yaml, sql/moz-fx-data-shared-prod/ads/fakespot_daily_events_rollup/view.sql
The upstream resource has been dropped via: https://github.com/mozilla/bigquery-etl/commit/a894dec99b4ad09f59faa26a8403dc672d6301c3
This is currently causing one of the CI steps to fail.
=> chore: delete ads.fakespot_daily_events_rollup view definition as it is pointing to bq asset that no longer exists

sql_generators/serp_events_v2/templates/desktop_query.sql
This PR adds `partner_code` to `serp_events` as requested in [#7744](https://github.com/mozilla/bigquery-etl/pull/7744)
* [DENG-8178](https://mozilla-hub.atlassian.net/browse/DENG-8178)
[DENG-8178]: https://mozilla-hub.atlassian.net/browse/DENG-8178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add partner code to serp_events

sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_items_daily_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_items_daily_v1/schema.yaml
This PR Adds columns with recommendation details to the newtab_items_daily_v1 table so that editorial team members looking at the New Tab Individual Recommendations dashboard table can quickly understand how specific articles are performing on the New Tab.
* [DENG-9185](https://mozilla-hub.atlassian.net/browse/DENG-9185)
=
[DENG-9185]: https://mozilla-hub.atlassian.net/browse/DENG-9185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add two columns for verifying recommendation data to newtab_items_daily_v1

sql/moz-fx-data-shared-prod/pocket/events/view.sql, sql/moz-fx-data-shared-prod/pocket/rolling_monthly_active_user_counts/metadata.yaml, sql/moz-fx-data-shared-prod/pocket/rolling_monthly_active_user_counts/view.sql, sql/moz-fx-data-shared-prod/pocket/twice_weekly_active_user_counts/metadata.yaml, sql/moz-fx-data-shared-prod/pocket/twice_weekly_active_user_counts/view.sql, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_history_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/rolling_monthly_active_user_counts_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/spoc_tile_ids_history_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_history_v1/metadata.yaml, sql/moz-fx-data-shared-prod/pocket_derived/twice_weekly_active_user_counts_v1/metadata.yaml
This PR un-schedules the data loads of the following tables, which were previously deprecated: 
- `moz-fx-data-shared-prod.pocket_derived.rolling_monthly_active_user_counts_history_v1`
- `moz-fx-data-shared-prod.pocket_derived.rolling_monthly_active_user_counts_v1`
- `moz-fx-data-shared-prod.pocket_derived.twice_weekly_active_user_counts_history_v1`
- `moz-fx-data-shared-prod.pocket_derived.twice_weekly_active_user_counts_v1`
This PR also deletes the following views: 
- `moz-fx-data-shared-prod.pocket.rolling_monthly_active_user_counts`
- `moz-fx-data-shared-prod.pocket.twice_weekly_active_user_counts`
- `moz-fx-data-shared-prod.pocket.events`
* [DENG-9088](https://mozilla-hub.atlassian.net/browse/DENG-9088) …
=> feat(DENG-9088): Unschedule some deprecated Pocket tables

sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_items_daily_v1/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_items_daily_v1/schema.yaml
This PR adds an `authors` column and a `publisher` column to the `newtab_items_daily_v1` table.
* [DENG-9205](https://mozilla-hub.atlassian.net/browse/DENG-9205)
[DENG-9205]: https://mozilla-hub.atlassian.net/browse/DENG-9205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add two more columns to newtab_items_daily_v1 (#9205)

sql/moz-fx-data-shared-prod/bigeye_derived/collection_service_v1/schema.yaml, sql/moz-fx-data-shared-prod/bigeye_derived/metric_service_v1/schema.yaml
This PR is a follow-up fix to [PR-7878](https://github.com/mozilla/bigquery-etl/pull/7878), it fixes the schema.yaml to match the schema existing in production for the new table, `moz-fx-data-shared-prod.bigeye_derived.metric_service_v1`
=> Fix schema metric service

bigquery_etl/glam/clients_daily_scalar_aggregates.py, bigquery_etl/glam/models.py, bigquery_etl/glam/templates/clients_daily_scalar_aggregates_v1.sql
Adds `dual_labeled_counter` metric type type to be processed by the GLAM ETL.
* DENG-9135
=> feat(GLAM ETL): Process dual_labeled_counters

sql/moz-fx-data-shared-prod/firefoxdotcom_derived/ga_sessions_v2/script.sql, sql/moz-fx-data-shared-prod/mozilla_org_derived/ga_sessions_v3/script.sql, sql/moz-fx-data-shared-prod/telemetry/ga4_sessions_firefoxcom_mozillaorg_combined/view.sql
* This PR renames the view `moz-fx-data-shared-prod.telemetry.ga4_sessions_combined` to `moz-fx-data-shared-prod.telemetry.ga4_sessions_firefoxcom_mozillaorg_combined` to be more explicit about which GA4 sites it contains data for.   (After this merges, will delete the old view that was already deployed to production).
* It also adds some comments to the 2 source tables to explain the logic to any future people since it's a bit complicated.
* [DENG-8732](https://mozilla-hub.atlassian.net/browse/DENG-8732)
[DENG-8732]: https://mozilla-hub.atlassian.net/browse/DENG-8732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8732): Rename view to be more explicit & add comments to sessions tables

sql/moz-fx-data-shared-prod/mofo/analytics_321347134_events/metadata.yaml, sql/moz-fx-data-shared-prod/mofo/analytics_321347134_events/view.sql
This PR is removing the view: 
- `moz-fx-data-shared-prod.mofo.analytics_321347134_events`
We will be deleteing this dataset and setting up the extract directly in the new mofo project itself.
=> Remove Mofo GA4 view, moving to separate mofo project

CODEOWNERS
This is required for https://mozilla-hub.atlassian.net/browse/DENG-9290
This PR configures `@mozilla/data-platform-infra-wg` as being required as reviewer for everything except `sql/`, `sql_generators/`, `tests/sql` and `dags.yaml`. The idea is to have more contributors added to the repo with write and review permissions so that they can operate more self-sufficiently without needing a DE to approve and merge their PRs. However, in order to ensure that no critical code gets changed we need to require reviews from DE on these more critical code paths.
=> Set @mozilla/data-platform-infra-wg CODEOWNER on most files, except sql/, sql_generators/, dags.yaml

CODEOWNERS
Use @mozilla/dataplatform-wg in CODEOWNER instead, as it is automatically updated based on the https://protosaur.dev/dawg/workgroup/dataplatform/ workgroup
=> Use @mozilla/dataplatform-wg as CODEOWNER

sql/moz-fx-data-shared-prod/telemetry_derived/newtab_merino_extract_to_gcs_v2/metadata.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_merino_priors_to_gcs_v1/metadata.yaml
Allow ML to look back further into the history of New Tab engagement data stored on GCS for Merino.
* [HNT-929](https://mozilla-hub.atlassian.net/browse/HNT-929)
[HNT-929]: https://mozilla-hub.atlassian.net/browse/HNT-929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(HNT-929): increase expiration of Merino GCS data

bigquery_etl/metadata/publish_metadata.py
Artifact deployment is currently failing due to how we handle config for external (e.g., Google Sheets-backed) tables:
```
File "/app/bigquery_etl/metadata/publish_metadata.py", line 148, in attach_external_data_config
for key, v in metadata.external_data.options.items():
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```
This updates the logic in `attach_external_data_config` to allow for `external_data` metadata that does not include an `options` field (which is an optional field)
I'll add a test in a followup PR.
=> External tables should not require "options" to be set

sql/moz-fx-data-shared-prod/glam_etl/dataset_metadata.yaml, sql/moz-fx-glam-prod/glam_etl/latest_versions/metadata.yaml, sql/moz-fx-glam-prod/glam_etl/latest_versions/schema.yaml, sql/moz-fx-glam-prod/glam_etl/latest_versions/view.sql
Working on [the related ticket](https://mozilla-hub.atlassian.net/jira/software/c/projects/DENG/boards/2647?selectedIssue=DENG-9374) I noticed that I could improve read times on the GLAM app by reading from `latest_versions` instead of querying the aggregates tables for version information. The reason for this whole dance here is that the GLAM app only reads from `moz-fx-data-shared-prod.glam_etl` dataset, so I have to create a view and syndicate it there.  
* DENG-9374
=> chore(glam): Use latest_versions instead of aggregates for version info

dags.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/newtab_clients_daily_v1/metadata.yaml
Add a DAG for bqetl new tab jobs that should specifically run late enough to capture recent activity relative to when editorial arrives at work in those US time zones
This PR runs the update to newtab_clients_daily_v1 about ten hours later in the day than previously, such that the Looker dashboard displaying this data has relatively recent content to show when editorial arrives at work in the UTC-5 time zone to analyze new tab article performance.
* [DENG-9184](https://mozilla-hub.atlassian.net/browse/DENG-9184)
[DENG-9184]: https://mozilla-hub.atlassian.net/browse/DENG-9184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> Collect Newtab Rec Performance Data Closer to When it is Reviewed

sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql
This PR updates the SQL generator for `clients_last_seen_joined_v1` queries to exclude the new column `experiments` which was added to the upstream table `baseline_clients_last_seen_v1`.
This is a follow up fix related to:
* [PR-7978](https://github.com/mozilla/bigquery-etl/pull/7978) - Adding experiments to baseline_clients_daily_v1
* [PR-7983](https://github.com/mozilla/bigquery-etl/pull/7983) - Adding experiments to baseline_clients_last_seen_v1
* [DENG-9445](https://mozilla-hub.atlassian.net/browse/DENG-9445)
[DENG-9445]: https://mozilla-hub.atlassian.net/browse/DENG-9445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> Exclude experiments from clients_last_seen_joined queries

sql/moz-fx-data-shared-prod/firefox_desktop_derived/new_profiles_aggregates_v1/schema.yaml
* This PR is a minor follow-up to [PR-7981](https://github.com/mozilla/bigquery-etl/pull/7981), removing 1 column (city) that was added accidentally at the end of `firefox_desktop_derived.new_profiles_aggregates_v1` that is not needed as it's not a part of the query.
=> fix: Remove incorrect extra column added to new_profiles_aggregates_v1

sql/moz-fx-data-shared-prod/firefox_desktop/cfs_ga4_attr/view.sql, sql/moz-fx-data-shared-prod/telemetry/cfs_ga4_attr/view.sql
This PR adjusts the logic for the 2 views:
- `moz-fx-data-shared-prod.telemetry.cfs_ga4_attr`
- `moz-fx-data-shared-prod.firefox_desktop.cfs_ga4_attr`
Essentially, it changes it so the download token can match on any reported stub session ID / ga client ID / ga session ID combo, instead of just the last stub session ID per GA client ID / ga session ID.
* [DENG-8732](https://mozilla-hub.atlassian.net/browse/DENG-8732)
[DENG-8732]: https://mozilla-hub.atlassian.net/browse/DENG-8732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-8732): Expand matching from DL token to GA4

sql/moz-fx-data-shared-prod/taskclusteretl/dataset_metadata.yaml
This is a no-op PR but will facilitate the work in https://mozilla-hub.atlassian.net/browse/DENG-9313 by making it possible to replace `person_mozilla_com` with an alternate implementation.
* DENG-9313
=> chore(DENG-9313): explicitly syndicate taskclusteretl views

sql/moz-fx-data-shared-prod/fenix_derived/clients_yearly_v1/schema.yaml, sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_events_v1/schema.yaml, sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v1/schema.yaml, sql/moz-fx-data-shared-prod/fenix_derived/feature_usage_metrics_v2/schema.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/baseline_clients_yearly_v1/schema.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v1/schema.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/feature_usage_metrics_v2/schema.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/ltv_ios_aggregates_v1/schema.yaml, sql/moz-fx-data-shared-prod/firefox_ios_derived/tos_rollout_enrollments_v1/schema.yaml, sql/moz-fx-data-shared-prod/org_mozilla_ios_firefox_derived/review_checker_clients_v1/schema.yaml, sql/moz-fx-data-shared-prod/search_derived/mobile_search_clients_last_seen_v1/schema.yaml, sql/moz-fx-data-shared-prod/search_derived/search_clients_daily_v8/schema.yaml, sql/moz-fx-data-shared-prod/telemetry_derived/fx_accounts_active_daily_clients_v1/schema.yaml, sql_generators/glean_usage/templates/baseline_clients_daily_v1.schema.yaml, sql_generators/glean_usage/templates/baseline_clients_first_seen_v1.schema.yaml, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.schema.yaml, sql_generators/glean_usage/templates/event_monitoring_aggregates_v1.schema.yaml, sql_generators/mobile_kpi_support_metrics/templates/attribution_clients.schema.yaml, sql_generators/urlbar_events/templates/schema.yaml
This PR adds column descriptions to tables created by the SQL generators, like: 
- `baseline_clients_last_seen_v1`
- `baseline_clients_daily_v1`
- `baseline_clients_first_seen_v1`
- `event_monitoring_aggregates_v1`
- `attribution_clients_v1`
- `urlbar_events_v1`
It also adds column descriptions to some other tables, such as: 
- `moz-fx-data-shared-prod.search_derived.mobile_search_clients_last_seen_v1`
- `moz-fx-data-shared-prod.search_derived.search_clients_daily_v8`
- `moz-fx-data-shared-prod.fenix_derived.clients_yearly_v1`
- `moz-fx-data-shared-prod.fenix_derived.feature_usage_events_v1`
- `moz-fx-data-shared-prod.fenix_derived.feature_usage_metrics_v1`
- `moz-fx-data-shared-prod.fenix_derived.feature_usage_metrics_v2`
- `moz-fx-data-shared-prod.firefox_ios_derived.baseline_clients_yea …
=> chore(metadata-completeness): Add column descriptions to multiple tables

bigquery_etl/cli/query.py
`bqetl query schema update` no longer creates `schema.yaml` if it doesn't already exist since https://github.com/mozilla/bigquery-etl/pull/7807.  This means new tables with no `schema.yaml` wouldn't get deployed.  This affects some glean_usage tables but there haven't been any new apps in the past month
=> Fix new schemas not being created

sql/moz-fx-data-experiments/monitoring/experimenter_experiments_v1/query.py
Nimbus could use `is_rollout` on the experiments table for validating profiles work. This and the other fields could also be useful generally.
* DENG-9503
=> feat(DENG-9503): add more fields to experiments monitoring table

sql/moz-fx-data-shared-prod/contextual_services_derived/event_aggregates_v1/query.sql
This PR fixes an issue with `event_aggregates` where we see null values for `fenix` data due to pulling from `metadata.user_agent.os` - which is null after version 139 and not the appropriate place to pull from. Being that all of this data is coming from `fenix`, it should all be `Android`
[AD-9356](https://mozilla-hub.atlassian.net/browse/AD-1007?focusedCommentId=1126981&sourceType=mention)
=> AD-9356 fixing issue where os is null after fx version 139

docs/reference/recommended_practices.md
This PR adds where the UDF stub file lives as well as fixing formatting of the stub sql.
* DENG-8576
* DSRE-XXXX
=> deng_8576 add where stub file lives and fix formatting

sql/moz-fx-data-shared-prod/external_derived/macroeconomic_indices_v1/metadata.yaml
Deprecate `external_derived.macroeconomic_indices_v1` table. Data Science has confirmed that this data is no longer in use, and we are not renewing our contract with FinancialModelingPrep (who we get this data from)
=> Deprecate macroeconomic_indices table

sql/moz-fx-data-shared-prod/external/holidays/view.sql
This PR updates the view `mozdata.external.holidays`, and adds the US holiday MLK Jr day to it (and fixes a typo in the date for Orthodox Christmas).
* [DENG-7810](https://mozilla-hub.atlassian.net/browse/DENG-7810)
[DENG-7810]: https://mozilla-hub.atlassian.net/browse/DENG-7810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-7810): Update holidays view

sql/moz-fx-data-shared-prod/external_derived/fred_daily_exchange_rates_v1/metadata.yaml, sql/moz-fx-data-shared-prod/external_derived/fred_daily_exchange_rates_v1/query.py
This PR changes the timing of the DAG to include a larger built in delay, since the FRED API only releases data on a set schedule (for example, by Monday EOD, they typically release the data for the week prior, but this can also be delayed by holidays as well).
* [DENG-9518](https://mozilla-hub.atlassian.net/browse/DENG-9518)
[DENG-9518]: https://mozilla-hub.atlassian.net/browse/DENG-9518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9518): Update delay to account for built in delay in source

sql/moz-fx-data-shared-prod/subscription_platform/daily_active_logical_subscriptions/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform/daily_active_logical_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/daily_active_service_subscriptions/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform/daily_active_service_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/exchange_rates_history/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/logical_subscriptions/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform/logical_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/monthly_active_logical_subscriptions/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform/monthly_active_logical_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/monthly_active_service_subscriptions/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform/monthly_active_service_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/service_subscriptions/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform/service_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/vat_rates_history/view.sql
Monthly/annual recurring revenue projections for logical subscriptions and service subscriptions were originally implemented in Looker views ([example](https://github.com/mozilla/looker-spoke-default/blob/7ba7a8ac6f32d1711058a0a2678e85ac626ce99c/subscription_platform/views/logical_subscriptions.view.lkml#L102-L348)), and this PR implements those same monthly/annual recurring revenue projections in BigQuery views so they are more generally available (not just in Looker).
This PR also adds columns for USD conversions of subscription plan amounts and discount amounts (DENG-9507), and adds `exchange_rates_history` and `vat_rates_history` views to avoid repeating the associated logic.
* DENG-9508: Implement projected monthly/annual revenue for subscriptions in BigQuery
* DENG-9507: Convert …
=> feat(SubPlat): Add revenue columns to logical subscription & service subscription views (DENG-9508)

bqetl_project.yaml, sql/moz-fx-data-shared-prod/taskclusteretl/dataset_metadata.yaml, sql/moz-fx-data-shared-prod/taskclusteretl/person_mozilla_com/metadata.yaml, sql/moz-fx-data-shared-prod/taskclusteretl/person_mozilla_com/view.sql
Extensive background about this change in https://mozilla-hub.atlassian.net/browse/DENG-9313. The original table this syndicate view was referencing stopped updating in Oct. 2024. At some point it will be DE's responsibility to replace this view with something else, but since it's part of the user-facing platform there are considerations for doing that.
The authorization will be handled manually in https://github.com/mozilla-services/cloudops-infra/pull/6558/ since that isn't hooked up to any automation. The full deployment plan will be written in the Jira ticket.
Most DE won't be able to run this query, since you need `workgroup:people` access. You can see the output from the query in an attachment to the Jira ticket.
* DENG-9313 …
=> chore(DENG-9313): replace person_mozilla_com implementation

sql_generators/glean_usage/baseline_clients_last_seen.py, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.query.sql, sql_generators/glean_usage/templates/baseline_clients_last_seen_v1.schema.yaml, sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql
* This PR adds the new column `days_visited_1_uri_bits` to the `baseline_clients_last_seen_v1` tables created by the Glean Usage SQL generator. 
* After this PR is merged, the following PR needs to be merged, to exclude the new column from the downstream tables, `clients_last_seen_joined_v1`, [PR-8051](https://github.com/mozilla/bigquery-etl/pull/8051).
Note: The column `browser_engagement_uri_count` is on many of the SQL generated `baseline_clients_last_seen_v1` tables but it is only really filled in on the desktop one, so when backfilling, will only need to backfill `moz-fx-data-shared-prod.firefox_desktop_derived.baseline_clients_last_seen_v1`. I debated adding it only to Firefox Desktop, but I think in the future, people may want to include it on mobile tables as well, in which case, …
=> feat(DENG-9538): Add column to baseline_clients_last_seen_v1

sql/moz-fx-data-shared-prod/glean_telemetry/active_users/view.sql, sql/moz-fx-data-shared-prod/glean_telemetry_derived/cohort_weekly_active_clients_staging_v1/query.sql
This PR does 2 things.
1. It creates the new view: `moz-fx-data-shared-prod.glean_telemetry.active_users`
2. It is also a follow-up fix to [PR-8039](https://github.com/mozilla/bigquery-etl/pull/8039), fixing the new table `moz-fx-data-shared-prod.glean_telemetry_derived.cohort_weekly_active_clients_staging_v1` so it references this view which is a combination of desktop & mobile data (equivalent to the old `telemetry.active_users`), instead of desktop data only (`firefox_desktop.baseline_active_users`).
* [DENG-9558](https://mozilla-hub.atlassian.net/browse/DENG-9558)
[DENG-9558]: https://mozilla-hub.atlassian.net/browse/DENG-9558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> feat(DENG-9558): Create glean_telemetry.active_users view

sql_generators/glean_usage/templates/clients_last_seen_joined.query.sql
This PR is a follow-up related to [PR-8047](https://github.com/mozilla/bigquery-etl/pull/8047/commits), which added a new column to `baseline_clients_daily_v1` tables.  This PR excludes the new column from being included in the clients_last_seen_joined_v1 tables.
* [DENG-9538](https://mozilla-hub.atlassian.net/browse/DENG-9538)
[DENG-9538]: https://mozilla-hub.atlassian.net/browse/DENG-9538?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9538): Exclude new column from clients_last_seen_joined tables

sql/moz-fx-data-shared-prod/glean_telemetry/active_users/view.sql
This PR makes an update to the view logic for the new view `glean_telemetry.active_users`, excluding the nil client ID.
* [DENG-9558](https://mozilla-hub.atlassian.net/browse/DENG-9558)
* Nil Client ID info: https://datatracker.ietf.org/doc/html/rfc4122.html#section-4.1.7
[DENG-9558]: https://mozilla-hub.atlassian.net/browse/DENG-9558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9558): Exclude nil client ID from active_users view

sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_clients_daily_v2/query.sql, sql/moz-fx-data-shared-prod/firefox_desktop_derived/newtab_clients_daily_v2/schema.yaml
Addition of new metrics and a few computation updates.
New metrics: `cumulative_newtab_visit_duration`
* DENG-9579
=> DENG-9579-new metrics and computation updates

bigquery_etl/cli/monitoring.py, bigquery_etl/metadata/parse_metadata.py
Freshness and volume metrics are currently always added when Bigeye monitoring is enabled for an ETL, with the default freshness metric being non-blocking for downstream Airflow tasks and the default volume metric being blocking for downstream Airflow tasks.
This PR allows us to specify in ETL metadata whether the freshness and volume metrics should be added, and whether those metrics should be blocking or not, with the default behavior still being to add a non-blocking freshness metric and a blocking volume metric.
* DENG-9443: Make BigQuery ETL's Bigeye freshness & volume monitoring configurable
=> feat(monitoring): Make Bigeye freshness & volume monitoring configurable (DENG-9443)

sql/moz-fx-data-shared-prod/bigeye_derived/issue_service_v1/schema.yaml, sql/moz-fx-data-shared-prod/bigeye_derived/metric_service_v1/schema.yaml
These are the new columns I found with:
```python
from pathlib import Path
from bigquery_etl.schema import Schema
prod = Schema.for_table("moz-fx-data-shared-prod", "bigeye_derived", "metric_service_v1")
local = Schema.from_schema_file(Path("sql/moz-fx-data-shared-prod/bigeye_derived/metric_service_v1/schema.yaml"))
prod.compatible(local)
```
* https://bugzilla.mozilla.org/show_bug.cgi?id=1987722
=> Bug 1987722 - Update bigeye_derived schemas

sql_generators/glean_usage/templates/events_stream_v1.query.sql
Currently it appears 56 apps have event pings where the `ping_info.experiments[].value.extra` field is of type `STRUCT<type STRING, enrollment_id STRING>`, while 31 apps have event pings where the `ping_info.experiments[].value.extra` field is of type `STRUCT<enrollment_id STRING, type STRING>`, and for the latter cases the current events stream ETL logic is unfortunately reversing the experiment `type` and `enrollment_id` values (DENG-9632).
This PR fixes the events stream ETL so both flavors of event ping experiments schema are handled properly.
* DENG-9632: Events stream ETL can mix up experiment type and enrollment ID data
=> fix(events_stream): Avoid mixing up experiment `type` and `enrollment_id` data (DENG-9632)

sql/moz-fx-data-shared-prod/stripe_external/customer_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/customer_v1/schema.yaml, sql/moz-fx-data-shared-prod/stripe_external/customers_changelog_v1/query.sql, sql/moz-fx-data-shared-prod/stripe_external/customers_changelog_v1/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_customers_history_v1/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_customers_revised_changelog_v1/query.sql, sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_customers_revised_changelog_v1/schema.yaml, sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_history_v2/schema.yaml
SubPlat is about to add support for additional payment methods for Stripe subscriptions ([PAY-2029](https://mozilla-hub.atlassian.net/browse/PAY-2029)), and which payment method is used for a customer's subscriptions will currently be determined by the customer's [invoice_settings.default_payment_method](https://docs.stripe.com/api/customers/object#customer_object-invoice_settings-default_payment_method) attribute.
This PR updates the SubPlat ETLs to save the customer's `invoice_settings.default_payment_method` attribute and capture any changes to it over time (DENG-9663), so that eventually we can implement a `payment_method` field in downstream SubPlat tables/views (DENG-9664).
* [PAY-2029](https://mozilla-hub.atlassian.net/browse/PAY-2029): Expanded Payment Methods
* DENG-9394: Handle …
=> feat(SubPlat): Save Stripe customer default payment methods (DENG-9663)

.circleci/workflows.yml, bigquery_etl/cli/metadata.py, bigquery_etl/cli/monitoring.py, bigquery_etl/cli/utils.py, bigquery_etl/dependency.py
This PR parallelizes the following commands that run as part of the `generate-sql` CI task:
* `./bqetl dependency record`
* `./bqetl metadata update`
* `./bqetl monitoring update`
This shaves off around 2.5 minutes from the `generate-sql` CI task (e.g. compare with https://app.circleci.com/pipelines/github/mozilla/bigquery-etl/52810/workflows/910fe13d-e797-4b56-964d-4bb9eda82430/jobs/655557).
=> Parallelize dependency record, metadata update, monitoring update (generate-sql CI task)

sql/moz-fx-data-shared-prod/firefox_desktop_derived/enterprise_metrics_clients_v1/query.sql
=> fix: invalid query error (firefox_desktop_derived.enterprise_metrics_clients_v1)

sql/moz-fx-data-shared-prod/firefox_desktop/newtab_content_live/metadata.yaml, sql/moz-fx-data-shared-prod/firefox_desktop/newtab_content_live/view.sql
https://mozilla-hub.atlassian.net/browse/DENG-9707
Add authorized view to firefox_desktop_live.newtab_content_v1 with read access for mozsoc-ml workgroup
=> [DENG-9707] Add authorized view for firefox-desktop/newtab_content

sql/moz-fx-data-shared-prod/firefox_desktop/newtab_content_live/metadata.yaml
https://github.com/mozilla/bigquery-etl/pull/8136/files#r2370422586
Fix metadata.yaml formatting for `authorized: true`
=> Move authorized flag to labels in metadata.yaml

sql/moz-fx-data-shared-prod/firefox_desktop_derived/enterprise_metrics_v1/backfill.yaml
depends on: https://github.com/mozilla/bigquery-etl/pull/8155 (only once the backfill process is completed this PR can be merged)
=> feat: add a backfill 2025-09-23 entry to enterprise_metrics_v1

sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_hits_v1/query.sql, sql/moz-fx-data-shared-prod/firefoxdotcom_derived/www_site_hits_v1/schema.yaml
This PR adds the new column `event_params` to the table & view:
- `moz-fx-data-shared-prod.firefoxdotcom.www_site_hits`
- `moz-fx-data-shared-prod.firefoxdotcom_derived.www_site_hits_v1`
* [DENG-9748](https://mozilla-hub.atlassian.net/browse/DENG-9748)
[DENG-9748]: https://mozilla-hub.atlassian.net/browse/DENG-9748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9748): Add event_params to firefoxdotcom.www_site_hits

sql_generators/firefox_crashes/templates/firefox_crashes.query.sql
The query currently dedupes based on minidump hash per app.  This changes it to look at the union of hashes across all apps.
cc @afranchuk 
* DENG-9684
=> [DENG-9684] Dedupe firefox_crashes across all apps

bqetl_project.yaml, sql_generators/glean_usage/event_monitoring_live.py
I tested and this allows `monitoring.event_monitoring_live` to be deployed from airflow-gke-prod
Removes
- pine
- org_mozilla_fenix_nightly
- org_mozilla_fennec_aurora
- org_mozilla_tv_firefox
- org_mozilla_vrbrowser
- mozilla_lockbox
- org_mozilla_ios_lockbox
- burnham
- org_mozilla_connect
- org_mozilla_firefoxreality
- org_mozilla_bergamot
- firefox_translations
- viu_politica
- treeherder
* https://bugzilla.mozilla.org/show_bug.cgi?id=1990074
=> Bug 1990074 - Exclude deprecated apps from event monitoring

sql/moz-fx-data-shared-prod/firefox_desktop_background_defaultagent_derived/events_stream_v1/backfill.yaml, sql/moz-fx-data-shared-prod/thunderbird_desktop_derived/events_stream_v1/backfill.yaml
I've confirmed this fixes the mixed up experiment type and enrollment ID data in the `events_stream_v1` tables for `firefox_desktop_background_defaultagent` and `thunderbird_desktop` (DENG-9632, #8084).
I also used this as an opportunity to check whether any event extra keys/values were ever actually mismatched in those two apps' `events_stream_v1` records (DENG-9633, #8094), and thankfully I found no evidence of that being a problem in practice.
Completing these managed backfills won't actually fix all the affected `firefox_desktop_background_defaultagent_derived.events_stream_v1` records because the underlying `firefox_desktop_background_defaultagent_stable.events_v1` table's partition expiration is set to 400 days, so it was only possible to backfill back to 2024-08-26, while the bug …
=> fix(events_stream): Complete backfills of two `events_stream_v1` tables that were affected by a bug (DENG-9632)

sql/moz-fx-data-shared-prod/firefox_desktop_derived/metrics_clients_last_seen_v1/schema.yaml, sql_generators/glean_usage/templates/metrics_clients_last_seen.metadata.yaml, sql_generators/glean_usage/templates/metrics_clients_last_seen.query.sql
This PR adds the column `search_with_ads_count_all` to the table and view:
- `moz-fx-data-shared-prod.firefox_desktop_derived.metrics_clients_last_seen_v1`
- `moz-fx-data-shared-prod.firefox_desktop.metrics_clients_last_seen`
I also noticed that the generated `metrics_clients_last_seen_v1` were missing the "depends_on_past: true" labels, so I fixed that in this PR as well.
* [DENG-9792](https://mozilla-hub.atlassian.net/browse/DENG-9792)
[DENG-9792]: https://mozilla-hub.atlassian.net/browse/DENG-9792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9792): Add search_with_ads_count_all to firefox_desktop.metrics_clients_last_seen

sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_logical_subscriptions_history_v1/query.sql
Rather than looking for Stripe invoices with `paypalTransactionId` metadata fields, which doesn't work if the subscription was a trial or used a 100%-off coupon, and thus no PayPal transaction was initiated.
* DENG-9565: Fix some known issues in SubPlat consolidated reporting ETLs
* DENG-9768: Base Stripe logical subscription's `payment_provider` on the Stripe subscription's `collection_method`
=> fix(SubPlat): Base Stripe logical subscription's `payment_provider` on the Stripe subscription's `collection_method` (DENG-9768)

sql/moz-fx-data-shared-prod/subscription_platform_derived/stripe_subscriptions_v2/schema.yaml
Fixup for https://github.com/mozilla/bigquery-etl/pull/7927.
This is causing dry-run failures for the `stripe_subscriptions_v2` ETL.
* DENG-4043: Implement `ended_reason` for logical & service subscriptions
* https://github.com/mozilla/bigquery-etl/pull/7927
=> fix(SubPlat): Correct `schema.yaml` for `stripe_subscriptions_v2` ETL (DENG-4043)

sql/moz-fx-data-shared-prod/braze_external/win10_users_sync_v1/query.sql
Quick fix, braze syncing needs a field as an array.
* DENG-9051
=> fix: subscription_groups must be an array to sync in braze

sql/moz-fx-data-shared-prod/fenix_derived/retention_v1/backfill.yaml
This PR backfills `fenix_derived.retention_v1`. It takes precedence over [this PR]( https://github.com/mozilla/bigquery-etl/pull/8191) because of the date parameters. 8191 did not take into account the 27 day look back for the query and backfilled for the wrong date range.
* DENG-9755
* DSRE-XXXX
=> deng_9755 use future dates to account for 27 day look back

sql/moz-fx-data-shared-prod/fenix_derived/retention_v1/backfill.yaml
This PR starts a backfill to add in data for fenix_derived.retention_v1 for the 2025-04-18 to 2025-04-24
* DENG-9755
* DSRE-XXXX
=> deng_9755 start backfill for 2025-04-18 to 04-24

sql/moz-fx-data-shared-prod/subscription_platform/daily_active_logical_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/daily_active_service_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/logical_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/monthly_active_logical_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/monthly_active_service_subscriptions/view.sql, sql/moz-fx-data-shared-prod/subscription_platform/service_subscriptions/view.sql
Apple and Google each take ~15% of our subscription revenue (DENG-9773).
* DENG-9565: Fix some known issues in SubPlat consolidated reporting ETLs
* DENG-9773: Subtract service fees charged by Apple App Store and Google Play Store from subscription revenue projections
=> fix(SubPlat): Subtract service fees charged by Apple App Store and Google Play Store (DENG-9773)

sql/moz-fx-data-shared-prod/firefox_desktop/glean_baseline_clients_first_seen/view.sql
This PR adds the new column `normalized_app_name` to the view: 
- `moz-fx-data-shared-prod.firefox_desktop.glean_baseline_clients_first_seen`
* [DENG-9793](https://mozilla-hub.atlassian.net/browse/DENG-9793)
[DENG-9793]: https://mozilla-hub.atlassian.net/browse/DENG-9793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9793): Add column to glean_baseline_clients_first_seen

bigquery_etl/shredder/config.py, sql/moz-fx-data-shared-prod/google_ads/glean_conversion_event_categorization/view.sql, sql/moz-fx-data-shared-prod/google_ads_derived/glean_conversion_event_categorization_v1/checks.sql, sql/moz-fx-data-shared-prod/google_ads_derived/glean_conversion_event_categorization_v1/metadata.yaml, sql/moz-fx-data-shared-prod/google_ads_derived/glean_conversion_event_categorization_v1/query.sql, sql/moz-fx-data-shared-prod/google_ads_derived/glean_conversion_event_categorization_v1/schema.yaml
This PR builds the following table & view, which are based off of Glean data instead of legacy telemetry data:
- `moz-fx-data-shared-prod.google_ads_derived.glean_conversion_event_categorization_v1`
- `moz-fx-data-shared-prod.google_ads.glean_conversion_event_categorization`
It also adds the new table to Shredder.
* [DENG-9791](https://mozilla-hub.atlassian.net/browse/DENG-9791)
[DENG-9791]: https://mozilla-hub.atlassian.net/browse/DENG-9791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(DENG-9791): Create google_ads.glean_conversion_event_categorization

bigquery_etl/cli/query.py
Related to https://github.com/mozilla/bigquery-etl/pull/7974 and https://github.com/mozilla/bigquery-etl/pull/8046 which have large backfills that would be simpler in the is_init than in a managed backfill since they can run in a single query.  The current parallelism is fairly high at 10 since it's unlikely to run 10 queries without slot contention, and smaller queries will be fast anyway so parallelism wouldn't matter as much.  Lowering the parallelism to reduce the chances of running out of memory or query timeouts.  Also moving to backfill reservation so it doesn't get in the way of etl if it runs overnight.
=> Lower initialization parallelism and run in backfill slots
